### ISSUE TITLE
shared folders: allow configuration of different destination directory

### ISSUE THREAD

**Issue by pintman** [abraunegg/onedrive#1004]
**Is your feature request related to a problem? Please describe.**

Currently the name of a shared folder conflicts with a onedrive folder name. If there is a directory `~/OneDrive/folder1`, it is not possible to add a shared folder `folder1` as well.

**Describe the solution you'd like**

If shared folders and onedrive-folders are kept in separate directories, no name clashes are possible - e.g. `~/OneDrive` and `~/OneDrive-shared-folders`

**Comment by abraunegg** [comment]
@pintman 
I am assuming here that this is when dealing with OneDrive Business Accounts, as with OneDrive Personal, when you add a shared folder to your OneDrive account, if a folder with the same name already exists, then this gets added with a `(X)` appendage.

If you are talking about OneDrive Business Accounts, please look at using 2 separate configuration directories, one per each local 'OneDrive' root, where each configuration specifies a unique `sync_dir` item - see: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#sync_dir

Please can you clarify your OneDrive account 'use case' here.

**Comment by pintman** [comment]
I'm using a OneDrive Business account. There a no numbers appended when adding a folder named identical to a shared folder. Using separate sync_dirs is kind of a workaround. However, all settings that should apply to both directories must be changed in two locations.

**Comment by abraunegg** [comment]
@pintman 
> There a no numbers appended when adding a folder named identical to a shared folder

Correct - that is a OneDrive Personal Shared Folders feature done 'online'

> Using separate sync_dirs is kind of a workaround. However, all settings that should apply to both directories must be changed in two locations.

Yep .. correct. It is either that, or:
* You change your offending / clashing folder name
* The person sharing the folder with you changes the offending / clashing folder name

Doing what you are wanting to do 'all-in-one' is not possible due to many underlying architectural issues with the client. Flip-flopping between 2 different 'root' directories locally just is not workable.

The *only* options you have are:
* Run 2 separate configurations to achieve what you want, and that would also mean fully excluding the normal OneDrive root data from the 'shared folder' configuration set
* Rename a folder - yours or theirs ...

You need to pick one of these options to resolve your issue.

**Comment by pintman** [comment]
I tried using separate folders and two configs. But when I try to synchronize with
`onedrive --confdir ~/.config/onedrive-shared-folders/ --sync-shared-folders --synchronize`
all non-shared-folders will be synchronized as well. :(

Is there an option to exclude all non-shared-folders?

**Comment by abraunegg** [comment]
@pintman 
> I tried using separate folders and two configs. But when I try to synchronize with
> `onedrive --confdir ~/.config/onedrive-shared-folders/ --sync-shared-folders --synchronize`
> all non-shared-folders will be synchronized as well. :(
> 
> Is there an option to exclude all non-shared-folders?

Please have a good read of https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md specifically:
* skip_dir
* sync_list

**Comment by pintman** [comment]
Yea, I know these options. But they must be adjusted everytime a new folder is added. I was looking for a more general and robust option. I do not know by name if a folder is shared or not.

However, thanks for your support so far. :)

**Comment by abraunegg** [comment]
@pintman 
> Yea, I know these options. But they must be adjusted everytime a new folder is added. I was looking for a more general and robust option. I do not know by name if a folder is shared or not.
> 
> However, thanks for your support so far. :)

OK .. so .. sounds like the best avenue is for you to rename your folder, that you own, on your OneDrive Business account, that sits in the root, that is name clashing ... and preventing the 'shared folder' to be synced locally ... this sounds like your *best* option here  .......

**Comment by pintman** [comment]
Yes, I try to go this way. :)

**Comment by abraunegg** [comment]
Closing issue as question answered
