### ISSUE TITLE
Sharepoint Error in an Enterprise Office 365

### ISSUE THREAD

**Issue by hamdyaea** [abraunegg/onedrive#1005]
Hi,

I try to sync some Sharepoint directories and I always have error messages. 

This is an Enterprise Office 365 Sharepoint.

Can you help me please ?

I have installed the software to sync the SharePoint like they said the instructions and now I try to connect to our Sharepoint :
```
(dmd-2.092.1)[root@XXXXX onedrive]# onedrive --get-O365-drive-id "https://XXX.sharepoint.com/sites/XXXXX/"
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: https://XXXX.sharepoint.com/sites/XXXXX/
ERROR: This site could not be found. Please check it's name and your permissions to access the site.

(dmd-2.092.1)[root@XXXXX]# onedrive --get-O365-drive-id "https://XXXX.sharepoint.com/sites/XXX/Shared Documents/"
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: https://XXXXX.sharepoint.com/sites/XXXX/Shared Documents/
ERROR: This site could not be found. Please check it's name and your permissions to access the site.

(dmd-2.092.1)[root@XXXX onedrive]# onedrive --get-O365-drive-id "https://XXXX.sharepoint.com/sites/XXXX/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000C716F84B1CB646449C17A4B293A65FCE&viewid=c0d29f4d%2D702a%2D46c2%2D824c%2D4a81826ba19d"
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: https://XXX.sharepoint.com/sites/XXX/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000C716F84B1CB646449C17A4B293A65FCE&viewid=c0d29f4d%2D702a%2D46c2%2D824c%2D4a81826ba19d
ERROR: This site could not be found. Please check it's name and your permissions to access the site.

(dmd-2.092.1)[root@XXXX onedrive]# onedrive --get-O365-drive-id "https://XXXX.sharepoint.com"
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: https://XXXXX.sharepoint.com
ERROR: This site could not be found. Please check it's name and your permissions to access the site.
```

**Comment by abraunegg** [comment]
@hamdyaea 

The URL you are using is incorrect - please can you re-read the directions to configure as per https://github.com/abraunegg/onedrive/blob/master/docs/Office365.md#show-how-to-access-a-sharepoint-group-drive-in-office-365-business-or-education

What you need to do is:

1. Login to OneDrive and under 'Shared Libraries' obtain the shared library name

If you have a shared library name called 'Project X' - then:
```
onedrive --get-O365-drive-id 'Projext X'
```

By trying to use the URL (or all of the options you have tried) - this is incorrect and not as per the documentation

**Comment by hamdyaea** [comment]
Hi,

The company Share library is called "Data production".

When I try it I have this error message. 

[root@XXXXX onedrive]# onedrive --get-O365-drive-id 'Data Production'
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: Data Production
ERROR: This site could not be found. Please check it's name and your permissions to access the site.

**Comment by abraunegg** [comment]
@hamdyaea 

Whilst I am not able to replicate your exact issue - a SharePoint site called 'Data Production' is found, please can you test the following PR which enhances the application output when a the requested SharePoint site cannot be found - hopefully then assisting to find the right name for the SharePoint site:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1006/head:pr1006
git checkout pr1006
./configure; make clean; make;
```

Example output when using the PR:
```
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: blah
ERROR: The requested SharePoint site could not be found. Please check it's name and your permissions to access the site.

The following SharePoint site names were returned:
 * Communication site
 * PointPublishing Hub Site
 * Community
 * Team Site
 * Data Production
 * testteamsite2
 * testteamsite
 * All Company
 * mynasau3
```

**Comment by abraunegg** [comment]
@hamdyaea

Please can you respond in regards to testing the PR

**Comment by abraunegg** [comment]
Merging PR to 'master' and closing issue
