### ISSUE TITLE
Skipping uploading this new file as parent path is not in the database

### ISSUE THREAD

**Issue by martiGIT** [abraunegg/onedrive#1007]
### Bug Report Details ###
**Describe the bug**
`Skipping uploading this new file as parent path is not in the database` occurs frequently

**Application and Operating System Details:**
*   OS: Debain 10, docker latest build onedrive v2.4.3-16-g928ad95
*   Headless
*   OneDrive From Office 365 Home
*   Root folder that I'm syncing to is folder shared by another Office 365 Home account

**To Reproduce**
Its hard to reproduce, I have this problem with some of the files in some folders. Its a photos dumps from mobile phone and has the same pattern like android has an an example IMG_20200603_182226.jpg

**Log Output**
A lot of following occurences happen while syncronizing, and they never get sync. Some of the files with the same pattern in the folder got syncronized without any issue, but some of them are not.
```
Skipping uploading this new file as parent path is not in the database: ./Photos/2020/Czerwiec2020/1/IMG_20200623_155006.jpg
```

 I've also checked files permissions or owner, and there is no issue with it (all files have the same owner and permissions)

**Comment by abraunegg** [comment]
@martiGIT 
Please can you follow the directions for generating a debug log for support: https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

What needs to be identified is, why, in your case, the database parent path is not present. A debug log will show what the application is doing and why.

**Comment by abraunegg** [comment]
@martiGIT 
Unable to even trigger this by dumping 2500 random images in random folders / paths of random depths - all files are uploaded without issue, without the message you are seeing.

Please can you:
1. Update your original post with all the required details as per https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md - this is why this exists .. please use it.
2. What sort of hardware are you running Docker on? 
3. What sort of system metrics can you provide about how busy your disk / cpu / memory / network is when this error occurs
4. Generate the verbose debug log as requested so that this can be looked at to determine what is going on and why

**Comment by martiGIT** [comment]
Thanks @abraunegg I will update those data just after I filter out Debug Log from recurring data (Logs with a lot of unimportant data has arount 1GB of size)

**Comment by abraunegg** [comment]
> Thanks @abraunegg I will update those data just after I filter out Debug Log from recurring data (Logs with a lot of unimportant data has arount 1GB of size)

Please do not filter the logs .. what may seem unimportant to you, may actually be important ... please do not do this.

If the log is too large post compression, please provide a link for the file to be downloaded

**Comment by abraunegg** [comment]
Logfile received and feedback provided via email

**Comment by abraunegg** [comment]
@martiGIT 
As per my email, the issue has been identified. Please can you help validate the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1009/head:pr1009
git checkout pr1009
./configure; make clean; make;
```

You will need to manually build a Docker container from this PR in order to test when running in Docker.
