### ISSUE TITLE
Files added to shared folders won´t get uploaded to OneDrive

### ISSUE THREAD

**Issue by humbertogu** [abraunegg/onedrive#1008]
### Bug Report Details ###
**Describe the bug**
Files added to shared folders won´t get uploaded to OneDrive.

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)

> Linux Manjaro-Humberto 5.7.9-1-MANJARO #1 SMP PREEMPT Thu Jul 16 08:20:05 UTC 2020 x86_64 GNU/Linux

*   Are you using a headless system (no gui) or with a gui installed?
No gui

*   OneDrive Account Type
Personal

*   Did you build from source or install from a package?
Installed from [https://aur.archlinux.org/packages/onedrive-abraunegg](https://aur.archlinux.org/packages/onedrive-abraunegg)

*   Application configuration: Output of `onedrive --display-config`

```
onedrive version                       = v2.4.3
Config path                            = /home/humbertogu/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/humbertogu/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

*   Curl Version: Output of `curl --version`
```
curl 7.71.1 (x86_64-pc-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
Copy or move a file to any shared folder, i´m running via systemd

**Application Log Output:**

```
Aug 05 20:18:30 Manjaro-Humberto onedrive[1135]:   Error Message: HTTP request returned status code 400 (Bad Request)
Aug 05 20:18:30 Manjaro-Humberto onedrive[1135]:   Error Reason:  Cannot perform operation within a mounted folder.
Aug 05 20:23:36 Manjaro-Humberto onedrive[1135]: Uploading new file ./TCC/teste ... skipped.
Aug 05 20:23:36 Manjaro-Humberto onedrive[1135]: ERROR: OneDrive returned an error with the following message:
Aug 05 20:23:36 Manjaro-Humberto onedrive[1135]:   Error Message: HTTP request returned status code 400 (Bad Request)
Aug 05 20:23:36 Manjaro-Humberto onedrive[1135]:   Error Reason:  Cannot perform operation within a mounted folder.
Aug 05 20:28:41 Manjaro-Humberto onedrive[1135]: Uploading new file ./TCC/teste ... skipped.
Aug 05 20:28:41 Manjaro-Humberto onedrive[1135]: ERROR: OneDrive returned an error with the following message:
Aug 05 20:28:41 Manjaro-Humberto onedrive[1135]:   Error Message: HTTP request returned status code 400 (Bad Request)
Aug 05 20:28:41 Manjaro-Humberto onedrive[1135]:   Error Reason:  Cannot perform operation within a mounted folder.
```

**Comment by abraunegg** [comment]
@humbertogu 
Please can you update your client to 'master' and re-test as per the support requirements however the error message you are showing is 'odd' - it means that OneDrive is throwing an error - not the application .. it (the OneDrive service) cannot perform an operation against a mounted folder ... not the client.

If you want to use the Arch AUR package to build from 'master', please use https://aur.archlinux.org/packages/onedrive-abraunegg-git or build from source - I would actually suggest you build from source to avoid any package build differences.

If you can still reproduce this after upgrading to 'master', please generate a debug log for analysis using the following process: https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

**Comment by humbertogu** [comment]
@abraunegg 
Thanks for the swift reply,
I'm kind of new to linux, gonna look into how to do the suggested and post the results ASAP.

**Comment by abraunegg** [comment]
@humbertogu 
Potentially this is also a duplicate of #1007 .. but manifesting itself as a 400 error in v2.4.3 that you are using.

Please can you try building from source, but using the following PR:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1009/head:pr1009
git checkout pr1009
./configure; make clean; make;
```

This would then determine if this is the same issue or not.

**Comment by humbertogu** [comment]
@abraunegg 
Tried that and got the same error when running --monitor.
Sending the debug now.

**Comment by abraunegg** [comment]
@humbertogu 
Thanks for that.

What is this 'teste' file locally ? Can you provide some details here on that?

Can you also perform a `--debug-https` debug log - so that I can see exactly what is being sent to / from OneDrive

**Comment by humbertogu** [comment]
@abraunegg 

Its just a txt file i created to try and upload something after i realized it was not doing so, im gonna try to upload something else.
Tryed `onedrive --monitor --debug-https` , sending log now

**Comment by abraunegg** [comment]
@humbertogu 

Thanks for the https log.

When I look at your 'request' URL, your's is formatted as per the following:
```
[DEBUG] Checking file: ./TCC/trying_to_upload.txt
[DEBUG] skip_file evaluation for: /TCC/trying_to_upload.txt
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root:/.%2FTCC%2Ftrying_to_upload.txt:/?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size
```

Whereas, when I am uploading a file to a shared folder, this is my 'request' URL:
```
[DEBUG] Checking file: shared/blah.txt
[DEBUG] skip_file evaluation for: shared/blah.txt
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root:/shared%2Fblah.txt:/?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size
```

Notice the difference here - your file path's have a './' prepended ... which is odd.

Can you please do the following:

1. Rebuild your client from PR #1009 - you should have `onedrive v2.4.3-19-g5b4f354` as your client version
2. Run the client without any service file & do not use --monitor for the moment. Perform a clean sync using `--synchronize --verbose --resync`
3. Files should upload without issue and not error out
4. Retry with using --monitor or service files


If you are still having an issue, please let me know.

**Comment by humbertogu** [comment]
@abraunegg 
Thank you very much,
Files are now uploading with --synchronize, --monitor, and via systemd.

Just a final question, should i stay with this release or can i upgrade when there is a new one, or could i just return to de package version from the AUR?

**Comment by abraunegg** [comment]
@humbertogu 
It would be best to stay with this version until v2.4.4 is released - unsure how or why the AUR package version was not working for you, but also there was a bug identified today in the code with Shared Folders ... not your issue - but .. right now - you have the latest codebase (and no longer have an issue).

Please 'watch' this repo so that you can be notified of when new releases are done - v2.4.4 will be a week away or there abouts. Once you see that release notification, most likely you can go back to the AUR package, or rebuild from source .. thats your choice there.

**Comment by humbertogu** [comment]
@abraunegg 
Great, thanks again for the swift solve.
