### ISSUE TITLE
Cant download-only a --single-directory

### ISSUE THREAD

**Issue by 3ntranced** [abraunegg/onedrive#1012]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
I want to download only files in one directory (50Mb) on one drive. Directory is called Office Lens and its in the Documents folder. 

I issue the following command 
`onedrive --verbose --synchronize --download-only --single-directory 'Documents/Office Lens/'`

For 26 minutes its working, outputting lines like this
```
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Processing 204 OneDrive items to ensure consistent local state
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
```

After its finished my `/mnt/ext/mysync_files/OneDrive/Documents/Office Lens$` is empty.

**Application and Operating System Details:**
*   OS: Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux. Debian 10
*   no gui
*   Personal OneDrive Account
*   Built from source
*   dmd-2.093.0
*   Application configuration: Output of `onedrive --display-config`:

```
Configuration file successfully loaded
onedrive version                       = v2.4.3-18-g786446f
Config path                            = /home/mysync/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /mnt/ext/mysync_files/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 30
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

*   Curl Version: curl 7.64.0

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Run `onedrive --verbose --synchronize --download-only --single-directory 'Documents/Office Lens/'`
2.  wait
3.  Folder is empty

**Comment by abraunegg** [comment]
@3ntranced 
As per the support requirements, please can you provide a full debug log as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

**Comment by abraunegg** [comment]
@3ntranced 
Please can you respond and provide the debug log

Additionally, prior to running the command, was this folder previously in-sync / ever sync'd - or was this the first ever attempt?

**Comment by abraunegg** [comment]
@3ntranced 
I have been able to replicate this scenario, so no debug log needed now.

Please can you test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1014/head:pr1014
git checkout pr1014
./configure; make clean; make;
```
When running the PR version, your client version should be: `onedrive v2.4.3-20-g753bcb4`, and as per the below example, data in the specified scope is downloaded:
```
./onedrive --confdir '~/.config/onedrive-personal/' --verbose --synchronize --download-only --single-directory 'Documents/Images' --resync
Using 'user' Config Dir: /home/alex/.config/onedrive-personal/
Using 'system' Config Dir: 
Configuration file successfully loaded
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.4.3-20-g753bcb4
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709070
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from this selected path: Documents/Images
Syncing changes from selected OneDrive path ...
Getting path details from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!190074
Updated Remaining Free Space: 5368709070
Processing 9 OneDrive items to ensure consistent local state
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Downloading file Documents/Images/image001.jpg ... done.
Number of items from OneDrive to process: 1
```

**Comment by 3ntranced** [comment]
Yes it was my first ever attempt. I followed your instructions, all worked! I ran 
` onedrive --verbose --synchronize --download-only --single-directory 'Documents/Office Lens/' --resync`
27 mins later all files are there. 
Now running 
` onedrive --verbose --monitor --download-only --single-directory 'Documents/Office Lens/'`
and as new file comes in it gets picked up. Thank you.

**Comment by abraunegg** [comment]
@3ntranced 
Thanks for the confirmation that this is fixed. Will merge into 'master'
