### ISSUE TITLE
What the dependencies for Ubuntu 20.04

### ISSUE THREAD

**Issue by zzavatar09** [abraunegg/onedrive#1020]
I install Ubuntu 20.04 on my laptop, and i am a Novice.
I can not find the dependencies for Ubuntu 20.04, is it same as 18.x?

**Comment by abraunegg** [comment]
@zzavatar09 
Your dependencies are listed - please review the documentation again:

https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-ubuntu-18x-ubuntu-19x-ubuntu-20x--debian-9-debian-10---x86_64

**Comment by abraunegg** [comment]
Closing issue as question answered
