### ISSUE TITLE
Can Onedrive only synchronize a specified directory?

### ISSUE THREAD

**Issue by zzavatar09** [abraunegg/onedrive#1022]
Hi,
I want synchronize a specified directory on my Onedrive, but i don't know if it works.

Thanks

**Comment by abraunegg** [comment]
@zzavatar09 
There are two ways to do this:
* Use the `--single-directory' directive
* Configure 'sync_list'

Please review https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md for further details

**Comment by abraunegg** [comment]
Closing issue as question answered
