### ISSUE TITLE
--single-directory ...... no respones

### ISSUE THREAD

**Issue by zzavatar09** [abraunegg/onedrive#1024]
Hi,
I use `onedrive --verbose --synchronize --download-only --single-directory 'pictures/2020 len'` to synchronise my folder, but it doesn't work, and my folder has no change.
```
avatar09@avatar09-ThinkPad-X1-Carbon-4th:~$ onedrive --verbose --synchronize --download-only --single-directory 'pictures/2020 len'
Using 'user' Config Dir: /home/avatar09/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/avatar09/OneDrive
Application version: v2.4.5
Account Type: personal
Default Drive ID: f26072ce7e635a3c
Default Root ID: F26072CE7E635A3C!130
Remaining Free Space: 9088670297
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from this selected path: pictures/2020 len
Syncing changes from selected OneDrive path ...
Getting path details from OneDrive ...
Applying changes of Path ID: F26072CE7E635A3C!23234
Updated Remaining Free Space: 9088670297
avatar09@avatar09-ThinkPad-X1-Carbon-4th:~$ onedrive -h
```

i don't know what's wrong.

Thanks

My  system is ubuntu 20.04, and I install Onedrive as following:
sudo apt install build-essential
sudo apt install libcurl4-openssl-dev
sudo apt install libsqlite3-dev
sudo apt install pkg-config
sudo apt install git
sudo apt install curl
sudo apt install libnotify-dev

**Comment by abraunegg** [comment]
@zzavatar09 
When submitting a new issue, please follow the correct support procedure as outlined here: https://github.com/abraunegg/onedrive#reporting-issues

Your post above is lacking critical details that the [Bug Report](https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md) template requests, such as:
* How did you install - via package or compile?
* If compile, what compiler did you use
* What Curl version are you using
* Verbose Debug Log

All of this is critical to providing timely support, understand if there is a bug & what the application is doing.

From the verbose log above - it is unclear to determine what is going on when the client is scanning OneDrive for changes. 

Please provide a verbose debug log.

**Comment by zzavatar09** [comment]
Hi,

My system is ubuntu 20.04, and I have install any other application. I install Onedrive as following:
sudo apt install build-essential
sudo apt install libcurl4-openssl-dev
sudo apt install libsqlite3-dev
sudo apt install pkg-config
sudo apt install git
sudo apt install curl
sudo apt install libnotify-dev

**Comment by abraunegg** [comment]
@zzavatar09 
Please provide a verbose debug log as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

**Comment by zzavatar09** [comment]
It works well today, I think the reason is that the download speed is slow yesterday.
Thanks
