### ISSUE TITLE
config file not read

### ISSUE THREAD

**Issue by rfindenegg** [abraunegg/onedrive#1025]
Dear people out there, some help would be appreciated with the following:

I want to use a non standard local sync folder. Therefore I copied the config file to ~/.config/onedrive/onedrive.conf, then removed the # and added the correct path. When doing a dry-run the system says no config file is found and it turns to the defaults. Why is that? I'm using version 2.4.3

Thanks for your kind reply
```
onedrive version                       = v2.4.3
Config path                            = /home/reinhard/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/reinhard/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

```
# Configuration for OneDrive Linux Client
# This file contains the list of supported configuration fields
# with their default values.
# All values need to be enclosed in quotes
# When changing a config option below, remove the '#' from the start of the line
# For explanations of all config options below see docs/USAGE.md or the man page.
#
sync_dir = "~/Opslag/OneDrive"
# skip_file = "~*|.~*|*.tmp"
# monitor_interval = "300"
# skip_dir = ""
# log_dir = "/var/log/onedrive/"
# drive_id = ""
# upload_only = "false"
# check_nomount = "false"
# check_nosync = "false"
# download_only = "false"
# disable_notifications = "false"
# disable_upload_validation = "false"
# enable_logging = "false"
# force_http_11 = "false"
# force_http_2 = "false"
# local_first = "false"
# no_remote_delete = "false"
# skip_symlinks = "false"
# debug_https = "false"
# skip_dotfiles = "false"
# dry_run = "false"
# min_notify_changes = "5"
# monitor_log_frequency = "5"
# monitor_fullscan_frequency = "10"
# sync_root_files = "false"
# classify_as_big_delete = "1000"
# user_agent = ""
# remove_source_files = "false"
# skip_dir_strict_match = "false"
# application_id = ""
# resync = "false"
# bypass_data_preservation = "false"
# azure_ad_endpoint = ""
# sync_business_shared_folders = "false"
```

**Comment by abraunegg** [comment]
@rfindenegg 
>  want to use a non standard local sync folder. Therefore I copied the config file to ~/.config/onedrive/onedrive.conf, then removed the # and added the correct path.

I am unsure on what documentation steps you are following, however your issue is directly related to you copying the default config file to 'onedrive.conf'. If you have been following a guide on the Internet, best advise the author to update their page with the right details.

To solve your issue, if you rename this file to 'config' , the client should then detect your configuration file and display the correct configuration you are expecting when you use `--display-config`. This will be the same for when you are using `--dry-run` and any client operations.

Additionally, v2.4.3 is out of date, please upgrade your client to v2.4.5.

**Comment by rfindenegg** [comment]
Thank you!

 I'm afraid I didn't read closely enough. I was using the official guide from github. But it works now!

**Comment by abraunegg** [comment]
Closing issue as question answered and resolved
