### ISSUE TITLE
Feature Request: Support Microsoft Information Protection

### ISSUE THREAD

**Issue by n-hebert** [abraunegg/onedrive#1026]
**Is your feature request related to a problem? Please describe.**
Some organizations require higher levels of confidentiality classification than the current client supports.
When Microsoft's MIP is enabled for OneDrive, this client is not provably compliant with these protections.

***Links***
* Microsoft: https://www.microsoft.com/en-us/security/business/information-protection
* Microsoft Tech Community: https://techcommunity.microsoft.com/t5/microsoft-security-and/microsoft-information-protection-amp-compliance-preview-programs/ba-p/1224776
* Relevant article: https://mspoweruser.com/microsoft-rolls-out-sensitivity-labels-to-onedrive-and-sharepoint/

**Describe the solution you'd like**
The onedrive client should be enhanced to either prove MIP functionality already exists or provide it if it is missing.

**Describe alternatives you've considered**
Alternatives are to use the web browser but it is extremely sub-par for those writing many files. 
We would lose more time in a day than it would be worth.

**Additional context**
![image](https://user-images.githubusercontent.com/68243838/90540704-f8280c80-e157-11ea-97d5-58ad5d5a29d1.png)

**Comment by abraunegg** [comment]
@n-hebert 
Many thanks for requesting a feature like this, however it will not be possible to implement.  

MIP or more commonly known as Azure Information Protection only supports the following operating systems:
* https://docs.microsoft.com/en-us/azure/information-protection/requirements#supported-operating-systems-for-client-devices

Essentially - this is a Windows only feature.

Additionally, the embedded security labels can only be utilised by the following applications, either via Office365 online or installed locally:
* https://docs.microsoft.com/en-us/azure/information-protection/requirements#applications

Unfortunately unless there is a way to support this in the client.

**Comment by abraunegg** [comment]
Closing issue - cannot be implemented - Windows ecosystem only

**Comment by n-hebert** [comment]
Hello @abraunegg ,

I took a look over here https://docs.microsoft.com/en-us/information-protection/develop/setup-configure-mip and it looks like AIP was the old and MIP is the new.
There are SDK packages for Linux.

Could you re-evaluate this request?

**Comment by abraunegg** [comment]
@n-hebert 
I have reviewed the new information, however my existing position still stands.

If you feel this should not be the case, please pick up the torch and develop an applicable PR to provide this feature.

**Comment by abraunegg** [comment]
reopening this issue so thread is visible

**Comment by abraunegg** [comment]
Closing this feature request for the following reason:
* Unable to support
