### ISSUE TITLE
Option to just download a single directory or file

### ISSUE THREAD

**Issue by gapf2010** [abraunegg/onedrive#1027]
**Is your feature request related to a problem? Please describe.**
Some times, it's just useful to download some files (or a directory) from OneDrive to the local disk. No need to sync changes or the file/directory to previously exist on the local drive, just be able to download a list of files. I found about "sync_list" but that requires modifying the config and doing a full synchronization, which is not ideal (IMO).

**Describe the solution you'd like**
Just using this command: "onedrive --synchronize --single-directory --download-only my-dir" should download the directory "my-dir" (which obviously does exist on my OneDrive) from OneDrive to the local disk on my PC. Currently, if I run this command it complains because the local directory ~/OneDrive/my-dir does not exist:
```
[user@laptop ~]$ onedrive --synchronize --single-directory --download-only my-dir
Initializing the Synchronization Engine ...
ERROR: The requested local directory does not exist. Please check ~/OneDrive/ for requested path
[user@laptop ~]$ 
```
If I create an empty directory "~/OneDrive/my-dir"  and run the same command with "--verbose" then I get this:
```
[user@laptop ~]$ onedrive --synchronize --single-directory --download-only --verbose my-dir
Using Config Dir: /home/gpulido/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/gpulido/OneDrive
Application version: v2.4.2
Account Type: personal
Default Drive ID: 198b1db90d811d51
Default Root ID: 198B1DB90D811D51!121
Remaining Free Space: 31129946763
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from this selected path: bootdisks
Syncing changes from selected OneDrive path ...
Getting path details from OneDrive ...
Applying changes of Path ID: 198B1DB90D811D51!100387
Processing 234 OneDrive items to ensure consistent local state
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
...
[user@laptop ~]$ 
```
The last message gets repeated "ad infinitum" apparently (I waited about 20 minutes and continued to appear, had to stop the sync with Ctrl+C).

Thanks!

**Comment by abraunegg** [comment]
@gapf2010 
There are 2 things at play here:
1. Local path not existing before attempting command
2. Remote change discarded messages

With the first point, yes, this could be improved, and if the local path does not exist, create it, rather than error out.

With the second point - you are running v2.4.2 which has a few issues that have been fixed in regards to `--single-directory` operation. Please upgrade your client to v2.4.5.

**Comment by gapf2010** [comment]
@abraunegg 

Thanks for the reply. I am using the latest verion on Fedora repos, guess I'll have to compile version 2.4.5 myself and try again. Anyway, my main issue is with the first point you mentioned: if the local directory does not exist, then onedrive should create it and download it, that would be great, IMO.

**Comment by abraunegg** [comment]
@gapf2010 
Refer to https://koji.fedoraproject.org/koji/packageinfo?packageID=26044 for Fedora packages - as v2.4.5 is available on Fedora. If not or your version, email the maintainer to ensure your Fedora version is supported.

**Comment by abraunegg** [comment]
@gapf2010 
Please can you test the following PR to assist with looking at this issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1031/head:pr1031
git checkout pr1031
./configure; make clean; make;
```

When testing, if you still have an issue, please can you generate a verbose debug log as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

Example when testing locally:
```
./onedrive --confdir '~/.config/onedrive-business/' --synchronize --single-directory 'asdf/jsjs ewjsj' --download-only
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
WARNING: The requested path for --single-directory does not exist locally. Creating requested path within /home/alex/OneDriveBusiness
Syncing changes from selected OneDrive path ...
ERROR: The requested single directory to sync was not found on OneDrive
```
On second run, no warning, the local directory was correctly created in the above step:
```
./onedrive --confdir '~/.config/onedrive-business/' --synchronize --single-directory 'asdf/jsjs ewjsj' --download-only
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from selected OneDrive path ...
ERROR: The requested single directory to sync was not found on OneDrive
```
