### ISSUE TITLE
ERROR: OneDrive account currently has zero space available.

### ISSUE THREAD

**Issue by stylersnico** [abraunegg/onedrive#1028]
**Bug Report Details**

Hello, 

When I try to sync shared library the following error show up:

```
onedrive --confdir="/home/nicolas/.config/onedrive/config-xxx" --synchronize --verbose
Using 'user' Config Dir: /home/nicolas/.config/onedrive/config-xxx
Using 'system' Config Dir: 
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/nicolas/OneDrive-xxx/
ERROR: OneDrive account currently has zero space available. Please free up some space online.
Application version: v2.4.5
Account Type: documentLibrary
Default Drive ID: ID1
Default Root ID: ID2
Remaining Free Space: 0
```

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
```
OS: Manjaro 20.1 Mikah
Kernel: x86_64 Linux 5.7.14-1-MANJARO
Shell: bash 5.0.18
DE: KDE 5.73.0 / Plasma 5.19.4
Disk: 199G / 464G (46%)
```

*   Are you using a headless system (no gui) or with a gui installed?
Gui, KDE but headless onedrive client

*   OneDrive Account Type
Microsoft 365 Business with personnal OneDrive and two shared library

*   Did you build from source or install from a package?
Using this: https://aur.archlinux.org/packages/onedrive-abraunegg-git

*   Application configuration: Output of `onedrive --display-config`
```Configuration file successfully loaded
onedrive version                       = v2.4.5
Config path                            = /home/nicolas/.config/onedrive/config-xxx
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/nicolas/OneDrive-xxx/
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'drive_id'               = b!Vek6purgUU2GnbfHr4JttDSjVgONrYdMlrXp6ofTshPE4OimSyezQK4zhfkU9NRc
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

*   Curl Version: Output of `curl --version`
```
curl 7.71.1 (x86_64-pc-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Setup a config for a shared Document Library
2.  Sync
3.  See that the free space is 0

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --confdir="/home/nicolas/.config/onedrive/config-xxx" --synchronize --verbose
Using 'user' Config Dir: /home/nicolas/.config/onedrive/config-xxx
Using 'system' Config Dir: 
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/nicolas/OneDrive-xxx/
ERROR: OneDrive account currently has zero space available. Please free up some space online.
Application version: v2.4.5
Account Type: documentLibrary
Default Drive ID: ID1
Default Root ID: ID2
Remaining Free Space: 0
```

**Additional context**
I have 3 onedrive config
The first one for my personnal sharepoint drive works well
The two other, for shared document library worked fine for months but stopped both 1 week ago.

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output

Thanks for the help :)

**Comment by abraunegg** [comment]
@stylersnico 
Thanks for the bug report

> See that the free space is 0

OK .. this due to the fact that the OneDrive API returns zero data for space remaining for the following:
* Personal Shared Folders
* Business Shared Folders
* Document Libraries

Will have to double check what is doing on, as, the code changes made with https://github.com/abraunegg/onedrive/commit/5907d9eb0a07386bca2aa1069a081d8d6676a5b4 should not have impacted operations - just updated how everything was being tracked.

I should be able to look into this later tonight, as replicating this should be fairly straight forward.

**Comment by stylersnico** [comment]
Thanks for your work :) 

Let me know if you want another log or if you want some test

**Comment by abraunegg** [comment]
@stylersnico 
In attempting to replicate this issue, when I use a `documentLibrary` , I get values returned from the API for free space as per below:
```
Using 'user' Config Dir: /home/alex/.config/onedrive-business/
Using 'system' Config Dir: 
Configuration file successfully loaded
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Application version: v2.4.5
Account Type: documentLibrary
Default Drive ID: b!ih5JL2-ujEmoAttncU-wUtRLy2CjX7BPsWFbPI6OIrmHAThv9jtNTJZKYgSGm4bw
Default Root ID: 01ACNMGWV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 27487789136280
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 01ACNMGWV6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 27487789136280
Number of items from OneDrive to process: 4
Skipping item - excluded by skip_file config: ~tmp6C_newfile-centos7full.txt
Uploading differences of ~/OneDriveBusiness
Processing .
The directory has not changed
Processing newfile-centos7full.txt
The file has not changed
Processing newfile.txt
The file has not changed
Uploading new items of ~/OneDriveBusiness
Applying changes of Path ID: 01ACNMGWV6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 27487789136280
```

So potentially, in your situation, this data is actually being restricted, rather than 0, so the messaging will need to be updated.

**Comment by abraunegg** [comment]
@stylersnico 

Please can you test the following PR to assist with looking at this issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1029/head:pr1029
git checkout pr1029
./configure; make clean; make;
```

When testing, if you still have an issue, please can you generate a verbose debug log as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

**Comment by stylersnico** [comment]
> So potentially, in your situation, this data is actually being restricted, rather than 0, so the messaging will need to be updated.

Yes it may be that, I'm actually a low rights user of these library



> @stylersnico
> 
> Please can you test the following PR to assist with looking at this issue:
> 
> ```
> git clone https://github.com/abraunegg/onedrive.git
> cd onedrive
> git fetch origin pull/1029/head:pr1029
> git checkout pr1029
> ./configure; make clean; make;
> ```
> 
> When testing, if you still have an issue, please can you generate a verbose debug log as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

It works and I have the same warning that I had before: 
WARNING: OneDrive quota information is being restricted or providing a zero value. Please fix by speaking to your OneDrive / Office 365 Administrator.

Thanks a lot :1st_place_medal:

**Comment by abraunegg** [comment]
@stylersnico 
Thanks for the confirmation - and no issues with uploading data - all OK?

**Comment by stylersnico** [comment]
Yes, everything works fine so far
