### ISSUE TITLE
Ondrive authentication error

### ISSUE THREAD

**Issue by sammybigboy440** [abraunegg/onedrive#1035]
when i try to do an authentication, i get the error message below

```
onedrive.OneDriveException@src/onedrive.d(874): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "c144f102-4327-4d4c-b0c0-**************",
    "error": "invalid_grant",
    "error_codes": [
        70000
    ],
    "error_description": "AADSTS70000: The provided value for the 'code' parameter is not valid.\r\nTrace ID: 5bc935d8-0d03-4858-9323-***********\r\nCorrelation ID: c144f102-4327-4d4c-b0c0-***********\r\nTimestamp: 2020-08-25 01:12:49Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=70000",
    "timestamp": "2020-08-25 01:12:49Z",
    "trace_id": "5bc935d8-0d03-4858-9323-****************"
}
----------------
??:? [0x5618379ec9d9]
??:? [0x5618379ebcb5]
??:? [0x5618379ecb65]
??:? [0x5618379eaf58]
??:? [0x5618379ea8c5]
??:? [0x5618379f87a8]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7f4e4be389db]
??:? _d_run_main2 [0x7f4e4be387ee]
??:? _d_run_main [0x7f4e4be3865d]
??:? __libc_start_main [0x7f4e4ba240b2]
??:? [0x5618379c35ed]
```

**Comment by abraunegg** [comment]
@sammybigboy440 
I will update this more shortly, however, most likely this because you are a Ubuntu user and just ran: `apt install onedrive` - this is not supported.

Please update your post above with ALL the required information as per the support process as detailed here: https://github.com/abraunegg/onedrive#reporting-issues

**Comment by abraunegg** [comment]
This is the same issue as https://github.com/abraunegg/onedrive/issues/1034

You are running an obsolete version. Your choices are:

1.	Build from source
2.	Use the Ubuntu PPA - https://launchpad.net/~yann1ck/+archive/ubuntu/onedrive (This gets updated when Debian packages are updated)

If I were you – remove the ‘onedrive’ package via ‘apt remove onedrive’ and then build from source. The instructions are very clear and easy to follow

**Comment by abraunegg** [comment]
Closing issue - old code version, Ubuntu install
