### ISSUE TITLE
Feature Request: Create shareable link

### ISSUE THREAD

**Issue by jugglerchris** [abraunegg/onedrive#1040]
**Is your feature request related to a problem? Please describe.**
I would sometimes find it useful to put a file into OneDrive on a Linux machine and conveniently get a link to that file which I could share with others (say an image or something), without having to go through the OneDrive web interface to do so.

**Describe the solution you'd like**
A new option like `--get-file-link` (say `--get-share-file-link`) but which creates a shared link which can be viewed without a MS account - as in what you can get from the "Share" option on the web interface.

**Describe alternatives you've considered**
The alternative is taking the link from `--get-file-link`, opening in a browser, clicking share -> link -> ... and copying the new link, then pasting it wherever it's going.

**Additional context**
I don't know if this is even possible, sorry - but if it is it would be convenient for me.  :-)

**Comment by abraunegg** [comment]
@jugglerchris 
Thanks for the feature request. The OneDrive API provides this capability, however there are a few more details that need to be considered here such as:
* read only or full access
* anonymous access or named accounts

Thus, creating the share link would require additional inputs for the type of share link needed to be created.

**Comment by jugglerchris** [comment]
For my particular use case, I'd just want a read only link that doesn't need a OneDrive account to open.  And ideally a link to the actual file rather than the OneDrive UI around it - again I don't know if that's possible.

I would want to use it to drop an image or PDF in to the drive, and send a link to some other device (not necessarily mine) to open it, rather than doing anything more interactive with the file.

**Comment by abraunegg** [comment]
@jugglerchris 
Thanks for the info - doing something like that should then be fairly straight forward if just assuming read-only anonymous access

**Comment by abraunegg** [comment]
@jugglerchris 

Please can you test the following PR to hopefully implement this feature:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1061/head:pr1061
git checkout pr1061
./configure; make clean; make;
```

When running the PR version, your client version for PR1061 should be `onedrive v2.4.5-12-g1195e1d` or greater.

When using the PR, below is an example of the output:
```
(dmd-2.092.0)[alex@centos7full fix-issue-1040]$ ./onedrive --confdir '~/.config/onedrive-personal/' --create-share-link file1.txt
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
File Shareable Link: https://1drv.ms/t/s!<redacted>
(dmd-2.092.0)[alex@centos7full fix-issue-1040]$ ./onedrive --confdir '~/.config/onedrive-personal/' --create-share-link /file1.txt
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
File Shareable Link: https://1drv.ms/t/s!<redacted>
(dmd-2.092.0)[alex@centos7full fix-issue-1040]$ 
(dmd-2.092.0)[alex@centos7full fix-issue-1040]$ ./onedrive --confdir '~/.config/onedrive-personal/' --create-share-link random_files/EKP9AGkht4XU6jFs9k8yWuesv0mCOmpo/file4.data
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
File Shareable Link: https://1drv.ms/u/s!<redacted>
(dmd-2.092.0)[alex@centos7full fix-issue-1040]$ ./onedrive --confdir '~/.config/onedrive-personal/' --create-share-link /random_files/EKP9AGkht4XU6jFs9k8yWuesv0mCOmpo/file4.data
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
File Shareable Link: https://1drv.ms/u/s!<redacted>
```

**Comment by jugglerchris** [comment]
I can confirm that works, awesome!

A couple of minor things:

1. It would be useful to (maybe optionally) only print the link to stdout so that it can be more easily piped into another program.
2. The URL links to a page with the file shown within the OneDrive UI.  Is it possible to get a URL equivalent to what you get from "View original" or "Download", i.e. that returns just the file itself?  I can see that either would be useful in different contexts!

This is already very useful to me - the above would just be minor improvements.

Thanks for doing this!

**Comment by abraunegg** [comment]
> I can confirm that works, awesome!
> 
> A couple of minor things:
> 
> 1. It would be useful to (maybe optionally) only print the link to stdout so that it can be more easily piped into another program.

The link is already going to stdout, but to make it informative, which is why the prefix on that line exists. The other output is due to wider other application use, thus can't be easily changed.

> 2. The URL links to a page with the file shown within the OneDrive UI.  Is it possible to get a URL equivalent to what you get from "View original" or "Download", i.e. that returns just the file itself?  I can see that either would be useful in different contexts!

Unfortunately there is zero option here - the API returns the provided URL. Such enhancement would require a modification by Microsoft to the API - sorry.

> 
> This is already very useful to me - the above would just be minor improvements.
> 
> Thanks for doing this!

Glad that this will be useful.

**Comment by jugglerchris** [comment]
Thanks, that all makes sense!
