### ISSUE TITLE
Notification when authentification has expired due to corp. policies

### ISSUE THREAD

**Issue by benjuy** [abraunegg/onedrive#1042]
Every other week I have to re-authorize the onedrive client due to "`policies configured by `[my] `administrator`". It would be nice to have a notification when this is needed. OneDrive throws an error `400 (bad request)` in those occasions, when I want to `--display-sync-status`, as well as a `401 (Unauthorized)`, reason: `Access token is empty`.

A notification would be nice. (Even better would be an automatic `logout` and `systemctl --user stop onedrive`, but I see that this is no general solution, as not everyone is running it as a service.)

Multi-factor (authenticator app) along with the "company portal app" is required in my case.

**Comment by abraunegg** [comment]
@benjuy 
There is no easy way to solve this.

When your credentials are invalid, OneDrive throws the 400 error and the 401 Unauthorised .. This is trapped and correctly handled - and you get the notification that this has occurred .. 

There is no way to display or query or present anything other than what is done today when your password expires.

If you feel this is not the case, please provide a full verbose debug log for each scenario you are talking about, so that I can walk through what the log is saying & what potentially any enhancement could be - if any.

**Comment by abraunegg** [comment]
@benjuy 
When not using a service / daemon the following is provided when the account password is changed:
```
Using 'user' Config Dir: /home/alex/.config/onedrive-business/
Using 'system' Config Dir: 
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2020-07-31T10:28:07.9262664Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2020-08-23T21:01:38.0000000Z'.
Trace ID: eb6453c2-c902-45bb-a590-4d6d348c0400
Correlation ID: e8196108-d554-4949-8e4b-c333aac7137e
Timestamp: 2020-08-28 21:38:22Z

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 401 (Unauthorized)
  Error Reason:  Access token is empty.

ERROR: Check your configuration as your refresh_token may be empty or invalid. You may need to issue a --logout and re-authorise this client.
```

Similar error messages would be printed to the systemd log file / system log file indicating this is the issue.

Without further evidence as to what you are seeing based on your actual log files, there is not much else that can be done as this level of notification is more than enough to advise you need to issue a `--logout` and re-authenticate.

If you are not seeing this level of detail:
1. Upgrade your client
2. Increase your client logging verbosity

**Comment by benjuy** [comment]
Thank you very much for your instant reply! My "questions" is rather if there is a possibility to get a GUI notification about these errors. Because it happened to me that I didn't realise that OneDrive isn't syncing anymore and was then a bit surprised that some files were "missing" on other machines. 

If not, I might include the command to open a terminal and give it a `onedrive --display-sync-status` in my startup script as a workaround.

**Comment by abraunegg** [comment]
@benjuy 
Thanks for the clarification on your use-case / scenario.

Please can you test the following PR to hopefully resolve this issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1046/head:pr1046
git checkout pr1046
./configure --enable-notifications; make clean; make;
```

You will need to ensure that you also install the dependencies for enabling notifications if you have not already done so.

What should occur is, on password change / expiry, one of the following GUI notifications should be displayed:
* ERROR: Refresh token invalid, use --logout to authorize the client again.
* ERROR: Check your configuration as your refresh_token may be empty or invalid. You may need to issue a --logout and re-authorise this client.

Please can you test and advise.

**Comment by benjuy** [comment]
Thank you very much - that went through smoothly. Now, I assume, I have to wait until it logs my client out from the company side - or is there a way to "simulate" the same log-out due to a needed re-authentication?

**Comment by abraunegg** [comment]
@benjuy 
Changing your corp password would have the same effect

**Comment by abraunegg** [comment]
@benjuy 
Any update here ?

**Comment by benjuy** [comment]
I'm very sorry, I know you have this pending, but I cannot easily change my Corp password, I simply have to wait. Should be due this week actually! I'll report back ASAP.

**Comment by benjuy** [comment]
Ok, it actually was due today - but I didn't got a notification. 

`~ >>> onedrive --display-config                                           [255]
Configuration file successfully loaded
onedrive version                       = v2.4.5
Config path                            = /home/manj/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/manj/OneDrive
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
`

The log-file only logged

`2020-Sep-12 11:32:35.5823104	Configuring Global Azure AD Endpoints
2020-Sep-12 11:32:35.5825657	
--synchronize or --monitor switches missing from your command line input. Please add one (not both) of these switches to your command line or use --help for further assistance.
2020-Sep-12 11:32:35.582612	No OneDrive sync will be performed without one of these two arguments being present.`

Please tell me, if I can provide you with any further information. Thank you for your commitment and this nice client. :)

**Comment by abraunegg** [comment]
@benjuy 
```
onedrive version                       = v2.4.5
```


You are not actually running the PR version.

When running the PR version, your client version for PR1046 should be `onedrive v2.4.5-10-g83eff17`

Additionally, the notifications should be sent to the log file & the GUI if you are running as a service / in `--monitor` mode. From the log file above it looks like you just ran it as 'onedrive' expecting it to tell you your credentials were invalid ... incorrect application use there.

Please make sure that you are using the right version:

* Stop any running service
* Compile the PR
* Test the PR
* Install the PR post your testing
* Validate you are running the PR version by issuing `onedrive --version`
* Start any service file  / services you may have

**Comment by benjuy** [comment]
How can I switch to this version? I did the following:

```
systemctl --user stop onedrive  

~ >>> git clone https://github.com/abraunegg/onedrive.git                                                                                                                                                         
cd onedrive
git fetch origin pull/1046/head:pr1046
git checkout pr1046
./configure --enable-notifications; make clean; make;

Cloning into 'onedrive'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 4038 (delta 14), reused 1 (delta 0), pack-reused 4011
Receiving objects: 100% (4038/4038), 2.76 MiB | 5.37 MiB/s, done.
Resolving deltas: 100% (2780/2780), done.
From https://github.com/abraunegg/onedrive
 * [new ref]         refs/pull/1046/head -> pr1046
Switched to branch 'pr1046'
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.093.1
checking for curl... yes
checking for sqlite... yes
checking for notify... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
	git describe --tags > version ; \
else \
	echo v2.4.6-dev > version ; \
fi
dmd -w -g -O -J. -version=NoPragma -version=NoGdk -version=Notifications -L-lcurl -L-lsqlite3 -L-lnotify -L-lgdk_pixbuf-2.0 -L-lgio-2.0 -L-lgobject-2.0 -L-lglib-2.0 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d src/notifications/notify.d src/notifications/dnotify.d -ofonedrive

~/onedrive >>> sudo make install      
                                                                                                                                                                
/usr/bin/install -c -D onedrive /usr/local/bin/onedrive
/usr/bin/install -c -D onedrive.1 /usr/local/share/man/man1/onedrive.1
/usr/bin/install -c -D -m 644 contrib/logrotate/onedrive.logrotate /usr/local/etc/logrotate.d/onedrive
mkdir -p /usr/local/share/doc/onedrive
/usr/bin/install -c -D -m 644 README.md config LICENSE CHANGELOG.md docs/Docker.md docs/INSTALL.md docs/Office365.md docs/USAGE.md docs/BusinessSharedFolders.md /usr/local/share/doc/onedrive
/usr/bin/install -c -d -m 0755 /usr/lib/systemd/user /usr/lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive@.service /usr/lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive.service /usr/lib/systemd/user

~/onedrive >>> onedrive --version         
                                                                                                                                                            
onedrive v2.4.5
```

I'm happy to test bit, but would need some guidance in how-to.

**Comment by abraunegg** [comment]
@benjuy 
You need to cleanup your binaries or something along that line ... 'sudo make install' should be installing the binary to the right location, but your search path is maybe picking up an older binary from somewhere, or you have a rogue process still running that is not allowing the installation to proceed.

This is all stuff I cant help you with - as this is all local to your system - sorry.

**Comment by benjuy** [comment]
A simple system restart did the trick...
```~ >>> onedrive --version                                                       
onedrive v2.4.5-10-g83eff17```

**Comment by abraunegg** [comment]
@benjuy 
Any update here?

**Comment by abraunegg** [comment]
Closing and merged into master to make v2.4.6 release

**Comment by benjuy** [comment]
I just got the error message
```
ERROR: Check your configuration as your refresh_token may...
```

But it creates a new error message every second, flushing the notification tray. Sure, this way I won't miss it - but once should be sufficient.

**Comment by abraunegg** [comment]
@benjuy 
> But it creates a new error message every second, flushing the notification tray. Sure, this way I won't miss it - but once should be sufficient.

That all depends on which code block is generating that message - a flag once and display once however still could lead to that being missed as the desktop notifications clear up as well - thus, you might not even see it.

At least you got the notification this time around :)
