### ISSUE TITLE
Issue while installing on Lubuntu

### ISSUE THREAD

**Issue by PrateekGoyal18** [abraunegg/onedrive#1043]
```
dpkg: dependency problems prevent configuration of onedrive:
 onedrive depends on libgcc-s1 (>= 3.0); however:
  Package libgcc-s1 is not installed.
 onedrive depends on libphobos2-ldc-shared91 (>= 1:1.21.0); however:
  Package libphobos2-ldc-shared91 is not installed.

dpkg: error processing package onedrive (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (242-7ubuntu3.11) ...
Processing triggers for man-db (2.8.7-3) ...
Errors were encountered while processing:
 onedrive
```

**Comment by abraunegg** [comment]
@PrateekGoyal18 
Closing issue for the following reasons:
1. Installing onedrive via 'apt intstall onedrive' is not supported unless using the PPA as per https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#important-information-for-ubuntu-users
2. Not following Ubuntu installation instructions as per https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md
3. Not following the support requirements for submitting an issue as per https://github.com/abraunegg/onedrive#reporting-issues
