### ISSUE TITLE
Add more config files per folder for more then one folder sync options

### ISSUE THREAD

**Issue by AllyPallies** [abraunegg/onedrive#1047]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when ...
I wanted to sync two different folders listed in two different dirs on my server.
**Describe the solution you'd like**
I would like something like this 
**Describe alternatives you've considered**
 sync_dir = "/mnt/OneDrive"
 sync_folder= "/mnt/OneDrive/site_backup"
and have an option two for almost the same thing so we can link two different dirs to two different folders for sync
**Additional context**
Easiest way to make this work the preferred let me know if your able to do such a thing or have two different configs something

**Comment by abraunegg** [comment]
@AllyPallies 
From within your 'sync_dir' - leave that as the default, which is `~/OneDrive`

Inside the `~/OneDrive` folder, create a symbolic link to:
* /folder/location/1/
* /folder/location/2/

The application will then sync those locations to OneDrive.

If this is not what you are wanting to achieve, please update your first post as it is difficult to interpret what you are trying to do or achieve.

**Comment by AllyPallies** [comment]
So this is what im trying to do.
I want two two different folders to be synced to my one drive into my one drive folders so lets say we have folder one on my local machine stored in /desktop/backup to be stored in a folder within one drive /backups_laptop (notice the names are different )
and the second would be /user/photo's to be stored in a different folder /camera uploads 
Something like this. would what your stating work for that?

**Comment by abraunegg** [comment]
Correct .. create symbolic links in the ~/OneDrive directories to the locations of the data you want to sync.

This is the easiest path to achieve your desired outcome.

**Comment by AllyPallies** [comment]
one thing with that im using a folder thats linked to my NAS in replace of those folders because my server is low on space and i need to make more room / back up my server so its under a mnt folder. so using the /onedrive would use space on the server how would i make it work without using that? would i need to make a folder on the NAS to only host those two folders then have it use that to backup to an other folder placed on the NAS for the sync purpose?

**Comment by abraunegg** [comment]
symbolic links do to not take up any meaningful space - so any symbolic link in ~/OneDrive is not going to cause you space concerns.

You can host the 'sync_dir' anywhere, have the symbolic links point to your data - for example:
```
[alex@centos7full OneDrivePersonal]$ ls -la
total 8
drwxrwxr-x.  6 alex alex  144 Sep  2 11:47 .
drwx------. 32 alex alex 4096 Sep  2 11:47 ..
drwxrwxr-x.  6 alex alex   62 Sep  2 11:47 Documents
drwxrwxr-x.  3 alex alex   28 Sep  2 11:47 Dropbox
-rw-rw-r--.  1 alex alex   25 Sep  2 11:47 file1.tmp
drwxrwxr-x.  2 alex alex   26 Sep  2 11:47 Images
drwxrwxr-x.  2 alex alex   26 Sep  2 11:47 Music
lrwxrwxrwx.  1 alex alex   32 Sep  2 11:47 random_files -> /home/alex/OneDrive/random_files
lrwxrwxrwx.  1 alex alex   33 Sep  2 11:47 random_images -> /home/alex/OneDrive/random_images
lrwxrwxrwx.  1 alex alex   33 Sep  2 11:47 random_videos -> /home/alex/OneDrive/random_videos
[alex@centos7full OneDrivePersonal]$ 


```

**Comment by abraunegg** [comment]
Closing issue as question answered
