### ISSUE TITLE
Personal and School Accounts Syncing Together Into One Account?

### ISSUE THREAD

**Issue by keithcdodd** [abraunegg/onedrive#1048]
I have a personal and a school account. I followed the "use multiple accounts" (created two different files for .config for each and sign in for each with those configs) and ran the associated commands. Now, when I run to synchronize one of them with their associated config files, it ends up downloading everything from both accounts into the one account (e.g. both my personal and school account are downloaded to my onedrive folder, with then all my personal files uploaded to my school onedrive and all my school files uploaded to my personal onedrive). 

Ideally I would like it to sync them separately but cannot figure out how or why it is doing this. I am running this in Manjaro with the updated AUR. Please let me know if you need more information.

Thank you!

**Comment by abraunegg** [comment]
@keithcdodd 
What you need to do is, for each separate configuration, have a different 'sync_dir' setting.

This way, each account data, stays in it's own folder.

This information is not clear under https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#using-multiple-onedrive-accounts - so will get that updated.

**Comment by abraunegg** [comment]
Documentation updated via https://github.com/abraunegg/onedrive/commit/bcd710a08718571e3a00467032ee04e901b101de

Closing issue as question answered

**Comment by keithcdodd** [comment]
Thank you!! 

If it helps anyone else searching, here were the lines I ended up running then (Note -- I had to realize not to make the syncdirs ahead of time on my computer, because otherwise it would try to delete the content online since the folder was more new than online. I think that might be an easy mistake to make.):
```
onedrive --synchronize --verbose --confdir="~/.config/onedrivePersonal" --syncdir "~/OneDrivePersonal" & 
onedrive --synchronize --verbose --confdir="~/.config/onedriveWork" --syncdir "~/OneDriveWork" & 
```
