### ISSUE TITLE
Save Space -- File Names With Direct Downloads

### ISSUE THREAD

**Issue by keithcdodd** [abraunegg/onedrive#1049]
I looked around for this feature and could not find it, but I apologize if I missed it!

**Is your feature request related to a problem? Please describe.**
Not so much an issue -- more like a benefit of saving space on one's laptop. Would be an issue if running out of space.

**Describe the solution you'd like**
The sync merely syncs the names of the files and are links to download and open the file to your computer. The folders would still be downloaded, just the files are simply filenames that when opened download and open the associated file. This way, you can have all the files at access to your fingertips, all while taking the least amount of space on your computer. The downside being that you would have to wait for the individual file to download if you want to edit it -- but would be a cool feature option.

I apologize if I missed this already being a possible feature.

**Describe alternatives you've considered**
I'm not quite sure what this means. Onedrive in microsoft has this feature/option? 

**Additional context**
None

**Comment by abraunegg** [comment]
@keithcdodd 
Please refer to https://github.com/abraunegg/onedrive/issues/757
