### ISSUE TITLE
--monitor won't delete on local computer 

### ISSUE THREAD

**Issue by keithcdodd** [abraunegg/onedrive#1050]
Hello, thanks for your patience. 

I have two accounts that I have syncing in systemctl as advised in your documentation (in ExecScript onedrive --monitor --confdir="PATH" --syncdir "PATH". 

When I add or delete a file locally, I do see the change online. But when I change things online, I do not see the change reflected locally. E.g. if I delete a file online, it is still on my local file/folder. What am I doing wrong -- is it somehow missing permissions to write on my local files?

**Comment by abraunegg** [comment]
@keithcdodd 
Local changes are uploaded right away, however remote changes are delayed until the next sync cycle which by default is 5 mins.
