### ISSUE TITLE
Filtering not working as intended?

### ISSUE THREAD

**Issue by remiburet** [abraunegg/onedrive#1051]
Hi,

I don't know if this is a deliberate feature or a bug but I see that all files including those starting with a dot are uploaded even when filtering is enabled and then put in the bin on the cloud side. 
Wouldn't it be better to filter those files before or am I missing something? Because of this, my bin is full of swap files.

Thank you,
Rémi

**Comment by abraunegg** [comment]
@remiburet 
Rather than editing and removing your problem, can yiu re edit and detail how you solved it - might be helpful for others in the future.
