### ISSUE TITLE
Support for moving and renaming

### ISSUE THREAD

**Issue by taokann** [abraunegg/onedrive#1052]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I rename a file on my computer and this software starts to download the file with the old name from onedrive, AND THEN uploads the file with the new name to the server. So now there are two files with two names. Great !

Also, if I move some files from one directory to another, onedrive deletes them all from the server, then starts to upload them again to their new location. It's OK when you move 3 little text files, but when you move a 4GB video, it's a bit annoying (my bandwidth is 150 kBps down, 50 kBps up so you see the problem).

**Describe the solution you'd like**
Renaming : If the file's CRC is the same as this from the server, it's just a renaming. Just take the most recent file and apply the new name to the remote file. (if the API permits it)

Moving : Again, if the files CRC are matching, no need to delete and re-upload. Just move them on the server. (if the API permits it)

**Describe alternatives you've considered**
Move myself to a big city, where optical fiber is available.

**Additional context**
```
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Downloading file folder/misc/old_name.png ... done.
Uploading differences of ~/OneDrive
Uploading new items of ~/OneDrive
Uploading new file ./foler/misc/new_name.png ... done.
```

**Comment by abraunegg** [comment]
@taokann 

> Support for moving and renaming

Can you please provide more detail and context here? How are you running the application? With what configuration?

The application absolutely 100% already supports this (moving and renaming) - and does this consistently. If you are running using `--synchronize` however then there is no way for the application to know what local operations have occurred - refer to https://github.com/abraunegg/onedrive/blob/master/docs/known-issues.md#moving-files-into-different-folders-should-not-cause-data-to-delete-and-be-re-uploaded for further information.

 Can you please provide all the details that are required in a bug report and provide a verbose debug log? Refer to https://github.com/abraunegg/onedrive#reporting-issues for more details.

Your information is super light on in details - and your additional context log is not very helpful - yes it shows something downloading and uploading, but .. what and why is the application doing this - this is why a verbose debug log is needed.

Please provide these details so this issue can be looked into with greater detail.

**Comment by taokann** [comment]
Hi, thanks for your answer.
I use ``--synchronize``, so maybe it's normal, sorry.
But couldn't the application search for information in file's metadata? With the creation date, it may know that the files has been moved.
I can send you a verbose log, but will it be helpful, since you are already aware of this issue? It's going to list all files in my onedrive folder...

**Comment by abraunegg** [comment]
@taokann 
No verbose debug log needed. Search / trawling the filesystem for changes is also very intensive. The only way to do what you want is via --monitor

**Comment by taokann** [comment]
OK, thanks for your help.
