### ISSUE TITLE
Exclude files of type socket

### ISSUE THREAD

**Issue by morgansimonsen** [abraunegg/onedrive#1054]
I have some folders I would like to sync that have UNIX domain sockets in them. These fail and warnings are entered in the log.

Ability to skip "special" file types

**Comment by abraunegg** [comment]
@morgansimonsen 
These are excluded for the reason as provided in the log. Files that are Unix domain socket will cause a 'hang' in the application, as the application is waiting for the domain socket to 'finish' - but it never does, thus this is the issue.

This functionality will not be changed - sorry.

**Comment by morgansimonsen** [comment]
I probably did not express myself clearly, sorry. Skipping the files is exactly what I want. When onedrive processes them the output is "item is not a valid file". I took this to mean an unhandled situation, but now I know otherwise. My suggestion was more to skip these files with some kind of filter so that they are not even processed. Thanks!

**Comment by abraunegg** [comment]
@morgansimonsen 
Not a problem - however I am not sure how the log output, when a file which is a domain socket is skipped, could be misinterpreted:
```
Skipping item './TEST/regular.pipe' as it is not a valid file
```

**Comment by morgansimonsen** [comment]
The file in my case is of type "other/socket" and it produces the error "item is not a valid file: ./.config/xpad/server". In the directory listing it is "srwxrwxr-x".

**Comment by abraunegg** [comment]
@morgansimonsen 
OK - that then needs to be updated so that the messaging is consistent.

**Comment by abraunegg** [comment]
@morgansimonsen 
Can you please provide a full debug log example, as looking at the code - no such log output as per your reference exists:
```
					// path is not a valid file
					log.log("Skipping item - item is not a valid file: ", path);
```

This is the error message generated, and is the ONLY reference in the entire code base. This was introduced in #985 , and no such log line output existed before then.

What version of code are you running? The latest release is v2.4.5, with 'master' sitting at 'v2.4.5-11-g4ddad0c'

Please provide a verbose debug log supporting your error output.

**Comment by morgansimonsen** [comment]
### Bug Report Details ###
Files of type socket/other report as invalid.

**Application and Operating System Details:**
*   OS: Linux hplinux 5.7.17-200.fc32.x86_64 #1 SMP Fri Aug 21 15:23:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
*   GUI: Gnome
*   OneDrive Account Type: Personal
*   Did you build from source or install from a package? Build from source
*   DMD64 D Compiler v2.093.0
*   onedrive version                       = v2.4.5-11-g4ddad0c
Config path                            = /home/<user>/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/<user>/OneDrive-Personal
Config option 'skip_dir'               = Backup|Customer Work|OneNote Notebooks|OneNote Uploads
Config option 'skip_file'              = ~*|.~*|*.tmp|.Trash-*
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = true
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
*   Curl Version: curl 7.69.1

debug log sent by email.

**Comment by abraunegg** [comment]
@morgansimonsen 

> The file in my case is of type "other/socket" and it produces the error "item is not a valid file: ./.config/xpad/server". In the directory listing it is "srwxrwxr-x".

Based on your log output, and based on the code, it is clear that the file is being skipped, due to reason of not being a valid file. The code is doing what you want, that is, to skip invalid files.
