### ISSUE TITLE
O365 shared library -- sync to subdirectory

### ISSUE THREAD

**Issue by kenyarnall** [abraunegg/onedrive#1055]
**Is your feature request related to a problem? Please describe.**
When I use drive_id = "..." to connect an Office365 shared library, the contents of that library are sync'd to ./OneDrive/. Thus, if I have multiple shared libraries with similar contents, I will get conflicts.

**Describe the solution you'd like**
When sync'ing a shared library, sync contents to a subdir of ./OneDrive named after the share.

**Describe alternatives you've considered**
I'm new with this onedrive client, so maybe there's a solution already -- if so, my apologies, I couldn't find it.

**Additional context**
Ubuntu 20.04, latest version from PPA.

**Comment by abraunegg** [comment]
@kenyarnall 
> When I use drive_id = "..." to connect an Office365 shared library, the contents of that library are sync'd to ./OneDrive/. Thus, if I have multiple shared libraries with similar contents, I will get conflicts.

The solution here is to:
* For each shared library, use a unique configuration
  * Each configuration specifies the unique 'drive_id' value
  * Each configuration specifies the unique 'sync_dir' value

To achieve the outcome of what you are wanting:
* Leave your ~/OneDrive as is
* Configure Office365 shared library 1 with a 'sync_dir' of `~/OneDriveSharedLibrary/<library_1_name>/`
* Configure Office365 shared library 2 with a 'sync_dir' of `~/OneDriveSharedLibrary/<library_2_name>/`
* Create a symbolic link from `~/OneDriveSharedLibrary/<library_1_name>/` to `~/OneDrive/<library_1_name>/`
* Create a symbolic link from `~/OneDriveSharedLibrary/<library_2_name>/` to `~/OneDrive/<library_2_name>/`

This will have the effect of every shared library you want to sync, in it's own sub folder under ~/OneDrive/ whilst keeping all the data unique and no conflicts.

For more details refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#using-multiple-onedrive-accounts

Also, please be aware of Issue https://github.com/abraunegg/onedrive/issues/1053 which only impacts Ubuntu PPA users.

**Comment by abraunegg** [comment]
Closing issue as question answered

**Comment by kenyarnall** [comment]
Thanks!
