### ISSUE TITLE
Sync onedrive and multiple sharepoint sites in one client

### ISSUE THREAD

**Issue by jurgeng-ot** [abraunegg/onedrive#1057]
In the documentation I read that I can sync Onedrive and sharepoint.

Is it also possible to have the onedrive client sync my personal onedrive folder and multiple sharepoint sites with one running onedrive instance?

I tried this some time ago with the skillion client but then ended up that my local onedrive folder was synced to the sharepoint site, creating some chaos on the sharepoint shite.

If that is possible, do you have a snippet of configuration how to so?

**Comment by abraunegg** [comment]
@jurgeng-ot 

> Is it also possible to have the onedrive client sync my personal onedrive folder and multiple sharepoint sites with one running onedrive instance?

Yes this is possible.

Please refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#using-multiple-onedrive-accounts and https://github.com/abraunegg/onedrive/wiki/OneDrive-Client-Multi-Configuration-Assistance

**Comment by abraunegg** [comment]
Closing issue as question answered

**Comment by jurgeng-ot** [comment]
Thanks a lot for the quick and comprehensive answer and keep up the good work!
