### ISSUE TITLE
onedrive --get-O365-drive-id ,site could not be found

### ISSUE THREAD

**Issue by leon-zhang-guoao** [abraunegg/onedrive#1059]
When I create a new channel XXX in teams, the following error occurs when I use -- get-o365 drive ID XXX
ERROR: The requested SharePoint site could not be found. Please check it's name and your permissions to access the site.
It has been confirmed that the account has permission
Can someone help me
onedrive --version
onedrive v2.4.5-11-g4ddad0c

**Comment by abraunegg** [comment]
@leon-zhang-guoao 

When you search the SharePoint site name - what do you get back as a result? Is the site you are searching for listed?

Example:
```
onedrive --confdir '~/.config/onedrive-business/' --get-O365-drive-id 'this does not exist'
Configuration file successfully loaded

Unable to access /var/log/onedrive/
Please manually create '/var/log/onedrive/' and set appropriate permissions to allow write access
The requested client activity log will instead be located in the users home directory

Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: this does not exist
ERROR: The requested SharePoint site could not be found. Please check it's name and your permissions to access the site.

The following SharePoint site names were returned:
 * Communication site
 * test site
 * Community
 * PointPublishing Hub Site
 * Team Site
 * testteamsite2
 * testteamsite
 * All Company
 * mynasau3
 * Data Production
```

When you use one of the SharePoint site names that you have access to:
```
onedrive --confdir '~/.config/onedrive-business/' --get-O365-drive-id 'Team Site'          
Configuration file successfully loaded

Unable to access /var/log/onedrive/
Please manually create '/var/log/onedrive/' and set appropriate permissions to allow write access
The requested client activity log will instead be located in the users home directory

Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: Team Site
SiteName: Team Site
drive_id: b!kUdW........ZRWV
URL:      https://mynasau3.sharepoint.com/sites/contentTypeHub
```

If the site you are trying to query is not present in the output in the first example, you do not have access to the SharePoint site.

**Comment by leon-zhang-guoao** [comment]
@abraunegg 
Yes, it lists the sites
However, the site name I need does not appear in the list, but I have created it and have permission. I want to know why
Thanks

**Comment by leon-zhang-guoao** [comment]
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: TEST
ERROR: The requested SharePoint site could not be found. Please check it's name and your permissions to access the site.

The following SharePoint site names were returned:
 * ENT-BPO
 * SYNNEX Team Site
 * RH WCA Brasil
 * SYNNEX Services
 * IT Infrastructure LATAM
 * IT Equipment Inventory
 * Olive Branch Production
 * UCaaS BD Team
 * Clean big table data project
 * Intel Marketing Internal
 * ENT-PUR
 * VBM Networking
 * ENT
 * TEST-ENT
 * Synnex Purchasing Distribution
 * All AP Team
 * Team 6520
 * Listas de Precios / Información Vendors
....................................................................

**Comment by abraunegg** [comment]
@leon-zhang-guoao 

> Yes, it lists the sites
> However, the site name I need does not appear in the list, but I have created it and have permission. I want to know why
> Thanks

If the name you need does not appear in the list, then, it is not available to you. 

This is nothing I can assist with. I have noticed that 'sometimes', depending on geographic regions, when you create a new SharePoint site, it will take ~24 hours to be available via the API calls .... why .. I do not know - but this is nothing I can help with. 

The client reports 'all' SharePoint names that the API returns ... if it is not there, it is not accessible -sorry.

**Comment by abraunegg** [comment]
Closing issue as question answered
