### ISSUE TITLE
A little suggestion for dmd download

### ISSUE THREAD

**Issue by ConwayPhelps** [abraunegg/onedrive#1062]
This is just a request on for the instructions... instead of going through all the rigmarole to install dmd, why not just have the user go to https://dlang.org/download.html#dmd and download the latest for their distro and install that way. I grabbed the .dev file and bip, bam, boom... its all installed and no worries, no extraneous code in the terminal.

**Comment by abraunegg** [comment]
@ConwayPhelps 

> This is just a request on for the instructions... instead of going through all the rigmarole to install dmd

Thanks for the suggestion. Running `curl -fsS https://dlang.org/install.sh | bash -s dmd` as opposed to finding, downloading & then manually installing your package for your architecture (assuming you selected the right one) is about the same effort IMHO. 

Feel free to submit a PR where the existing documentation is improved and works for all combinations of OS & Architecture.
