### ISSUE TITLE
"Disk I/O error" after moving to 2-factor authentication

### ISSUE THREAD

**Issue by phrxmd** [abraunegg/onedrive#1064]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**

After reconfiguring my Office 365 Business account to use two-factor authentication via MS Authenticator (rather than phone #) and re-authenticating OneDrive, I get the error message "A database statement execution error occurred: disk I/O error" until I manually remove the files `items.sqlite3-shm`  `items.sqlite3-wal` from my `~/.config/onedrive` directory.

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
`Linux calypso 5.8.4-1-default #1 SMP Wed Aug 26 10:53:09 UTC 2020 (64fe492) x86_64 x86_64 x86_64 GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed?
GUI
*   OneDrive Account Type
O365 Business Essentials
*   Did you build from source or install from a package?
OpenSUSE distribution package
*   Application configuration: 
```
$ onedrive --display-config
onedrive version                       = v2.4.3
Config path                            = /home/my-user-name/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/my-user-name/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Curl Version: Output of `curl --version`
```
$ curl --version
curl 7.72.0 (x86_64-suse-linux-gnu) libcurl/7.72.0 OpenSSL/1.1.1g-fips zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.9.3/openssl/zlib nghttp2/1.41.0
Release-Date: 2020-08-19
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
(Can't reproduce without configuring my entire O365 domain.)

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```
$ onedrive --synchronize
Configuring Global Azure AD Endpoints

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.
Trace ID: 4b986f75-b221-4a9c-80c3-b3670b9e3000
Correlation ID: 20322043-df48-441b-9558-75ce3f5c8c44
Timestamp: 2020-09-15 15:55:59Z

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 401 (Unauthorized)
  Error Reason:  Access token is empty.

ERROR: Check your configuration as your refresh_token may be empty or invalid. You may need to issue a --logout and re-authorise this client.

$ onedrive --logout     
Configuring Global Azure AD Endpoints
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=my-client-id&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.Read.All%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=long-code&session_state=session.state-uuid

Application has been successfully authorised, however no additional command switches were provided.

Please use --help for further assistance in regards to running this application.

$ onedrive --synchronize
Configuring Global Azure AD Endpoints

A database statement execution error occurred: disk I/O error

Please retry your command with --resync to fix any local database corruption issues.

$ onedrive --resync --synchronize         
Configuring Global Azure AD Endpoints

A database statement execution error occurred: disk I/O error

Please retry your command with --resync to fix any local database corruption issues.

$ cd ~/.config/onedrive 
$ ls
items.sqlite3  items.sqlite3-shm  items.sqlite3-wal  refresh_token
$ rm *shm *wal
$ ls -l
insgesamt 36
-rw-r--r-- 1 my-user-name users 28672 15. Sep 17:59 items.sqlite3
-rw-r--r-- 1 my-user-name users  1276 15. Sep 18:54 refresh_token
$ onedrive --resync --synchronize
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
```

**Additional context**

### Bug Report Checklist ###
*   [X] Detailed description
*   [] Reproduction steps (if applicable)
*   [X] Verbose Log Output

**Comment by abraunegg** [comment]
@phrxmd 

This issue primarily manifests itself when you have 2 x binaries running at the same time with the same configuration. The existing execution still has a lock on the files. You 'most likely' had a service file running the daemon which you did not stop.

By removing the files in the way that you did, would have caused the 'other' running process to fail in an ungraceful manner - thus, potentially put you in a data loss scenario. It is never advisable to manually remove those files.

Also, please upgrade your client. v2.4.3 contains issues which have been fixed - refer to https://github.com/abraunegg/onedrive/releases

Until the package is updated, you will need to build from source to uplift your client version.

@SchoolGuy

Please can you update the OpenSuSE package from v2.4.3 to v2.4.5, and keep a watch of releases to ensure the package is kept up-to-date.

**Comment by SchoolGuy** [comment]
@abraunegg I am deeply sorry. We talked about 2.4.5, I will do it after lunch asap.

**Comment by SchoolGuy** [comment]
Request for devel is open: https://build.opensuse.org/request/show/834898

**Comment by SchoolGuy** [comment]
Request to Tumbleweed is in the wild: https://build.opensuse.org/request/show/834937

**Comment by SchoolGuy** [comment]
@phrxmd Do you need this asap in Leap or do you use Tumbleweed? If not then I would talk to some people before submitting this to Leap.

**Comment by abraunegg** [comment]
Closing issue as not an issue, SuSE package update in-flight

**Comment by phrxmd** [comment]
@SchoolGuy Thank you. I'm on Tumbleweed, there is no great hurry.
