### ISSUE TITLE
Can't login with the last version.

### ISSUE THREAD

**Issue by unguest** [abraunegg/onedrive#1069]
When I put the URL at the very first launch, I obtain this : 

```log
onedrive.OneDriveException@src/onedrive.d(874): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "24badc6f-98f2-4850-a9f0-7a73b640079f",
    "error": "invalid_grant",
    "error_codes": [
        70000
    ],
    "error_description": "AADSTS70000: The provided value for the 'code' parameter is not valid.\r\nTrace ID: 5b4aefef-2632-4c34-bc97-d8910e720c00\r\nCorrelation ID: 24badc6f-98f2-4850-a9f0-7a73b640079f\r\nTimestamp: 2020-09-19 17:00:37Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=70000",
    "timestamp": "2020-09-19 17:00:37Z",
    "trace_id": "5b4aefef-2632-4c34-bc97-d8910e720c00"
}
```

**Comment by abraunegg** [comment]
@unguest 

Your bug report is missing critical information to assist as you have not followed of used the bug report template.

Please provide the following information:
1. What Linux Operating System are you using?
2. What version is this OS?
3. How did you install the application?
4. What version of the application did you install?
5. What installation instructions did you follow - what is the URL / link / information source?

**Comment by TobiasB22** [comment]
I get the same error on Ubuntu 20.04.1 LTS
Linux kernel: 5.4.0-47-generic
Installed with:  sudo apt install onedrive 
Version: onedrive v2.3.13-1build2

**Comment by abraunegg** [comment]
@TobiasB22 

> I get the same error on Ubuntu 20.04.1 LTS
> Linux kernel: 5.4.0-47-generic
> Installed with: sudo apt install onedrive
> Version: onedrive v2.3.13-1build2

This is your issue.

On Ubuntu – `apt install onedrive` is not supported. Refer to : https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#important-information-for-ubuntu-users

You are running an obsolete version. Your choices are:

1.	Build from source
2.	Use the Ubuntu PPA - https://launchpad.net/~yann1ck/+archive/ubuntu/onedrive (This gets updated when Debian packages are updated)

If I were you – remove the ‘onedrive’ package via ‘apt remove onedrive’ and then build from source. The instructions are very clear and easy to follow.

**Comment by unguest** [comment]
I'm running the last release of Pop OS & installed it via apt.

**Comment by unguest** [comment]
Building from source didn't work neither because of sqlite3 which wasn't recognized...

**Comment by abraunegg** [comment]
@unguest 
> I'm running the last release of Pop OS & installed it via apt.

Installing via apt is not supported. It will install an obsolete version.

> Building from source didn't work neither because of sqlite3 which wasn't recognized...

As Pop OS is Ubuntu based, you should be able to follow the Ubuntu instructions to install the required dependencies. Did you do this?

For the time being please try an use the Ubuntu PPA then. In the background I will get a Pop OS platform up and running to try and assist you.

**Comment by unguest** [comment]
I'm currently setting-up the PPA. Thanks for your help ;)

**Comment by abraunegg** [comment]
@unguest 
I have just run through the installation of POP OS 20.x, plus followed all the instructions in the installation readme to compile from source. No issue can be found, application was successfully compiled by following the Ubuntu instructions:

![pop_os](https://user-images.githubusercontent.com/4956234/93689393-7be76700-fb11-11ea-882b-0bd16f66239a.JPG)

What I will do is update the installation document to make it clearer to follow Ubuntu instructions if you are running a Ubuntu based operating system.

Given this, you have 2 options:
1. Install via the PPA 
2. Install via compiling from source following the Ubuntu instructions

Marking this as resolved & closing

**Comment by unguest** [comment]
Thanks for your help, I'll try it :smile:
