### ISSUE TITLE
error: Could not find any compatible D compiler

### ISSUE THREAD

**Issue by mpaninop** [abraunegg/onedrive#1070]
Hi! I saw that another user raised the issue in June and you replied and closed it. However, I have the same error when running configure. I have installed all the dependencies. I'm running Mint 19 on x86-64 AMD. The attached shows the existing dependencies and the specific error when running configure. Any thoughts?

```
mozeu@mozeu-MS-7A35:~$ uname -a
Linux mozeu-MS-7A35 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

mozeu@mozeu-MS-7A35:~$ cat /etc/upstream-release/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

mozeu@mozeu-MS-7A35:~$ sudo apt install build-essential libcurl4-openssl-dev libsqlite3-dev pkg-config git curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
pkg-config is already the newest version (0.29.1-0ubuntu2).
curl is already the newest version (7.58.0-2ubuntu3.10).
git is already the newest version (1:2.17.1-1ubuntu0.7).
libcurl4-openssl-dev is already the newest version (7.58.0-2ubuntu3.10).
libsqlite3-dev is already the newest version (3.22.0-1ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
mozeu@mozeu-MS-7A35:~$ sudo apt install libnotify-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libnotify-dev is already the newest version (0.7.7-3).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.

mozeu@mozeu-MS-7A35:~$ curl -fsS https://dlang.org/install.sh | bash -s dmd
dmd-2.093.1 already installed
Using dub 1.22.0 shipped with dmd-2.093.1

Run `source ~/dlang/dmd-2.093.1/activate` in your shell to use dmd-2.093.1.
This will setup PATH, LIBRARY_PATH, LD_LIBRARY_PATH, DMD, DC, and PS1.
Run `deactivate` later on to restore your environment.

mozeu@mozeu-MS-7A35:~$ source ~/dlang/dmd-2.093.1/activate
(dmd-2.093.1)mozeu@mozeu-MS-7A35:~$ sudo git clone https://github.com/abraunegg/onedrive.git
Cloning into 'onedrive'...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 4100 (delta 58), reused 12 (delta 9), pack-reused 4011
Receiving objects: 100% (4100/4100), 2.80 MiB | 19.13 MiB/s, done.
Resolving deltas: 100% (2824/2824), done.

(dmd-2.093.1)mozeu@mozeu-MS-7A35:~$ cd onedrive

(dmd-2.093.1)mozeu@mozeu-MS-7A35:~/onedrive$ sudo ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... no
checking for ldmd2... no
checking for ldc2... no
configure: error: Could not find any compatible D compiler
(dmd-2.093.1)mozeu@mozeu-MS-7A35:~/onedrive$ 

```

**Comment by abraunegg** [comment]
@mpaninop 
In your post above, you say you are running Mint 19, but your output details you are running Ubuntu 18.x. - however the issue you referred to, the user was using Ubuntu 19.x.

The issue comes down to your steps:
```
(dmd-2.093.1)mozeu@mozeu-MS-7A35:~/onedrive$ sudo ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... no
checking for ldmd2... no
checking for ldc2... no
configure: error: Could not find any compatible D compiler
(dmd-2.093.1)mozeu@mozeu-MS-7A35:~/onedrive$ 
```

Up to this point you running everything as a normal user, then, running `sudo ./configure` - what this is doing is elevating your user to root (where DMD is not activated) - thus this is why it cannot be found.

Please follow the correct instructions to compile as per: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#compilation--installation

**Comment by abraunegg** [comment]
Closing issue as question answered

**Comment by mpaninop** [comment]
I certainly appreciate your response.  Yes, I am running Mint 19. I thought it might be more useful to know which Ubuntu release was under.  The reason I attempted to execute configure using sudo is that trying to compile exactly  per the instructions did not work. Without root, there are two Permission denied errors, both of which have to do with writing to config.log (lines 1409 and 1419 of the configure script) Config.log is owned by root, so I thought perhaps if I ran as root, that would help.  I'll attach the bash session which shows you what I'm talking about. That can't be too hard to solve.
[further_D_compiler_not_compatible.txt](https://github.com/abraunegg/onedrive/files/5278127/further_D_compiler_not_compatible.txt)

**Comment by abraunegg** [comment]
@mpaninop 
Please start from scratch and follow the [directions](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md) to compile the software.

Start by 'removing' the following folder `~/onedrive` as you cloned the github under your user account using sudo as well. This means all files and folders in that folder are owned by 'root' not 'mozeu'. Once removed follow the directions as per the installation document.

To assist with that, also read the very specific the Linux Mint 19 directions here: https://forums.linuxmint.com/viewtopic.php?p=1889392#p1889392

If this still fails, upgrade your Linux Mint to Mint 20.x, and use the Ubuntu PPA. Those instructions are also in the [install.md](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md) but also in the forum post above.

**Comment by mpaninop** [comment]
Thank you for taking the time.  I'm good now.
