### ISSUE TITLE
Config option 'skip_symlinks' operation not clear in USAGE.md

### ISSUE THREAD

**Issue by helderdaniel** [abraunegg/onedrive#1071]
Hi,

In  **USAGE.md** , about **skip_symlinks** config option, it is written that:

_"Setting this to "true" will skip all symlinks while syncing"_

But this seems not clear.
I mean, what is the operation when `skip_symlinks = "true"` ?

```
1. does not copy the symlinks?
or
2. does not copy the files/folder referenced by the symlinks, but copies the symlinks?
```

and what is the operation when `skip_symlinks = false` ?

```
1. copy the symlinks?
or
2. copy the files/folders referenced by the symlinks?
```

**Comment by abraunegg** [comment]
@helderdaniel 
When this option is enabled, all files and folder that are a symbolic link will be skipped - the description in the usage document is correct and accurate.

For example, consider the following folder structure:
```
.
├── Documents
│   ├── file2.pdf
│   ├── Images
│   │   └── image001.jpg
│   └── Music
│       └── audio001.mp3
├── Dropbox
├── file1.pdf
├── file1.tmp
├── file1.txt
├── Images
│   └── image003.jpg
├── Music
│   └── audio003.mp3
├── random_files -> /home/alex/OneDrive/random_files
├── random_images -> /home/alex/OneDrive/random_images
└── random_videos -> /home/alex/OneDrive/random_videos

9 directories, 8 files
```

The the option enabled:
```
Skipping item - skip symbolic links configured: ./random_files
Skipping item - skip symbolic links configured: ./random_images
Skipping item - skip symbolic links configured: ./random_videos
```
Files and folders that are symbolic links are not synced to OneDrive.

When the option is disabled (default), they are synced to OneDrive.

Please test this yourself, and `--dry-run` is useful when testing new configuration changes.

**Comment by abraunegg** [comment]
Closing issue as questioned answered

**Comment by helderdaniel** [comment]
@abraunegg, thanks for the details, but what I cannot understand from the
documentation is whether the symlink itself is synced or not when this
option is true or false

**Comment by abraunegg** [comment]
@abraunegg 
The symbolic link is skipped, the target is skipped - nothing is synced as it is skipped.

**Comment by helderdaniel** [comment]
Ok, so if I understand it, if skip_symlinks links is false, the file or the
whole directory tree referenced by the symlink is synced, which mean that a
duplicate is created

**Comment by abraunegg** [comment]
> Ok, so if I understand it, if skip_symlinks links is false, the file or the whole directory tree referenced by the symlink is synced, which mean that a duplicate is created

No 'duplicate' is created. I am unsure where you are getting this sort of understanding from.

A symbolic link is a 'pointer' to where a file or folder is on your local file system.

When this option is 'false' that pointer, as it is named, is uploaded to OneDrive. If that 'pointer' points to a file, the file is uploaded as the symbolic link name. If that 'pointer' is a directory, then the directory and all it's contents will be uploaded as the symbolic link name.

When this option is 'true', the symbolic link is skipped - that means nothing is uploaded to OneDrive - no link, no file, no reference - nothing. No reference will exist on OneDrive.

Please - test out the option and utilise `--dry-run` to assist with your understanding here. As per the documentation, when this option is enabled, symbolic links are skipped. There is no clearer way to explain this.

**Comment by helderdaniel** [comment]
On Wed, 23 Sep 2020 at 22:30, abraunegg <notifications@github.com> wrote:

> Ok, so if I understand it, if skip_symlinks links is false, the file or
> the whole directory tree referenced by the symlink is synced, which mean
> that a duplicate is created
>
> No 'duplicate' is created. I am unsure where you are getting this sort of
> understanding from.
>

bear with me, please

A symbolic link is a 'pointer' to where a file or folder is on your local
> file system.
>

that's precisely the point ... no pun intended :)

Ok,

*So let's consider a Linux system, and this folder tree:*

/storage
/storage/Pictures
/storage/Pictures/pictureFantastic.jpg
/storage/Pictures/pictureAwesome.jpg

*let's say I have a symbolic link in my area to folder: /home/Pictures*

/home/hdaniel
/home/hdaniel/symlinkToPictures -> /home/Pictures

*let's say that I want to copy the symlink (just the link, not the whole
/home/Pictures folder), to another user area:*

/home/john

*i can try:*

cp   /home/hdaniel/symlinkToPictures   /home/john

*and expect to copy only the symlink, ie. the pointer to john's area,
getting this:*

/home/john
/home/john/symlinkToPictures -> /home/Pictures

*however, the whole folder pointed by the symlink will be copied with this
command, ending with:*

/home/john
/home/john/Pictures/
/home/john/Pictures/pictureFantastic.jpg
/home/john/Pictures/pictureAwesome.jpg

*Unfortunately I duplicated the folder "Pictures".*
*To copy just the symlink I need to add a switch to linux cp command,
switch -P*

cp  * -P    * /home/hdaniel/symlinkToPictures  /home/john

*and now I have just the symlink itself copied as intended:*

/home/john
/home/john/symlinkToPictures -> /home/Pictures

I had some bad experiences with some cloud storage clients, like *"copy"*,
which was an old cloud storage service and client named, you guessed: *copy*
.
By default the *copy* client when syncing a symlink will act as Linux *cp*
command without the *-P* switch,
so It *duplicates* the whole tree pointed by the symlink, instead of just
copying the symlink (ie. the pointer itself).

When this option is 'false' that pointer, as it is named, is uploaded to
> OneDrive. If that 'pointer' points to a file, the file is uploaded as the
> symbolic link name. If that 'pointer' is a directory, then the directory
> and all it's contents will be uploaded as the symbolic link name.
>

So that is my question.
When this option is false, what is uploaded is just the symlink?
Or the whole structure pointed by it?
If it is the whole structure it duplicates that structure at the position
of the symlink.

When this option is 'true', the symbolic link is skipped - that means
> nothing is uploaded to OneDrive - no link, no file, no reference - nothing.
> No reference will exist on OneDrive.
>

ok, got it :)


> Please - test out the option and utilise --dry-run to assist with your
> understanding here. As per the documentation, when this option is enabled,
> symbolic links are skipped. There is no clearer way to explain this.
>

I will,

thanks

**Comment by abraunegg** [comment]
@helderdaniel 
> When this option is false, what is uploaded is just the symlink?

OneDrive has zero concept of a symbolic link and this file type is not supported. All files must be whole files or directories.

> Or the whole structure pointed by it?

When false (default state), the whole structure is uploaded as referenced by the symbolic link.

**Comment by helderdaniel** [comment]
Ok, so since the info in **USAGE.md** just states that:

 _"Setting this to "true" will skip all symlinks while syncing."_

One might think, as I did, that setting it to false will sync the symlink, I mean the pointer itself, not the whole structure.

Other cloud services, such as Dropbox does that. It just uploads the symlink pointer, not the whole structure pointed.

I proposed to add that info to the documentation, without entering in details about files, inodes, symlinks, and all that.

Something that warn the user that with the default setting, when finding a symlink, the client will duplicate contents:


**skip_symlinks**
Example:

```
# local_first = "false"
# no_remote_delete = "false"
skip_symlinks = "true"
# debug_https = "false"
# skip_dotfiles = "false"
```

Setting this to "true" will skip all symlinks while syncing.

Setting this to "false" will sync the whole folder structure referenced by the symlink, duplicating the contents in the place where the symlink is.

The default setting is "false".
