### ISSUE TITLE
monitoring mode not correctly detecting directory delete

### ISSUE THREAD

**Issue by nrandon** [abraunegg/onedrive#1078]
### Bug Report Details ###
**Describe the bug**
Monitoring mode not correctly detecting directory delete if performed when client is offline and brought back online

**Reproducer is as follows:**
- Make a directory test/test/test
- Place a file in the above directory test.txt
- Let one drive client sync this.
- Now take OneDrive client offline.
- Delete the all the directory's and files made above. (or simple rm -rf temp at the bottom level)
- Restart the OnceDrive client the delete will not be detected or a new sync occur.
- Expected outcome: All new content delete.

Detected when network connection was down and i was working in a OneDrvie directory.

OneDrive client is at: v2.4.5-23-ga3a2726

**Application and Operating System Details:**
*   OS: Debian Buster: Docker version 19.03.13, build 4484c46d9d, SMP Debian 5.6.14-2~bpo10+1 (2020-06-09)
*   Are you using a headless system (no gui) or with a gui installed? Headless
*   OneDrive Account Type: Personal (free)
*   Did you build from source or install from a package? Installed using latest Alpine docker
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
onedrive version                       = v2.4.5-23-ga3a2726
Config path                            = /root/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /root/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

**Comment by abraunegg** [comment]
@nrandon 
Will look at this in the morning, no time last 24hrs due to other commitments.

**Comment by abraunegg** [comment]
@nrandon 
I have been able to replicate this scenario, please can you test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1082/head:pr1082
git checkout pr1082
./configure; make clean; make;
```
When running the PR version, your client version should be: `onedrive v2.4.5-25-g36ccfbf`.

**Comment by abraunegg** [comment]
PR merged into master, validated locally, closing issue
