### ISSUE TITLE
OneDrive Uploads and Downloads Existing Files

### ISSUE THREAD

**Issue by astralspurs** [abraunegg/onedrive#1080]
I have used abraunegg's onedrive for some time now. A problem I run into quite often is when I setup a new computer and re-install onedrive on it, the first sync takes just forever as the program seems to think there is a need to re-download files from onedrive even though they exist on local, or re-upload files from my computer even though they exist on my onedrive. Isn't there some sort of comparison that takes place before it tries to sync, like checking if the filename is there, or if the modification dates are the same?

Happy to provide any information I may have forgotten. Thank you.

`uname -sr
Linux 5.8.12-arch1-1`

`onedrive --version
onedrive v2.4.5`

```
onedrive --display-config
Configuration file successfully loaded
onedrive version                       = v2.4.5
Config path                            = /home/astralspurs/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /media/onedrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ._*|~*|*.md~|thumbs.db|sync.ffs_db|.DS_Store|*.swp|*.lock
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

**Comment by abraunegg** [comment]
@astralspurs 
> A problem I run into quite often is when I setup a new computer and re-install onedrive on it, the first sync takes just forever as the program seems to think there is a need to re-download files from onedrive even though they exist on local, or re-upload files from my computer even though they exist on my onedrive.

The issue here is that unless you are also copying the `items.sqlite3` from the old PC to new PC, the client has no idea about the current sync state of the client on the new PC. Are you doing this?

If you are not doing this, when you do the first sync, it will go through all of your files - local and remote, to determine what is in sync, what is out of sync. This being said, if your modified timestamp of any file / folder on the new PC is different, this will then cause an upload to occur (as the file is .. according to the client) modified.

As the local DB is not present, there is no way for the file to be looked up, or compared checksum wise to prevent a file upload (as, the client does not know because the DB is missing).

When setting up a new PC and migrating data over, how are you migrating that data?

I have always found it better better to use rsync, as this ensures that the timestamp is not being updated in a false manner:
```
rsync -av --progress source/ destination
```
eg:
```
rsync -av --progress /home/alex/OneDrive/ alex@new.ip.address:/home/alex/OneDrive
```

This way the timestamps remain the same and are not falsely updated.

**Comment by astralspurs** [comment]
Thank you for your quick reply. 

This most recent time I did not copy the `items.sqlite3`, but I'll keep this in mind. I'll use rsync exclusively too.

I imagine it is the modified timestamps that may be affecting this, but it is hard to verify. The files listed on the OneDrive web interface list the same date as my local files, but they'll still re-downloaded. They're the same size, same file name, and seemingly the same date. I will treasure my `items.sqlite3` once I get it back in sync, but to do so I'm going to have to redundantly go through so much data transferring.

**Comment by abraunegg** [comment]
@astralspurs 

> I imagine it is the modified timestamps that may be affecting this, but it is hard to verify. The files listed on the OneDrive web interface list the same date as my local files, but they'll still re-downloaded

They should not be re-downloaded. if the DB entry does not exist, it will see if the file exists locally, and if it does, and the file hash is the same, then the database is just updated, no download will occur. Appropriate messaging around this is also evident.

If this is *not* what you are seeing, please provide a verbose debug log.

**Comment by abraunegg** [comment]
Closing issue, question answered

**Comment by astralspurs** [comment]
Thank you for clarifying this. Concerning the moving of the onedrive folder between computers, when I copy items.sqlite3, can I expect the database will sync correctly even if the sync_dir may be different? On one computer I may have the onedrive directory at `/media/onedrive` and on another computer it may be `/mnt/veracrypt1/onedrive`.

**Comment by abraunegg** [comment]
@astralspurs 
> Thank you for clarifying this. Concerning the moving of the onedrive folder between computers, when I copy items.sqlite3, can I expect the database will sync correctly even if the sync_dir may be different? On one computer I may have the onedrive directory at `/media/onedrive` and on another computer it may be `/mnt/veracrypt1/onedrive`.

A change in 'sync_dir' will trigger a '--resync' requirement. This will purge the existing items in the items.sqlite3 file.

However - so long as all the data in the 'old' and 'new' sync_dir is the same (file size, modified timestamp etc), then, when the items are retrieved from OneDrive, they will be found to exist already locally, thus report that the local DB is out of sync, and DB will be updated upon first new sync in the new location.

**Comment by astralspurs** [comment]
Great, ok. Thank you.
