### ISSUE TITLE
Takes 10 minutes to recognize new files on one drive?

### ISSUE THREAD

**Issue by erithtotl** [abraunegg/onedrive#1087]
So this may not be an issue but just some kind of user error, but I've installed and have this running, and it takes pretty much always 10 minutes for a new file on my onedrive to be recognized and synced to the linux environment running this.

I've tried changing the various interval configurations to no effect (Those read like they only affect the client side anyway).  Is there a way to improve syncing of changes from onedrive?

**Comment by abraunegg** [comment]
@erithtotl 
> So this may not be an issue but just some kind of user error, but I've installed and have this running, and it takes pretty much always 10 minutes for a new file on my onedrive to be recognized and synced to the linux environment running this.
> 
> I've tried changing the various interval configurations to no effect (Those read like they only affect the client side anyway). Is there a way to improve syncing of changes from onedrive?


As you have not used the bug report template, I have no idea what your configuration is, what client version you are running, none of the pertinent information to assist you quickly. Please can you update your post with all the required information.

The way the client works, depending on how you have it configured, in 'monitor mode':
* Application startup
* Register local directories to be watched for changes
* Sync changes from online
* Process any local changes
* Wait 300 seconds, processing any watched local changes
* Sync changes from online
* Process any local changes
* Wait 300 seconds, processing any watched local changes
...


If you are waiting 600 seconds, you have probably changed the 'monitor_interval' setting.

If your 'sync_dir' is on a network file system (NFS, Samba, other) it most likely does not support watching for local changes - I cannot fix that.

Please update your post with the required information.

**Comment by erithtotl** [comment]
```
My apologies.  In my last two tests it was definitely faster, within 2-5 minutes.  Please note the error in the logfile below.  Could that have had something to do with the delays?  Is it related to the environment variables fs.file-max and fs.inotify.max_user_watches?  I'm not sure what appropriate values are for those.

Thanks for all your help.

Here's the output of display-config:

onedrive version                       = v2.4.6
Config path                            = /home/imurphy/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/imurphy/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 60
Config option 'min_notify_changes'     = 1
Config option 'log_dir'                = /home/imurphy/log/onedrive
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
FoundryVTT/Data
Business Shared Folders configured     = false
```

Linux kernel: 4.19.0-10-cloud-amd64

Logfile:

```
2020-Oct-05 19:35:37.1047982    Configuring Global Azure AD Endpoints
2020-Oct-05 19:35:39.1374086    Initializing the Synchronization Engine ...
2020-Oct-05 19:35:39.137474     Initializing monitor ...
2020-Oct-05 19:35:39.1374938    OneDrive monitor interval (seconds): 60
2020-Oct-05 19:39:29.3315045    Downloading file FoundryVTT/Data/pics/Tokens/elf wizard token.png ... done.
2020-Oct-05 19:39:35.5778306    Uploading differences of FoundryVTT/Data/pics/Tokens/elf wizard token.png
2020-Oct-05 19:39:35.5788861    Uploading new items of FoundryVTT/Data/pics/Tokens/elf wizard token.png
2020-Oct-05 19:47:43.5229056    ERROR: OneDrive returned an error with the following message:
2020-Oct-05 19:47:43.5231746      Error Message: Timeout was reached on handle 55E7516AAAB0
2020-Oct-05 19:50:47.5515284    Downloading file FoundryVTT/Data/pics/Tokens/wizard2.jpg ... done.
2020-Oct-05 19:55:26.9810487    Starting a sync with OneDrive
2020-Oct-05 19:55:26.9813084    Syncing changes from OneDrive ...
2020-Oct-05 19:55:40.0703085    Sync with OneDrive is complete
2020-Oct-05 20:01:33.4716509    Starting a sync with OneDrive
2020-Oct-05 20:01:33.4719415    Syncing changes from OneDrive ...
2020-Oct-05 20:01:46.2858889    Sync with OneDrive is complete
```
Notice its doing the sync with onedrive roughly every 6 minutes?  Where is that time coming from.


It's Microsoft 365 family, OneDrive premium

**Comment by abraunegg** [comment]
@erithtotl 
> Notice its doing the sync with onedrive roughly every 6 minutes? Where is that time coming from.

Actually it wont be. That is the logging output. The reason why it is 'looking like' it is syncing every 6 minutes is as follows:
```
monitor_log_frequency = "5"
```
This is the default. In a non-verbose manner, to really make the client as silent as possible, this supresses log output ton only every X syncs - by default 5, so logging output on sync 1, miss 2,3,4,5, output on 6.

Additionally, dont set 'monitor_interval' to 60 seconds.

Unless your rate of data change on OneDrive really is every 60 seconds, then fine - but otherwise - that is a waste. 300 seconds as a minimum is a good balance for checking for changes on OneDrive.

**Comment by abraunegg** [comment]
Closing issue as question answered
