### ISSUE TITLE
onedrive compilation failed (ldc issue ?) on raspbian

### ISSUE THREAD

**Issue by JusTiCe8** [abraunegg/onedrive#1090]
Hi,

using latest source from git repository, both ldc from the install doc or the official raspbian testing package (ldc2-1.16.0-linux-armhf or ldc package 1:1.21.0-1), compilation of onedrive stuck with kernel error.

Here is the file with kernel errors (pasting text make it's very hard to read) as well as last top command display
[onedrive-compilestuck-pi.txt](https://github.com/abraunegg/onedrive/files/5339594/onedrive-compilestuck-pi.txt)

Raspberry Pi 3B with Raspian testing and kernel : 
Linux raspberrypi 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux

Required packages : 
ii  libcurl4-openssl-dev:armhf 7.72.0-1      armhf        development files and documentation for libcurl (OpenSSL flavour)
ii  libsqlite3-dev:armhf       3.33.0-1      armhf        SQLite 3 development files
ii  libxml2:armhf              2.9.10+dfsg-6 armhf        GNOME XML library
ii  pkg-config                 0.29.2-1      armhf        manage compile and link flags for libraries

Am I the only one to have such an issue ? Any clue on how to make things work ?

looks like MS have updated their stuff a few days ago and old onedrive I've used failed with the exception : 

```
onedrive.OneDriveException@src/onedrive.d(874): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "3001f80f-fcae-4671-a464-37d548b4d3f2",
    "error": "invalid_grant",
    "error_codes": [
        9002313
    ],
    "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: 12869bca-487b-439b-b8aa-aba816cf4500\r\nCorrelation ID: 3001f80f-fcae-4671-a464-37d548b4d3f2\r\nTimestamp: 2020-10-07 09:41:41Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=9002313",
    "timestamp": "2020-10-07 09:41:41Z",
    "trace_id": "12869bca-487b-439b-b8aa-aba816cf4500"
}
----------------
??:? [0x1164df]
??:? [0x12089b]
??:? [0x1063a3]
onedrive.d:0 [0x36ba3]
onedrive.d:560 [0x35e47]
onedrive.d:425 [0x36d5b]
onedrive.d:410 [0x34fc7]
onedrive.d:150 [0x34983]
main.d:431 [0x422d7]
??:? [0x105fd7]
??:? [0x105e87]
??:? __libc_start_main [0x76c28baf]
```

**Comment by abraunegg** [comment]
@JusTiCe8 
> using latest source from git repository, both ldc from the install doc or the official raspbian testing package (ldc2-1.16.0-linux-armhf or ldc package 1:1.21.0-1), compilation of onedrive stuck with kernel error.
> 
> Here is the file with kernel errors (pasting text make it's very hard to read) as well as last top command display

Please follow the instructions completely for compiling on Raspbian. Follow these instructions (https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-raspbian-armhf) to install the required dependencies. Do not follow any other instructions found elsewhere.

To post log out put & have it format correctly, use 3 x backticks  ``` top and bottom to have the text display correctly.

> looks like MS have updated their stuff a few days ago and old onedrive I've used failed with the exception :
>```
>onedrive.OneDriveException@src/onedrive.d(874): HTTP request returned status code 400 (Bad Request)
> ...
>```
You get this error because:
* You potentially cloned from the 'skilion' repo
* You potentially installed via 'apt install onedrive' which installs either the 'skilion' version or an old v2.3.13 version which has a bug

Please start from scratch, uninstall any packages you have installed that are not listed in the Raspbian instructions. Also ensure that you meet the build environment requirement:
* Build environment must have at least 1GB of memory & 1GB swap space. Check with `swapon -s`

**Comment by JusTiCe8** [comment]
Thanks for the quick reply, I just increase swap space, then it has worked well.

For the record, I did this (no need to reboot the Pi) :
```
sudo vi /etc/dphys-swapfile
=> set CONF_SWAPSIZE=1024 (it was 100)
sudo dphys-swapfile  setup
sudo dphys-swapfile  swapoff
sudo dphys-swapfile  swapon
```

It may be a good idea to add this in the documentation as well as put a bit more emphasis of build environment requirement (I did not notice it to be honest).

**Comment by abraunegg** [comment]
@JusTiCe8 

> It may be a good idea to add this in the documentation as well as put a bit more emphasis of build environment requirement (I did not notice it to be honest).

This requirement of at least 1GB swap apace is already clearly articulated .. twice infact .. in the relevant sections.

Glad you are now up and running.
