### ISSUE TITLE
Synchronization without system login

### ISSUE THREAD

**Issue by Boia11** [abraunegg/onedrive#1095]
I have install onedrive with [instruction](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#arm64-architecture) as root on my little cloud server but I need to login over SSH for syncronized files and directories.
What can I do for running Onedrive sync app in background without login?

**Comment by abraunegg** [comment]
@Boia11 
Please refer to the documentation regarding this topic: [Running 'onedrive' as a system service](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#running-onedrive-as-a-system-service)

**Comment by Boia11** [comment]
I already use [this configuration via systemd](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-root-user-via-systemd-arch-ubuntu-debian-opensuse-fedora) but the monitor and sync start only after SSH login

**Comment by abraunegg** [comment]
@Boia11 
You will need to reach out to who ever provides your cloud server / cloud server Linux OS for support in that regards.

The systemd service should the starting upon restart. I cannot assist you any further at this point. Sorry.

**Comment by abraunegg** [comment]
Closing issue, question answered.

**Comment by Boia11** [comment]
My server use debian 9 and systemd work perfectly...I use your software since 2 yrs and it never worked without root login via ssh terminal

**Comment by abraunegg** [comment]
@Boia11 
Please refer your question to starting a service at reboot to the systemd documentation: https://www.freedesktop.org/wiki/Software/systemd/

I do not write systemd nor can assist further with your question

**Comment by Boia11** [comment]
I ask....It's not properly advised this action but for solved this problem using root user you need to enable lingering for systemd

**USE ONLY AT YOUR OWN RISK AND ONLY IF YOU UNDERSTAND WHAT YOU DOING!**
`loginctl enable-linger root`
