### ISSUE TITLE
business_shared_folders results in segfault if folder name matches part of the name of a shared file

### ISSUE THREAD

**Issue by karlol** [abraunegg/onedrive#1096]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
When the list of business shared folders (.config/onedrive/business_shared_folders) contains a directory name and that directory name matches part of a filename that is checked against the list of business shared folders the sync will try to synchronize the matching file as a folder, resulting in a segfault.

The problem is the matching done in selective.d where any name that contains a string identical to the shared folder name results in a match. A working fix is shown below, but I'm sure there are better fixes as I never used D before. In addition, there should be a check that the matched name is a folder before it tries to sync it as a folder.

```
+++ b/src/selective.d
@@ -160,12 +160,14 @@ final class SelectiveSync
        {
                // if there are no shared folder always return false
                if (businessSharedFoldersList.empty) return false;
-               
-               if (!name.matchFirst(businessSharedFoldersList).empty) {
-                       return true;
-               } else {
-                       return false;
+
+               foreach (businessSharedFolder; businessSharedFoldersList) {
+                   if (!name.matchFirst(regex(r"^"~businessSharedFolder~"$")).empty){
+                          return true;
+                   }
                }
+               return false;
        }

```

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
Debian 10.3
Linux van01 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux

*   Are you using a headless system (no gui) or with a gui installed?
headless

*   OneDrive Account Type
Business
*   Did you build from source or install from a package?
From source

*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
DMD64 D Compiler v2.093.0

*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
$ onedrive --display-config
Configuration file successfully loaded
onedrive version                       = v2.4.6-7-ga3c4ba1
Config path                            = /home/user/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/user/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 3600
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = ~/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = true
business_shared_folders contents:
Tracking
```

*   Provide the version of curl you are using: Output of `curl --version`
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3

*   Is your configured 'sync_dir' a local directory or a network mount point?
local dir

*   If *not* local, provide all the mountpoints in your system: Output of: `mount`

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. Someone shares a file with you named "somedata.xlsx"
2. Someone shares a folder with you named "data"
3. Add the folder "data" to .config/onedrive/business_shared_folders
run onedrive --synchronize --resync

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```
```
$ onedrive --synchronize --resync -v
Using 'user' Config Dir: /home/user/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Using logfile dir: ~/log/onedrive/
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/user/OneDrive
Application version: v2.4.6-7-ga3c4ba1
Account Type: business
Default Drive ID: b!-random
Default Root ID: random
Remaining Free Space: 1093344455405
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: random
Updated Remaining Free Space: 1093344455405
Processing 201 OneDrive items to ensure consistent local state
Processing 234 OneDrive items to ensure consistent local state
Processing 216 OneDrive items to ensure consistent local state
Processing 217 OneDrive items to ensure consistent local state
Processing 217 OneDrive items to ensure consistent local state
Processing 223 OneDrive items to ensure consistent local state
Processing 225 OneDrive items to ensure consistent local state
Processing 231 OneDrive items to ensure consistent local state
Processing 245 OneDrive items to ensure consistent local state
Processing 227 OneDrive items to ensure consistent local state
Processing 239 OneDrive items to ensure consistent local state
Processing 233 OneDrive items to ensure consistent local state
Processing 241 OneDrive items to ensure consistent local state
Processing 12 OneDrive items to ensure consistent local state
Attempting to sync OneDrive Business Shared Folders
Syncing this OneDrive Business Shared Folder: TrendTracking_NN.pptx
OneDrive Business Shared Folder - Shared By:  Name, Name (Name.Name@Company.com)
Applying changes of Path ID: random
OneDrive quota information is set at zero, as this is not our drive id, ignoring
Adding OneDrive root details for processing
Adding OneDrive folder details for processing
Adding 0 OneDrive items for processing from OneDrive folder
Number of items from OneDrive to process: 2
Segmentation fault
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@karlol 
Finally have time to look at this

**Comment by abraunegg** [comment]
@karlol 
Please can you test the following PR against your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1104/head:pr1104
git checkout pr1104
./configure; make clean; make;
```

When running the PR, your version should be `onedrive v2.4.6-9-g4f2afcf` or greater.

With the 'Business Shared Folders' feature, this should only be syncing shared folder - not attempting to sync shared folders & files. What this PR does is tightens the sync matching of shared objects to just folder parent items - which was the original intention of the 'Business Shared Folders' feature.

**Comment by karlol** [comment]
@abraunegg 
Thanks, the fix works fine! 
The correct folder is synced and the shared files are skipped without segfaults. However, it is causing a lot of noise since it prints a warning like that below for what seems to be all files that have been shared with me even though I did not use any debug or verbose flag.
`WARNING: Not syncing this OneDrive Business Shared File: image.png`

**Comment by abraunegg** [comment]
@karlol 
> Thanks, the fix works fine!

Great ... as for the warning line, that was deliberate in the PR to ensure that we were correctly capturing the data and filtering correctly. Will update the PR, but if you are using `--verbose` this will still print to notify that this is not being synced.

**Comment by abraunegg** [comment]
@karlol 
If you rebuild the PR now you should get `onedrive v2.4.6-14-gf44c4a4` as the version where the warning is now in `--verbose` only.

If you can validate this that would be greatly appreciated, then this can be merged into 'master'

**Comment by abraunegg** [comment]
@karlol 
Any update in testing the updated PR?

**Comment by abraunegg** [comment]
PR merged into 'master', closed issue ticket

**Comment by karlol** [comment]
@abraunegg Sorry for the slow response. It looks like the `--verbose` flag does what it should, and the right things are synced. Thanks for the quick update.
