### ISSUE TITLE
Repeated timeouts

### ISSUE THREAD

**Issue by Petemir** [abraunegg/onedrive#1097]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
Hello, I have several OneDrive containers (two for shared Business libraries, one for my normal business account) and encounter several timeout errors when uploading (and in some cases, when downloading) files that I cannot debug. Connectivity seems to be fine, as I don't seem to have major troubles surfing or with other syncing applications. Yesterday at the office, with a very high-speed connection, I could upload several GB; at home, with a 1Mbps upload rate, I am having troubles syncing just a few file changes. If I create some empty files they are uploaded OK, but I already start having timeouts with files around ~200Kb. Sometimes the files are uploaded correctly even when a timeout appears in the log, others I end up with lots of "~tmp" files. 

I saw in other issues that the problem may had to do with DNS issues. I run pihole (DNS sinkhole) here at home, disabled it, but still get the errors. I also tried recreating the containers, while removing the databases files and the refresh tokens from the volumes.

I will send the debug file by e-mail as requested, but just to have them here, I found the following errors:
* For the downloading of a file
```[DEBUG] OneDrive change is a new local item
Downloading file Slides/10-Karnaugh Maps - Combinational-Circuits.pptx ... [DEBUG] Request URL = https://graph.microsoft.com/v1.0/drives/b!HNWqRIhj50ml_zur-nezWqrE-I1mrgBIiqLucCsuX_8GkWm5gB9TTIc3cMQ7gxhR/items/01ZSMKDHD5YR5BRPXDIVAK7QZKERZFVOMB?select=size,malware,file,webUr
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle DD7680
^M                                                                                ^MDownloading   0% |                                        |   ETA   --:--:--:[DEBUG] Raw Error Data: Timeout was reached on handle DD7680
ERROR: File download size mis-match. Increase logging verbosity to determine why.
ERROR: File download hash mis-match. Increase logging verbosity to determine why.
[DEBUG] JSON Message: null
```

* For the upload of a file:
```
[DEBUG] Checking file: ./Midterm/midterm-2020-v1016-solutions.pdf
[DEBUG] skip_file evaluation for: /Midterm/midterm-2020-v1016-solutions.pdf
[DEBUG] File upload destination is users default driveId ..
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/drives/b!HNWqRIhj50ml_zur-nezWqrE-I1mrgBIiqLucCsuX_8GkWm5gB9TTIc3cMQ7gxhR/root:/.%2FMidterm%2Fmidterm-2020-v1016-solutions.pdf:/?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size
[DEBUG] fileDetailsFromOneDrive = onedrive.getPathDetails(path); generated a OneDriveException
Uploading new file ./Midterm/midterm-2020-v1016-solutions.pdf ...
^M                                                                                ^MUploading   0% |                                        |   ETA   --:--:--:
[DEBUG] Fragment: 1 of 1
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle DD7680
^M                                                                                ^MUploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:00 [DEBUG] onedrive.perform() Generated a OneDrive CurlException
File upload session failed - invalid response from OneDrive
```
(btw, there's a weird linebreak character only after "Uploading" lines that kind of breaks the visualization of the output logs)

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
**KUbuntu 20.04 - Linux jakku 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux**
*   Are you using a headless system (no gui) or with a gui installed?
**Kubuntu (KDE), but using Docker for onedrive**
*   OneDrive Account Type
**Business**
*   Did you build from source or install from a package?
**Latest docker image from driveone/onedrive**
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
**N/A**
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
Configuration file successfully loaded
onedrive version                       = v2.4.6-7-ga3c4ba1
Config path                            = /onedrive/conf
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /onedrive/data
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'drive_id'               = REDACTED
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
```
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets 
```

*   Is your configured 'sync_dir' a local directory or a network mount point?
**It is a local directory**

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
It's not clear to me how I can reproduce it because it seems random. Although it seemed to work at the office, I don't see why it shouldn't work at home.

**Complete Verbose Log Output**
I put two error examples earlier in the report. Debug will be sent by e-mail (after submitting the report).

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Verbose Log Output from your error
*   [x] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@Petemir 
Most likely this is to do with your Internet service between you at home and OneDrive. 

Without knowing more at the moent - you are probably being hit by this: https://github.com/abraunegg/onedrive/blob/master/docs/known-issues.md#application-stops-running-without-any-visible-reason

Can you please redo the debug log, this time following https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support

This will show what is occurring at the HTTPS transport layer and provide and indication as to your issue. Given your location, this sort of issue is also 'most prevalent' when interacting with OneDrive farm hosted in the Western Europe Data Centre.

As for the `^M` in the logging output .. I will have to check the files .. that should not be the case ... as in all my logging output there is no issue. It is like a Windows CLRF has been inserted somehow / somewhere - will check.

**Comment by Petemir** [comment]
@abraunegg Thank you for the incredibly quick fast answer :). 

I followed your indications (also did this little improvement #1098]; [wiki](https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support) could be updated to add the Docker example, like [here](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support)), and got the log (sent by e-mail, too, just in case). 

The important part, I would believe:
```
< HTTP/1.1 302 Found^M
< Cache-Control: private^M
< Content-Type: text/plain^M
< Location: https://usi365.sharepoint.com/sites/REDACTED/_layouts/15/download.aspx?UniqueId=REDACTED&Translate=false&tempauth=REDACTED&ApiVersion=2.1^M
< request-id: 56a4f7dd-b5c0-4dc0-843d-8517f6675273^M
< client-request-id: 56a4f7dd-b5c0-4dc0-843d-8517f6675273^M
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Europe","Slice":"SliceC","Ring":"4","ScaleUnit":"001","RoleInstance":"AGSFE_IN_23"}}^M
< Strict-Transport-Security: max-age=31536000^M
< Date: Fri, 16 Oct 2020 10:32:30 GMT^M
< Content-Length: 0^M
< ^M
* Connection #2 to host graph.microsoft.com left intact
* Issue another request to this URL: 'https://usi365.sharepoint.com/sites/REDACTED/_layouts/15/download.aspx?UniqueId=REDACTED&Translate=false&tempauth=REDACTED&ApiVersion=2.1'
* Resolving timed out after 10520 milliseconds
* Closing connection 3
```

The "Resolving timed out" got me to Issue #964, where I saw that maybe the workplace could be blocking this. It made me think of trying with the University VPN and, although it is not a full-tunnel VPN, it started working... and afterwards I ended the VPN connection, and it kept working. Who knows... 

Thank you very much!

**Comment by abraunegg** [comment]
@Petemir 
Glad you have got it sorted. I 100% suspect it is something to do with your OS / choice of platform - something in the firewall rules / local resolution process for systems is failing & timing out - but that gets fixed when your VPN gets activated. I would open a bug against your platform and provide as much detail to them as possible to fix as this is not something I can fix.

In terms of the `^M` in the logging output .. I have checked all the code and there is no stray `^M` anywhere. I suspect again something in your local OS is either changing the files when it is being built, or whatever terminal program you are using is incorrectly interpreting the data and thinking it is a `^M` ... I cannot see / reproduce this. Again, I would open a bug against your platform and provide as much detail to them as possible to fix as this is not something I can fix.
