### ISSUE TITLE
Invalid authentication response from OneDrive. Please check the response uri

### ISSUE THREAD

**Issue by 366Cobra** [abraunegg/onedrive#1099]
Hi,

I have just installed the latest version of Ubuntu LTS (20, 5.4.0-48-generic) and installed the latest available apt onedrive which is version v2.3.9-dev.

When i try to authenticate against my private onedrive account, I can log in and get the URI that I am supposed to paste onto the command line.  Unfortunately I get the error message about the URI being invalid.
Is this a known issue for this version?  Is there a workaround, as I would like to stick with the apt versions, as they update automatically.

**Comment by abraunegg** [comment]
@366Cobra 
> I have just installed the latest version of Ubuntu LTS (20, 5.4.0-48-generic) and installed the latest available apt onedrive which is version v2.3.9-dev.

This is not the latest version. That is > 12 months old. Please refer to https://github.com/abraunegg/onedrive/releases for details & the latest release information.

> Is this a known issue for this version? Is there a workaround, as I would like to stick with the apt versions, as they update automatically.

This package does not update automatically. No one is the Ubuntu package maintainer. If you wish to change this, please become the Ubuntu package maintainer.

To install this client correctly on your OS, please read the install document: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md - specifically:
* https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#important-information-for-all-ubuntu-and-ubuntu-based-distribution-users
