### ISSUE TITLE
Constant disk activity when onedrive --monitor is running

### ISSUE THREAD

**Issue by jeyoung** [abraunegg/onedrive#1102]
### Bug Report Details ###
**Describe the bug**
When running onedrive as a non-root user with

```
systemctl --user enable onedrive
systemctl --user start onedrive
```

onedrive runs as follows `onedrive --monitor`.

When in this mode, there is a constant disk activity as shown by `sudo iotop`. This happens even after a full synchronisation has been completed.

Using the command `watch ls -al ~/.config/onedrive/`, I can see that the database file `items.sqlite3` is constantly written to.

```
Every 2.0s: ls -al /home/jeyoung/.config/onedrive/                              lenny: Wed Oct 21 16:09:12 2020

total 11412
drwxr-xr-x 1 jeyoung jeyoung     232 Oct 21 15:47 .
drwx------ 1 jeyoung jeyoung     674 Oct 20 22:24 ..
-rw-r--r-- 1 jeyoung jeyoung     116 Oct 21 13:18 config
-rw-r--r-- 1 jeyoung jeyoung     116 Oct 21 13:18 .config.backup
-rw-r--r-- 1 jeyoung jeyoung      28 Oct 21 13:18 .config.hash
-rw-r--r-- 1 jeyoung jeyoung 7454720 Oct 21 16:09 items.sqlite3
-rw-r--r-- 1 jeyoung jeyoung   32768 Oct 21 16:08 items.sqlite3-shm
-rw-r--r-- 1 jeyoung jeyoung 4173592 Oct 21 16:09 items.sqlite3-wal
-rw-r--r-- 1 jeyoung jeyoung     437 Oct 21 15:55 refresh_token
-rw-r--r-- 1 jeyoung jeyoung      79 Oct 21 15:46 sync_list
-rw-r--r-- 1 jeyoung jeyoung      28 Oct 21 15:47 .sync_list.hash
```
This is more obvious when `sync_dir` is on an HDD than when it is on an SSD (owing to the audible disk spinning sound). I checked on my laptop with an SSD and saw the same behaviour there. This _probably_ explains why there has been a decrease in battery time on the laptop.

**Application and Operating System Details:**
*   Linux lenny 5.8.0-3-amd64 #1 SMP Debian 5.8.14-1 (2020-10-10) x86_64 GNU/Linux
*   No GUI
*   OneDrive Personal
*   Installed from package: 
```
jeyoung@lenny:~$ onedrive --version
onedrive v2.4.6-1
```

*  OneDrive config:

```
eyoung@lenny:~$ onedrive --display-config
Configuration file successfully loaded
onedrive version                       = v2.4.6-1
Config path                            = /home/jeyoung/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/jeyoung/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp|*_embedded.jpg|*_shotwell.jpg
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 600
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
Documents
Email attachments
Music
Pictures
Projects
Shared
Sound Clips
Videos

Business Shared Folders configured     = false
```
* curl version:

```
jeyoung@lenny:~$ curl --version
curl 7.72.0 (x86_64-pc-linux-gnu) libcurl/7.72.0 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.8.0 nghttp2/1.41.0 librtmp/2.3
Release-Date: 2020-08-19
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

*  `sync_dir` is a local directory
* Count of files:

```
jeyoung@lenny:~$ find ~/OneDrive -type f | wc -l
44263
```

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Start OneDrive Free in monitoring mode with `systemctl --user enable onedrive && systemctl --user start onedrive`.
2.  Leave to run for up to 60 seconds.
3.  Monitor disk activity with `sudo iotop`.
4. Observe disk activity by `onedrive --monitor` in `iotop` output.

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose --resync
```

```
eyoung@lenny:~$ onedrive --synchronize --verbose --resync
Using 'user' Config Dir: /home/jeyoung/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/jeyoung/OneDrive
Application version: v2.4.6-1
Account Type: personal
Default Drive ID: xxx
Default Root ID: xxx!112
Remaining Free Space: 915490740241
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: xxx!112
Updated Remaining Free Space: 915490740241
...
...
```
(NOTE: `xxx` masks an actual key here. It is the same key throughout the output.)

Partial extract of `onedrive --monitor --verbose`. **This appears to never end.**

```
Processing 205 OneDrive items to ensure consistent local state due to sync_list being used
Processing 205 OneDrive items to ensure consistent local state due to sync_list being used
Processing 205 OneDrive items to ensure consistent local state due to sync_list being used
Processing 205 OneDrive items to ensure consistent local state due to sync_list being used
Processing 205 OneDrive items to ensure consistent local state due to sync_list being used
Processing 207 OneDrive items to ensure consistent local state due to sync_list being used
Processing 207 OneDrive items to ensure consistent local state due to sync_list being used
Processing 204 OneDrive items to ensure consistent local state due to sync_list being used
Processing 205 OneDrive items to ensure consistent local state due to sync_list being used
Processing 213 OneDrive items to ensure consistent local state due to sync_list being used
Processing 204 OneDrive items to ensure consistent local state due to sync_list being used
Processing 233 OneDrive items to ensure consistent local state due to sync_list being used
Processing 280 OneDrive items to ensure consistent local state due to sync_list being used
Processing 212 OneDrive items to ensure consistent local state due to sync_list being used
Processing 208 OneDrive items to ensure consistent local state due to sync_list being used
Processing 223 OneDrive items to ensure consistent local state due to sync_list being used
Processing 219 OneDrive items to ensure consistent local state due to sync_list being used
The Microsoft OneNote Notebook 'Documents/Eddy's Notebook' is not supported by this client
Processing 243 OneDrive items to ensure consistent local state due to sync_list being used
The Microsoft OneNote Notebook 'Documents/Eddy's Notebook' is not supported by this client
Processing 219 OneDrive items to ensure consistent local state due to sync_list being used
The Microsoft OneNote Notebook 'Documents/Eddy's Notebook' is not supported by this client
Processing 264 OneDrive items to ensure consistent local state due to sync_list being used
The Microsoft OneNote Notebook 'Documents/Eddy's Notebook' is not supported by this client
Processing 226 OneDrive items to ensure consistent local state due to sync_list being used
The Microsoft OneNote Notebook 'Documents/Eddy's Notebook' is not supported by this client
Processing 239 OneDrive items to ensure consistent local state due to sync_list being used
The Microsoft OneNote Notebook 'Documents/Eddy's Notebook' is not supported by this client
Processing 223 OneDrive items to ensure consistent local state due to sync_list being used
Processing 226 OneDrive items to ensure consistent local state due to sync_list being used
The Microsoft OneNote Notebook 'Documents/Eddy's Notebook' is not supported by this client
Processing 215 OneDrive items to ensure consistent local state due to sync_list being used
Processing 212 OneDrive items to ensure consistent local state due to sync_list being used
Processing 240 OneDrive items to ensure consistent local state due to sync_list being used
Processing 283 OneDrive items to ensure consistent local state due to sync_list being used
The Microsoft OneNote Notebook 'Documents/Eddy's Notebook' is not supported by this client
...
```

**Comment by abraunegg** [comment]
@jeyoung 
To clear 1 item off:
```
Processing 205 OneDrive items to ensure consistent local state due to sync_list being used
```

This is **100%** normal due to you using 'sync_list' - zero issue here.

For the reported performance issue, disk access issue, I need you to provide additional information as per: https://github.com/abraunegg/onedrive/wiki/Generate-system-performance-data-for-performance-related-issues

**Comment by jeyoung** [comment]
@abraunegg -- Thank you for responding. After creating this issue, I looked around and saw your comment about the full scan happening because of the presence of a sync_list. I removed the sync list and repeated the `onedrive --monitor` experiment and observed the same result.

Here I am attaching the performance information.

[cpuinfo.txt](https://github.com/abraunegg/onedrive/files/5418886/cpuinfo.txt)
[meminfo.txt](https://github.com/abraunegg/onedrive/files/5418888/meminfo.txt)
[scaling_available_governors.txt](https://github.com/abraunegg/onedrive/files/5418890/scaling_available_governors.txt)
[scaling_governor.txt](https://github.com/abraunegg/onedrive/files/5418891/scaling_governor.txt)
[iostat.txt](https://github.com/abraunegg/onedrive/files/5418887/iostat.txt)
[strace.txt](https://github.com/abraunegg/onedrive/files/5418892/strace.txt)
[perf.out.gz](https://github.com/abraunegg/onedrive/files/5418957/perf.out.gz)

`perf.out` generated with `perf record --call-graph dwarf --pid 22530` whilst `onedrive --monitor` is running.

Some additional information about the filesystem since `perf` reports a majority of the time spent in the kernel.

```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
/dev/mapper/lenny--vg0-root /               btrfs   defaults        0       0
# /boot was on /dev/sda2 during installation
UUID=3b0ef2cd-871f-4658-bbbf-04611583cdb3 /boot           ext2    defaults        0       2
# /boot/efi was on /dev/sda1 during installation
UUID=7D87-5E8F  /boot/efi       vfat    umask=0077      0       1
/dev/mapper/lenny--vg1-home /home           btrfs   defaults        0       0
/dev/mapper/lenny--vg0-swap none            swap    sw              0       0
/dev/sr0        /media/cdrom0   udf,iso9660 user,noauto     0       0
```

**Comment by abraunegg** [comment]
@jeyoung 
Thanks - however your debugging is not quite right. For example - you ran strace for less than a second against the process ID .. that needs to be much longer, and your perf output is also not right - cannot be used.

Did you install all the required debug symbols, rebuild the client using the debug switch?

Please review https://github.com/abraunegg/onedrive/issues/404 to give you an idea of what your output should look like

**Comment by jeyoung** [comment]
@abraunegg -- Apologies for the strace output being insufficient, I have re-generated a new one but find the output not much different from the one before.

[strace.txt](https://github.com/abraunegg/onedrive/files/5419126/strace.txt)

Regarding the perf output, I recorded it because the output being in constant screen refresh was making it hard to copy-paste into a text file. I was hoping you would be able to read the perf output with `perf report -i perf.out`. 

Interestingly whilst I was waiting to capture a new `perf` output, I noticed the disk was reading **more**. When I checked the output of `onedrive --monitor -vv`, I can see it still doing the same thing as before (read JSON, compare change, etc), except that it is not doing it in bursts now. Here is the previous `perf` output I captured and the new one.

[perf_1.txt](https://github.com/abraunegg/onedrive/files/5419166/perf_1.txt)
[perf_2.txt](https://github.com/abraunegg/onedrive/files/5419167/perf_2.txt)

I followed the instructions to build `onedrive` in debug mode. The Makefile contains `DEBUG = yes`.

The output of `onedrive --version`:

```
onedrive v2.4.6-8-g11e094c
```
```
jeyoung@lenny:~/Temp/onedrive-diag$ ldd /usr/bin/onedrive
	linux-vdso.so.1 (0x00007ffdfeb40000)
	libsqlite3.so.0 => /lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f3c2e6f9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3c2e6d7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3c2e593000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3c2e58d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3c2e573000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3c2e3ae000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3c2ecd3000)
```

OneDrive size:
```
jeyoung@lenny:~/OneDrive$ du -sh .
212G	.
```

Mount option:
```
jeyoung@lenny:~/OneDrive$ mount | grep home
/dev/mapper/lenny--vg1-home on /home type btrfs (rw,relatime,space_cache,subvolid=5,subvol=/)
```
(I will update to **noatime** -- as per your recommendation on #404) and re-test shortly.)
Like #404 I am running `onedrive` on an LVM file system itself on LUKS.
```
jeyoung@lenny:~/Temp/onedrive-diag$ sort -u /proc/crypto | grep module
module       : aesni_intel
module       : ansi_cprng
module       : blake2b_generic
module       : ccm
module       : cmac
module       : crc32c_generic
module       : crc32c_intel
module       : crc32_pclmul
module       : crct10dif_generic
module       : crct10dif_pclmul
module       : cryptd
module       : ctr
module       : drbg
module       : ecdh_generic
module       : ghash_clmulni_intel
module       : jitterentropy_rng
module       : kernel

eyoung@lenny:~/Temp/onedrive-diag$ sudo cryptsetup status /dev/mapper/sdb1_crypt
/dev/mapper/sdb1_crypt is active and is in use.
  type:    LUKS2
  cipher:  aes-xts-plain64
  keysize: 512 bits
  key location: keyring
  device:  /dev/sdb1
  sector size:  512
  offset:  32768 sectors
  size:    3906994176 sectors
  mode:    read/write
  flags:   discards 

```

**Comment by abraunegg** [comment]
@jeyoung 
Any update on this issue in regards to switching to noatime ?

**Comment by jeyoung** [comment]
@abraunegg -- Sorry, I have been busy replacing this HDD with an SSD. I am also set the filesystem on this one as EXT4 to see if that has any effect.

Unfortunately, `noatime` didn't make a difference.

I can see that the code compares modified time and not access time, which suggests that 'relatime' should not make any difference in comparison other than a potential performance problem _But_ checking on another machine, I found that OneDrive Free detects a file as changed locally even if I just open it. Which is very strange.

I followed up with another experiment. I did a `btrfs filesystem defragment` on `sync_dir` and found all files to be marked as updated locally. At this point my hypothesis is that one machine reads the files causing the files to be marked as updated, to be updated and then sync'ed on the other machine in an endless loop.

**Comment by abraunegg** [comment]
@jeyoung 
If you have multiple systems all using the same OneDrive account then yes - you could be in that sort of scenario. This is not something that can be easily solved - as technically, the file is updated, modified, needs to be synced / DB updated.

A suggestion here is to set your machine(s) as the 'source of truth' - and utilise the '--local-first' flag. This will treat the local files as the correct starting point, rather than OneDrive. This ensures that OneDrive is in a consistent state with the local machine first, before any new changes are downloaded from OneDrive.

**Comment by jeyoung** [comment]
@abraunegg -- Given that we are two to think that is a possibility, I will try your suggestion of `--local-first` and see if that improves things. Do you know if that is the approach of OneDrive on Windows?

**Comment by abraunegg** [comment]
@jeyoung 
> Do you know if that is the approach of OneDrive on Windows? 

I do not - sorry.

**Comment by jeyoung** [comment]
@abraunegg -- Posting an update for future reference---

`--local-first` seems to have resolved the problem of constant disk activity. I also see faster speed and more consistency in the synchronisation and monitoring.

Personally I think `--local-first` should be the default given that it produces a behaviour that _seems_ to be similar to the one in Windows.

**Comment by abraunegg** [comment]
@jeyoung 
Thanks for the feedback.

Is this issue now solved? If so, can you close the issue ticket please.

**Comment by jeyoung** [comment]
@abraunegg -- Closing the ticket now. Your help with this issue is much appreciated.
