### ISSUE TITLE
Packaging/building on Debian 10 fails.

### ISSUE THREAD

**Issue by threepistons** [abraunegg/onedrive#1105]
**Given:** Debian 10, DMD 2.094 from the Dlang website, downloaded zip file from https://github.com/abraunegg/onedrive/releases/tag/v2.4.6, and the dependencies installed using Apt, and the `man` help system installed from Apt.

**When I:** build OneDrive using the usual trio of `./configure; make; sudo checkinstall` in order to make an installable and uninstallable deb file.

**I get:**
```
Installing with make install...

========================= Installation results ===========================
/usr/bin/install -c -D onedrive /usr/local/bin/onedrive
/usr/bin/install -c -D onedrive.1 /usr/local/share/man/man1/onedrive.1
/usr/bin/install: cannot create directory '/usr/local/share/man/man1': No such file or directory
make: *** [Makefile:109: install] Error 1

****  Installation failed. Aborting package creation.
```
**I expected:** the makefile not to try to put manual pages into directories that don't exist on my system.

If I add a line like `if [ ! -d "$(DESTDIR)$(mandir)/man1" ] ; then mkdir $(DESTDIR)$(mandir)/man1 ; fi` to the makefile to create the missing directory, the `checkinstall` gets a bit further down the makefile before again trying to put a file into a non-existent directory.

**Comment by abraunegg** [comment]
@threepistons 
Whilst this is being investigated, please can you utilise this package: https://packages.debian.org/sid/net/onedrive

**Comment by norbusan** [comment]
@threepistons 
I can reproduce this with `checkinstall` but this is a bug of checkinstall, and not of the Makefile here.

We use `install -D` which generates all leading directories if necessary, so no changes should be necessary.

If checkinstall does something different, in particular ignore the option -D, then we cannot do a lot here.

**Comment by abraunegg** [comment]
@threepistons 
`checkinstall` has major issues and contains many security issues. Please stop using it.

As such, this issue is invalid, so I am closing it. 

If you want to use your own package, or build your own package, please use the Debian source packages that were linked to above.

**Comment by threepistons** [comment]
> checkinstall has major issues and contains many security issues.

This I did not know, thank you.

I am still using Ubuntu 18.04 and Debian 10 so I have difficulty meeting the dependencies for the pre-built packages for 20.04 and sid.
