### ISSUE TITLE
Tune required access rights?

### ISSUE THREAD

**Issue by paaland** [abraunegg/onedrive#1106]
Is there any way to tune the access rights this app requires?

My IT department says there is no way they'll approve this app as long as it requires "Edit or delete items in all site collections". That apparently lets it delete sites and stuff from sharepoint.

Any way to limit the app's rights (and thus features) to only the users files and profile?

![image](https://user-images.githubusercontent.com/172243/97009269-2ead4980-1544-11eb-8272-5489ca8c8674.png)

**Comment by abraunegg** [comment]
@paaland 
 > Is there any way to tune the access rights this app requires?

No there is not. The application 'requests' access, but what access is given is governed by the Office365 / SharePoint permissions.

The text from Microsoft is miss-leading for 'all' items - but in reality access is given for 'all' items that you have *access* to, with the access rights that *you* have been configured with.

Suggest also that your IT Department read up on permissions, permission inheritance & delegated permissions for Office365 / SharePoint as by their response to you they appear to me as not understanding how access is granted.

**Comment by abraunegg** [comment]
Closing issue as questioned answered
