### ISSUE TITLE
Local changes are uploads are delayed

### ISSUE THREAD

**Issue by ricwtk** [abraunegg/onedrive#1109]
### Bug Report Details ###
**Describe the bug**
The local changes are not uploaded immediately but only updated in roughly a period of `monitor-interval`.

**Application and Operating System Details:**
* OS: Manjaro Linux with Linux kernel of 5.8.16
* OneDrive Account Type: Business
* Installed from the `onedrive-abraunegg` on Arch Linux Repository.
* OneDrive Application Version: `onedrive v2.4.6`
* OneDrive Application Configuration:
```
Configuration file successfully loaded
onedrive version                       = v2.4.6
Config path                            = /home/ricwtk/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /mnt/data/Linux/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /home/ricwtk/.log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
*
Research
!Research/datavis*
Business Shared Folders configured     = false
```
* Provide the version of curl you are using: 
```bash
curl 7.72.0 (x86_64-pc-linux-gnu) libcurl/7.72.0 OpenSSL/1.1.1h zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-08-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```
* sync_dir is a local directory
* The OneDrive folder is can be accessed by two OS but only synced through Linux.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. Start the synchronization process.
2. Make changes to a file.
3. Check the command line outputs.
4. Only see the synchronization takes place after 5-7 minutes.

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
-- Reboot --
Oct 25 13:57:47 zenux systemd[1286]: Started OneDrive Free Client.
Oct 25 13:57:47 zenux onedrive[1298]: Configuration file successfully loaded
Oct 25 13:57:52 zenux onedrive[1298]: Configuring Global Azure AD Endpoints
Oct 25 13:57:53 zenux onedrive[1298]: Initializing the Synchronization Engine ...
Oct 25 13:57:53 zenux onedrive[1298]: Initializing monitor ...
Oct 25 13:57:53 zenux onedrive[1298]: OneDrive monitor interval (seconds): 300
Oct 25 14:10:56 zenux onedrive[1298]: Deleting item from OneDrive: Research/index.js
Oct 25 14:10:57 zenux onedrive[1298]: Deleting item from OneDrive: index.js
```

The files were deleted at around 14:03pm.

**Comment by abraunegg** [comment]
@ricwtk 
This would indicate that your 'sync_dir' partition format is *not* EXT{2,3,3}, XFS, ZFS, BTRFS but something else.

What is the partition format of your 'sync_dir' ... it may be *local*, but because you are sharing this, it is something else.

Most likely whatever partition format it is, it does not support 'inotify'

Please provide a verbose debug log as per support requirements.

**Comment by ricwtk** [comment]
I see. The files are on NTFS partition. I suppose that would be the issue? In the older version, it's working fine. Meanwhile, I'm waiting for the verbose log to be generated. Will post once it's ready.

**Comment by abraunegg** [comment]
@ricwtk 
> I see. The files are on NTFS partition. 

NTFS volumes do not support 'inotify' - never has, never will.


> I suppose that would be the issue? In the older version, it's working fine.

What older version are you talking about here?
* Skilion - v1.x -> v1.1.3
* this one - v2.x +

A change was made to increase the 'monitor_interval' from 45 seconds -> 300 seconds quite a while back. Perhaps it is because of this setting that it 'appeared' to be working correctly for you, but in reality - your client never was using 'inotify' if your data was always on an NTFS formatted volume.

**Comment by ricwtk** [comment]
Good to know that. I was using this one, installed a while back directly by compiling the source. I just switched to the one on Arch Linux Repo a couple of days ago to make sure it's updated. I checked the default config of the file I pulled from github previously, the `monitor-interval` was actually at 45 seconds. Thanks!
