### ISSUE TITLE
Not working - unable to authenticate

### ISSUE THREAD

**Issue by fgauvrit** [abraunegg/onedrive#111]
### Bug Report Details ###
**Describe the bug**
Error when launching onedrive

**Application and Operating System Details:**
 - OS: Linux FGA-E6540.HOME 4.4.140-62-default #1 SMP Tue Jul 17 12:14:34 UTC 2018 (951943d) x86_64 x86_64 x86_64 GNU/Linux (Leap 42.3)
- Application version: onedrive v2.0.2-23-ge922a7d

**To Reproduce**
from root :
zypper install libcurl-devel sqlite-devel sqlite3-devel dmd phobos-devel-static phobos-devel
git config --global http.sslVerify false
git clone https://github.com/abraunegg/onedrive
make
make install
onedrive

from user :
/usr/local/bin/onedrive
```
std.net.curl.CurlException@std/net/curl.d(4332): Peer certificate cannot be authenticated with given CA certificates on handle 1B4C3F0
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x63f40e]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x63f381]
??:? void std.net.curl.Curl._check(int) [0x61051c]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x610950]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x60f40c]
src/util.d:125 bool util.testNetwork() [0x5c73c2]
src/main.d:151 _Dmain [0x5a4b85]
```

**Comment by abraunegg** [comment]
This is your issue:

```
Peer certificate cannot be authenticated with given CA certificates
```

You need to ensure your CA certificates for your OS are updated and current.

**Comment by abraunegg** [comment]
Why are you also doing this:

```
git config --global http.sslVerify false
```

Why are you having to perform a git pull without validating SSL ?

**Comment by abraunegg** [comment]
you either have a gateway device doing SSL scanning and presenting a self signed certificate, and that self signed CA needs to be added into your Linux system, or your Leap 42.3 system certificates are totally out of date (which I doubt)

This is not a 'onedrive' client issue. This is an issue with your local environment which you need to resolve.

**Comment by fgauvrit** [comment]
I see, but I had it working a few weeks ago...

I have the 3 following packages for the CA certificates :
zypper search ca-cert
i+ | ca-certificates         | Utilities for system wide CA certificate installation | package   
i+ | ca-certificates-cacert  | CAcert root certificates                              | package   
i+ | ca-certificates-mozilla | CA certificates for OpenSSL

Maybe a link somewhere which is missing... No cert problem with citrix receiver or internet.

**Comment by fgauvrit** [comment]
Name        : ca-certificates-cacert
Version     : 1
Release     : 24.1
Architecture: noarch
Install Date: Mon Nov  6 19:36:34 2017
Group       : Productivity/Networking/Security
Size        : 12034
License     : SUSE-CacertRoot
Signature   : RSA/SHA256, Fri Mar 17 19:44:35 2017, Key ID b88b2fd43dbdc284
Source RPM  : ca-certificates-cacert-1-24.1.src.rpm
Build Date  : Fri Mar 17 19:44:30 2017
Build Host  : lamb62
Relocations : (not relocatable)
Packager    : http://bugs.opensuse.org
Vendor      : openSUSE
URL         : http://www.cacert.org
Summary     : CAcert root certificates
Description :
This package contains the root certificates from cacert.org
Distribution: openSUSE Leap 42.3

**Comment by fgauvrit** [comment]
Pity... stuck with a cert issue...

**Comment by fgauvrit** [comment]
No gateway here, just facing internet via a box. No firewall.

**Comment by abraunegg** [comment]
Unless you can do a git clone without needing this `git config --global http.sslVerify false` your system is broken for SSL stuff.

Chat with support teams for opensuse to resolve.

**Comment by fgauvrit** [comment]
OK, thanks, I understand.

**Comment by fgauvrit** [comment]
One last question : One which distribution do you make your tests ?

**Comment by abraunegg** [comment]
All testing (application build & application run) is done on:
* CentOS (x86, x86_64) 
* Debian (x86, x86_64, armhf)
* Ubuntu (x86, x86_64)

Every commit / pull request is automatically tested via Travis CI on:
* Debian (x86, armhf)
* Ubuntu (x86_64)

**Comment by fgauvrit** [comment]
OK, Thanks.

**Comment by abraunegg** [comment]
@fgauvrit 
Unsure if you resolved your local issue regarding certificates, however this URL details a potential solution to your problem:
https://forums.opensuse.org/showthread.php/530383-Looking-for-ca-certificates-crt-file-where-is-it

Solution:
> I found the solution by retracing my steps and following the file on Tumbleweed - actually the file /etc/ssl/certs/ca-certificates.crt was just a symlink to /var/lib/ca-certificates/ca-bundle.pem, which both OpenSUSE 42.3 and Tumbleweed had.

**Comment by fgauvrit** [comment]
Thanks again for your help, the certificate problem is fixed and I was able to start onedrive. However, I have opened another bug that occurs on one of my desktop...
