### ISSUE TITLE
OneDrive Business Shared Folders: help w/config file

### ISSUE THREAD

**Issue by martinpescador** [abraunegg/onedrive#1110]
Hi,

Basic sync works fine, thanks for useful tool!

But: I do not understand the format of the config file: :~/.config/onedrive/business_shared_folders

More specifically, what is meant by: "On each new line, list the OneDrive Business Shared Folder you wish to sync" ?

It would be very useful to see an example.

And if I get it to work, where will the shared folders sync to? Will they appear as subdirs in /home/me/OneDrive ?

Hoping someone can help!

**Comment by abraunegg** [comment]
@martinpescador 

> But: I do not understand the format of the config file: :~/.config/onedrive/business_shared_folders
>
> More specifically, what is meant by: "On each new line, list the OneDrive Business Shared Folder you wish to sync" ?

There is an example in the configuration: https://github.com/abraunegg/onedrive/blob/master/docs/BusinessSharedFolders.md#configuring-onedrive-business-shared-folders

> And if I get it to work, where will the shared folders sync to? Will they appear as subdirs in /home/me/OneDrive ?

The shared folders will appear as folders under your configured 'sync_dir' location.

**Comment by abraunegg** [comment]
Closing issue as question answered
