### ISSUE TITLE
upload goes to personal folder not shared drive.

### ISSUE THREAD

**Issue by smatsmats** [abraunegg/onedrive#1111]
### Bug Report Details ###
**Describe the bug**
Despite being configured to upload to shared drive files go into personal folder.  
Shared drive is within our 'site' (no world icon)
This could be as simple as not escaping '(' and ')' but I've tried every combination of quotes and nothing changes.  

The command I'm using is:
```
./onedrive/onedrive --synchronize --sync-shared-folders --verbose --upload-only
```

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
```
Linux ip-172-31-9-180.us-west-2.compute.internal 4.14.198-152.320.amzn2.x86_64 #1 SMP Wed Sep 23 23:57:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
*   Are you using a headless system (no gui) or with a gui installed?
headless
*   OneDrive Account Type
business
*   Did you build from source or install from a package?
built from source
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
```
DMD64 D Compiler v2.094.1
Copyright (C) 1999-2020 by The D Language Foundation, All Rights Reserved written by Walter Bright
```
*   OneDrive Application Version: Output of `onedrive --version`
```
[ec2-user@ip-172-31-9-180 ~]$ ./onedrive/onedrive --version
onedrive v2.4.6-8-g11e094c
```
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
Configuration file successfully loaded
onedrive version                       = v2.4.6-8-g11e094c
Config path                            = /home/ec2-user/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/ec2-user/mmarch_copy/mm13
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = true
business_shared_folders contents:
"PR-2020-00691 (Southerland)"
```
*   Provide the version of curl you are using: Output of `curl --version`
```
curl 7.61.1 (x86_64-koji-linux-gnu) libcurl/7.61.1 OpenSSL/1.0.2k zlib/1.2.7 libidn2/2.3.0 libssh2/1.4.3 nghttp2/1.41.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy Metalink 
```
*   Is your configured 'sync_dir' a local directory or a network mount point?
local
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
n/a
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
```
[ec2-user@ip-172-31-9-180 ~]$ ./onedrive/onedrive --list-shared-folders
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...

Listing available OneDrive Business Shared Folders:
---------------------------------------
Shared Folder:   PR-2020-00691 (Southerland)
Shared By:       UW-IT (uwitprr@uw.edu)
```
I frankly don't know where else the shared drive is shared but this tool doesn't even try and upload to it so I don't think that matters.  

**Complete Verbose Log Output**
emailed to support@mynas.com.au

thanks,
steve

**Comment by abraunegg** [comment]
@smatsmats 
This is all due to your configuration.

In your configuration, you are specifying:
```
"PR-2020-00691 (Southerland)"
```
when you should just be specifying:
```
PR-2020-00691 (Southerland)
```

With your current configuration, you are trying to sync / match `"PR-2020-00691 (Southerland)"` which does not exist, which is why you are seeing this sort of behavior. As per the configuration example (https://github.com/abraunegg/onedrive/blob/master/docs/BusinessSharedFolders.md#configuring-onedrive-business-shared-folders) - folders with spaces in their names do not need to be quoted out.

Please correct your configuration and re-test.

**Comment by smatsmats** [comment]
Thanks, but removing the quotes doesn’t make a difference.  I had also tried single quotes and ‘^’ escape chars for the parenthesis.  

thanks,
steve

[ec2-user@ip-172-31-9-180 ~]$ ./onedrive/onedrive --display-config
Configuration file successfully loaded
onedrive version                       = v2.4.6-8-g11e094c
Config path                            = /home/ec2-user/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/ec2-user/mmarch_copy/mm13
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = true
business_shared_folders contents:
PR-2020-00691 (Southerland)
[ec2-user@ip-172-31-9-180 ~]$ ./onedrive/onedrive --synchronize --sync-shared-folders --verbose --upload-only --verbose
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/ec2-user
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/ec2-user/.config
[DEBUG] configDirName: Configuring application to use default config path
Using 'user' Config Dir: /home/ec2-user/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
[DEBUG] refreshTokenFilePath = /home/ec2-user/.config/onedrive/refresh_token
[DEBUG] deltaLinkFilePath = /home/ec2-user/.config/onedrive/delta_link
[DEBUG] databaseFilePath = /home/ec2-user/.config/onedrive/items.sqlite3
[DEBUG] databaseFilePathDryRun = /home/ec2-user/.config/onedrive/items-dryrun.sqlite3
[DEBUG] uploadStateFilePath = /home/ec2-user/.config/onedrive/resume_upload
[DEBUG] userConfigFilePath = /home/ec2-user/.config/onedrive/config
[DEBUG] syncListFilePath = /home/ec2-user/.config/onedrive/sync_list
[DEBUG] systemConfigFilePath = /etc/onedrive/config
[DEBUG] businessSharedFolderFilePath = /home/ec2-user/.config/onedrive/business_shared_folders
Configuration file successfully loaded
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /home/ec2-user/mmarch_copy/mm13
[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive Service
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
[DEBUG] Downgrading all HTTP operations to HTTP/1.1 by default
[DEBUG] clientId    = d50ca740-c83f-4d1b-b616-12c519384f0c
[DEBUG] companyName = abraunegg
[DEBUG] appTitle    = OneDrive Client for Linux
Opening the item database ...
[DEBUG] Using database file: /home/ec2-user/.config/onedrive/items.sqlite3
All operations will be performed in: /home/ec2-user/mmarch_copy/mm13
[DEBUG] Loading user configured business_shared_folders file ...
[DEBUG] business_shared_folders: PR-2020-00691 (Southerland)
[DEBUG] Configuring skip_dir ...
[DEBUG] skip_dir: 
[DEBUG] Configuring skip_dir_strict_match ...
[DEBUG] skip_dir_strict_match: false
[DEBUG] Configuring skip_dotfiles ...
[DEBUG] skip_dotfiles: false
[DEBUG] Configuring skip_file ...
[DEBUG] skip_file: ~*|.~*|*.tmp
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root
[DEBUG] OneDrive Account Details:      {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#drives\/$entity","createdBy":{"user":{"displayName":"System Account"}},"createdDateTime":"2014-05-06T21:41:06Z","description":"","driveType":"business","id":"b!Wt0AOgHWb0yxPBGAYo9fdZ2S-JSZzltCmDHMlkmUmhMMMyXHAejGRbWCxs1yUUaW","lastModifiedBy":{"user":{"displayName":"stephen w mats mats","email":"willey@uw.edu","id":"baf82045-d974-419f-9250-057a1eb9460a"}},"lastModifiedDateTime":"2020-10-26T00:37:50Z","name":"OneDrive","owner":{"user":{"displayName":"stephen w mats mats","email":"willey@uw.edu","id":"baf82045-d974-419f-9250-057a1eb9460a"}},"quota":{"deleted":40553422,"remaining":5497514661146,"state":"normal","total":5497558138880,"used":0},"webUrl":"https:\/\/uwnetid-my.sharepoint.com\/personal\/willey_uw_edu\/Documents"}
[DEBUG] OneDrive Account Root Details: {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#users('baf82045-d974-419f-9250-057a1eb9460a')\/drive\/root\/$entity","createdDateTime":"2014-05-06T21:41:06Z","fileSystemInfo":{"createdDateTime":"2014-05-06T21:41:06Z","lastModifiedDateTime":"2020-10-26T00:37:50Z"},"folder":{"childCount":0},"id":"012URFCQV6Y2GOVW7725BZO354PWSELRRZ","lastModifiedDateTime":"2020-10-26T00:37:50Z","name":"root","parentReference":{"driveId":"b!Wt0AOgHWb0yxPBGAYo9fdZ2S-JSZzltCmDHMlkmUmhMMMyXHAejGRbWCxs1yUUaW","driveType":"business"},"root":{},"size":0,"webUrl":"https:\/\/uwnetid-my.sharepoint.com\/personal\/willey_uw_edu\/Documents"}
Application version: v2.4.6-8-g11e094c
Account Type: business
Default Drive ID: b!Wt0AOgHWb0yxPBGAYo9fdZ2S-JSZzltCmDHMlkmUmhMMMyXHAejGRbWCxs1yUUaW
Default Root ID: 012URFCQV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 5497514661146
Fetching details for OneDrive Root
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
[DEBUG] performSync API scan triggers
[DEBUG] -----------------------------
[DEBUG] fullScanRequired =                   false
[DEBUG] syncListConfiguredFullScanOverride = false
[DEBUG] -----------------------------
[DEBUG] ################################################## NEW SYNC ##################################################
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/mmarch_copy/mm13
[DEBUG] Processing DB entries for this driveId: b!Wt0AOgHWb0yxPBGAYo9fdZ2S-JSZzltCmDHMlkmUmhMMMyXHAejGRbWCxs1yUUaW
Processing .
[DEBUG] skip_dir evaluation for: root
The directory has not changed
Processing 121tutorials.mbox
[DEBUG] skip_file evaluation for: 121tutorials.mbox
The file has not changed
Uploading new items of ~/mmarch_copy/mm13
[DEBUG] Checking file: ./121tutorials.mbox
[DEBUG] skip_file evaluation for: /121tutorials.mbox
[DEBUG] ################################################ SYNC COMPLETE ###############################################
(dmd-2.094.1)[ec2-user@ip-172-31-9-180 ~]$

**Comment by abraunegg** [comment]
@smatsmats 
```
onedrive/onedrive --synchronize --sync-shared-folders --verbose --upload-only --verbose
```

So with this - you are wanting your data to go to the 'shared folder' but ... your data resides in `~/mmarch_copy/mm13` and *not* `~/mmarch_copy/mm13/PR-2020-00691 (Southerland)/`

The client has no idea that you want your data to go in `PR-2020-00691 (Southerland)` because that folder does not exists locally to the client .. this is why you are seeing this sort of behavior.

Corrective actions:
1. Reconfigure 'sync_dir' to be default and not `/home/ec2-user/mmarch_copy/mm13`
2. Create (given you are trying to just use upload only) all the required folder structures, including the 'Shared Business Folder' names within your ~/OneDrive location
3. Put the data you want to sync into the data locations needed locally
4. Test your sync with `--dry-run`
5. Correct any issues
6. Sync your data

**Comment by smatsmats** [comment]
Thanks, but there is still something I’m not getting about this configuration.  Doing what you suggest simply creates a PR-2020-00691 (Southerland) directory in my person onedrive root directory and doesn’t put the file in the shared drive.  

[ec2-user@ip-172-31-9-180 ~]$ ./onedrive/onedrive --display-config
Configuration file successfully loaded
onedrive version                       = v2.4.6-8-g11e094c
Config path                            = /home/ec2-user/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/ec2-user/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = true
business_shared_folders contents:
# comments are nice
PR-2020-00691 (Southerland)
[ec2-user@ip-172-31-9-180 ~]$ ls -lR OneDrive/
OneDrive/:
total 0
drwxrwxr-x 2 ec2-user ec2-user 31 Oct 26 01:50 PR-2020-00691 (Southerland)

OneDrive/PR-2020-00691 (Southerland):
total 3908
-rw-rw-r-- 1 ec2-user ec2-user 3999119 Oct 26 01:33 121tutorials.mbox
(dmd-2.094.1)[ec2-user@ip-172-31-9-180 ~]$ ./onedrive/onedrive --synchronize --sync-shared-folders --verbose --upload-only --verbose
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/ec2-user
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/ec2-user/.config
[DEBUG] configDirName: Configuring application to use default config path
Using 'user' Config Dir: /home/ec2-user/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
[DEBUG] refreshTokenFilePath = /home/ec2-user/.config/onedrive/refresh_token
[DEBUG] deltaLinkFilePath = /home/ec2-user/.config/onedrive/delta_link
[DEBUG] databaseFilePath = /home/ec2-user/.config/onedrive/items.sqlite3
[DEBUG] databaseFilePathDryRun = /home/ec2-user/.config/onedrive/items-dryrun.sqlite3
[DEBUG] uploadStateFilePath = /home/ec2-user/.config/onedrive/resume_upload
[DEBUG] userConfigFilePath = /home/ec2-user/.config/onedrive/config
[DEBUG] syncListFilePath = /home/ec2-user/.config/onedrive/sync_list
[DEBUG] systemConfigFilePath = /etc/onedrive/config
[DEBUG] businessSharedFolderFilePath = /home/ec2-user/.config/onedrive/business_shared_folders
Configuration file successfully loaded
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /home/ec2-user/OneDrive
[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive Service
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
[DEBUG] Downgrading all HTTP operations to HTTP/1.1 by default
[DEBUG] clientId    = d50ca740-c83f-4d1b-b616-12c519384f0c
[DEBUG] companyName = abraunegg
[DEBUG] appTitle    = OneDrive Client for Linux
Opening the item database ...
[DEBUG] Using database file: /home/ec2-user/.config/onedrive/items.sqlite3
All operations will be performed in: /home/ec2-user/OneDrive
[DEBUG] Loading user configured business_shared_folders file ...
[DEBUG] business_shared_folders: # comments are nice
[DEBUG] business_shared_folders: PR-2020-00691 (Southerland)
[DEBUG] Configuring skip_dir ...
[DEBUG] skip_dir: 
[DEBUG] Configuring skip_dir_strict_match ...
[DEBUG] skip_dir_strict_match: false
[DEBUG] Configuring skip_dotfiles ...
[DEBUG] skip_dotfiles: false
[DEBUG] Configuring skip_file ...
[DEBUG] skip_file: ~*|.~*|*.tmp
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root
[DEBUG] OneDrive Account Details:      {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#drives\/$entity","createdBy":{"user":{"displayName":"System Account"}},"createdDateTime":"2014-05-06T21:41:06Z","description":"","driveType":"business","id":"b!Wt0AOgHWb0yxPBGAYo9fdZ2S-JSZzltCmDHMlkmUmhMMMyXHAejGRbWCxs1yUUaW","lastModifiedBy":{"user":{"displayName":"stephen w mats mats","email":"willey@uw.edu","id":"baf82045-d974-419f-9250-057a1eb9460a"}},"lastModifiedDateTime":"2020-10-26T01:57:44Z","name":"OneDrive","owner":{"user":{"displayName":"stephen w mats mats","email":"willey@uw.edu","id":"baf82045-d974-419f-9250-057a1eb9460a"}},"quota":{"deleted":52553426,"remaining":5497502661142,"state":"normal","total":5497558138880,"used":0},"webUrl":"https:\/\/uwnetid-my.sharepoint.com\/personal\/willey_uw_edu\/Documents"}
[DEBUG] OneDrive Account Root Details: {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#users('baf82045-d974-419f-9250-057a1eb9460a')\/drive\/root\/$entity","createdDateTime":"2014-05-06T21:41:06Z","fileSystemInfo":{"createdDateTime":"2014-05-06T21:41:06Z","lastModifiedDateTime":"2020-10-26T01:57:44Z"},"folder":{"childCount":0},"id":"012URFCQV6Y2GOVW7725BZO354PWSELRRZ","lastModifiedDateTime":"2020-10-26T01:57:44Z","name":"root","parentReference":{"driveId":"b!Wt0AOgHWb0yxPBGAYo9fdZ2S-JSZzltCmDHMlkmUmhMMMyXHAejGRbWCxs1yUUaW","driveType":"business"},"root":{},"size":0,"webUrl":"https:\/\/uwnetid-my.sharepoint.com\/personal\/willey_uw_edu\/Documents"}
Application version: v2.4.6-8-g11e094c
Account Type: business
Default Drive ID: b!Wt0AOgHWb0yxPBGAYo9fdZ2S-JSZzltCmDHMlkmUmhMMMyXHAejGRbWCxs1yUUaW
Default Root ID: 012URFCQV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 5497502661142
Fetching details for OneDrive Root
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root
OneDrive Root does not exist in the database. We need to add it.
[DEBUG] Handing a OneDrive 'root' change
[DEBUG] Update/Insert local database with item details
[DEBUG] item details: Item("b!Wt0AOgHWb0yxPBGAYo9fdZ2S-JSZzltCmDHMlkmUmhMMMyXHAejGRbWCxs1yUUaW", "012URFCQV6Y2GOVW7725BZO354PWSELRRZ", "root", dir, "", "", 2020-Oct-26 01:57:44Z, "", "", "", "", "", "", "Y")
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
[DEBUG] performSync API scan triggers
[DEBUG] -----------------------------
[DEBUG] fullScanRequired =                   false
[DEBUG] syncListConfiguredFullScanOverride = false
[DEBUG] -----------------------------
[DEBUG] ################################################## NEW SYNC ##################################################
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/OneDrive
[DEBUG] Processing DB entries for this driveId: b!Wt0AOgHWb0yxPBGAYo9fdZ2S-JSZzltCmDHMlkmUmhMMMyXHAejGRbWCxs1yUUaW
Processing .
[DEBUG] skip_dir evaluation for: root
The directory has not changed
Uploading new items of ~/OneDrive
[DEBUG] Checking local path: ./PR-2020-00691 (Southerland)
OneDrive Client requested to create remote path: ./PR-2020-00691 (Southerland)
[DEBUG] Attempting to query OneDrive for this path: ./PR-2020-00691 (Southerland)
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/drives/b!Wt0AOgHWb0yxPBGAYo9fdZ2S-JSZzltCmDHMlkmUmhMMMyXHAejGRbWCxs1yUUaW/root:/.%2FPR-2020-00691%20(Southerland)?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size
[DEBUG] response = onedrive.getPathDetails(path); generated a OneDriveException
The requested directory to create was not found on OneDrive - creating remote directory: ./PR-2020-00691 (Southerland)
[DEBUG] Adding to database: Item("b!Wt0AOgHWb0yxPBGAYo9fdZ2S-JSZzltCmDHMlkmUmhMMMyXHAejGRbWCxs1yUUaW", "012URFCQXYY7HRSHWQIRB3U5YXFVLCACW4", "PR-2020-00691 (Southerland)", dir, "\"{19CFC7F8-D01E-4344-BA77-172D56200ADC},1\"", "\"c:{19CFC7F8-D01E-4344-BA77-172D56200ADC},0\"", 2020-Oct-26 01:59:04Z, "012URFCQV6Y2GOVW7725BZO354PWSELRRZ", "", "", "", "", "", "Y")
Successfully created the remote directory ./PR-2020-00691 (Southerland) on OneDrive
[DEBUG] Checking file: ./PR-2020-00691 (Southerland)/121tutorials.mbox
[DEBUG] skip_file evaluation for: /PR-2020-00691 (Southerland)/121tutorials.mbox
[DEBUG] File upload destination is users default driveId ..
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root:/.%2FPR-2020-00691%20(Southerland)%2F121tutorials.mbox:/?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size
[DEBUG] fileDetailsFromOneDrive = onedrive.getPathDetails(path); generated a OneDriveException
Uploading new file ./PR-2020-00691 (Southerland)/121tutorials.mbox ... 
Uploading   0% |                                        |   ETA   --:--:--:                                                                            
[DEBUG] Fragment: 1 of 1
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:02                                                                             
done.
[DEBUG] Adding to database: Item("b!Wt0AOgHWb0yxPBGAYo9fdZ2S-JSZzltCmDHMlkmUmhMMMyXHAejGRbWCxs1yUUaW", "012URFCQRG4QYUZYNJ25DYXDHYBZIQJG5K", "121tutorials.mbox", file, "\"{4C31E426-A9E1-47D7-8B8C-F80E51049BAA},5\"", "\"c:{4C31E426-A9E1-47D7-8B8C-F80E51049BAA},2\"", 2020-Oct-26 01:33:11Z, "012URFCQXYY7HRSHWQIRB3U5YXFVLCACW4", "", "", "kI4SUUi7aYb8yBrveM84q9zZgX8=", "", "", "Y")
Remaining free space on OneDrive: 5497498662023
[DEBUG] ################################################ SYNC COMPLETE ###############################################
[ec2-user@ip-172-31-9-180 ~]$

**Comment by abraunegg** [comment]
@smatsmats 
> Thanks, but there is still something I’m not getting about this configuration.  Doing what you suggest simply creates a PR-2020-00691 (Southerland) directory in my person onedrive root directory and doesn’t put the file in the shared drive.

Please can you provide the full verbose debug log (attached as an attachment) via email for analysis.

**Comment by smatsmats** [comment]
thanks,
steve

**Comment by abraunegg** [comment]
@smatsmats 
Still waiting for the debug log via email. Any update as to when you can send this through?

**Comment by smatsmats** [comment]
Thanks, meant to send it last night.
steve

**Comment by smatsmats** [comment]
[debug_output.log](https://github.com/abraunegg/onedrive/files/5441384/debug_output.log)
I see the attachment is getting stripped-out when sent via email.  uploaded here.

**Comment by abraunegg** [comment]
@smatsmats 
OK .. what you have provided is a HTTPS Debug Log, not a Debug Log.

I am going to have to try and replicate this scenario - as, because you have already synced the desired folder to your remote, the client thinks the shared folder is local, rather than remote.

What I need to replicate are all your steps, starting at the beginning, to work out what is going wrong and where.

**Comment by abraunegg** [comment]
@smatsmats 
I have been able to replicate your issue, but this issue *only* occurs when:
* You initially configure OneDrive Business Shared Folders
* You use --upload-only
* You use --resync

In all other scenario's, the database contains the folder details for the Shared Folder, thus no issue exists.

To resolve your issue, please can you test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1127/head:pr1127
git checkout pr1127
./configure; make clean; make;
```

When running the PR, your version should be `onedrive v2.4.6-18-g1a3def1` or greater.

In addition to this, you may need to cleanup your folder structures locally & on OneDrive so that you can test the fix correctly.

**Comment by galettof** [comment]
Hello! I am experiencing essentially the same issue. I set up a shared folder in business_shared_folders, and synced with --sync-shared-folders. The shared folder was downloaded to my local OneDrive folder. After adding some files locally and syncing again, the entire shared folder was recreated in my cloud OneDrive folder with the new files, but the new files were not added to the actual shared folder online. I am on version v2.4.11-7-gb0771f7.

I can send a debug log, if it helps.

**Comment by abraunegg** [comment]
@galettof 
Please do not respond to closed issues
