### ISSUE TITLE
third parties data sharing

### ISSUE THREAD

**Issue by zud** [abraunegg/onedrive#1115]
**Is your feature request related to a problem? Please describe.**
Does OneDrive Client for Linux share any onedrive user data with third parties? 

**Describe the solution you'd like**
Could you update your "terms of service"?

**Comment by abraunegg** [comment]
@zud 
> Does OneDrive Client for Linux share any onedrive user data with third parties?

No data is *EVER* shared with 3rd parties from this client. Feel free to review the code. What Microsoft shares, you need to refer to their Terms and Conditions.

> Could you update your "terms of service"?

Will look into it.
