### ISSUE TITLE
Select directory for O365 Shared Library

### ISSUE THREAD

**Issue by tedtms** [abraunegg/onedrive#1116]
A particular problem I'm running into is that when I sync an O365 Shared Library, it drops all of the synced contents into the root of my OneDrive folder. 

Ideally, I'd like to be able to specify a folder within the sync root that each drive_id can sync to. 

Is this already possible in the given configuration options? If not, I think it'd be an excellent feature.

Thanks for your hard work on this! It makes us Linux enterprise users' lives much easier!

Cheers,
Ted

**Comment by abraunegg** [comment]
@tedtms 
This is not possible.

The reason for this is multiple, and would require a major rework of the architecture of how the application currently stores files in the database, locally and references them - sorry.

**Comment by abraunegg** [comment]
Closing issue as question answered
