### ISSUE TITLE
Cannot upload file changes/creation: JSONValue is not a object

### ISSUE THREAD

**Issue by ABCMoNa** [abraunegg/onedrive#1118]
### Bug Report Details ###
**Describe the bug**
When files are modified, onedrive reports ```Cannot upload file changes/creation: JSONValue is not a object```. I have not tried to verify whether or not uploading actually fails.

**Application and Operating System Details:**
*   _Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`:_
Ubuntu 20.04 LTS
```Linux hostname 5.9.1-050901-lowlatency #202010170731 SMP PREEMPT Sat Oct 17 07:46:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux``` (Ubuntu mainline-ppa kernel, but I think it also happens with the default one)
*   _Are you using a headless system (no gui) or with a gui installed?_
With GUI: Standard gnome-shell/mutter DE
*   _OneDrive Account Type_
Microsoft365 business plan (we have Sharepoint + Onedrive)
*   _Did you build from source or install from a package?_
Using PPA: https://launchpad.net/~yann1ck/+archive/ubuntu/onedrive
*   _If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`_
N/A
*   _OneDrive Application Version: Output of `onedrive --version`_
```onedrive v2.4.6-0~202010041107~ubuntu20.04.1```
*   _OneDrive Application Configuration: Output of `onedrive --display-config`_
```
onedrive version                       = v2.4.6-0~202010041107~ubuntu20.04.1
Config path                            = /home/myuser/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/myuser/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   _Provide the version of curl you are using: Output of `curl --version`_
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
*   _Is your configured 'sync_dir' a local directory or a network mount point?_
A local directory.
*   _If *not* local, provide all the mountpoints in your system: Output of: `mount`_
N/A
*   _What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f`_ 
ext4 on top of dmcrypt-luks1 on top of a gpt partition on a NVMe device
(I prefer not to share full lsblk -f output, but have verified this is the correct file system / mount point)
*   _Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time_
The OneDrive folder is not shared or used on any other devices. An iOS device with the official OneDrive application also has access to this OneDrive account and the data stored there.

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

--> Will do so if still needed, see below.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

--> Will provide reproducer if still needed, see below.

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

--> Will do so if still needed, see below.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

N/A

**Additional context**

**I just realized I am running two onedrive processes:**
```
myuser@hostname:~$ ps auxw | grep oned
myuser        1861  0.0  0.1 722216 25496 ?        Ssl  09:28   0:01 /usr/bin/onedrive --monitor
myuser        2697  0.0  0.1 722220 25912 ?        Sl   09:28   0:01 /usr/bin/onedrive --monitor
myuser        6854  0.0  0.0   9400   664 pts/0    S+   10:54   0:00 grep --color=auto oned
```

This is likely the root cause of these warnings. I think I added the onedrive process to "Startup Applications" (a Gnome specific mechanism to start applications on login), because, by the time I installed this package, I don't think it started the onedrive miniotring process itself.

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

---

Original report:

I'm using onedrive ```v2.4.6-0~202010041107~ubuntu20.04.1``` on Ubuntu 20.04, with a Microsoft365 business plan (we have Sharepoint + Onedrive). It works fine, generally, which is great.

When, however, I edit a text file in a text editor, save it  first time, then edit it more and save again, I run into this error message:
```Cannot upload file changes/creation: JSONValue is not a object```
(reported to the gnome-shell GUI as a pop-up).

I assume this means that edited files which are already present (in earlier versions) on the target (OneDrive) are never uploaded, which bears a potential for data loss.

I'm happy to do more testing as needed, please instruct.

**Comment by abraunegg** [comment]
@ABCMoNa 
Please follow the correct support proceedures as per: https://github.com/abraunegg/onedrive#reporting-issues

What you need to do is:
1. Edit your post above and provide all the details as required to assist with diagnosing / replicating the issue
2. Replicate the issue whilst generating a verbose debug log
3. Provide that verbose debug log.

Many thanks in advance.

**Comment by ABCMoNa** [comment]
Long story short: It seems that I have been running two ```onedrive --monitor``` processes lately. I believe this to be the source of the problem.

**Comment by abraunegg** [comment]
@ABCMoNa 
Thanks for the update.

If you can generate the debug log in this scenario - 3 clients running - that will at least track down how and where this error is being generated from so it can be fixed.

**Comment by abraunegg** [comment]
@ABCMoNa 
Any update in generating the debug logs for this scenario?
