### ISSUE TITLE
Database error, only on dry-run, works OK on normal sync

### ISSUE THREAD

**Issue by Swallowtail23** [abraunegg/onedrive#1120]
### Bug Report Details ###
**Describe the bug**

`onedrive --synchronize --upload-only --dry-run`
fails with:
`An internal database error occurred: database disk image is malformed`

Running without --dry-run completes successfully.

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`

CentOS 8
`Linux emp80.simonandkate.lan 4.18.0-193.19.1.el8_2.x86_64 #1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

*   Are you using a headless system (no gui) or with a gui installed?
Headless

*   OneDrive Account Type
Personal

*   Did you build from source or install from a package?
Source

*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
DMD64 D Compiler v2.094.1

*   OneDrive Application Version: Output of `onedrive --version`
onedrive v2.4.6-13-ge81de98

*   OneDrive Application Configuration: Output of `onedrive --display-config`
Configuration file successfully loaded
onedrive version                       = v2.4.6-13-ge81de98
Config path                            = /root/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /root/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false

*   Provide the version of curl you are using: Output of `curl --version`
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1c zlib/1.2.11 brotli/1.0.6 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.9.0/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05

*   Is your configured 'sync_dir' a local directory or a network mount point?
Local

*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
N/A

*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
XFS
nvme0n1
└─nvme0n1p1 xfs                                        cc596646-c8c6-4712-a0c1-e747bd6a355d /mnt/external

*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
OneDrive sync'ed to from several machines and devices, concurrently, however this server's folder only exists on this device and at OneDrive, only sync'ed with this server. 

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
Run onedrive --synchronize --upload-only --dry-run --verbose --verbose - fails with db error
Run without dry-run completes OK.

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):

```
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /root
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /root/.config
[DEBUG] configDirName: Configuring application to use default config path
Using 'user' Config Dir: /root/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
[DEBUG] refreshTokenFilePath = /root/.config/onedrive/refresh_token
[DEBUG] deltaLinkFilePath = /root/.config/onedrive/delta_link
[DEBUG] databaseFilePath = /root/.config/onedrive/items.sqlite3
[DEBUG] databaseFilePathDryRun = /root/.config/onedrive/items-dryrun.sqlite3
[DEBUG] uploadStateFilePath = /root/.config/onedrive/resume_upload
[DEBUG] userConfigFilePath = /root/.config/onedrive/config
[DEBUG] syncListFilePath = /root/.config/onedrive/sync_list
[DEBUG] systemConfigFilePath = /etc/onedrive/config
[DEBUG] businessSharedFolderFilePath = /root/.config/onedrive/business_shared_folders
Configuration file successfully loaded
DRY-RUN Configured. Output below shows what 'would' have occurred.
[DEBUG] Removing items-dryrun.sqlite3 as it still exists for some reason
[DEBUG] Copying items.sqlite3 to items-dryrun.sqlite3 to use for dry run operations
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /root/OneDrive
Using logfile dir: /var/log/onedrive/
[DEBUG] Process ID: 7FA7F4E23E80
[DEBUG] User UID:   0
[DEBUG] User GID:   0
[DEBUG] User Name:  root
[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive Service
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
[DEBUG] Downgrading all HTTP operations to HTTP/1.1 by default
[DEBUG] clientId    = d50ca740-c83f-4d1b-b616-12c519384f0c
[DEBUG] companyName = abraunegg
[DEBUG] appTitle    = OneDrive Client for Linux
Opening the item database ...
[DEBUG] Using database file: /root/.config/onedrive/items-dryrun.sqlite3

An internal database error occurred: database disk image is malformed
```
Without dry-run:
```
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /root
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /root/.config
[DEBUG] configDirName: Configuring application to use default config path
Using 'user' Config Dir: /root/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
[DEBUG] refreshTokenFilePath = /root/.config/onedrive/refresh_token
[DEBUG] deltaLinkFilePath = /root/.config/onedrive/delta_link
[DEBUG] databaseFilePath = /root/.config/onedrive/items.sqlite3
[DEBUG] databaseFilePathDryRun = /root/.config/onedrive/items-dryrun.sqlite3
[DEBUG] uploadStateFilePath = /root/.config/onedrive/resume_upload
[DEBUG] userConfigFilePath = /root/.config/onedrive/config
[DEBUG] syncListFilePath = /root/.config/onedrive/sync_list
[DEBUG] systemConfigFilePath = /etc/onedrive/config
[DEBUG] businessSharedFolderFilePath = /root/.config/onedrive/business_shared_folders
Configuration file successfully loaded
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /root/OneDrive
Using logfile dir: /var/log/onedrive/
[DEBUG] Process ID: 7F313E406E80
[DEBUG] User UID:   0
[DEBUG] User GID:   0
[DEBUG] User Name:  root
[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive Service
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
[DEBUG] Downgrading all HTTP operations to HTTP/1.1 by default
[DEBUG] clientId    = d50ca740-c83f-4d1b-b616-12c519384f0c
[DEBUG] companyName = abraunegg
[DEBUG] appTitle    = OneDrive Client for Linux
Opening the item database ...
[DEBUG] Using database file: /root/.config/onedrive/items.sqlite3
All operations will be performed in: /root/OneDrive
[DEBUG] Configuring skip_dir ...
[DEBUG] skip_dir:
[DEBUG] Configuring skip_dir_strict_match ...
[DEBUG] skip_dir_strict_match: false
[DEBUG] Configuring skip_dotfiles ...
[DEBUG] skip_dotfiles: false
[DEBUG] Configuring skip_file ...
[DEBUG] skip_file: ~*|.~*|*.tmp
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root
[DEBUG] OneDrive Account Details:      {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#drives\/$entity","driveType":"personal","id":"4ecf809b65b10cbd","owner":{"user":{"displayName":"Simon Wilson","id":"4ecf809b65b10cbd"}},"quota":{"deleted":468289296,"remaining"$
[DEBUG] OneDrive Account Root Details: {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#users('simon%40simonandkate.net')\/drive\/root\/$entity","cTag":"adDo0RUNGODA5QjY1QjEwQ0JEITExMi42MzczOTcyODIyODAxMDAwMDA","createdBy":{"user":{"displayName":"Simon Wilson","id$
Application version: v2.4.6-13-ge81de98
Account Type: personal
Default Drive ID: 4ecf809b65b10cbd
Default Root ID: 4ECF809B65B10CBD!112
Remaining Free Space: 1336186282630
Fetching details for OneDrive Root
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
[DEBUG] performSync API scan triggers
[DEBUG] -----------------------------
[DEBUG] fullScanRequired =                   false
[DEBUG] syncListConfiguredFullScanOverride = false
[DEBUG] -----------------------------
[DEBUG] ################################################## NEW SYNC ##################################################
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/OneDrive
[DEBUG] Processing DB entries for this driveId: 4ecf809b65b10cbd
Processing .
[DEBUG] skip_dir evaluation for: root
The directory has not changed
Processing EMP80-sync
[DEBUG] skip_dir evaluation for: EMP80-sync
The directory has not changed
Processing EMP80-sync/sync
[DEBUG] skip_dir evaluation for: sync
The directory has not changed
Processing EMP80-sync/sync/logs
[DEBUG] skip_dir evaluation for: logs
The directory has not changed
Processing EMP80-sync/sync/logs/backup_vms.08302020_1727PM.log
[DEBUG] skip_file evaluation for: backup_vms.08302020_1727PM.log
The file has not changed
Processing EMP80-sync/sync/logs/backup_vms.08302020_2141PM.log
[DEBUG] skip_file evaluation for: backup_vms.08302020_2141PM.log
The file has not changed
Processing EMP80-sync/sync/logs/backup_vms.08312020_1937PM.log
[DEBUG] skip_file evaluation for: backup_vms.08312020_1937PM.log
The file has not changed
Processing EMP80-sync/sync/logs/backup_vms.09022020_1021AM.log
[DEBUG] skip_file evaluation for: backup_vms.09022020_1021AM.log
The file has not changed
Processing EMP80-sync/sync/logs/backup_vms.09022020_2142PM.log
[DEBUG] skip_file evaluation for: backup_vms.09022020_2142PM.log
The file has not changed
Processing EMP80-sync/sync/logs/backup_vms.09072020_0430AM.log
[DEBUG] skip_file evaluation for: backup_vms.09072020_0430AM.log
The file has not changed
Processing EMP80-sync/sync/logs/backup_vms.10052020_0430AM.log
[DEBUG] skip_file evaluation for: backup_vms.10052020_0430AM.log
The file has not changed
Processing EMP80-sync/sync/emp81-2020-08-30.tar.gz
[DEBUG] skip_file evaluation for: emp81-2020-08-30.tar.gz
The file has not changed
Processing EMP80-sync/sync/emp01-2020-08-30.tar.gz
[DEBUG] skip_file evaluation for: emp01-2020-08-30.tar.gz
The file has not changed
Processing EMP80-sync/sync/emp86-2020-08-31.tar.gz
[DEBUG] skip_file evaluation for: emp86-2020-08-31.tar.gz
The file has not changed
Processing EMP80-sync/sync/emp75-2020-09-02.tar.gz
[DEBUG] skip_file evaluation for: emp75-2020-09-02.tar.gz
The file has not changed
Processing EMP80-sync/sync/emp07-2020-09-02.tar.gz
[DEBUG] skip_file evaluation for: emp07-2020-09-02.tar.gz
The file has not changed
Processing EMP80-sync/sync/emp01-2020-10-05.tar.gz
[DEBUG] skip_file evaluation for: emp01-2020-10-05.tar.gz
The file has not changed
Processing EMP80-sync/sync/emp86-2020-10-05.tar.gz
[DEBUG] skip_file evaluation for: emp86-2020-10-05.tar.gz
The file has not changed
Processing EMP80-sync/sync/emp07-2020-10-05.tar.gz
[DEBUG] skip_file evaluation for: emp07-2020-10-05.tar.gz
The file has not changed
Processing EMP80-sync/sync/emp81-2020-10-05.tar.gz
[DEBUG] skip_file evaluation for: emp81-2020-10-05.tar.gz
The file has not changed
Processing EMP80-sync/sync/emp75-2020-10-05.tar.gz
[DEBUG] skip_file evaluation for: emp75-2020-10-05.tar.gz
The file has not changed
Uploading new items of ~/OneDrive
[DEBUG] Checking local path: ./EMP80-sync
[DEBUG] Checking local path: ./EMP80-sync/sync
[DEBUG] Checking local path: ./EMP80-sync/sync/logs
[DEBUG] Checking file: ./EMP80-sync/sync/logs/backup_vms.08302020_1727PM.log
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/logs/backup_vms.08302020_1727PM.log
[DEBUG] Checking file: ./EMP80-sync/sync/logs/backup_vms.08302020_2141PM.log
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/logs/backup_vms.08302020_2141PM.log
[DEBUG] Checking file: ./EMP80-sync/sync/logs/backup_vms.08312020_1937PM.log
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/logs/backup_vms.08312020_1937PM.log
[DEBUG] Checking file: ./EMP80-sync/sync/logs/backup_vms.09022020_1021AM.log
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/logs/backup_vms.09022020_1021AM.log
[DEBUG] Checking file: ./EMP80-sync/sync/logs/backup_vms.09022020_2142PM.log
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/logs/backup_vms.09022020_2142PM.log
[DEBUG] Checking file: ./EMP80-sync/sync/logs/backup_vms.09072020_0430AM.log
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/logs/backup_vms.09072020_0430AM.log
[DEBUG] Checking file: ./EMP80-sync/sync/logs/backup_vms.10052020_0430AM.log
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/logs/backup_vms.10052020_0430AM.log
[DEBUG] Checking file: ./EMP80-sync/sync/emp81-2020-08-30.tar.gz
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/emp81-2020-08-30.tar.gz
[DEBUG] Checking file: ./EMP80-sync/sync/emp01-2020-08-30.tar.gz
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/emp01-2020-08-30.tar.gz
[DEBUG] Checking file: ./EMP80-sync/sync/emp86-2020-08-31.tar.gz
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/emp86-2020-08-31.tar.gz
[DEBUG] Checking file: ./EMP80-sync/sync/emp75-2020-09-02.tar.gz
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/emp75-2020-09-02.tar.gz
[DEBUG] Checking file: ./EMP80-sync/sync/emp07-2020-09-02.tar.gz
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/emp07-2020-09-02.tar.gz
[DEBUG] Checking file: ./EMP80-sync/sync/emp01-2020-10-05.tar.gz
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/emp01-2020-10-05.tar.gz
[DEBUG] Checking file: ./EMP80-sync/sync/emp86-2020-10-05.tar.gz
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/emp86-2020-10-05.tar.gz
[DEBUG] Checking file: ./EMP80-sync/sync/emp75-2020-10-05.tar.gz
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/emp75-2020-10-05.tar.gz
[DEBUG] Checking file: ./EMP80-sync/sync/emp07-2020-10-05.tar.gz
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/emp07-2020-10-05.tar.gz
[DEBUG] Checking file: ./EMP80-sync/sync/emp81-2020-10-05.tar.gz
[DEBUG] skip_file evaluation for: /EMP80-sync/sync/emp81-2020-10-05.tar.gz
[DEBUG] ################################################ SYNC COMPLETE ###############################################
```

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by Swallowtail23** [comment]
```
[root@emp80 onedrive]# pwd
/root/.config/onedrive
[root@emp80 onedrive]# ll
total 140
-rw-r--r-- 1 root root  1296 Oct 29 23:03 config
-rw-r--r-- 1 root root 36864 Oct 31 17:31 items-dryrun.sqlite3
-rw-r--r-- 1 root root 32768 Oct 31 18:03 items-dryrun.sqlite3-shm
-rw-r--r-- 1 root root 24752 Oct 29 23:04 items-dryrun.sqlite3-wal
-rw-r--r-- 1 root root 36864 Oct 31 17:31 items.sqlite3
-rw-r--r-- 1 root root   437 Oct 31 18:03 refresh_token
```

**Comment by Swallowtail23** [comment]
Manually removing the dryrun sqlite files allows the dry-run operation to proceed and complete. 

Looks like a previous dry-run corrupted the sqlite db.

Is there a way to have the client handle that a little more gracefully?

**Comment by abraunegg** [comment]
@Swallowtail23 
Thanks for reporting the issue, however I am unable to replicate this. Regardless, please can you test & validate the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1121/head:pr1121
git checkout pr1121
./configure; make clean; make;
```

When running the PR, your version should be `onedrive v2.4.6-15-g05f2e02` or greater.

**Comment by Swallowtail23** [comment]
I put back in the dry-run sqlite files which caused the problem, updated per your PR, and ran:

`onedrive --synchronize --upload-only --dry-run --verbose --verbose`

...and the dry-run finished OK.

**Comment by Swallowtail23** [comment]
Thank you 👍 

BTW, I sent an email to the support email address - can you advise?
Hi there, 

I have a question please for configuration of the linux onedrive client (which is great, by the way, thank you!).
My question is on remote delete with upload only. 
I'll describe how I'm using it, and then the question should make sense.

I have multiple servers running the client, each set to run as a daemon on CentOS linux. Each server has ONLY one command override set in ~/.config/onedrive/config:

  upload_only = "true"

Server1 has ONLY one folder in ~/OneDrive - "EMD80-sync" (with symlinks in it to data folders). That folder has about 70GB of files which have synced to OneDrive.
Server2 has ONLY one folder in ~/OneDrive - "EMD75-sync" (with symlinks in it to data folders). That folder has about 1.5TB of files which are currently syncing to OneDrive.

At the moment those folders are syncing to OneDrive, and in OneDrive online I see those two folders alongside all other folders already there:

E.g. 

Apps
Desktop
EMP75-sync
EMP80-sync
Music
Pictures
etc...

The objective is to have each server keep THEIR folder backed up and synced on OneDrive, with the server as the 'master', leaving everything else on OneDrive alone.

To just keep each server's ~/OneDrive/EMP* folders sync'ed, should I set the no-remote-delete flag in config to protect other files OUTSIDE of those folders? That flag is NOT currently set.

In reference to upload-only USAGE.md states:

_Note: If a file or folder is present on OneDrive, that does not exist locally, it will be removed. If the data on OneDrive should be kept, the following should be used:_

All of the folders outside the EMP folder from each of the servers ARE present on OneDrive, they DO NOT exist locally on the servers... but are not being removed. I'm assuming that the "will be removed" in this instance only applies to what is inside the server's sync'ed folder? but want to be sure.

Can you advise please?

Thanks from Brisbane - I see you are in Melbourne, I hope you are enjoying being out of lock-down!

**Comment by abraunegg** [comment]
@Swallowtail23 
Thanks for the confirmation regarding the fix - will merge this into master.

RE: your usage question

In regards using `--no-remote-delete` it all comes down to the client configuration and what ‘sync_dir’ is set to.

What the client does, it replicates what is in this configured location – and, with `--upload-only` will delete anything that is not within ‘sync_dir’. A misconception here is that ‘upload-only’ is upload only – yes, but not accurate. What it does is it uploads your local state to OneDrive, (1-way Sync) without downloading any changes.

In your specific circumstance, if nothing else is on each server (and the intention is nothing ever will be), then the client, will operate as required, but depending on your backup rotations locally, you may want to utilise the `--no-remote-delete` flag to ensure OneDrive keeps any ‘deleted’ local backup.

I am going to assume for now, that ‘sync_dir’ is configured to point to `~/OneDrive`. To better handle the one-way sync, utilise the `--single-directory` option on each server. This way if anything ever goes into your ~/OneDrive folder, it will not foul up your data and delete all other data on OneDrive

**Example:**
```
onedrive (--synchronize|--monitor) --upload-only --verbose --single-directory <folder> (--no-remote-delete)
```

Hope this helps answer this question.
