### ISSUE TITLE
Wrong behavior: If local contents exist in skip_dir folders, they will be uploaded

### ISSUE THREAD

**Issue by dersuchmann** [abraunegg/onedrive#1122]
# Bug Report Details
## Describe the bug

Downloaded some files from my OneDrive, then added some subdirectories to skip_dir. When executing `onedrive --synchronize`, these subdirectories are not downloaded, but the client tries to *upload* these directories/their contents from local to the server, which I believe shouldn't be the case.

### Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: uname -a
Regolith Linux (basically Ubuntu 20.04 + i3wm + GNOME tools)
```Linux dersuchmann-Akoya-S4220-MD99810 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

### Are you using a headless system (no gui) or with a gui installed?
with GUI (inside a terminal emulator within i3wm)

### OneDrive Account Type
Personal

### Did you build from source or install from a package?
The PPM recommended on the website

### If you installed from source, what is your DMD or LDC compiler version: dmd --version or ldmd2 --version
N/A

### OneDrive Application Version: Output of onedrive --version
onedrive v2.4.6-0[tilde]202010041108[tilde]ubuntu20.04.1

### OneDrive Application Configuration: Output of onedrive --display-config
```
Configuration file successfully loaded
onedrive version                       = v2.4.6-0[tilde]202010041107[tilde]ubuntu20.04.1
Config path                            = /home/dersuchmann/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/dersuchmann/OneDrive
Config option 'skip_dir'               = Filme und Serien (synced)/Test Ordner|Filme und Serien (synced)/Test Ordner Kopie|Dokumente/carbon|Uni/0*|Uni/Uni-Videos|Uni/12-S19/03-Planning|Z_BlogSicherungenOneNoteUndLinkListen/Website-Downloads/TEMP
Config option 'skip_file'              = TiddlyStorage/docs/book_kernels*
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

### Provide the version of curl you are using: Output of curl --version
curl is not installed

### Is your configured 'sync_dir' a local directory or a network mount point?
Local

### If not local, provide all the mountpoints in your system: Output of: mount
N/A

### What partition format type does your configured 'sync_dir' reside on? Output of: lsblk -f
```
sda                                                                               
├─sda1  vfat                  0617-E7B3                              64,4M    33% /boot/efi
├─sda2                                                                            
├─sda3  ntfs   Boot           CEBC1477BC145BF1                                    
├─sda4  ntfs                  B06E00B46E00757E                                    
├─sda5  ntfs   Recover        B8F23466F2342AD0                                    
├─sda6  vfat   PRC_RP         2C8A-FA5D                                           
├─sda7  ext4                  2f2e2e80-7a6f-498c-90ce-e5cf1c4e6849   78,5G    13% /
├─sda8  ext4                  480a91f8-45ac-4ab5-bc14-7837fed82aa0   11,1G    85% /home
├─sda9  ntfs   regolith-share 0D1D01715F7A419C                                    
└─sda10 swap                  8abaf4f5-598b-48f7-b8a7-9cd7ec8458d5                [SWAP]
```

### Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
OneDrive is synced with several Windows devices, however this is the only linux device with which I try to access the account.

### To Reproduce
Steps to reproduce the behavior if not causing an application crash:
I would assume you could do a full sync and then exclude some directory via skip_dir and do a resync. I cannot test this right now as I only have my 100GB OneDrive and I do not want to mess with this setup further, whcih might result in having to sync all these files again or anything.

### Complete Verbose Log Output
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):

Only partial because it would be verrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrry long.
```
The requested directory to create was found on OneDrive - skipping creating the directory: ./Uni/06-SS16/DIS_II/ProjectRepo/WindowsFormsApplication1/WindowsFormsApplication1
The parent for this path is in the local database - adding requested path (./Uni/06-SS16/DIS_II/ProjectRepo/WindowsFormsApplication1/WindowsFormsApplication1) to database
Requested file to upload exists on OneDrive - local database is out of sync for this file: ./Uni/06-SS16/DIS_II/ProjectRepo/WindowsFormsApplication1/WindowsFormsApplication1/StatusEventArgs.cs
Updating the local database with details for this file: ./Uni/06-SS16/DIS_II/ProjectRepo/WindowsFormsApplication1/WindowsFormsApplication1/StatusEventArgs.cs
Requested file to upload exists on OneDrive - local database is out of sync for this file: ./Uni/06-SS16/DIS_II/ProjectRepo/WindowsFormsApplication1/WindowsFormsApplication1/HandEventArgs.cs
Updating the local database with details for this file: ./Uni/06-SS16/DIS_II/ProjectRepo/WindowsFormsApplication1/WindowsFormsApplication1/HandEventArgs.cs
```
This should not be uploaded because `Uni/0*` is in skip_dir

**Comment by abraunegg** [comment]
@dersuchmann 
Thanks for reporting the issue. Please can you test & validate the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1125/head:pr1125
git checkout pr1125
./configure; make clean; make;
```

When running the PR, your version should be `onedrive v2.4.6-17-g0173e89` or greater.
