### ISSUE TITLE
Is dockerized onedrive trying to clone the whole onedrive from cloud to local?

### ISSUE THREAD

**Issue by otakenz** [abraunegg/onedrive#1126]
Hi, I am trying out the dockerized onedrive by following this guide https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md 

Then I noticed that it is trying to clone the whole onedrive from cloud to local?

Can I get confirmation on this? I am worry that I do not have enough space to clone the whole onedrive locally....

**Comment by otakenz** [comment]
Or are they anyway to narrow down the folder that i want to sync in onedrive? 

I noticed its mounting the whole onedrive locally?
-v "${onedriveDir}:/onedrive/data"

Anyway to narrow down the scope, because I do not have enough local space to clone the whole onedrive

**Comment by abraunegg** [comment]
@otakenz 
> Then I noticed that it is trying to clone the whole onedrive from cloud to local? Can I get confirmation on this?

Correct, the client sync's your data. That is the nature of a sync action.

> Or are they anyway to narrow down the folder that i want to sync in onedrive?

Please refer to the usage documentation on configuring the client:
* https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md
* https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md#6-edit-the-config

**Comment by abraunegg** [comment]
Closing issue as question answered
