### ISSUE TITLE
Old version in ubuntu au archive

### ISSUE THREAD

**Issue by CaptainPi-PiLabs** [abraunegg/onedrive#1130]
Just tried installing this today. Tried a simple apt-get when I saw onedrive but when trying to run the login it fails. I think this is due to a old client id for the oauth which I saw mentioned somewhere. Looked here and found the ppa repo. au version is 2.3.13 whereas the ppa version is 2.4.6. If the au version no longer works it would be good if that got removed.

**Comment by abraunegg** [comment]
@CaptainPi-PiLabs 

Feel free to become the package maintainer for Ubuntu to keep this up to date.

This is precisely the reason why this warning exists: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#important-information-for-all-ubuntu-and-ubuntu-based-distribution-users
