### ISSUE TITLE
Hard coding client id is not ideal.

### ISSUE THREAD

**Issue by ELadner** [abraunegg/onedrive#1135]
Because of the change of the client id (#770) - this caused problems for people that already had a working setup.  These application ID's are tied to GUID's in each site's AD setup and permissions are tied to that ID, so providing no way to change it (short of editing the code) is not ideal.  Perhaps make it a value in the config file?

**Comment by abraunegg** [comment]
Please refer to the documentation and the following: https://github.com/abraunegg/onedrive/issues/835

The application ID is *not* hardcoded, and can be changed.

Please read the documentation:
* https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md
* https://github.com/abraunegg/onedrive/blob/master/docs/national-cloud-deployments.md#step-4-configure-the-onedrive-client-to-use-new-application-registration
