### ISSUE TITLE
skip some files

### ISSUE THREAD

**Issue by fengmao31** [abraunegg/onedrive#1138]
manjaro20
![image](https://user-images.githubusercontent.com/19343842/98891862-0af17980-24da-11eb-8c7c-2124b8724199.png)
i don't set sync_list. why it skip files.
![image](https://user-images.githubusercontent.com/19343842/98891989-4c822480-24da-11eb-9713-742fc13f94cd.png)

**Comment by abraunegg** [comment]
@fengmao31 
It is skipping files due to invalid names - as per the application output.

Please review: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#local-file-and-folder-naming-conventions and https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file
