### ISSUE TITLE
Opened / locked files, skip and retry later?

### ISSUE THREAD

**Issue by devalian** [abraunegg/onedrive#1139]
Hi, im trying to sync my network file share to onedrive from ubuntu to onedrive for business. 

however, during working hour, there are files that is opened and locked by user. for example microsoft access mdb files, instead of skipping it and retry later when the files it opened, this onedrive sync client will retry 3 times and killed the synchronization job. 

is there any option i can adjust my issue? 
- either skip and retry this file later, until the file is closed
- do a shadow copy (or equivalent) data sync with lagged data

Much appreciated of your suggestion.

**Comment by abraunegg** [comment]
@devalian 
Please follow the correct support process as per https://github.com/abraunegg/onedrive#reporting-issues

You have not also used the [Issue Template](https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md) you are missing other critical information to help assist you quickly - this is why there is a Bug Report Template .. next time please use it. Can you please update your first post with the missing information.

**Comment by devalian** [comment]
### Bug Report Details ###
**Describe the bug**
a local folder that is also a network shares, sync with onedrive client will have 'action not permitted' error on opened and locked file. 
for example, an file.mdb is opened by networked user to work on the file, onedrive client will unable to sync the file and retry 3 times and failed. 


**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
Linux svr1 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?
gui installed
*   OneDrive Account Type
SharePoint with M365 account
*   Did you build from source or install from a package?
install from source
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
DMD64 D Compiler v2.094.0
*   OneDrive Application Version: Output of `onedrive --version`
onedrive v2.4.7-1-g6405c9d
*   OneDrive Application Configuration: Output of `onedrive --display-config`
Configuration file successfully loaded
onedrive version                       = v2.4.7-1-g6405c9d
Config path                            = /home/*****/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/****/*****
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'drive_id'               = b!UvFrFGRIeEizVT_oD34IoqrX9XCCx3RMhBn75rbVIJFWUNzgjIboQa97L9BOCgav
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false

*   Provide the version of curl you are using: Output of `curl --version`
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
*   Is your configured 'sync_dir' a local directory or a network mount point?
local directory, but local directory is shared out to network share via smb

*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
LVM2

*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
sharepoint site is a department shares

**Comment by devalian** [comment]
Here's the screenshot of the error. 
https://imgur.com/NcnpHK3

let me email you the logs as well.

thanks for coming back to me.

**Comment by abraunegg** [comment]
@devalian 
Most likely this is related to #1137 based on the debug log.

Please can you test & validate the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1140/head:pr1140
git checkout pr1140
./configure; make clean; make;
```

This should hopefully take care of at least the application crash.

When running the PR, your version should be `onedrive v2.4.7-4-g68cc51a` or greater.

**Comment by abraunegg** [comment]
@devalian 
I have been able to replicate the environment and work on a fix. Please can you rebuild PR 1140. 

When running the updated client, your client version should be: `onedrive v2.4.7-9-gb595965`

**Comment by devalian** [comment]
Hi Abraunegg, we are having same issue. after rebuild the branch, it still show v2.4.7.1 version. hence it still crash on opened files. i removed the entire onedrive folder, and ran that 5 commands above.

**Comment by abraunegg** [comment]
@devalian 
You need to run the PR from the PR directory as per email or install it.

**Comment by devalian** [comment]
Thanks @abraunegg . managed to get this upgraded to version 2.7.10-gaa533ef. once i run the ./onedrive --monitor. it started sync and when it reached the previous break point (operation not permitted), it wont crash now, and it wont move forward either. any chance to get it to continue and upload the rest of the files, until after working hour to retry to resync?

**Comment by abraunegg** [comment]
@devalian 
Please provide a [full verbose debug](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) log using 'master' as this previous PR is now merged into the main branch.

**Comment by devalian** [comment]
Appreciate @abraunegg . it looks like i rebuilt the client with main branch and newer version. seems to be working now that it continue to sync and skipped opened files. Cheers!
