### ISSUE TITLE
Source files not being removed despite remove_source_files=true

### ISSUE THREAD

**Issue by mfschumann** [abraunegg/onedrive#1141]
### Bug Report Details ###
**Describe the bug**
onedrive does not delete source files after successful upload to OneDrive, despite config option remove_source_files being set to true.

Non-default config parameters:
```
sync_dir = "/media/nas/OneDrive-upload"
monitor_interval = "10"
upload_only = "true"
no_remote_delete = "true"
remove_source_files = "true"
```

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`   
> Fedora 33
> Linux srv 5.8.18-300.fc33.x86_64 #1 SMP Mon Nov 2 19:09:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?
> headless
*   OneDrive Account Type 
> personal
*   Did you build from source or install from a package?
> from source
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
> 1.23.0
*   OneDrive Application Version: Output of `onedrive --version`
> onedrive v2.4.7-2-gcb57213
*   OneDrive Application Configuration: Output of `onedrive --display-config`  
> Configuration file successfully loaded
onedrive version                       = v2.4.7-2-gcb57213
Config path                            = /etc/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /media/nas/OneDrive-upload
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 10
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
*   Provide the version of curl you are using: Output of `curl --version`
> curl 7.71.1 (x86_64-redhat-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1h-fips zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.41.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
*   Is your configured 'sync_dir' a local directory or a network mount point?
> network mount point (smb)
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
> //fritz.box/fritz.nas/NAS on /media/nas type cifs (rw,relatime,vers=3,cache=strict,username=nas,uid=0,noforceuid,gid=1004,forcegid,addr=192.168.0.1,file_mode=0664,dir_mode=0775,soft,nounix,mapposix,rsize=65536,wsize=65536,bsize=1048576,echo_interval=60,actimeo=1)
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
> btrfs
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
> I created a folder OneDrive-upload on a SMB share that the server running onedrive has access to. I want onedrive to upload all files that are placed in this folder and delete the files after upload completes successfully. 

**Complete Verbose Log Output**
```bash
onedrive --confdir=/etc/onedrive --synchronize --verbose
Using 'user' Config Dir: /etc/onedrive
Using 'system' Config Dir: 
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /media/nas/OneDrive-upload
Application version: v2.4.7-2-gcb57213
Account Type: personal
Default Drive ID: 792e1611d7b1a289
Default Root ID: 792E1611D7B1A289!103
Remaining Free Space: 32115286648
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of /media/nas/OneDrive-upload
Processing .
The directory has not changed
Uploading new items of /media/nas/OneDrive-upload
Requested file to upload exists on OneDrive - local database is out of sync for this file: ./NEWFILE
Requested file to upload is newer than existing file on OneDrive
Uploading modified file ./NEWFILE ... done.
Remaining free space on OneDrive: 32115286648
```

**Comment by abraunegg** [comment]
@mfschumann 
Thanks for reporting this issue.

**Comment by abraunegg** [comment]
@mfschumann 
Please can you test & validate the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1142/head:pr1142
git checkout pr1142
./configure; make clean; make;
```

When running the PR, your version should be `onedrive v2.4.7-3-g61ee67e` or greater.

**Comment by mfschumann** [comment]
@abraunegg 
Thanks for looking into the issue so quickly!
It seems to be resolved now.
