### ISSUE TITLE
Not respecting most recent file rule and unstoppable

### ISSUE THREAD

**Issue by magiwanders** [abraunegg/onedrive#1143]
IMPORTANT

PLEASE DISABLE automatic activation of background service when installing from repository. It does not work as intended, as it substitutes newer local files for older remote ones. Please leave the activation of the service to be done by user. 

PLEASE DISABLE automatic activation at startup. Leave it to activate to the user.

### Bug Report Details ###
**Describe the bug**
Onedrive's background process substitutes remote older files to local most recent files. I noticed while coding, code I just wrote just disappeared few seconds later. I cannot afford to lose my work and right now I cannot download the repository version because Onedrive operates in background automatically when booting up (shows in system monitor) but does not show up in startup application and cannot be stopped through systemctl as it does not show in the list.

**Application and Operating System Details:**
*   Linux pop-os 5.4.0-7642-generic #46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC  x86_64 x86_64 x86_64 GNU/Linux

*   OneDrive Account Type - 
Buisness (student activation)

*   Did you build from source or install from a package? 
Ubuntu Package

*   OneDrive Application Version: Output of `onedrive --version` -
 Latest as of 13 November, cannot verify as I uninstalled it

*   OneDrive Application Configuration: Output of `onedrive --display-config` - 
Out of the box, no default config changed

*   Provide the version of curl you are using: Output of `curl --version`- 
curl 7.68.0

*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=8084764k,nr_inodes=2021191,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1626080k,mode=755)
/dev/sda3 on / type ext4 (rw,noatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=17616)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
/var/lib/snapd/snaps/core_10185.snap on /snap/core/10185 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/core18_1932.snap on /snap/core18/1932 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/flutter_32.snap on /snap/flutter/32 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/core18_1885.snap on /snap/core18/1885 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/core_10126.snap on /snap/core/10126 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/flutter_31.snap on /snap/flutter/31 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/vlc_1700.snap on /snap/vlc/1700 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/hello-world_29.snap on /snap/hello-world/29 type squashfs (ro,nodev,relatime,x-gdu.hide)
/dev/sda2 on /recovery type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/sda1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/user/110 type tmpfs (rw,nosuid,nodev,relatime,size=1626076k,mode=700,uid=110,gid=116)
gvfsd-fuse on /run/user/110/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=110,group_id=116)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=1626076k,mode=700,uid=1000,gid=1000)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/fuse on /run/user/1000/doc type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/sdc1 on /media/magiwanders/Vault type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)

*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
NAME          FSTYPE   LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
loop0         squashfs                                                  0   100% /snap/core/10126
loop1         squashfs                                                  0   100% /snap/core/10185
loop2         squashfs                                                  0   100% /snap/core18/1932
loop3         squashfs                                                  0   100% /snap/flutter/32
loop4         squashfs                                                  0   100% /snap/core18/1885
loop5         squashfs                                                  0   100% /snap/flutter/31
loop6         squashfs                                                  0   100% /snap/vlc/1700
loop7         squashfs                                                  0   100% /snap/hello-world/29
sda                                                                              
├─sda1        vfat           9A6C-6AB9                               193M    61% /boot/efi
├─sda2        vfat           9A6C-B1ED                               1.7G    59% /recovery
├─sda3        ext4           77864688-5900-4963-930d-e7e4511e41aa    204G    49% /
└─sda4        swap           82db92ef-8570-459b-a60d-da6931e38384                
  └─cryptswap swap           14510cf8-c70a-4298-857a-54f75f0e7650                [SWAP]
sdb                                                                              
├─sdb1        ntfs     win   0A2BB3D862CF2B83                                    
└─sdb2        ntfs           8CEAA186EAA16CE0                                    
sdc                                                                              
└─sdc1        exfat    Vault 5E56-374D                               5.5T    40% /media/magiwanders/Vault

*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
Onedrive is just a folder in my home, only accessible through this machine

**Note:** Please generate a full debug log whilst reproducing the issue as per 
Again, had to uninstall the application since the nature of the bug

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Install from repository
2.  Reboot
3.  onedrive --synchronize gives error because "another process is locking the database"
4.  Modified files revert back

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@magiwanders 
I am not responsible for the Ubuntu package. Please go take this issue elsewhere or become the Ubuntu package maintainer.

**Comment by norbusan** [comment]
The Debian packages does not activate any service automatically, so that means that Ubuntu has changed something.

**Comment by magiwanders** [comment]
Thank you and I am sorry if this was not the most appropriate section. I will now proceed to reinstall compling from this repository. In case the problem is in my system, can you please point me a quick way/set of commands to reset configs and disable everything automatic (other than uninstalling) in case things go south? I just wanna be able to run the 'onedrive --synchronize' manually. Nothing more

**Comment by abraunegg** [comment]
@magiwanders 
Please refer to the [usage document](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md) or man page.

If you installed via the Ubuntu PPA, you need to open your issue / bug here: https://launchpad.net/~yann1ck/+archive/ubuntu/onedrive
