### ISSUE TITLE
Files getting renamed - synchronization?

### ISSUE THREAD

**Issue by jsahil730** [abraunegg/onedrive#1144]
### Bug Report Details ### 
**Describe the bug**
I have observed this several times, my files get renamed to <filename>-sahil-Inspiron-5559.<extension> I don't know why, seems like maybe onedrive is not performing synchronization properly?
Also noticed this just today, the onedrive monitor is being intialized again n again; which shouldn't probably be the case. This log is near the end of the log file.
Note that the exact time this was observed is Nov 13 18:31:18 something, please check it around that time.

**Application and Operating System Details:**
*   `Linux sahil-Inspiron-5559 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
*   GUI
*   Organization account is what I am working with atm(Microsoft 365 suite, I guess)
*   Built from source
*   DMD64 D Compiler v2.094.1
*   onedrive v2.4.7
*   OneDrive Application Configuration: Output of `onedrive --display-config` ->
```
onedrive version                       = v2.4.7
Config path                            = /home/sahil/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/sahil/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version` ->
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
*   Is your configured 'sync_dir' a local directory or a network mount point? Local dir
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` : sda10 ext4 
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
This account syncs to my phone all the time(Redmi Note 5 Pro) : but that is not usually the cause of the issue afaik.

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
No idea what-so-ever, I was trying to generate some plots using some python code(the t2.png file especially, that was over-writted by the code; and then now it has a t2-sahil-Inspiron-5559.png)!

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [x] Debug Log generated and submitted

**Comment by jsahil730** [comment]
@abraunegg I have mailed the debug log at the mentioned mail id!

**Comment by abraunegg** [comment]
@jsahil730 
The log files show some sort of background process moving the file from a -> b

Please can you:
* Determine if you have the client running via multiple systemd service files
* Determine if you have the client running as root & as your normal user account at the same time

**Comment by abraunegg** [comment]
@jsahil730 
Further feedback provided via email. Marking this as a local environment issue.

**Comment by abraunegg** [comment]
@jsahil730 
Please can you respond in regards to providing further information and your system checks

**Comment by jsahil730** [comment]
@abraunegg Thanks for your support! Yup, as mentioned, it indeed was due to multiple systemd service files! I had modified the user service file and had enabled it which must've been the cause of all this! Seems like it's resolved for the time being, will get back to you again, once I find the duplication happening.
