### ISSUE TITLE
std.file.FileException

### ISSUE THREAD

**Issue by tyger** [abraunegg/onedrive#1148]
Running version built from tag v2.4.7

### Bug Report Details ###
**Describe the bug**
Trying to synchronise folder from previous version using `--synchronise --resync`, it seems that all new files (the ones that present only on OneDrive) are failed to sync into folder.
File that is being synchronised from OneDrive to local disc is fine if check it through OneDrive UI, also downloading it manually and putting into destination folder makes onedrive check it fine on resync and move on until next file that doesn't present locally.
Also file could be successfully created in the target folder from the user logic that is used to run onedrive.

**Application and Operating System Details:**
*   `Linux reezonpi 5.4.72-v7l-MY_CRYPTO_KERNEL+ #1 SMP Mon Oct 19 19:42:18 BST 2020 armv7l GNU/Linux`
*   using a headless system (no gui)?
*   OneDrive Account Type - Personal
*   Built from sources tag v2.4.7
*   LDC - the LLVM D compiler (1.17.0):
  based on DMD v2.087.1 and LLVM 8.0.1
  built with LDC - the LLVM D compiler (1.17.0)
  Default target: armv7l-unknown-linux-gnueabihf
  Host CPU: cortex-a72
  http://dlang.org - http://wiki.dlang.org/LDC
  Registered Targets:
    arm     - ARM
    armeb   - ARM (big endian)
    thumb   - Thumb
    thumbeb - Thumb (big endian)
    wasm32  - WebAssembly 32-bit
    wasm64  - WebAssembly 64-bit

*   onedrive v2.4.7
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
Configuration file successfully loaded
onedrive version                       = v2.4.7
Config path                            = /var/lib/onedrive/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /srv/dev-disk-by-label-disk/personal/user/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp|.DS_Store|._.DS_Store
Config option 'skip_dotfiles'          = true
Config option 'skip_symlinks'          = true
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/onedrive/
Config option 'classify_as_big_delete' = 200
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
```
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```
*   Is your configured 'sync_dir' a local directory or a network mount point?
    Local directory on LUKS encrypted partition on a disk connected through USB3
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
   `/dev/mapper/extcrypt on /srv/dev-disk-by-label-disk type ext4 (rw,relatime,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
   ```
sdb
├─sdb2       crypto_LUKS          7fb1bc58-e5c5-4a51-a943-49a5ab8370e5
│ └─extcrypt ext4        disk 6bd81be1-3fa0-465b-a4c9-d6980e4d6c12  524.3G    42% /srv/dev-disk-by-label-ExtDrive
```
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
Raspberry Pi 4 4GB, Rasbian OS 32bit, OpenMediaVault v5, onedrive to sync data to OneDrive, onedirve syncdyr is shared through smbd

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Very hard to tell but seems to be new behaviour of v2.4.7 where as v2.4.5 was quite stable on the same configuration 

**Complete Verbose Log Output**

Application Log Output:
```bash
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"xxxx0RTY0QzlCODI3QzhGREQyITQzNzxxx","eTag":"xxxxxx","file":{"hashes":{"quickXorHash":"P\/pgDVIhW9CbqTtQ3luIkYF3jCQ=","sha1Hash":"827B4B8C2A4A608B8B5C028426A5EBE1D7DF838F","sha256Hash":"426014ED58AE5661A0F3912F2BBA2A0B958E7D99224343CC509776F362256736"},"mimeType":"image\/jpeg"},"fileSystemInfo":{"createdDateTime":"2020-05-08T02:16:08.886Z","lastModifiedDateTime":"2017-08-13T12:10:46Z"},"id":"xE64C9B827Cxxxxx!xxxxx","name":"20170813_131046.jpg","parentReference":{"driveId":"xe64c9b827cxxxxx","driveType":"personal","id":"xE64C9B827Cxxxxx!xxxxx","name":"2017","path":"\/drive\/root:\/Pictures\/2017"},"size":4584812}
[DEBUG] Not a OneDrive deleted item change
[DEBUG] defaultRootId                                        = xE64C9B827Cxxxxx!104
[DEBUG] 'search id'                                          = xE64C9B827Cxxxxx!104
[DEBUG] id == defaultRootId                                  = true
[DEBUG] isItemRoot(item)                                     = false
[DEBUG] item['name'].str == 'root'                           = false
[DEBUG] singleDirectoryScope                                 = false
[DEBUG] 'parentReference id'                                 = xE64C9B827Cxxxxx!42832
[DEBUG] search criteria: syncFolderName                      = root
[DEBUG] search criteria: syncFolderPath                      =
[DEBUG] search criteria: syncFolderChildPath                 =
[DEBUG] thisItemId                                           = xE64C9B827Cxxxxx!43724
[DEBUG] thisItemParentPath                                   = /drive/root:/Pictures/2017
[DEBUG] thisItemFullPath                                     = /drive/root:/Pictures/2017/20170813_131046.jpg
[DEBUG] 'item id' matches search 'id'                        = false
[DEBUG] 'parentReference id' matches search 'id'             = false
[DEBUG] 'thisItemParentPath' contains 'syncFolderChildPath'  = true
[DEBUG] 'thisItemParentPath' contains search 'id'            = false
[DEBUG] Change matches search criteria to apply
[DEBUG] lastModifiedDateTime (OneDrive item): 2017-Aug-13 12:10:46Z
[DEBUG] skip_file item to check: /Pictures/2017/20170813_131046.jpg
[DEBUG] skip_file evaluation for: /Pictures/2017/20170813_131046.jpg
[DEBUG] Result: false
[DEBUG] The item we are syncing is a file
[DEBUG] OneDrive change is a new local item
Downloading file Pictures/2017/20170813_131046.jpg ... [DEBUG] Request URL = https://graph.microsoft.com/v1.0/drives/xe64c9b827cxxxxx/items/xE64C9B827Cxxxxx!xxxxx?select=size,malware,file,webUrl
Giving up on sync after three attempts: Pictures/2017: Operation not permitted
std.file.FileException@/home/pi/tmp/ldc2-1.17.0-linux-armhf/bin/../import/std/file.d(2233): Pictures/2017: Operation not permitted
----------------
??:? [0x151dcb]
??:? [0x15d463]
??:? [0x141a37]
file.d:272 [0xaaff3]
config.d:2233 [0x345fb]
onedrive.d:502 [0x34a43]
sync.d:2563 [0x3394b]
sync.d:2399 [0x32b13]
sync.d:2225 [0x285fb]
sync.d:0 [0x204df]
sync.d:563 [0x180e3]
main.d:1303 [0x75ac3]
main.d:915 [0x6489f]
??:? [0x14166b]
??:? [0x141523]
??:? [0x1413b3]
??:? __libc_start_main [0xb6bb6717]
std.net.curl.CurlException@std/net/curl.d(4364): A libcurl function was given a bad argument on handle null
----------------
??:? [0x151dcb]
??:? [0x15d463]
??:? [0x141a37]
??:? [0x103017]
??:? [0x11ca37]
onedrive.d:280 [0x61303]
??:? [0x14166b]
??:? [0x141523]
??:? [0x1413b3]
```

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [x] Verbose Log Output from your error
*   [x] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@tyger 
This is actually an issue due to your local file permissions on your mount point.

You need to be running the latest 'master' to resolve this issue, due to how file permissions are being used in the application in v2.4.7 and beyond. Refer to: https://github.com/abraunegg/onedrive/pull/1140

**Comment by abraunegg** [comment]
Closing issue, duplicate bug, already fixed, running old code

**Comment by tyger** [comment]
@abraunegg Could you give more info what kind of configuration made that problem?

And, yes, latest version did fix this issue. Thank you.

**Comment by abraunegg** [comment]
@tyger 
The best I can theorise here is the following:
* v2.4.6 and below, default permissions for new folders / files was world readable - a security issue - but this is due to the quirks of the compiler. An update in code to fix this was done, so that post creation, file / folder permissions are updated resolving this issue.
* When updating file / folder permissions, when not using a mounted file system, no issue in the permission setting is encountered, however - for some reason, the original code fix did not like to update permissions on files / folders on function exit (your issue) .. which was not uncovered until the original issue was raised.
* When analysing the debug logs, the mount point was owned by root, but world writable. Changing the mount point owner to the right user, fixed the initial flaw.
* Updating the permissions change to a higher up function fixes the flaw you had, without needing the mount permission change - but is not entirely logical, as, by rights, the original code in original location should have worked ... thus all I can think of is some sort of access race condition was occuring, which is now removed by moving the permissions fix to the calling function.

Hope that helps explain what was going on
