### ISSUE TITLE
Possible issue when directory has `rwxrwsrwx` with `setgid` bit.

### ISSUE THREAD

**Issue by tyger** [abraunegg/onedrive#1149]
### Bug Report Details ###
**Describe the bug**
Maybe it's a known issue and I want to check first. If full bug report is needed I will do that later.
The actual problem: if directory has chmod config `onedrive:onedrive -rwxrwsrwx` (where onedrive is the group and user that runs app) with `setgid` bit, then onedrive fails to create (download file from OneDrive) with error 
```
ERROR: The local file system returned an error with the following message:
  Error Message: Pictures/2017: Operation not permitted
[DEBUG] Download or creation of local directory failed
```

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
`Linux reezonpi 5.4.72-v7l-MY_CRYPTO_KERNEL+ #1 SMP Mon Oct 19 19:42:18 BST 2020 armv7l GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed?
*   OneDrive Account Type
*   Did you build from source or install from a package?
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
*   OneDrive Application Version: Output of `onedrive --version`
    `onedrive v2.4.7-13-g0d5b004`
*   OneDrive Application Configuration: Output of `onedrive --display-config`
*   Provide the version of curl you are using: Output of `curl --version`
*   Is your configured 'sync_dir' a local directory or a network mount point?
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Get new file on OneDrive
2. Set mod on the directory for the file as `rwxrwsrwx` with `setgid` bit
3. Run onedrive with `--synchronise`
4.  See error with it reaches that file.

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [X] Detailed description
*   [] Application and Operating System Details provided in full
*   [X] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@tyger 
Special permission bits (setuid, setgid, sticky bit) are not supported. Refer to:

https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#sync_dir-directory-and-file-permissions

This is a limit of the DMD / LDC compilers that they do not support the setting of these values.

**Comment by tyger** [comment]
@abraunegg 
Sorry if my explanation was confusing, but I meant slightly different issue.
I don't want to set set either of those bit through the app, it's rather that if onedrive tries to synchronise anything (file) from a cloud to a folder that has `setgid` bit set it fails with aforementioned issue. Removing that bit from the folder resolves it.
Hope that makes sense.

**Comment by abraunegg** [comment]
@tyger 
Correct - `setgid` whether set on a local directory without using the application or any other method is not supported.

**Comment by tyger** [comment]
Hm, behaviour is not consistent though...
I've cleaned `setgid` bit from all directories in the path up to the root of the onedrive sync dir (not to the root of the mount point).
And still getting error:
```
[DEBUG] skip_file item to check: /Pictures/Camera Roll/20180825_160740.jpg
[DEBUG] skip_file evaluation for: /Pictures/Camera Roll/20180825_160740.jpg
[DEBUG] Result: false
[DEBUG] The item we are syncing is a file
[DEBUG] OneDrive change is a new local item
Downloading file Pictures/Camera Roll/20180825_160740.jpg ... [DEBUG] Request URL = https://graph.microsoft.com/v1.0/drives/xxxx/items/xxxxx!xxxx?select=size,malware,file,webUrl
ERROR: The local file system returned an error with the following message:
  Error Message: Pictures/Camera Roll: Operation not permitted
[DEBUG] Download or creation of local directory failed
```

Don't really see any reason to fail on such operation - it went successfully in adjacent folder

**Comment by tyger** [comment]
Probably I will need to open another bug report if it sounds like bug.

**Comment by abraunegg** [comment]
@tyger 
It is a local file system permission issue .. This is not something that I can solve.

You can 'test' by changing the permissions that will be used in the config file, and I suspect, it will be when the world readable / world writeable flags are set, you will not see an issue ... so this means, that the file / folder permissions locally are too restrictive.

**Comment by tyger** [comment]
@abraunegg  Thank you for info it's very helpful.
I think I narrowed down problem to the directory owner where files are being created.
As I see it: when onedrive downloads file it tries to change permission bits on the owning directory at the same time, but if owner of it is different from the user that runs onedrive (in my case it's service user) it fails.
So it might look like solution is easy - to change owner of all directories where I need to sync something.
But there is still problem in, what I think is very popular use-case, situation when directories are created externally, e.g. through SMB using different user id, in order for that directory and files in it synced into Cloud and back.
I don't know what would be right approach to deal with it, but just as an idea, do you think it would be possible to add configuration to prevent changing mod on the directories that already exists locally?

**Comment by abraunegg** [comment]
@tyger 
The issue (in regards to making a further change) however is this - from your debug log:
>```
> [DEBUG] OneDrive change is a new local item
> Downloading file Pictures/Camera Roll/20180825_160740.jpg ... [DEBUG] Request URL = https://graph.microsoft.com/v1.0/drives/xxxx/items/xxxxx!xxxx?select=size,malware,file,webUrl
> ERROR: The local file system returned an error with the following message:
>  Error Message: Pictures/Camera Roll: Operation not permitted
>```

The file was attempted to be created to allow the download to occur, however the file creation *before* the permission attempt failed - meaning - that the location where the folder is, is too restrictive.

The code currently only changes:
* New folders when created *by* the application when downloading new folders
* New files when created *by* the application when downloading new files

No modification of permissions is done when an existing file or folder is found.

> But there is still problem in, what I think is very popular use-case, situation when directories are created externally, e.g. through SMB using different user id, in order for that directory and files in it synced into Cloud and back.

Right .. so - in this use case, you will need to then set your permission config in the config file to:
```
# sync_business_shared_folders = "false"
sync_dir_permissions = "777"
sync_file_permissions = "666"
```

This way, you will not face this issue you are seeing - or you add the 'user' that runs the 'onedrive' binary into the same 'group' as your network / SMB users when they are writing data, so that you can use:
```
# sync_business_shared_folders = "false"
sync_dir_permissions = "770"
sync_file_permissions = "660"
```

**Comment by abraunegg** [comment]
Closing issue, local environment issue with file / folder permissions of mounted folder

**Comment by tyger** [comment]
@abraunegg I appreciate your explanation, thank you for that, and understand what you are talking about.
But let me state my case using a concrete example, if it won't make sense I will bail :)
```
#Locally 
drwxrwxr--   2 pi onedrive  68K Nov 18 00:47  2017/

#Config
sync_dir_permissions = "700"
sync_file_permissions = "600"

#InCloud
2017 folder with some new files.
```
Trying to run `onedrive --synchronise --verbose` fails with aforementioned error on each file it tries to create in `2017`.
Creation any file though from under `onedrive` user in `2017` is successful:
```
/Pictures/2017$ touch test
/Pictures/2017$ ls -l test
-rw-r--r-- 1 onedrive onedrive 0 Nov 18 21:30 test
```

Now, changing owner of `2017` to `onedrive` resolves problem with downloading new files into this folder, but in addition to that:
```
/Pictures$ ls -ld 2017
drwx------ 2 onedrive onedrive 69632 Nov 18 21:30 2017
```
So effectively as part of file download `onedrive` changed permission on containing folder according to `sync_dir_permissions = "700"`.
According to what you said earlier it should not happen for existing folder.
This is reproducible on `onedrive v2.4.7-13-g0d5b004` on `raspbian (armv7l)` on `armhf`

**Comment by abraunegg** [comment]
@tyger 
> So effectively as part of file download `onedrive` changed permission on containing folder according to `sync_dir_permissions = "700"`.
According to what you said earlier it should not happen for existing folder.

OK .. that is a bug, and should not be happening. If `2017` exists locally, the folder permissions should not be touched.

**Comment by tyger** [comment]
I guess I need to create another ticket/report for that? What do you think?

**Comment by abraunegg** [comment]
@tyger 
Will take care of it when I have some free time

**Comment by abraunegg** [comment]
@tyger 
Please can you test & validate the following PR for the directory issue above:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1152/head:pr1152
git checkout pr1152
./configure; make clean; make;
```

When running the PR version, your version should be `onedrive v2.4.7-15-g745bb5f` or greater.

**Comment by tyger** [comment]
@abraunegg 
Sorry for delay, get time only in the evening.
Checking latest master as I can PR is merged already. 
I can confirm it works as expected, thank you for fixing that.
