### ISSUE TITLE
systemctl not available in openrc system

### ISSUE THREAD

**Issue by Yassith** [abraunegg/onedrive#1158]
Hi,

Systemctl command is a systemd related and I'm using Gentoo with open rc.
Tried rc-update but onedrive is not a service and cannot start. Any hints to solve it ?

Kind regards
Yassith

**Comment by abraunegg** [comment]
@Yassith 
As OpenRC utilises inid.d, you most likely need to utilise the init.d service files. You most likely will need to manually set this up.

Refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-root-user-via-initd and https://github.com/abraunegg/onedrive/tree/master/contrib/init.d

Additionally, you have not indicated if you built from source or used the Gentoo package (https://gpo.zugaina.org/net-misc/onedrive). I would expect, if using the Gentoo package, that the package maintainer would set this up correctly. If not, then that issue needs to be raised with the package maintainer.

Please also to contribute to enhancing the documentation as well once you get this working for Gentoo.

**Comment by Yassith** [comment]
Hi,

I managed to prepare the following script
It should be located st : /etc/init.d/

Create file by 

root ~ #  touch /etc/init.d/onedrive

root ~ #  nano -w /etc/init.d/onedrive

put the following script through copy/paste

# =================================                                                                                    
#! /bin/sh
# /etc/init.d/onedrive
#
touch /var/lock/onedrive

case "$1" in
  start)
    /usr/local/bin/onedrive --monitor
    ;;
  stop)
    echo "Stopping onedrive"
    ;;
  *)
    echo "Usage: /etc/init.d/onedrive {start|stop}"
    exit 1
    ;;
esac

exit 0
# ============================================

Then execute :
 
root ~ #  /etc/init.d/onedrive start
root ~ #  rc-update add onedrive default

this will auto load the onedrive at system start
However it will start as root which I don't like for security reasons.

In my opinion everything which os not a must to run as root should run as a user.
I don't think openrc allows to run as users which is why I would create a desktop shortcut for Desktop Manager like GNOME and put it into ois autostart folder.

I can work it out a bit later.

However as I'm not an expert user please check if the above works properly.

Kind regards
Yassith

In order to run as a user it should be done through desktop manager like GNOME.

**Comment by abraunegg** [comment]
@Yassith 

> However it will start as root which I don't like for security reasons.

This is *why* I suggested for you to read / review this: https://github.com/abraunegg/onedrive/blob/master/contrib/init.d/onedrive.init

Note the following:
```
start() {
	export PATH=/usr/local/bin/:$PATH
        echo -n "Starting $APP_NAME: "
        daemon --user root onedrive_service.sh
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/onedrive || \
           RETVAL=1
        return $RETVAL
}
```

If Gentoo supports the use of 'daemon' you can pass through what user to run the service as, then utilise a further script that runs the binary + required options.

There is no other way to run this as another user when using init.d - it is an init.d limitation.

**Comment by Yassith** [comment]
Thanks,

The script is nice just can't find "onedrive_service.sh" file.

I can run it as a user from GNOME session both manually or in autostart but there is no way to observe syncing status right ?

**Comment by abraunegg** [comment]
@Yassith 
As per my initial response, you can find sample init.d files in the following location: https://github.com/abraunegg/onedrive/tree/master/contrib/init.d

In there you will find:
* onedrive.init - sample inid.d script
* onedrive_service.sh - sample script to start the service when using init.d & 'daemon'

> there is no way to observe syncing status right

Yes there is. Enable logging, configure logging directory & appropriate logrotate configurations as well. Read [usage.md](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md) for details.

**Comment by Yassith** [comment]
I managed slightly different way.
Replaced daemon which is not supported with runuser command

more less it is now like this

export PATH=/usr/local/bin/:$PATH
runuser user -s /bin/bash -c "nohup onedrive --monitor &>/home/user/.local/share/applications/onedrive_user.log &"

most of the options are not necessary but I like it clean when started from terminal

Thanks

**Comment by abraunegg** [comment]
@Yassith 
>`&>/home/user/.local/share/applications/onedrive_user.log`

This could be replaced with:
* Configure 'enable_logging' & 'log_dir' in the config file

**Comment by abraunegg** [comment]
Closing issue as original question answered
