### ISSUE TITLE
Error when using onedrive for business

### ISSUE THREAD

**Issue by pcmagic** [abraunegg/onedrive#1159]
Hi, 

I'm trying to use onedrive on ubuntu 20.04, I have two accounts, one is personal and another one is business. 
I can use your onedrive client with my personal account, but the business account reports an error. 

here is a brief of my system information
```
        $ onedrive --display-config
        onedrive version                       = v2.4.7-0~202011102339~ubuntu20.04.1
        Config path                            = /home/zhangji/.config/onedrive
        Config file found in config path       = false
        Config option 'check_nosync'           = false
        Config option 'sync_dir'               = /home/zhangji/OneDrive
        Config option 'skip_dir'               = 
        Config option 'skip_file'              = ~*|.~*|*.tmp
        Config option 'skip_dotfiles'          = false
        Config option 'skip_symlinks'          = false
        Config option 'monitor_interval'       = 300
        Config option 'min_notify_changes'     = 5
        Config option 'log_dir'                = /var/log/onedrive/
        Config option 'classify_as_big_delete' = 1000
        Config option 'sync_root_files'        = false
        Selective sync 'sync_list' configured  = false
        Business Shared Folders configured     = false
```
Thanks.

**Comment by abraunegg** [comment]
@pcmagic 

As you have not used the [Issue Template](https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md) - you are missing in your first post critical information to help assist you quickly - this is why there is a Bug Report Template .. please use it. Can you please update your first post with the missing information.

Additionally, you have not provided *any* details re what error you are receiving when using a business account configuration.

**Comment by abraunegg** [comment]
Closing this issue due to user opening #1161
