### ISSUE TITLE
Add a bit to documentation for using the same folder when dual booting

### ISSUE THREAD

**Issue by Fishezzz** [abraunegg/onedrive#1160]
**Is your feature request related to a problem? Please describe.**
This isn't actually a feature request but a request for adding a bit to the documentation. More specific for using the same folder when dual booting Windows and Linux. It may have been a solution for #782 and has a bit of relevance to #757.

**Context**
I'm dual booting Windows and Kubuntu since a few months now and the only thing holding me back from making the switch away from windows completely was onedrive synchronization, because I use onedrive to "store" all of my school stuff. But then I found this project, which is amazing btw, and all was good and everything was working. I could use the same folders on the same partition for both windows and linux.
But then I tried moving windows from my SSD to my HDD to make space for Kubuntu, but that failed horribly, cuz f*ck windows. Eventually I managed to reinstall windows and setup onedrive there (and check "keep offline" on the whole folder). But when switching back to linux, I noticed all files where 0 byte links (made by windows).

**Describe the solution you'd like**
To fix the problem of windows turning all files (that should be kept offline) into links, you have to uncheck a specific option in the onedrive settings window. The option in question is `Save space and download files as you use them`.

Where to find this setting?
Open the onedrive pop-up window from the taskbar, click "Help & Settings" > "Settings". This opens a new window. Go to the tab "Settings" and look for the section "Files On-Demand".

After unchecking the option `Save space and download files as you use them` and clicking "Ok", Onedrive should restart itselve and start actually downloading your files so they will truely be available on your disk offline, and should be seen as actual files on linux.

**Describe alternatives you've considered**
/

**Additional context**
I added 2 screenshots with the option that should be unchecked.
| personal Onedrive | Onedrive Business<br>SharePoint |
|---|---|
| ![Uncheck-Personal](https://user-images.githubusercontent.com/33294032/99952429-f33eae80-2d7f-11eb-93a1-9ce28eba303e.png) | ![Uncheck-Business](https://user-images.githubusercontent.com/33294032/99952483-0782ab80-2d80-11eb-9fe1-410ce3b0f742.png) |

**Comment by abraunegg** [comment]
@Fishezzz 
Thanks for the feedback and suggestion, will add this as part of the v2.4.8 release changes in the next week or so.

**Comment by Fishezzz** [comment]
Awesome!

**Comment by abraunegg** [comment]
@Fishezzz 
Please can you review https://github.com/abraunegg/onedrive/blob/release-2.4.8/docs/advanced-usage.md#configuring-the-client-for-use-in-dual-boot-windows--linux-situations for applicability

**Comment by Fishezzz** [comment]
That's great, but I would change the first sentence of the last paragraph to:

> After unchecking the option and clicking "OK", the Windows OneDrive client should restart itself and start actually downloading your files so they will truely be available on your disk when offline.

It reads a bit beter and fixed a typo.

**Comment by abraunegg** [comment]
@Fishezzz 
thanks - updated

**Comment by abraunegg** [comment]
Closing issue as v2.4.8 released, documentation added
