### ISSUE TITLE
Error when using onedrive for business

### ISSUE THREAD

**Issue by pcmagic** [abraunegg/onedrive#1161]
Can not log in to the business account. 
I have two accounts, one is personal and another one is business.
I can use your onedrive client with my personal account, but the business account reports an error.

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
Linux zj 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?
with GUI
*   OneDrive Account Type
Business
*   Did you build from source or install from a package?
install from a package
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
...
*   OneDrive Application Version: Output of `onedrive --version`
```
onedrive v2.4.7-0~202011102339~ubuntu20.04.1
```
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
onedrive version                       = v2.4.7-0~202011102339~ubuntu20.04.1
Config path                            = /home/zhangji/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/zhangji/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
*   Is your configured 'sync_dir' a local directory or a network mount point?
a local directory 
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
...
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
└─sdb1 ext4         
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time

Can not log in. Thus, no such problems. 

**Note:** Please generate a full debug log whilst reproducing the issue as per 
```
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/zhangji
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/zhangji/.config
[DEBUG] configDirName: Configuring application to use default config path
Using 'user' Config Dir: /home/zhangji/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
[DEBUG] refreshTokenFilePath = /home/zhangji/.config/onedrive/refresh_token
[DEBUG] deltaLinkFilePath = /home/zhangji/.config/onedrive/delta_link
[DEBUG] databaseFilePath = /home/zhangji/.config/onedrive/items.sqlite3
[DEBUG] databaseFilePathDryRun = /home/zhangji/.config/onedrive/items-dryrun.sqlite3
[DEBUG] uploadStateFilePath = /home/zhangji/.config/onedrive/resume_upload
[DEBUG] userConfigFilePath = /home/zhangji/.config/onedrive/config
[DEBUG] syncListFilePath = /home/zhangji/.config/onedrive/sync_list
[DEBUG] systemConfigFilePath = /etc/onedrive/config
[DEBUG] businessSharedFolderFilePath = /home/zhangji/.config/onedrive/business_shared_folders
No user or system config file found, using application defaults
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /home/zhangji/OneDrive
[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive Service
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
[DEBUG] Downgrading all HTTP operations to HTTP/1.1 by default
[DEBUG] clientId    = d50ca740-c83f-4d1b-b616-12c519384f0c
[DEBUG] companyName = abraunegg
[DEBUG] appTitle    = OneDrive Client for Linux
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d50ca740-c83f-4d1b-b616-12c519384f0c&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.Read.All%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri:
```

**Comment by abraunegg** [comment]
@pcmagic 
I am not seeing any issue.

What is your exact problem here?

There is no error message. You need to open the authentication URL, login with your OneDrive Business credentials, and provide the response URI to the application.

**Comment by abraunegg** [comment]
@pcmagic 
Please can you respond with either a screen shot of whatever error you are getting or further details, as so far you have provided no details of any error.

**Comment by abraunegg** [comment]
@pcmagic 
Please can you respond

**Comment by abraunegg** [comment]
Closing issue, lack of response
