### ISSUE TITLE
Office365 Files not being downloaded

### ISSUE THREAD

**Issue by sclel016** [abraunegg/onedrive#1172]
### Bug Report Details ###
When an Office365 file (Word, Excel, etc) is created in the OneDrive web client, `onedrive syncrhonize` will not download the file to the local directory. However, an empty folder created within the OneDrive web client will be synchronized. I didn't find any mention of a limitation in the extensive documentation. I love the tool!

**Application and Operating System Details:**
*   Fedora 33
*   SwayWM
*   Personal and Education
*   Fedora package manager
*   OneDrive Application Version: `onedrive v2.4.5`
*   OneDrive Application Configuration: See below
*   Provide the version of curl you are using: `curl 7.71.1`
*   Configured sync_dir is `~/OneDrive`
*   What partition format type does your configured 'sync_dir' reside on? `btrfs`

**Configuration**
```bash
Configuration file successfully loaded
onedrive version                       = v2.4.5
Config path                            = /home/<user>/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/<user>/OneDrive
Config option 'skip_dir'               = .*|backup
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Link `onedrive` client to an education or personal account.
2.  In the onedrive web client, create a new file (word document, etc) `test.docx`
3. Run `onedrive --synchronize`
3.  File not downloaded to local path `~/OneDrive/test.docx`

**Complete Verbose Log Output**
```bash
onedrive --synchronize --verbose
Using 'user' Config Dir: /home/<user>/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/<user>/OneDrive
Application version: v2.4.5
Account Type: personal
Default Drive ID: 1fb8db4ca8e4477a
Default Root ID: 1FB8DB4CA8E4477A!101
Remaining Free Space: 5368698099
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 1FB8DB4CA8E4477A!101
Updated Remaining Free Space: 5368698099
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Uploading new items of ~/OneDrive
Applying changes of Path ID: 1FB8DB4CA8E4477A!101
Updated Remaining Free Space: 5368698099
```

Application Log Output:
Empty

**Comment by abraunegg** [comment]
@sclel016 
Please upgrade your client as you are running an obsolete version and re-test.

**Comment by sclel016** [comment]
Sorry for wasting your time, a fresh clone and build seems to have fixed the issue!

Any timeline on an update to the Fedora package?

Thanks!

**Comment by abraunegg** [comment]
@sclel016 
> Any timeline on an update to the Fedora package?

I am not responsible for Fedora packages, so I cannot advise there. Please take up any packaging lag with the Fedora packaging maintainers here: https://koji.fedoraproject.org/koji/packageinfo?packageID=26044

**Comment by sclel016** [comment]
Thanks for the quick response, I'll try and get in touch with the maintainers. Love the tool, thanks for all the hard work!
