### ISSUE TITLE
screen shot onedrive linux?

### ISSUE THREAD

**Issue by manuelsongokuh** [abraunegg/onedrive#1173]
hi

where is the screenshot of onedrive linux? icon tray..?

**Comment by abraunegg** [comment]
@manuelsongokuh 
There is no screen shot as this is a CLI tool. If you would like to enhance the documentation if you feel something like this is lacking, feel free to submit a PR with any required changes or additions.

There is no tray icon provided by this client. An external enhancement (https://github.com/DanielBorgesOliveira/onedrive_tray) provides a tray icon.
