### ISSUE TITLE
Onedrive silently fails and does not retry if there is no internet connection when it is launched

### ISSUE THREAD

**Issue by davidferlay** [abraunegg/onedrive#1184]
**Current behavior**

- I have been struggling quite a bit to make onedrive to launch when my computer starts : at some point of enabling and reading logs I understood that onedrive was not successfully reaching it's online service.
- The reason for that is quite simple in the end : if onedrive is executed during or before internet connection (which can take a few seconds when you pc starts, specifically when using wifi), it fails silently and will not attempt to connect again giving the impression that the software does not work 

**Solution proposed**

- when executed, onedrive should check for internet connection. If no connection, onedrive should keep watching for it until either a timeout is reached or indefinitly
- when executed and if there is not internet connection, onedrive should display a notification about impossibility to connect. 

**Alternatives considered**

- My current workaround is to start onedrive via i3 config using this shell oneliner command : 
`TRY=100; until [ $TRY -eq 0 ] || ping -c 1 google.com && onedrive --monitor; do echo $TRY; echo "Fail"; TRY=$(expr $TRY - 1); sleep 1; done;`
- Set it up to be executed at session start, it will check for internet connection 100 times every 1 seconds and when it succeeds, it will start onedrive

**Comment by abraunegg** [comment]
@davidferlay 
Whilst I can understand your frustration here - there are many things lacking in your details:

* what linux os are you using
* what application version
* how did you install
* examples of your logs / failures

The application does, and consistently provides very meaningful log output - so unsure what you are seeing. The application and systemd service files do constantly retry connection - for up to 1.2 years of being offline when starting.

Evidence please of what you are seeing and provide details as to your environment.

**Comment by davidferlay** [comment]
Hi @abraunegg

- I'm using Manjaro i3 community edition (5.8.18-1) and version v2.4.8 of onedrive
- It was installed using "yay" package manager (`yay onedrive`)
- Logs in a jiffy

**Comment by abraunegg** [comment]
@davidferlay 
> onedrive is set to launch at startup by adding an exec_always line in ~/.i3/config

This is your first issue ... this is the *wrong* way to start the application correctly at system startup. Use the systemd service files - this is why they exist. This correctly starts the application after other required services have been started - such as network, firewall etc.

On Manjaro, as this is based on Arch Linux, you need to follow the systemd directions as listed here:

https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#running-onedrive-as-a-system-service

* Run the client as ‘root’ - https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-root-user-via-systemd-arch-ubuntu-debian-opensuse-fedora
* Run the client as your user - https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-a-non-root-user-via-systemd-all-linux-distributions

OK - looking at your logs, this is an issue - the application, on startup should not be initialising the application if it cannot connect after performing the initial network test:

> ```
> 2020-Dec-16 13:45:59.0918916	[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive Service
> 2020-Dec-16 13:45:59.1023807	Cannot connect to Microsoft OneDrive Service
> 2020-Dec-16 13:45:59.1024237	Reason: Couldn't resolve host name on handle 55EF4C6912E0
> 2020-Dec-16 13:45:59.102447	Initializing the OneDrive API ...
> ```

So this is a bug.

**Comment by abraunegg** [comment]
@davidferlay 
Please can you test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1188/head:pr1188
git checkout pr1188
./configure; make clean; make;
```

When running the PR, your version should be: `onedrive v2.4.8-7-ge93dddd` or greater.

When there is no network connection to the OneDrive API, the PR will act in the following manner:
```
Using 'user' Config Dir: /home/alex/.config/onedrive-personal/
Using 'system' Config Dir: 
Configuration file successfully loaded
Notification (dbus) server not available, disabling
Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't connect to server on handle 1C7A770
  Calling Function: testNetwork()

Unable to reach Microsoft OneDrive API service at this point in time, re-trying network tests

Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't connect to server on handle 1C7A770
  Calling Function: testNetwork()

Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't connect to server on handle 1C7A770
  Calling Function: testNetwork()

Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't connect to server on handle 1C7A770
  Calling Function: testNetwork()

Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't connect to server on handle 1C7A770
  Calling Function: testNetwork()

Cannot connect to Microsoft OneDrive Service - Network Connection Issue
.....
ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't connect to server on handle 1C7A770
  Calling Function: testNetwork()

ERROR: Was unable to reconnect to the Microsoft OneDrive service after 10000 attempts lasting over 1.2 years!
```


If, at startup, there is no network connection, and it returns, the following will occur:
```
Using 'user' Config Dir: /home/alex/.config/onedrive-personal/
Using 'system' Config Dir: 
Configuration file successfully loaded
Notification (dbus) server not available, disabling
Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't connect to server on handle 1FCF770
  Calling Function: testNetwork()

Unable to reach Microsoft OneDrive API service at this point in time, re-trying network tests

Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't connect to server on handle 1FCF770
  Calling Function: testNetwork()

Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't connect to server on handle 1FCF770
  Calling Function: testNetwork()

Internet connectivity to Microsoft OneDrive service has been restored
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
...
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Monitor directory: .
Monitor directory: ./Documents
...
Starting a sync with OneDrive
...
Processing 1 OneDrive items to ensure consistent local state due to a full scan being requested
Sync with OneDrive is complete

```

Please can you test this PR in your environment.

**Comment by davidferlay** [comment]
Thanks @abraunegg , i'll try that soon

**Comment by davidferlay** [comment]
I confirm PR working as expected @abraunegg : 
```[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive Service
[DEBUG] Attempting to contact online service
[DEBUG] No Network Connection
[DEBUG] Raw Error Data: Couldn't resolve host name on handle 5606F66903E0
[DEBUG] JSON Message: null
[DEBUG]   Retry Attempt:      1
[DEBUG]   Retry In (seconds): 2
[DEBUG] Attempting to contact online service
[DEBUG] Shutting down HTTP engine as sucessfully reached OneDrive Online Service
Internet connectivity to Microsoft OneDrive service has been restored
Initializing the OneDrive API ...```

Thanks a lot for this quick support !

**Comment by abraunegg** [comment]
@davidferlay 
Thanks for confirmation, will merge this into 'master'
