### ISSUE TITLE
Webhook Integration

### ISSUE THREAD

**Issue by sclel016** [abraunegg/onedrive#1189]
**Is your feature request related to a problem? Please describe.**
Currently, the `onedrive` client polls OneDrive on `monitor_interval` cadence to get any changes on the remote. This works for most storage purposes, but for some real-time applications it can be slow. For example, annotating a PDF on a tablet across Linux and tablet benefits from as very low latency updates between the two devices.

**Describe the solution you'd like**
If viable, make use of OneDrive webhooks subscription API. This would allow the client to be notified of changes without being limited by the polling rate.

**Workaround**
Use a local SMB share to share files in real-time.

I'm happy to help beta test any PR! Feel free to close the issue if this isn't a reasonable feature.

**Comment by abraunegg** [comment]
@sclel016 
Using webhook's is not viable for this application. It requires the creation of a unique URL / website to receive the notifications, from which then the action is taken.

This will not be implemented in this client - sorry.

**Comment by sclel016** [comment]
No problem, thanks for maintaining the project!
