### ISSUE TITLE
Instant upload stopped working on Linux 20.04

### ISSUE THREAD

**Issue by Rmano** [abraunegg/onedrive#1191]
It seems that, for whatever reason, the instant upload of changes to OneDrive stopped working. I suppose it is the result of some change in the main distro, because nothing changing on the `onedrive` side; but I hope somebody can help me to debug this thing. 

I have the following configuration:

```
Configuration file successfully loaded
onedrive version                       = v2.4.8-7-gba94b92
Config path                            = /home/romano/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/romano/OneDrive
Config option 'skip_dir'               = Attic|Notebooks|Backups|Blocs de Notas
Config option 'skip_file'              = ~*|.~*|*.tmp|Romano @ Universidad*
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = true
business_shared_folders contents:
#
# después de modificar hacer
# onedrive --resync
# 
# Test por si acaso
IEEC 2020
#
```
compiled on a Ubuntu 20.04 (desktop version) from git master, with 
```
[romano:~/software/onedrive/onedrive] master* ± dmd --version
DMD64 D Compiler v2.094.2
```

If I do a `--resync`, the documents are correctly uploaded (but see note 1). But if I change a document locally, it is not automatically uploaded (it worked perfectly one month ago --- I do not know what could have changed). If I stop and restart the service with

```
systemctl --user restart onedrive
```

I have the following in `journalctl --user-unit=onedrive -f`:

```
Dec 18 11:30:15 RRyS systemd[2386]: Stopped OneDrive Free Client.
Dec 18 12:04:54 RRyS systemd[2386]: Started OneDrive Free Client.
Dec 18 12:04:54 RRyS onedrive[31816]: Configuration file successfully loaded
Dec 18 12:04:54 RRyS onedrive[31816]: Configuring Global Azure AD Endpoints
Dec 18 12:04:56 RRyS onedrive[31816]: Initializing the Synchronization Engine ...
Dec 18 12:04:56 RRyS onedrive[31816]: Initializing monitor ...
Dec 18 12:04:56 RRyS onedrive[31816]: OneDrive monitor interval (seconds): 300
```

Notice that I have one file in 
```
[romano:~/OneDrive] % date
Fri 18 Dec 2020 12:05:30 CET
[romano:~/OneDrive] % ls -l *.xlsx
-rw------- 1 romano romano 33838 Dec 17 21:56 'FB Training-backup.xlsx'
-rw------- 1 romano romano 34280 Dec 18 08:53 'FB Training.xlsx'
-rw------- 1 romano romano 33838 Dec 18 12:05  test1.xlsx
```

I tried a `--resync --synchronize`, it works and resynchronize things, although I have a lot of messages like:

```
Processing 247 OneDrive items to ensure consistent local state
Skipping item - excluded by skip_dir config: Backups
``` 
...I supposed that the directory would be ignored completely, also on the other side (It has a lot of things in it). 

I have another instance on a remote computer (same configuration file, on the same OneDrive disk) that seems to work ok. 
How can I find what happens? Is the application when run in user-mode with systems the same as running in `--monitor` mode? If yes, I can try to obtain verbose output for that.

### Bug Report Checklist ###
*   [*] Detailed description
*   [*] Application and Operating System Details provided in full

I am not really sure how to obtain the following in my case... but will try to do it!

*   [] Reproduction steps (if applicable) 
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by Rmano** [comment]
Ah, ok, maybe this is a false alarm. After half an hour...

```
Dec 18 12:04:56 RRyS onedrive[31816]: OneDrive monitor interval (seconds): 300
Dec 18 12:32:59 RRyS onedrive[31816]: Uploading new file ./test1.xlsx ...
Dec 18 12:33:01 RRyS onedrive[31816]: [470B blob data]
Dec 18 12:33:01 RRyS onedrive[31816]: done.
Dec 18 12:48:13 RRyS onedrive[31816]: Starting a sync with OneDrive
Dec 18 12:48:13 RRyS onedrive[31816]: Syncing changes from OneDrive ...
Dec 18 12:48:17 RRyS onedrive[31816]: Sync with OneDrive is complete
Dec 18 12:54:15 RRyS onedrive[31816]: Uploading differences of ./test2.xlsx
Dec 18 12:54:15 RRyS onedrive[31816]: Uploading new items of ./test2.xlsx
Dec 18 12:54:15 RRyS onedrive[31816]: Uploading new file ./test2.xlsx ...
Dec 18 12:54:17 RRyS onedrive[31816]: [470B blob data]
Dec 18 12:54:17 RRyS onedrive[31816]: done.
```

So maybe the problem is that ultra large delay to check the whole `Backup` tree when it then is ignored?

**Comment by abraunegg** [comment]
@Rmano 
When you use `--resync` the application needs to rebuild the local cache. Do not use `--resync` unless the application specifically tells you to. This will delay any local upload because the remote state has to be re-built locally.

Uploading of files immediately requires the support of 'inotify', but if your configured 'sync_dir' is not on a supported file system, inotify cannot work. As you have left out specific details which is asked in the bug report template, I can only assume that you are probably on a supported file system.

If you stop your client, then use verbose debug logging, you can see what is going on with the client:
```
systemctl --user stop onedrive
```
then 
```
onedrive --monitor --verbose --verbose
```

This will show you:
1. What the application is doing
2. When local file changes are detected
3. When the file is uploaded

**Comment by Rmano** [comment]
Ok, sorry for the lack of info. The operating system is Ubuntu 20.04 and the filesystem is `ext4`, so I suppose it is supported. I am running your suggested commands now, and it is generating *a lot* of data. Will try to resume it and make the full one available... but I am not sure how much sensitive info can be in that log. 

Anyway, it seems that it is receiving from OneDrive all the "change" info with respect to the `Backups` directory (which is huge) and only after receiving it decides to ignore the change. One example:

```
[DEBUG] ------------------------------------------------------------------
[DEBUG] Processing change 3 of 239
[DEBUG] OneDrive Change: {"@odata.etag":"\"{F431C886-8C02-4A63-A568-CF55983F2E0A},1\"","@odata.type":"#microsoft.graph.driveItem","cTag":"\"c:{F431C886-8C02-4A63-A568-CF55983F2E0A},0\"","eTag":"\"{F431C886-8C02-4A63-A568-CF55983F2E0A},1\"","fileSystemInfo":{"createdDateTime":"2020-11-19T09:51:29Z","lastModifiedDateTime":"2020-11-19T09:51:29Z"},"folder":{"childCount":4},"id":"01CRET2R4GZAY7IAUMMNFKK2GPKWMD6LQK","name":"Live","parentReference":{"driveId":"b!LtHke7bh3kG0bVzBE1QCWW33fbzkHnhNqI5o-VcAsHJ_LJBMtZ3mQagpnag-F9Cq","driveType":"business","id":"01CRET2RYSRVWZYB6FLNBK6CEFMRDFTXCL","path":"\/drives\/b!LtHke7bh3kG0bVzBE1QCWW33fbzkHnhNqI5o-VcAsHJ_LJBMtZ3mQagpnag-F9Cq\/root:\/Backups"},"size":41191586667}
[DEBUG] Not a OneDrive deleted item change
[DEBUG] defaultRootId                                        = 01CRET2R56Y2GOVW7725BZO354PWSELRRZ
[DEBUG] 'search id'                                          = 01CRET2R56Y2GOVW7725BZO354PWSELRRZ
[DEBUG] id == defaultRootId                                  = true
[DEBUG] isItemRoot(item)                                     = false
[DEBUG] item['name'].str == 'root'                           = false
[DEBUG] singleDirectoryScope                                 = false
[DEBUG] 'parentReference id'                                 = 01CRET2RYSRVWZYB6FLNBK6CEFMRDFTXCL
[DEBUG] search criteria: syncFolderName                      = root
[DEBUG] search criteria: syncFolderPath                      = 
[DEBUG] search criteria: syncFolderChildPath                 = 
[DEBUG] thisItemId                                           = 01CRET2R4GZAY7IAUMMNFKK2GPKWMD6LQK
[DEBUG] thisItemParentPath                                   = /drives/b!LtHke7bh3kG0bVzBE1QCWW33fbzkHnhNqI5o-VcAsHJ_LJBMtZ3mQagpnag-F9Cq/root:/Backups
[DEBUG] thisItemFullPath                                     = /drives/b!LtHke7bh3kG0bVzBE1QCWW33fbzkHnhNqI5o-VcAsHJ_LJBMtZ3mQagpnag-F9Cq/root:/Backups/Live
[DEBUG] 'item id' matches search 'id'                        = false
[DEBUG] 'parentReference id' matches search 'id'             = false
[DEBUG] 'thisItemParentPath' contains 'syncFolderChildPath'  = true
[DEBUG] 'thisItemParentPath' contains search 'id'            = false
[DEBUG] Change matches search criteria to apply
[DEBUG] lastModifiedDateTime (OneDrive item): 2020-Nov-19 09:51:29Z
[DEBUG] Flagging as unwanted: find(item.parentId).length != 0
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] ------------------------------------------------------------------
```

So I suspect that the problem is that OneDrive sends always all the changes (even if there should be much less than the one it sends; that directory is updated nightly with an rclone and only the changed files are uploaded...). 

So it's probably a fact of life and how the protocol works. 

When `onedrive` finishes to discard info from the ignored `Backups` directory it starts working ok.

**Comment by Rmano** [comment]
Hmmm.... log is 
```
[romano:~/tmp] % ls -lh tes*gz
-rw-rw-r-- 1 romano romano 37M Dec 19 17:48 test.log.gz
``` 

;-) I do not know if you still want this...

**Comment by abraunegg** [comment]
@Rmano 
No need for the log file, this all sounds 100% normal.

> If it were possible to avoid the lengthy scan by just synchronizing a subdir of the OneDrive I can adapt to it

Look to use the `--single-directory` option specifying the path that you want to sync.

**Comment by Rmano** [comment]
Is there a config equivalent for --single-directory in the config file? So that I can use it automatically for all my confs...

**Comment by abraunegg** [comment]
@Rmano 
> Is there a config equivalent for --single-directory in the config file? So that I can use it automatically for all my confs...

No there is not. You can modify the systemd files to include this is required.

> Would be this equivalent to use a `sync_list` with just the directory(s) I want to sync? Would this avoid the half-hour delay checking the skipped Backup Directory?

No this is not equivalent, and would be the same as your current situation + be even more time consuming each and every check.

**Comment by abraunegg** [comment]
Closing issue as question answered

**Comment by Rmano** [comment]
1000 thanks! (I noticed that the official onedrive app on Android has the same problem of the long scanning time for the Backup directory... so well, nothing to do). 
I learned things, which is always good.
