### ISSUE TITLE
Invalid UTF-8 sequence (at index 1)

### ISSUE THREAD

**Issue by VincentFrangi** [abraunegg/onedrive#1192]
### Bug Report Details ###

Error message trying to perform `onedrive --synchronize`

```
Giving up on sync after three attempts: Invalid UTF-8 sequence (at index 1)

```
**Application and Operating System Details:**
*  Linux 5.9.11-3-MANJARO
*  i3WM
*   OneDrive classic account
*   I'am using Arch package [onedrive-abraunegg-git](https://aur.archlinux.org/packages/onedrive-abraunegg-git/) (got the same issue, with classic `onedrive-abraunegg` package
*   `onedrive v2.4.8-7-gba94b92`

 ```
Configuration file successfully loaded
onedrive version                       = v2.4.8-7-gba94b92
Config path                            = /home/vincent/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/vincent/OneDrive
Config option 'skip_dir'               = Archives|Attachments
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*    `curl 7.73.0 (x86_64-pc-linux-gnu) libcurl/7.73.0 OpenSSL/1.1.1h zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-10-14
Protocols: dict file ftp ftps gopher http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd`
*   sync_dir' in local
*  'sync_dir' in `ext4` 

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**

```
onedrive --synchronize --resync --verbose
```

```bash
Processing Vincent_Gestion/Travaux/En_cours/Portes/Neuchatel_Bourgogne48/Img5.jpg
The file has not changed
Processing Vincent_Gestion/Travaux/En_cours/Portes/Neuchatel_Bourgogne48/Img2.jpg
The file has not changed
Processing Vincent_Gestion/Travaux/En_cours/Portes/Neuchatel_Bourgogne48/Img8.jpg
The file has not changed
Processing Vincent_Gestion/Travaux/En_cours/Portes/Neuchatel_Bourgogne48/Img9.jpg
The file has not changed
Processing Vincent_Gestion/Travaux/En_cours/Portes/Neuchatel_Bourgogne48/Img3.jpg
The file has not changed
Processing Vincent_Gestion/Travaux/En_cours/Portes/Neuchatel_Bourgogne48/Img4.jpg
The file has not changed
Processing Vincent_Gestion/Travaux/En_cours/Portes/Neuchatel_Bourgogne48/Img7.jpg
The file has not changed
Uploading new items of ~/OneDrive
Giving up on sync after three attempts: Invalid UTF-8 sequence (at index 1)
std.utf.UTFException@/usr/include/dlang/dmd/std/utf.d(1508): Invalid UTF-8 sequence (at index 1)
----------------
??:? pure dchar std.utf.decodeImpl!(true, 0, const(char)[]).decodeImpl(ref const(char)[], ref ulong) [0x559e4dacc0f2]
??:? pure @trusted dchar std.utf.decode!(0, const(char)[]).decode(ref const(char)[], ref ulong) [0x559e4dacbcd9]
??:? pure @property @safe dchar std.range.primitives.front!(char).front(scope const(char)[]) [0x559e4dacbc0f]
??:? pure @safe std.uni.Grapheme std.uni.genericDecodeGrapheme!(true).genericDecodeGrapheme!(immutable(char)[]).genericDecodeGrapheme(ref immutable(char)[]) [0x559e4db756bc]
??:? pure @safe std.uni.Grapheme std.uni.decodeGrapheme!(immutable(char)[]).decodeGrapheme(ref immutable(char)[]) [0x559e4db75338]
??:? pure @safe void std.uni.byGrapheme!(immutable(char)[]).byGrapheme(immutable(char)[]).Result!(immutable(char)[]).Result.popFront() [0x559e4db75144]
??:? pure @safe ulong std.range.primitives.walkLength!(std.uni.byGrapheme!(immutable(char)[]).byGrapheme(immutable(char)[]).Result!(immutable(char)[]).Result).walkLength(std.uni.byGrapheme!(immutable(char)[]).byGrapheme(immutable(char)[]).Result!(immutable(char)[]).Result) [0x559e4db75956]
??:? void sync.SyncEngine.uploadNewItems(const(immutable(char)[])) [0x559e4dbb3171]
??:? void sync.SyncEngine.uploadNewItems(const(immutable(char)[])) [0x559e4dbb3c63]
??:? void sync.SyncEngine.uploadNewItems(const(immutable(char)[])) [0x559e4dbb3c63]
??:? void sync.SyncEngine.uploadNewItems(const(immutable(char)[])) [0x559e4dbb3c63]
??:? void sync.SyncEngine.uploadNewItems(const(immutable(char)[])) [0x559e4dbb3c63]
??:? void sync.SyncEngine.uploadNewItems(const(immutable(char)[])) [0x559e4dbb3c63]
??:? void sync.SyncEngine.uploadNewItems(const(immutable(char)[])) [0x559e4dbb3c63]
??:? void sync.SyncEngine.uploadNewItems(const(immutable(char)[])) [0x559e4dbb3c63]
??:? void sync.SyncEngine.uploadNewItems(const(immutable(char)[])) [0x559e4dbb3c63]
??:? void sync.SyncEngine.uploadNewItems(const(immutable(char)[])) [0x559e4dbb3c63]
??:? void sync.SyncEngine.uploadNewItems(const(immutable(char)[])) [0x559e4dbb3c63]
??:? void sync.SyncEngine.scanForDifferences(const(immutable(char)[])) [0x559e4dbb00cd]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool, bool, bool, bool, monitor.Monitor) [0x559e4db956ad]
??:? _Dmain [0x559e4db93e52]
std.net.curl.CurlException@std/net/curl.d(4402): A libcurl function was given a bad argument on handle null
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x559e4dc39e2a]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x559e4dc39d9b]
??:? void std.net.curl.Curl._check(int) [0x559e4dc07b53]
??:? void std.net.curl.Curl.clear(etc.c.curl.CurlOption) [0x559e4dc07efe]
??:? void std.net.curl.HTTP.clearRequestHeaders() [0x559e4dc06c33]
??:? void onedrive.OneDriveApi.shutdown() [0x559e4db995c4]
??:? _Dmain [0x559e4db94b68]
```

Maybe someone got an idea,
Thanks in advance

**Comment by abraunegg** [comment]
@VincentFrangi 
As this is a bug and crash, please can you send a verbose debug log to the support email address please.

**verbose debug log:**
```
onedrive --synchronize --resync --verbose --verbose
```

**Comment by abraunegg** [comment]
@VincentFrangi 

Please can you also test the following PR when generating the debug log:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1192/head:pr1192
git checkout pr1192
./configure; make clean; make;
```

When running the PR, your version should be: `onedrive v2.4.8-8-g72a1de4` or greater.

**Comment by VincentFrangi** [comment]
> u also test the following PR when generating the debug log:
> 
> ```
> git clone https://github.com/abraunegg/onedrive.git
> cd onedrive
> git fetch origin pull/1192/head:pr1192
> git checkout pr1192
> ```

I wasn't able to fetch the ref

```
~/D/onedrive (master)> git fetch origin pull/1192/head:pr1192
fatal: couldn't find remote ref pull/1192/head
```

**Comment by abraunegg** [comment]
@VincentFrangi 
My apologies - incorrect instructions - used the issue number not the PR number. Please try:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1193/head:pr1193
git checkout pr1193
./configure; make clean; make;
```
as per below:
```
(dmd-2.093.1)[alex@centos7full ~]$ git clone https://github.com/abraunegg/onedrive.git
Cloning into 'onedrive'...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 4423 (delta 44), reused 41 (delta 24), pack-reused 4334
Receiving objects: 100% (4423/4423), 3.14 MiB | 1.80 MiB/s, done.
Resolving deltas: 100% (3045/3045), done.
(dmd-2.093.1)[alex@centos7full ~]$ cd onedrive
(dmd-2.093.1)[alex@centos7full onedrive]$ git fetch origin pull/1193/head:pr1193
From https://github.com/abraunegg/onedrive
 * [new ref]         refs/pull/1193/head -> pr1193
(dmd-2.093.1)[alex@centos7full onedrive]$ git checkout pr1193
Switched to branch 'pr1193'
(dmd-2.093.1)[alex@centos7full onedrive]$ ./configure; make clean; make;
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.093.1
checking for curl... yes
checking for sqlite... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.4.9-dev > version ; \
fi
dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
(dmd-2.093.1)[alex@centos7full onedrive]$ ./onedrive --version
onedrive v2.4.8-8-g72a1de4
(dmd-2.093.1)[alex@centos7full onedrive]$ 
```

**Comment by VincentFrangi** [comment]
> @VincentFrangi
> My apologies - incorrect instructions - used the issue number not the PR number. Please try:
> 
> ```
> git clone https://github.com/abraunegg/onedrive.git
> cd onedrive
> git fetch origin pull/1193/head:pr1193
> git checkout pr1193
> ./configure; make clean; make;
> ```
> 
> as per below:
> 
> ```
> (dmd-2.093.1)[alex@centos7full ~]$ git clone https://github.com/abraunegg/onedrive.git
> Cloning into 'onedrive'...
> remote: Enumerating objects: 89, done.
> remote: Counting objects: 100% (89/89), done.
> remote: Compressing objects: 100% (63/63), done.
> remote: Total 4423 (delta 44), reused 41 (delta 24), pack-reused 4334
> Receiving objects: 100% (4423/4423), 3.14 MiB | 1.80 MiB/s, done.
> Resolving deltas: 100% (3045/3045), done.
> (dmd-2.093.1)[alex@centos7full ~]$ cd onedrive
> (dmd-2.093.1)[alex@centos7full onedrive]$ git fetch origin pull/1193/head:pr1193
> From https://github.com/abraunegg/onedrive
>  * [new ref]         refs/pull/1193/head -> pr1193
> (dmd-2.093.1)[alex@centos7full onedrive]$ git checkout pr1193
> Switched to branch 'pr1193'
> (dmd-2.093.1)[alex@centos7full onedrive]$ ./configure; make clean; make;
> checking for a BSD-compatible install... /usr/bin/install -c
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for dmd... dmd
> checking version of D compiler... 2.093.1
> checking for curl... yes
> checking for sqlite... yes
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating contrib/pacman/PKGBUILD
> config.status: creating contrib/spec/onedrive.spec
> config.status: creating onedrive.1
> config.status: creating contrib/systemd/onedrive.service
> config.status: creating contrib/systemd/onedrive@.service
> rm -f onedrive onedrive.o version
> rm -rf autom4te.cache
> rm -f config.log config.status
> if [ -f .git/HEAD ] ; then \
>         git describe --tags > version ; \
> else \
>         echo v2.4.9-dev > version ; \
> fi
> dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
> (dmd-2.093.1)[alex@centos7full onedrive]$ ./onedrive --version
> onedrive v2.4.8-8-g72a1de4
> (dmd-2.093.1)[alex@centos7full onedrive]$ 
> ```

pr1193 seem to have fix the issue!
Thank you
