### ISSUE TITLE
Feature request: Support for Healthchecks.io

### ISSUE THREAD

**Issue by jtenniswood** [abraunegg/onedrive#1195]
I would love to be able to monitor the status of syncs using Healthchecks.io
Not sure if that’s easy one to add?

**Comment by abraunegg** [comment]
@jtenniswood 
This is not easy to do from inside the application.

What would be easier to do, would be for you to:
* Utilise the 'cronjob' option as per the https://healthchecks.io/ documentation and use `--synchronize` to sync your data
* Update your systemd configuration to support healthchecks.io using the following example: https://gist.github.com/elyscape/7e8c1ea7ae186fd780c59e8cbf87181d

If you find something that does work, contribute back here with a Wiki update or PR to add documentation as to how to do it.

**Comment by abraunegg** [comment]
Closing this feature request for the following reason:
* Unable to support, workaround available
