### ISSUE TITLE
Not skipping folders 

### ISSUE THREAD

**Issue by grxgghxrpxr** [abraunegg/onedrive#1196]
Thank you so much for creating a client for OneDrive, it has made my life learning how to use Linux so much easier.

One issue I’m having is that I’ve entered in the config file to skip some directories, yet it still downloads them.

 

I want to skip the following folders:

Downloads

Public

A folder called ‘Downloaded music’ in a folder called ‘Music’.

 

In the config file, I have entered this:

‘skip_dir = “Downloads|Music/Downloaded Music|Public’

 

Is there something I’m doing wrong? Or is there anything else I have to do?

 

Thanks

Gregg

**Comment by abraunegg** [comment]
@grxgghxrpxr 
Please follow the correct support procedure as detailed here: https://github.com/abraunegg/onedrive#reporting-issues

You have not:
1. Followed the correct support procedure
2. Used the bug report template
