### ISSUE TITLE
Enhancement: progress of large uploads on normal log

### ISSUE THREAD

**Issue by Abasz** [abraunegg/onedrive#12]
It would be good to be able to follow the upload progress in normal log not just in verbose mode (e.g. logging the percentage of the fragments)

**Comment by Abasz** [comment]
Hi, since I was testing, I have given some thought to this as well. So the simplest way to do is put a log.log in upload.d in the JSONValue upload function just below the `log.vlog("Uploading fragment: ", offset, "-", offset + fragSize, "/", fileSize);` ) call

The following code could do the trick: `log.log("Progress: ", double(offset)/fileSize*100,"%");`

If you feel you can cut the decimals to one decimal place to have a more elegant output

**Comment by abraunegg** [comment]
Thanks for the feedback & trying something out on this - will look at this later today

**Comment by abraunegg** [comment]
So with adding in the data this way it is totally dependant on the file size / fragment size. If still a large file but <10Mb progress stays at 0% then gets done, if 20Mb and so on it gets Progress: 50% then done. I was reading a number of other articles a while back on some other items - will dig this out as I think the right way to do this is elsewhere.

**Comment by Abasz** [comment]
You are absolutely correct, this outputs a lot of 0% as the main source of truth here are the fragments and onedirve large file logic. I also mentioned that this is the simplest way just with 1 line of code to add :)

The problem here is that the need for information depends on two things: file size (that is an easy one as we have that info) and the upload speed (this is problematic as it likely changes over time). The reason being is that if you have a 10mb file but your upload speed is only 10kb than you surely want some output of the progress, but if your upload speed is 10mb you would not want upload progress for a file less that a few hundred mb.

**Comment by abraunegg** [comment]
I think the right way to do this is to utilise http.onProgress to display this information - will work on that aspect & why it's being fickle at the moment.

**Comment by Abasz** [comment]
Confirmed, log works

**Comment by Abasz** [comment]
This works just great. Nice work!

It was a good idea to remove it from the log and put it to screen only (if one just thinks about it, from a log perspective the progress is not relevant - e.g. when you run it as a daemon, but when you actually have a terminal open to track the progress than you do want some feedback)

one thing, but its more like a nice to have: we upload/download is finished, the ETA that is currently changes to 00:00:00 could show the time required for upload.

**Comment by abraunegg** [comment]
thanks for the suggestion - agree that the ETA should be changed from `ETA 00:00:00` to list how long it actually took.

Will also look at how best to integrate with a download operation - as that will be easier than handling the chunks for upload using http.onProgress

**Comment by abraunegg** [comment]
@Abasz 
Can you check the latest pull of PR #99? You should get something similar to this for uploads now:

In-progress upload:
```
Uploading  66% |ooooooooooooooooooooooooooo             |   ETA   00:00:03     
```

Completed upload:
```
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:17
```

**Comment by abraunegg** [comment]
@Abasz 
Can you help validate the latest code from PR #99?

Along with the upload progress bar, there should now be a working download progress bar for large files - where the file threshold is the same for uploads of 4MiB:
```
Loading config ...
Using Config Dir: /root/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 5344558311
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: <redacted>
Downloading file large_file1.txt ... 
Downloading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:08                                                                                                         
done.
Downloading file white_paper_c11-494994.pdf ... 
done.
Uploading differences of .
Processing root
The directory has not changed
Processing large_file1.txt
The file has not changed
Processing white_paper_c11-494994.pdf
The file has not changed
Uploading new items of .
Applying changes of Path ID: <redacted>
```

**Comment by abraunegg** [comment]
@Abasz 
Any update testing the latest PR #99?

**Comment by abraunegg** [comment]
Closing due to merge into master of PR #99

**Comment by Abasz** [comment]
Sorry, I am on holiday with limited access :) I'll be able to have a look at this on Sunday the earliest
