### ISSUE TITLE
solution to: User tried to log in to a device from a platform (Unknown)

### ISSUE THREAD

**Issue by emdej** [abraunegg/onedrive#1200]
This is about #666 and #13 - seems this can be fixed as `rclone` works well. The way they authenticate is more automatic (they open web browser for user and a temporary local http server is involved).

I don't know how the MS authentication works but seems it is possible to cope with that issue.

**Comment by abraunegg** [comment]
@emdej 
I am well aware of how `rclone` does this, however, what is not well known is the Azure AD configuration performed to create this scenario that generates this issue in the first place. Without knowing that, no fix can be developed or tested.

If this is your issue, speak to your Azure AD Administrator to understand what security settings are being set that are too restrictive and / or create a PR to implement this fix. PR's are always welcome.
