### ISSUE TITLE
Bug report: docker container alpine build fails for aarch64

### ISSUE THREAD

**Issue by hllhll** [abraunegg/onedrive#1205]
### Bug Report Details ###
Since I want to use a container, prebuild ones aren't for raspbery pi (4) I've tried building the apline image
**Describe the bug**
`docker build . -t local-ondrive-alpine -f contrib/docker/Dockerfile-alpine` results in
```
$ docker build . -t local-ondrive-alpine -f contrib/docker/Dockerfile-alpine
Sending build context to Docker daemon  5.329MB
Step 1/10 : FROM golang:alpine
alpine: Pulling from library/golang
159e5727ea61: Already exists
89e1f0424fba: Pull complete
4e458f4c6c66: Pull complete
ec4e3c46f4b2: Pull complete
577341a4c2b5: Pull complete
Digest: sha256:49b4eac11640066bc72c74b70202478b7d431c7d8918e0973d6e4aeb8b3129d2
Status: Downloaded newer image for golang:alpine
 ---> ad8b97833863
Step 2/10 : RUN apk add     alpine-sdk gnupg xz curl-dev sqlite-dev binutils-gold     autoconf automake ldc
 ---> Running in 258f3452f7b0
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/aarch64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.12/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.2c4ac24e.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/aarch64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.12/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.40a3604f.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  alpine-sdk (missing):
    required by: world[alpine-sdk]
  autoconf (missing):
    required by: world[autoconf]
  automake (missing):
    required by: world[automake]
  binutils-gold (missing):
    required by: world[binutils-gold]
  curl-dev (missing):
    required by: world[curl-dev]
  gnupg (missing):
    required by: world[gnupg]
  ldc (missing):
    required by: world[ldc]
  sqlite-dev (missing):
    required by: world[sqlite-dev]
  xz (missing):
    required by: world[xz]
The command '/bin/sh -c apk add     alpine-sdk gnupg xz curl-dev sqlite-dev binutils-gold     autoconf automake ldc' returned a non-zero code: 9
```
**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
Raspberry pi 4 @ Raspberry pi os 64 bit
`Linux raspberrypi 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed?
No Gui - terminal
*   Did you build from source or install from a package?
Building the alpine dockerfile from the contrib folder

Not relevant for my case?:
*   OneDrive Account Type - NA - Build process
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
*   OneDrive Application Version: Output of `onedrive --version`
*   OneDrive Application Configuration: Output of `onedrive --display-config`
*   Provide the version of curl you are using: Output of `curl --version`
*   Is your configured 'sync_dir' a local directory or a network mount point?
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Try [to build the alpine docker image](https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md#building-the-docker-image)on rpi4 @ 64 bit raspberry pi os

### Bug Report Checklist ###
*   [V] Detailed description
*   [V] Application and Operating System Details provided in full
*   [V] Reproduction steps (if applicable)
*   [V] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by hllhll** [comment]
I See there's a different dockerfile for raspberry, can't the alpine be used? since rpi makes `FROM debian:stretch-slim` Which, I guess is larger then the one made by alpine.
Anyway that should be good enough for me, maybe documentation should be updated. I'm leaving it open for the sake of maybe clarifying the documentation [here](https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md#building-the-docker-image)

**Comment by hllhll** [comment]
Scrap everything, Have a setup problem I guess.

**Comment by abraunegg** [comment]
@hllhll 
The 'alpine' builds are fairly unique and I guess this is why the current apline x64 Dockerfile wont build for ARM.

You are better off building your own Docker image using the  'Dockerfile-rpi' file from the contrib directory using the following process:

https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md#building-the-docker-image

Example:
```
docker build . -t local-ondrive-stretch -f contrib/docker/Dockerfile-rpi
```
