### ISSUE TITLE
Slow Uploading Issue

### ISSUE THREAD

**Issue by najum98** [abraunegg/onedrive#1206]
Hello, I really loved your tool and effort in making this tool.
But I am facing a issue with it, I have a decent internet connection and earlier when I was using Mega Sync it was also working perfectly alright, but this onedrive client is uploading data really slow, its like 10MBs/2-3 hours which is very slow and would take months to upload the amount of data I am trying to upload.

Each time I run `onedrive --display-sync-status -v` it always shows me "Approximate data to transfer: 1300070 KB" and this data amount is also not altering. Is there any way I can speed up this process?

**Comment by abraunegg** [comment]
@najum98 
> But I am facing a issue with it, I have a decent internet connection and earlier when I was using Mega Sync it was also working perfectly alright, but this onedrive client is uploading data really slow, its like 10MBs/2-3 hours which is very slow and would take months to upload the amount of data I am trying to upload.

What are the file sizes that you are uploading? I do not see this sort of issue (speed wise) and can upload many GB of data without issue in a short period of time. The client does have issue with many small files, simply because of the current single threaded nature of the application - see #232

> Each time I run `onedrive --display-sync-status -v` it always shows me "Approximate data to transfer: 1300070 KB" and this data amount is also not altering. Is there any way I can speed up this process?

The `--display-sync-status` shows if your local directory is in-sync or not, and the value presented represents what needs to be downloaded from OneDrive. It does not display what needs to be uploaded.

2 enhancements are potentially needed here:
1. Update the messaging around 'Approximate data to transfer' to better indicate that this is what is needed to be downloaded
2. Do a local filesystem walk to determine files that need to be uploaded to display an upload value

**Comment by najum98** [comment]
> @najum98
> 
> > But I am facing a issue with it, I have a decent internet connection and earlier when I was using Mega Sync it was also working perfectly alright, but this onedrive client is uploading data really slow, its like 10MBs/2-3 hours which is very slow and would take months to upload the amount of data I am trying to upload.
> 
> What are the file sizes that you are uploading? I do not see this sort of issue (speed wise) and can upload many GB of data without issue in a short period of time. The client does have issue with many small files, simply because of the current single threaded nature of the application - see #232
> 
> > Each time I run `onedrive --display-sync-status -v` it always shows me "Approximate data to transfer: 1300070 KB" and this data amount is also not altering. Is there any way I can speed up this process?
> 
> The `--display-sync-status` shows if your local directory is in-sync or not, and the value presented represents what needs to be downloaded from OneDrive. It does not display what needs to be uploaded.
> 
> 2 enhancements are potentially needed here:
> 
>     1. Update the messaging around 'Approximate data to transfer' to better indicate that this is what is needed to be downloaded
> 
>     2. Do a local filesystem walk to determine files that need to be uploaded to display an upload value

These are many files having a varying size from under 1MB to almost 7GB per file so its a mixture of different sizes but the upload is really slow

**Comment by abraunegg** [comment]
@najum98 

Please can you test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1209/head:pr1209
git checkout pr1209
./configure; make clean; make;
```

When running the PR, your version should be: `onedrive v2.4.9-2-g4e853ec`

This PR does the following:
* In verbose mode, outputs the time it took to upload the file
* Provides a rough calculation as to the Mb per second throughput of uploading the file

Examples below:
```
---------------------- small files, business account ----------------------

Remaining free space on OneDrive: 1098816564760
Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file154.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01                                                                                                                    
done.
File Size: 577600 Bytes
Upload Duration: 0.941 Seconds
Upload Speed: 0.58538 Mbps (approx)
Remaining free space on OneDrive: 1098815987160
Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file155.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01                                                                                                                    
done.
File Size: 94848 Bytes
Upload Duration: 0.812 Seconds
Upload Speed: 0.111397 Mbps (approx)
Remaining free space on OneDrive: 1098815892312
Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file156.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01                                                                                                                    
done.
File Size: 836640 Bytes
Upload Duration: 1.201 Seconds
Upload Speed: 0.664348 Mbps (approx)
Remaining free space on OneDrive: 1098815055672
Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file157.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:00                                                                                                                    
done.
File Size: 344032 Bytes
Upload Duration: 1.074 Seconds
Upload Speed: 0.305488 Mbps (approx)

---------------------- small files, personal account ----------------------

Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file275.data ... done.
File Size: 947392 Bytes
Upload Duration: 1.596 Seconds
Upload Speed: 0.566105 Mbps (approx)
Remaining free space on OneDrive: 5184633375
Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file276.data ... done.
File Size: 717088 Bytes
Upload Duration: 1.236 Seconds
Upload Speed: 0.553292 Mbps (approx)
Remaining free space on OneDrive: 5183916287
Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file277.data ... done.
File Size: 887104 Bytes
Upload Duration: 1.741 Seconds
Upload Speed: 0.485932 Mbps (approx)
Remaining free space on OneDrive: 5183029183
Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file278.data ... done.
File Size: 184032 Bytes
Upload Duration: 0.745 Seconds
Upload Speed: 0.235579 Mbps (approx)
Remaining free space on OneDrive: 5182845151
Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file279.data ... done.
File Size: 848576 Bytes
Upload Duration: 1.291 Seconds
Upload Speed: 0.626851 Mbps (approx)
Remaining free space on OneDrive: 5181996575
Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file280.data ... done.
File Size: 456768 Bytes
Upload Duration: 1.026 Seconds
Upload Speed: 0.424569 Mbps (approx)
Remaining free space on OneDrive: 5181539807
Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file281.data ... done.
File Size: 667008 Bytes
Upload Duration: 1.008 Seconds
Upload Speed: 0.63106 Mbps (approx)

---------------------- large files, business account ----------------------

Successfully created the remote directory ./random_files/vdAm1O9r2rKfcqlJV5h4Pm11n0bt3tlC on OneDrive
Uploading new file ./random_files/vdAm1O9r2rKfcqlJV5h4Pm11n0bt3tlC/file0.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:21                                                                                                                    
done.
File Size: 67672064 Bytes
Upload Duration: 22.04 Seconds
Upload Speed: 2.92818 Mbps (approx)
Remaining free space on OneDrive: 1098744422884
Uploading new file ./random_files/vdAm1O9r2rKfcqlJV5h4Pm11n0bt3tlC/file1.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:19                                                                                                                    
done.
File Size: 67604480 Bytes
Upload Duration: 19.429 Seconds
Upload Speed: 3.31837 Mbps (approx)
Remaining free space on OneDrive: 1098676818404
Uploading new file ./random_files/vdAm1O9r2rKfcqlJV5h4Pm11n0bt3tlC/file2.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:05                                                                                                                    
done.
File Size: 14008320 Bytes
Upload Duration: 5.199 Seconds
Upload Speed: 2.5696 Mbps (approx)
Remaining free space on OneDrive: 1098662810084
Uploading new file ./random_files/vdAm1O9r2rKfcqlJV5h4Pm11n0bt3tlC/file3.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:08                                                                                                                    
done.
File Size: 26552320 Bytes
Upload Duration: 8.27 Seconds
Upload Speed: 3.06194 Mbps (approx)
Remaining free space on OneDrive: 1098636257764
Uploading new file ./random_files/vdAm1O9r2rKfcqlJV5h4Pm11n0bt3tlC/file4.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01                                                                                                                    
done.
File Size: 2846720 Bytes
Upload Duration: 1.921 Seconds
Upload Speed: 1.41325 Mbps (approx)
Remaining free space on OneDrive: 1098633411044
Skipping item - excluded as included in business_shared_folders config: ./Top Folder
To sync this directory to your OneDrive Account update your business_shared_folders config
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1098633407405

---------------------- large files, personal account ----------------------

Successfully created the remote directory ./random_files/OWighfHS7younq7Pqh2iYnJWoDp8pWRM on OneDrive
Uploading new file ./random_files/OWighfHS7younq7Pqh2iYnJWoDp8pWRM/file0.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:18                                                                                                                    
done.
File Size: 43501568 Bytes
Upload Duration: 17.775 Seconds
Upload Speed: 2.33397 Mbps (approx)
Remaining free space on OneDrive: 5304489585
Uploading new file ./random_files/OWighfHS7younq7Pqh2iYnJWoDp8pWRM/file1.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:14                                                                                                                    
done.
File Size: 47484928 Bytes
Upload Duration: 14.316 Seconds
Upload Speed: 3.16325 Mbps (approx)
Remaining free space on OneDrive: 5257004657
Uploading new file ./random_files/OWighfHS7younq7Pqh2iYnJWoDp8pWRM/file2.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:09                                                                                                                    
done.
File Size: 29560832 Bytes
Upload Duration: 8.853 Seconds
Upload Speed: 3.18439 Mbps (approx)
Remaining free space on OneDrive: 5227443825
Uploading new file ./random_files/OWighfHS7younq7Pqh2iYnJWoDp8pWRM/file3.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:12                                                                                                                    
done.
File Size: 42463232 Bytes
Upload Duration: 11.93 Seconds
Upload Speed: 3.39448 Mbps (approx)
Remaining free space on OneDrive: 5184980593
Uploading new file ./random_files/OWighfHS7younq7Pqh2iYnJWoDp8pWRM/file4.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:03                                                                                                                    
done.
File Size: 8960000 Bytes
Upload Duration: 3.972 Seconds
Upload Speed: 2.15129 Mbps (approx)
Remaining free space on OneDrive: 5176020593
```

If your upload is still really slow, then you need to take this up with your Internet provider.

**Comment by najum98** [comment]
> @najum98
> 
> Please can you test the following PR:
> 
> ```
> git clone https://github.com/abraunegg/onedrive.git
> cd onedrive
> git fetch origin pull/1209/head:pr1209
> git checkout pr1209
> ./configure; make clean; make;
> ```
> 
> When running the PR, your version should be: `onedrive v2.4.9-2-g4e853ec`
> 
> This PR does the following:
> 
>     * In verbose mode, outputs the time it took to upload the file
> 
>     * Provides a rough calculation as to the Mb per second throughput of uploading the file
> 
> 
> Examples below:
> 
> ```
> ---------------------- small files, business account ----------------------
> 
> Remaining free space on OneDrive: 1098816564760
> Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file154.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01                                                                                                                    
> done.
> File Size: 577600 Bytes
> Upload Duration: 0.941 Seconds
> Upload Speed: 0.58538 Mbps (approx)
> Remaining free space on OneDrive: 1098815987160
> Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file155.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01                                                                                                                    
> done.
> File Size: 94848 Bytes
> Upload Duration: 0.812 Seconds
> Upload Speed: 0.111397 Mbps (approx)
> Remaining free space on OneDrive: 1098815892312
> Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file156.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01                                                                                                                    
> done.
> File Size: 836640 Bytes
> Upload Duration: 1.201 Seconds
> Upload Speed: 0.664348 Mbps (approx)
> Remaining free space on OneDrive: 1098815055672
> Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file157.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:00                                                                                                                    
> done.
> File Size: 344032 Bytes
> Upload Duration: 1.074 Seconds
> Upload Speed: 0.305488 Mbps (approx)
> 
> ---------------------- small files, personal account ----------------------
> 
> Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file275.data ... done.
> File Size: 947392 Bytes
> Upload Duration: 1.596 Seconds
> Upload Speed: 0.566105 Mbps (approx)
> Remaining free space on OneDrive: 5184633375
> Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file276.data ... done.
> File Size: 717088 Bytes
> Upload Duration: 1.236 Seconds
> Upload Speed: 0.553292 Mbps (approx)
> Remaining free space on OneDrive: 5183916287
> Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file277.data ... done.
> File Size: 887104 Bytes
> Upload Duration: 1.741 Seconds
> Upload Speed: 0.485932 Mbps (approx)
> Remaining free space on OneDrive: 5183029183
> Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file278.data ... done.
> File Size: 184032 Bytes
> Upload Duration: 0.745 Seconds
> Upload Speed: 0.235579 Mbps (approx)
> Remaining free space on OneDrive: 5182845151
> Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file279.data ... done.
> File Size: 848576 Bytes
> Upload Duration: 1.291 Seconds
> Upload Speed: 0.626851 Mbps (approx)
> Remaining free space on OneDrive: 5181996575
> Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file280.data ... done.
> File Size: 456768 Bytes
> Upload Duration: 1.026 Seconds
> Upload Speed: 0.424569 Mbps (approx)
> Remaining free space on OneDrive: 5181539807
> Uploading new file ./random_files/G0E9sC3ZlL50epck6d8ITKG7zgrGvHJs/file281.data ... done.
> File Size: 667008 Bytes
> Upload Duration: 1.008 Seconds
> Upload Speed: 0.63106 Mbps (approx)
> 
> ---------------------- large files, business account ----------------------
> 
> Successfully created the remote directory ./random_files/vdAm1O9r2rKfcqlJV5h4Pm11n0bt3tlC on OneDrive
> Uploading new file ./random_files/vdAm1O9r2rKfcqlJV5h4Pm11n0bt3tlC/file0.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:21                                                                                                                    
> done.
> File Size: 67672064 Bytes
> Upload Duration: 22.04 Seconds
> Upload Speed: 2.92818 Mbps (approx)
> Remaining free space on OneDrive: 1098744422884
> Uploading new file ./random_files/vdAm1O9r2rKfcqlJV5h4Pm11n0bt3tlC/file1.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:19                                                                                                                    
> done.
> File Size: 67604480 Bytes
> Upload Duration: 19.429 Seconds
> Upload Speed: 3.31837 Mbps (approx)
> Remaining free space on OneDrive: 1098676818404
> Uploading new file ./random_files/vdAm1O9r2rKfcqlJV5h4Pm11n0bt3tlC/file2.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:05                                                                                                                    
> done.
> File Size: 14008320 Bytes
> Upload Duration: 5.199 Seconds
> Upload Speed: 2.5696 Mbps (approx)
> Remaining free space on OneDrive: 1098662810084
> Uploading new file ./random_files/vdAm1O9r2rKfcqlJV5h4Pm11n0bt3tlC/file3.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:08                                                                                                                    
> done.
> File Size: 26552320 Bytes
> Upload Duration: 8.27 Seconds
> Upload Speed: 3.06194 Mbps (approx)
> Remaining free space on OneDrive: 1098636257764
> Uploading new file ./random_files/vdAm1O9r2rKfcqlJV5h4Pm11n0bt3tlC/file4.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01                                                                                                                    
> done.
> File Size: 2846720 Bytes
> Upload Duration: 1.921 Seconds
> Upload Speed: 1.41325 Mbps (approx)
> Remaining free space on OneDrive: 1098633411044
> Skipping item - excluded as included in business_shared_folders config: ./Top Folder
> To sync this directory to your OneDrive Account update your business_shared_folders config
> Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
> Updated Remaining Free Space: 1098633407405
> 
> ---------------------- large files, personal account ----------------------
> 
> Successfully created the remote directory ./random_files/OWighfHS7younq7Pqh2iYnJWoDp8pWRM on OneDrive
> Uploading new file ./random_files/OWighfHS7younq7Pqh2iYnJWoDp8pWRM/file0.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:18                                                                                                                    
> done.
> File Size: 43501568 Bytes
> Upload Duration: 17.775 Seconds
> Upload Speed: 2.33397 Mbps (approx)
> Remaining free space on OneDrive: 5304489585
> Uploading new file ./random_files/OWighfHS7younq7Pqh2iYnJWoDp8pWRM/file1.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:14                                                                                                                    
> done.
> File Size: 47484928 Bytes
> Upload Duration: 14.316 Seconds
> Upload Speed: 3.16325 Mbps (approx)
> Remaining free space on OneDrive: 5257004657
> Uploading new file ./random_files/OWighfHS7younq7Pqh2iYnJWoDp8pWRM/file2.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:09                                                                                                                    
> done.
> File Size: 29560832 Bytes
> Upload Duration: 8.853 Seconds
> Upload Speed: 3.18439 Mbps (approx)
> Remaining free space on OneDrive: 5227443825
> Uploading new file ./random_files/OWighfHS7younq7Pqh2iYnJWoDp8pWRM/file3.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:12                                                                                                                    
> done.
> File Size: 42463232 Bytes
> Upload Duration: 11.93 Seconds
> Upload Speed: 3.39448 Mbps (approx)
> Remaining free space on OneDrive: 5184980593
> Uploading new file ./random_files/OWighfHS7younq7Pqh2iYnJWoDp8pWRM/file4.data ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:03                                                                                                                    
> done.
> File Size: 8960000 Bytes
> Upload Duration: 3.972 Seconds
> Upload Speed: 2.15129 Mbps (approx)
> Remaining free space on OneDrive: 5176020593
> ```
> 
> If your upload is still really slow, then you need to take this up with your Internet provider.

Will doing this require me to delete my previous onedrive set up and make all the configurations again?

**Comment by abraunegg** [comment]
@najum98 
> Will doing this require me to delete my previous onedrive set up and make all the configurations again?

No - your configurations remain, only the application binary needs to be updated.

**Comment by najum98** [comment]
> @najum98
> 
> > Will doing this require me to delete my previous onedrive set up and make all the configurations again?
> 
> No - your configurations remain, only the application binary needs to be updated.

Ok so I tried it, installed all the dependencies for Debian 10 from  https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#build-requirements and then also activated the environment, then I ran the commands you gave but when I run the last line i.e `./configure;make clean;make;   ` it gives the following output:
`./configure: line 1409: config.log: Permission denied
./configure: line 1419: config.log: Permission denied
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
`
With sudo it says source not found. The terminal is showing the environment activated which is (dmd-2.094.2)

**Comment by abraunegg** [comment]
@najum98 
> ```
> ./configure: line 1409: config.log: Permission denied
>```


You have some incorrect permissions somewhere. Potentially you have run a command / some of the commands with sudo at 'some point'

Remove the 'onedrive' directory that git created, and start from scratch there.

Do not use sudo at all, unless you are performing the 'make install' - every other command is done without using sudo.

If you are still getting this error - this is a permissions error on your local system. I cannot assist you with that and you will need to debug to work out what permission is wrong & why & fix.

**Comment by najum98** [comment]
> @najum98
> 
> > ```
> > ./configure: line 1409: config.log: Permission denied
> > ```
> 
> You have some incorrect permissions somewhere. Potentially you have run a command / some of the commands with sudo at 'some point'
> 
> Remove the 'onedrive' directory that git created, and start from scratch there.
> 
> Do not use sudo at all, unless you are performing the 'make install' - every other command is done without using sudo.
> 
> If you are still getting this error - this is a permissions error on your local system. I cannot assist you with that and you will need to debug to work out what permission is wrong & why & fix.

Ok so I have repeated the process without "sudo" and got this:
`checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.094.2
checking for curl... yes
checking for sqlite... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.4.10-dev > version ; \
fi
dmd -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
`

But the version is still the older one.

**Comment by abraunegg** [comment]
@najum98 
> But the version is still the older one.

This is because you are not installing the client or running it from the 'onedrive' directory

To compile the PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1209/head:pr1209
git checkout pr1209
./configure; make clean; make;
```

To run / test the PR - from inside the 'onedrive' directory:
```
./onedrive --version
```

To install the PR:
```
sudo make install
```

**Comment by najum98** [comment]
I dont think so that the tool is giving any new detail in verbose mode, also the config file got back to default and I had to fix it.
I ran `onedrive --display-sync-status -v` and got this
`Using 'user' Config Dir: /home/najamulsaqib/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/najamulsaqib/OneDrive
Application version: v2.4.9-2-g4e853ec
Account Type: business
Default Drive ID:***
Default Root ID: ***
Remaining Free Space: 1056522136884
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Local directory is out of sync with OneDrive
Approximate data to download from OneDrive: 1300070 KB
`

**Comment by najum98** [comment]
`File Size: 19 Bytes
Upload Duration: 1.707 Seconds
Upload Speed: 1.0615e-05 Mbps (approx)
Remaining free space on OneDrive: 1056521916024
Uploading new file Linux/Bug Bounty Hunting/Targets/zscaler.com/screenshots aquatone/html/https__wsf_wellington_isolation_zscaler_com__da39a3ee5e6b4b0d.html ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01                                                                                            
done.
File Size: 19 Bytes
Upload Duration: 1.75 Seconds
Upload Speed: 1.03542e-05 Mbps (approx)
Remaining free space on OneDrive: 1056521916005
Uploading new file Linux/Bug Bounty Hunting/Targets/zscaler.com/screenshots aquatone/html/https__pf_ocorian_isolation_zscaler_com__da39a3ee5e6b4b0d.html ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01                                                                                            
done.
File Size: 19 Bytes
Upload Duration: 1.689 Seconds
Upload Speed: 1.07281e-05 Mbps (approx)
Remaining free space on OneDrive: 1056521915986
Uploading new file Linux/Bug Bounty Hunting/Targets/zscaler.com/screenshots aquatone/html/http__wsp_americas-se_isolation_zscaler_com__da39a3ee5e6b4b0d.html ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01                                                                                            
done.
File Size: 19 Bytes
Upload Duration: 1.845 Seconds
Upload Speed: 9.82104e-06 Mbps (approx)
Remaining free space on OneDrive: 1056521915967
Uploading new file Linux/Bug Bounty Hunting/Targets/zscaler.com/screenshots aquatone/html/https__was_apj-se_isolation_zscaler_com__da39a3ee5e6b4b0d.html ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:02      `
This is some of the result, the upload speed is very slow, whereas I have other uploading/downloading tasks going on seamlessly on the same PC, there's nothing wrong with internet

**Comment by abraunegg** [comment]
@najum98 
This is *not a bug or issue*

Small file size uploading is slow. This is not a bug or issue, the application is functioning 100% normally.
