### ISSUE TITLE
How to tell onedrive to perform upload operation in background, when it put & at last of command , it returns to foreground just after a second

### ISSUE THREAD

**Issue by ssoftwares** [abraunegg/onedrive#1211]
**Is your feature request related to a problem? Please describe.**
How to tell onedrive to perform upload operation in background, when it put & at last of command , it returns to foreground just after a second.

**Describe the solution you'd like**
give an option to perform all operations in background silently

**Comment by abraunegg** [comment]
@ssoftwares 
> How to tell onedrive to perform upload operation in background, when it put & at last of command , it returns to foreground just after a second.

You cant. The nature of the application when running in a terminal does not lend itself to 'backgrounding'

> give an option to perform all operations in background silently

Please read the [usage](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md) document on running the application as a system service.
