### ISSUE TITLE
Backup or sync entire Microsoft 365 Tenant

### ISSUE THREAD

**Issue by ranyc2000** [abraunegg/onedrive#1214]
Synology has a NAS application called Active Backup for Microsoft 365, which provides a script to generate IDs and keys for accessing the entire Microsoft 365/O365 Tenant through its API, and then backs up the whole thing (or as much off it as you want) to the NAS. This includes all Exchange Mailboxes, Contacts, Calendars, etc. for the Tenant Team, all Sharepoint sites, libraries, etc. Of course you have to have something (such as one of their NAS boxes) that runs their NAS OS in 64-bit form. I have successfully used the software on this site as well, for OneDrive, OneDrive for Business and Sharepoint libraries. The Synology app seems to work much the same way as this one. Are there any plans to expand this app to handle the entire Tenant data set?

**Comment by abraunegg** [comment]
@ranyc2000 
> Are there any plans to expand this app to handle the entire Tenant data set?

No plans for this sort of functionality - sorry. PR's are welcome to add this to the clients capability.

**Comment by abraunegg** [comment]
Closing issue as question / feature request answered
