### ISSUE TITLE
[Question] Selective sync

### ISSUE THREAD

**Issue by TheHellSite** [abraunegg/onedrive#1215]
Is it possible to sync only certain folders from onedrive to my local device?
For example...

OneDrive_root
--Folder A
--Folder B
----Folder B1
----Folder B2 <--- Sync ONLY THIS folder to and from my local device
--Folder C
----Folder C1
----Folder C2
----Folder C3 <--- And maybe also that folder
and so on...

Is this possible without having to exlude all my other "thousands" of folders?
I thought about something like "sync_dir" but for the remote location. --> sync_remote_dir = "/OneDrive/Folder B/Folder B1"

Kind Regards
TheHellSite

EDIT: Closed.
Didn't see the part with the "sync_list" file.

**Comment by abraunegg** [comment]
@TheHellSite 
There are 2 ways to achieve this:

1. Use `--synchronize --single-directory` and specify your desired folder to sync - eg: `onedrive --synchronize --single-directory '/Folder B/Folder B2/'`. Refer to: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#performing-a-selective-directory-sync
2. Utilise the 'sync_list' file to specify the files / folders you wish to sync. Refer to: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#selective-sync-via-sync_list-file

**Comment by TheHellSite** [comment]
Oh that was a fast reply, solved it in the meantime. Thank you anyway, working great.

**Comment by TheHellSite** [comment]
I still have one question left.

By adding "/Folder B/Folder B2/" to the sync file it syncs the whole path and not just "Folder B2" to my local device.
"OneDrive/Folder B/Folder B2/" gets synced to "LOCAL_path_to_syncdir/Folder B/Folder B2/".

I would like to have it that way.
"OneDrive/Folder B/Folder B2/" gets synced to "LOCAL_path_to_syncdir/Folder B2/".

**Comment by abraunegg** [comment]
@TheHellSite 
> I still have one question left.
> ...
> I would like to have it that way.
> "OneDrive/Folder B/Folder B2/" gets synced to "LOCAL_path_to_syncdir/Folder B2/".

This is not possible due to how the OneDrive API works - ie - local folder re-direction to a specific point.

The client is a 'sync' client, replicating the OneDrive cloud state to your local folder.

**Comment by TheHellSite** [comment]
Okay thank you for pointing this out!
