### ISSUE TITLE
Compile to FreeNas

### ISSUE THREAD

**Issue by DanielBorgesOliveira** [abraunegg/onedrive#1218]
Hi friends,

I would like to know if there is someone that successfully compile to FreeNas. I would like to try it in FreeNas and any information about the compiling process will very appreciated.

Thank you very much.

**Comment by abraunegg** [comment]
@DanielBorgesOliveira 
email me offline as I have some other ideas as well

**Comment by DanielBorgesOliveira** [comment]
Send me your o email, please.

**Comment by abraunegg** [comment]
@DanielBorgesOliveira 
Use the support email address listed here

**Comment by abraunegg** [comment]
Closing issue as question answered & discussion via email offline
