### ISSUE TITLE
Compile error on OpenSuSE Leap 15.0 when using OpenSuSE "D" repository

### ISSUE THREAD

**Issue by dpramone** [abraunegg/onedrive#122]
make barfs up when using D rpm's from http://download.opensuse.org/repositories/devel:/languages:/D/openSUSE_Leap_15.0/ instead of installing the dmd rpm from http://downloads.dlang.org/releases/2.x/2.081.1/dmd-2.081.1-0.openSUSE.x86_64.rpm as advised in README.md .

dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lphobos2
collect2: error: ld returned 1 exit status

When using .rpm's, it makes sense to get them from OpenSuSE repositories as to avoid orphan rpm packages and/or miss critical updates. For a seamless onedrive installation on OpenSuSE Leap 15.0 - and to avoid above compilation error -, steps are as follows:

1. Add D Language repository:
- sudo zypper addrepo --check --refresh --name "D"  http://download.opensuse.org/repositories/devel:/languages:/D/openSUSE_Leap_15.0/ 
2. Install onedrive package dependencies:
sudo zypper install git libcurl-devel sqlite3-devel D:dmd D:libphobos2-0_81 D:phobos-devel D:phobos-devel-static
3. Clone, compile and install onedrive from Github
- As a normal user (not root): cd ~/(your preferred app/git directory)
- git clone https://github.com/abraunegg/onedrive.git
- cd onedrive
- make
- sudo make install

**Comment by abraunegg** [comment]
Can you create a pull request of your recommended changes to the readme.md file ?

**Comment by dpramone** [comment]
Hi @abraunegg. I could, but creating/maintaining a fork of my own to create a pull request for a one-off minor change to README.md seems a bit of overkill to me. I haven't tried installation on different versions of openSUSE, but AFAIK the standard repositories for Tumbleweed (the rolling release) already contain all required dependencies, including the "D"-ones. Which makes adding the "D" repository unnecessary. Everyone on 42.3 or lower should be upgrading to Leap 15 or Tumbleweed.

**Comment by abraunegg** [comment]
Updated readme after validating on local OpenSuSE Leap 15.0 install
