### ISSUE TITLE
No GUI for Headless?

### ISSUE THREAD

**Issue by thewismit** [abraunegg/onedrive#1220]
I'd like to install this without the gnome components, on a headless server. Is this possible? If this isn't the correct support process, can you please point me to it?

Thank you.

**Comment by abraunegg** [comment]
@thewismit 
This client does not have any GUI components (gnome or otherwise), so this is totally possible.

Follow whatever instructions are relevant for your OS as per https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md

**Comment by abraunegg** [comment]
Closing issue as question answered
