### ISSUE TITLE
How to install the package on Debian Buster?

### ISSUE THREAD

**Issue by pezlin** [abraunegg/onedrive#1222]
Can anyone give a short description on how to install Onedrive on Debian Buster?

**Comment by abraunegg** [comment]
@pezlin 
Please follow the Debian instructions in the Install Guide here: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md

**Comment by pezlin** [comment]
I tried to install the debian package but it couldn't be found. Probably because I am on Buster and the package is available in Sid and Bullseye so I was asked to see if anyone could guide me into getting it installed.

**Comment by abraunegg** [comment]
@pezlin 
Best option then is to install from source or backport the package manually for your older platform.

**Comment by pezlin** [comment]
I don't know if the official Debian version should be titled "old platform" but thank you for your reply. I will keep looking for a solution to my question.

**Comment by darrepac** [comment]
How to know who is the debian package maintainer so we could ask him to update it to support Buster?

**Comment by abraunegg** [comment]
@darrepac 
Refer to this discussion point: https://github.com/abraunegg/onedrive/discussions/1380

Additionally, you can review the packages here: https://packages.debian.org/search?keywords=onedrive which details the package maintainer.
