### ISSUE TITLE
Quote information restricted

### ISSUE THREAD

**Issue by joshdinsdale** [abraunegg/onedrive#1225]
### Bug Report Details ###
**Describe the bug**

Tried to run with --monitor and get the message:
```
WARNING: OneDrive quota information is being restricted or providing a zero value. Please fix by speaking to your OneDrive / Office 365 Administrator.
```
**Application and Operating System Details:**
*   Linux Mint 20 5.4.0-60-generic
*   GUI Cinnamon
*   OneDrive Business
*   Source
*   IDMD64 D Compiler v2.090.1

**Comment by abraunegg** [comment]
@joshdinsdale 
This is your problem:
>```
>WARNING: OneDrive quota information is being restricted or providing a zero value. Please fix by speaking to your OneDrive / Office 365 Administrator.
>```

Please read the warning as it advises how to fix this.
