### ISSUE TITLE
add config option to specify location of refreshTokenFilePath

### ISSUE THREAD

**Issue by cyberatz** [abraunegg/onedrive#1228]
Currently the refreshTokenFilePath is generated based on a the configDirName & "/refresh_token" (line 208 in config.d).

While this is fine if there is only a single docker container running, doing the whole AUTU URL routine on a container by container basis for multiple containers becomes suboptimal.  

Each container has to have it's own /onedrive/conf directory which contains the refresh_token. As the refresh_token file is contained in a mounded conf directory, it's hard to share across containers. 

It would be great to be able to specify the location of the refresh_token to allow for the file sharing across multiple containers. 

An alternative option would be to allow for the configuration of multiple drive_ids in the configuration file with he ability to sync them all in the same process. I suspect that this would require more complex code refactoring.

**Comment by abraunegg** [comment]
@cyberatz 

> Currently the refreshTokenFilePath is generated based on a the configDirName & "/refresh_token" (line 208 in config.d).
> 
> While this is fine if there is only a single docker container running, doing the whole AUTU URL routine on a container by container basis for multiple containers becomes suboptimal.
> 
> Each container has to have it's own /onedrive/conf directory which contains the refresh_token. As the refresh_token file is contained in a mounded conf directory, it's hard to share across containers.
> 
> It would be great to be able to specify the location of the refresh_token to allow for the file sharing across multiple containers.

This would create a security issue by having the the configuration directory shared with many Docker containers. The conf directory contains many more items than just the authentication information.

> An alternative option would be to allow for the configuration of multiple drive_ids in the configuration file with he ability to sync them all in the same process. I suspect that this would require more complex code refactoring.

Correct, and will not be done. The code rebuild for multi-threading will not take this into account either. It will still be 1 account (personal, business, sharepoint site) to client configuration.

**Comment by abraunegg** [comment]
Closing issue as question answered
