### ISSUE TITLE
Ability to sync linked folders

### ISSUE THREAD

**Issue by cyberatz** [abraunegg/onedrive#1229]
OneDrive allows for links to be added to alternate sharepoint locations. This is great from a user perspective as it allows easy navigation from the OneDrive folder to SharePoint locations. 

The linked folders use a different Finder/Explorer icon in the Mac/Windows OneDrive clients as indicated here:
![image](https://user-images.githubusercontent.com/2226414/104913939-a4cc1b80-598e-11eb-85b2-d4c29efb6bd7.png)

Currently these links are not synced in the Linux client. It would be great if these links could be synced as folders within the OneDrive data folder.

**Comment by abraunegg** [comment]
@cyberatz 
Due to how the API operates, supporting these links is not possible. This is the same request as https://github.com/abraunegg/onedrive/issues/1224

SharePoint sites are supported via this process only: https://github.com/abraunegg/onedrive/blob/master/docs/Office365.md

**Comment by abraunegg** [comment]
Closing issue as question answered
