### ISSUE TITLE
Add a config option skip_dir

### ISSUE THREAD

**Issue by fgauvrit** [abraunegg/onedrive#123]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to exclude directories only.
For example, I would like to exclude "/cache" but not "cache.jpg".

Thanks.

**Comment by abraunegg** [comment]
@fgauvrit 
Please can you help test the following PR which implements this feature:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/388/head:pr388
git checkout pr388
make
```

If you are able to test this PR, and report back that would be greatly appreciated.

Please use this against a **TEST** OneDrive account - as I would currently call this feature **BETA** quality as I have only tested it. 

The feature currently does what it "should" do in my test cases, however this needs some extensive testing & confirmation that there is no undesirable bug which could cause data to be lost.

**Comment by abraunegg** [comment]
Testing with your specific example:
```
Loading config ...
Using Config Dir: <redacted>
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: <redacted>
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 5368709115
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Skipping item - excluded by skip_dir config: ./cache
Uploading file ./cache.jpg ... done.
Remaining free space: 5368709106
Applying changes of Path ID: <redacted>
```

**Comment by abraunegg** [comment]
@fgauvrit 
Have you been able to test this PR?

**Comment by abraunegg** [comment]
Closing issue as PR #388 merged
