### ISSUE TITLE
choosing available folders with Sharepoint

### ISSUE THREAD

**Issue by ukuvainik** [abraunegg/onedrive#1231]
Hi!

Thank you for the wonderful sync program. Looks like a really good fit to my use, if I only could access the folders I want.

### Bug Report Details ###
**Describe the bug**
When connecting to my workplace Sharepoint, the library has two available folders - Documents and Teams Wiki Data. The onedrive app connects to Teams Wiki Data and acts like this is the sole folder. I cannot see the Documents folder, which I would like to connect to.

As a comparison, Insync does not connect to Sharepoint at all. Expandrive lists both folders of the library as separate drives.

**Application and Operating System Details:**
*  Ubuntu 18.04  Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
**Linux sophl50 5.4.0-60-generic #67~18.04.1-Ubuntu SMP Tue Jan 5 22:01:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux**
**Headless system (no gui)**
*   OneDrive Account Type: **OneDrive SharePoint Shared Library**
*   Did you build from source or install from a package? **Source, installed compiler and onedrive today.** 
*   OneDrive Application Version: Output of `onedrive --version`
**onedrive v2.4.9-6-g1c6dd42**
*   OneDrive Application Configuration: Output of `onedrive --display-config`
 **sync_dir is local NTFS drive.** 
*   Provide the version of curl you are using: Output of `curl --version`
**curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp** 

*   Is your configured 'sync_dir' a local directory or a network mount point? **Local**
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time   **Not shared. Unless you mean that I connect to Sharepoint**

**Comment by abraunegg** [comment]
@ukuvainik 
To sync Sharepoint folders, you need to follow these directions: https://github.com/abraunegg/onedrive/blob/master/docs/Office365.md

For each Sharepoint Library you wish to sync, you need to create a new application configuration.

**Comment by ukuvainik** [comment]
Hi! 

Thanks for the quick reply. Yes, I have followed these instructions. I am attaching screenshots to illustrate what I experience:

Here you can see that the library "PT2021" has two folders - "Dokumendid" and "Teams Wiki Data"

![image](https://user-images.githubusercontent.com/6614391/105088120-2497da00-5aa4-11eb-8a1d-6a249b6611e4.png)

I have synced "PT2021" to my local drive. I have created the folder "eetika" which I uploaded to the "General" folder. Both "Dokumendid" and "Teams Wiki Data" have a "General" folder, as General is the name of my channel. 

![image](https://user-images.githubusercontent.com/6614391/105088474-9a03aa80-5aa4-11eb-9ca4-9850919147a4.png)

When I search for the folder "eetika", it is part of the Teams Wiki Data folder. This makes little sense for me. It would be better to have it under "Dokumendid [Documents]" folder. However, I cannot see the "Dokumendid" folder when syncing with onedrive.

![image](https://user-images.githubusercontent.com/6614391/105088290-59a42c80-5aa4-11eb-981b-62c7e955e703.png)

I can see both folders, when using the demo version of ExpanDrive. Expandrive lists two directories under PT2021. Note, that here I have renamed "PT2021" to "psygv". 

![image](https://user-images.githubusercontent.com/6614391/105089351-adfbdc00-5aa5-11eb-8b01-89df220350dd.png)

Any ideas, how to proceed?

Thanks
Uku

**Comment by abraunegg** [comment]
@ukuvainik 
> I have synced "PT2021" to my local drive. I have created the folder "eetika" which I uploaded to the "General" folder. Both "Dokumendid" and "Teams Wiki Data" have a "General" folder, as General is the name of my channel.

By default, your 'sync_dir' in your config file points to `~/OneDrive`. You can change this to point 'anywhere' within reason.

In your configuration:
* PT2021 is a 'logical' name on SharePoint. It is the 'site name'.
  * If you want to sync data from this SharePoint Library to this folder name locally, then:
    * Create a new local path called: `~/OneDrive_Sharepoint_PT2021/` and configure your 'sync_dir' to point to this location

> However, I cannot see the "Dokumendid" folder when syncing with onedrive.

All data from 'PT2021' that you have permission to access will be synced to this sync location, including the remote folder structure. If this is not happening, you need to:
* Double check your configuration
* Fix your configuration
* Test your configuration with `--dry-run`
* Perform a `--resync`
* Provide a verbose debug log, when doing the `--resync` by adding `--verbose --verbose` and providing the debug log output for analysis.

> I can see both folders, when using the demo version of ExpanDrive. Expandrive lists two directories under PT2021. Note, that here I have renamed "PT2021" to "psygv".

Do not confuse how this client operates with that of other clients please. It is irrelevant.

**Comment by ukuvainik** [comment]
Thanks for your reply! 

After taking a small break, I figured this out Apparently, the folder structure in my first picture reflects two separate drives within the PT2021. The Expandrive mounting two drives should have hinted me that!

When I ran the  "--get-0365-drive-id" command again, I get two drive_id-s. I previously did not notice that there were  two of them and automatically chose the last one. Now I chose the first one and I am within the folders I want.

![image](https://user-images.githubusercontent.com/6614391/105339348-3d5bd900-5be5-11eb-9d06-ecc15736bc2b.png)

Perhaps it may be useful to add to the SharePoint page under point 4: 
**Note:** depending on your SharePoint setup you may get several drive_id variables. Choose the one having the files you want access to.
