### ISSUE TITLE
Can't download from Business Shared Folder when using --download-only & --single-directory

### ISSUE THREAD

**Issue by eloii23** [abraunegg/onedrive#1234]
Hello,
I think I found a Bug. I've been testing to "--upload-only" to a Business Shared Folder and it works fine, but when I try "--download-only", the files are not downloaded :(

**Application and Operating System Details:**
* CentOS 8 - Linux SCLD01UJIFE02 4.18.0-193.19.1.el8_2.x86_64 #1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64 x86_64 x86_64 GNU/LinuxGNU/Linux
* NO GUI
* Business
* From source
* Dmd-2.095.0
* onedrive v2.4.9-4-gbbba32c
* 
![image](https://user-images.githubusercontent.com/61405335/105146697-900f9500-5b00-11eb-9e18-c6847b8e2d41.png)
* curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.6 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.2.0) libssh/0.9.4/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink
* Local directory
* XFS
* We have a business OneDrive account with some Shared Folders (SharePoint). In one of this Shared Folders there are some files that I need to download, but only on one folder (/General/ExcelsHistorificacion)

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to OneDrive -> Shared Library -> folder General/ExcelsHistorificacion
2.  Create a Excel file
3.  Execute onedrive --synchronize --sync-shared-folders --download-only --single-directory 'General/ExcelsHistorificacion'
4.  Nothing happens

**Complete Verbose Log Output**
![image](https://user-images.githubusercontent.com/61405335/105147450-7cb0f980-5b01-11eb-9cd8-9b6de220ecc2.png)

Best regards,
Eloi.

**Comment by abraunegg** [comment]
@eloii23 
Please can you also test the following PR to resolve your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1235/head:pr1235
git checkout pr1235
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.9-10-g0bbf162` or greater.

**Comment by eloii23** [comment]
Hi @abraunegg ,
I've tried running the PR but still can't download. Let me show you some screenshots:
Testing Upload:
![image](https://user-images.githubusercontent.com/61405335/105320068-05916900-5bc6-11eb-9661-13bdd55626ad.png)

Testing download:
![image](https://user-images.githubusercontent.com/61405335/105320128-180ba280-5bc6-11eb-9c71-936fba67e54f.png)

Local folder:
![image](https://user-images.githubusercontent.com/61405335/105320173-25289180-5bc6-11eb-8431-d1f666618637.png)

OneDrive folder:
![image](https://user-images.githubusercontent.com/61405335/105320213-32458080-5bc6-11eb-8d73-f90cbb04b57e.png)

Hope this helps.
Best regards!

**Comment by abraunegg** [comment]
@eloii23 
In-between the 'upload' & 'download' - are you modifying the file on OneDrive?

You cant download a file that is already in-sync locally.

**Comment by eloii23** [comment]
Yes, I modified the files to discard that it was cached. In any case, the XLSX files are on OneDrive but not locally so it would be downloaded if I do a --resync but I can't download it in any way :(

![image](https://user-images.githubusercontent.com/61405335/105325161-94a17f80-5bcc-11eb-8898-c55354621db2.png)

Can you show me your --display-config? I acn't understand why are you able to download and I'm not, using the same command..

Best regards!

**Comment by eloii23** [comment]
In addition,
I see that it is uploading, although I'm doing --download-only:

![image](https://user-images.githubusercontent.com/61405335/105326129-b3544600-5bcd-11eb-92ed-810d493a9891.png)

May be I'm running the PR wrong way?

Hope this helps :)
Regards!

**Comment by abraunegg** [comment]
@eloii23 
The PR does work - I have confirmed that. The evidence above also illustrates this.

Why it is uploading ... no idea .. are you 100% sure you are running the PR version, without any other background service enabled as well?

--download-only does not and cannot envoke upload mode either .... so ... what / how are you running / compiling / modifying your files?

Screen shots here are not good references. Please provide a verbose debug log showing:

- you uploaded a file that you modified
- you modified that file then online
- you downloaded the file

In the meantime, I will spin up my CentOS 8 system to align to your OS version, and compile the PR and retest there to be 100% sure - but right now, I strongly suspect the error is with your process.

**Comment by abraunegg** [comment]
@eloii23 
Below is a test using CentOS 8:

**Environment:**

Installed dmd-2.095.0 via `curl -fsS https://dlang.org/install.sh | bash -s dmd`
```
[root@centos-8-x86-64 onedrive-pr1235]# uname -a
Linux centos-8-x86-64 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@centos-8-x86-64 onedrive-pr1235]# cat /etc/redhat-release 
CentOS Linux release 8.3.2011
[root@centos-8-x86-64 onedrive-pr1235]# ./onedrive --display-config
Configuration file successfully loaded
onedrive version                       = v2.4.9-10-g0bbf162
Config path                            = /root/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /root/OneDrive
Config option 'skip_dir'               = 50k_random_files     <- forcing to skip this as I do not want to download my 50k test dataset to a new system
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = true
business_shared_folders contents:
# Top level Folder
Top Folder
# Sub Shared Folder
# Sub Folder 2
```

**Application Run:**
```
[root@centos-8-x86-64 onedrive-pr1235]# ./onedrive --synchronize --sync-shared-folders --download-only --verbose --single-directory 'Top Folder/asdfasdf/' 
Using 'user' Config Dir: /root/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /root/OneDrive
Application version: v2.4.9-10-g0bbf162
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1097723469146
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from this selected path: Top Folder/asdfasdf/
Syncing changes from selected OneDrive path ...
Attempting to sync OneDrive Business Shared Folders
Getting path details from OneDrive ...
Applying changes of Path ID: 01TZRSBFFDOHNDGGFYAJAI5XHEGC2KCLDY
OneDrive quota information is set at zero, as this is not our drive id, ignoring
Adding OneDrive root details for processing
Adding OneDrive folder details for processing
Adding 1 OneDrive items for processing from OneDrive folder
Number of items from OneDrive to process: 3
Downloading file asdfasdf/qwerksdjfg.txt ... done.
[root@centos-8-x86-64 onedrive-pr1235]#
```

**Create new XLSX file on OneDrive Shared Folder & Download:**

![Capture](https://user-images.githubusercontent.com/4956234/105334591-2b9d2480-5c2b-11eb-918c-f4cf1e6e4794.JPG)

```
[root@centos-8-x86-64 onedrive-pr1235]# ./onedrive --synchronize --sync-shared-folders --download-only --verbose --single-directory 'Top Folder/asdfasdf/' 
Using 'user' Config Dir: /root/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /root/OneDrive
Application version: v2.4.9-10-g0bbf162
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1097723469146
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from this selected path: Top Folder/asdfasdf/
Syncing changes from selected OneDrive path ...
Attempting to sync OneDrive Business Shared Folders
Getting path details from OneDrive ...
Applying changes of Path ID: 01TZRSBFFDOHNDGGFYAJAI5XHEGC2KCLDY
OneDrive quota information is set at zero, as this is not our drive id, ignoring
Adding OneDrive root details for processing
Adding OneDrive folder details for processing
Adding 2 OneDrive items for processing from OneDrive folder
Number of items from OneDrive to process: 4
Downloading file asdfasdf/Book.xlsx ... done.
[root@centos-8-x86-64 onedrive-pr1235]# 
```

This to me illustrates that the PR is working as intended, on CentOS 8, using dmd-2.095.0 as the compiler. 

I strongly suspect that the issue you are seeing is 100% environmental to your system / platform / process at this stage.

**Comment by abraunegg** [comment]
@eloii23 
I am going to mark this bug as fixed, as without the required code change, the error you originally uncovered is a bug, and the code change 100% fixes this issue.

**Comment by eloii23** [comment]
Hi @abraunegg ,
thanks for your demonstration! I will try to remove onedrive and reinstall again.

Regards!

**Comment by eloii23** [comment]
Hi @abraunegg ,
finally I get it! :) best rgards! I close the issue, let me know when the fix were merged to master to use onedrive as normal.

Thanks!
