### ISSUE TITLE
What should ONEDRIVE_UID and ONEDRIVE_GID be?

### ISSUE THREAD

**Issue by nateGeorge** [abraunegg/onedrive#1236]
In the docker instructions it says "the user id and group id should be added to remove any potential user conflicts, denoted by the environment variables ${ONEDRIVE_UID} and ${ONEDRIVE_GID}." 

Should these IDs be our user ID, or some new IDs for a onedrive user and group we create?

**Comment by abraunegg** [comment]
@nateGeorge 
> Should these IDs be our user ID, or some new IDs for a onedrive user and group we create?

These can be either depending on your security policy for your environment.

**Comment by abraunegg** [comment]
Closing issue as question answered
