### ISSUE TITLE
Possibility to sync with cifs mount

### ISSUE THREAD

**Issue by mvzut** [abraunegg/onedrive#1239]
**Is your feature request related to a problem? Please describe.**
I want to use the Linux onedrive client to synchronize between OneDrive and a hard drive that is shared in my network. The drive is a USB drive connected to my ASUS router, shared to the network using Samba/cifs. I have mounted it on my Raspberry Pi as /home/pi/OneDrive. However, when I start a sync it give error messages ("operation not permitted"). Syncing to a "regular" folder on my Pi works fine. 

**Describe the solution you'd like**
I would really appreciate it when the Linux onedrive client could also sync to a mounted cifs share. This would enable me to sync my network drive (shared via my router) to OneDrive without the need for a PC. 

**Describe alternatives you've considered**
At the moment, I use a Windows PC to accomplish the above. But I already have a Raspberry Pi which runs other light services, and this could easily do the synchronization next to its other tasks (e.g. at night). In this way, I do not the the PC to run 24/7 anymore. 

**Additional context**
N.A.

**Comment by abraunegg** [comment]
@mvzut 
> However, when I start a sync it give error messages ("operation not permitted"). Syncing to a "regular" folder on my Pi works fine.

This is a Linux user|group permissions issue. The user you are running the client as, does not have permission to read / write the files on the network share.

Use `getfacl` to determine what the effective user|group permissions are and fix your security issue.

**Comment by abraunegg** [comment]
Closing issue as not a bug or issue with the client, but is an issue with users local environment that needs to be resolved.
