### ISSUE TITLE
First scan goes through symlinks

### ISSUE THREAD

**Issue by fgauvrit** [abraunegg/onedrive#124]
### Bug Report Details ###
**Describe the bug**
First scan goes through symlinks

**Application and Operating System Details:**
- OS: Linux FGA-E6540.HOME 4.4.140-62-default #1 SMP Tue Jul 17 12:14:34 UTC 2018 (951943d) x86_64 x86_64 x86_64 GNU/Linux (Leap 42.3)
- Application version: onedrive v2.1.1
- DMD or LDC compiler version: DMD64 D Compiler v2.081.0

**To Reproduce**
Create a symlink in the sync_dir, pointing to a big directory.
Erase all local db files.
Launch onedrive --monitor --local-first --upload-only --skip-symlinks --verbose

We can see the first scan going through the symlink, which takes some time for no reason.

As a workaround, I have excluded some known symlinks with their name, which is not very practical.

The fact to add skip_symlinks = "true" in the config file does not change anything in that behavior.

Thanks.

**Comment by fgauvrit** [comment]
It is even worse if you create a symlink of himself inside a directory... The first scan goes through a loop and it never starts the sync...

**Comment by abraunegg** [comment]
Can you provide verbose log output validating the issue & a local directory listing?

**Comment by abraunegg** [comment]
Can you help validate PR #125 to resolve your issue:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/125/head:pr125
git checkout pr125
make
make install
```
Local validation
```
[root@localhost OneDrive]# ls -la
total 0
drwxr-xr-x. 3 root root  56 Aug 17 06:35 .
dr-xr-x---. 8 root root 217 Aug 17 05:52 ..
lrwxrwxrwx. 1 root root  12 Aug 17 05:56 link -> ./test/1.txt
lrwxrwxrwx. 1 root root   7 Aug 17 05:57 link2 -> ./test/
lrwxrwxrwx. 1 root root  15 Aug 17 06:35 link3 -> /root/OneDrive/
drwxr-xr-x. 2 root root  19 Aug 17 05:55 test
[root@localhost OneDrive]# 
```
```
[root@localhost OneDrive]# onedrive --monitor --local-first --upload-only --skip-symlinks --verbose
Loading config ...
Using Config Dir: /root/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 112742891511
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing monitor ...
OneDrive monitor interval (seconds): 45
Monitor directory: .
Monitor directory: ./test
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Processing root
The directory has not changed
Processing test
The directory has not changed
Processing 1.txt
The file has not changed
Uploading new items of .
Skipping item - skip symbolic links configured: ./link
Skipping item - skip symbolic links configured: ./link2
Skipping item - skip symbolic links configured: ./link3
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Processing root
The directory has not changed
Processing test
The directory has not changed
Processing 1.txt
The file has not changed
Uploading new items of .
Skipping item - skip symbolic links configured: ./link
Skipping item - skip symbolic links configured: ./link2
Skipping item - skip symbolic links configured: ./link3
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Processing root
The directory has not changed
Processing test
The directory has not changed
Processing 1.txt
The file has not changed
Uploading new items of .
```

**Comment by fgauvrit** [comment]
Hi,

It works perfectly now ! Thanks for that quick fix. :-)

A little question : How can I get the current version of your onedrive client from the url ? I would like to write a script which keeps the program up to date automatically by checking on the web and reinstalling if needed.

Thanks.

**Comment by abraunegg** [comment]
Closing issue due to merge of PR #125

**Comment by abraunegg** [comment]
> How can I get the current version of your onedrive client from the url ? 

Unsure on that .. you may need to use the git command or something against the git url or something along those lines.
