### ISSUE TITLE
onedrive doesn't continue syncing when internet connection changes - Error message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?

### ISSUE THREAD

**Issue by ctonic** [abraunegg/onedrive#1245]
See this  image:
![image](https://user-images.githubusercontent.com/42185809/106341753-a9ea6e00-629e-11eb-9229-6c0dda653c80.png)

At about 01:45 I unplugged my Notebook from LAN and (maybe 2 minutes later) connected it to WLAN.
When the program loses its internet connection, I get the error `Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?`.
This error message just keeps on coming, independently of whether internet connection is available.

The only solution for me is to restart the onedrive service.

Could this possibly be because I run the program in user mode?

**Comment by abraunegg** [comment]
Closing issue, support template not used

Please follow the correct support process
