### ISSUE TITLE
Bug: configuration: log_dir option treats '~' literally

### ISSUE THREAD

**Issue by mmhmm** [abraunegg/onedrive#1255]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###

The `log_dir` configuration option appears to treat `"~"` at the start of its value literally.

(The `sync_dir` option has a default value of `"~/OneDrive"` and this is documented in the sample config file which could lead a user - me! - to expect `log_dir` to also respect a value beginning with `"~"`)

**Application and Operating System Details:**
* OS: Ubuntu 20.04.02
* uname -a: `Linux user-SATELLITE-R830 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* OneDrive Account Type: personal
*   Installed from PPA package
*   OneDrive Application Version: `onedrive v2.4.9-0~202012270043~ubuntu20.04.1`
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
Config path                            = /home/mmh/.config/onedrive
Config file found in config path       = true
Config option 'sync_dir'               = /home/mmh/OneDrive
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'log_dir'                = ~/.config/onedrive/log/
```

Both options in the config file begin with `"~/..."`, note that this has been expanded for `sync_dir` but not `log_dir`

**To Reproduce**

1.  Create a config file with `log_dir = "~/path/to/log/dir/`
2.  Run onedrive with the `--enable-logging` flag
3.  The `log_dir` value will be created as a directory path with beginning with a literal `~` in the current working directory.

(I'm happy I have backups, I didn't think very well and removed the directory created by onedrive with `rm -rf ~` with the `~` unquoted and deleted my home directory! :) )

**Comment by abraunegg** [comment]
@mmhmm  
Please can you test the following PR to resolve your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1258/head:pr1258
git checkout pr1258
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.9-14-gdc5938f` or greater.

**Example:**
Create a config file with `log_dir = "~/path/to/log/dir/"`

```
./onedrive --confdir '~/.config/onedrive-business/' --display-config
Configuration file successfully loaded
config file has been updated, checking if --resync needed
onedrive version                       = v2.4.9-14-gdc5938f
Config path                            = /home/alex/.config/onedrive-business/
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/alex/OneDriveBusiness
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /home/alex/path/to/log/dir
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
```

The `~/path/to/log/dir/` is correctly expanded and used.

If you can test and provide feedback that would be greatly appreciated.

**Comment by mmhmm** [comment]
@abraunegg wow, thank you so much for looking into it so quickly!

I've tested the PR branch, and the `~` is now expanded. Unfortunately there seems to be another issue now though - the logfile is created named `loguser.onedrive.log` rather than `$USER.onedrive.log`, and a directory level up.
```
-rw-rw-r-- 1 user user 3177 Feb  5 22:12 /home/user/.config/onedrive/loguser.onedrive.log`
```
My config file has:

```
log_dir = "~/.config/onedrive/log/"
```
and running `~/git/onedrive/onedrive --display-config` gives:

```
onedrive version                       = v2.4.9-14-gdc5938f
Config option 'log_dir'                = /home/user/.config/onedrive/log
```

In case it's relevant, in my previous onedrive version, the trailing slash here was preserved:

```
onedrive version                       = v2.4.9-0~202012270043~ubuntu20.04.1
Config option 'log_dir'                = ~/.config/onedrive/log/
```

Sorry I've not been able to do much more than take a cursory look at the code and haven't tried to submit a PR myself, unfortunately Dlang is new to me.

**Comment by abraunegg** [comment]
@mmhmm 
> I've tested the PR branch, and the `~` is now expanded. Unfortunately there seems to be another issue now though - the logfile is created named `loguser.onedrive.log` rather than `$USER.onedrive.log`, and a directory level up.

Please can you rebuild the PR and test `onedrive v2.4.9-15-gbba4181` to resolve this additional issue

**Comment by mmhmm** [comment]
@abraunegg Tested with `onedrive v2.4.9-15-gbba4181`, the log file is created where and named as expected now with a `log_dir` value of `"~/.config/onedrive/log/"`:

```
-rw-rw-r-- 1 user user 202 Feb  5 22:58 /home/user/.config/onedrive/log/user.onedrive.log
```

(Specifying the `log_dir` value without a trailing slash results in a file named `loguser.onedrive.log` in the parent directory. I believe this was the existing behaviour, and it is documented with a trailing slash in the sample config file, though)

**Comment by abraunegg** [comment]
@mmhmm 
> (Specifying the `log_dir` value without a trailing slash results in a file named `loguser.onedrive.log` in the parent directory. I believe this was the existing behaviour, and it is documented with a trailing slash in the sample config file, though)

Correct, it is documented that this parameter needs the trailing slash.

Will mark this as fixed and merge into master shortly.
