### ISSUE TITLE
Feature request/suggestion: Utilize fuse and rclone for windows ondemand sync and/or encryption

### ISSUE THREAD

**Issue by Rihcus** [abraunegg/onedrive#1261]
Regarding encryption and onedrive on demand rclone can do both via a fuse mount. Currently I have have rclone cach drive mounted via fuse which acts similarley to windows on demand sync. In rclone config:

Onedrive remote --> rclone cach  --> fuse mount to local folder

For encrytption:
Onedrive remote --> encrypted drive --> rclone cach --> fuse mount local folder.

The pros to this aproach:
-- streams and caches files very quickly
-- upload cach can be stored in event of network outage (upload will happen upon reconnection)
-- fuse mounts to file system seamlessly

The negatives to this aproach:
-- Doesn't support onedrive revision control (if you save a file the old file is moved to onedrive trash and new file saved)
-- File corruption/damge can occur should fuse fail (happens if improper mount or force reboot, mostly can be recoverd from trash but if using encryption this can be a severe problem).

source:
https://rclone.org/cache/

**Comment by abraunegg** [comment]
@Rihcus 
Please see:

**Encryption:** https://github.com/abraunegg/onedrive/issues/1023
**On-Demand:** https://github.com/abraunegg/onedrive/issues/757
