### ISSUE TITLE
Logging indicates file uploads occuring when they're not

### ISSUE THREAD

**Issue by sweharris** [abraunegg/onedrive#1266]
My local machine is CentOS 7.9, and I'm using onedrive v2.4.9-10-g3b87602

Very frequently I can take a picture on my phone, which uploads to onedrive, and then I see it download and upload.

e.g.

    Feb 07 12:24:42 mercury7.spuddy.org onedrive[1268]: Downloading file Pictures/Camera Roll/IMG_20210207_122356.jpg ... done.
    Feb 07 12:24:49 mercury7.spuddy.org onedrive[1268]: Uploading differences of Pictures/Camera Roll/IMG_20210207_122356.jpg
    Feb 07 12:24:49 mercury7.spuddy.org onedrive[1268]: Uploading new items of Pictures/Camera Roll/IMG_20210207_122356.jpg

This also happens with files I edit with O365

    Feb 09 19:31:54 mercury7.spuddy.org onedrive[9091]: Downloading file tmp/tst.xlsx ... done.
    Feb 09 19:32:01 mercury7.spuddy.org onedrive[9091]: Uploading differences of tmp/tst.xlsx
    Feb 09 19:32:01 mercury7.spuddy.org onedrive[9091]: Uploading new items of tmp/tst.xlsx

After discussion this appears to be a false-logging issue; no upload is happening, but the logs don't represent actual activity.

**Comment by abraunegg** [comment]
@sweharris 
Please can you test #1267 to resolve this issue.

I have tested locally without issue both `--monitor` and `--synchronize` and no issue now with correctly handling the `~/OneDrive` location .. that was a real bug where the expansion was never being updated to the configuration file so it can be correctly reused.

**Comment by sweharris** [comment]
Looks good

```
% onedrive --synchronize
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Downloading file tst2 ... done.
Uploading differences of /home/sweh/OneDrive
Uploading new items of /home/sweh/OneDrive

% onedrive --monitor    
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 300
```

**Comment by abraunegg** [comment]
@sweharris 
Just made a small tweak - please ensure you are testing `onedrive v2.4.9-19-g8c9800d`

**Comment by sweharris** [comment]
```
$ ./onedrive --version
onedrive v2.4.9-19-g8c9800d

$ ./onedrive --synchronise
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Downloading file tst1 ... done.
Trying to delete item tst2
Deleting item tst2
Uploading differences of /home/sweh/OneDrive
Uploading new items of /home/sweh/OneDrive

$ onedrive --monitor
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 300

**Comment by abraunegg** [comment]
@sweharris 
Marking as fixed, but will hold off on merging to 'master' for the moment - give you 24hrs to allow for some full regression testing.

**Comment by sweharris** [comment]
FWIW, I've these test cases:
Onedrive file created:  New file downloaded locally
Onedrive file modified: file downloaded
Onedrive file deleted: deleted locally
Local file created: uploaded
Local file modified: uploaded
Local file deleted: remote deleted

All tests done with the --synchronize flag
