### ISSUE TITLE
Ubuntu PPA | OpenSuSE Build Service: onedrive --monitor runs automatically on startup after install

### ISSUE THREAD

**Issue by salaivv** [abraunegg/onedrive#1274]
### Bug Report Details ###
The onedrive client runs automatically on startup in `--monitor` mode and writes around a gigabyte of data (~1.3 GB). This happens at every startup. I didn't configure any systemd service for the client; this happens out of the box.

**Application and Operating System Details:**
*   PopOS 20.10 | uname output `Linux pop-os 5.8.0-7642-generic #47~1612288990~20.10~b8113e7-Ubuntu SMP Wed Feb 3 02:27:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
*   Running with a GUI
*   OneDrive Account Type -- Personal
*   Installed from the Ubuntu PPA mentioned in the INSTALL.md document.
*   DMD -- 2.095.0
*   OneDrive Application Version: 2.4.9-22-g42b7945
* Config file:
```
Configuration file successfully loaded
onedrive version                       = v2.4.9-22-g42b7945
Config path                            = /home/salaivv/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /media/salaivv/Treazure/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = fals
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   curl version -- 7.68.0
*   'sync_dir' is on a local NTFS volume to share data between Linux and Windows (dual boot).
*   My OneDrive account is only used on my PC and mobile. Accessed from both Linux and Windows as mentioned above, but have stopped syncing from Windows. I only sync from Linux using this client.

**To Reproduce**
Steps to reproduce:
1.  Install onedrive from Ubuntu PPA mentioned in the INSTALL.md document.
2.  Authenticate and configure onedrive.
3.  Restart the PC and login.
4.  OneDrive should start automatically in --monitor mode even without any manual configuration of systemd services.

**Comment by abraunegg** [comment]
@yann1cks
This issue *keeps* coming up and on the askubuntu forums as well.

Please can you fix the Ubuntu PPA package

**Comment by nabriis** [comment]
Just a comment here. You can check if onedrive is running automatically from this ppa by checking the logs with
`journalctl --user-unit=onedrive -f`

**Comment by abraunegg** [comment]
When the PPA installs the application, it creates a symbolic link as follows:
```
Created symlink /etc/systemd/user/default.target.wants/onedrive.service → /usr/lib/systemd/user/onedrive.service.
```

To resolve this, so that the client is *not* automatically started, without 'enabling' the client yourself, you need to remove this symbolic link:
```
sudo rm /etc/systemd/user/default.target.wants/onedrive.service
```

**Comment by abraunegg** [comment]
Closing this issue as this is a packaging issue due to Debian & Ubuntu processes, unrelated to 'onedrive'.
