### ISSUE TITLE
Manjaro aarch64-linux-gnu support for Raspberry Pi 

### ISSUE THREAD

**Issue by ScaroDj** [abraunegg/onedrive#1278]
I was trying to install it in Manjaro 64-bit on my Raspberry Pi 4 (4GB) but their repository does not have it (request for the dist admin)  so I tried to compile it using the instructions at docs/INSTALL.md but DMD is not available in the repository either, using LDC I get a version error from the ./config script. 

``` 
onedrive]$ uname -a
Linux scar4spi 5.4.83-1-MANJARO-ARM #1 SMP PREEMPT Mon Dec 14 08:37:33 CST 2020 aarch64 GNU/Linux
[snip]
 onedrive]$ sudo pacman -S onedrive
error: target not found: onedrive
[snip]
warning: curl-7.74.0-1 is up to date -- reinstalling
warning: sqlite-3.34.0-1 is up to date -- reinstalling
warning: libnotify-0.7.9-1 is up to date -- reinstalling
error: target not found: dmd
[snip]
warning: ldc-2:1.24.0-3 is up to date -- reinstalling
[snip]
 onedrive]$ ldc --version
LDC - the LLVM D compiler (1.24.0):
  based on DMD v2.094.1 and LLVM 11.0.1
  built with LDC - the LLVM D compiler (1.24.0)
  Default target: aarch64-unknown-linux-gnu
[snip]
 onedrive]$ ./configure DC=~/ldc2-1.16.0-linux-aarch64/bin/ldmd2
checking for a BSD-compatible install... /bin/install -c
checking for pkg-config... no
checking for dmd... /home/scarodj/ldc2-1.16.0-linux-aarch64/bin/ldmd2
checking version of D compiler... ./configure: line 2130: /home/scarodj/ldc2-1.16.0-linux-aarch64/bin/ldmd2: No such file or directory

configure: error: Compiler version insufficient, current compiler version , minimum version 1.12.0
``` 

Thanks in advance for your time and consideration.

**Comment by abraunegg** [comment]
@ScaroDj 
Please follow the correct process to install the client.

It appears that you have:
* Installed packages / dependencies that cause issues `warning: ldc-2:1.24.0-3 is up to date -- reinstalling`
* Not downloaded or installed the correct LDC compiler
* Not activated the LDC compiler post install

Please can you:
* Uninstall all your packages that you have installed
* Follow the directions for Manjaro + ARMHF or ARM64 compilation as directed

For any further issue, please follow the correct support process as detailed here: https://github.com/abraunegg/onedrive#reporting-issues
