### ISSUE TITLE
Onedrive command not found on macOS

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [abraunegg/onedrive#1279]
Hi,
I installed Onedrive through home-brew. It works without problem, but when I try to launch it from the command line to check and modify the configuration, I received a command not found error. How I can solve this problem?
Thanks in advance

**Comment by abraunegg** [comment]
@GiuseppeLaurenza 
This is the GitHub site for the OneDrive client for Linux - not for MacOS nor home-brew.

If you have installed the MacOS client via this: https://formulae.brew.sh/cask/onedrive, then I suggest you seek support from the Home Brew folk as I cannot assist.
