### ISSUE TITLE
How to stop downloading from Onedrive automatically - filling up local HD

### ISSUE THREAD

**Issue by staplemk** [abraunegg/onedrive#1284]
Hello,

Does anyone know why this app might be downloading contents from Onedrive (cloud) back to my local directory after I have deleted them from my local dir?  I left my computer on for a while and when I came back it had shut itself down because my HD was completely full.  I had to run the command line and manually delete files before restarting.

I am just using the command:

onedrive --synchronize --upload-only --no-remote-delete

It seems like Onedrive is somehow running 'as a service', but I never told it to do so.   My current idea to fix this is to change the download rate in the config file to be very low or to 0 so I cut if off....but I am curious if there is another method of stopping this automatic download back to my local dir after deleting the local dir files :)

EDIT: I realized there is only one rate_limit in the configuration that controls both the upload and download speed...so my solution isn't going to work 

Thanks!

**Comment by abraunegg** [comment]
@staplemk 
As you have not followed the correct support process as outlined here: https://github.com/abraunegg/onedrive#reporting-issues or used the bug report template. This is why this exists, to quickly provide answers & help.

As such, I am going to make some assumptions responding to your issue:

1. You are using Ubuntu
2. You have installed via the Ubuntu PPA
3. You are hit by the Ubuntu PPA bug listed here: https://github.com/abraunegg/onedrive/issues/1274

To resolve:
1. Dont use Ubuntu
     - switch to another Linux OS
2. Dont use the Ubuntu PPA
     - Uninstall the Ubuntu PPA package
     - Build from source
     - Email the PPA package developer and get them to fix the package
