### ISSUE TITLE
Sync files shared with me.

### ISSUE THREAD

**Issue by justinabrahms** [abraunegg/onedrive#1294]
**Is your feature request related to a problem? Please describe.**
I work on a shared document and I often want it locally. I have to go into the office365 UI to download a copy, but I really want to sync it via my cli (less clicking & moving around). I can't do that currently b/c this repo [doesn't support](https://github.com/abraunegg/onedrive/blob/3ea16b619fed9b9d04c48cc80904f4910b2b4ac9/src/sync.d#L719) downloading individual shared files.

**Describe the solution you'd like**
I want to say the name of the file I want to sync (maybe in something like my business_shared_folders config?) and have it sync when I run `onedrive`

**Describe alternatives you've considered**
Nothing yet. I'll probably keep with my manual clicking on UI's workflow and stay sad.

**Additional context**
This is in a business, which may have impacts. Nothing beyond that.

**Comment by abraunegg** [comment]
@justinabrahms 
This is what 'sync_list' can be used for - syncing individual files and/or folders.

Please review using this to acomplish your desired outcome.
