### ISSUE TITLE
OneDrive authorization link returns empty page

### ISSUE THREAD

**Issue by cptully** [abraunegg/onedrive#1298]
onedrive --version
onedrive v2.3.13-1build2

Just installed via apt install onedrive

### Bug Report Details ###
I have tried multiple times to follow the configuration steps and always get stopped at the point of authorizing this client to access my work account. The first time I got a popup window with an allow button so I clicked that and got back a blank page. Inspecting shows no html and no code. I have never seen a response URL. I tried again by openeing a new tab in my browser and inspecting that page. then pasting in the "Authorize this app by visiting:" string. Doing this allowed me to look at the reprocess?ctx... packet  on te netwrok tab where I find a response header that looks like the expected value so I pasted that into the command as the response URL and I get back this error message:
```
onedrive.OneDriveException@src/onedrive.d(874): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "a1a38511-f2e4-4bc8-833f-0f6952177b79",
    "error": "invalid_grant",
    "error_codes": [
        9002313
    ],
    "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: f42e253c-3785-436b-98a8-bcdf3faa3d00\r\nCorrelation ID: a1a38511-f2e4-4bc8-833f-0f6952177b79\r\nTimestamp: 2021-02-25 21:19:24Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=9002313",
    "timestamp": "2021-02-25 21:19:24Z",
    "trace_id": "f42e253c-3785-436b-98a8-bcdf3faa3d00"
}
----------------
??:? [0x563712add9d9]
??:? [0x563712adccb5]
??:? [0x563712addb65]
??:? [0x563712adbf58]
??:? [0x563712adb8c5]
??:? [0x563712ae97a8]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7f8ee54929db]
??:? _d_run_main2 [0x7f8ee54927ee]
??:? _d_run_main [0x7f8ee549265d]
??:? __libc_start_main [0x7f8ee507e0b2]
??:? [0x563712ab45ed]
```

**Application and Operating System Details:**
*   ubuntu 20.04 and the output of: `uname -a`
   * uname -a
Linux chris-TGCS 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?  GUI
*   OneDrive Account Type corporate
*   Did you build from source or install from a package? no
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
*   OneDrive Application Version: Output of `onedrive --version`  onedrive v2.3.13-1build2
*   OneDrive Application Configuration: Output of `onedrive --display-config`

onedrive --display-config
onedrive version                    = v2.3.13-1build2
Config path                         = /home/chris/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/chris/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false

*   Provide the version of curl you are using: Output of `curl --version`

curl --version
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

*   Is your configured 'sync_dir' a local directory or a network mount point?
my sync_dir had not been created, so I created it as a local directory and tried again, still no joy.

*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 

lsblk -f
NAME        FSTYPE   LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
loop0       squashfs                                                  0   100% /snap/code/55
loop1       squashfs                                                  0   100% /snap/code/54
loop2       squashfs                                                  0   100% /snap/core18/1988
loop3       squashfs                                                  0   100% /snap/core20/904
loop4       squashfs                                                  0   100% /snap/dbeaver-ce/101
loop5       squashfs                                                  0   100% /snap/core/10823
loop6       squashfs                                                  0   100% /snap/dbeaver-ce/102
loop7       squashfs                                                  0   100% /snap/gnome-3-34-1804/66
loop8       squashfs                                                  0   100% /snap/git-standup/55
loop9       squashfs                                                  0   100% /snap/gtk-common-themes/1514
loop10      squashfs                                                  0   100% /snap/snap-store/467
loop11      squashfs                                                  0   100% /snap/gnome-system-monitor/148
loop12      squashfs                                                  0   100% /snap/spotify/43
loop13      squashfs                                                  0   100% /snap/teams-for-linux/105
loop14      squashfs                                                  0   100% /snap/snapd/11036
loop15      squashfs                                                  0   100% /snap/vlc/1700
loop16      squashfs                                                  0   100% /snap/gtk-common-themes/1506
loop17      squashfs                                                  0   100% /snap/snap-store/518
loop18      squashfs                                                  0   100% /snap/gnome-3-34-1804/60
loop19      squashfs                                                  0   100% /snap/core/10583
loop20      squashfs                                                  0   100% /snap/vlc/2103
loop21      squashfs                                                  0   100% /snap/acrordrdc/24
loop22      squashfs                                                  0   100% /snap/robo3t-snap/4
loop23      squashfs                                                  0   100% /snap/gnome-3-28-1804/145
loop24      squashfs                                                  0   100% /snap/kde-frameworks-5-core18/32
loop25      squashfs                                                  0   100% /snap/core18/1944
loop26      squashfs                                                  0   100% /snap/postman/132
loop27      squashfs                                                  0   100% /snap/snapd/10707
loop28      squashfs                                                  0   100% /snap/teams-for-linux/150
loop29      squashfs                                                  0   100% /snap/sublime-text/97
loop30      squashfs                                                  0   100% /snap/flameshot/6
loop31      squashfs                                                  0   100% /snap/gnome-system-monitor/157
loop32      squashfs                                                  0   100% /snap/lnav/1569
loop33      squashfs                                                  0   100% /snap/postman/133
loop34      squashfs                                                  0   100% /snap/wine-platform-5-stable/16
loop35      squashfs                                                  0   100% /snap/wine-platform-runtime/212
loop36      squashfs                                                  0   100% /snap/wine-platform-runtime/216
nvme0n1                                                                        
├─nvme0n1p1 vfat           E96B-4EE7                             462.5M     9% /boot/efi
└─nvme0n1p2 ext4           36fae319-9912-4f34-9a91-ec7ad93435a3  325.7G    25% /

*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
This account can be accessed via my browser but I am not syncing it to any other computers.

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

The entire verbose log:

[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/chris
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/chris/.config
[DEBUG] configDirName: Configuring application to use default config path
Using Config Dir: /home/chris/.config/onedrive
No config file found, using application defaults
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /home/chris/OneDrive
Initializing the OneDrive API ...
[DEBUG] Downgrading all HTTP operations to HTTP/1.1 by default
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: 

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  run 'onedrive' on cli
2.  get prompt to visit an authorization URL
3.  Click the 'Allow' button on the prompt dialog
4.  Get a blank screen with no HTML elements visible in the Chrome dev tools

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Screenshots**

A screenshot of a white screen won't tell you much...

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@cptully 
> Just installed via apt install onedrive

This is the cause of your problem. This is not supported as Ubuntu Universe contains old invalid versions.

You are running v2.3.13 which is over 13 months old now. Please uninstall that package, + all dependencies that were installed and please follow the correct installation process as per https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md

Specifically for Ubuntu, refer to this: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#important-information-for-all-ubuntu-and-ubuntu-based-distribution-users

If you want to change this situation, so that you can just install via 'apt install onedrive' consider becoming the package maintainer for Ubuntu.

**Comment by cptully** [comment]
I will contend that your README.md file needs to be updated. If you really do not want people using the PPA, then don't list in the matrix at the top of the page. Listing there implies that it is working solution.

**Comment by abraunegg** [comment]
@cptully 
> I will contend that your README.md file needs to be updated. If you really do not want people using the PPA, then don't list in the matrix at the top of the page. Listing there implies that it is working solution.

FYI - nothing in the [readme.md](https://github.com/abraunegg/onedrive/blob/master/README.md) details Ubuntu package support, that is all in the [install.md](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md) document, and the table at the top *clearly* denotes to use the PPA.

> I read that table saw the instructions for using the PPA and did not read the rest of the file. I know, RTFM, but I did, I just did not read the whole file so I did not see the note below explaining that the PPA is so badly out of date.

The PPA *is* up to date (it has the latest version v2.4.10 available), it is the Ubuntu Universe is out-of-date by a major margin. Please re-read the documents again as this is very clearly stated.

If you feel that changes are needed in the documentation, PR's are welcome.
