### ISSUE TITLE
Built from latest source code, still unable to get a response URL

### ISSUE THREAD

**Issue by cptully** [abraunegg/onedrive#1299]
Since my initial report [#1298](https://github.com/abraunegg/onedrive/issues/1298) has been closed and I am still having issues...

I followed the instructions at the link you provided:

> Specifically for Ubuntu, refer to this: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#important-information-for-all-ubuntu-and-ubuntu-based-distribution-users

And I get the same result. I followed the steps to install dependencies, and then the steps to build onedrive. Then I ran onedive and got the expected prompt to visit a custom login url. I visited that URL and got a dialog prompting me to accept the requested permissions. I clicked accept. Then several things loaded (I was watching the network tab in dev tools) and I ended up with a blank page as before.

In case it will help in diagnosing:

onedrive --version
onedrive v2.4.10-2-gcdc6b0b

Other data is unchanged from my [initial report](https://github.com/abraunegg/onedrive/issues/1298).

**Note:** Content removed for security reasons

**Comment by abraunegg** [comment]
@cptully 
> Then several things loaded (I was watching the network tab in dev tools) and I ended up with a blank page as before.

The blank page is 100% correct. It is the URI in your browser that what is required.

Copy and paste that resultant URI from your browser, and paste in the application here:
```
Enter the response uri:
```

This will authenticate your client.

**Comment by abraunegg** [comment]
@cptully 
Additionally, this authentication process is clearly articulated here: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#authorize-the-application-with-your-onedrive-account

**Comment by abraunegg** [comment]
@cptully 
Given also your information dump, I would strongly advise you to *change* your OneDrive password now - and do so before authenticating the client, otherwise you will need to re-authenticate again using `--logout`

**Comment by cptully** [comment]
Password changed. But I did not see your message before authenticating so I used --logout and the reautheticated. Sorry to be a pest but I completely missed the sentence about getting a blank page and copying the URI.

**Comment by abraunegg** [comment]
@cptully 
Glad you are hopefully operational now with the client. Closing issue.
