### ISSUE TITLE
Device platform Unknown used by the user is an unsupported device platform

### ISSUE THREAD

**Issue by erenoglu** [abraunegg/onedrive#13]
Hi, I'm getting the below error message in the authentication URL, after authenticating to Onedrive.
This is Onedrive for Business authenticating with Multi Factor Authorization. My company is exerting some protections on the data, ie not allowing syncing from Android with official Onedrive app unless Intune Company Portal is installed, device is encrypted. Maybe it has to do with it, and it may not be a bug as such. 

https://login.microsoftonline.com/common/oauth2/nativeclient?error=access_denied&error_description=.....+Device+platform+Unknown+used+by+the+user+is+an+unsupported+device+platform.+Supported+device+platforms+are%3a+iOS%2c+Android%2c+Mac%2c+and+Windows+flavors......

**Comment by abraunegg** [comment]
> My company is exerting some protections on the data, ie not allowing syncing from Android with official Onedrive app unless Intune Company Portal is installed, device is encrypted. Maybe it has to do with it, and it may not be a bug as such.

This is not a 'onedrive' bug.

Your company protections exist to enforce company policies regarding data leakage & data protection requirements to ensure with any data security compliance requirements that they have.

By trying to use the 'onedrive' client without those protections in place you are essentially trying to 'go-around' these protections which could be seen as an employee attempting to extract data (data leakage) and could result in undesirable consequences for you.

**Comment by abraunegg** [comment]
Added information to FAQ: https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions
