### ISSUE TITLE
Implicit wildcard "*" in sync_list

### ISSUE THREAD

**Issue by xushangning** [abraunegg/onedrive#1311]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**

When the path `/hhh` is specified in `sync_list`, the file at `/hhhh` will also be uploaded to OneDrive. This behavior should be reserved for `/hhh*` per my understanding of the `sync_list` syntax. The correct behavior should be that only the file or dir at `/hhh` will be uploaded.

**Application and Operating System Details:**
*  OS version: Ubuntu 20.04.1
    ```
    $ uname -a
    Linux xsn-serverless 5.4.0-65-generic #73+NOHZFULL SMP Sun Feb 14 07:49:37 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
    ```
*   Headless
*   OneDrive Account Type: OneDrive Business
*   Did you build from source or install from a package? Ubuntu package.
*   ~~If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`~~ NA
*   OneDrive Application Version: Output of `onedrive --version`
    ```
    onedrive v2.4.10-0~202102221319~ubuntu20.04.1
    ```
*   OneDrive Application Configuration: Output of `onedrive --display-config`
    ```
    Configuration file successfully loaded
    onedrive version                       = v2.4.10-0~202102221319~ubuntu20.04.1
    Config path                            = /home/xsn/.config/onedrive
    Config file found in config path       = true
    Config option 'check_nosync'           = false
    Config option 'sync_dir'               = /home/xsn
    Config option 'skip_dir'               = _minted-*
    Config option 'skip_file'              = ~*|.~*|*.tmp|*.fls|*.aux|*.fdb_latexmk|*.log|*.fls|*.synctex.gz 
    Config option 'skip_dotfiles'          = false
    Config option 'skip_symlinks'          = false
    Config option 'monitor_interval'       = 300
    Config option 'min_notify_changes'     = 5
    Config option 'log_dir'                = /var/log/onedrive/
    Config option 'classify_as_big_delete' = 1000
    Config option 'upload_only'            = false
    Config option 'no_remote_delete'       = false
    Config option 'remove_source_files'    = false
    Config option 'sync_root_files'        = false
    Selective sync 'sync_list' configured  = true
    sync_list contents:
    /Documents/Notes
    /Calibre Library
    /hhh
    Business Shared Folders configured     = false
    ```
*   Provide the version of curl you are using: Output of `curl --version`
    ```
    curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
    Release-Date: 2020-01-08
    Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
    Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
    ```
*   Is your configured 'sync_dir' a local directory or a network mount point? Local
*   ~~If *not* local, provide all the mountpoints in your system: Output of: `mount`~~ NA
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f`: ext4
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time: None of the above applies.

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**

1. Create the directory `hhh` and file `hhhh` at the local OneDrive root.
2. Add `/hhh` to `sync_list` and run `onedrive --synchronize --resync`
3. Both `hhh` and `hhhh` will be uploaded.

~~If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au~~

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output: Run with `onedrive --synchronize --resync --verbose`: [onedrive-log.txt](https://github.com/abraunegg/onedrive/files/6074264/onedrive-log.txt)

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [ ] Verbose Log Output from your error
*   [ ] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@xushangning 

Many thanks for the bug report. Please can you test the following PR to assist in resolving your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1317/head:pr1317
git checkout pr1317
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.10-7-g1ec235d` or greater.
