### ISSUE TITLE
Is it possible to use '--single-directory' with '--sync-shared-folders'

### ISSUE THREAD

**Issue by wn2000** [abraunegg/onedrive#1312]
Hello is it possible to use `--single-directory` with `--sync-shared-folders` to sync a single directory from OneDrive Business Shared Folders?
I tried that and it says the specified single directory does not exist on OneDrive.

**Comment by abraunegg** [comment]
@wn2000 
Please open this as a [discussion](https://github.com/abraunegg/onedrive/discussions)
