### ISSUE TITLE
Order of processing?

### ISSUE THREAD

**Issue by wn2000** [abraunegg/onedrive#1313]
Sorry not an issue but a question, as I don't know where to ask that.

I'm trying to migrate a large OneDrive Business Shared Folder to local drive, so I can delete the remote files after that.

If I see the program has moved on to download files in a new subfolder, can I assume it has finished downloading all previous folders? Asking as I do not want to wait until everything downloaded then delete remote folders, that would take a long time.

Thanks.

**Comment by abraunegg** [comment]
@wn2000 
Please open this as a [discussion](https://github.com/abraunegg/onedrive/discussions)
