### ISSUE TITLE
cannot get drive-id due to rest-api limit

### ISSUE THREAD

**Issue by tomturbu** [abraunegg/onedrive#1324]
First of all - many thanks for this very helpful project - it is really great and helps me every day!

### Bug Report Details ###
I try to find my drive-id of a shared folder - i'm sure there is no typo in my site-name.....

`onedrive --get-O365-drive-id 'xxxx - Sales'`     

Onedrive-application doesn't find that sharepoint-site, but gives me back exactly 200 shared sites - but hey, we have way more then 200 shared sites here, so i was a bit surprised why only 200 shared folders were reported....

I had a look on the code (onedrive.d) and see that the default query is used, which has a limit of 200 results as described here: https://stackoverflow.com/questions/39772614/microsoft-graph-maximum-number-for-list-onedrive-items
and here:
https://docs.microsoft.com/en-us/microsoft-365/compliance/limits-for-content-search?view=o365-worldwide

So after checking the code i realized you retrieve all sites and loop over them. Basically that results in a loop of the default number of items which is 200 - if the site is outside of this array, it will not be found of course....

### Workaround ###

Unfortunately i'm not familiar in developing code and can't add better code (imo some pagination should be a better approach) or even add a merge request - but at least i try to highlight the workaround i found so maybe it is useful....

I changed the code in onedrive.d on my workstation, recompliled it, and tested it again - and now it is possible to find the drive-id of my shared folder.
Unfortunately my code snippet is a bad workaround, as i only increased the limit to 500 to get my shared-folder-id.....
In onedrive.d i changed all of this 
`string siteSearchUrl = globalGraphEndpoint ~ "/v1.0/sites?search";`
to
`string siteSearchUrl = globalGraphEndpoint ~ "/v1.0/sites?top=500&search";`

However, i have now the drive-id and now i'm using the official build again - just needed that drive-id to initiate the sync....

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
Linux xxx 5.8.0-7642-generic #47~1614007149~20.04~82fb226-Ubuntu SMP Tue Feb 23 02:56:27 UTC  x86_64 x86_64 x86_64 GNU/Linux

*   Are you using a headless system (no gui) or with a gui installed?
Pop!_OS based on Ubuntu
*   OneDrive Account Type
o365 enterprise
*   Did you build from source or install from a package?
well, basically i tried the package, but for testing and the workaround i built it on my own....

package - currently running on Application version: v2.4.10-0~202102221319~ubuntu20.04.1
*   OneDrive Application Version: Output of `onedrive --version`
onedrive v2.4.10-0~202102221319~ubuntu20.04.1

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. you need more than 200 shared sites
2. search for any site to get the list of available sites
3. check which site is missing from that list
4. try to get drive id exactly of one of the missing sites..

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@tomturbu 
Many thanks for the bug report & suggested fix.

Given I am not able to test this, there might also be another fix. Can you generate a verbose debug log using this command:
```
onedrive --get-O365-drive-id 'xxxx - Sales' --verbose --verbose
```
It would be great if you can archive and email this to me so I can look through the actual response in this situation.

The reason for this is I am wondering if, by default, if the response includes 'nextLink' to page through to the next set of data (next lot of 200 or remaining data) when >200 items are found - however there is nothing in the API [documentation](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/site?view=odsp-graph-online) that details that it does this, and without a SharePoint setup of >200 items I cannot test to determine myself. I could go and create 300+ dummy SharePoint sites and add some dummy data to all of them - but that is also rather time intensive to do.

Making a change like you have suggested is pretty easy to do, but if you could help by answering the above question first, this would be greatly appreciated - as your fix would then just limit the query to 500 and if someone else has more - then the same issue would pop up again in the future. If the API does return nextLink data, that becomes a better fix.

**Comment by tomturbu** [comment]
@abraunegg i've archived the logs and sent via mail......
I agree, my change is not really a workaround, it is just a quick 'n dirty "thing" to get this required drive-id :-) including pagination would be perfect of course to finally fix it...

**Comment by tomturbu** [comment]
Sure, i have time, no worries.....

**Comment by tomturbu** [comment]
@abraunegg 
I can confirm that now the drive-id is retrieved - but at the end this error messages pops up:
```
ERROR: The results returned from OneDrive API do not contain the required items to match. Please check your permissions with your site administrator.
ERROR: Your site security settings is preventing the following details from being accessed: 'displayName', 'id' and 'webUrl'
ERROR: To debug this further, please use --verbose --verbose to provide insight as to what details are actually returned.

```
i guess this is due to some site restrictions of public shared site for which i don't have permissions and not really an error - but i'll send you the logfiles via mail just to be sure...

**Comment by fgr1986** [comment]
Hi @tomturbu  experiencing the same issue. Please update the thread whenever you get more insights on whether it is admin permissions or an error. Thanks in advance

**Comment by abraunegg** [comment]
@tomturbu 
If you could send an updated verbose log using the PR (`onedrive --get-O365-drive-id 'xxxx - Sales' --verbose --verbose`) that would be greatly appreciated.

@fgr1986 
The error message is 'normal' when SharePoint details are being restricted. In the PR, it *might* be being displayed due to an unforeseen issue with the changes made as part of the PR.

**Comment by abraunegg** [comment]
@tomturbu 
I have updated the PR to provide some additional details as to what is missing when that particular error pop's up.

Please make sure you are testing `onedrive v2.4.10-16-g5ef6bee` to see the additional details when using single verbose mode:
```
onedrive --get-O365-drive-id 'xxxx - Sales' --verbose
```

**Example:**
```
ERROR: SharePoint Site details not provided for : testteamsite
ERROR: The SharePoint Site results returned from OneDrive API do not contain the required items to match. Please check your permissions with your site administrator.
ERROR: Your site security settings is preventing the following details from being accessed: 'displayName', 'id' and 'webUrl'
 - 'displayName' available = false
 - 'id' available          = true
 - 'webUrl' available      = false
ERROR: To debug this further, please use --verbose --verbose to provide insight as to what details are actually returned.

```

From this, you should then be able to determine if this site is the public shared site you do not have access to, or if the site is something else.

**Comment by abraunegg** [comment]
@tomturbu 
Any update here in being able to test the updated code?

**Comment by tomturbu** [comment]
@abraunegg 
Sorry for my late response, was out of office short-term....
The testing looks really good now, i can confirm that the pagination works as expected.

The errors mentioned above are "works as designed" for me, please see the output of some tests of pr1329
`ERROR: SharePoint Site details not provided for: lcmigration
ERROR: The SharePoint Site results returned from OneDrive API do not contain the required items to match. Please check your permissions with your site administrator.
ERROR: Your site security settings is preventing the following details from being accessed: 'displayName', 'id' and 'webUrl'
 - Is 'displayName' available = false
 - Is 'id' available          = true
 - Is 'webUrl' available      = true
ERROR: To debug this further, please increase verbosity (--verbose or --verbose --verbose) to provide further insight as to what details are actually being returned.

ERROR: SharePoint Site details not provided for: ShortPoint
ERROR: The SharePoint Site results returned from OneDrive API do not contain the required items to match. Please check your permissions with your site administrator.
ERROR: Your site security settings is preventing the following details from being accessed: 'displayName', 'id' and 'webUrl'
 - Is 'displayName' available = false
 - Is 'id' available          = true
 - Is 'webUrl' available      = true
ERROR: To debug this further, please increase verbosity (--verbose or --verbose --verbose) to provide further insight as to what details are actually being returned.`

So on both sites i have no displayName, therefore the error. Both sites are some old sites on our sharepoint, seems that both sites have been migrated to new sharepoint and displayName is just missing...

**Comment by abraunegg** [comment]
@tomturbu 
Many thanks for the confirmation - will merge this PR to 'master' and mark this issue as fixed
