### ISSUE TITLE
Filename with % in them causes error

### ISSUE THREAD

**Issue by sweharris** [abraunegg/onedrive#1342]
### Bug Report Details ###
If a file contains a % then the upload fails (not a valid JSON response).

```
DEBUG] Checking local path: ./tmp
[DEBUG] Checking file: ./tmp/file%21%22%23
[DEBUG] skip_file evaluation for: /tmp/file%21%22%23
[DEBUG] File upload destination is users default driveId ..
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/drives/<mydriveid>/root:/.%2Ftmp%2Ffile%2521%2522%2523?select=id,name,eTag,cTag,deleted,file,folder,
root,fileSystemInfo,remoteItem,parentReference,size
[DEBUG] fileDetailsFromOneDrive = onedrive.getPathDetailsByDriveId(parent.driveId, path); generated a OneDriveException
ERROR: An error was returned from OneDrive and the resulting response is not a valid JSON object
ERROR: Increase logging verbosity to assist determining why.
```

(Even with extra verbosity I don't see any additional output)

This is possibly a OneDrive issue, since `rclone` (which also sends to `%2521%2522%2523`...) also suffers the same problem and reports `nameContainsInvalidCharacters: One or more invalid characters are present in the path (/file!"#).`

So I think OneDrive itself may be double-unescaping the `%2521` into `%21` into `!`

**Application and Operating System Details:**
CentOS 7, onedrive 2.4.10, personal Onedrive.

**Comment by abraunegg** [comment]
@sweharris 
It looks like also a documentation bug on the Microsoft end, as based on the [documentation](https://support.microsoft.com/en-us/office/invalid-file-names-and-file-types-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa) a '%' should be allowed for Personal Accounts - but, the API is throwing an error.

None the less, this is a bug, as the invalid local file name should be trapped correctly, before being attempted to be searched if available online.

As such, please can you test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1343/head:pr1343
git checkout pr1343
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.10-16-ge9772b1` or greater.

**Comment by sweharris** [comment]
OK, that seems to get trapped

```
% ./onedrive --synchronize
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Uploading differences of ~/OneDrive
Uploading new items of ~/OneDrive
Skipping item - invalid name (Microsoft Naming Convention): ./tmp/test%21%22%23
```

But is it an invalid name, though?  On the OneDrive website I can perfectly create a file "foo%21%22%23.txt"

And it happily downloaded..

```
% ls ~/OneDrive/tmp/
foo%21%22%23.txt  test%21%22%23
```

**Comment by abraunegg** [comment]
@sweharris 
Based on the documentation - https://support.microsoft.com/en-us/office/invalid-file-names-and-file-types-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa - '%' is an invalid character.

**Comment by sweharris** [comment]
If I'm reading that correctly, % isn't allowed for Sharepoint 2013 but _is_ allowed for O365

**Comment by abraunegg** [comment]
@sweharris 
Creating a file online with a '%' is different from using the API and making calls via the API with a correctly URL Encoded JSON call to determine if a file exists or not, before attempting to upload the file (this is where your error is begin generated from)

So, if, for Personal Accounts '%' is meant to be accepted for all API calls, then, when querying the file, the response should work, not return an error - which is your experience.

So .. to be consistent:

* Files with a '%' also fail API query when using a SharePoint Library or using Office365 Business Account
* When making the change to flag '%' as an invalid file when attempting to upload, this provides consistent behavior across all account types, and that you say that 'rclone' presents a similar error message as well for similar named files
* That you can download a file that has a '%' in it, leads to me to think that this is an API inconsistency.

If you are unhappy with this fix, more than happy for you to re-work and submit a better fix via a PR that supports all account types and resolves this issue or submit a bug against the API and have the OneDrive API team look into it.

**Comment by sweharris** [comment]
Oh I definitely think it's an API issue on the Microsoft side since the error returned from the graph endpoint (as reported by `rclone`) has `%2521` converted to `!`.  I dunno if there's any way it can be worked around.

With the current PR you run the risk of someone downloading a file from OneDrive, trying to edit it, then it failing to upload 'cos it contains the `%` character.  It'll definitely need documenting :-)

**Comment by sweharris** [comment]
And just for fun, with the pre-fix version I created a file "test%4a" and it resulted in an upload file of "TestJ".  Definitely looks like a Microsoft API bug to me...

**Comment by abraunegg** [comment]
> And just for fun, with the pre-fix version I created a file "test%4a" and it resulted in an upload file of "testJ". Definitely looks like a Microsoft API bug to me...

Which means, the approach of checking '%' in local file names is the right one, although downloading existing files from OneDrive, even if they have the '%' in the name, is also correct unless Microsoft prevents the actual creation of these files online.

**Comment by sweharris** [comment]
It looks like Microsoft have fixed the problem on their end, so the % character is safe to use again.  Using a version from before this PR I can now correctly upload a file called "test%21" and that's how it shows up on onedrive.

**Comment by abraunegg** [comment]
@sweharris 
No problem - I will back out the PR.

In the future, if this pops up again - this will have to be handled by Microsoft, as technically was not a bug with the client.
