### ISSUE TITLE
Bad Request when using it in a standard Raspberrypi OS 32bits with student onedrive account

### ISSUE THREAD

**Issue by andresperezcera** [abraunegg/onedrive#1353]
I installed and tested this app in ubuntu-desktop 20.10 64bits for raspberrypi 4 and it worked correctly. However I forgot to note the version. Yet on Raspberrypi OS Buster 32 bits, onedrive v2.2.5-1  I get the following error:

```terminal
onedrive.OneDriveException@src/onedrive.d(713): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "xxxxxxx",
    "error": "invalid_grant",
    "error_codes": [
        9002313
    ],
    "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: x0x0x0x0x0x0x0x0x\r\nCorrelation ID: xxxxxxa\r\nTimestamp: 2021-03-18 11:35:10Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=9002313",
    "timestamp": "2021-03-18 11:35:10Z",
    "trace_id": "x0x0x0x0x0x0x0x0x"
}
----------------
??:? [0x92f03]
??:? [0x921cb]
??:? [0x92a1b]
??:? [0x9155b]
??:? [0x9afb3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xb6860b17]
??:? _d_run_main [0xb68608af]
??:? __libc_start_main [0xb659e717]
```
I've replaced trace_id and correlation_id in case those include relevant information. Procedure followed in both OS's was the same. I'll proceed to download and install from repo to verify if it is a resolved issue on current release.

**Comment by andresperezcera** [comment]
After following [build instructions](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md) and installing onedrive v2.4.10-18-g0dcc76f the issue is resolved for current version. I leave this behind for others interested in solving this issue on the same conditions. The build process took less than 10 minutes and little over 30% of CPU power on a raspberrypi4.

**Comment by abraunegg** [comment]
@andresperezcera 
> I installed and tested this app in ubuntu-desktop 20.10 64bits for raspberrypi 4 and it worked correctly. However I forgot to note the version. Yet on Raspberrypi OS Buster 32 bits, onedrive v2.2.5-1 I get the following error

This is because `apt install onedrive` using the default Ubuntu Universe is not supported. You have 2 options:
1. Use the Ubuntu PPA
2. Build from Source

Even for this platform - ubuntu-desktop 20.10 64bits for raspberrypi 4 - if you have not compiled from source you are running an unsupported version.

If you want to *change* this situation, become the Ubuntu Package maintainer and update the packages across all Ubuntu based platforms.
