### ISSUE TITLE
Service failed after rPi 4 reboot

### ISSUE THREAD

**Issue by rusulucian85** [abraunegg/onedrive#1355]
uname -a
Linux ubuntu 5.8.0-1017-raspi #20-Ubuntu SMP PREEMPT Mon Mar 1 14:19:20 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

no gui

onedrive v2.4.10-16-g6bec0dd

Mar 19 21:07:54 ubuntu systemd[1]: Started OneDrive Free Client.
Mar 19 21:07:54 ubuntu onedrive[2924]: Configuration file successfully loaded
Mar 19 21:07:55 ubuntu systemd[1]: onedrive.service: Main process exited, code=dumped, status=4/ILL
Mar 19 21:07:55 ubuntu systemd[1]: onedrive.service: Failed with result 'core-dump'.
Mar 19 21:07:58 ubuntu systemd[1]: onedrive.service: Scheduled restart job, restart counter is at 312.
Mar 19 21:07:58 ubuntu systemd[1]: Stopped OneDrive Free Client.

**Comment by abraunegg** [comment]
@rusulucian85 
Please follow the correct support process as detailed here:
* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
