### ISSUE TITLE
A flag to ignore SSL certificate check (like curl --insecure or wget --no-check-certificate)

### ISSUE THREAD

**Issue by marceloandrioni** [abraunegg/onedrive#1356]
**Is your feature request related to a problem? Please describe.**

Yes, I am trying to use onedrive behind a corporate proxy but it fails due to local certificates. I tried to export all the certificates that I could find in Windows and import on Linux but it didn't solve the problem.

Usually I can bypass this when downloading something by using `wget --no-check-certificate` or `curl  --insecure` but I couldn't find a similar option in onedrive.

Bellow are the last lines of `onedrive --synchronize --resync --download-only --verbose --debug-https` with the SSL certificate error.

```
Proxy-Authorization: Basic ZWFuaTptUFNXaDMyYw==
User-Agent: ISV|abraunegg|OneDrive Client for Linux/v2.4.10-0~202102221319~ubuntu20.04.1
Proxy-Connection: Keep-Alive

< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* CONNECT phase completed!
* CONNECT phase completed!
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 2

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    SSL peer certificate or SSH remote key was not OK on handle 564D75F828B0
  Calling Function: download()

ERROR: File download size mis-match. Increase logging verbosity to determine why.
ERROR: File download hash mis-match. Increase logging verbosity to determine why.
Skipping item - excluded by skip_dir config: Arquivos de Chat do Microsoft Teams
```

**Describe the solution you'd like**
A flag to ignore SSL certificate check.

**Describe alternatives you've considered**
Importing all the certificates I could find from a Windows machine, but it didn't solve the problem.

**Additional context**

**Comment by abraunegg** [comment]
@marceloandrioni 
Whilst I can understand how this might be useful, you need to speak with your security team and load your corporate CA certificate into your Linux system so that Linux can use your corporate CA.
