### ISSUE TITLE
Migration use case: Upload home dirs for multiple users

### ISSUE THREAD

**Issue by mcmenkes** [abraunegg/onedrive#136]
1st of all really cool software. Thanks for your work! 

So i have an up and running onedrive and looking for the best strategy to upload an amount of old linux samba server users' home directories - as kinda bulk upload to O365.

If i understand the logical part correctly i have to 

```
onedrive --synchronize --monitor --upload-only --confdir="~/.config/user01" & 
onedrive --synchronize --monitor --upload-only --confdir="~/.config/user02" &
onedrive --synchronize --monitor --upload-only --confdir="~/.config/user03" &
....
```
Every user-profile must be authenticated via the O365 tokens after logging in with the web browser for every single user - manually. 

- is there a way to import CSVs to manage the bulk: user | profile-dir | home-dir | O365-Account-Token

- how do i manage the sync path for each user best?
Every profile must match to O365-user0x <---> /homes/user0x 

Try to find an easy approach for 50 user and looking forward for some ideas. 

Thanks. 

MCm

**Comment by abraunegg** [comment]
@mcmenkes 
Any update on your side as to progress?

**Comment by mcmenkes** [comment]
Thank you very for your quick support.
Actually i am off this particular problem right now, but will come back, because it has to be solved. 

Yes I have  to write a wrapper script and will share it here...

thanks.
