### ISSUE TITLE
Syslog disabling

### ISSUE THREAD

**Issue by Boia11** [abraunegg/onedrive#1361]
Bug Report Details

The rsyslog keeps reporting debug infromation of everything onedrive does, I can't stop it.

Application and Operating System Details:

```
    Debian 9.13 | uname output `4.4.197-1236-rockchip-ayufan-g30faab37e339 #1 SMP Tue Oct 22 11:35:10 UTC 2019 aarch64 GNU/Linux`
    Running without GUI
    OneDrive Account Type -- Business
    Installed using "Debian (ARM64)" instructions mentioned in the INSTALL.md document.
    LDC -- 1.25.1
    OneDrive Application Version: 2.4.10
```
Config file:
```
sync_dir = "~/OneDrive"
skip_file = "~*|.~*"
monitor_interval = "1800"
# skip_dir = ""
log_dir = "/var/log/onedrive/"
# drive_id = ""
# upload_only = "true"
# check_nomount = "false"
check_nosync = "true"
# download_only = "false"
disable_notifications = "true"
# disable_upload_validation = "false"
enable_logging = "false"
# force_http_11 = "false"
# force_http_2 = "false"
# local_first = "false"
# no_remote_delete = "false"
skip_symlinks = "false"
# debug_https = "false"
skip_dotfiles = "false"
# dry_run = "false"
# min_notify_changes = "5"
# monitor_log_frequency = "5"
monitor_fullscan_frequency = "6"
# sync_root_files = "false"
# user_agent = ""
```

To Reproduce
Steps to reproduce:

    Set enable_logging from "true" to "false"
    Reboot system

**Comment by abraunegg** [comment]
@Boia11 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

Additionally debug information is only enabled when using `--verbose --verbose`. However you are starting the client may be activating debug mode.

Closing issue as support template not used.
