### ISSUE TITLE
Unable to authorise app

### ISSUE THREAD

**Issue by waynedmoore** [abraunegg/onedrive#137]
### Bug Report Details ###
**Describe the bug**
After installing onedrive (v2.1.1-4-g448b624), I run it from the command line and am prompted with the URL to authorise the app. When I browse to the URL, I get the MS account picker, but when I click on my name then I just get a blank screen. I've tried this on Chrome and Firefox on Ubuntu, and Chrome and IE on Windows 10 with the same result. I've uninstalled and reinstalled the app with the same result.

**Application and Operating System Details:**
- OS: Output of `uname -a`
- Application version: Output of `onedrive --version`
- DMD or LDC compiler version `dmd --version` or `ldmd2 --version`

uname -r: 4.15.0-32-generic
onedrive --version: onedrive v2.1.1-4-g448b624
dmd --version DMD64 D Compiler v2.081.0
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. Go to shell and run ./onedrive
2. Copy the URL from terminal into the browser and go, click on my username in the account picker
URL: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
3. Browser redirects but just renders a blank page.
Redirect URL: https://login.microsoftonline.com/common/oauth2/nativeclient?code=<code redacted>

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```
onedrive --synchronize --verbose <any of your other needed options>

wayne@MacBuntu:~$ onedrive --synchronize --verbose
Loading config ...
Using Config Dir: /home/wayne/.config/onedrive
Initializing the OneDrive API ...
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: 

```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See https://guides.github.com/features/mastering-markdown/ for more details.

Application Log Output:
```
Verbose console log output goes here
```

**Screenshots**

**Additional context**
I had previously been using v1.0.1 (skiion) successfully. I changed my Office365 password recently but never re-authorised v1.0.1. I didn't remove this version before installing v2.1.1 but after the initial failure, I did uninstall 2.1.1 and move my config files before reinstalling. It made no difference.

### Bug Report Checklist ###
- [ ] Detailed description
- [ ] Reproduction steps (if applicable)
- [ ] Verbose Log Output

**Comment by abraunegg** [comment]
> When I browse to the URL, I get the MS account picker, but when I click on my name then I just get a blank screen. I've tried this on Chrome and Firefox on Ubuntu, and Chrome and IE on Windows 10 with the same result. I've uninstalled and reinstalled the app with the same result.

You copy the URL from the browser that is presenting the 'blank' screen and paste that entire URL at the `Enter the response uri:` prompt

If you still have issues, please let me know.

**Comment by waynedmoore** [comment]
I feel stupid now. Thank you. I was sure I should get a short code back in response (I've seen this from other apps). I'm happily syncing now.
