### ISSUE TITLE
dependencies unmet

### ISSUE THREAD

**Issue by BeerHuntor** [abraunegg/onedrive#1377]
trying to get onedrive installed on my laptop - i am a new linux user so possible im doing something wrong but using the information here https://www.linuxuprising.com/2020/02/how-to-keep-onedrive-in-sync-with.html on ubuntu 20.04 im getting this error when following the install instructions using ppa

"sudo apt install onedrive
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 onedrive : Depends: libphobos2-ldc-shared90 (>= 1:1.20.1) but it is not installable
E: Unable to correct problems, you have held broken packages."

**Comment by BeerHuntor** [comment]
> trying to get onedrive installed on my laptop - i am a new linux user so possible im doing something wrong but using the information here https://www.linuxuprising.com/2020/02/how-to-keep-onedrive-in-sync-with.html on ubuntu 20.04 im getting this error when following the install instructions using ppa
> 
> "sudo apt install onedrive
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies.
> onedrive : Depends: libphobos2-ldc-shared90 (>= 1:1.20.1) but it is not installable
> E: Unable to correct problems, you have held broken packages."

Seemed to have fixed the issue - turns out I had the checkboxes under unbuntu software and updates > ubuntu software on default selections - since have checked all the top 4 boxes and it works as intended.

**Comment by abraunegg** [comment]
@BeerHuntor 
Glad you solved your issue, however to install the client on Ubuntu you really *should* be following these instructions and not a 3rd party website: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md

For Ubuntu 20.x you have 2 options:
* Install via the Ubuntu PPA
* Compile via using the correct dependencies: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-ubuntu-18x-ubuntu-19x-ubuntu-20x--debian-9-debian-10---x86_64


Additionally in future, please follow the correct support process as outlined here:
* Have a question - https://github.com/abraunegg/onedrive#have-a-question
* Reporting an issue or bug - https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
