### ISSUE TITLE
File kept in database when using --no-remote-delete & --remove-source-files

### ISSUE THREAD

**Issue by SylvainLaugie** [abraunegg/onedrive#1382]
### Bug Report Details ###

Following #1381 

When using option "--no-remote-delete" in the command `onedrive --synchronize --upload-only --no-remote-delete --remove-source-files`, local files are deleted as expected, **but stay in the database**. Because of that, each new run of the command will still mention those deleted files. Worst, if at some point I execute again without "--no-remote-delete", it will deleted remote files that stayed in database until then.

**Application and Operating System Details:**
*   Debian 10.9 : `Linux *hostname* 4.19.0-5-cloud-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux`
*   No GUI
*   OneDrive **Personal**
*   Built **from source on tag v2.4.10**
*   Built with: **DMD64 D Compiler v2.096.0**
*   OneDrive Application Version: **onedrive v2.4.10**
*   OneDrive Application Configuration:
```
Configuration file successfully loaded
onedrive version                       = v2.4.10
Config path                            = /root/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /root/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
Myfolder/Mysubfolder/
Business Shared Folders configured     = false
```
*   curl version: **curl 7.64.0**
*   sync_dir is a **local directory** (no network mount)
*   Partition format type: **ext4**

**To Reproduce**

I reproduced with the following commands (and logged at the same time)
```bash
echo "file 1" > /root/OneDrive/Myfolder/Mysubfolder/file1
# New file is created

onedrive --synchronize --verbose --verbose --upload-only --no-remote-delete --remove-source-files > /root/debug_output_1.log 2>&1
# File is now present on OneDrive and deleted from local storage

onedrive --synchronize --verbose --verbose --upload-only --no-remote-delete --remove-source-files > /root/debug_output_2.log 2>&1
# onedrive still checks for file1 state (see logs just after)
```

Logs are sent to your address. The specific parts that draws my attention are:

**debug_output_1.log:133** : File is deleted locally only, not from database
```
Removing local file as --upload-only & --remove-source-files configured
[DEBUG] Removing local file: ./Myfolder/Mysubfolder/file1
```

**debug_output_2.log:107** : File is still in database and checked by onedrive
```
Processing Myfolder/Mysubfolder/file1
[DEBUG] skip_file evaluation for: file1
[DEBUG] Evaluation against 'sync_list' for: Myfolder/Mysubfolder/file1
[DEBUG] Evaluation against 'sync_list' entry: Myfolder/Mysubfolder
[DEBUG] Evaluation against 'sync_list' result: parental path match
[DEBUG] Evaluation against 'sync_list' final result: included for sync
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
```

Thanks

**Comment by abraunegg** [comment]
@SylvainLaugie 

Please can you test the following PR to resolve this issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1383/head:pr1383
git checkout pr1383
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.10-24-geb53403` or greater

**Comment by SylvainLaugie** [comment]
@abraunegg 

This worked well 👍 file is uploaded, locally deleted, not present in database:

```
Uploading new file ./Myfolder/Mysubfolder/file2 ... done.
[DEBUG] File Size: 7 Bytes
[DEBUG] Upload Duration: 0.474 Seconds
[DEBUG] Upload Speed: 1.40838e-05 Mbps (approx)
[DEBUG] Skipping adding to database as --upload-only & --remove-source-files configured
Remaining free space on OneDrive: 5327665137
Removing local file as --upload-only & --remove-source-files configured
[DEBUG] Removing local file: ./Myfolder/Mysubfolder/file2
```

However, I'm thinking about another possible case: if you don't use `--remove-source-files`, but delete the file manually later. In that case, file is in database and will stay there. That can happen if you want to keep the local file for a certain time, for example.

Note that this is not my case, and I'm happy with the solution given in your PR 👍 but I thought that was worth mentioning.

Thanks for your rapidity 💯

**Comment by abraunegg** [comment]
@SylvainLaugie 
Thanks for confirming the fix, will merge into 'master'

As for the other use case, nothing has been raised thus far as that being an issue.
