### ISSUE TITLE
Synchronization fails with 'The parent item is not in the local database'

### ISSUE THREAD

**Issue by dleslie** [abraunegg/onedrive#139]
### Bug Report Details ###
**Describe the bug**
The execution of synchronize prematurely halts due to an unhandled exception.

**Application and Operating System Details:**
- OS: Linux dleslie-ThinkPad-X140e 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Application version: `bdc33e6`
- OneDrive Account Type: Family
- DMD or LDC compiler version `dmd --version` or `ldmd2 --version`: DMD64 D Compiler v2.078.2

**To Reproduce**
```
#> onedrive --resync --synchronize
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
The parent item is not in the local database
Syncing changes from OneDrive ...
The parent item is not in the local database
Syncing changes from OneDrive ...
object.Exception@src/sync.d(1114): The parent item is not in the local database
----------------
??:? pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, const(char[])) [0x83044266]
??:? pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x830c68b9]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x830a854d]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x830a7cda]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x830a7bd1]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x830a7bd1]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x830a7bd1]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x830a68fb]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x8308b737]
??:? _Dmain [0x8308afa7]
```

**Comment by abraunegg** [comment]
This may be the same as https://github.com/abraunegg/onedrive/issues/121 which was a local path issue.

Can you provide a full log using:

```
onedrive --synchronize --verbose --debug-https
```

and email to support@mynas.com.au

**Comment by dleslie** [comment]
My apologies, but I'm not too comfortable with that, the log is full of private information.

**Comment by abraunegg** [comment]
OK .. can you go through the resulting log and post (via email) the following:

1. Full path which is failing the check
2. The HTTP responses where the path is checked on OneDrive & it's returning response
3. The response of the database

That should trim down the data & allow you to sanitize the details to the extent that your happy.

**Comment by abraunegg** [comment]
Additionally, anything that you do send me is protected by the following legislation: Privacy and Data Protection Act 2014 (Vic)
(http://www8.austlii.edu.au/cgi-bin/viewdb/au/legis/vic/num_act/padpa201460o2014317/)

**Comment by abraunegg** [comment]
@dleslie 
Based on the work I was doing for #121, please can you test this branch:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/143/head:pr143
git checkout pr143
make
make install
```

I suspect that you have the following 'somewhere':
```
/my/path/to/files/file1.txt
/my/path/to/Files/file1.txt
```

Note the differences between 'files' and 'Files'

On Linux, this is no issue. For OneDrive, it is the same:

https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file

> Do not assume case sensitivity. For example, consider the names OSCAR, Oscar, and oscar to be the same, even though some file systems (such as a POSIX-compliant file system) may consider them as different. Note that NTFS supports POSIX semantics for case sensitivity but this is not the default behavior.

I suspect it is this that is causing the crash, which PR 143 should resolve.

**Comment by abraunegg** [comment]
@dleslie 
Any further update on this issue?

**Comment by abraunegg** [comment]
PR merged

**Comment by dleslie** [comment]
Yes, that worked. Thank-you! 💯
