### ISSUE TITLE
Unhandled Error 412 when uploading modified files to OneDrive Business Accounts

### ISSUE THREAD

**Issue by amelcon-dot** [abraunegg/onedrive#1393]
### Bug Report Details ###
For unknown reasons I got this error in a number of files:
```
Uploading modified file v1/MEGA/upct/bin/V1_amelcon_Local_Mail.txt ...
skipped.
ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 412 (Precondition Failed)
  Error Reason:     ETag does not match current item's value
  Error Timestamp:  2021-04-07T10:49:04
  API Request ID:   d8a52774-cf4c-43d2-868c-52c83a63bb11
  Calling Function: uploadFileDifferences()
```
**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
```
OpenSuse Leap15.2, Linux pcaamelcon 5.3.18-lp152.66-default #1 SMP Tue Mar 2 13:18:19 UTC 2021 (73933a3) x86_64 x86_64 x86_64 GNU/Linux
```
*   Are you using a headless system (no gui) or with a gui installed?
I use onedrive from an xterm command line
*   OneDrive Account Type
Business
*   Did you build from source or install from a package?
OpenSuse Leap15.2 package
*   OneDrive Application Version: Output of `onedrive --version`
onedrive v2.4.10
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
Configuration file successfully loaded
onedrive version                       = v2.4.10
Config path                            = /home/amelcon/.config/onedriveAMELCON
Config file found in config path       = true
Config option 'check_nosync'           = true
Config option 'sync_dir'               = /home/amelcon
Config option 'skip_dir'               = *.aedtresults|*_lib
Config option 'skip_file'              = ~*|.~*|*.tmp|*.aux|*.bbl|*.blg|*.dvi|*.log|*.soc|Thumbs.db*
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = true
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /home/amelcon/logs/onedriveAMELCON/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
```
curl 7.66.0 (x86_64-suse-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1d-fips zlib/1.2.11 libidn2/2.2.0 libpsl/0.20.1 (+libidn2/2.2.0) libssh/0.8.7/openssl/zlib nghttp2/1.40.0
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
*   Is your configured 'sync_dir' a local directory or a network mount point?
local directory
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
```
NAME FSTYPE LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
sda                                                                   
└─sda1
     ext4         0217a526-1173-4764-be10-946d77658553  162.5G    64% /home
sdb                                                                   
├─sdb1
│    swap         a87b22ae-7d55-4a17-a9da-d05a3ba1aefd                [SWAP]
├─sdb2
│    btrfs        376d69ef-2721-418d-919d-44e2d98f4355  811.2M     9% /boot
└─sdb3
     btrfs        39fdcf7c-f171-49b6-b96d-5e7e0199a25d   44.9G    79% /var 
sr0 
```
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
* 
The file system is shared with a Windows machine using SAMBA

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

Error happening on certain files:
```
Uploading modified file v1/MEGA/upct/bin/V1_amelcon_Local_Mail.txt ...
skipped.
ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 412 (Precondition Failed)
  Error Reason:     ETag does not match current item's value
  Error Timestamp:  2021-04-07T10:49:04
  API Request ID:   d8a52774-cf4c-43d2-868c-52c83a63bb11
  Calling Function: uploadFileDifferences()
```
**To Reproduce**
The process to reproduce the error is unknown.
I suspect it is caused by using rclone to upload files, and then conflicts with onedrive on the next
--synchronize operation.
 
**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```
Uploading modified file v1/MEGA/upct/bin/V1_amelcon_Local_Mail.txt ...
skipped.
ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 412 (Precondition Failed)
  Error Reason:     ETag does not match current item's value
  Error Timestamp:  2021-04-07T10:49:04
  API Request ID:   d8a52774-cf4c-43d2-868c-52c83a63bb11
  Calling Function: uploadFileDifferences()
```

Application Log Output:
```
Uploading modified file v1/MEGA/upct/bin/V1_amelcon_Local_Mail.txt ...
skipped.
ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 412 (Precondition Failed)
  Error Reason:     ETag does not match current item's value
  Error Timestamp:  2021-04-07T10:49:04
  API Request ID:   d8a52774-cf4c-43d2-868c-52c83a63bb11
  Calling Function: uploadFileDifferences()
```

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [X] Verbose Log Output from your error
*   [X] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@amelcon-dot 
Please can you test the following PR to resolve this issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1394/head:pr1394
git checkout pr1394
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.11-2-gb1cd5ac` or greater

**Comment by amelcon-dot** [comment]
I am having some problems during compilation, since a library is not found by the linker:
´´´
 dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lphobos2
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
make: *** [Makefile:101: onedrive] Error 1
´´´
The libraries exist in my system:
´´´
/usr/lib64/libphobos2.so
/usr/lib64/libphobos2.so.0.85
/usr/lib64/libphobos2.so.0.85.1
´´´
Anyway, this is not related to onedrive, and it is probably a problem with OpenSuse Leap15.2 setup.
Sorry for the trouble.

**Comment by amelcon-dot** [comment]
I am having a compilation error, since the linker cannot find a library:
```
dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lphobos2
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
make: *** [Makefile:101: onedrive] Error 1
```
However, this library does exist in my system:
```
/usr/lib64/libphobos2.so
/usr/lib64/libphobos2.so.0.85
/usr/lib64/libphobos2.so.0.85.1
```
anyway, this is not related to onedrive, but most certainly to Opensuse Leap15.2 setup.
Sorry for the trouble.

**Comment by abraunegg** [comment]
> I am having a compilation error, since the linker cannot find a library:
> 
> ```
> dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
> /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lphobos2
> collect2: error: ld returned 1 exit status
> Error: linker exited with status 1
> make: *** [Makefile:101: onedrive] Error 1
> ```
> 
> However, this library does exist in my system:
> 
> ```
> /usr/lib64/libphobos2.so
> /usr/lib64/libphobos2.so.0.85
> /usr/lib64/libphobos2.so.0.85.1
> ```
> 
> anyway, this is not related to onedrive, but most certainly to Opensuse Leap15.2 setup.
> Sorry for the trouble.

My only suggestion here is to review https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-opensuse-leap-150 and update / modify as needed for OpenSuSE Leap 15.2

**Comment by amelcon-dot** [comment]
Thanks, I finally managed to compile the new version. I had one package missing: phobos-devel-static

I setup a test file inside the syncing directory, and I can confirm that this is produce by a change in file if using rclone.
With the official version I get:
```
Uploading modified file v1/MEGA/test_onedrive2 ... 
skipped.

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 412 (Precondition Failed)
  Error Reason:     ETag does not match current item's value
  Error Timestamp:  2021-04-08T13:04:46
  API Request ID:   ea99074b-65f4-4edf-b04d-7d002c7f3875
  Calling Function: uploadFileDifferences()
```

With the new compiled version I get:
```
Uploading modified file v1/MEGA/test_onedrive2 ... 
skipped.
Uploading new items of v1/MEGA
Uploading modified file v1/MEGA/test_onedrive2 ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:00      
done.
```

The error does not show up, and the updated file gets finally uploaded. Does this mean that the procedure now could be compatible with rclone?.
Thank you very much.

**Comment by abraunegg** [comment]
@amelcon-dot 
> The error does not show up, and the updated file gets finally uploaded. Does this mean that the procedure now could be compatible with rclone?.

No .. do not use 2 different clients .. pick one.

**Comment by abraunegg** [comment]
@amelcon-dot 
Marking this issue as fixed & will merge the PR into 'master'

**Comment by amelcon-dot** [comment]
I will do so. Thanks for the help.
