### ISSUE TITLE
Feature Request: .onedriveignore files

### ISSUE THREAD

**Issue by maxfrei750** [abraunegg/onedrive#1396]
**Is your feature request related to a problem? Please describe.**
If you have many files/directories to ignore, then doing it in a centralized manner can be cumbersome.

**Describe the solution you'd like**
Support for git-like `.onedriveignore` files, to control files that are ignored during the sync.

**Describe alternatives you've considered**
I guess it might be possible to write a wrapper script, which searches for `.onedriveignore` files and compiles them into a `--skip-file` argument or adds them to the configuration file. However, that's seems a little hacky to me.

**Additional context**
This idea has already been brought up in the past: https://github.com/abraunegg/onedrive/issues/87#issue-345215905

Thanks for your great work.

**Comment by abraunegg** [comment]
@maxfrei750 
> If you have many files/directories to ignore, then doing it in a centralized manner can be cumbersome

This is why 'sync_list' supports wildcards to simplify this action.

 > Support for git-like `.onedriveignore` files, to control files that are ignored during the sync.

The other option here is to use `.nosync` and `--check-for-nosync` to skip the sync of a particular directory.

As there are already options to ignore files, this will not be implemented. This being said, PR's welcome.

**Comment by maxfrei750** [comment]
@abraunegg Classical case of RTFM. Thanks for pointing me in the right direction. `.nosync` is basically what I was looking for.
