### ISSUE TITLE
Fix skip_dir documentation

### ISSUE THREAD

**Issue by folknor** [abraunegg/onedrive#1398]
I found https://github.com/abraunegg/onedrive/issues/810 which asks

> Is it possible to add a configuration like skip_dir="**/target", in order to skip syncing directories like a/target or a/b/target?

and @abraunegg replies
> This is how the client already operates.

But https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#skip_dir says `Important: Entries under skip_dir are relative to your sync_dir path.`. I'm guessing `USAGE.md` is incorrect.

This might seem like a minor thing, but it was very important for me and it took me a long time to find out.

**Comment by abraunegg** [comment]
@folknor 
This is not a bug - should be a Discussion. Please follow the correct support process.

> This might seem like a minor thing, but it was very important for me and it took me a long time to find out. 

If you feel that the documentation is inaccurate, feel free to submit a PR to correct the documentation.
