### ISSUE TITLE
Add support for ARM processors

### ISSUE THREAD

**Issue by Boia11** [abraunegg/onedrive#14]
Hi!
It's possible to convert from DMD to GDC (or LDC) for support:

- armhf
- arm64 (aarch64)

[https://wiki.dlang.org/Compilers#Comparison](https://wiki.dlang.org/Compilers#Comparison)

**Comment by abraunegg** [comment]
Within the Makefile you can specify what compiler to use:
```
DC = dmd
```

Feel free to locally modify this and use GDC or LDC to compile, however this project will only test compile using the DMD reference compiler from https://dlang.org/download.html

**Comment by abraunegg** [comment]
That would be the place to do it - what values to use I cannot say as it is not being tested or checked.

**Comment by abraunegg** [comment]
@rapucha 
Which relevant bug are you talking about here? Are you meaning this comment: https://github.com/skilion/onedrive/issues/325#issuecomment-377553097 ?

**Comment by rapucha** [comment]
The whole thread for the bug is of some relevance, and the final comment has the working solution.

**Comment by abraunegg** [comment]
Can you provide the dependencies you installed on Raspbian Stretch Lite so I can add this to the readme?

**Comment by abraunegg** [comment]
@Boia11 
Whilst this issue was closed, can you help validate the below proposed changes that help articulate how to build on ARM architecture?

https://github.com/abraunegg/onedrive/blob/update-readme-for-i686-and-ARM-support/README.md

**Comment by rapucha** [comment]
I followed the slightly altered instruction from the spoken comment:

```
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libsqlite3-dev
wget https://github.com/ldc-developers/ldc/releases/download/v1.10.0/ldc2-1.10.0-linux-armhf.tar.xz
tar -xvf ldc2-1.10.0-linux-armhf.tar.xz
git clone https://github.com/skilion/onedrive.git
cd onedrive
make DC=/home/pi/ldc2-1.10.0-linux-armhf/bin/ldmd2
sudo make install
```

Verified platforms, all running Raspbian Stretch Lite (2018-06-27):
Raspberry Pi (original), ARMv6 CPU (will re-check) -- does not work
Raspverry Pi 2 model B, ARMv7 CPU -- works

I also plan to verify in few days:
Raspberry Pi Model B+, ARMv6 
Raspberry Pi 3, ARMv8

**Comment by abraunegg** [comment]
The only issue here is your cloning from `git clone https://github.com/skilion/onedrive.git` - which has known defects

**Comment by abraunegg** [comment]
If you can comment on this pull request https://github.com/abraunegg/onedrive/pull/83 the hardware that works / does not work that would be great. I can then add that to the readme

**Comment by abraunegg** [comment]
Resolved by https://github.com/abraunegg/onedrive/commit/e07ee71ad230fe0fb314a8149f145323455877c4
