### ISSUE TITLE
--synchronize or --monitor missing from your command options or use --help for further assistance

### ISSUE THREAD

**Issue by kcdah** [abraunegg/onedrive#140]
### --synchronize or --monitor missing from your command options or use --help for further assistance

No OneDrive sync will be performed without either of these two arguments being present
###

I originally had the skillion version, but was running into issues (onedrive command failed, was getting a key error with lastModifiedDate, files kept automatically being renamed). I purged onedrive, removed files, removed make, and then started fresh with instructions here. After installation, first run gave the following error pasted above.

**onedrive v2.1.1-5-gbdc33e6:**
- OS: Linux keith-GP62-2QE 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Application version: onedrive v2.1.1-5-gbdc33e6:
- OneDrive Account Type: Personal use
- DMD or LDC compiler version DMD64 D Compiler v2.081.2

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. Purged, deleted, & removed make files from skillion
2. Followed Dependencies Ubuntu/Debian steps
3. Followed Configuration Steps
4. Ran account, connected URL
5. Ran `onedrive` for the first time and get the pasted error

onedrive help still seems to imply I have these options... `onedrive --help`
Usage: onedrive [OPTION]...

no option        No sync and exit
       --check-for-nomount Check for the presence of .nosync in the syncdir root. If found, do not perform sync.
                 --confdir Set the directory used to store the configuration files
        --create-directory Create a directory on OneDrive - no sync will be performed.
   --destination-directory Destination directory for renamed or move on OneDrive - no sync will be performed.
             --debug-https Debug OneDrive HTTPS communication.
-d              --download Only download remote changes
             --local-first Synchronize from the local directory source first, before downloading changes from OneDrive.
                  --logout Logout the current user
-m               --monitor Keep monitoring for local and remote changes
        --no-remote-delete Do not delete local file 'deletes' from OneDrive when using --upload-only
             --print-token Print the access token, useful for debugging
                  --resync Forget the last saved state, perform a full sync
        --remove-directory Remove a directory on OneDrive - no sync will be performed.
        --single-directory Specify a single local directory within the OneDrive root to sync.
           --skip-symlinks Skip syncing of symlinks
        --source-directory Source directory to rename or move on OneDrive - no sync will be performed.
                 --syncdir Set the directory used to sync the files that are synced
             --synchronize Perform a synchronization
             --upload-only Only upload to OneDrive, do not sync changes from OneDrive locally
-v               --verbose Print more details, useful for debugging
                 --version Print the version and exit
-h                  --help This help information.

Thanks!

**Comment by abraunegg** [comment]
You need to use a command that looks like this:

```
onedrive --synchronize <plus any other options you want to use like --verbose>
```

or

```
onedrive --monitor <plus any other options you want to use like --verbose>
```
