### ISSUE TITLE
Push docker images to docker hub / github container registry

### ISSUE THREAD

**Issue by felbinger** [abraunegg/onedrive#1400]
It would be nice if you share the build images for all architectures and flavors, checkout the repository of https://github.com/MarcelCoding/onedrive-docker
He added a github action to build and push these images to https://ghcr.io and https://hub.docker.com

**Comment by abraunegg** [comment]
@felbinger 
Not an issue, should be a discussion. 

Please follow the correct support process as detailed here:
* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
