### ISSUE TITLE
Authorization link for business account returns 'The signed-in user is not assigned to a role for the application'

### ISSUE THREAD

**Issue by sitnarf** [abraunegg/onedrive#1402]
### Bug Report Details ###
**Describe the bug**
Cannot register the business account from my university (KU Leuven). 

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`:  
**Linux sitnarf-zb 5.11.0-051100rc4-generic #202101180234 SMP Mon Jan 18 02:36:59 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.10**
*   Are you using a headless system (no gui) or with a gui installed? **no gui**
*   OneDrive Account Type: **Business**
*   Did you build from source or install from a package? **Installed from source and also tested the pre-build for Ubuntu**
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
**DMD64 D Compiler v2.096.0**

*   OneDrive Application Version: Output of `onedrive --version`:  **v2.4.11**
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
onedrive version                       = v2.4.11
Config path                            = /home/sitnarf/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/sitnarf/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false**
```
*   Provide the version of curl you are using: Output of `curl --version`: **curl 7.68.0 **
*   Is your configured 'sync_dir' a local directory or a network mount point? **Local**
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` : **ext4**
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time:
**I am the owener, but there is a folder that I shared with few another accounts in the same institution**

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. Run `onedrive --monitor`
```
Configuring Global Azure AD Endpoints
Authorize this app visiting: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d50ca740-c83f-4d1b-b616-12c519384f0c&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.Read.All%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
```
3. Opening a link: ![image](https://user-images.githubusercontent.com/289991/114407400-a29de580-9ba8-11eb-8ea0-daa69fb161ab.png)
4. Entering my univrsity login: ![image](https://user-images.githubusercontent.com/289991/114407595-d547de00-9ba8-11eb-9f90-78ba79922dde.png)
5. The page is redirected to: 
```
https://login.microsoftonline.com/common/oauth2/nativeclient?error=interaction_required&error_description=AADSTS50105%3a+The+signed+in+user+%27%7bEmailHidden%7d%27+is+not+assigned+to+a+role+for+the+application+%27d50ca740-c83f-4d1b-b616-12c519384f0c%27(OneDrive+Client+for+Linux).%0d%0aTrace+ID%3a+65603499-8018-466e-ad59-0c722fd45900%0d%0aCorrelation+ID%3a+7221f6df-f5a2-4940-bb4a-183c6f46f0df%0d%0aTimestamp%3a+2021-04-12+14%3a05%3a32Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d50105
```
![image](https://user-images.githubusercontent.com/289991/114407851-23f57800-9ba9-11eb-833c-3592c0910898.png)

**Note**: Logging in to online version or using OneDrive on Windows with these credentials works!

**Comment by abraunegg** [comment]
@sitnarf 
This is not an error or bug with this application - sorry. This is an issue with Azure AD.

The URL response from OneDrive includes the error you are getting:
* AADSTS50105
* The signed in user (email address) is not assigned to a role for the application
* Further details: https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50105-user-not-assigned-role#:~:text=Error%20AADSTS50105%20%2D%20The%20signed%20in,a%20role%20for%20the%20application.

What this means is, the Application ID that this client uses, your OneDrive Business Account has not been authorised to use.

The *only* way to fix this is speak to your University Azure AD administration team and get them to authorise the use of this application.
