### ISSUE TITLE
Can't access shared folders

### ISSUE THREAD

**Issue by ukreddy-erwin** [abraunegg/onedrive#1424]
Able to access folders created by the account logged in.
But, can't access the shared folders by someone else.

Let's say, I have a builds folder shared by team.
Which I have full rights.
But can't see here.

**Comment by abraunegg** [comment]
@ukreddy-erwin 
Please follow the correct support process as detailed here:
* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

Please also be more clear with your post as it is unclear what you are asking
