### ISSUE TITLE
New local folder content is not uploaded to OneDrive when using --upload-only & --remove-source-files

### ISSUE THREAD

**Issue by SylvainLaugie** [abraunegg/onedrive#1427]
### Bug Report Details ###

When I create a local folder, put files in it, and try to sync with options --upload-only & --remove-source-files, the folder is created on OneDrive but the files in it are ignored.

**Application and Operating System Details:**
*   Debian 10.9 : `Linux *hostname* 4.19.0-5-cloud-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux`
*   No GUI
*   OneDrive **Personal**
*   Built **from source on master b7eedbd**
*   Built with: **DMD64 D Compiler v2.096.0**
*   OneDrive Application Version: **onedrive v2.4.11-5-gb7eedbd**
*   OneDrive Application Configuration:
```
Configuration file successfully loaded
onedrive version                       = v2.4.11-5-gb7eedbd
Config path                            = /root/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /root/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
Myfolder/*
Business Shared Folders configured     = false
```
*   curl version: **curl 7.64.0**
*   sync_dir is a **local directory** (no network mount)
*   Partition format type: **ext4**

**To Reproduce**

1. Create a subfolder in Myfolder : `cd ~/OneDrive/Myfolder && mkdir subfolder`

2. Create a file in the newly created subfolder : `cd subfolder && echo 'this is the new file' > newfile`

3. Launch onedrive with --upload-only & --remove-source-files : `/usr/local/bin/onedrive --synchronize --verbose --upload-only --remove-source-files`

4. Observe that `subfolder` is created in OneDrive but `newfile` is **not** uploaded, it is ignored

```
Uploading new items of ~/OneDrive
OneDrive Client requested to create remote path: ./Myfolder/subfolder
The requested directory to create was not found on OneDrive - creating remote directory: ./Myfolder/subfolder
Successfully created the remote directory ./Myfolder/subfolder on OneDrive
Skipping uploading this new file as parent path is not in the database: ./Myfolder/subfolder/newfile
```

**Debug Log Extract**

```
OneDrive Client requested to create remote path: ./Myfolder/subfolder
[DEBUG] Attempting to query OneDrive for this path: ./Myfolder/subfolder
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/drives/xxxxxxxxxxxxxxxx/root:/.%2FMyfolder%2Fsubfolder?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size
[DEBUG] response = onedrive.getPathDetails(path); generated a OneDriveException
The requested directory to create was not found on OneDrive - creating remote directory: ./Myfolder/subfolder
[DEBUG] Skipping adding to database as --upload-only & --remove-source-files configured
Successfully created the remote directory ./Myfolder/subfolder on OneDrive
[DEBUG] Checking file: ./Myfolder/subfolder/newfile
[DEBUG] skip_file evaluation for: /Myfolder/subfolder/newfile
[DEBUG] Evaluation against 'sync_list' for this path: Myfolder/subfolder/newfile
[DEBUG] [S]exclude        = false
[DEBUG] [S]excludeMatched = false
[DEBUG] Evaluation against 'sync_list' entry: Myfolder/*
[DEBUG] Evaluation against 'sync_list' result: wildcard pattern match
[DEBUG] [F]exclude        = false
[DEBUG] [F]excludeMatched = false
[DEBUG] Evaluation against 'sync_list' final result: included for sync
[DEBUG] File upload destination is a shared folder - the upload may fail if not enough space on OneDrive ..
Skipping uploading this new file as parent path is not in the database: ./Myfolder/subfolder/newfile
```

**Comment by abraunegg** [comment]
@SylvainLaugie 
This is most likely an impact from this issue https://github.com/abraunegg/onedrive/issues/1382 & the fix .. because you did not like that the DB was storing the data, and checking the DB data ... thus the parent is not in the database, thus, the file is not in the DB.

**Comment by abraunegg** [comment]
@SylvainLaugie 

Please can you test the following PR to resolve this issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1399/head:pr1437
git checkout pr1437
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.11-6-gdac7e23` or greater

**Comment by SylvainLaugie** [comment]
Hi @abraunegg 

Looks good to me, new folder is created and files in it are uploaded to OneDrive now.

Thanks a lot !

**Comment by abraunegg** [comment]
@SylvainLaugie 
Thanks for confirming the fix, will merge this into 'master'
