### ISSUE TITLE
Shared folders not visible

### ISSUE THREAD

**Issue by ukreddy-erwin** [abraunegg/onedrive#1431]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
Shared folders are not visible to sync.

**Application and Operating System Details:**
*   Ubuntu 18 and 20 both with same issue.
*   Both I tried in Headless and GUI syste,
*   OneDrive Account Type- Onedrive for Business,work account
*   Did you build from source or install from a package? Both make same impact

When I sync my account using this application, only the created by me or in my account or visible. But, folders shared by my team members with me, even I am having full access to those folders, are not visible with this command line tool.

Please guide me how to access shared with me folders.

**Comment by abraunegg** [comment]
@ukreddy-erwin 
Please can you detail things a little more - as this is really unclear.

Please can you provide screen shots of what you are atempting to do. Provide a screen shot of the 'shared folder' that you are trying to sync from the OneDrive Web UI interface, and the output when attempting to configure OneDrive Shared Business Folders as per https://github.com/abraunegg/onedrive/blob/master/docs/BusinessSharedFolders.md

Example:

What does the output of this command provide:
```
onedrive --list-shared-folders
```

Does this list the shared folder?

Or ... are you trying to sync a SharePoint Library / Team Site? If yes - you need to reconfigure your client following these directions: https://github.com/abraunegg/onedrive/blob/master/docs/SharePoint-Shared-Libraries.md

Please can you update your issue ticket with more details - as previously requested - as you are missing all the details needed to correctly support you.

**Comment by ukreddy-erwin** [comment]
onedrive --list-shared-folders
Unrecognized option --list-shared-folders
Try 'onedrive -h' for more information

**Comment by abraunegg** [comment]
@ukreddy-erwin 
You have installed most likely an unknown version..

What does:
```
which onedrive
```
```
find / | grep onedrive
```

Then what is the 'onedrive --version' output for each binary that the above commands find.

The `--list-shared-folders` was added in v2.4.3 ... so if your version does not support that - you are running a *very* old version.

You need to update your client, delete the old clients you have installed.

**Comment by ukreddy-erwin** [comment]
I have upgraded now.
For testing, I ran the installation on a new machine and configure my credentials by running onedrive without parameters.

(ldc-1.26.0)uday@test1:~/onedrive$ onedrive --list-shared-folders
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...

Listing available OneDrive Business Shared Folders:

No OneDrive Business Shared Folders were returned

But there are folders shared with me,

**Comment by abraunegg** [comment]
@ukreddy-erwin 
Are these shared folders shared by people from within your organisation or *external* to your organisation?

Please provide a screen shot of the OneDrive Web UI showing these shared folders.

**Comment by ukreddy-erwin** [comment]
within the organization

**Comment by abraunegg** [comment]
@ukreddy-erwin 
Please provide a screen shot of the OneDrive Web UI showing these shared folders.

If the application is responding with:
```
No OneDrive Business Shared Folders were returned
```

This means no data was provided by the API for the query. This means either:
* There are no shared folders with you
* You do not have the right API permissions

Try:
```
onedrive --logout
```

and re-authenticate - given that you had old client versions - the access scopes may not be correct. Find and delete *all* onedrive binaries that are less that the current release / master version.

**Comment by ukreddy-erwin** [comment]
Folders are there.

**Comment by abraunegg** [comment]
@ukreddy-erwin 
Please follow what I am asking:

1. Provide screen shots
2. Perform a re-authentication
3. Provide debug logs as per support requirements

**Comment by ukreddy-erwin** [comment]
Even shared folders with "Add shortcut to my files" option selected also not showing.

**Comment by abraunegg** [comment]
@ukreddy-erwin 
I have tried to help you - however you are not providing the information requested, thus it is difficult to support you any further in trying to work out what is wrong.
