### ISSUE TITLE
Upgrading to latest version

### ISSUE THREAD

**Issue by mbaldassarri** [abraunegg/onedrive#1435]
It would be nice to have documentation about upgrating onedrive to latest release version.
Should I re-clone it and re-compile it again? Or maybe using 'apt' ?

**Comment by abraunegg** [comment]
@mbaldassarri 
There is documentation - please read https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md

Closing issue as this should have been a discussion.

Please follow the correct support process as detailed here:
* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
