### ISSUE TITLE
Syncing Shared Folders From Other User Accounts in The Same Organization

### ISSUE THREAD

**Issue by adam2392** [abraunegg/onedrive#1443]
Hi 

Sorry for posting in a closed issue. Just reposting here based on https://github.com/abraunegg/onedrive/issues/459#issuecomment-833822849

I ran the command `onedrive --list-shared-folders`, and then I get;

```
Error: Unsupported account type for listing OneDrive Business Shared Folders
```

Do you happen to know if that's a result of my institutions OneDrive business account, or something config?

**Comment by abraunegg** [comment]
@adam2392 
Please follow the correct process - this is *not* an issue, this is a question. Closing issue as this should have been a discussion.

Please follow the correct support process as detailed here:

https://github.com/abraunegg/onedrive#have-a-question
https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
