### ISSUE TITLE
Sync issues on file delete inside subfolders

### ISSUE THREAD

**Issue by aseemit** [abraunegg/onedrive#1454]
### Bug Report Details ###
**Describe the bug**
Contents inside subfolders do not get deleted even after they have been deleted on Onedrive cloud/other hosts.

**Application and Operating System Details:**
*   OS: CentOS 8.3 
     4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Apr 8 19:01:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?
    - N/A
*   OneDrive Account Type
     - Business
*   Did you build from source or install from a package?
     - Built from source
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
     - DMD64 D Compiler v2.096.0
*   OneDrive Application Version: Output of `onedrive --version`
     - onedrive v2.4.11
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
Configuration file successfully loaded
onedrive version                       = v2.4.11
Config path                            = /home/<user>/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/<user>/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 30
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                =  /home/log/<log>
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
     - curl 7.61.1
*   Is your configured 'sync_dir' a local directory or a network mount point?
     - Local Directory
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
     - LVM - xfs
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
   - Folder is not shared. Onedrive is configured across multiple operating systems/platforms

NO ERRORS ARE REPORTED. SYNC WORKS PROPERLY. JUST FAILS TO SEE THAT THE FILE WAS DELETED.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  On any platform or cloud, upload a file/folder inside a subdirectory of Onedrive
2.  Make sure Onedrive linux client is synced by navigating to the location
3.  Delete the file from Onedrive Cloud or any other host
4.  File not deleted on the Linux host.

Application Log Output:
The file hasn't changed.

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Application and Operating System Details provided in full
*   [X] Reproduction steps (if applicable)
*   [-] Verbose Log Output from your error
*   [-] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@aseemit 
As per the [discussion](https://github.com/abraunegg/onedrive/discussions/1453) - please provide your evidence of what is going on including verbose logging and verbose debug logging showing that the client *is* checking OneDrive, getting the deleted change and not properly processing the delete event. These logs help then identify *if* there is an issue and how to replicate if required to fix any issue - if there is an issue. This is *why* these are required.

You also say that this is occurring when you have multiple clients connected. Ensure you also do not have 'rclone' or anything else also configured as these impact the client operations.

**Comment by aseemit** [comment]
The reason I didn't include the logs were because there are no events generated on the Linux client when the file is deleted on OneDrive[cloud]. 

However, if a file on the root[OneDrive] is deleted it propagates without any issues. 

I mentioned the steps to reproduce the issue. If you or anyone else can test it out on any Linux host (v2.4.11) it should be reproducible. 

Create a subfolder in Onedrive cloud create/copy a file in that folder. Let it sync on Linux client. Delete the file from the cloud. If this deletes the file on your Linux client then I can debug further which is why I asked in Q/A before creating an issue.

**Comment by abraunegg** [comment]
@aseemit 
As per previously requested, please provide verbose logs and verbose debug logs of the issue you are claiming as per the support process.

**Comment by abraunegg** [comment]
@aseemit 
I am also unable to reproduce this issue you are claiming - local files, in sub folders, are correctly deleted when the file has been removed from OneDrive online:

![Capture](https://user-images.githubusercontent.com/4956234/118202339-0b74c800-b49d-11eb-8d62-4b4fa1fe001b.JPG)


```
(dmd-2.096.1)[alex@centos-8-onedrive-test onedrive]$ ./onedrive --monitor --verbose
Using 'user' Config Dir: /home/alex/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Application version: v2.4.11-7-gb0771f7
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1092981381841
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Monitor directory: .
Monitor directory: ./SpeedTest
Starting a sync with OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1092981381841
Number of items from OneDrive to process: 4
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Processing Document2.docx
The file has not changed
Processing SpeedTest
The directory has not changed
Processing SpeedTest/Bandwidth measurement_ Speedtest.net.csv
The file has not changed
Processing SpeedTest/Bandwidth measurement_ Speedtest.net.xlsx
The file has not changed
Processing SpeedTest/automated_speedtest.log
The file has not changed
Uploading new items of ~/OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1092981381841
Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1092981381841
Number of items from OneDrive to process: 2
Trying to delete item SpeedTest/automated_speedtest.log
Deleting item SpeedTest/automated_speedtest.log     <-- Processing the OneDrive event to delete the local file after removed online
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Processing Document2.docx
The file has not changed
Processing SpeedTest
The directory has not changed
Processing SpeedTest/Bandwidth measurement_ Speedtest.net.csv
The file has not changed
Processing SpeedTest/Bandwidth measurement_ Speedtest.net.xlsx
The file has not changed
[M] Item deleted: SpeedTest/automated_speedtest.log <-- Event triggered because of deletion event from local disk
Item cannot be deleted from OneDrive because it was not found in the local database <-- Event triggered because of deletion event from local disk
Uploading new items of ~/OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1092981381841
Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1092981381841
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Processing Document2.docx
The file has not changed
Processing SpeedTest
The directory has not changed
Processing SpeedTest/Bandwidth measurement_ Speedtest.net.csv
The file has not changed
Processing SpeedTest/Bandwidth measurement_ Speedtest.net.xlsx
The file has not changed
Uploading new items of ~/OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1092981381841
Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1092981381841
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Processing Document2.docx
The file has not changed
Processing SpeedTest
The directory has not changed
Processing SpeedTest/Bandwidth measurement_ Speedtest.net.csv
The file has not changed
Processing SpeedTest/Bandwidth measurement_ Speedtest.net.xlsx
The file has not changed
Uploading new items of ~/OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1092981381841
Sync with OneDrive is complete
^CGot termination signal, shutting down db connection
```

**Comment by aseemit** [comment]
Thanks for testing this. I will compare the differences based on the output you posted and see if that helps identify what is happening in my test scenario. 

It was just weird why it works fine on the root folder. 

I'll also try a clean instance just to make sure there aren't any old artifacts.

**Comment by aseemit** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/26338922/118306814-e2adfc00-b4b7-11eb-8e6e-a722d3a54619.png">

So all operations except delete are working properly.

**Comment by aseemit** [comment]
I think I found a solution to this. It was related to the /children setting for NCD deployment. As soon as I recompiled without setting NationaclCloudDeployment in main.d for the endpoint that we use, everything works as expected.

**Comment by abraunegg** [comment]
@aseemit 
So you *never* raised the discussion or issue citing you were:
* Using NCD deployments
* Modifying the code to make it work for you and your NCD deployment

A working NCD deployment takes configuration file modification to set:
* Correct location for authentication
* API endpoints via tenant ID

Read https://github.com/abraunegg/onedrive/blob/master/docs/national-cloud-deployments.md on *how* to configure this properly without you having to modify the code.

Next time you open a discussion or issue - be upfront and honest with *what* you have done - code changes, configuration + what you are trying to achieve so that you dont waste other folk time with them chasing ghosts.
