### ISSUE TITLE
OneDrive it self don't sync anymore after adding a Sharepoint Folder

### ISSUE THREAD

**Issue by pepperbilly** [abraunegg/onedrive#1458]
Hi

After adding a SharePoint Folder in ~/.config/onedrive/config

`sync_dir="~/Local_Sharepointfolder"
drive_id="thedriveid"
`

My default added OneDrive Folder is not syncing anymore. Only the SharePoint Folder will sync.
As soon as i remove the Sharepoint Folder from the config File and run

`onedrive --synchronize --resync`

the OneDrive Folder will sync again.

Any Idea of what i did wrong?

thanks for your Help

Sascha

Ubuntu 20.04.2 LTS
Release:	20.04

**Comment by abraunegg** [comment]
@pepperbilly 
Please follow the correct support process as detailed here:
* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
