### ISSUE TITLE
504 and 502 errors when uploading a large (>100MB) file

### ISSUE THREAD

**Issue by pitsi** [abraunegg/onedrive#1462]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.
Unfortunatelly, I am not running the latest version of the app and I can not build the new one because I just rely on what my distro can offer via its repo.

### Bug Report Details ###
**Describe the bug**
As mentioned in the title and seen in the logs below, I get 504 and 502 errors after some time. Also, after MANY retries, the app mentions that the file was uploaded successfully, but it is not (I check it from onedrive's page). What is even more weird is that the app keeps hogging the network's upload speed even after it finished/stopped/crashed! More info at additional context.

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
	Debian testing x64 and `Linux x 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed?
	Gui installed.
*   OneDrive Account Type
	Regular/free, the one you get after creating an email account at microsoft.
*   Did you build from source or install from a package?
	Installed from the distro's repo.
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
	Not applicable
*   OneDrive Application Version: Output of `onedrive --version`
```
$ onedrive --version
onedrive v2.4.10-1
```
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
$ onedrive --display-config 
Configuration file successfully loaded
onedrive version                       = v2.4.10-1
Config path                            = /home/x/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/x/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = true
Config option 'no_remote_delete'       = true
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
*   Is your configured 'sync_dir' a local directory or a network mount point?
	Local
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
	Not applicable.
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f`
	Ext4 and
```
$ lsblk -f
NAME   FSTYPE FSVER LABEL                     UUID                                 FSAVAIL FSUSE% MOUNTPOINT
sda                                                                                               
├─sda1 ntfs         Δεσμευμένο από το σύστημα 32F41EC2F41E87ED                                    
├─sda2 ntfs                                   CE9C25A29C2585D5                                    
└─sda3 ext4   1.0                             76f6823f-e242-43d2-8a04-3d5ea1626f99    9.2G    60% /
```

*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
	No to all.
	
**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Have a slow internet connection like me (12Mps down, 1Mbps up) and a rather big file for upload. For the example below I used a ~150MB file.
2.  Configure onedrive like so, because I only want it to send stuff to my onedrive storage and not receive.
```
$ cat .config/onedrive/config 
upload_only = "true"
no_remote_delete = "true"
```
3.  Run `onedrive --synchronize` and wait
4.  Once the app crashes and the terminal gets me back to the prompt, it continues to hog the upload speed for several minutes, as seen in the screenshot below. So I assume it just keeps running for a while after it crashes.

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```
$ onedrive --synchronize --verbose
Using 'user' Config Dir: /home/user/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/user/OneDrive
Application version: v2.4.10-1
Account Type: personal
Default Drive ID: (removed)
Default Root ID: (removed)
Remaining Free Space: 30542813145
Fetching details for OneDrive Root
OneDrive Root exists in the database
Trying to restore the upload session ...
Continuing the upload session ...
Uploading   5% |ooo                                     |   ETA   00:00:00      
Fragment upload failed - received an exception response from OneDrive

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 504 (Gateway Timeout)
  Calling Function: upload()

Retrying fragment upload
Retry to upload fragment failed

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 504 (Gateway Timeout)
  Calling Function: upload()

File upload session failed - invalid response from OneDrive
ERROR: An error was returned from OneDrive and the resulting response is not a valid JSON object
ERROR: Increase logging verbosity to assist determining why.
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Processing (removed directory)
The directory has been deleted locally
Skipping remote directory delete as --upload-only & --no-remote-delete configured
Processing test10Mb.db
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Processing a.png
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Processing b.png
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Processing c.png
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Processing d.png
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Uploading new items of ~/OneDrive
Uploading new file ./bigfile.7z ... 
Uploading   5% |ooo                                     |   ETA   00:00:00      
Fragment upload failed - received an exception response from OneDrive

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 504 (Gateway Timeout)
  Calling Function: upload()

Retrying fragment upload
Retry to upload fragment failed

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 504 (Gateway Timeout)
  Calling Function: upload()

File upload session failed - invalid response from OneDrive
```

**Screenshots**
Screenshot of nethogs. The reason is explained above.
![2021-05-16-132234_816x460_scrot](https://user-images.githubusercontent.com/5880037/118394445-7bc24b80-b64d-11eb-9477-131ac3b60156.jpg)

**Additional context**
The png and db files that appear in the log were all uploaded successfully last time onedrive was ran. The db file, as mentioned in its name, was 10MB and all the png files were 10-15MB in total. The new file, bigfile.7z, is ~150MB big and it can not be sent anywhere for further investigation because it contains data about a health issue I had. 
Also, there is no debug log sent, only the verbose one mentioned here.

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output from your error
*   [ ] Debug Log generated and submitted

**Comment by pitsi** [comment]
I just tried the upload again and it now says that the 7z file is already there...
```
$ onedrive --synchronize --verbose
Using 'user' Config Dir: /home/user/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/user/OneDrive
Application version: v2.4.10-1
Account Type: personal
Default Drive ID: (removed)
Default Root ID: (removed)
Remaining Free Space: 30378587225
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Processing (removed directory)
The directory has been deleted locally
Skipping remote directory delete as --upload-only & --no-remote-delete configured
Processing test10Mb.db
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Processing a.png
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Processing b.png
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Processing c.png
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Processing d.png
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Processing bigfile.7z
The file has not changed
Uploading new items of ~/OneDrive
```
And it really is, I checked it from the webpage. I also moved the png files in a new folder, thus the messages for remote "deletion".
Can I assume that the app keeps uploading even when it is not running in the foreground? It definitely does not run as a service, because debian does not enable a systemd service for it, although it does provide one.
```
$ dpkg -L onedrive | grep systemd
/lib/systemd
/lib/systemd/system
/lib/systemd/system/onedrive@.service
/usr/lib/systemd
/usr/lib/systemd/user
/usr/lib/systemd/user/onedrive.service

$ systemctl status onedrive
Unit onedrive.service could not be found.
```

**Comment by abraunegg** [comment]
@pitsi 
> Installed from the distro's repo

You are using unsupported software. Only the current release or greater is supported. The v2.4.10 client has bugs and issues that has been fixed. You need to uninstall the package and build from source.

To get the Debian package updated, you need to contact the package maintainer. See:

* https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#important-note
* https://packages.debian.org/search?keywords=onedrive
