### ISSUE TITLE
Unable to set rate limit

### ISSUE THREAD

**Issue by Lobout** [abraunegg/onedrive#1463]
Fedora Core 34, when trying to use the rate_limit option it indicates there is an invalid config.

**Comment by abraunegg** [comment]
@Lobout 
The Fedora packages are not current and are *many* releases behind. You need to contact the package maintainer to update the package. See: 
* https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#important-note
* https://koji.fedoraproject.org/koji/packageinfo?packageID=26044
