### ISSUE TITLE
client uploads files with extended filename

### ISSUE THREAD

**Issue by Grimmwicht** [abraunegg/onedrive#1464]
Hi folks,

I'm using this onedrive client on a Onedrive Business, which is used by many people. Sometimes ago some strange files were discovered – duplicates with an added -ze65 at the filename, which is the name of my machine.

I watched this since, but can't find a cause for this behaviour. This seems to happen to random files. First, the client reports a download of a changed file (correct, changed by someone other), later in a second step, it says „Uploading modified file ... skipped” (which is bollocks, because I didn't touch this file), and third, it uploads this file as filename-ze65.extension.

I would love to get some hints, why this happens – mostly the client works fine as expected. Thanks in advance.

**Comment by abraunegg** [comment]
@Grimmwicht 
Closing this issue as this should have been a discussion. Please follow the correct support process as detailed here:
* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
