### ISSUE TITLE
Enable delay before trying to upload new/changed files

### ISSUE THREAD

**Issue by ajgringo619** [abraunegg/onedrive#1475]
**Is your feature request related to a problem? Please describe.**
When monitoring changes, files that are being downloaded/copied/moved throw errors as they change.

**Describe the solution you'd like**
An adjustable delay, so that the service will "wait" for the changes to complete before trying to update.

**Describe alternatives you've considered**
For downloads, I've created a separate, non-syncing directory.

**Additional context**

**Comment by abraunegg** [comment]
@ajgringo619 
> An adjustable delay, so that the service will "wait" for the changes to complete before trying to update.

The solution currently *does* wait for changes to complete before performing updates. It appears that you are asking for a work around for a potential bug - which has never been described or articulated before.

Please follow the correct support process in reporting a bug.
