### ISSUE TITLE
File corruption

### ISSUE THREAD

**Issue by MarcelCoding** [abraunegg/onedrive#1477]
### Bug Report Details ###
**Describe the bug**
If onedrive is downloading files. And I shutdown the pc and a file is not fully downloaded. If I start the pc again onedrive is uploading the corrupted file because it is not the same as on the server. 

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output: `Linux pc-marcel 5.8.0-53-generic #60~20.04.1 Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed? no
*   OneDrive Account Type personal (office 365)
*   Did you build from source or install from a package? (ubuntu ppa - http://ppa.launchpad.net/yann1ck/onedrive/ubuntu)
*   OneDrive Application Version: Output: `onedrive v2.4.10-0~202102221319~ubuntu20.04.1`
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
Configuration file successfully loaded
onedrive version                       = v2.4.10-0~202102221319~ubuntu20.04.1
Config path                            = /home/marcel/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /media/marcel/Daten/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
!Nistkasten
*
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
*   Is your configured 'sync_dir' a local directory or a network mount point? local
*   If *not* local, provide all the mountpoints in your system: Output of: `mount` `/dev/sdb2 on /media/marcel/Daten type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)
` And to much more
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` ntfs
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
It is shared with Windows. (I tested this Bugs only with Linux.)

**To Reproduce**
see description

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [ ] Verbose Log Output from your error
*   [ ] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@MarcelCoding 
> If onedrive is downloading files. And I shutdown the pc and a file is not fully downloaded. If I start the pc again onedrive is uploading the corrupted file because it is not the same as on the server.

Thanks for this bug report ... it is an interesting scenario .. however
```
onedrive version                       = v2.4.10-0~202102221319~ubuntu20.04.1
```

You are running an obsolete version which is unsupported, and the version you are running does contains defects which have been fixed. Additionally, because you are using Ubuntu PPA package, you are impacted by this issue as well - https://github.com/abraunegg/onedrive/issues/1274

Steps for you to complete:
1. Uninstall the PPA package & ensure all traces are removed
2. Build from source and replicate the issue using 'master'
