### ISSUE TITLE
Stuck "Processing X OneDrive items to ensure consistent local state"

### ISSUE THREAD

**Issue by eraguzin-bnl** [abraunegg/onedrive#1479]
### Bug Report Details ###
**Describe the bug**
Onedrive used to work, but no longer performs any synchronization. When I run --synchronization --verbose, I get repeated messages about Processing X OneDrive items to ensure consistent local state. The number fluctuates, never consistently going down. I tried using `sudo apt-get remove onedrive` and reinstalling it, but I still see the same behavior. Files that I add locally to this machine don't get uploaded to the Onedrive sharepoint.com website, and new files I add there get immediately downloaded on my other machines, but not this one.

**Application and Operating System Details:**
*   `Ubuntu 20.04: Linux computer_name 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
*   No gui
*   OneDrive for Business
*   Installed from PPA
*   OneDrive Application Version: `onedrive v2.4.10-0~202102221319~ubuntu20.04.1`
*   OneDrive Application Configuration: 
```
onedrive version                       = v2.4.10-0~202102221319~ubuntu20.04.1
Config path                            = /home/me/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/me/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

```
curl 7.71.1 (x86_64-conda_cos6-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libssh2/1.9.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

*   Is your configured 'sync_dir' a local directory or a network mount point? Local directory
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 

```
├─sda2
│    ext4         f36ba89c-da58-4e75-a45a-43353d654cca    2.3T     9% /
```

*   I share this account with a number of other Windows laptops and PCs, all running Windows 10.

I can email the debug list, but my verbose output is essentially:

```
$ onedrive --synchronize --verbose
Using 'user' Config Dir: /home/me/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/me/OneDrive
Application version: v2.4.10-0~202102221319~ubuntu20.04.1
Account Type: business
Default Drive ID: myID
Default Root ID: rootID
Remaining Free Space: 996390792192
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: pathID
Updated Remaining Free Space: 996390792192
Processing 204 OneDrive items to ensure consistent local state
Processing 210 OneDrive items to ensure consistent local state
Processing 226 OneDrive items to ensure consistent local state
```
And the "Processing message continues indefinitely.
![onedrive](https://user-images.githubusercontent.com/32136565/119546925-7312f900-bd62-11eb-921d-f006bdcd2809.png)

**Comment by abraunegg** [comment]
@eraguzin-bnl 
> I tried using sudo apt-get remove onedrive and reinstalling it, but I still see the same behavior.

Unless you are using the Ubuntu PPA, which you appear to be - however if you uninstalled and reinstalled without using the PPA, you would get an even older version that installs to a different path, which, overrides the PPA version installation.

Unfortunately, you are also running an obsolete version which contains bugs and issues and is not supported.

Steps for you to complete:

1. Uninstall the PPA package & ensure all 'onedrive' traces are removed .. search your system and remove all traces to ensure the older package / binaries are removed
2. Build from source and replicate the issue using 'master'
