### ISSUE TITLE
Delay to upload

### ISSUE THREAD

**Issue by sBanana** [abraunegg/onedrive#148]
EDIT: I fixed it by increasing the monitor_interval delay to 300

I am currently using WPS Office Suite and uploading to One drive but it uploads before the file has completed saving, is there anyway to add a delay to the local One drive upload.

Thanksa

**Comment by abraunegg** [comment]
@sBanana 
Whilst there is no way to 'delay' the upload in monitor mode, increasing the monitor delay between sync's certainly has the same desired effect.
