### ISSUE TITLE
Q: Error during resync: core.exception.AssertError@src/itemdb.d(222): The result must have 14 columns

### ISSUE THREAD

**Issue by nea** [abraunegg/onedrive#1497]
### Bug Report Details ###
Ahoi

I am trying to do a resync as the monitor process failed and told me to resync.
When kicking off the resync, sometimes one or two files are synced, then it stops with the error 
```
core.exception.AssertError@src/itemdb.d(222): The result must have 14 columns
```
There is not much happening before only
```
Initializing the Synchronization Engine ...
Applying changes of 56489A643CC66225!105
Processing 56489A643CC66225!105 root
Root
Processing 56489A643CC66225!252 Private
Folder
```
then the error.

I am trying to look at versions etc. but also these commands end in such a failure.

I was looking around but did not find a similar report. Maybe I am missing something. Any hint pointing me in the right direction is highly appreciated.

Thanks a lot ^^

**Application and Operating System Details:**
*   Debian 9.13
*   no gui
*   OneDrive Account Type: Private
*   Debian package 2.4.10-1

**Comment by abraunegg** [comment]
@nea 
There are 2 things going on:
1. You have the 'skilion' version installed somewhere. You must delete all onedrive references on your system, and reboot
2. You are running an obsolete and out of date client, you must upgrade. You must uninstall the package you used to install and build from source.

**Comment by nea** [comment]
Ok @abraunegg 

Thanks for the quick response. Even if it worked before?
Yes, skillion was on the system before, before I switched to your version several months ago. Until it now stopped.
That was why I was asking.

Will try to clean everything and start over.

Thanks
