### ISSUE TITLE
How to sync at a specific location?

### ISSUE THREAD

**Issue by nazar2sfive** [abraunegg/onedrive#1498]
I dual boot my pc.
/dev/sda my main disk

/dev/sda2 = windows 10
/dev/sda3 = linux
/dev/sda4 = ntfs partition(my files including onedrive)

![Screenshot (3)](https://user-images.githubusercontent.com/12841320/120102340-3b44f080-c16a-11eb-93ee-8563bb6664b4.png)

I have around 71Gb of Data in onedrive in my ntfs partition. 
![image](https://user-images.githubusercontent.com/12841320/120102400-86f79a00-c16a-11eb-936a-769b3caec7d6.png)
I have disabled files on demand option. so i can access them locally on both linux and windows.

now to the question...
How can i use onedrive in linux to sync to that specific location ? Will this avoid downloading again those 71Gb of data and sync only the changed files?

**Comment by abraunegg** [comment]
@nazar2sfive 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
