### ISSUE TITLE
Segmentation Fault (core dumped) after entering URI for Auth

### ISSUE THREAD

**Issue by Nelson-Morais** [abraunegg/onedrive#1499]
After entering the URI from the browser into the terminal, a segmentation fault happens.

**Application and Operating System Details:**
*   Ubuntu 18.04
*   Gnome GUI
*   OneDrive Private Account 
*   Installed from package
*   OneDrive Application Version: onedrive v1.0.1
*   OneDrive Application Configuration: No output, "Unrecognized option"
*   Provide the version of curl you are using: curl 7.58.0 

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  type "ondrive" in terminal
2.  Click on auth link
3.  login with MS account and copy URI from browser
4.  paste URI from browser into Terminal
5.  error happens.

Application Error:
```bash
onedrive.OneDriveException@src/onedrive.d(403): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "ac92eeca-60ca-4716-a5ff-9174e40001de",
    "error": "invalid_grant",
    "error_codes": [
        70000
    ],
    "error_description": "AADSTS70000: The provided value for the 'code' parameter is not valid.\r\nTrace ID: 18d2b422-24e2-42f9-9b2b-f42ab32d4601\r\nCorrelation ID: ac92eeca-60ca-4716-a5ff-9174e40001de\r\nTimestamp: 2021-06-01 19:57:46Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=70000",
    "timestamp": "2021-06-01 19:57:46Z",
    "trace_id": "18d2b422-24e2-42f9-9b2b-f42ab32d4601"
}
----------------
0x55c9aa57ea9c ???
	???:0
0x55c9aa5f4d22 ???
	???:0
0x55c9aa57d96b ???
	???:0
0x55c9aa57d7ff ???
	???:0
0x55c9aa57c136 ???
	???:0
0x55c9aa57be7f ???
	???:0
0x55c9aa5797a7 ???
	???:0
0x55c9aa6cd8be ???
	???:0
0x55c9aa6cda2e ???
	???:0
0x55c9aa6cddea ???
	???:0
0x55c9aa6cda2e ???
	???:0
0x55c9aa6cdbc0 ???
	???:0
0x55c9aa578ea3 ???
	???:0
0x7efe4de00bf6 __libc_start_main
	???:0
0x55c9aa570c99 ???
	???:0
0xffffffffffffffff ???
	???:0
Segmentation fault (core dumped)

```

**Comment by abraunegg** [comment]
@Nelson-Morais 
You are running Ubuntu & using an unsupported application version.

Steps for you to complete:
1. Uninstall the 'skilion' client which you have installed, remove any 'onedrive' package you have installed.
2. Follow the correct installation instructions for Ubuntu as listed here: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md - ie DO NOT install via `sudo apt install onedrive`
3. Optional: Upgrade your Ubuntu 18.x to 21.x

**Comment by Nelson-Morais** [comment]
> @Nelson-Morais
> You are running Ubuntu & using an unsupported application version.
> 
> Steps for you to complete:
> 
> 1. Uninstall the 'skilion' client which you have installed, remove any 'onedrive' package you have installed.
> 2. Follow the correct installation instructions for Ubuntu as listed here: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md - ie DO NOT install via `sudo apt install onedrive`
> 3. Optional: Upgrade your Ubuntu 18.x to 21.x

Hello abraunegg, 

Sadly i can't change my version of ubuntu as I need to be running 18.04 for a University project. 
I used that exact link to download the package for Ubuntu 18.04 ( clicking on the OneDrive link corresponding to my Ubuntu version on the table ). The only other option I see is Ubuntu PPA, which also did no work for me, I tested it right now.

I guess the only viable way is to build it from source then right ? 

Thank alot for the super fast reply :)

**Comment by abraunegg** [comment]
@Nelson-Morais 
Correct - the only option for Ubuntu is to build from source. All Ubuntu package versions and PPA are unsupported as they are old and contain bugs.

**Comment by Nelson-Morais** [comment]
@abraunegg ok I will give it a go tomorrow then, thanks a lot for the help !
