### ISSUE TITLE
skip_file config entry needs to be checked for any characters to escape

### ISSUE THREAD

**Issue by dawbarton** [abraunegg/onedrive#15]
I've just tried the client on another business account (I have two separate businesses, the other one works fine) and I get the error
```
std.regex.internal.ir.RegexException@/usr/include/dmd/phobos/std/regex/internal/parser.d(1019): '*', '+', '?', '{', '}' not allowed in atom
Pattern with error: `^[^/]*+` <--HERE-- `++[^/]*$`
Pattern with error: `^[^/]*+` <--HERE-- `++[^/]*$`
----------------
/usr/include/dmd/phobos/std/regex/internal/parser.d:1019 pure @trusted void std.regex.internal.parser.Parser!(immutable(char)[], std.regex.internal.parser.CodeGen).Parser.error(immutable(char)[]) [0x542437]
/usr/include/dmd/phobos/std/regex/internal/parser.d:559 ref @trusted std.regex.internal.parser.Parser!(immutable(char)[], std.regex.internal.parser.CodeGen).Parser std.regex.internal.parser.Parser!(immutable(char)[], std.regex.internal.parser.CodeGen).Parser.__ctor!(const(char)[]).__ctor(immutable(char)[], const(char)[]) [0x542826]
/usr/include/dmd/phobos/std/regex/package.d:420 @safe std.regex.internal.ir.Regex!(char).Regex std.regex.regexImpl!(immutable(char)[]).regexImpl(immutable(char)[], const(char)[]) [0x540db2]
/usr/include/dmd/phobos/std/functional.d:1090 std.regex.internal.ir.Regex!(char).Regex std.functional.memoize!(std.regex.regexImpl!(immutable(char)[]).regexImpl(immutable(char)[], const(char)[]), 8).memoize(immutable(char)[], const(char)[]) [0x55b50e]
/usr/include/dmd/phobos/std/regex/package.d:392 @trusted std.regex.internal.ir.Regex!(char).Regex std.regex.regex!(immutable(char)[]).regex(immutable(char)[][], const(char)[]) [0x53fd98]
/usr/include/dmd/phobos/std/regex/package.d:399 @trusted std.regex.internal.ir.Regex!(char).Regex std.regex.regex!(immutable(char)[]).regex(immutable(char)[], const(char)[]) [0x53fc35]
src/util.d:104 std.regex.internal.ir.Regex!(char).Regex util.wild2regex(const(char)[]) [0x5b1ad3]
src/selective.d:27 void selective.SelectiveSync.setMask(const(char)[]) [0x5a570e]
src/main.d:187 _Dmain [0x5935de]
```
This happens when I paste in the response URI after I've authenticated. It used to work at some point in the past; I checked an old backup and used the refresh_token from that so I didn't need to authenticate again but the same error came up.

Any ideas? Thanks.

**Comment by dawbarton** [comment]
I've just realised, I've got `skip_file = *+++*` in my config (I mark files containing sensitive information with +++ somewhere in the file name so they aren't synced). I guess the `+` are the offending character in the regex. I've tried escaping it for now (i.e., `skip_file = *\+\+\+*`) which gets the sync started (it'll take a while to finish and for me to see if it's worked....). It might be worth checking for valid file name characters that need escaping in `skip_file`.

**Comment by abraunegg** [comment]
The only suggestion I have at this point in time is to work offline with me on this one to determine what the issue is with the account / parsing. 

I am testing with OneDrive Business test accounts and don't get a URL parse issue - so i am wondering if it is something environmental / local or account related.

**Comment by abraunegg** [comment]
> It might be worth checking for valid file name characters that need escaping

Thanks - will look at this once #2 and #11 are resolved

**Comment by abraunegg** [comment]
@dawbarton 

Just wondering if the approach taken here would work:

https://github.com/JonaMX/onedrive/commit/a45e11c6533a51ef752dec4599bbec2a8df0aa03

**Comment by abraunegg** [comment]
@dawbarton 
Can you help validate PR https://github.com/abraunegg/onedrive/pull/39 ?

Below is my validation:
```
cat ~/.config/onedrive/config 

skip_file = "*+++*"
```

```
Loading config ...
Using Config Dir: /root/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 1098617079679
Fetching details for OneDrive Root
OneDrive Root exists in the database
Applying changes of Path ID: <redacted>
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Skipping item - excluded by skip_file config: ./sensative-file-+++.doc
Applying changes of Path ID: <redacted>
```

**Comment by dawbarton** [comment]
Thanks! That seems to work for me as well.
