### ISSUE TITLE
Bandwidth limiter

### ISSUE THREAD

**Issue by happydemic** [abraunegg/onedrive#150]
**Is your feature request related to a problem? Please describe.**
When uploading large amounts of data, I’d like to be able to limit the bandwidth used for OneDrive. I see this was [discussed before](http://github.com/skilion/onedrive/issues/174) but the requester didn’t follow up. 

**Describe the solution you'd like**
I’d like to be able to set a bandwidth limit in the config. Rclone has a good implementation which includes a schedule for the limit and, usefully, an interrupt signal which toggles the throttle on and off (which a user can then connect to a keyboard shortcut). 

**Describe alternatives you've considered**

**Additional context**

**Comment by abraunegg** [comment]
Whilst I appreciate the desire to do this "in application" there are many other alternatives to do this:
* trickle
* iptables
* implement QoS in system, switch, router etc

Please look into some of the above alternatives to provide this capability.

**Comment by abraunegg** [comment]
PR #1210 implements this feature request
