### ISSUE TITLE
log:Trying to delete item

### ISSUE THREAD

**Issue by leon-zhang-guoao** [abraunegg/onedrive#1510]
I find that sometimes  delete files that have been synchronized, and I want to know why it will be deleted.
version 2.4.0

**Comment by abraunegg** [comment]
@leon-zhang-guoao 
You are using an unsupported client version. You must upgrade your client.

Additionally, please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
