### ISSUE TITLE
How to use onedrive client only for upload?

### ISSUE THREAD

**Issue by ukreddy-erwin** [abraunegg/onedrive#1522]
I am using the below command to sync files to onedrive.

There is a folder in onedrive "Test_folder", so whichever files need to upload are being copied to the local folder with same name and once the sync command is ran, the files are being uploaded.

onedrive --synchronize --single-directory "Test_folder" --verbose

But, the files exists locally also and if we remove locally after syncing, next time, it is deleting online also.

Is there any version of this command to use only to upload to remote folder and no need to keep a local copy after upload?

**Comment by abraunegg** [comment]
@ukreddy-erwin 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
