### ISSUE TITLE
Unable to enable onedrive.service

### ISSUE THREAD

**Issue by Wmorg97** [abraunegg/onedrive#1528]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
I am unable to enable the systemd onedrive service via the 'systemctl --user unmask onedrive' command.

I get the following error on executing the command:
Failed to enable unit: Unit file /etc/xdg/systemd/user/onedrive.service is masked.

I have tried 'systemctl --user unmask onedrive', however that has not fixed my problem.  I have also added the following lines to my .bashrc with no success:
```
'119 export XDG_RUNTIME_DIR="/run/user/$UID"
120 export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"'
```

**Application and Operating System Details:**
*  ` Ubuntu 20.04 : Linux Ubuntu-Will 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

*   Headless, no GUI
*   365 Personal
*   Source
*   dmd-2.097.0 
*   onedrive v2.4.12-10-g13b3709

*   Application configuration:
```
onedrive version                       = v2.4.12-10-g13b3709
Config path                            = /home/wtcmo/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/wtcmo/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
# sync list for one drive client
# exclusions: !<filepath>
# all of type: <filepath>/*.pdf -- includes all pdf files
# <filepath>/* includes all subdirectories
# Do Exclusions then Inclusions


# -------Exclusions-------------------

!Desktop/*
!Documents/*
!Pictures/*
!Programming/Libraries/Cpp/FLTK/*
!Riot Logs/*
!Storage/*
!Programming/Code/Learn/Cpp/PPP/Practice/Graphics/*
#-------------------------------------




#------------Inclusions----------------

/*

#--------------------------------------
Business Shared Folders configured     = false
```

*  curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

*   local directory

*   
* 
*lsbk -f:
```
NAME FSTYPE LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
loop0
     squash                                                  0   100% /snap/cano
loop1
     squash                                                  0   100% /snap/core
loop2
     squash                                                  0   100% /snap/gnom
loop3
     squash                                                  0   100% /snap/gtk-
loop4
     squash                                                  0   100% /snap/snap
loop5
     squash                                                  0   100% /snap/core
loop6
     squash                                                  0   100% /snap/curl
loop7
     squash                                                  0   100% /snap/gnom
loop8
     squash                                                  0   100% /snap/gtk-
loop9
     squash                                                  0   100% /snap/snap
loop10
     squash                                                  0   100% /snap/wine
loop11
     squash                                                  0   100% /snap/snap
loop12
     squash                                                  0   100% /snap/snap
loop13
     squash                                                  0   100% /snap/core
loop14
     squash                                                  0   100% /snap/note
loop15
     squash                                                  0   100% /snap/gnom
loop16
     squash                                                  0   100% /snap/wine
loop17
     squash                                                  0   100% /snap/core
loop18
     squash                                                  0   100% /snap/core
  
 nvme0n1
│                                                                     
├─nvme0n1p1
│    vfat         7CA1-39CB                               562M     1% /boot/efi
├─nvme0n1p2
│    ext4         aa2ad38a-e4d0-40b4-9a94-90c76f80c6eb   11.7G    45% /
├─nvme0n1p3
│    ext4         2220b54a-0ff9-427a-92b9-405c84993d9d     48G    43% /home
├─nvme0n1p4
│    swap         d5c7989e-34c1-442f-8b29-99669f5a2585                [SWAP]
└─nvme0n1p5
     exfat  Share exFAT
                  EDCD-B5D0      
```
       
*   I have OneDrive running on my Windows OS that I have installed a separate SSD on my PC, in dual boot configuration

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Type in "systemctl --user enable onedrive"

Terminal Input : systemctl --user enable onedrive
Terminal Output : Failed to enable unit: Unit file /etc/xdg/systemd/user/onedrive.service is masked.
![Screenshot from 2021-06-28 19-11-25](https://user-images.githubusercontent.com/66193807/123722068-d356f800-d844-11eb-96fe-31bbf95e244e.png)

**Comment by abraunegg** [comment]
@Wmorg97 
This is a case of potentially not reading the documentation correctly

**OneDrive service running as root user via systemd (Arch, Ubuntu, Debian, OpenSuSE, Fedora)**
Refer to: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-root-user-via-systemd-arch-ubuntu-debian-opensuse-fedora

**OneDrive service running as a non-root user via systemd (All Linux Distributions)**
Refer to: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-a-non-root-user-via-systemd-all-linux-distributions

**Note:** This is what you appear to be trying / want to do .... 

Start over, remove your bash export lines and use the correct method to enable systemd services for a *non root user* account ...........

**Comment by Wmorg97** [comment]
> @Wmorg97
> This is a case of potentially not reading the documentation correctly
> 
> **OneDrive service running as root user via systemd (Arch, Ubuntu, Debian, OpenSuSE, Fedora)**
> Refer to: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-root-user-via-systemd-arch-ubuntu-debian-opensuse-fedora
> 
> **OneDrive service running as a non-root user via systemd (All Linux Distributions)**
> Refer to: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-a-non-root-user-via-systemd-all-linux-distributions
> 
> **Note:** This is what you appear to be trying / want to do ....
> 
> Start over, remove your bash export lines and use the correct method to enable systemd services for a _non root user_ account ...........

Thanks!
