### ISSUE TITLE
Unable to reach Microsoft OneDrive API service, unable to initialize application

### ISSUE THREAD

**Issue by bruceesmith** [abraunegg/onedrive#1529]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###

The OneDrive application can't start (single-shot execution) or repeatedly times out (running as a Docker container). I run the app in a container launched from the image at https://hub.docker.com/r/driveone/onedrive, and I use a launch script based on documentation at https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md. I've run in the same configuration for maybe 18 months, it's always been flawless ()a great experience) until this new problem surfaced.

**Application and Operating System Details:**
*   Ubuntu 20.04 desktop, fully patched (unattended-upgrades enabled).
```
    bruce@corunastylis:~$ uname -a
    Linux corunastylis 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
    bruce@corunastylis:~$
```
*   Are you using a headless system (no gui) or with a gui installed? Ubuntu desktop with Gnome
*    OneDrive Account Type - Business
*   Did you build from source or install from a package? I'm running the latest Docker image. From "docker inspect"
```
           "RepoDigests": [
               "driveone/onedrive@sha256:5256856b89a7f9e0c21f80b6a1b01bf3b4523679f1d0b3ae7be00df62bf055aa" ]
            "Created": "2021-06-17T21:18:41.605878595Z"
            "Labels": {
                "org.label-schema.build-date": "20201113",
                "org.label-schema.license": "GPLv2",
                "org.label-schema.name": "CentOS Base Image",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "CentOS",
                "org.opencontainers.image.created": "2020-11-13 00:00:00+00:00",
                "org.opencontainers.image.licenses": "GPL-2.0-only",
                "org.opencontainers.image.title": "CentOS Base Image",
                "org.opencontainers.image.vendor": "CentOS"
            }
```
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
*   OneDrive Application Version: onedrive v2.4.12-10-g13b3709
*   OneDrive Application Configuration: 
```
onedrive version                       = v2.4.12-10-g13b3709
Config path                            = /home/onedrive/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/onedrive/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: 

 (from inside the Docker container) curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0

*   Is your configured 'sync_dir' a local directory or a network mount point? Local directory
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on?

 It is in the /home folder that is in an ext4 file system 
 ```
 sda                                                                                                       
 ├─sda1                  crypto_LUKS 1               45ca65c6-6f39-47f3-8686-ef38f036eddf                  
 │ └─LUKS_BOOT           ext4        1.0             d7f9d6d7-7cdc-40e8-bc82-d2f911ec798c    377.6M    42% /boot
 ├─sda2                                                                                                    
 ├─sda3                  vfat        FAT16    EFI-SP 68D2-6B6D                               122.5M     4% /boot/efi
 └─sda5                  crypto_LUKS 1               b2af6a1c-d771-431c-a7f0-0d09b102e61e                  
   └─sda5_crypt          LVM2_member LVM2 001        O6pfeN-FsIO-RuNQ-Vp5G-00ST-QSrs-AsHnDR                
     ├─ubuntu--vg-swap_1 swap        1               e3ddfecd-4632-41e0-ae23-83268fdf5636                  [SWAP]
     ├─ubuntu--vg-root   ext4        1.0             f64afe4d-182c-4a33-a2a2-dfcdec0eb6b2     45.5G    37% /
     └─ubuntu--vg-home   ext4        1.0             72218ba0-c276-4efc-9c72-954c0b8013cf    335.1G    45% /home
```

*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time

OneDrive folder is not shared with other systems
OneDrive account is active on a separate Windows 10 device at the same time (but it has been this way for the entire year or more that I've used driveone/onedrive and I've never had this problem in that time)

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**

Here is my launch file
```
#!/bin/bash
#
# Update onedriveDir with correct existing OneDrive directory path
#
onedriveDir="${HOME}/OneDrive"
firstRun='-d'
docker pull driveone/onedrive
docker inspect onedrive_conf > /dev/null || { docker volume create onedrive_conf; firstRun='-it'; }
docker inspect onedrive > /dev/null && docker rm -f onedrive
docker run $firstRun --restart unless-stopped --name onedrive -v onedrive_conf:/onedrive/conf -v "${onedriveDir}:/onedrive/data" driveone/onedrive
```
**Complete Verbose Log Output**

Will submit via e-mail

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@bruceesmith 
Please refer to this: https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions#cannot-connect-to-microsoft-onedrive-service---network-connection-issue

Most likely:
* You are blocking HTTPS somewhere
* You are blocking DNS somewhere
* You have slow DNS response / resolution

Follow the advice in the FAQ to determine where your system is letting you down, perform the tests from inside the Docker container as well.

**Comment by bruceesmith** [comment]
Please tell me the URL to which I should perform the network checks. I've already proven that I can access OneDrive through O365 in a web browser on the same Ubuntu desktop, and I can manually curl to https://graph.microsoft.com/v1.0

**Comment by abraunegg** [comment]
@bruceesmith 

Please read the FAQ link

**Comment by bruceesmith** [comment]
Sorry, I just read that other page:

bruce@corunastylis:~$ curl -I --connect-timeout 5 --max-time 5 https://login.microsoftonline.com
HTTP/1.1 200 OK
Cache-Control: no-store, no-cache
Pragma: no-cache
Content-Length: 153494
Content-Type: text/html; charset=utf-8
Expires: -1
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Link: <https://aadcdn.msauth.net>; rel=preconnect; crossorigin
Link: <https://aadcdn.msauth.net>; rel=dns-prefetch
Link: <https://aadcdn.msftauth.net>; rel=dns-prefetch
X-DNS-Prefetch-Control: on
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
x-ms-request-id: 115aab5e-985d-4c93-b8d2-18384c975d00
x-ms-ests-server: 2.1.11829.9 - AUSELR2 ProdSlices
Set-Cookie: fpc=Ajsdhpk1VQBGuzdzW8M-tLg; expires=Thu, 29-Jul-2021 03:15:12 GMT; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: esctx=AQABAAAAAAD--DLA3VO7QrddgJg7WevrSeSy7qxwddkCxRIGDeh0s3ZOsdwXVr-XdbXNTbM8pplMnmKut6qon1VKKD_NEJK7Nr-O5j9mio_1wMh8vl2fR2Gbon7d9_d3lWDTubWKz2tuWLhyApVWw0hU0HsCGnBxq_0zNzoWDBG-QbN8Ej5NJR6CF01ECf9FDqR9ES0GoPIgAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
Set-Cookie: stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Tue, 29 Jun 2021 03:15:11 GMT

bruce@corunastylis:~$

**Comment by abraunegg** [comment]
@bruceesmith 

Perform the tests from inside your docker container, not your host.

This is a network issue - not a problem with the client

**Comment by bruceesmith** [comment]
You are 100% correct, this is a network problem from inside Docker-land

[root@b22168e48406 onedrive]# curl -I --connect-timeout 5 --max-time 5 https://login.microsoftonline.com
curl: (28) Resolving timed out after 5517 milliseconds
[root@b22168e48406 onedrive]#

Apologies for raising this with you before really thinking it through myself. By the way, thank you for a great product, it is a real lifeline in my world.
