### ISSUE TITLE
On centos/amazon linux not compiling

### ISSUE THREAD

**Issue by ukreddy-erwin** [abraunegg/onedrive#1531]
I am using the app in ubuntu, it worked.
I didn't check recently as I installed 6 months to 1 year back.
But, today I tried on centos 8 and amazon linux 7
Both places, it is not compiling.

dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
cc: No such file or directory
Error: linker exited with status 255
make: *** [onedrive] Error 1

**Comment by abraunegg** [comment]
@ukreddy-erwin 
Closing issue as not following reasons:
* support procedures despite numerous advice on the correct process to follow
* not following the correct build process as per installation guide for centos platforms
