### ISSUE TITLE
How to use onedrive client only for upload?

### ISSUE THREAD

**Issue by ukreddy-erwin** [abraunegg/onedrive#1532]
### Discussed in https://github.com/abraunegg/onedrive/discussions/1523

<div type='discussions-op-text'>

<sup>Originally posted by **ukreddy-erwin** June 23, 2021</sup>
I am using the below command to sync files to onedrive.

There is a folder in onedrive "Test_folder", so whichever files need to upload are being copied to the local folder with same name and once the sync command is ran, the files are being uploaded.

onedrive --synchronize --single-directory "Test_folder" --verbose

But, the files exists locally also and if we remove locally after syncing, next time, it is deleting online also.

Is there any version of this command to use only to upload to remote folder and no need to keep a local copy after upload?</div>

**Comment by abraunegg** [comment]
@ukreddy-erwin 
You are *not* following the correct support process. You need to use the support template, fill it in and provide all the details
