### ISSUE TITLE
Database statement execution error occured : Disk I/O error

### ISSUE THREAD

**Issue by kapawit** [abraunegg/onedrive#1538]
I love this app so much. I have been using it since I discovered it. but last night my ubuntu 20 filesystem is almost full so I decided to resize the partition from 50 Gb to 100 Gb. everything works great until I try to continue uploading my data. 
![image](https://user-images.githubusercontent.com/52441717/124010338-e9adb100-da08-11eb-896f-678d8859a7ef.png)

Does anybody have any solution? I have read all the issues but no one mentioning the DISK I/O error.

**Comment by abraunegg** [comment]
@kapawit 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
