### ISSUE TITLE
Changes applied in the wrong order - deletion last unfortunately

### ISSUE THREAD

**Issue by dawbarton** [abraunegg/onedrive#154]
It appears that an old bug has resurfaced; changes applied to a remote aren't necessarily applied in the same order locally.

I just deleted a directory on a remote computer (which contained some sourcecode) and then recreated the same directory using a git clone (the previous source just a copy, not version controlled). Consequently a lot of the files/directories were the same (but not all).

I've just run `onedrive --synchronize` and got
```
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Creating directory: Coding/SoftGlobalScope/.git
Creating directory: Coding/SoftGlobalScope/.git/hooks
Downloading file Coding/SoftGlobalScope/.git/hooks/update.sample ... done.
...lots more downloads...
Downloading file Coding/SoftGlobalScope/.git/packed-refs ... done.
Downloading file Coding/SoftGlobalScope/src/SoftGlobalScope.jl ... done.
Creating directory: Coding/SoftGlobalScope/test
Downloading file Coding/SoftGlobalScope/test/runtests.jl ... done.
Downloading file Coding/SoftGlobalScope/.travis.yml ... done.
Downloading file Coding/SoftGlobalScope/LICENSE.md ... done.
Downloading file Coding/SoftGlobalScope/README.md ... done.
Downloading file Coding/SoftGlobalScope/REQUIRE ... done.
Deleting item Coding/SoftGlobalScope/Manifest.toml <----- Correct
Deleting item Coding/SoftGlobalScope/Project.toml <----- Correct
Deleting item Coding/SoftGlobalScope/src/SoftGlobalScope.jl <----- Problem!! Only just downloaded it!
Deleting item Coding/SoftGlobalScope/src <----- Problem!!
Deleting item Coding/SoftGlobalScope <----- Problem!!
Deleting item from OneDrive: Coding/SoftGlobalScope <----- Problem!!
```
onedrive decided to perform the deletions after doing all the downloads rather than the other way around. This had quite significant repercussions in wiping out the entire directory!

**Comment by abraunegg** [comment]
Nothing has changed in the codebase as to the order processing here .. so potentially this may be an API change where delete's are now being sent last (where they used to be sent first). The client processes the "changes" in the order that they were received.

**Comment by dawbarton** [comment]
That's annoying if they've changed the API. Do you receive a date stamp for
the changes? I'll see how reproducible it is (it's happened twice to me so
far).

**Comment by abraunegg** [comment]
Unsure. I know when I was doing all the validation around folders not being deleted in the correct order, that all the delete's were sent first - so it would be a process of adding in a line of code in sync.d ~ line 400-405 right after `string thisItemPath;`

```
log.log("OD Reported Change: ", item);
```

You can then see each change being reported from OneDrive & see in which order they are being sent

**Comment by dawbarton** [comment]
Great, I'll try that. Thanks!

**Comment by abraunegg** [comment]
@dawbarton 
Any update from your side as to validating the order of changes your seeing?

**Comment by abraunegg** [comment]
@dawbarton
Any update from your side as to validating the order of changes your seeing?

**Comment by dawbarton** [comment]
Apologies for the slow response - been a bit busy with other things. I've generated a few log files where the problems are apparent and I'm now trying to reduce the logs down to the actual things of interest. Is there a way I could send you the logs privately?

**Comment by abraunegg** [comment]
@dawbarton 
The best email address the logs is support@mynas.com.au

**Comment by dawbarton** [comment]
Apologies for the delay - been a bit busy at work. I've now got a fairly minimal example of where things go wrong. See below; laptop is a linux laptop with your client and desktop is a Windows machine with the Microsoft OneDrive client (auto-syncing).
```
laptop> mkdir Coding/testdir1
laptop> echo "Hello world" > Coding/testdir1/testfile
laptop> onedrive --synchronize
desktop> rm -rf Coding/testdir1  # background sync
desktop> mkdir Coding/testdir1  # background sync
desktop> echo "Hello another world" > Coding/testdir1/testfile2  # background sync
laptop> onedrive --synchronize
```
The output of this (with logging output as you mentioned)
```
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
OD Reported Change:
{
  "@odata.type": "#microsoft.graph.driveItem",
  "fileSystemInfo": {
    "createdDateTime": "2014-11-24T07:23:10Z",
    "lastModifiedDateTime": "2018-09-13T14:57:36Z"
  },
  "folder": {
    "childCount": 31
  },
  "id": "01XNGKPN",
  "name": "root",
  "parentReference": {
    "driveId": "b!vu1HI4m",
    "driveType": "business"
  },
  "root": {}
}
OD Reported Change:
{
  "@odata.etag": "\"{BB25B2CB9B70},2\"",
  "@odata.type": "#microsoft.graph.driveItem",
  "cTag": "\"c:{BB25B2CB9B70},0\"",
  "eTag": "\"{BB25B2CB9B70},2\"",
  "fileSystemInfo": {
    "createdDateTime": "2018-03-26T15:40:28Z",
    "lastModifiedDateTime": "2018-03-26T15:40:21Z"
  },
  "folder": {
    "childCount": 4
  },
  "id": "EWZMXG3Q",
  "name": "Coding",
  "parentReference": {
    "driveId": "b!vu1HI4m",
    "driveType": "business",
    "id": "01XNGKPN",
    "path": "/drives/b!vu1HI4m/root:"
  }
}
OD Reported Change:
{
  "@odata.type": "#microsoft.graph.driveItem",
  "cTag": "\"c:{1CED57C03BA0},4294967295\"",
  "deleted": {
    "state": "deleted"
  },
  "fileSystemInfo": {},
  "folder": {
    "childCount": 0
  },
  "id": "5VL4AO5A",
  "parentReference": {
    "driveId": "b!vu1HI4m",
    "driveType": "business",
    "id": "EWZMXG3Q"
  }
}
OD Reported Change:
{
  "@odata.type": "#microsoft.graph.driveItem",
  "cTag": "\"c:{3E5F87D259DC},4294967295\"",
  "deleted": {
    "state": "deleted"
  },
  "file": {},
  "fileSystemInfo": {},
  "id": "L6D5EWO4",
  "parentReference": {
    "driveId": "b!vu1HI4m",
    "driveType": "business",
    "id": "5VL4AO5A"
  }
}
OD Reported Change:
{
  "@odata.etag": "\"{5DDB7ADE9392},2\"",
  "@odata.type": "#microsoft.graph.driveItem",
  "cTag": "\"c:{5DDB7ADE9392},0\"",
  "eTag": "\"{5DDB7ADE9392},2\"",
  "fileSystemInfo": {
    "createdDateTime": "2018-09-13T14:56:43Z",
    "lastModifiedDateTime": "2018-09-13T14:56:40Z"
  },
  "folder": {
    "childCount": 1
  },
  "id": "3N5N5E4S",
  "name": "testdir1",
  "parentReference": {
    "driveId": "b!vu1HI4m",
    "driveType": "business",
    "id": "EWZMXG3Q",
    "path": "/drives/b!vu1HI4m/root:/Coding"
  }
}
OD Reported Change:
{
  "@odata.etag": "\"{C0D5AE782BE1},2\"",
  "@odata.type": "#microsoft.graph.driveItem",
  "cTag": "\"c:{C0D5AE782BE1},2\"",
  "eTag": "\"{C0D5AE782BE1},2\"",
  "file": {
    "hashes": {
      "quickXorHash": "qSVxe9vpEhCEwQ1vtAMayiAHENw="
    },
    "mimeType": ""
  },
  "fileSystemInfo": {
    "createdDateTime": "2018-09-13T14:57:34Z",
    "lastModifiedDateTime": "2018-09-13T14:57:34Z"
  },
  "id": "2WXHQK7B",
  "name": "testfile2",
  "parentReference": {
    "driveId": "b!vu1HI4m",
    "driveType": "business",
    "id": "3N5N5E4S",
    "path": "/drives/b!vu1HI4m/root:/Coding/testdir1"
  }
}
Downloading file Coding/testdir1/testfile2 ... done.
Deleting item Coding/testdir1/testfile
Deleting item Coding/testdir1
Deleting item from OneDrive: Coding/testdir1
```
Note that I've sanitised the IDs but they should be consistent (i.e., the same ids are in the same places); the JSON is also pretty-printed for convenience.

It looks like the order that the changes are logged in is the reverse of the order that they are applied in. Thoughts?

**Comment by abraunegg** [comment]
Will have to do some exhaustive testing, as the "changes" array when doing a sync, when I was going through fixing the nested folders not deleting, the delete changes were always listed first, not last. If this has changed, then this is a MS API change.

In your log above - where you have listed `# background sync` - is this running as a service or manual sync? Also, what application version are you using `onedrive --version`

**Comment by dawbarton** [comment]
One the laptop `onedrive --version` gives `onedrive v2.1.2`. I only use manual syncs on the laptop. On the desktop I'm running the Windows onedrive client (MS) as a service.

I can rerun with the latest master next week if that's helpful.

**Comment by abraunegg** [comment]
No - that should be OK .. v2.1.2 is the latest outside of the patches added in yesterday to master - of which nothing material there which would affect this behaviour.

Will run some tests this side & get a test script written which hopefully can replicate / see what is going on here.

**Comment by abraunegg** [comment]
@dawbarton 
I have been doing some testing and whiteboarding on this issue.

This 'onedrive' client will only process the changes as presented by OneDrive & in the order provided by OneDrive.

In all of your examples, your making changes on a 2nd system & whilst the changes are being reflected, they are being sent by OneDrive in an order that is out of sequence.

I suspect that what needs to happen here is that this issue needs to be brought to Microsoft's attention & the OneDrive / Graph team given all of your examples.

Their 'logic' engine should be able to 'cancel out' delete's if a deleted file is replaced by a newer file, or present delete's as the items to process first. If I start manually messing with the order of what is provided, this will screw up other processing on the 'list of changes'

Happy to re-look at this if there is no happy response from Microsoft.
