### ISSUE TITLE
ldc2, not compiling with this

### ISSUE THREAD

**Issue by ukreddy-erwin** [abraunegg/onedrive#1541]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
I am trying with ldc2 compiler as per instructions but getting error.

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
* Linux onedrive 5.8.0-1036-azure #38~20.04.1-Ubuntu SMP Thu Jun 17 14:14:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?no gui

*   Did you build from source or install from a package? source
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`

azureuser@onedrive:~/onedrive$ ~/ldc2-1.25.1-linux-aarch64/bin/ldmd2 --version
-bash: /home/azureuser/ldc2-1.25.1-linux-aarch64/bin/ldmd2: cannot execute binary file: Exec format error
azureuser@onedrive:~/onedrive$ sudo ~/ldc2-1.25.1-linux-aarch64/bin/ldmd2 --version
/home/azureuser/ldc2-1.25.1-linux-aarch64/bin/ldmd2: 1: N@��=@8: not found
/home/azureuser/ldc2-1.25.1-linux-aarch64/bin/ldmd2: 1: ELF��: not found
/home/azureuser/ldc2-1.25.1-linux-aarch64/bin/ldmd2: 2: Syntax error: Unterminated quoted string
azureuser@onedrive:~/onedrive$ ldmd2 --version

**Comment by ukreddy-erwin** [comment]
working with this:
wget https://github.com/ldc-developers/ldc/releases/download/v1.27.0-beta2/ldc2-1.27.0-beta2-linux-x86_64.tar.xz
tar -xvf ldc2-1.27.0-beta2-linux-x86_64.tar.xz

**Comment by abraunegg** [comment]
@ukreddy-erwin 
It looks like you are trying to use LDC - however, it also appears you are *not* following the correct instructions to install LDC ..... and you are trying to use the AARCH64 LDC version on AMD64 .... that is never every going to work.

On platforms where you want to use LDC as the compiler you *must* install in the following manner:
```
curl -fsS https://dlang.org/install.sh | bash -s ldc
```

No other method *will* work .... please follow the provided instructions. This is *why* they exist.
