### ISSUE TITLE
How to pass --sync-shared-folders to docker?

### ISSUE THREAD

**Issue by ukreddy-erwin** [abraunegg/onedrive#1548]
You can provided multiple options as environment variables to docker.

<html>
<body>

ONEDRIVE_UID | UserID (UID) to run as | 1000
-- | -- | --
ONEDRIVE_GID | GroupID (GID) to run as | 1000
ONEDRIVE_VERBOSE | Controls "--verbose" switch on onedrive sync. Default is 0 | 1
ONEDRIVE_DEBUG | Controls "--verbose --verbose" switch on onedrive sync. Default is 0 | 1
ONEDRIVE_DEBUG_HTTPS | Controls "--debug-https" switch on onedrive sync. Default is 0 | 1
ONEDRIVE_RESYNC | Controls "--resync" switch on onedrive sync. Default is 0 | 1
ONEDRIVE_DOWNLOADONLY | Controls "--download-only" switch on onedrive sync. Default is 0 | 1
ONEDRIVE_LOGOUT | Controls "--logout" switch. Default is 0 | 1

</body>
</html>

But these two options are not available.

--sync-shared-folders --single-directory 'Jenkins'

How to pass them to docker container?

**Comment by abraunegg** [comment]
@ukreddy-erwin 
Please follow the correct support process as detailed here:

https://github.com/abraunegg/onedrive#have-a-question
https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
