### ISSUE TITLE
Monitor command stops after a few minutes

### ISSUE THREAD

**Issue by ZacharieALES** [abraunegg/onedrive#1550]
I am using version v2.4.6.7 on Ubuntu. 

The command `onedrive --monitor` stops after a few minutes. Isn't it supposed to run indefinitely and keep synchronizing?

Is there a way to prevent it from stopping?

**Comment by abraunegg** [comment]
@ZacharieALES 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
