### ISSUE TITLE
Business Shared Folders with parentheses are ignored

### ISSUE THREAD

**Issue by eEQK** [abraunegg/onedrive#1554]
### Bug Report Details ###
**Describe the bug**
There's a folder shared with me but it's ignored by OneDrive when synchronizing

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
`Linux dell 5.10.36-2-MANJARO #1 SMP PREEMPT Tue May 11 19:38:44 UTC 2021 x86_64 GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed?
no gui
*   OneDrive Account Type
sorry but I have no idea 
*   Did you build from source or install from a package?
From source using `yay` 
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
```
DMD64 D Compiler v2.097.0

Copyright (C) 1999-2021 by The D Language Foundation, All Rights Reserved written by Walter Bright
```
*   OneDrive Application Version: Output of `onedrive --version`
`onedrive v2.4.12-14-g54a6575`
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
onedrive version                       = v2.4.12-14-g54a6575
Config path                            = /home/user/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/user/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = true
business_shared_folders contents:
Foo (Core)
```
*   Provide the version of curl you are using: Output of `curl --version`
```
curl 7.76.1 (x86_64-pc-linux-gnu) libcurl/7.76.1 OpenSSL/1.1.1k zlib/1.2.11 zstd/1.4.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0
Release-Date: 2021-04-14
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```
*   Is your configured 'sync_dir' a local directory or a network mount point?
local dir
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
N/A
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
encrypted ext4
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
Not shared in any way

**To Reproduce**
1. Have a shared folder that has parentheses in it's name (`Foo (Core)` in my case)
2. Add this folder to `business_shared_folders`
3. synchronize (I'm using `onedrive --synchronize --resync --sync-shared-folders --verbose`)

**It works using the same setup but using a different directory that doesn't have parentheses in name**

output of sync:
```
$ onedrive --synchronize --resync --sync-shared-folders --verbose
Using 'user' Config Dir: /home/user/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/user/OneDrive
Application version: v2.4.12-14-g54a6575
Account Type: business
Default Drive ID: b!Ohy<obfuscated>MY2u
Default Root ID: 01E4WZ<obfuscated>LRRZ
Remaining Free Space: 1099508990477
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 01E4WZN<obfuscated>ELRRZ
Updated Remaining Free Space: 1099508990477
Processing 5 OneDrive items to ensure consistent local state
Attempting to sync OneDrive Business Shared Folders
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Processing <obfuscated>
The file has not changed
Processing <obfuscated>
The file has not changed
Processing <obfuscated>
The directory has not changed
Processing <obfuscated>
The directory has not changed
Uploading new items of ~/OneDrive
Applying changes of Path ID: 01E4W<obfuscated>ELRRZ
Updated Remaining Free Space: 1099508990477
Number of items from OneDrive to process: 0
Attempting to sync OneDrive Business Shared Folders
```

**Comment by abraunegg** [comment]
@eEQK 
You need to provide more information here - your issue contains no real error, does not even show the issue you are claiming. Please also provide a verbose debug log regarding this issue.

Also, *do not* use `--resync` all the time unless the application asks you you.

**Comment by abraunegg** [comment]
@eEQK 
I have been able to replicate this specific issue, as such, please can you test the following PR:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1560/head:pr1560
git checkout pr1560
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.12-16-gea5af73` or greater

**Comment by abraunegg** [comment]
@eEQK
Please can you respond

**Comment by eEQK** [comment]
I can confirm that this works now, cheers!

**Comment by abraunegg** [comment]
@eEQK 
Thanks for the confirmation - will mark as fixed and merge into 'master'
