### ISSUE TITLE
Provide workaround for docker interactive firstrun authentication

### ISSUE THREAD

**Issue by dipique** [abraunegg/onedrive#1557]
**Is your feature request related to a problem? Please describe.**
Because of how the docker version handled authentication, I can't put all my configuration complexity into one place (e.g. a docker template or docker-compose.yml). Instead, I have to have my docker configuration as well as maintaining special first run configuration instructions, since these steps are non-obvious (at least for me). This makes OneDrive the most high maintenance docker container I have.

**Describe the solution you'd like**
I can think of a couple solutions. Perhaps the most elegant would be to add a GUI whose only purpose was to handle authentication. There is still an extra step, but it would not require any documentation to perform; it would just require remembering to open the GUI and perform the sign-in.

A faster solution to implement would be providing the ability to add the authentication token (or url, I suppose) to the onedrive/config file. So, after installing the container, I would check the log (without being in interactive mode) to get the auth url, get the url, and add it to the configuration file. I would restart the container, which could recognize that it a) needed that url and b) had one available to use, then authenticate itself.

I don't fully understand the entire process, so a couple alternative places to put the auth url would be a docker bash variable (set via the docker template) or creating a special text file containing the url that could then be deleted when consumed.

**Describe alternatives you've considered**
I can keep doing it manually.

**Additional context**
I'm not a docker (or linux) veteran, so my terminology might be off or I might be missing something. If so let me know.

**Comment by abraunegg** [comment]
@dipique 
> Because of how the docker version handled authentication, I can't put all my configuration complexity into one place (e.g. a docker template or docker-compose.yml). Instead, I have to have my docker configuration as well as maintaining special first run configuration instructions, since these steps are non-obvious (at least for me). This makes OneDrive the most high maintenance docker container I have.


Please look into the following 'not well documentation' capability:
```
--auth-files ARG
      Perform authorization via two files passed in as ARG in the format `authUrl:responseUrl`
      The authorization URL is written to the `authUrl`, then onedrive waits for the file `responseUrl`
      to be present, and reads the response from that file.
```

You should be able to tell the client what startup command to to use, include | add the `--auth-files ARG`  option, then the client will sit there, waiting until the response file is present, read the contents, authenticate and proceed.

Refer to https://github.com/abraunegg/onedrive/issues/524 for further details.

> I can think of a couple solutions. Perhaps the most elegant would be to add a GUI whose only purpose was to handle authentication. There is still an extra step, but it would not require any documentation to perform; it would just require remembering to open the GUI and perform the sign-in.

Feel free to write one and contribute.

**Comment by dipique** [comment]
Perfect! The auth files meet my needs pretty well.

I'd definitely be interested in contributing, although I'm famously bad at follow-through. If I gather the motivation, I'll dig into what would be involved in a WebUI and take a stab at it. :)

**Comment by abraunegg** [comment]
@dipique 
Feel free to also update the Docker documentation detailing how this can be used with Docker
