### ISSUE TITLE
Reconnect after internet connection drops and returns

### ISSUE THREAD

**Issue by petobens** [abraunegg/onedrive#156]
Hi, I recently noticed that if my internet connection drops and then returns for some reason OneDrive doesn't seem to reconnect. I'm attaching a screenshot of the log file. Can onedrive monitor the internet connection and automatically reconnect once internet is up again? For the record I'm running onedrive with `onedrive --synchronize --monitor &`. Thanks!

![screenshot_2018-08-29_19 58 35](https://user-images.githubusercontent.com/2583971/44827771-04250780-abeb-11e8-896b-d7bc4ddfb642.png)

**Comment by abraunegg** [comment]
If you are using the service files, the client should be re-connecting automatically when there is a connection available. If you are not using the service files, then when there is a connection drop, the application will stop executing despite `&` being used.

**Comment by petobens** [comment]
I'm not using the service files. That's the recommended way of running the application?

**Comment by abraunegg** [comment]
If you are wanting to run the application continuously, then yes. If your attempting to do adhoc sync's, then when the Internet connection drops, the application will terminate and you will need to manually restart.

**Comment by petobens** [comment]
Thanks!
