### ISSUE TITLE
Asynchronous operation

### ISSUE THREAD

**Issue by borouhin** [abraunegg/onedrive#157]
**Is your feature request related to a problem? Please describe.**
The program is sometimes extremely slow due to synchronous processing of all tasks. For example:
- I add a new subdirectory with ~300.000 files, 200 Gb to local OneDrive directory;
- onedrive process hangs for ~2 hours (!) eating 100% of one CPU core, no log entries, no network activity (presumably, adding DB entries, calculating CRCs etc.)
- After that onedrive starts uploading files one by one, this process is much slower with a lot of small files than with a few large ones, network bandwidth allows much faster upload.

**Describe the solution you'd like**
The program should run CPU-consuming and network-dependent tasks in parallel whenever possible. For example, CRCs may be calculated by several threads/processes utilizing all CPU cores, whereas network upload may start as soon as at least some items are ready. Network operations themselves should be performed in several parallel threads/processes.
This should accelerate lengthy operations considerably.

**Describe alternatives you've considered**
Writing my own client from scratch :)

**Additional context**
I realize this may require an almost full rewrite, so not expecting immediate realization, just sharing my considerations.

**Comment by borouhin** [comment]
As an example of inefficient bandwidth usage with multiple small files - there is a graph of traffic from my server. At first, several large files (1-15 Gb each) were uploaded, and almost all bandwidth was utilized. Then small files begun uploading and onedrive used only a small portion of available bandwidth:

![if_bond0_2-pinpoint 1535544035 1535628275](https://user-images.githubusercontent.com/3224392/44868294-135f9000-ac93-11e8-9bab-67226bffab14.png)

If several network operations were performed in parallel, upload would complete much earlier.

**Comment by abraunegg** [comment]
As per #158 - much of this branch of the client is all about fixing the defects of the 'skilion' codebase. Yes this is a performance defect, but I have a feeling that re-writing the application to be more multi-threaded for many processes & operations is what is required here.

**Comment by abraunegg** [comment]
> onedrive process hangs for ~2 hours (!) eating 100% of one CPU core, no log entries, no network activity (presumably, adding DB entries, calculating CRCs etc.)

Most likely this is solved via https://github.com/abraunegg/onedrive/pull/419 

Other aspects are still in plan to resolve

**Comment by borouhin** [comment]
> Most likely this is solved via #419

This is an old comment indeed, many things have improved since then. CPU usage in particular is much less now and no such problems as before.

**Comment by davidbarratt** [comment]
@borouhin could you try out https://github.com/onedrivejs/onedrive ?

**Comment by borouhin** [comment]
> 
> 
> @borouhin could you try out https://github.com/onedrivejs/onedrive ?

@davidbarratt, thanks for the link, looks promising! I gave up attempts to achieve stable 2-way sync and switched to using rclone for 1-way sync only. Had to reorganize my files, but now it works like a charm without any manual interference. I'll give JS client a try when I have time for some experiments.

**Comment by abraunegg** [comment]
@borouhin 
Stable 2 way sync is certainly possible with this client - lots of improvements have been made.

Also - I am closing this issue, as it is better referenced by #232
