### ISSUE TITLE
Change how logfile writing occurs to avoid excessive disk I/O

### ISSUE THREAD

**Issue by borouhin** [abraunegg/onedrive#158]
**Is your feature request related to a problem? Please describe.**

Each time onedrive, when run with --synchronize flag, rechecks hashes of all local files to determine whether they have changed and therefore need to be re-uploaded (calls _testFileHash_ in _uploadFileDifferences_ function). This takes very long with a lot of local files.

Unfortunately, running "onedrive --synchronize" manually is frequently required as the program tends to stop sync tasks or even crash because of every minor error with single file (see my comment in #152) and doesn't resume failed upload automatically when run in monitor mode again.

However, the situation when file contents have changed but it's size and date have not is extremely rare. Skipping hash check for files with unchanged date/time and size would speed up resyncs considerably.

**Describe the solution you'd like**

Skip hash check for local files whose date/time and size have not changed.
Provide a switch to force rechecking hashes in case this is indeed necessary.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by borouhin** [comment]
Sorry to say, I was wrong. Trying to create a fork with the desired behavior I realized that hashes are indeed not checked when size/date are the same. testFileHash is only called if date/time has changed.

That said, I can't understand how came 481.000 files, 497 Gb total are being checked for changes for 5 hours (!)  Xeon X3350, 6 Gb RAM, hardware RAID - not the most modern hardware, but it just shouldn't be **so** long!

Trying to investigate further...

**Comment by abraunegg** [comment]
It could be how the file lists to check are being collated & processed. At the moment it is performing a tree / branch walk which may not be the most efficient way in doing this.

Also please note - much of this branch of the client is all about fixing the defects of the 'skilion' codebase. Yes this is a performance defect, but I have a feeling that re-writing the application to be more multi-threaded for many processes & operations is what is required here.

**Comment by borouhin** [comment]
Interestingly enough, most of the time appeared to be spent by logging! Removing most often log.vlog calls in source reduced the time to check the same files from 5 hours to less than 2! It's also too slow, but much better.
I guess trying to open log file upon writing each line is also not the most efficient way of doing things.

**Comment by abraunegg** [comment]
agree on that - it should be opened once, and written to as required.

**Comment by abraunegg** [comment]
@borouhin 
Can you please help test this PR:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/239/head:pr239
git checkout pr239
make
make install
```

This PR provides the following enhancements:
* Change '--download' to '--download-only' to align with '--upload-only' 
* Change the logging to a separate file to not be the default so that excessive disk I/O does not occur (Issue #158)
* Close out Feature Request #108, by only enabling the local logfile when '--enable-logging' is used
* Close out Feature Request #212 by adding a new configuration option to specify the logging directory

To use a different log directory, add the following to `~/.config/onedrive/config`:
```
log_dir = "/path/to/location/"
```
Trailing slash required

**Comment by abraunegg** [comment]
PR #239 merged
