### ISSUE TITLE
Implement multithreading

### ISSUE THREAD

**Issue by NicTanghe** [abraunegg/onedrive#1585]
Hello,

Can u maybe implement multithreading ?

I know its a big ask i get the feeling that might make things faster.
I might b wrong and it might even already b implemented.

**Comment by abraunegg** [comment]
@NicTanghe 
> Hello,
> 
> Can u maybe implement multithreading ?
> 
> I know its a big ask i get the feeling that might make things faster.
> I might b wrong and it might even already b implemented.

Please can you review https://github.com/abraunegg/onedrive/issues/232 - which I guess you did not see.

Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
