### ISSUE TITLE
Feature Request: Mark partially-downloaded files

### ISSUE THREAD

**Issue by AnClark** [abraunegg/onedrive#1593]
**Is your feature request related to a problem? Please describe.**
Due to poor network, some files will fail on downloading and need a retry. However, those corrupted files are still named (also not marked) as if they did have downloaded successfully.

So when OneDrive client syncs, those partially-download files will also be uploaded. This could be severe that many files will be corrupted at last.

**Describe the solution you'd like**
Here's my ideas:
- Mark those partial-downloaded files by name (for example, if `foo-bar.pdf` failed to download, or download process were interrupted, it should be renamed into `foo-bar.pdf.partial`)
- Or, mark them in a database / configuration file.
- Or, simply remove them for the next download session (which is Git's behavior).

**Describe alternatives you've considered**
Auto-resuming partial downloads should be even better. (Curl and Aria2c behavior.)

**Additional context**
Perhaps doing a brief check for newly-downloaded files is essential. (Can be bypassed by argument.)

**Comment by abraunegg** [comment]
@AnClark 
Can you provide some detailed log evidence here?

When there is a download failure, the file 'should' be removed, as this is what was tested & confirmed as working. It could be you are running older client version ...

**Comment by AnClark** [comment]
Here's my reported client version:

```
➜  ~ onedrive --version
onedrive v2.4.13
```

**Comment by AnClark** [comment]
And here's a log when downloading a folder. I terminated the download process with **keyboard interrupt**, and the file still exists.

<details>
<summary>Log</summary>

```
➜  ~ onedrive --synchronize --download-only --single-directory '法学学习/法考主观题二战/框架图' --no-remote-delete --verbose
Using 'user' Config Dir: /home/anclark/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/anclark/OneDrive
Application version: v2.4.13
Account Type: personal
Default Drive ID: fc8fd21fba1359b5
Default Root ID: FC8FD21FBA1359B5!203
Remaining Free Space: 845316422
Fetching details for OneDrive Root
OneDrive Root exists in the database
Trying to restore the upload session ...
The file does not exist anymore
Initializing the Synchronization Engine ...
WARNING: The requested path for --single-directory does not exist locally. Creating requested path within /home/anclark/OneDrive
Syncing changes from this selected path: 法学学习/法考主观题二战/框架图
Syncing changes from selected OneDrive path ...
Getting path details from OneDrive ...
Applying changes of Path ID: FC8FD21FBA1359B5!15800
Updated Remaining Free Space: 845316422
Processing 219 OneDrive items to ensure consistent local state
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Remote change discarded - not in --single-directory sync scope (in DB)
Downloading file 法学学习/法考主观题二战/框架图/【BT学院】2021年法考：行政法框架.pdf ... 
Downloading  40% |oooooooooooooooo                        |   ETA   00:00:13 ^C
```
</details>

**Comment by abraunegg** [comment]
@AnClark 
So this requires a multi-part feature request | potential bug fix

1. Ensure that large downloaded files are done in a potentially resumeable fashion if the API supports this
2. Flagging partially downloaded files as .partial during file download, with rename to full file name on successful completion
3. Preventing .partial filename upload to prevent these partial files, if attempting to be uploaded, not uploaded as they are incomplete & invalid

**Comment by fMeow** [comment]
I have encounter the same issue, and frustratedly found my file corrupted.

I think the latter two (download to .partial first and avoid upload) is much more important to prevent file corruption during download and easy to implement. 

I am urgently in need of this fix and would like to help.

**Comment by fMeow** [comment]
Also, another approach is to use temporary direcory for download. Files can be first downloaded to a temporary folder (like /tmp/xxx in linux), and then move to the destination folder after completely downloaded. In this way, the feature No.3 (avoid uploading .partial files) can be auto resolved since there is no additional files in onedrive folder.

**Comment by abraunegg** [comment]
@fMeow 
Thanks for your inputs. Potentially will look at this post the v2.4.14 release

**Comment by steverweber** [comment]
a directory local to the onedrive mount with a name like `.partial` might be better than /tmp because crossing filesystem boundaries like partitions or mount points can be problematic. Also at some point people are going to start wanting to use one drive on network mounted storage that might be shared on multiple systems. So if not done already should have a .lock file created and checked to ensure only one demon is managing syncs at a time.

**Comment by Rz1010** [comment]
I agree under poor connection and if the file didn't finish download , when synchronization is requested under same session , no sync is done since a partial version with the same name already exists .
When session is closed and opened pr a --resync is provided , the previous partial file is renamed and a new version of the file started download from zero.
BTW I am using --download-only flag not to corrupt online files.

Would be solved if file is marked "partial" as stated before.

**Comment by abraunegg** [comment]
@Rz1010 
> I agree under poor connection ... 

Please rebuild your client from 'master' so that you are getting this fix: https://github.com/abraunegg/onedrive/pull/1789

This dramatically improves the situations where poor Internet connections were causing download issues.

**Comment by abraunegg** [comment]
@AnClark , @fMeow , @steverweber , @Rz1010 
Please can you test the following PR against this feature request:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1868/head:pr1868
git checkout pr1868
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.15-28-gdca7ae7` or greater.

**Comment by Rz1010** [comment]
@abraunegg Hello sir  , I tested PR1868 on my Manjaro Linux kernel 5.10 . I started a download from Onedrive to my local folder : the being-downloaded file is called XXX.partial indeed . I interrupted the downloaded and restarted it , it seems the download is restarting from 0%. 

I provide my log :


`[fireflood@rz onedrive]$ ./onedrive --synchronize --download-only --verbose --resync
Using 'user' Config Dir: /home/fireflood/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults

The use of --resync will remove your local 'onedrive' client state, thus no record will exist regarding your current 'sync status'
This has the potential to overwrite local versions of files with potentially older versions downloaded from OneDrive which can lead to data loss
If in-doubt, backup your local data first before proceeding with --resync

Are you sure you wish to proceed with --resync? [Y/N] y 

Deleting the saved application sync status ...
Checking Application Version ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/fireflood/OneDrive
Application version: v2.4.15-30-gd846356 //satisfied > 2.4.15-28
Account Type: personal
Remaining Free Space: 5361113071
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: FF7EF4CD345EF386!103
Updated Remaining Free Space: 5361113071
Number of items from OneDrive to process: 3
Downloading file Graduate_Viewbook.pdf ... 
Downloading  10% |oooo                                    |   ETA   00:06:36 ^C  // download interrupted by user

[fireflood@rz onedrive]$ ./onedrive --synchronize --download-only --verbose
Using 'user' Config Dir: /home/fireflood/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Checking Application Version ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/fireflood/OneDrive
Application version: v2.4.15-30-gd846356
Account Type: personal
Remaining Free Space: 5361113071
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: FF7EF4CD345EF386!103
Updated Remaining Free Space: 5361113071
Number of items from OneDrive to process: 3
Downloading file Graduate_Viewbook.pdf ... 
Downloading   0% |                                        |   ETA   --:--:--:^C   //downloaded restarts from null , not acknowledging the .partial

`

**Comment by abraunegg** [comment]
@Rz1010 

> I interrupted the downloaded and restarted it , it seems the download is restarting from 0%.

Unfortunately this is expected - resuming from a potential marker point is not going to be possible as the online file may have changed completely, thus invalidating the already downloaded content, chunks etc.

**Comment by Rz1010** [comment]
Is it possible to access the file's general information (Modified since (date)) specifically to check that ?? 
It would be an interesting feature to resume downloads/uploads from a previous point (like wget -c).

**Comment by abraunegg** [comment]
@Rz1010 
> Is it possible to access the file's general information (Modified since (date)) specifically to check that ??

No it is not - because the download of the file was not successful, thus, there is no record stored in the local cache DB that a file download was attempted, thus zero correlative information is available locally to compare with remote to determine such state.
