### ISSUE TITLE
OneDrive for business - Admin Consent

### ISSUE THREAD

**Issue by phillip-from-oz** [abraunegg/onedrive#16]
Hi,
Can you please tell me if you support "Admin Consent" as described:
https://docs.microsoft.com/en-au/azure/active-directory/develop/active-directory-devhowto-multi-tenant-overview#understanding-user-and-admin-consent
The reason that I need this is that I have thousands of accounts under our OneDrive for business, so the administrator will give admin consent to a set of users

**Comment by abraunegg** [comment]
The `prompt=admin_consent` is not currently included v2.0 OAuth that the client sends.

Suggestion here would be to test and try & report back on whether the current authorisation process works with your current approval process.

**Comment by phillip-from-oz** [comment]
In my "OneDrive for business", the administrator has:
1. Authorized skilion as a valid application
2. Authorized skilion to access my "OneDrive for business" account as admin consent

However I get an error when skilion tries to access my "OneDrive for business" acount.

So in short it does not work!

**Comment by abraunegg** [comment]
Can you post the `--verbose` output of what error is being sent back?

**Comment by awehrfritz** [comment]
I ran into the exact same problem with the exact same OneDrive for Business provider (i.e. at the same uni). Not sure if there is much to do on the client side, as the error message indicates that it is a server-side setting that needs to be changed.

@phillip-from-oz: Did you get it working in the end? I asked our IT services to fix this, but didn't get a response yet.

**Comment by abraunegg** [comment]
@phillip-from-oz 
Any update from your end as to if you have been able to get your admin to authorise tha application / URL?

**Comment by phillip-from-oz** [comment]
I'm trying to understand the whole process so can you please confirm my understanding.

I understand that this happens:
1. skilion uses oauth2 protocol & OpenID Connect protocol. skilion code uses the D language.
2. skilion was registered as an app for Microsoft "OneDrive for Business". skilion was registered as an multi tenant application.
    Microsoft gave you a client_id which I think is "22c49a0d-d21c-4792-aed1-8f163c982546"
3. When I run skilion on my Linux machine I need to get an authorisation code from "OneDrive for Business" in my tenant
     The request looks like:
     Endpoint tenant is "comon", that is for both personal onedrive and business onedrive
          See https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols#endpoints
     Scope:  files.readwrite  files.readwrite.all offline_access
     if I sign into my account sucessfully and I have given consent to the scope then go to the url "https://login.microsoftonline.com/common/oauth2/nativeclient" [redirect_uri]
4. I get a error from "OneDrive for Business"

Now I have signed in sucessfully to my "OneDrive for Business" tenant as if I go into another browser window I see my standard "OneDrive for Business".

So it seems there is a permissions problem.

The consents required do not seem to need "admin consent".
See https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference

So maybe when the app was registered it has asked for permissions that have not been given to me by my tenant admin. 

Questions:
1. When skilion was registered as an app for "OneDrive for Business", do you have to ask for permissions?
     If so what permissions are they?
     I have seen this example of app registration that seems to suggest that you ask for permissions:
     https://documentation.commvault.com/commvault/v11/article?p=41817.htm
2. Can an individual user within "OneDrive for Business", give consent to an app, give consent to permissions for that app?
3. The redirect_uri appears to be for a "native app". What is a "native app"?
     See https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-code

**Comment by phillip-from-oz** [comment]
I have a few questions:
1. Was skilion registered to use Azure AD version 2?
 https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-compare
2. To make it simple, I could register the app as single tenant in my tenant as single tenant.
Would I then need to change just client_id and secret_code? Where in the code would I find these?

**Comment by abraunegg** [comment]
> Questions:
> 1. When skilion was registered as an app for "OneDrive for Business", do you have to ask for permissions?
> If so what permissions are they?
> I have seen this example of app registration that seems to suggest that you ask for permissions:
https://documentation.commvault.com/commvault/v11/article?p=41817.htm
> 2. Can an individual user within "OneDrive for Business", give consent to an app, give consent to permissions for that app?
> 3. The redirect_uri appears to be for a "native app". What is a "native app"?
See https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-code

Will try to respond as best as possible here.

A1: I have no idea or visibility as to the process skilion used when registering the application for Personal or Business accounts.

A2: This is how OneDrive Personal Accounts work, however in my experience, after authenticating with a OneDrive Business Account, I am simply presented with the response URL.

A3: Native App in this sense would be a mobile application. I would classify this client as a 'web app' as all calls are made via HTTPS using curl

> I have a few questions:
> 1. Was skilion registered to use Azure AD version 2?
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-compare
> 2. To make it simple, I could register the app as single tenant in my tenant as single tenant.
Would I then need to change just client_id and secret_code? Where in the code would I find these?

A1: I have no idea sorry.

A2: The client ID is in `onedrive.d`:
```
string clientId = "22c49a0d-d21c-4792-aed1-8f163c982546";
```

However there is no secret code. By changing the clientId, you would effectively have a new 'client' that would need to be re-authorised into OneDrive Personal and OneDrive Business as a new application.

**Comment by dimk1** [comment]
I'm not sure if this is a similar kind of issue, but when I first run onedrive and launch the login I get the following string in my browser 

https://login.microsoftonline.com/common/oauth2/nativeclient?error=access_denied&error_description=AADSTS50005%3a+Device+platform+Unknown+used+by+the+user+is+an+unsupported+device+platform.+Supported+device+platforms+are%3a+iOS%2c+Android%2c+Mac%2c+and+Windows+flavors.%0d%0aTrace+ID%3a+49fe427b-a686-4729-a499-327f52060500%0d%0aCorrelation+ID%3a+740453c8-f7b5-4c93-99ec-b37dfdaa619b%0d%0aTimestamp%3a+2018-07-28+11%3a39%3a08Z

**Comment by abraunegg** [comment]
@dimk1 
Your issue is different. Your OneDrive service is being limited to what devices & systems your Administrator will allow to connect. Please refer to the FAQ (https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions) & https://github.com/abraunegg/onedrive/issues/13 for some details.

**Comment by abraunegg** [comment]
Closing this issue as it is more AD Administrator permissions related than a onedrive client bug
