### ISSUE TITLE
Feature Request: Environment Variables add authUrl and responseUrl

### ISSUE THREAD

**Issue by jackadam1981** [abraunegg/onedrive#1606]
**Is your feature request related to a problem? Please describe.**

After the first run, get authurl and responseurl save to file.
Two files can be used to store authentication information, which is very convenient.
However, the docker cannot use these two Environment .

**Describe the solution you'd like**
Upgrade entrypoint.sh to support automatic file generation of these two Environment  variables and log in with file verification information.

**Describe alternatives you've considered**
Store two files by myself and activate the function use other Environment  . just like ONEDRIVE_DEBUG .

**Additional context**
```
# Tell client to use file to login
if [[ $authUrl && $responseUrl ]];then
	echo $authUrl > /onedrive/conf/authUrl
	echo $responseUrl > /onedrive/conf/responseUrl
	ARGS=(--auth-files /onedrive/conf/authUrl:/onedrive/conf/responseUrl ${ARGS[@]})
fi
```

**Comment by abraunegg** [comment]
@jackadam1981 
Feel free to tackle a PR to resolve this issue within Docker
