### ISSUE TITLE
Running 5 hours still hasn't finished

### ISSUE THREAD

**Issue by colourful-land** [abraunegg/onedrive#1608]
### Bug Report Details ###
**Describe the bug**

By the Internet speed the sync should take around 1 hour. Still executing the first `-synchronize` after 5 hours.
**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`

Ubuntu 20.04

uname:

Linux thinkpad 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

*   Are you using a headless system (no gui) or with a gui installed?

no gui.

*   OneDrive Account Type

Personal. Free.

*   Did you build from source or install from a package?

OpenSuSE's build service for Ubuntu.

*   OneDrive Application Version: Output of `onedrive --version`

onedrive v2.4.13-1~np1

*   OneDrive Application Configuration: Output of `onedrive --display-config`

````
~$ onedrive --display-config
Configuration file successfully loaded
onedrive version                       = v2.4.13-1~np1
Config path                            = /home/a/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /var/local/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
````

*   Provide the version of curl you are using: Output of `curl --version`
* 
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3

*   Is your configured 'sync_dir' a local directory or a network mount point?

local.

*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 

ext4

*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time

OneDrive folder is accessible by mobile devices through their app and another OS X computer but they are not in use when this error occur. Also the error occurred while syncing a folder that is disused for years.

**To Reproduce**

Steps to reproduce the behavior if not causing an application crash:
1.  run `$ onedrive --synchronize --verbose --verbose > debug_output.log 2>& `
2.  Wait 5 hours.

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
[debug_output.zip](https://github.com/abraunegg/onedrive/files/7019172/debug_output.zip)

**Additional context**

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [ ] Verbose Log Output from your error
*   [x] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@colourful-land 
This is not a bug ... how long it takes for the application to run is dependent on a number of factors:
1. Number of files residing online
2. Internet access speed
3. Processing speed of device where the client is running

This is not a bug or issue - sorry
