### ISSUE TITLE
the client isn't seeing the "config" file (sync_dir)

### ISSUE THREAD

**Issue by Deviner75** [abraunegg/onedrive#1612]
### Bug Report Details ###
I just installed the client.
I did the following:
```
mkdir -p ~/.config/onedrive
cp ./config ~/.config/onedrive/config
```
uncommented the lines in the config "~/.config/onedrive/config":
```
sync_dir = "/home/disk_d/OneDrive"
# skip_file = "~*|.~*|*.tmp"
monitor_interval = "1000"
skip_dir = "Documents|Downloads|Work_sync"
# log_dir = "/var/log/onedrive/"
# drive_id = ""
```
But the sync started in this directory:
"/root/OneDrive/"
it looks like it doesn't see the config file.

**Application and Operating System Details:**
Linux fedora 5.13.12-200.fc34.x86_64 #1 SMP Wed Aug 18 13:27:18 UTC 2021 x86_64 x86_64 x86_64 
dmd-2.097.2
de: xfce
Built from source
OneDrive Account Type: personal

```
Configuration file
config file has been updated, checking if --resync needed
onedrive version                       = v2.4.13-13-ga73c911
Config path                            = /home/deviner/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/disk_d/OneDrive
Config option 'skip_dir'               = Documents|Downloads|Work_sync
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 1000
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 20
Config option 'upload_only'            = true
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
#sync_list supports comments
#The ordering of entries is highly recommended - exclusions before inclusions
#Exclude temp folders under Documents
#!Documents/temp*
#Exclude my secret data
#!/Secret_data/*
#Include my Backup folder
#Work_sync/Backup
Business Shared Folders configured     = false
```
curl 7.76.1 (x86_64-redhat-linux-gnu) libcurl/7.76.1 OpenSSL/1.1.1k-fips zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.43.0
Release-Date: 2021-04-14

Is your configured 'sync_dir' a local directory or a network mount point?
- local

What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
- btrfs

Explain your entire configuration setup:
- I have my onedrive on the windows machine with some shared folders with other people.
(the windows machine was turned off at the moment of testing)

**Note:** Please generate a full debug log whilst reproducing the issue:
emailed

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
command: sudo onedrive --synchronize --verbose --resync
Application Log Output:
```
[@fedora onedrive]$ sudo onedrive --synchronize --verbose --resync
Using 'user' Config Dir: /root/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /root/OneDrive
```

**Comment by abraunegg** [comment]
@Deviner75 
This is your problem:
```
sudo onedrive --synchronize --verbose --resync
```

You are running the client via sudo .... you do not need to do this. Because you are running the client via sudo, you are making the client run as 'root' - not the normal user account you are using - thus, of course it will not see your configuration file in your users directory.

Your options to solve:
1. Dont use sudo to run the application
2. Configure the application correctly for the root user - but then all files will be downloaded as 'root' - thus, cause access permission issues for your normal user account

**Comment by Deviner75** [comment]
@abraunegg I see :) really appreciate the help!
it worked.
I'm a new linux user and still learning about it :)
