### ISSUE TITLE
How to integrate with github actions?

### ISSUE THREAD

**Issue by ukreddy-erwin** [abraunegg/onedrive#1613]
We have integrated onedrive client for linux with our jenkins node so that, it will sync to the shared folders once our build artifacts are created.

Is there anyway to link this with github actions also, as the slave in github actions will be created a new one everytime the build is triggered. Is there any option to just dump the config files there?

**Comment by abraunegg** [comment]
@ukreddy-erwin 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

Specifically to your 'question' you need to seek support with github actions - please review https://support.github.com/features/actions
