### ISSUE TITLE
slow sync

### ISSUE THREAD

**Issue by Deviner75** [abraunegg/onedrive#1616]
### Bug Report Details ###
The sync for me is very slow. I need to sync about 17gb. Basically a root backup. it should take at max a couple of hours on my win machine.
`onedrive --synchronize --verbose`

![Peek 2021-09-02 09-39](https://user-images.githubusercontent.com/31226325/131883786-a1abae66-8a3f-44b5-8e5b-35cab505a6fe.gif)

```
[DEBUG] File Size: 120872 Bytes
[DEBUG] Upload Duration: 0.7 Seconds
[DEBUG] Upload Speed: 0.164675 Mbps (approx)

```

**Application and Operating System Details:**
Linux fedora 5.13.12-200.fc34.x86_64 #1 SMP Wed Aug 18 13:27:18 UTC 2021 x86_64 x86_64 x86_64 
dmd-2.097.2
de: xfce
Built from source
OneDrive Account Type: personal

```
Configuration file successfully loaded
onedrive version                       = v2.4.13-13-ga73c911
Config path                            = /home/deviner/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/disk_d/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 3600
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 20
Config option 'upload_only'            = true
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
```
curl 7.76.1 (x86_64-redhat-linux-gnu) libcurl/7.76.1 OpenSSL/1.1.1k-fips zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.43.0
Release-Date: 2021-04-14

Is your configured 'sync_dir' a local directory or a network mount point?
- local

What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
- btrfs

Explain your entire configuration setup:
- I have my onedrive on the windows machine with some shared folders with other people.
(the windows machine was turned off at the moment of testing)

**Comment by abraunegg** [comment]
@Deviner75 
This is not a bug or issue with this client - sorry.

This is impacted by the following factors:
* Your Internet access speed
* The speed of your CPU
* How the client utilises the Curl library for each operation
* No multi-threaded capability at present - see: https://github.com/abraunegg/onedrive/issues/232
