### ISSUE TITLE
Feature Request: Adopt a new scanning method

### ISSUE THREAD

**Issue by Do1e** [abraunegg/onedrive#1617]
I found that this onedrive client scan **all of** the files and directories while synchronizing.
It doesn't matter if there are not many files, but it will cause slow synchronization when there are a lot of files and directories.
Maybe adopting a new scanning method will be better, like official onedrive, or it can't be called scanning.

**Comment by abraunegg** [comment]
@Do1e 
Unfortunately this is how this client works when ensuring the local data is in-sync with OneDrive online. Great effort has gone to ensure that the performance & speed of the client during this part of the operation.

If you use `--resync` you also, force the scanning of all objects online + local. In normal operation, only the 'delta' changes online are scanned, but the contents of the local DB is still worked through to ensure the local state + local changes are correctly replicated to OneDrive online.

The scope of what is checked can also be limited by configuration options:
* skip_dir
* skip_file
* sync_list
* `--single-directory`

Closing this issue as this is how this client works.
