### ISSUE TITLE
no log file,no way to see working status

### ISSUE THREAD

**Issue by apaes** [abraunegg/onedrive#162]
Hi, I have cloned the repo and installed on a Debian system as per the instructions in readme.md. It built correctly and installed without a problem, it's running as a service through systemd. Unfortunately there is no log in /var/log/onedrive/ as stated in the documentation. Also, journalctl --user-unit onedrive -f complains about lack of permissions, calling this under sudo says started 2days ago but there is no other information. This is very important as I believe there are errors in the sync because new files do not show online.

**Comment by abraunegg** [comment]
Have you check your permissions for the log directory to ensure that the user's group has correct write access?

If the application cannot write to the log file location, it will default to the users home directory.

> This is very important as I believe there are errors in the sync because new files do not show online.

Stop the service and run the application manually to confirm your suspicions:

```
onedrive --synchronize --verbose
```

If an error is being generated, the above command will help identify what is going on. Once all is working, then re-enable the service.

**Comment by apaes** [comment]
Thanks abraunegg, that was it, such a simple thing and I just couldn't figure it out. Everything is working perfect now. By following your suggestion i was able to find out that the initial sync had not terminated and that's why my local changes were not being reflected online. Thanks for the help and for maintaining the software.
