### ISSUE TITLE
Feature Request: Webhook integration for real-time remote OneDrive updates

### ISSUE THREAD

**Issue by Lyncredible** [abraunegg/onedrive#1620]
👋  I am teleporting from skilion/onedrive#360. I finally have some free time to look into implementing the webhooks.

The logic seems to be straightforward, but I am having trouble with D lang and web servers. In particular, I would like to get advice on:

1.  What is the best, minimal web server library to use in D lang? The default choice is [vibe.d](https://vibed.org/). Is it good?
2.  How to add said web server library to this project? vibe.d suggests using dub, but dub is not used in this project. So what is the recommended path here?

For completeness, here is the text from my original feature request:
> OneDrive allows apps to register webhooks to listen for updates: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/subscription_post_subscriptions.
> 
> It would be nice to leverage this to enable faster pull when running as a daemon.
>
> To implement this, I think the changes are:
>
> - Register webhook with a configurable endpoint (user may want to run this behind nginx, for example)
> - Configurable client_id so that webhooks don't cross fire.
> - Listen to incoming webhooks and trigger pull.

**Comment by abraunegg** [comment]
@Lyncredible 
Many thanks for looking into adding something like this.

> What is the best, minimal web server library to use in D lang? The default choice is vibe.d. Is it good?

I do not know - sorry. My best advice here would be post a question on the D forums, or jump into the D IRC channel and post a question regarding what would be the most suitable web server library to implement webhooks. A suitable web server for 'pages' might not be the same suitable server for delivering API endpoints - it might be, but it might also not be. When I also investigated this, using webhooks also required the registration of a unique URL for the client|server architecture to utilise - something which I could not quite work out how best to implement.

> How to add said web server library to this project? vibe.d suggests using dub, but dub is not used in this project. So what is the recommended path here?

From what I have seen, dub is essentially a wrapper. All you will need to do is ensure all the *.d files that are needed, are in the source tree, then, ensure that the Makefile knows where they are, and ensure then that they are pulled in at compile time.
