### ISSUE TITLE
Docker volume for data (${ONEDRIVE_DATA_DIR})

### ISSUE THREAD

**Issue by svatos-jirka** [abraunegg/onedrive#1629]
Is it possible to use docker volume as data folder?

with best regards, jiri

**Comment by abraunegg** [comment]
@svatos-jirka 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
