### ISSUE TITLE
ignore folder when special file present

### ISSUE THREAD

**Issue by Alwinius** [abraunegg/onedrive#163]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be very useful if one could create a file in a folder to exclude the folder and subfolders from syncing. For example on Android, media players will ignore folders that contain a .nomedia file. In my case I sync source code files but compiled artefacts should not be synchronised. 

**Describe alternatives you've considered**
At the moment you can can specify folders to skip in the configuration file. That's a bit complicated though and not something you want to do every day, especially when the paths are long.

**Comment by abraunegg** [comment]
@Alwinius 
Potentially there are 2 ways to solve this at present:
1. Utilise 'sync_list' to specify the folder you want to sync, all others will be excluded
2. Utilise 'skip_dir' (PR #388) to specify what directories to skip (full path needed relative to 'sync_dir')

**Question:**
Whilst I totally understand the use case behind this request, should this be a 'default' action if a file called '.nosync' is found, or should the 'do not sync this folder' only be actioned if '.nosync' & a flag is passed in?

I am leaning towards needing the '.nosync' & flag to activate rather having this as a default action.

Can you provide some feedback / comment please

**Comment by norbusan** [comment]
I searched a bit and it seems the `.nosync` extension to files or directories blocks syncing on iCloud. Maybe it is used in other products, too, but I haven't seen much mentioning otherwise.

**Comment by norbusan** [comment]
Ah, and I agree with @abraunegg that the .nosync should stop syncing only when a special cmdline arg/config file option is set. Not by default.

**Comment by Alwinius** [comment]
I don't mind either way. What are your reasons that you don't want to enable it by default?

**Comment by norbusan** [comment]
@Alwinius My expectation is that without any configuration, *every* file and directory should be synced.

**Comment by abraunegg** [comment]
> @Alwinius My expectation is that without any configuration, _every_ file and directory should be synced.

Agreed

**Comment by Alwinius** [comment]
Ok, that makes sense.

**Comment by abraunegg** [comment]
@Alwinius 
Please can you help test the following PR which implements this feature:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/390/head:pr390
git checkout pr390
make
```

If you are able to test this PR, and report back that would be greatly appreciated.

Please use this against a **TEST** OneDrive account - as I would currently call this feature **BETA** quality as I have only tested it. 

The feature currently does what it "should" do in my test cases, however this needs some extensive testing & confirmation that there is no undesirable bug which could cause data to be lost.

**to use feature:**
Pass in `--check-for-nosync` when using `--synchronize`. Not currently tested or checked for use with `--monitor`

Add an empty file called `.nosync` into the directory to skip. Skipping of that directory will now occur, stopping the upload of any new / changed files. Existing files already uploaded & stored in the database cache will be unaffected.

**Comment by Alwinius** [comment]
I did a quick test and it looks good so far. I will think about more test cases over the next few days.

**Comment by abraunegg** [comment]
@Alwinius 
I did find an issue with the PR - if the flag was not passed in, there was a config option issue. This is fixed in the latest version of the PR.

**Comment by abraunegg** [comment]
Closing case as PR #390 is merged
