### ISSUE TITLE
dead link in https://github.com/abraunegg/onedrive/wiki/OneDrive-Client-Multi-Account-Configuration-Assistance

### ISSUE THREAD

**Issue by dinkumsoftware** [abraunegg/onedrive#1630]
### Bug Report Details ###
**Describe the bug**
Dead link on https://github.com/abraunegg/onedrive/wiki/OneDrive-Client-Multi-Account-Configuration-Assistance

    Refer to the following document.
    https://github.com/abraunegg/onedrive/blob/master/docs/Office365.md

I think document got renamed:
    Rename Office365.md --> SharePoint-Shared-Libraries.md which better describes this document
    2.4.9 - 2020-12-27
```
tc@gizmo:~$ onedrive --version
onedrive v2.4.10-0~202102221319~ubuntu20.04.1
```

**Comment by abraunegg** [comment]
@dinkumsoftware 
Thanks for pointing this out - I thought I had fixed all of those.

Additionally, you are using v2.4.10 - which is unsupported. Please update your client as per https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md

**Comment by abraunegg** [comment]
Closing issue as wiki page is updated
