### ISSUE TITLE
Can't authorize the client

### ISSUE THREAD

**Issue by davidromerot** [abraunegg/onedrive#1639]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
Upon installation, the first run of onedrive fails to authorize the client.

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
Ubuntu 20.04
Linux XPS-Ubuntu-DR 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?
no
*   OneDrive Account Type
personal
*   Did you build from source or install from a package?
no
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
*   OneDrive Application Version: Output of `onedrive --version`
 onedrive v2.3.13-1build2
*   OneDrive Application Configuration: Output of `onedrive --display-config`
onedrive version                    = v2.3.13-1build2
Config path                         = /home/dromero/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/dromero/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
*   Provide the version of curl you are using: Output of `curl --version`
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
*   Is your configured 'sync_dir' a local directory or a network mount point?
local
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
It's ext4
sda                                                                                   
├─sda1                                                                                
└─sda2       ntfs     DATA        0AEC971FEC97045B                      163.5G    91% /mnt/DATA
sr0                                                                                   
nvme0n1                                                                               
├─nvme0n1p1  vfat     ESP         CE50-741D                             415.9M    16% /boot/efi
├─nvme0n1p2                                                                           
├─nvme0n1p3  ntfs     OS          38108CD6108C9C8E                       24.2G    90% /mnt/WIN10
├─nvme0n1p4  ntfs                 AC0A07EC0A07B1FE                                    
├─nvme0n1p5  ext4                 5c840109-c313-4cdf-80e5-f245b54b5c18   44.1G    50% /
├─nvme0n1p6  swap                 3cab7dd8-925f-42df-af50-19f8c2211bc6                [SWAP]
├─nvme0n1p7  ext4                 126e7b65-e0fb-442a-9deb-374426bdfea5   16.4G    80% /home
├─nvme0n1p8  ntfs                 784EFF9D4EFF527C                                    
├─nvme0n1p9  ntfs     Image       AE3EB8203EB7E00F                                    
└─nvme0n1p10 ntfs     DELLSUPPORT 60EADBF7EADBC78
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
I sync this folder to another linux computer (also with your client), and to my Windows desktop
**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

This is the full debug log file:
```
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /home/dromero/OneDrive
Initializing the OneDrive API ...
[DEBUG] Downgrading all HTTP operations to HTTP/1.1 by default
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: 
```
As you see, it fails when I try to authorize. Hence, the instructions for creating the debug log did not work (it is waiting for user input).

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```
```
dromero@XPS-Ubuntu-DR  ~  $ onedrive --verbose
Using Config Dir: /home/dromero/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=M.R3_BAY.c3d477c1-4bc2-f70b-e640-a11ebb40c114
OneDrive returned a 'HTTP 400 - Bad Request' - gracefully handling error
onedrive.OneDriveException@src/onedrive.d(874): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "7fb22dd4-3f6b-4c9e-a464-a7f019691e75",
    "error": "invalid_grant",
    "error_codes": [
        70000
    ],
    "error_description": "AADSTS70000: The provided value for the 'code' parameter is not valid.\r\nTrace ID: fd796f94-3ed2-43a6-8a12-4db2be0d4400\r\nCorrelation ID: 7fb22dd4-3f6b-4c9e-a464-a7f019691e75\r\nTimestamp: 2021-09-27 15:55:08Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=70000",
    "timestamp": "2021-09-27 15:55:08Z",
    "trace_id": "fd796f94-3ed2-43a6-8a12-4db2be0d4400"
}
----------------
??:? [0x55e2b80899d9]
??:? [0x55e2b8088cb5]
??:? [0x55e2b8089b65]
??:? [0x55e2b8087f58]
??:? [0x55e2b80878c5]
??:? [0x55e2b80957a8]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7fdba421a9db]
??:? _d_run_main2 [0x7fdba421a7ee]
??:? _d_run_main [0x7fdba421a65d]
??:? __libc_start_main [0x7fdba3e060b2]
??:? [0x55e2b80605ed]
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@davidromerot 
This is your problem: onedrive v2.3.13-1build2

This means you installed the onedrive client from Ubuntu Universe which is not supported. This is why you have this issue, but you say above that you did not install from a package .....

You must solve this by:
1. Uninstalling the application if also compiled from source via using `make uninstall` - that is if you installed via source code.
2. Follow the *correct* instructions for installing on Ubuntu as per https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md and https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md
