### ISSUE TITLE
**Operation not permitted** Error but everything synchronise fine

### ISSUE THREAD

**Issue by lbarbierato** [abraunegg/onedrive#164]
I create a `config` file in `˜/.config/onedrive/` like this:

`sync_dir = "/mnt/disk01/OneDrive"`

This folder is mounted and is shared with Windows 10. It has root permissions. When I launch one drive from terminal:

`sudo onedrive --synchronize`

Everything works fine and all my data are synchronised correctly.

When I try to run the daemon with systemd, I experience this error trying to add a new file from another PC:

systemd[1341]: Started OneDrive Free Client.
onedrive[2760]: Initializing the Synchronization Engine ...
onedrive[2760]: Initializing monitor ...
onedrive[2760]: OneDrive monitor interval (seconds): 5
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive …
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Downloading file STATUTO DDR.pdf ... done.
**onedrive[2760]: STATUTO DDR.pdf: Operation not permitted**
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Deleting item STATUTO DDR.pdf
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Downloading file STATUTO DDR.pdf ... done.
**onedrive[2760]: STATUTO DDR.pdf: Operation not permitted**
onedrive[2760]: Syncing changes from OneDrive ...
onedrive[2760]: Syncing changes from OneDrive ...

But when I take a look to the folder in my Ubuntu, the file is present. Any way to solve this bug?

Kind regards,
Luca

**Application and Operating System Details:**
- OS: Ubuntu 18.04
- Application version: v2.1.2-1-g4dfdd18
- OneDrive Account Type: Office 365 A1 Plus for faculty
- DMD v2.082.0

**Comment by abraunegg** [comment]
This is your problem:

sudo onedrive --synchronize

All your files downloaded have the wrong file permissions for your user

**Comment by lbarbierato** [comment]
I just tried to run the service and again the same behaviour:

onedrive[6200]: Syncing changes from OneDrive ...
onedrive[6200]: Downloading file STATUTO DDR copy.pdf ... done.
onedrive[6200]: STATUTO DDR copy.pdf: Operation not permitted
onedrive[6200]: Syncing changes from OneDrive ...

I find the file in the  /mnt/disk01/OneDrive folder.

**Comment by abraunegg** [comment]
You have a permissions issue - this is not a problem with the client
