### ISSUE TITLE
Sync a SharePoint library with --single-directory <lib> together with --syncdir works but creates an empty <lib> dir

### ISSUE THREAD

**Issue by ceztko** [abraunegg/onedrive#1645]
### Bug Report Details ###
I'm trying to manually sync a SharePoint library that is linked within a OneDrive account. I'm using both `--single-directory` and `--syncdir` parameters. The sync works, even without the need to specify a `drive_id` as described [here](https://github.com/abraunegg/onedrive/blob/master/docs/SharePoint-Shared-Libraries.md) but a spurious directory with the name of the SharePoint library is created.

**To Reproduce**

1. Have an account with a SharePoint library linked, as in the following example:
![image](https://user-images.githubusercontent.com/3037449/135711320-482923e1-7bd6-4261-8431-4f3163f5da4c.png)

2. Connect the OneDrive account to the client;
2.  Synchronize the library with the following command:
`onedrive --synchronize --resync --download-only --single-directory "Documenti" --syncdir "~/test"`

The synchronization works flawlessly but a spurious/empty "Documenti" directory is created.

**Expected behavior**

The sync actually works exactly the way I want it to be: all the content of the library is synced inside the specified `--syncdir`, without intermediate folders. What I don't want is the creation of the empty directory with the name of the SharePoint library.

**Complete Verbose Log Output**

Application Log Output:
```bash
Using 'user' Config Dir: /home/administrator/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/administrator/test
Application version: v2.4.13-15-gb778141
Account Type: business
Default Drive ID: b!lZShaKReWUG83y-DXpqx1tplW29h-vhMlpb0ts03QirCxXKHpWEUTbmhQ-hmIKVF
Default Root ID: 01FIIP5DV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1099508147187
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
WARNING: The requested path for --single-directory does not exist locally. Creating requested path within /home/administrator/test
Syncing changes from this selected path: Documenti
Syncing changes from selected OneDrive path ...
Getting path details from OneDrive ...
Applying changes of Path ID: 01FIIP5DX3ZDG7KAFPOJDYBWLY4FPRZF7W
Updated Remaining Free Space: 1099508147187
Number of items from OneDrive to process: 4
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Applying changes of Path ID: 01OK6OENN6Y2GOVW7725BZO354PWSELRRZ
OneDrive quota information is set at zero, as this is not our drive id, ignoring
Processing 19 OneDrive items to ensure consistent local state
Creating local directory: [...]
Downloading file [...]
[...]
```

The warning `WARNING: The requested path for --single-directory does not exist locally` seems to be relevant.

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
Ubuntu 18.04.3 LTS
```Linux lanmaster 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```

*   Are you using a headless system (no gui) or with a gui installed?
Headless
*   OneDrive Account Type
Microsoft 365 basic
*   Did you build from source or install from a package?
Source, git b778141
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
v2.097.2
*   OneDrive Application Version: Output of `onedrive --version`
onedrive v2.4.13-15-gb778141
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
onedrive version                       = v2.4.13-15-gb778141
Config path                            = /home/administrator/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/administrator/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
curl 7.58.0 
*   Is your configured 'sync_dir' a local directory or a network mount point?
Local (for now)
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
ext4

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Application and Operating System Details provided in full
*   [X] Reproduction steps (if applicable)
*   [X] Verbose Log Output from your error
*   [No] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@ceztko 
> I'm trying to manually sync a SharePoint library that is linked within a OneDrive account.

SharePoint links, added to your OneDrive folder using 'Add Shortcut to My Files' is not supported. This is a OneDrive API issue as the API does not support them. Refer to https://github.com/OneDrive/onedrive-api-docs/issues/1427 for further details.

This is why an empty "Documenti" directory is created.

The *only* way to support SharePoint libraries is to configure as per https://github.com/abraunegg/onedrive/blob/master/docs/SharePoint-Shared-Libraries.md

This is not a bug, this is not something that I can solve, this is an API issue - sorry.

**Comment by ceztko** [comment]
Thank you for the quick reply! The interesting thing here is that, disregarding of the fact that you can't explicitly support SharePoint links because of web API limitations in the regular synchronization, the sync operation here at least appears to work, possibly because of the use of `--single-directory` switch! I discovered this seems to be accidental, as per the behavior of the `--syncdir` parameter which would like to reconstruct the whole hierarchy, even when the `--single-directory` switch is used. Would it be feasible to add a semantics to synchronize to a target directory without necessarily recreating the OneDrive hierarchy? In this way you could just ignore the fact that the supplied `--single-directory` is a link or not.

To elaborate more, this would have the same semantics of:
```
 rsync -av --delete src/ dest/
```

Which synchronize all the content of `src/` inside `dest/` (doesn't create the `src `directory inside `dest/`).

**Comment by ceztko** [comment]
Actually, you can forget my last comment. After your client has served me well for many years, I am changing the infrastructure of my backup solution and I'm finding the features of [rclone](https://rclone.org/) to fit better what I am trying to achieve. I'm not finding equivalent semantics in your client, so I guess your are simply not interested in having them in the set of features you intend to maintain, which is fine. Thank you again for the quick help.

**Comment by abraunegg** [comment]
@ceztko 
> The interesting thing here is that, disregarding of the fact that you can't explicitly support SharePoint links because of web API limitations in the regular synchronization, the sync operation here at least appears to work, possibly because of the use of `--single-directory` switch!

No - this will be due to you using `--resync` - as this deletes your local database cache as to what is in sync. You should only ever use that if the application tells you to. The reason why you have to use is it because you are setting your `--syncdir` as `"~/test"`

With your full command as: `onedrive --synchronize --resync --download-only --single-directory "Documenti" --syncdir "~/test"`

You are telling the client to download only `OneDriveRoot/Documenti` -> `~/test/Documenti` folder  ... the problem here is that `Documenti` online is a SharePoint Folder linked with 'Add Shortcut to My Files' thus all the normal API data to access this folder does not exist in the API responses.

Now `--single-directory` does have some extra logic in it to detect if the OneDrive folder is 'local driveId' or 'remote driveId'  - but I am surprised this was working for you in this manner. 

> Would it be feasible to add a semantics to synchronize to a target directory without necessarily recreating the OneDrive hierarchy?

This is not possible as the target has to exist locally & remotely:
* To ensure that the file source exists
* To ensure that the destination exists
* To ensure that the data is copied correctly & without data loss

If you feel that this can be improved, submit a feature request .. or how about contribute back?

> After your client has served me well for many years, I am changing the infrastructure of my backup solution

Thanks for using the client.

> I'm not finding equivalent semantics in your client, so I guess your are simply not interested in having them in the set of features you intend to maintain, which is fine.

I guess you do not communicate with other people who live in other timezones often .... I am not going to respond to things when it is late into the night .....

Best of luck using rclone - last time i checked they did not handle all the SharePoint oddities with how SharePoint modifies files ... so .. potential you will get into some data loss scenarios.
