### ISSUE TITLE
Question: Handling Linux symlinks on a dual-boot setup

### ISSUE THREAD

**Issue by gctypo** [abraunegg/onedrive#1648]
I'm dual-booting EndeavourOS with Windows 10. I have it set up such that I have a "shared" partition where I store documents/music/projects/etc - platform-independent files. Most of these files are with my OneDrive folder. I still use Windows from time to time, and while it isn't my main OS anymore, I do use it in segments upwards of several weeks sometimes. I have Microsoft's OneDrive client set up to that folder on Windows, and am trying to set up abraunegg/onedrive for that folder on Linux.

Due to where certain projects are placed, and how I frequently work with files from different locations within this OneDrive folder, I've been setting up symlinks between them. The thing is, symlinks in Linux are different than symlinks in Windows, and are definitely different than Windows shortcuts. MS's OneDrive doesn't exactly provide a lot of options, so if it sees a Linux symlink I've set up it just sees it as some extensionless file and uploads it as an extensionless file. But when I boot back to Linux and run a sync in abraunegg/onedrive, it sees that extensionless file in cloud storage, attempts to download it, and throws an error because it conflicts with what it sees as a *directory* of the same name, since it sees the symlink and tries to dereference it for contents inside.

I seem to have a few options:
1. Rely entirely on abraunegg/onedrive and stop using MS OneDrive for syncing, and turn off symlink uploads.
2. Ignore the errors and hope no shenanigans occur regarding the symlinks and conflicts that arise.
3. Stop using Linux symlinks within OneDrive, entirely.

Option 1 seems like the least problematic option, but if there was a way to get abraunegg/onedrive to not dereference symlinks and instead treat them as plain files (much like MS OneDrive treats Windows LNK shortcuts), that seems like it would alleviate this problem entirely. Is this at all possible?

---

**Setup:**

*onedrive-abraunegg 2.4.13-1*
EndeavourOS, kernel 5.14.9-arch2-1, zsh 5.8, KDE Plasma 5.22.5

**Comment by abraunegg** [comment]
@gctypo 
Please follow the correct support process as detailed here:

https://github.com/abraunegg/onedrive#have-a-question
https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
