### ISSUE TITLE
SystemD Service File Hardening

### ISSUE THREAD

**Issue by SchoolGuy** [abraunegg/onedrive#1657]
**Is your feature request related to a problem? Please describe.**

The SUSE internal Security Team has proposed by a bot that we introduce more options to harden the SystemD Service.

**Describe the solution you'd like**

Review the following request in the OBS and if okay, I would create an upstream PR: https://build.opensuse.org/request/show/925119?notification_id=27973920

**Describe alternatives you've considered**

Declining the Submitrequest from OBS: Not feasible since security hardenings should be included if possible.

**Additional context**

None

**Comment by abraunegg** [comment]
@jsegitz , @SchoolGuy 
No worries - please submit a PR for the required changes.

**Comment by abraunegg** [comment]
@jsegitz , @SchoolGuy
Any update on raising a PR for this?

**Comment by SchoolGuy** [comment]
Yeah we broke it in Tumbleweed. I think the general request is still very valid but it needs more finetuning. Give me a few days until I have something working.

**Comment by SchoolGuy** [comment]
Okay. I tested myself with my work Business Account the new hardenings. We had to dial back a lot but now you we have a working out of the box experience. I will open a PR for this in the following minutes.
