### ISSUE TITLE
Support structured logging

### ISSUE THREAD

**Issue by tanaga9** [abraunegg/onedrive#1672]
Support structured logging for parse logs.
(Add some command line options.)

As a background, I'm trying my own approach to WebGUI. (#1668)
https://github.com/tanaga9/docker-onedrive-webui

I think the core(main) features and the GUI should be separated.
So I need to connect the GUI and CUI in some way.

One of the methods is structured logging (JSON logs).

Here is an example of parsing the logs (by regexp) (Because there is no structured logging yet)

- [Authorize](https://github.com/tanaga9/docker-onedrive-webui/blob/61a56bbf6dee61a3a4fc83df3717ce2bd5d7b9ac/OneDriveLogin.ipynb)
- [Show pretty log](https://github.com/tanaga9/docker-onedrive-webui/blob/61a56bbf6dee61a3a4fc83df3717ce2bd5d7b9ac/OneDriveLogs.ipynb)

**Comment by abraunegg** [comment]
@tanaga9 
Whilst I appreciate your desire to work on a GUI, doing something like this (structured logging) does not make much practical sense. Using JSON files for config - that is is different matter.

Suggest you review https://github.com/abraunegg/onedrive/wiki/External-Enhancements-to-the-OneDrive-Linux-Client in regards to some of the other external enhancements that have been developed thus far.

**Comment by tanaga9** [comment]
Thanks @abraunegg

This time, I used GUI as an example, but the effect of structured logging is not limited to that (rather, GUI is the purpose of heresy).

If you want the log to be read by a machine (not a human) on some occasion, remember the structured log.
