### ISSUE TITLE
Allow to sync sync_dir to a specific remote folder

### ISSUE THREAD

**Issue by sromeroi** [abraunegg/onedrive#1674]
I just installed the OneDrive client in Linux Mint from OpenSuSE build service and couldn't find an option to synchronize "~/OneDrive" to a folder named "DesktopSync" in my OneDrive storage.

My OneDrive storage keeps right now several "backup" folders from a NAS and I don't want to synchronize them, just a simple sync between my laptop (~/OneDrive folder) and a remote folder in OneDrive (/DesktopSync):

(local) ~/OneDrive <---> (remote) /DesktopSync

(which will keep a file sync between my OneDrive folder and the DesktopSync folder in the remote Service)

Instead of:

(local) ~/OneDrive <---> (remote) /

(which will sync to my local computer all the folders in the root of the OneDrive service, including my NAS backup, Photo uploads, and some folders I don't want to be synced).

I also checked if skip_dir allowed to specify remote folders but it looks it's meant for local folders (I would skipped all remote folders but for "/DesktopSync").

Is this possible with the current client?

Thanks.

**Comment by abraunegg** [comment]
@sromeroi 
This should have been opened as a discussion. Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
