### ISSUE TITLE
PIPE Error message

### ISSUE THREAD

**Issue by Remski** [abraunegg/onedrive#1676]
Hello all,

Have finally gotten round to installing this on Manjaro gnome

Got everything working well and managed to sync a few directories (manually for now)

However I did quite a bit of tidying up once replicated locally (using DupeGuru to remove dupes and then re-arranging files where the should go

Nopw I keep getting what I suspect is a timeout whenever I try to sync back the changes

The error message is simply PIPE x" with a timestamp

![image](https://user-images.githubusercontent.com/76783886/140663004-70742286-cc50-41e4-a21c-9ed258e3afd3.png)

Can any one advise on what this means and what I can do to prevent it in future?

Many thanks
R

**Comment by abraunegg** [comment]
@Remski 
This should have been opened as a discussion. Please follow the correct support process as detailed here:

https://github.com/abraunegg/onedrive#have-a-question
https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
