### ISSUE TITLE
Folder moving is not updated

### ISSUE THREAD

**Issue by ukreddy-erwin** [abraunegg/onedrive#1678]
In the onedrive shared folders, I synced a folder called Jenkins.

In that, I synced only the Jenkins/LatestBuilds folder

Today I moved some of the subfolders of Jenkins\LatestBuilds to Jenkins\OldBuilds from Onedrive website in through browser.

And then I synced using the onedrive sync command again.

`onedrive --synchronize --verbose --verbose --sync-shared-folders --single-directory Jenkins --confdir ~/.config/onedrive-business`

But the folders still there in the LatestBuilds folder of linux machine.

So, I deleted a folder and synced to check.

But it got deleted in the Jenkins\OldBuilds folder this time.

It seems, even though we moved folders to a different folder, the onedrive client still pointing to the same contents

**Comment by abraunegg** [comment]
@ukreddy-erwin 
If you are going to raise an issue, please follow the correct process ... 
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

It is *VERY* difficult to advise what is going on if you do not follow the correct process.
