### ISSUE TITLE
Can't reauthorize after password change

### ISSUE THREAD

**Issue by arbasel** [abraunegg/onedrive#168]
### Bug Report Details ###
**Describe the bug**

**Application and Operating System Details:**
    OS: Linux baselmania.com 4.17.19-200.fc28.x86_64 #1 SMP Fri Aug 24 15:47:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (Fedora 28)
    Gnome Version 3.28.2
    Application version: Version 3.28.2
    OneDrive Account Type: Home (Family)
    DMD or LDC compiler version: DMD64 D Compiler v2.073.1

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. Changed my Onedrive Password

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
Sep 12 17:53:28 baselmania.com systemd[2796]: Started OneDrive Free Client.
Sep 12 17:53:28 baselmania.com onedrive[25704]: Initializing the Synchronization Engine ...
Sep 12 17:53:30 baselmania.com onedrive[25704]: Authorization token invalid, use --logout to authorize the client again
Sep 12 17:53:30 baselmania.com systemd[2796]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 17:53:30 baselmania.com systemd[2796]: onedrive.service: Failed with result 'exit-code'.
Sep 12 17:53:33 baselmania.com systemd[2796]: onedrive.service: Service hold-off time over, scheduling restart.
Sep 12 17:53:33 baselmania.com systemd[2796]: onedrive.service: Scheduled restart job, restart counter is at 12367.
Sep 12 17:53:33 baselmania.com systemd[2796]: Stopped OneDrive Free Client.
Sep 12 17:53:33 baselmania.com systemd[2796]: Started OneDrive Free Client.

**Additional context**
I can't work out how to re-authorise the connection

### Bug Report Checklist ###
- [ ] Detailed description
- [ ] Reproduction steps (if applicable)
- [ ] Verbose Log Output

**Comment by abraunegg** [comment]
You need to run the following:

```
onedrive --logout
```
