### ISSUE TITLE
onedrive service issue...

### ISSUE THREAD

**Issue by cgeyma** [abraunegg/onedrive#169]
hello, had a problem with the skilion/onedrive repo and was directed to this fork that would have solved the service issue.

cloned this fork and rebuild.
getting the following systemctl status report.

~/git-repo/onedrive (master) $ systemctl start onedrive
~/git-repo/onedrive (master) $ systemctl status onedrive
● onedrive.service - OneDrive Free Client
   Loaded: loaded (/etc/systemd/system/onedrive.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-09-12 08:40:26 EDT; 428ms ago
     Docs: https://github.com/abraunegg/onedrive
  Process: 32566 ExecStart=/usr/local/bin/onedrive --monitor (code=exited, status=1/FAILURE)
 Main PID: 32566 (code=exited, status=1/FAILURE)

Sep 12 08:40:26 localhost.localdomain systemd[1]: Unit onedrive.service entered failed state.
Sep 12 08:40:26 localhost.localdomain systemd[1]: onedrive.service failed.

log shows the following.
2018-Sep-12 08:46:15.127765 Invalid uri
2018-Sep-12 08:46:15.1278277 Could not initialize the OneDrive API
2018-Sep-12 08:46:18.6186463 Authorize this app visiting:

thanks

**Comment by cgeyma** [comment]
sorry about the report.
it looks like the service is running under root and in the root .config/onedrive folder, there is no refresh_token file. copied the files from user .config/onedrive folder to /root/.config/onedrive folder, onedrive service is running now.

however, not sure if my set up is actually correct.
thanks

/.config/onedrive $ systemctl status onedrive
● onedrive.service - OneDrive Free Client
   Loaded: loaded (/etc/systemd/system/onedrive.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-09-12 08:49:47 EDT; 31s ago
     Docs: https://github.com/abraunegg/onedrive
 Main PID: 27657 (onedrive)
    Tasks: 1
   CGroup: /system.slice/onedrive.service
           └─27657 /usr/local/bin/onedrive --monitor

Sep 12 08:49:47 localhost.localdomain systemd[1]: Started OneDrive Free Client.
Sep 12 08:49:47 localhost.localdomain systemd[1]: Starting OneDrive Free Client...
Sep 12 08:49:47 localhost.localdomain onedrive[27657]: Initializing the Synchronization Engine ...
Sep 12 08:49:48 localhost.localdomain onedrive[27657]: Initializing monitor ...
Sep 12 08:49:48 localhost.localdomain onedrive[27657]: OneDrive monitor interval (seconds): 45

**Comment by cgeyma** [comment]
ok, i see now that it created a folder named /rootOneDrive.
looks like i did something wrong that the entire onedrive setup is done as root and now the service and files all belong to root.

**Comment by abraunegg** [comment]
Thanks - it looks like it should not be doing this: `/rootOneDrive`

Will create a fix & publish.

**Comment by abraunegg** [comment]
@cgeyma 
Please can you test this PR to resolve your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/170/head:pr170
git checkout pr170
make
sudo make install
```
When running the application, this 'should' now use /root/OneDrive as the default path when running under a service. To 'avoid' re-downloading all the files, you will need to manually move all the files from `/rootOneDrive` to `/root/OneDrive`

**Comment by cgeyma** [comment]
@abraunegg 
ok, completed and i see the PR fixed the path from /rootOneDrive to /root/OneDrive.
restart the onedrive service after the re-make.
add a file online and see it synced to the new folder.
thanks

~/git-repo/onedrive (pr170) $ sudo ls -la /root/OneDrive
total 16
drwxr-xr-x.  2 root root   23 Sep 12 18:16 .
dr-xr-x---. 18 root root 4096 Sep 12 18:15 ..
-rw-r--r--.  1 root root 9318 Sep 12 18:16 test.docx

**Comment by abraunegg** [comment]
> looks like onedrive is running under root
When running as a systemd service, this is correct.

> how can i correct this and have onedrive running under pma?
You need to look at using the `onedrive@.service` service file. The readme needs to be updated as to how to use it - will do that shortly, however that service file runs as your 'user' rather than root.

The best reference here on how to use the 'user' service files is this:

https://github.com/skilion/onedrive/issues/321

**Comment by abraunegg** [comment]
PR #170 merged

**Comment by cgeyma** [comment]
@abraunegg thanks very much!
this https://github.com/skilion/onedrive/issues/321
helps and it is working under my user name now.

t
