### ISSUE TITLE
option to specify root folder to upload into

### ISSUE THREAD

**Issue by billsargent** [abraunegg/onedrive#1698]
**Is your feature request related to a problem? Please describe.**
I don't want my synced files from linux synced into the root of the onedrive account

**Describe the solution you'd like**
A config option to specify the remote directory on onedrive to upload into.

**Describe alternatives you've considered**
Creating a subdirectory inside my OneDrive sync folder to keep things out of the root of OneDrive

**Additional context**
If I've missed this option, please let me know.

**Comment by abraunegg** [comment]
@billsargent 
What you want to do is not possible with the OneDrive API - you need to structure your local data in a way that achieves this

Please review: 
* https://github.com/abraunegg/onedrive/discussions/1540
* https://github.com/abraunegg/onedrive/discussions/1675

**High level steps:**
1. Create a new folder, for example `/opt/OneDrive`
2. Configure your 'sync_dir' to look at this folder
3. Inside `/opt/OneDrive` create the folder you wish to sync the data to, example: `/opt/OneDrive/RemoteDestination`
4. Configure the application to only sync `/opt/OneDrive/RemoteDestination` via 'sync_list'
5. Symbolically link `~/OneDrive` -> `/opt/OneDrive/RemoteDestination`
