### ISSUE TITLE
Error 'Key not found: remaining' with Business Shared Folders

### ISSUE THREAD

**Issue by pctin** [abraunegg/onedrive#1712]
With lastet DMD and Onedrive version:
- DMD: 2.098.0
- Ondrive Linux: v2.4.13-28-gb0a1bae
- OS: Centos 8
- Install by clone source from git hub.

The issue cause from this day 2021-11-21 (UTC+7), it was still working on yesterday.

It just causes the error with only Business Shared Folders:

```OneDrive Business Shared File - Shared By:  Phuong Nguyen Duy (XSDT-IT) (phuongnd@dailyxsdt.vn)
WARNING: Not syncing this OneDrive Business Shared File: TALK ONLINE CÙNG MAI TÂM ANH-20210910_161652-Meeting Recording.mp4
OneDrive Business Shared File - Shared By:  Nguyễn Lê Thùy Linh (XSDT-Sale Manager) (linhnlt@dailyxsdt.vn)
Syncing this OneDrive Business Shared Folder: IT
OneDrive Business Shared Folder - Shared By:  Nguyễn Lê Thùy Linh (XSDT-Sale Manager) (linhnlt@dailyxsdt.vn)
Applying changes of Path ID: 01KGJBVPCHMT4G7AVVKRFJWZWOLBYBYR5O
Giving up on sync after three attempts: Key not found: remaining
std.json.JSONException@std/json.d(641): Key not found: remaining
----------------
??:? _D3std9exception__T7bailOutHTCQBc4json13JSONExceptionZQBjFNaNfAyamMAxaZNn [0x69b133]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x7683cc]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(return immutable(char)[]) [0x71c7f1]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[], bool) [0x6d4c9e]
??:? void sync.SyncEngine.applyDifferences(bool) [0x6d2c60]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool, bool, bool, bool, monitor.Monitor) [0x6bf23a]
??:? _Dmain [0x6bd944]
std.net.curl.CurlException@std/net/curl.d(4402): A libcurl function was given a bad argument on handle null
----------------
??:? _D3std9exception__T7bailOutHTCQBc3net4curl13CurlExceptionZQBnFNaNfAyamMAxaZNn [0x7687d2]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x76873f]
??:? void std.net.curl.Curl._check(int) [0x73e375]
??:? void std.net.curl.Curl.clear(etc.c.curl.CurlOption) [0x73e72a]
??:? void std.net.curl.HTTP.clearRequestHeaders() [0x73d4bb]
??:? void onedrive.OneDriveApi.shutdown() [0x6c31ec]
??:? _Dmain [0x6be775]
```

**Comment by abraunegg** [comment]
@pctin 
Yes this is a bug due to a OneDrive API change - but would 100% appreciate if you followed the correct support process so that this can be fixed:

* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

**Comment by abraunegg** [comment]
@pctin 
Please can you test the following PR to see if this resolves this issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1713/head:pr1713
git checkout pr1713
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.13-30-g4bfae61` or greater

**Comment by pctin** [comment]
> @pctin Please can you test the following PR to see if this resolves this issue:
> 
> ```
> git clone https://github.com/abraunegg/onedrive.git
> cd onedrive
> git fetch origin pull/1713/head:pr1713
> git checkout pr1713
> ./configure; make clean; make;
> ```
> 
> To run the PR, you need to run the client from the PR build directory:
> 
> ```
> ./onedrive <any options needed>
> ```
> 
> When running the PR, your version should be: `onedrive v2.4.13-30-g4bfae61` or greater

Hi, This fixed the issue, only run with ./onedrive <any options needed>. I don't know why not work with global: onedrive <any options needed>. Or I need to uninstall onedrive first, the resinstall with branch pr1713 ?

**Comment by abraunegg** [comment]
@pctin 
If the PR build works, you need to perform:
```
sudo make install
```

To install the PR version

**Comment by pctin** [comment]
Hi, the issues has been fixed, thank you so much for your great and quick support!

I will keep using this branch: pr1713 ?

**Comment by abraunegg** [comment]
@pctin 
PR is now merged into 'master' - rebuild & install from 'master' please

**Comment by MetroMarv** [comment]
Thanks for fixing this problem so fast!

Can you tell me if there will be a new release soon that includes this fix?

**Comment by abraunegg** [comment]
@MetroMarv 
I am looking to do a new release in the new year. Keep an eye on releases + potential beta releases between now and then.

**Comment by zonywhoop** [comment]
Just FYI, the change on the MS sides completely breaks the client from what we're seeing and I don't expect the distros will pick up and build new packages until an update is released. We're working on a custom build but may be good to rap this into a new release just so the fix get's out faster.

**Comment by abraunegg** [comment]
@zonywhoop 
Doing a 'quick' release now may be OK for those 'distros' that can fire out a new package quickly (Arch AUR) - however, there are *so* many laggard distro's (looking at you Ubuntu) where their package update policies are just *******

Given the impact, I will push the Internationalisation to a new version and do a new release today.

**Comment by zonywhoop** [comment]
That's awesome @abraunegg! TY.

**Comment by MetroMarv** [comment]
Thanks a lot @abraunegg!

**Comment by abraunegg** [comment]
v2.4.14 released.

If you are using a package, follow up with the package maintainer.
