### ISSUE TITLE
Overwriting local files with older versions from OneDrive when items.sqlite3 does not exist and --resync is not used

### ISSUE THREAD

**Issue by dresco** [abraunegg/onedrive#1714]
### Bug Report Details ###
**Describe the bug**
Sync is overwriting local files with older versions from OneDrive (see discussion #1710)

For all(?) files that have already been synced, am getting a message as below. Looking in the local filesystem, the newer file has been replaced with the remote version, with no backup created. Caught early, and running with --dry-run option to capture the errors without overwriting more files.

```
The local item has a different modified time 2021-Sep-28 10:20:11Z when compared to remote modified time 2020-Dec-23 14:18:08Z
The local item has a different hash when compared to remote item hash
Local item does not exist in local database - replacing with file from OneDrive - failed download?
Downloading file Data/FreeCAD/Tools/Bit/5mm_Drill.fctb ... done.
```

Current client version is v2.4.13 (fedora 35 package), unknown what version would have run the last successful sync (will have been at least 6 months ago). Hopefully packaged version is acceptable, else will build from source..

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
Fedora 35 
Linux laptop.localdomain 5.14.16-301.fc35.x86_64 SMP Wed Nov 3 13:55:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?
GUI installed
*   OneDrive Account Type
Personal
*   Did you build from source or install from a package?
Package
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
*   OneDrive Application Version: Output of `onedrive --version` 
Application version: v2.4.13
*   OneDrive Application Configuration: Output of `onedrive --display-config`
onedrive version                       = v2.4.13
Config path                            = /home/jone/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/jone/OneDrive
Config option 'skip_dir'               = Apps/Joplin
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
*   Provide the version of curl you are using: Output of `curl --version`
curl 7.79.1 (x86_64-redhat-linux-gnu) libcurl/7.79.1 OpenSSL/1.1.1l-fips zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.45.1 OpenLDAP/2.4.59
*   Is your configured 'sync_dir' a local directory or a network mount point?
Local directory
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
ext4
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
Folder is not shared with any other system. 
The same OneDrive account is used for syncing another applications data (Joplin) on both this system and on mobile device, neither would be happening at the same time though.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
onedrive --synchronize

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```
Emailing dry-run log output to support address support@mynas.com.au

**Comment by abraunegg** [comment]
@dresco 
Please can you test the following PR to see if this resolves this issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1717/head:pr1717
git checkout pr1717
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.13-34-g1b3575a` or greater

**Comment by dresco** [comment]
Can confirm this now preserves the local data before downloading (dry-run output);

```
The local item has a different modified time 2021-Oct-13 16:51:05Z when compared to remote modified time 2021-Mar-08 13:06:25Z
The local item has a different hash when compared to remote item hash
Local item does not exist in local database - replacing with file from OneDrive - failed download?
The local item is out-of-sync with OneDrive, renaming to preserve existing file and prevent local data loss: Data/FreeCAD/LEAD CNC Parts.FCStd -> Data/FreeCAD/LEAD CNC Parts-laptop.localdomain.FCStd
Downloading file Data/FreeCAD/LEAD CNC Parts.FCStd ... done. 
```

**Comment by abraunegg** [comment]
@dresco 
Thanks for confirming the fix, will merged the PR into 'master'

**Comment by pd5rm** [comment]
I think this fix will address my overwritten local file problems which I brought up in #1507, #1169. 

I still don't understand how a file could "drop out" of the local items db (re the error message saying it doesn't exist below). The db file itself is certainly present, and I actively write to this file many times a day.

The following recent occurrence of this error (with local data loss) as of v2.4.13:

> 2021-Nov-10 11:05:11.4540697    The local item has a different modified time 2021-Nov-10 04:10:41Z when compared to remote modified time 2021-Nov-08 21:39:15Z
2021-Nov-10 11:05:11.4540999    The local item has a different hash when compared to remote item hash
2021-Nov-10 11:05:11.4541494    Local item does not exist in local database - replacing with file from OneDrive - failed download?
...
2021-Nov-10 11:05:12.0802701    Downloading file notes/todo.txt ... done.
2021-Nov-10 11:05:12.0803119    [DEBUG] Inserting item details to local database

**Comment by dresco** [comment]
> I still don't understand how a file could "drop out" of the local items db (re the error message saying it doesn't exist below). The db file itself is certainly present, and I actively write to this file many times a day.

Yep, just for clarity - that was the situation here also. The items.sqlite3 file was certainly present, but numerous files (that had previously been synchronised) were missing from it. 

I had also been using the Fedora package, so possibly buggy? Have now uninstalled that and using the binary that I built from source. Will update if I see any further occurrences of files dropping out of the database.

Probably not relevant, but only other thing I can think of - I do get failures with the 141 error (am running against MS EU data centre) very often - so I just re-run the sync process until it gets all the way through with a 0 return code.

**Comment by pd5rm** [comment]
It may be error related, since this only happens to me when I need to change account credentials due to corporate polices and get a new access token.

> ERROR: Microsoft OneDrive API returned an error with the following message:
2021-Nov-10 11:01:53.6809365      Error Message:    HTTP request returned status code 400 (Bad Request)
2021-Nov-10 11:01:53.6809925    [DEBUG] Raw Error Data: HTTP request returned status code 400 (Bad Request)
....
 "error_description": "AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. 
...
2021-Nov-10 11:01:54.1992738    [DEBUG] oneDriveDetails = onedrive.getDefaultDrive() generated a OneDriveException
2021-Nov-10 11:01:54.1993721    
ERROR: Microsoft OneDrive API returned an error with the following message:
2021-Nov-10 11:01:54.1994142      Error Message:    HTTP request returned status code 401 (Unauthorized)
2021-Nov-10 11:01:54.2002566      Error Reason:     Access token is empty.
2021-Nov-10 11:01:54.2188991    ERROR: Check your configuration as your refresh_token may be empty or invalid. You may need to issue a --logout and re-authorise this client.
