### ISSUE TITLE
Onedrive Start Exception

### ISSUE THREAD

**Issue by adg7511** [abraunegg/onedrive#1715]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
We have been using this onedrive client for several months, but today after we kill the onedrive process it can't start anymore.
onedrive v2.4.13
log info:
```
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
std.json.JSONException@std/json.d(641): Key not found: remaining

??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x640b43]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x702645]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x6b63f9]
??:? void sync.SyncEngine.init() [0x672a46]
??:? bool main.initSyncEngine(sync.SyncEngine) [0x6619e8]
??:? _Dmain [0x65f742]
std.net.curl.CurlException@std/net/curl.d(4402): A libcurl function was given a bad argument on handle null

??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x702a7a]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x7029eb]
??:? void std.net.curl.Curl._check(int) [0x6cf33b]
??:? void std.net.curl.Curl.clear(etc.c.curl.CurlOption) [0x6cf6ea]
??:? void std.net.curl.HTTP.clearRequestHeaders() [0x6ce40f]
??:? void onedrive.OneDriveApi.shutdown() [0x665e9c]
??:? _Dmain [0x66136a]
```
**Application and Operating System Details:**

* CentOS 6.x
* curl 7.29.0
* onedrive v2.4.13

**Comment by scoleri** [comment]
As well.  Same error.

Alpine Linux v3.14
curl 7.78.0
onedrive v2.4.13
aarch64

**Comment by microbug** [comment]
Also getting this.

Manjaro, kernel 5.15.2-2-MANJARO
curl 7.80.0
onedrive v2.4.13-28-gb0a1bae
x86-64

**Comment by scoleri** [comment]
I recompiled and it ran but wouldn't upload complaining about space.  So i force set: 
quotaAvailable = true;

Working now.  I needed to push reports.  Hopefully this gets fixed.

**Comment by tuuxx** [comment]
Same error.
The synchronisation with the home directory works smoothly, only with the shared Onedrive folders the error occurs. 

Mint Cinnamon 20.2
curl 7.68
onedrive v2.4.13
x86-64

**Comment by obstinacyvalue** [comment]
Did you search the closed issues?

6 hours before this bug report https://github.com/abraunegg/onedrive/issues/1712

**Comment by abraunegg** [comment]
This is a fixed issue - it is a OneDrive API change

Rebuild your client from 'master'

**Comment by abraunegg** [comment]
@scoleri 
> I recompiled and it ran but wouldn't upload complaining about space. So i force set (in sync.d): quotaAvailable = true;
> 
> Working now. I needed to push reports. Hopefully this gets fixed.

Please can you URGENTLY send me some verbose debug logs using the PR code so that I can look into this - as you *should* not have to set that value to upload. This means that the PR code is not complete & has a bug somewhere.

**Comment by obstinacyvalue** [comment]
I can send my debug logs if you can tell me how to do so. I had to change that variable and one other to get my files to upload.


```
private bool quotaAvailable = false;
// quota details restricted
private bool quotaRestricted = true;
// sync business shared folders flag
```

Otherwise I got this message complaining there was no space available.

`Skipping item './censored' due to insufficient free space available on OneDrive`

**Comment by abraunegg** [comment]
@scoleri 
Please do the following:
1. Rebuild the PR without your change
2. Generate a debug log as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

**Comment by obstinacyvalue** [comment]
Will do when I find a lull in the workday.

**Comment by abraunegg** [comment]
@scoleri 
> Will do when I find a lull in the workday.

If you can put some priority into this that would be great - this debug log and investigation is delaying the release of v2.4.14 to ensure that this issue is not shipped with the new version.

**Comment by abraunegg** [comment]
@scoleri 
As an FYI - I cannot reproduce this issue you are claiming with failing to upload to a Business Shared Folder with the PR ...

Need the debug logs ASAP please.

**Comment by scoleri** [comment]
Huh?  What issue?  What PR code - i didn't issue a PR?  All i did was
disable the disk space checking locally as it looked like the API changed
or something on MS side.  In my env i don't really care about disk space.
However being down wasn't an option as all reports get published via
sharepoint.  I just recompiled without the disk space checking and it and
got me going again.

I'll recompile from master and if it's working i'll be good?

I had the same problem as originally reported in this issue.  JSON from api
was wack.

**Comment by obstinacyvalue** [comment]
I couldn't reproduce the error I saw. It was happily uploading new files without issue.

**Comment by abraunegg** [comment]
v2.4.14 released

If you are using a package, please follow up with the package maintainer.
