### ISSUE TITLE
RPi Dockerfile has outdated glibc

### ISSUE THREAD

**Issue by MarcelCoding** [abraunegg/onedrive#1726]
### Bug Report Details ###
```
/ldc2-1.17.0-linux-armhf/bin/ldc2: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /ldc2-1.17.0-linux-armhf/bin/ldc2)
#15 3.410 
#15 3.643 configure: error: Compiler version insufficient, current compiler version , minimum version 1.17.0
```
[onedrive_rpi.log](https://github.com/abraunegg/onedrive/files/7598780/onedrive_rpi.log)

Setup: https://github.com/MarcelCoding/onedrive-docker/tree/f1dd8ae9e16a5e5d32eca05bed24d4e3966e3ff1

**Comment by MarcelCoding** [comment]
maybe use bulseye and not strech

**Comment by MarcelCoding** [comment]
```Dockerfile
# -*-Dockerfile-*-
FROM debian:bullseye
RUN apt-get update && \
    apt-get install -y build-essential curl libcurl4-openssl-dev libsqlite3-dev pkg-config wget git
RUN wget https://github.com/ldc-developers/ldc/releases/download/v1.17.0/ldc2-1.17.0-linux-armhf.tar.xz && \
    tar -xvf ldc2-1.17.0-linux-armhf.tar.xz
COPY . /usr/src/onedrive
RUN cd /usr/src/onedrive/ && \
    ./configure DC=/ldc2-1.17.0-linux-armhf/bin/ldmd2 && \
    make clean && \
    make && \
    make install

FROM debian:bullseye-slim
ENTRYPOINT ["/entrypoint.sh"]
RUN apt-get update && \
    apt-get install -y gosu libcurl4 libsqlite3-0 && \
    rm -rf /var/*/apt && \
    mkdir -p /onedrive/conf /onedrive/data
COPY contrib/docker/entrypoint.sh /
COPY --from=0 /usr/local/bin/onedrive /usr/local/bin/

``` all package changes reflected

**Comment by abraunegg** [comment]
@MarcelCoding 
Can you submit a PR for this please ? Probably both docker files that use stretch need to be updated.

**Comment by MarcelCoding** [comment]
I'll going to improve and update the Docker files tomorrow or on Friday.

**Comment by MarcelCoding** [comment]
@abraunegg 
Maybe we should rename `stretch` to `debian`. If you update the debian version the docker tag does not change.

**Comment by MarcelCoding** [comment]
Is there some reason why you are using sometimes dmd and sometimes ldc? Would it be ok to always use ldc. In that case, I could provide one Dockerfile (and tag) for all supported architectures (plus separate alpine). Is centos still relevant? I am not that up to date but wasn't centos abandoned?

**Comment by MarcelCoding** [comment]
Better than ldc would be gdc because it is available in the Debian package sources on a variety of architectures.

**Comment by abraunegg** [comment]
@MarcelCoding 
> Maybe we should rename stretch to debian. If you update the debian version the docker tag does not change.

No issues in doing this to simplify files | deployment options

> Is there some reason why you are using sometimes dmd and sometimes ldc?

It comes down to compiler options.

On RPI - esp ARMHF, you cannot use DMD, LDC only works, and the only version of compiler that works is LDC 1.17. This is because of Raspian itself.

On other platforms, the packaged version of the compiler is generally too old, so, we have to download the appropriate later package to compile - and generally, for better comparability, DMD works better. 

For example - all the Ubuntu packages use LDC, and, have this ugly segfault when you stop the application. This 'only' occurs when using the Ubuntu packaged version of LDC - if you manually install that LDC version, no segfault. If you use DMD also no segfault.

> I am not that up to date but wasn't centos abandoned?

Sort of - probably better to switch that to a Fedora one rather than CentOS now anyways.

> Better than ldc would be gdc because it is available in the Debian package sources on a variety of architectures.

Dont use gdc

**Comment by MarcelCoding** [comment]
Could I always use ldc, or should I use dmd if it is available?

**Comment by abraunegg** [comment]
@MarcelCoding 
Do not use the distro version of DMD or LDC

**Comment by MarcelCoding** [comment]
@abraunegg I mean with the architecture.

**Comment by MarcelCoding** [comment]
I was able to create a Dockerfile for Debian Bullseye, Alpine & Fedora: https://github.com/MarcelCoding/onedrive-docker
Currently, I always use ldc. Alpine is only for amd64 and arm64 available and Debian and Fedora are available for amd64, arm64, armhf. (https://hub.docker.com/r/marcelcoding/onedrive/tags?page=1&name=edge) Tomorrow I am going to test everything and if it works and you don't have anything left I create a PR.

**Comment by abraunegg** [comment]
@MarcelCoding 
Greatly appreciated thankyou :)
