### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by MarcelCoding** [abraunegg/onedrive#1727]
### Bug Report Details ###
**Describe the bug**
Unable to authenticate:
![image](https://user-images.githubusercontent.com/34819524/143414752-099f5412-45a7-4f21-ab1b-10c33c608671.png)

**Application and Operating System Details:**
*  `Linux codespaces_1afc8c 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
*  GitHub Codespaces 
*  Personal Account
*  Alpine Docker Image (selfbuild)
* master branch

### Bug Report Checklist ###
*   [ ] Detailed description
*   [x] Application and Operating System Details provided in full
*   [ ] Reproduction steps (if applicable)
*   [ ] Verbose Log Output from your error
*   [ ] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@MarcelCoding 
I think this is an issue with *your* account, not this application.

Using the authentication UR:
```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d50ca740-c83f-4d1b-b616-12c519384f0c&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.Read.All%20Sites.ReadWrite.All%20offline_access&response_type=code&prompt=login&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
```

Using <user>@outlook.com account type for OneDrive Personal returns the correct AUTH response and the application is correctly authenticated.

```
[alex@centos7full onedrive]$ ./onedrive
Configuring Global Azure AD Endpoints
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d50ca740-c83f-4d1b-b616-12c519384f0c&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.Read.All%20Sites.ReadWrite.All%20offline_access&response_type=code&prompt=login&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=<redacted>

Application has been successfully authorised, however no additional command switches were provided.

Please use --help for further assistance in regards to running this application.

[alex@centos7full onedrive]$
```


Using <user>@<domain>.onmicrosoft.com account type for OneDrive Business returns the correct AUTH response and the application is correctly authenticated.
```
[alex@centos7full onedrive]$ ./onedrive
Configuring Global Azure AD Endpoints
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d50ca740-c83f-4d1b-b616-12c519384f0c&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.Read.All%20Sites.ReadWrite.All%20offline_access&response_type=code&prompt=login&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=0.AUIArzBTHXWoz0WeVkNDMxV970CnDNU<redacted>

Application has been successfully authorised, however no additional command switches were provided.

Please use --help for further assistance in regards to running this application.

[alex@centos7full onedrive]$ 
```

**Comment by MarcelCoding** [comment]
I don't understand what you mean. I use an personal Microsoft account with an @outlook.com Email-Address. And the URL returned by the client and the one provided by you are both not working. (same error as in the screenshot)

**Comment by MarcelCoding** [comment]
@abraunegg

**Comment by abraunegg** [comment]
@MarcelCoding 
This has nothing to do with this client - it has everything to do with your account.

Check:
* what is your auth url - is it the same as mine?
* are you using a different application id ?

If you still cant authenticate - raise a case with Microsoft - it is your account that is at fault.

**Comment by abraunegg** [comment]
@MarcelCoding 
Additionally - clear your web browser cache and cookies before trying the authentication

**Comment by MarcelCoding** [comment]
I just tried it in an private tab and an clean different browser, it is still not working.

**Comment by MarcelCoding** [comment]
Ohh, I tried an different account and it worked. I am going to let you know, if I found the issue. You may want to add it to the docs or troubleshooting section.

**Comment by abraunegg** [comment]
@MarcelCoding 
Just to reiterate - the issue *is* with your Microsoft account. it has nothing to do with this client at all.

This client is a consumer of the auth details provided by the auth process - nothing more.
