### ISSUE TITLE
Onedrive 2.4.14 downloads fine from a Sharepoint shared library but fails to upload due to insufficient free space available

### ISSUE THREAD

**Issue by geoffmol** [abraunegg/onedrive#1729]
### Bug Report Details ###
**Describe the bug**
I can use onedrive 2.4.14 on Ubuntu 20.04 to download files from my company sharepoint site using the drive_id configuration provided using the -get-O365-drive-id option but *not* upload any due to insufficient free space available on OneDrive. I then tried downloading/uploading from my personal 'My Files' Onedrive space and that worked without issue. My 'Account Type' seems to be **documentLibrary** and because of that I can't seem to use --list-shared-folders (ERROR: Unsupported account type for listing OneDrive Business Shared Folders) Is the fact that the 'Remaining disc space' count is returning 0 or cannot be determined preventing the upload? Is there anyway to circumvent that or get any files uploaded to a drive_id?

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
```
Ubuntu 20.04.3 Linux gm-linux-pc 5.4.0-91-generic 102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
*   Are you using a headless system (no gui) or with a gui installed?
```
onedrive from the command line
```
*   OneDrive Account Type
*   Did you build from source or install from a package?
```
installed following instructions from https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md
```
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
*   OneDrive Application Version: Output of `onedrive --version`
```
onedrive v2.4.14-1~np1
```
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
(base) gm@gm-linux-pc$ onedrive --display-config
Configuration file successfully loaded
onedrive version                       = v2.4.14-1~np1
Config path                            = /home/gm/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/gm/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'drive_id'               = b!GtEZbo-6j0S95r3CDbcb76QIU3r_kiFBmXS65CgdtoYnYtRWxap2T4QAxwnpkGWB
Config option 'sync_root_files'        = true
Selective sync 'sync_list' configured  = true
sync_list contents:
# sync_list supports comments
#
# The ordering of entries is highly recommended - exclusions before inclusions
#
testcases_gm
Business Shared Folders configured     = false
```

*   Provide the version of curl you are using: Output of `curl --version`
```
(base) gm@gm-linux-pc$ curl --version
curl 7.65.3 (x86_64-conda_cos6-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1d zlib/1.2.11 libssh2/1.8.2
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

*   Is your configured 'sync_dir' a local directory or a network mount point?
```
local directory
```
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
```
sda                                                                       
├─sda1 vfat           AD2C-F648                             505.8M     1% /boot/efi
└─sda2 ext4           fd3b2857-8bdd-4a99-ab92-87c2c0231782    756G    12% /
```
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
```
Onedrive on Windows 10 platform also syncs with sharepoint library
```
**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  onedrive --synchronize
If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose 
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Using 'user' Config Dir: /home/gm/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/gm/OneDrive
ERROR: OneDrive quota information is being restricted. Please fix by speaking to your OneDrive / Office 365 Administrator.
Application version: v2.4.14-1~np1
Account Type: documentLibrary
Default Drive ID: b!GtEZbo-6j0S95r3CDbcb76QIU3r_kiFBmXS65CgdtoYnYtRWxap2T4QAxwnpkGWB
Default Root ID: 01X5ZPALN6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 0
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 01X5ZPALN6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Processing documentation_examples
The directory has not changed
Processing documentation_examples/datastep_obsolete
The directory has not changed
Processing documentation_examples/datastep_obsolete/functions
The directory has not changed
Processing documentation_examples/datastep_obsolete/functions/bit
The directory has not changed
Processing documentation_examples/datastep_obsolete/functions/bit/BAND.sas
The file has not changed

.. lots more lines that have been removed etc ...

Processing testcases_gm/Support_Services/WEB_demo/frontend/20160904_webbapp/mnuSystems.html
The file has not changed
Processing testcases_gm/Support_Services/WEB_demo/frontend/20160904_webbapp/mnuRetail.html
The file has not changed
Processing testcases_gm/Support_Services/WEB_demo/frontend/20160904_webbapp/mnuPharmaceutical
The directory has not changed
Processing home/gm/OneDrive/testcases_gm/Support_Services/bin/FSM-Simple-0.02
The directory has not changed
Processing home/gm/OneDrive/testcases_gm/Support_Services/bin/FSM-Simple-0.02/t
The directory has not changed
Processing home/gm/OneDrive/testcases_gm/Support_Services/bin/FSM-Simple-0.02/lib
The directory has not changed
Processing home/gm/OneDrive/testcases_gm/Support_Services/bin/FSM-Simple-0.02/lib/FSM
The directory has not changed
Processing home/gm/OneDrive/testcases_gm/Support_Services/bin/FSM
The directory has not changed
Uploading new items of ~/OneDrive
Skipping item './testcases_gm/Customer_Services/Zendesk_Issues/39298/39298-gm-linux-pc.sas' due to insufficient free space available on OneDrive
Skipping item './testcases_gm/Support_Services/bin/Platform-gm-linux-pc.pm' due to insufficient free space available on OneDrive
Applying changes of Path ID: 01X5ZPALN6Y2GOVW7725BZO354PWSELRRZ

```

**Screenshots**

**Additional context**
I know the sharepoint site has a lot of storage and syncing Sharepoint with onedrive on windows PC has no issue and continues to work as it is a large company site. It's just that I would really like it to work from linux and for the last year has been working fine with the previous 2.4.13 version but that one was giving errors of the form:
```
std.json.JSONException@std/json.d(626): Key not found: remaining
----------------
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x7fe48ca29af6]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x7fe48ca81ef6]
??:? [0x559f131652fd]
??:? [0x559f131aa4f2]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7fe48c79f9db]
??:? _d_run_main2 [0x7fe48c79f7ee]
??:? _d_run_main [0x7fe48c79f65d]
??:? __libc_start_main [0x7fe48c38b0b2]
??:? [0x559f1315433d]
std.net.curl.CurlException@std/net/curl.d(4386): A libcurl function was given a bad argument on handle null
----------------
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x7fe48ca29d9c]
??:? void std.net.curl.HTTP.clearRequestHeaders() [0x7fe48ca8e8ef]
??:? [0x559f131a5652]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7fe48c79f9db]
??:? _d_run_main2 [0x7fe48c79f7ee]
??:? _d_run_main [0x7fe48c79f65d]
??:? __libc_start_main [0x7fe48c38b0b2]
??:? [0x559f1315433d]
```
that I could not resolve so I tried to move up to 2.4.14 and at least that gets past the above error and downloading works fine.
Is the fact that the 'Remaining disc space' count is returning 0 or cannot be determined preventing the upload? Is there anyway to circumvent that?

### Bug Report Checklist ###
*   [] Detailed description
*   [] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@geoffmol 
You need to rebuild your client from 'master' and not use the Ubuntu Package

**Comment by geoffmol** [comment]
@abraunegg 
Thanks for the advice, rebuilt from master and now onedrive v2.4.14-6-ga2d2ea9 seems to nicely resolve the issue, only caveat was that I had to uninstall anaconda3 which interferes with the search paths for library resolution and breaks the make. All good now thanks again for your swift response.
