### ISSUE TITLE
E-mail notification on errors

### ISSUE THREAD

**Issue by arbasel** [abraunegg/onedrive#173]
**Describe the solution you'd like**
I would like to be e-mailed when any failures occure

**Describe alternatives you've considered**
Not sure of any

**Additional context**
E-mail address and SMTP info could be entered in the config file.

**Comment by abraunegg** [comment]
If running as a service, you should configure init.d / systemd to mail you if an email error occurs.

Have a read of https://unix.stackexchange.com/questions/210429/systemd-mailto-replacement-failing which may assist
