### ISSUE TITLE
A database statement execution error occurred: disk I/O error

### ISSUE THREAD

**Issue by sramaram-rythmos** [abraunegg/onedrive#1732]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Database error when trying to run synchronize/monitor
After building from source and trying to sync files, seeing error:
 ```A database statement execution error occurred: disk I/O error when trying monitor/synchronize```

**Application and Operating System Details:**
*   Provide your OS & version - Ubuntu 20.04.3, Linux ram-ThinkPad-L470 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed? No GUI
*   OneDrive Account Type : Business
*   Did you build from source or install from a package? From source
*   If you installed from source, what is your DMD or LDC compiler version: DMD64 D Compiler v2.098.0
*   OneDrive Application Version: onedrive v2.4.14-6-ga2d2ea9
*   OneDrive Application Configuration: 
Configuration file successfully loaded
Deleting the saved application sync status ...
onedrive version                       = v2.4.14-6-ga2d2ea9
Config path                            = /home/ram/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /
Config option 'skip_dir'               = */node_modules/*
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 600
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
MYWORK
/home/ram/Desktop
#/home/ram/Downloads
/home/ram/Pictures
/home/ram/Videos
/home/ram/.aws
#/home/ram/.m2
/home/ram/.bashrc
/home/ram/.gitconfig
/home/ram/.ssh/known_hosts
/home/ram/.config/onedrive/config
/home/ram/.config/onedrive/sync_list
/home/ram/.config/systemd
Business Shared Folders configured     = false

*   Provide the version of curl you are using: curl 7.68.0
*   Is your configured 'sync_dir' a local directory or a network mount point? Local
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on?
NAME   FSTYPE   LABEL     UUID                                 FSAVAIL FSUSE% MOUNTPOINT
loop0  squashfs                                                      0   100% /snap/core/11798
loop1  squashfs                                                      0   100% /snap/bare/5
loop2  squashfs                                                      0   100% /snap/core/11993
loop3  squashfs                                                      0   100% /snap/core18/2246
loop4  squashfs                                                      0   100% /snap/core20/1242
loop5  squashfs                                                      0   100% /snap/core18/2253
loop6  squashfs                                                      0   100% /snap/dbeaver-ce/147
loop7  squashfs                                                      0   100% /snap/dbeaver-ce/148
loop8  squashfs                                                      0   100% /snap/gnome-3-28-1804/145
loop9  squashfs                                                      0   100% /snap/gnome-3-28-1804/161
loop10 squashfs                                                      0   100% /snap/gnome-3-34-1804/72
loop11 squashfs                                                      0   100% /snap/gnome-3-34-1804/77
loop12 squashfs                                                      0   100% /snap/gnome-3-38-2004/87
loop13 squashfs                                                      0   100% /snap/gtk-common-themes/1515
loop14 squashfs                                                      0   100% /snap/gtk-common-themes/1519
loop15 squashfs                                                      0   100% /snap/p3x-redis-ui/281
loop16 squashfs                                                      0   100% /snap/p3x-redis-ui/282
loop17 squashfs                                                      0   100% /snap/postman/132
loop18 squashfs                                                      0   100% /snap/postman/133
loop19 squashfs                                                      0   100% /snap/prospect-mail/16
loop20 squashfs                                                      0   100% /snap/prospect-mail/11
loop21 squashfs                                                      0   100% /snap/rustup/1027
loop22 squashfs                                                      0   100% /snap/rustup/983
loop23 squashfs                                                      0   100% /snap/snap-store/547
loop24 squashfs                                                      0   100% /snap/snap-store/558
loop25 squashfs                                                      0   100% /snap/snapd/13640
loop26 squashfs                                                      0   100% /snap/snapd/14066
loop27 squashfs                                                      0   100% /snap/supertuxkart/630
loop28 squashfs                                                      0   100% /snap/supertuxkart/631
loop29 squashfs                                                      0   100% /snap/vlc/2344
loop30 squashfs                                                      0   100% /snap/vlc/2288
sda                                                                           
├─sda1 vfat     SYSTEM    D613-F9FF                             222.3M    13% /boot/efi
├─sda2                                                                        
├─sda3 ntfs     Windows   E230178430175F3B                                    
├─sda4 vfat               AAEE-DE7F                              44.8G    66% /media/ram/AAEE-DE7F
├─sda5 ntfs     WinRE_DRV 187A183C7A1818D8                                    
├─sda6 ext4               b5ff58ab-c57e-4f4b-9598-d10d8603d2db   34.6G    43% /home
├─sda7 swap               a3f64f7b-76a7-4732-9c4d-6e88da8e3a78                [SWAP]
└─sda8 ext4               7fbe77da-a6a1-440c-a468-c646965f1e24  199.8G    16% /

*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
   Standalone setup on my laptop, onedrive account not shared but in use by only my laptop

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Follow the instructions for setup in: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-ubuntu-18x-ubuntu-19x-ubuntu-20x--debian-9-debian-10---x86_64 and https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#compilation--installation

2.  Inside dmd environment,`onedrive --synchronize --resync`

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
```(dmd-2.098.0)sramaram@sramaram-ThinkPad-L470:.../onedrive$ onedrive --synchronize --resync 
Configuration file successfully loaded
Deleting the saved application sync status ...
Configuring Global Azure AD Endpoints

A database statement execution error occurred: disk I/O error

Please retry your command with --resync to fix any local database corruption issues.

(dmd-2.098.0)sramaram@sramaram-ThinkPad-L470:.../onedrive$
```
Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@sramaram-rythmos 
This is not a bug.

You probably have installed via a 'package' - and, not fully understood this: https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md#known-issues-with-installing-from-the-above-packages

What is happening is that you most like have 2 instances running at the same time - one because of the Ubuntu package bug, the other is your manual run using the compiled version.

To resolve:
1. Uninstall the Ubuntu package version
2. Ensure you remove the badly created symbolic systemd link
3. Reboot
4. Compile and build from source
5. Retest
6. Install from source

**Comment by sramaram-rythmos** [comment]
@abraunegg 
thank you for the quick response.
i think i have two installations like you said, but I couldn't figuring out a way to purge 'package' version - apt remove and purge won't work.
