### ISSUE TITLE
AADSTS90102: 'redirect_uri' value must be a valid absolute URI.

### ISSUE THREAD

**Issue by OskarZyg** [abraunegg/onedrive#1739]
When starting the program for the first time, you are asked to click on a link and enter the response URI:
```
Configuring Global Azure AD Endpoints
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d50ca740-c83f-4d1b-b616-12c519384f0c&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.Read.All%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: 
```

Visiting this link however, sends you to an MS login page with the following error: `AADSTS90102: 'redirect_uri' value must be a valid absolute URI.`

![image](https://user-images.githubusercontent.com/56176746/144728795-0273be2f-e3e3-4e84-b22e-a00803fd0365.png)

**Comment by abraunegg** [comment]
@OskarZyg 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
