### ISSUE TITLE
Inefficient (slow) selective sync from large onedrive account

### ISSUE THREAD

**Issue by gatlanticus** [abraunegg/onedrive#1742]
### Bug Report Details ###
I have hundreds of folders and thousands of files on my onedrive account (totalling 30 GB). When I try to selectively sync one small folder with either the `sync_list` option or `--single-directory` flag, the client successfully completes the job and then runs for an unreasonably long time to check (what seems to be) my entire onedrive account for consistency.

**Expected behaviour**
Synchronise "included" files and directories from `sync_list`, or the single directory specified by `--single-directory` and then **stop**.

**Application and Operating System Details:**
*   Linux Mint 20.2 (based on Ubuntu 20.04) 
* Linux 5.4.0-91-generic 102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
*   Personal OneDrive Account
*   Installed from package as per instructions at https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md
*   onedrive v2.4.14-1~np1
*   OneDrive Application Configuration

.

    Configuration file successfully loaded
    onedrive version                       = v2.4.14-1~np1
    Config path                            = /home/<redacted>/.config/onedrive
    Config file found in config path       = true
    Config option 'check_nosync'           = false
    Config option 'sync_dir'               = /home/<redacted>/OneDrive
    Config option 'skip_dir'               = 
    Config option 'skip_file'              = ~*|.~*|*.tmp
    Config option 'skip_dotfiles'          = false
    Config option 'skip_symlinks'          = false
    Config option 'monitor_interval'       = 300
    Config option 'min_notify_changes'     = 5
    Config option 'log_dir'                = /var/log/onedrive/
    Config option 'classify_as_big_delete' = 1000
    Config option 'upload_only'            = false
    Config option 'no_remote_delete'       = false
    Config option 'remove_source_files'    = false
    Config option 'sync_root_files'        = false
    Selective sync 'sync_list' configured  = true
    sync_list contents:
    # Include
    SyncTest

*   curl 7.68.0 (x86_64-pc-linux-gnu)
*   'sync_dir' is on a local directory

**Reproduction with verbose output**
Start with a large onedrive account online, with thousands of files and folders, and then try to selectively sync one small folder using either approach below.

`onedrive synchronize --verbose  --single-directory 'SyncTest'` outputs:

    Using 'user' Config Dir: /home/<redacted>/.config/onedrive
    Using 'system' Config Dir: /etc/onedrive
    Configuration file successfully loaded
    Initializing the OneDrive API ...
    Configuring Global Azure AD Endpoints
    Opening the item database ...
    All operations will be performed in: /home/<redacted>/OneDrive
    Application version: v2.4.14-1~np1
    Account Type: personal
    Default Drive ID: f688de37991f936c
    Default Root ID: F688DE37991F936C!133
    Remaining Free Space: 1098149886146
    Fetching details for OneDrive Root
    OneDrive Root exists in the database
    Initializing the Synchronization Engine ...
    Syncing changes from this selected path: SyncTest
    Syncing changes from selected OneDrive path ...
    Getting path details from OneDrive ...
    Applying changes of Path ID: F688DE37991F936C!169175
    Updated Remaining Free Space: 1098149886146
    Processing 228 OneDrive items to ensure consistent local state due to sync_list being used
    Remote change discarded - not in --single-directory sync scope (not in DB)
    Remote change discarded - not in --single-directory sync scope (not in DB)
    Remote change discarded - not in --single-directory sync scope (not in DB)
    Remote change discarded - not in --single-directory sync scope (not in DB)
    Remote change discarded - not in --single-directory sync scope (not in DB)
    Remote change discarded - not in --single-directory sync scope (not in DB)
    ... (repeated for thousands of lines)

`onedrive --synchronize --verbose --dry-run --enable-logging` (with only one folder included in `sync_list`) outputs:

    Using 'user' Config Dir: /home/<redacted>/.config/onedrive
    Using 'system' Config Dir: /etc/onedrive
    Configuration file successfully loaded
    DRY-RUN Configured. Output below shows what 'would' have occurred.
    Using logfile dir: /var/log/onedrive/
    Initializing the OneDrive API ...
    Configuring Global Azure AD Endpoints
    Opening the item database ...
    All operations will be performed in: /home/<redacted>/OneDrive
    Application version: v2.4.14-1~np1
    Account Type: personal
    Default Drive ID: f688de37991f936c
    Default Root ID: F688DE37991F936C!133
    Remaining Free Space: 1098149886146
    Fetching details for OneDrive Root
    OneDrive Root does not exist in the database. We need to add it.
    Added OneDrive Root to the local database
    Initializing the Synchronization Engine ...
    Syncing changes from OneDrive ...
    Applying changes of Path ID: F688DE37991F936C!133
    Updated Remaining Free Space: 1098149886146
    Processing 226 OneDrive items to ensure consistent local state due to sync_list being used
    Skipping item - excluded by sync_list config: Backups
    Creating local directory: SyncTest
    Downloading file SyncTest/test 1.txt ... done.
    Downloading file SyncTest/test 2.txt ... done.
    Processing 213 OneDrive items to ensure consistent local state due to sync_list being used
    Skipping item - excluded by sync_list config: Documents
    Skipping item - excluded by sync_list config: Pictures
    Processing 222 OneDrive items to ensure consistent local state due to sync_list being used
    Skipping item - excluded by sync_list config: Documents
    Skipping item - excluded by sync_list config: Finances
    ... (with similar lines to the last few being repeated hundreds of times)

In either case, I did not wait until the end because it seemed to be going through my whole account, which would take a very long time.

**Comment by abraunegg** [comment]
@gatlanticus 
This is not a bug or issue. This is due to how the OneDrive API exposes files & data, and how 'changes' online are only presented via the /delta call. To ensure a consistent local state - even if you have a selection of data - moves | adds | deletes that fall outside of /delta notifications will then be missed - thus leading to an inconsistent. This is why the application operates in this manner.

**Comment by gatlanticus** [comment]
OK, thank you for the explanation.
