### ISSUE TITLE
Can Not Download From Onedrive

### ISSUE THREAD

**Issue by oliverck** [abraunegg/onedrive#1746]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
Can Not Download from Onedrive

**Application and Operating System Details:**
*   Ubuntu 20.04
*   Using Docker
*   Onedrive Account Type: Microsoft 365 Home (China)

```
Application Log Output:
ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't resolve host name on handle 558A36FA0060
  Calling Function: download()

ERROR: File download size mis-match. Increase logging verbosity to determine why.
ERROR: File download hash mis-match. Increase logging verbosity to determine why.
INFO: Potentially add --disable-download-validation to work around this issue but downloaded data integrity cannot be guaranteed.
```

And how can I config update only in docker??

**Comment by abraunegg** [comment]
@oliverck 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
