### ISSUE TITLE
Slow when Syncing Many Files

### ISSUE THREAD

**Issue by Modelmat** [abraunegg/onedrive#175]
### Bug Report Details ###
**Describe the bug**
When syncing many files, it is slow. Whilst syncing larger files, it downloads fast. About 10-100x faster with larger files.
https://github.com/skilion/onedrive/issues/250
**Application and Operating System Details:**
- OS:  Linux desktop 4.18.6-1-MANJARO #1 SMP PREEMPT Wed Sep 5 19:26:55 UTC 2018 x86_64 GNU/Linux 
- Are you using a headless system (no gui) or with a gui installed? GUI
- Application version: onedrive v2.1.2-5-g53cbc8f
- OneDrive Account Type: Business
- DMD or LDC compiler version: `DMD64 D Compiler v2.082.0
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright`

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. Not what it's for, but certainly easiest way, create a node_modules directory or venv, sync on windows
2. Sync using onedrive `onedrive --synchronize`

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```
onedrive --synchronize --verbose <any of your other needed options>
```

only downloading files, not really useful

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See https://guides.github.com/features/mastering-markdown/ for more details.

**Screenshots**
![peek 2018-09-14 17-20](https://user-images.githubusercontent.com/25718989/45535590-5b111a80-b842-11e8-8e7f-bedd77533805.gif)

**Additional context**
https://github.com/skilion/onedrive/issues/250

### Bug Report Checklist ###
- [x] Detailed description
- [x] Reproduction steps (if applicable)
- [ ] Verbose Log Output

**Comment by abraunegg** [comment]
@Modelmat 
Can you provide an analysis of all your files in terms of:

* total # of files
* the type of file size ranges & # - ie 10K small files ~1 byte large

This can then be used to provide some metrics for analysis and testing of any future code changes. This is also potentially similar to #157

**Comment by Modelmat** [comment]
Yeah, it's probably the fix for this. The example above is a python virtualenv, with about 300 files. Most are about 1kb - the entire folder is 7MB.
