### ISSUE TITLE
After installing and later uninstalling it with the Debian package manager, onedrive.service restarts in a loop when it no longer exists

### ISSUE THREAD

**Issue by grohart** [abraunegg/onedrive#1750]
Hello,

I hope I am in the right place and that this issue was not already opened.

I installed onedrive Linux client on my Debian 11 bullseye distrib via _apt_ using the opensuse repository:
_deb https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/Debian_11/ ./_

After later removing onedrive via the _apt remove_ command, the following messages are displayed in a loop into my _syslog_:

```
Dec 15 12:35:45 myserver systemd[5883]: Stopped OneDrive Free Client.
Dec 15 12:35:45 myserver systemd[5883]: Started OneDrive Free Client.
Dec 15 12:35:45 myserver systemd[33573]: onedrive.service: Failed to locate executable /usr/bin/onedrive: No such file or directory
Dec 15 12:35:45 myserver systemd[33573]: onedrive.service: Failed at step EXEC spawning /usr/bin/onedrive: No such file or directory
Dec 15 12:35:45 myserver systemd[5883]: onedrive.service: Main process exited, code=exited, status=203/EXEC
Dec 15 12:35:45 myserver systemd[5883]: onedrive.service: Failed with result 'exit-code'.
Dec 15 12:35:48 myserver systemd[5883]: onedrive.service: Scheduled restart job, restart counter is at 4463.
Dec 15 12:35:48 myserver systemd[5883]: Stopped OneDrive Free Client.
Dec 15 12:35:48 myserver systemd[5883]: Started OneDrive Free Client.
Dec 15 12:35:48 myserver systemd[33575]: onedrive.service: Failed to locate executable /usr/bin/onedrive: No such file or directory
Dec 15 12:35:48 myserver systemd[33575]: onedrive.service: Failed at step EXEC spawning /usr/bin/onedrive: No such file or directory
Dec 15 12:35:48 myserver systemd[5883]: onedrive.service: Main process exited, code=exited, status=203/EXEC
Dec 15 12:35:48 myserver systemd[5883]: onedrive.service: Failed with result 'exit-code'.
Dec 15 12:35:51 myserver systemd[5883]: onedrive.service: Scheduled restart job, restart counter is at 4464.
```

I tried almost everything:

```
#  systemctl --user disable onedrive
# systemctl --user stop onedrive
#  sudo systemctl disable onedrive@myuser.service
# sudo systemctl disable onedrive
# sudo systemctl daemon-reload
# sudo systemctl reset-failed
```

Nothing seems to work, could someone help me?

**Comment by grohart** [comment]
hmmm never mind, after running the command _ps aux | grep 5883_ I found this line:

`another_user+    5883  0.0  0.0  15244  7620 ?        Ss   08:34   0:13 /lib/systemd/systemd --user
`

And after killing the _5883_ process the messages are not displayed anymore, but I can't tell why this user was running the service in the first place...

**Comment by abraunegg** [comment]
@grohart 
Glad you solved your issue - but next time please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

> After later removing onedrive via the apt remove command, the following messages are displayed in a loop into my syslog
> ....
> And after killing the 5883 process the messages are not displayed anymore, but I can't tell why this user was running the service in the first place...

This is because you potentially missed reading this section: 
* https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md#known-issues-with-installing-from-the-above-packages
