### ISSUE TITLE
Unable to upload to shared folder (OneDrive Personal) when using  --upload-only --no-remote-delete --resync

### ISSUE THREAD

**Issue by MADx00** [abraunegg/onedrive#1761]
### Bug Report Details ###
**Describe the bug**
I  can not upload to a shared folder, even after "Add to my OneDrive".

**Application and Operating System Details:**
*   Ubuntu 20.04.3 LTS 
*   Headless system (no GUI)
*   OneDrive Personal
*   Install from package [ubuntu-package-install.md](https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md)
*   onedrive v2.4.14-1~np1
*   OneDrive Application Configuration: 
```
onedrive version                       = v2.4.14-1~np1
Config path                            = /home/xxx/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/xxx/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: curl 7.68.0
*   Explain your entire configuration setup : The shared folder is from a personal account that is shared with me (also personal account)

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  add the folder to my one drive as [Shared folders (OneDrive Personal)
](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#shared-folders-onedrive-personal)
2.  Move the desired folder to the shared OneDrive Folder
3.  Sync/upload folder/files

**Complete Verbose Log Output**

Application Log Output:
The shared folder name is "tmp"

```bash
$ onedrive --synchronize --upload-only --no-remote-delete --resync
Deleting the saved application sync status ...
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/OneDrive
Uploading new items of ~/OneDrive
OneDrive generated an error when creating this path: ./tmp/xxx

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 400 (Bad Request)
  Error Reason:     Cannot perform operation within a mounted folder.
  Error Timestamp:  2021-12-29T20:59:18
  API Request ID:   xxx
  Calling Function: uploadCreateDir()
```

**Additional context**
while googling the request error I found this page, it may be useful:
https://www.akeeba.com/support/akeeba-backup-3x/Ticket/31598:remote-backup-with-onedrive-error-could-not-create-directory-500-error-generalexception-cannot-perfo.html

**Comment by abraunegg** [comment]
@MADx00 
Please provide a full verbose debug log as per support requirements

**Comment by abraunegg** [comment]
@MADx00 
Please can you test the following PR:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1762/head:pr1762
git checkout pr1762
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.14-8-g25c9002` or greater.

**Comment by MADx00** [comment]
Great, the new version works fine.

Thanks.

**Comment by abraunegg** [comment]
@MADx00 
Thanks for the confirmation - will merge the PR into 'master'
