### ISSUE TITLE
Getting Error trying to register> probably me and not a bug

### ISSUE THREAD

**Issue by jwaltrip4** [abraunegg/onedrive#1766]
Ubuntu 20.04
Just install your onedrive client.

Ran: **sudo onedrive**
Linked to URL, Pasted in link
Got this:
**====================**
onedrive.OneDriveException@src/onedrive.d(874): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "0314b3dd-e300-4f70-be80-4c32858fba7c",
    "error": "invalid_grant",
    "error_codes": [
        70000
    ],
    "error_description": "AADSTS70000: The provided value for the 'code' parameter is not valid.\r\nTrace ID: ff26e29f-182a-4c20-af9f-9772856afc02\r\nCorrelation ID: 0314b3dd-e300-4f70-be80-4c32858fba7c\r\nTimestamp: 2021-12-30 19:05:23Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=70000",
    "timestamp": "2021-12-30 19:05:23Z",
    "trace_id": "ff26e29f-182a-4c20-af9f-9772856afc02"
}
----------------
??:? [0x556560e649d9]
??:? [0x556560e63cb5]
??:? [0x556560e64b65]
??:? [0x556560e62f58]
??:? [0x556560e628c5]
??:? [0x556560e707a8]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7f87e58659db]
??:? _d_run_main2 [0x7f87e58657ee]
??:? _d_run_main [0x7f87e586565d]
??:? __libc_start_main [0x7f87e54510b2]
??:? [0x556560e3b5ed]

**Comment by abraunegg** [comment]
@jwaltrip4 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

**Comment by jwaltrip4** [comment]
That did it

Thanks
