### ISSUE TITLE
Not Syncing Symlink Folders

### ISSUE THREAD

**Issue by matthewdolman** [abraunegg/onedrive#1770]
I have a folder located at `/media/folder/source` and have a symbolic link to that at `/media/folder/onedrive/source`

The link is absolute, ie `ln -s /media/folder/source /media/folder/onedrive/source'

Even though it is an absolute link when syncing I get the message in the console "Skipping item - invalid symbolic link: ./source".

Just using docker with standard settings, UID and GID are all set properly and permissions are all 777

Not familiar with the code, but looking in sync.d it seems to test specifically for a filename, does this mean symlinks to folders are not supported?

**Comment by abraunegg** [comment]
@matthewdolman 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

**Comment by matthewdolman** [comment]
If anyone else is struggling with this, you also need to mount any target folder at the same absolute location in the container.

`docker run ........ -v /media/folder/source:/media/folder/source`
