### ISSUE TITLE
Add the app to myapps (https://myapplications.microsoft.com/)

### ISSUE THREAD

**Issue by GillesC** [abraunegg/onedrive#1779]
Hi,
For some companies it requires that the app is added in the page: https://myapplications.microsoft.com/.
Maybe the docs can be updated to include this step as well.
As for my case, I first had to add the app before the authentication procedure.

As I didn't know where to put this, I opened an issue as a FR.
Let me know whete I best put this and I'll make a PR.

Thanks!

**Comment by abraunegg** [comment]
If you could open as a PR with any of the documentation updates needed that would be greatly appreciated.

**Comment by abraunegg** [comment]
@GillesC 
Any update here in drafting a PR with the required documentation updates that are applicable to this situation?

**Comment by abraunegg** [comment]
@GillesC 
Closing issue due to lack of response from OP
