### ISSUE TITLE
Install failed dependancy Pop OS 21.10

### ISSUE THREAD

**Issue by AMoonRabbit** [abraunegg/onedrive#1785]
Hello, I am trying to get Onedrive installed on my Pop OS install and have followed the OpenSuSE instructions but when trying to run `sudo apt install onedrive` I get the following output

```
sudo apt install onedrive
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 onedrive : Depends: libphobos2-ldc-shared82 (>= 1:1.12.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

After the first failed attempt, I then saw a post about installing dependancies, so I used the following:

```
sudo apt install build-essential
sudo apt install libcurl4-openssl-dev
sudo apt install libsqlite3-dev
sudo apt install pkg-config
sudo apt install git
sudo apt install curl
curl -fsS https://dlang.org/install.sh | bash -s dmd
```

Device Detail
OS: Pop!_OS 21.10 x86_64 
Host: Surface Pro 4 124000000000000000000000D:0B:09F:1C:03P:38 
Kernel: 5.15.8-76051508-generic 
DE: GNOME 40.5 
CPU: Intel i5-6300U (4) @ 2.400GHz 
GPU: Intel Skylake GT2 [HD Graphics 520] 
Memory: 2783MiB / 3846MiB

I've had it installed on this device previously, but a while back and I cannot remember how.

**Comment by abraunegg** [comment]
@AMoonRabbit 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

Additionally, package dependencies issues need to be fixed by the package maintainer - please get in contact with the package maintainer to resolve.

The dependencies you have installed are only relevant if you are building from source.

**Comment by abraunegg** [comment]
@AMoonRabbit 
Just to close this out - most likely you did not follow the instructions correctly as documented here: https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md

1. Always ensure your platform is up-to-date first. Use a script like below, as 'root' to update your Ubuntu OS:
```
#!/bin/bash
rm -rf /var/lib/dpkg/lock-frontend
rm -rf /var/lib/dpkg/lock
apt-get update
apt-get upgrade -y
apt-get dist-upgrade -y
apt-get autoremove -y
apt-get autoclean -y
reboot
```

2. Use the correct instructions for your OS - POP_OS 21.10 is based on Ubuntu 21.10:

![uname](https://user-images.githubusercontent.com/4956234/148706409-d27f60ca-3b02-4de1-a442-78ab90a15d5d.JPG)


3. Configure the repository as per [step 1](https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md#step-1-update-etcaptsourceslist-4) and [step 2](https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md#step-2-download-and-add-the-release-key-4)

![apt-sources](https://user-images.githubusercontent.com/4956234/148706613-1f40344a-78d0-4bd1-828a-2ce57fcfbd05.JPG)


![configure repo](https://user-images.githubusercontent.com/4956234/148706422-cd17445f-fdee-4656-a268-5808f27fbeea.JPG)

4. Update the package cache as per [step 3](https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md#step-3-update-your-apt-package-cache-4)

![update repo](https://user-images.githubusercontent.com/4956234/148706449-0af6918c-bc89-4763-8ec4-cefac3c4e4a1.JPG)


5. Install the application as per [step 4](https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md#step-4-install-onedrive-4)

![install](https://user-images.githubusercontent.com/4956234/148706481-24fbda8e-2527-48d3-801c-0b7bdacb9b33.JPG)

No dependency issues ...............

**Reminder:** Read and Understand the known issues with these packages.


6. Run the application

![installed_and_running](https://user-images.githubusercontent.com/4956234/148706508-af97d388-8304-4307-a358-0543684cf2c1.JPG)
