### ISSUE TITLE
apt-key deprecated - install docs for Ubuntu need to be updated

### ISSUE THREAD

**Issue by murraycs** [abraunegg/onedrive#1787]
When following the install instructions for Ubuntu-based distributions, the system gives the following error:

> Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).

The man page indicates that apt-key will last be available in Ubuntu 22.04, and best practice going forward is the following:

> Note: Instead of using this command a keyring should be placed directly in the /etc/apt/trusted.gpg.d/ directory with a descriptive name and either "gpg" or "asc" as file extension.

I am happy to update the docs in preparation for apt-key's removal if someone can let me know where users should obtain the key.

**Comment by murraycs** [comment]
For Pop_OS, the process is straightforward:

1. Add the repository using "Repoman" within the PopShop settings
2. Run sudo apt-get onedrive
3. Deal with known issues

I will report back if I hit any unexpected hiccups, but so far so good.

**Comment by abraunegg** [comment]
@murraycs 
> ...
> The man page indicates that apt-key will last be available in Ubuntu 22.04, and best practice going forward is the following ..

Thanks for the heads up, however, this means that the current process for the Ubuntu platforms that *are* currently supported by the Ubuntu OpenSuSE Build Service have no such issue.

Ubuntu 22.04 has an EOL date of April 2032 as it is an LTS release .. so, my expectation here that apt-key will still be 100% functional on that platform until that time.

> I am happy to update the docs in preparation for apt-key's removal if someone can let me know where users should obtain the key.

The document clearly articulates where to obtain the key from - however the OpenSuSE Build Service does not support Ubuntu 22.04.

Once Ubuntu 22.04 is supported by OBS, the documentation can be updated to reflect using the new Ubuntu process.

Closing issue, as irrelevant for the moment.
