### ISSUE TITLE
Sync only specific folders (whitelist instead of blacklist)

### ISSUE THREAD

**Issue by larsaars** [abraunegg/onedrive#1790]
**Is your feature request related to a problem? Please describe.**
If I want to sync only for example one folder, I have to manually exclude all other folders, reading the docs I have found no method to do the opposite, of syncing only specific folders.

**Describe the solution you'd like**
There is only a blacklist, but I'm also in need of a whitelist.

**Comment by abraunegg** [comment]
@larsaars 
Please re-read the documentation - this is possible and clearly documented in a number of places
