### ISSUE TITLE
One way upload sync does not delete OneDrive files that do not exist locally

### ISSUE THREAD

**Issue by callegar** [abraunegg/onedrive#1791]
### Bug Report Details ###
**Describe the bug**

I have a situation where I want to make a directory on OneDrive identical to a directory that is local to my system, so I am syncing with `--sinchronize --upload-only --single-directory <dir>`. Unfortunately, what I get from it is not an identical copy of my local directory. On OneDrive I still have files that are not present on my local system. In fact, if after that I try to perform a regular (bidirectional) sync, onedrive immediately tries to download them to the local system.

The issue is present either with or without `--resync` in the upload only synchronization.

The issue appears to happen with files starting with a dot, but I have selected no special treatment for them.

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
Linux 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

*   Are you using a headless system (no gui) or with a gui installed?
Working from the terminal in KDE plasma

*   OneDrive Account Type
Provided by my company

*   Did you build from source or install from a package?
Locally built deb from the git tree

*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
DMD64 D Compiler v2.097.0

*   OneDrive Application Version: Output of `onedrive --version`
`onedrive v2.4.13-5-g8a20275`

*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
Configuration file successfully loaded
onedrive version                       = v2.4.13-5-g8a20275
Config path                            = /home/callegar/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = true
Config option 'sync_dir'               = /home/callegar/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

*   Provide the version of curl you are using: Output of `curl --version`
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

*   Is your configured 'sync_dir' a local directory or a network mount point?
It is a link to a directory on a second internal disk that is mounted to /mnt/something. It is mounted from `fstab` and not removable.

*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f`
btrfs
 
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
Local to onedrive, so far.

Will generate logs if the issue persists (now I have already manually deleted the files causing the issue).

**Comment by abraunegg** [comment]
@callegar 
> onedrive v2.4.13-5-g8a20275

You are running an invalid and unsupported client version. 

Please upgrade your client before seeking support

**Comment by callegar** [comment]
Sorry for the noise, I'll upgrade to 2.4.15 and if the issue comes again open a new bug.
