### ISSUE TITLE
Wishlist: "translate" symlink option

### ISSUE THREAD

**Issue by callegar** [abraunegg/onedrive#1796]
**Is your feature request related to a problem? Please describe.**

Using onedrive with linux systems can at times be unpractical because onedrive does not perfectly match the posix filesystem semantics.  The main issue is the management of symlinks.  If you upload a directory that includes symlinks to onedrive those cannot be stored on onedrive.

Currently the onedrive client offers two options: (a) skip them; or (b) follow the links and store the corresponding file.  Both can be unsatisfactory: with (a) you miss something; with (b) when you download back the directory your symlinks will be gone.

**Describe the solution you'd like**

I advocate the introduction of a `--translate-symlinks` options that will let symlink be transformed to and from regular text files with a special syntax.  This will be consistent to the way in which other programs store symlinks on system that do not support them. For instance consider `git` that has the option to represent symlinks as small text files containing the path linked to.

With `--translate-symlinks` a local symbolic link such as `file_a` pointing to `dir_b/file_c` would be uploaded to onedrive as a file named `file_a` with content `OneDrive filelink -> dir_b/file_c`. On download, the onedrive client would recognize the special content of the file by matching the initial `OneDrive filelink` string (or whatever string is deemed appropriate) and create a `file_a` symlink pointing to `dir_b/file_c`.

This proposal would let one use onedrive as an effective synchronization mechanism even for linux filesystems.

**Describe alternatives you've considered**

As an alternative to the `--translate-symlinks` options, consider deprecating the `--skip-symlinks` options and introducing a new ternary switch `--symlinks` taking values `ignore`, `follow`, `translate`.

**Additional context**

None

**Comment by abraunegg** [comment]
@callegar 
OneDrive API does not support symbolic links, so, the client already converts the symbolic link to an actual file or folder to upload.

Tracking any 'translation' or conversion so that when you are downloading a 'file' or 'folder' it converts back to a symbolic link is impractical.

**Comment by callegar** [comment]
> OneDrive API does not support symbolic links

Indeed, I was pointing it out myself (onedrive does not match the posix filesystem semantics)

> so, the client already converts the symbolic link to an actual file or folder to upload

If I understand correctly, it does not *convert* in strict sense, it *follows* (dereferences) the link, namely it uploads whatever the link points to. This happens, unless you choose to skip symlinks, which in some scenarios may be advisable because following symlinks while syncing to shared folders can be a security hazard.

Possible scenario: Mr. A and Mr. B use platforms supporting symbolic links. Mr. A shares a folder on OneDrive with Mr. B and uses `onedrive` to keep it in sync with his own stuff. Mr. B passes an archive file (e.g., a zip or a tar.gz) to Mr. A via a different channel (e.g., via email or pushing him to download the file from a web server) and convinces him to expand its content in the directory that that is synced to the shared folder. The archive is evilly crafted to contain a symbolic link to some location where in the system of Mr. A there a secret is held (e.g. a link to `~/.ssh/id_rsa`, namely Mr. A's ssh private key). In this way, Mr. B receives Mr. A's secret on the shared folder in OneDrive.

Is my understanding correct?

> Tracking any 'translation' or conversion so that when you are downloading a 'file' or 'folder' it converts back to a symbolic link is impractical.

It is unclear to me what you mean by *impractical*.  Do you regard it as impractical for the programmer to code it or for the user?
- At the code level, it should involve a conditional based on the comparison of the first 10-20 bytes of every file (depending on the length of the chosen filelink signature), which looks rather tolerable both in complexity and in overhead.
- For the user, well, someone's impractical may be someone else's delight. For instance, I am advocating this feature because as is I cannot use the `onedrive` software and OneDrive to sync a directory among multiple linux systems without losing the symlinks. With this feature, this very practical thing would become possible.  Now, I agree that it would be impractical to have this behavior as a non optional one, but what I am suggesting is precisely to introduce this behavior as an *optional* behavior under the control of a flag.

With respect to practicality, I also would like to suggest that the very `git` on which `onedrive` has its repo supports this kind of translation (via the `core.symlink` option).

Following these considerations, I would like to kindly ask to reconsider the decision to drop the feature request altogether or alternatively to at least provide some hint at why it could be impractical at the code level (should it be so) and what would be the key functions to look at, attempting an independent implementation.

**Comment by abraunegg** [comment]
@callegar 
> Possible scenario ..

Well that's plausible - but the onus is on Mr B to test the archives & trust what is being sent is correct before blindly extracting data as requested .... this of all has nothing to do with this client operation.

> On download, files are checked for the special header. If the special header is found, the file is converted into the corresponding symlink

OneDrive API and files stored on OneDrive does not support 'extra header' data in files. Microsoft adds its own XML data into some file types, but that is done on their end inside SharePoint. Even if the API / platform were to support something like that, it would be highly impractical to convert symbolic links to text files - and be totally meaningless garbage to any other platform that looks | uses those files - such as Windows platforms - it may even make the file 'appear' corrupt ...

> Following these considerations ..

Feel free to delve into the code and write a PR to support your requirement for your needs

Your challenges will be:
* OneDrive API itself
* DMD / LDC on how it handles links / symbolic links
* File handling & tracking
