### ISSUE TITLE
Fail excute command but install Onedrive in Centos 7

### ISSUE THREAD

**Issue by bisol2022** [abraunegg/onedrive#1797]
### Bug Report Details ###
An AWS virtual machine was created to install the application
The following error is displayed when executing the command _sudo make install_
The DMD was active all the time of executing the command
source ~/dlang/dmd-2.098.1/activate

**Application and Operating System Details:**

*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
Linux ip-172-31-90-207.ec2.internal 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

*   Are you using a headless system (no gui) or with a gui installed?
This equipment does not have a graphical interface. (GUI)
*   OneDrive Account Type
At the beginning of the development, a personal account will be used, and when validating that everything is correct, it will be changed to a company account.
*   Did you build from source or install from a package?
It was Installed from source, from the github website
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
DMD64 D Compiler v2.098.1
Copyright (C) 1999-2021 by The D Language Foundation, All Rights Reserved written by Walter Bright
*   OneDrive Application Version: Output of `onedrive --version`
v2.4.15-6-gc30fa4b
This information was obtained from the version file, inside the onedrive folder
*   OneDrive Application Configuration: Output of `onedrive --display-config`
*   Provide the version of curl you are using: Output of `curl --version`
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
*   Is your configured 'sync_dir' a local directory or a network mount point?
local directory
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f`
NAME    FSTYPE LABEL UUID                                 MOUNTPOINT
xvda
└─xvda1 xfs          388a99ed-9486-4a46-aeb6-06eaf6c47675 /

*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time

The OneDrive folder will only be used on that computer (centos), so that the changes made in the Cloud OneDrive are updated in the OneDrive folder on the computer.
**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au
The log cannot be generated because the Onedrive application is not installed.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Log in virtual machine
2.  User change to root
3.  Install application sudo yum groupinstall 'Development Tools'
4.  Install application  sudo yum install libcurl-devel
5.  Install application sudo yum -y install sqlite-devel
6.  Run command curl -fsS https://dlang.org/install.sh | bash -s dmd
7. Activate command dmd comando source ~/dlang/dmd-2.098.1/activate
8. Run command git clone https://github.com/abraunegg/onedrive.git
9. Get into the folder with command cd onedrive
10. Run command ./configure
11. Run command make clean
12. Run command make
13. Run command sudo make install

In step 13, the error is displayed.

I searched about the error.  I found this.
https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions#make-command-during-installation-encounters-error-127
In the installation process,  I already was logged into the DMD

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Screenshots**
[installOnedrive_error_centos.txt](https://github.com/abraunegg/onedrive/files/7871871/installOnedrive_error_centos.txt)

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Application and Operating System Details provided in full
*   [X] Reproduction steps (if applicable)
*   [X] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@bisol2022 
From your `lsblk` output you only have disk mounted on '/` missing swap space.

Please re-read the requirements to build from source as you are non-compliant with these requirements: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#building-from-source---high-level-requirements

If you still have issues, try build an RPM file for your system - although this may also still fail as you are missing swap space:
https://github.com/abraunegg/onedrive/blob/master/docs/build-rpm-howto.md

**Comment by bisol2022** [comment]
Thanks for your answer. Please tell me how to do it, so that every 7 hours the entire onedrive all folders is updated.
I am testing with crontab.
