### ISSUE TITLE
Can't find SharePoint Library

### ISSUE THREAD

**Issue by dysonsphere-startmail** [abraunegg/onedrive#1798]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
I followed the instructions to synchronize a SharePoint site.  Unfortunately, on step 2, the application is unable to find the SharePoint named.  I tried both with "Public" and "Private" SharePoints, same result.  Also, since my institution seems to add "_Group" to and SharePoint name I create I also tried using names with and without the "_Group" appended, again same result.

**Application and Operating System Details:**
*   Pop!_OS 21.10 : Linux serval-pop-os 5.15.11-76051511-generic #202112220937~1640185481~21.10~b3a2c21 SMP Wed Dec 22 15:41:49 U x86_64 x86_64 x86_64 GNU/Linux
*   GUI system
*   Business (University) OneDrive Account
*   OneDrive For Linux built from source
*   Compiled with dmd-2.098.1
*   OneDrive Application Version 2.4.15-5-gf72f6c9
*   OneDrive Application Configuration
```Configuration file successfully loaded
config file has been updated, checking if --resync needed
onedrive version                       = v2.4.15-5-gf72f6c9
Config path                            = /home/kdys/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/kdys/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = true
business_shared_folders contents:
Ken Dyson FINAL
Ken Dyson JPEGs
```
* curl version: 
```
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 libidn2/2.3.1 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
*   'sync_dir' is a local directory
*   ext4   1.0 file system
*   The OneDrive account I use is shared on this Pop!_OS PC and my Android mobile device.

*A full debug log was emailed to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Enter: `onedrive --get-O365-drive-id 'LinuxTest_Group'` in the terminal
2.  See: 
```
Configuration file successfully loaded
config file has been updated, checking if --resync needed
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: LinuxTest_Group
ERROR: Query of OneDrive for Office 365 Library Name failed

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 404 (Not Found)
  Error Reason:     Item not found
  Error Timestamp:  2022-01-14T17:04:35
  API Request ID:   a0651927-5a89-468e-8dda-094607c21591
  Calling Function: querySiteCollectionForDriveID()
```

**Complete Verbose Log Output**
onedrive --get-O365-drive-id 'LinuxTest_Group' --verbose
Application Log Output:
```bash
Using 'user' Config Dir: /home/kdys/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/kdys/OneDrive
Application version: v2.4.15-5-gf72f6c9
Account Type: business
Default Drive ID: b!EDJIAfShWUOWwKD1e8wrXo-AuciK-GZCkVDhmdwIa6TMwW9IB-a_TokIoT_TD5XI
Default Root ID: 01ANVJFL56Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1096533148982
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Office 365 Library Name Query: LinuxTest_Group
ERROR: Query of OneDrive for Office 365 Library Name failed

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 404 (Not Found)
  Error Reason:     Item not found
  Error Timestamp:  2022-01-14T17:49:06
  API Request ID:   5cd0457a-31a1-4ccf-bbef-f2c1d0f82042
  Calling Function: querySiteCollectionForDriveID()


```

**Screenshots**
See attached shot of the library name I am trying to sync.

**Additional context**

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output from your error
*   [x] Debug Log generated and submitted

![libraryName](https://user-images.githubusercontent.com/22195888/149557001-7f73d149-086e-475b-8e5e-45bf573b22f3.png)

**Comment by abraunegg** [comment]
@dysonsphere-startmail 

It would appear that your OneDrive SharePoint site has either permissions issues or is not setup correctly. This is *not* a bug with the client.

If a 'SharePoint' site, when configured correctly, with the correct permissions, and you do not know the name of the entity, the client will respond as follows:
```
Using 'user' Config Dir: /home/alex/.config/onedrive-business/
Using 'system' Config Dir: 
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Application version: v2.4.15-7-g33a2de1
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1099504347541
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Office 365 Library Name Query: LinuxTest_Group

ERROR: The requested SharePoint site could not be found. Please check it's name and your permissions to access the site.

The following SharePoint site names were returned:
 * testteamsite
 * Communication site
 * testteamsite2
 * test site
 * Data Production
 * All Company
 * PointPublishing Hub Site
 * mynasau3
 * Community
 * Team Site
```


To understand where it is failing on OneDrive, a verbose HTTPS debug log is required. See: https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support

**Comment by abraunegg** [comment]
@dysonsphere-startmail 
As per offline conversation, this issue stems from your account access to query standard Microsoft OneDrive API endpoints.

This is nothing that I can do to assist to resolve as this is not an application issue.

**Comment by dysonsphere-startmail** [comment]
Thanks @abraunegg .  I will take this up with my IT admin.
