### ISSUE TITLE
symlinks are not uploaded

### ISSUE THREAD

**Issue by ittayd** [abraunegg/onedrive#1800]
### Bug Report Details ###
I've created a symlink in my onedrive folder, it is to a full path that is outside of the onedrive folder. The file is not uploaded

**Application and Operating System Details:**
*   Linux 14d1f1c07567 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux
*   No GUI
*   Personal
*   Source
*   Used DMD from here: https://hub.docker.com/r/antonmeep/dmd
*  v2.4.13-20-gd99bd5a
*   onedrive version                       = v2.4.13-20-gd99bd5a
Config path                            = /home/www-data/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /var/www/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
!/MediawikiBackup/data/locks*
!/MediawikiBackup/data/*cache.sqlite*
!/MediawikiBackup/data/*jobqueue.sqlite*

# Just sync the mediawiki backup folder
/MediawikiBackup/*

Business Shared Folders configured     = false
*   curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

*  local
*   NAME    FSTYPE FSVER LABEL UUID FSAVAIL FSUSE% MOUNTPOINT
vda
|-vda1                            19.3G    17% /etc/hosts
|-vda14
`-vda15
vdb

*   the one drive folder is not shared.

**Comment by ittayd** [comment]
It did it after some time...

**Comment by abraunegg** [comment]
@ittayd 
> Used DMD from here: https://hub.docker.com/r/antonmeep/dmd

This is not supported - use the correct process.


> v2.4.13-20-gd99bd5a

You are using an unsupported and obsolete client version. Upgrade your client before seeking support.
