### ISSUE TITLE
can't upload files with message: Skipping uploading this new file as parent path is not in the database

### ISSUE THREAD

**Issue by WSandwitch** [abraunegg/onedrive#1808]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
onedrive[289878]: Skipping uploading this new file as parent path is not in the database: for many files

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `5.11.0-1023-aws #24~20.04.1-Ubuntu SMP Fri Dec 3 13:46:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed? headless
*   OneDrive Account Type bussines
*   Did you build from source or install from a package? build from master
*   If you installed from source, what is your DMD or LDC compiler version: DMD64 D Compiler v2.096.1
Copyright (C) 1999-2021 by The D Language Foundation, All Rights Reserved written by Walter Bright
*   OneDrive Application Version: onedrive v2.4.15-9-g2c71e94
*   OneDrive Application Configuration:
```
onedrive version                       = v2.4.15-9-g2c71e94
Config path                            = /home/scheduler/.config/onedrive_reportautomation
Config file found in config path       = true
Config option 'check_nosync'           = true
Config option 'sync_dir'               = /home/scheduler/Reporting Automation
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*
Config option 'skip_dotfiles'          = true
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 200
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /home/scheduler/onedrivelog/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = true
Config option 'remove_source_files'    = false
Config option 'drive_id'               = b!60xDdUWnoUee2Ds1kdj2mX1gUAqKYsVDosIAWayR3xeBG-68FO5PQr6ewOCoKtFI
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: curl 7.77.0-DEV (x86_64-pc-linux-gnu) libcurl/7.77.0-DEV OpenSSL/1.1.1f zlib/1.2.11 zstd/1.4.4 nghttp2/1.40.0
*   Is your configured 'sync_dir' a local directory or a network mount point? local

*   What partition format type does your configured 'sync_dir' reside on?  nvme0n1p1 ext4     cloudimg-rootfs 
*   Onedrive folder shared with many accounds, current account run only on one host.

onedrive running with --no-remote-delete

**Comment by WSandwitch** [comment]
sent log to support@mynas.com.au

**Comment by abraunegg** [comment]
@WSandwitch 
> onedrive running with --no-remote-delete

Please can you clarify the 'full' command you are using

**Comment by abraunegg** [comment]
@WSandwitch 
After reviewing the debug log the cause of the issue is that the parent item cannot be queried in the database, however, the exact item being queried is added to the DB in prior operations.

So there is potentially one of the following going on:
* Memory stack level corruption
* File system corruption

As this is Ubuntu, not updated, running on AWS - this could be an indicator of a block write hole issue on AWS / underlying storage subsystem being presented up to Ubuntu.

Suggestions for resolution provided offline.

**Comment by WSandwitch** [comment]
I use this command:
/usr/local/bin/onedrive --monitor --confdir=/home/scheduler/.config/onedrive_reportautomation --no-remote-delete

Looks like there was an error in local database..
I started client with --resync and it uploaded all files.

Thanks for the help.
