### ISSUE TITLE
Wrong config directory is used if $XDG_CONFIG_HOME is present

### ISSUE THREAD

**Issue by marcusball** [abraunegg/onedrive#181]
### Bug Report Details ###
**Describe the bug**
The environment variable `XDG_CONFIG_HOME` defines the path to the main directory for configuration files (ex: `/home/username/.config`), however, [it is currently being used as the `homePath`](https://github.com/abraunegg/onedrive/blob/master/src/main.d#L14) so when it is set, [onedrive uses `/home/username/.config/.config/onedrive` as the config directory](https://github.com/abraunegg/onedrive/blob/master/src/main.d#L33) rather than `/home/username/.config/onedrive`. 

**Application and Operating System Details:**
- OS: Linux archlabs 4.18.6-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 5 11:54:09 UTC 2018 x86_64 GNU/Linux
- Application version: `onedrive v2.1.2-5-g53cbc8f`
- OneDrive Account Type: Personal
- DMD version: `DMD64 D Compiler v2.082.0`

**To Reproduce**

* Set `XDG_CONFIG_HOME` to the base directory in which the onedrive config directory should be stored. 
* Onedrive will use the path `$XDG_CONFIG_HOME/.config/onedrive` rather than `$XDG_CONFIG_HOME/onedrive`. 

**Complete Verbose Log Output**
```
2018-Sep-19 12:01:13.2023002 Loading config ...
2018-Sep-19 12:01:13.2023763 Using Config Dir: /home/marcus/.config/.config/onedrive
2018-Sep-19 12:01:13.2024817 No config file found, using defaults
```

**Comment by abraunegg** [comment]
Thanks for finding this and submitting a PR too

**Comment by abraunegg** [comment]
PR merged after local testing
