### ISSUE TITLE
Support for NextCloud

### ISSUE THREAD

**Issue by afzl-wtu** [abraunegg/onedrive#1821]
NextClound currently have no OneDrive support, specially for OneDrive for Business. Microsoft do not allow to connect OneDrive for Business from new apps or unverfied apps.
Mostly universities offer their students Terabytes of free space in form of OneDrive for Business, office365 account. But we can not use that space because their policies like Disbaled public sharing link. and more over university admins can see your files.
So the soultion is this: 
1. Onedrive should be connected to Nextcloud as a folder or extra storage drive.
2. We upload file to nextcloud server and it automatically encrypt its data and name and then upload to onedrive.
3. But we still can see the file in next cloud and if video file, play it on demand, decryption and download in background.

**Comment by abraunegg** [comment]
@afzl-wtu 
> NextClound currently have no OneDrive support, specially for OneDrive for Business

OK .. unfortunately I cant assist with that - speak with NextCloud?

> Microsoft do not allow to connect OneDrive for Business from new apps or unverfied apps.

Unsure what you mean by this? This app is technically 'unverified' - and as any OneDrive client, you need to authorise its use - and 100% works with OneDrive Business and SharePoint.

> So the soultion is this

I dont exactly understand what you are wanting to do - you mean have this client communicate to NextCloud and then pull data from NextCloud and put on OneDrive?

If so - this client is not a cloud-to-cloud integration tools - Google is your friend.

**Comment by afzl-wtu** [comment]
> 

Sorry for bad writing last night. Here is a plugin Next Cloud that allows you to connect Onedrive. But I am not sure if it supports Onedrive for business.
![image](https://user-images.githubusercontent.com/64379149/151692730-6a6743b0-9ce5-4f13-917f-29509b11c4a1.png)
So I go on azure portal and register an app:
![image](https://user-images.githubusercontent.com/64379149/151692921-37c9996d-3679-4aab-baf9-c3033a806bea.png)

So I see this line there:
![image](https://user-images.githubusercontent.com/64379149/151692953-108dac8a-1a00-4d3e-ac51-6c80717f6f46.png)

**Comment by abraunegg** [comment]
@afzl-wtu 
You need to take this up with the developers of that tool - all of this is nothing I can assist with - sorry.

**Comment by afzl-wtu** [comment]
> @afzl-wtu You need to take this up with the developers of that tool - all of this is nothing I can assist with - sorry.

I am able to do this with the help of rclone. I can mount my business one drive as VFS and then I point NextCloud to this folder and all set.
I highly recommend you to know about NextCloud. Thanks

**Comment by abraunegg** [comment]
@afzl-wtu 
> I am able to do this with the help of rclone. I can mount my business one drive as VFS and then I point NextCloud to this folder and all set.
> I highly recommend you to know about NextCloud. Thanks

So why dont you do the *exact* same thing using this client then? This client stores all data in `~/OneDrive` ... It seems like potentially you have not read the documents or at least tested / tried?

rclone is also a 1-way sync client - not bidirectional like this one. Rclone also does not support all the OneDrive Business items nor can it deal with the SharePoint shenanigans that go on.

**Comment by afzl-wtu** [comment]
> @afzl-wtu
> 
> > I am able to do this with the help of rclone. I can mount my business one drive as VFS and then I point NextCloud to this folder and all set.
> > I highly recommend you to know about NextCloud. Thanks
> 
> So why dont you do the _exact_ same thing using this client then? This client stores all data in `~/OneDrive` ... It seems like potentially you have not read the documents or at least tested / tried?
> 
> rclone is also a 1-way sync client - not bidirectional like this one. Rclone also does not support all the OneDrive Business items nor can it deal with the SharePoint shenanigans that go on.

rclone encrypts my files even their name and then upload them to onedrive and when i Nedd them it automatically decrypts them

**Comment by abraunegg** [comment]
@afzl-wtu 
> rclone encrypts my files even their name and then upload them to onedrive and when i Nedd them it automatically decrypts them

OneDrive does not support encrypted files | folders - whilst you *can* upload that data - depending on *how* things are encrypted (folder structure, content) - you run into their architectural legacy path length issue.

Please read https://github.com/abraunegg/onedrive/issues/1023 very carefully.

**Comment by afzl-wtu** [comment]
your Onedrive start download all files at once when connected to account , lol.
I have more than 200GB data over onedrive. So I exclude files and folders to use your onedrive software. otherwise it is best software if it support file on demand functionality,

**Comment by abraunegg** [comment]
@afzl-wtu 
> I have more than 200GB data over onedrive. So I exclude files and folders to use your onedrive software. otherwise it is best software if it support file on demand functionality

Please read: https://github.com/abraunegg/onedrive/issues/757

**Comment by abraunegg** [comment]
@afzl-wtu 
> your Onedrive start download all files at once when connected to account , lol.

Because probably you are using Ubuntu ... please read https://github.com/abraunegg/onedrive/issues/1274 and read the installation instructions for Ubuntu - https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md & https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md

**Comment by afzl-wtu** [comment]
Sure I read them  now. I I have vm instance with 4 cores arrch64 and 24GB on oracle. I just upload my files without encryption in NextCloud account it then pass to rclone directory on my vm server. It then encrypts the data and upload to onedrive. All this happens in background. When I need that data I just ask Nextcloud and it ask rclone to get data and rclone downloads and decrypts data and pass to nextcloud in background.

**Comment by afzl-wtu** [comment]
Thanks all your suggestions and work arounds:
They reason to use rclone is it integrate onedrive as a local storage in my NextCloud Drive. So I just care for Nextcloud.
2nd my Organization do not allow to share files in one drive to public. But I can overcome this by sharing Nextcloud link as onedrive files are now available in Nextcloud drive.

**Comment by afzl-wtu** [comment]
Now I got better solutions and all credit goes to you:
![image](https://user-images.githubusercontent.com/64379149/151718553-79bbf396-c939-4cae-a586-3f39f603d551.png)

**Comment by afzl-wtu** [comment]
Sadly.. This is not a solution. It will not run on my headless ubuntu it is GUI only. and their CLI is worse than even its existence.

**Comment by abraunegg** [comment]
@afzl-wtu 
As per https://github.com/abraunegg/onedrive/issues/1023 - The OneDrive service from Microsoft is not architecture to support encrypted files.

Whilst I get your desire to store encrypted content there and share the files using other technology solutions (why - for you to know ... getting around geo-political issues or sharing who-knows-what - thats your business - not mine) - OneDrive as a service itself is not the right solution for storing encrypted files in the manner you are trying to achieve.

There are *many* better cloud storage solutions / services that provide this including end-to-end encryption.

Now - just because your organisation (work|university|whatever) is providing you a nice *subsidised* storage space on OneDrive - can I suggest that potentially trying to use that, for whatever purpose you are doing (hence the encrypted files so your organisation + Microsoft cant see your data) is potentially against your user access policy / terms & conditions.
