### ISSUE TITLE
Add One Drive gnome shell extension within contrib folder ?

### ISSUE THREAD

**Issue by bufferoverflow** [abraunegg/onedrive#1824]
**Is your feature request related to a problem? Please describe.**
There is a [One Drive gnome shell extension](https://github.com/dbazza/oneDrive) for this project here and it seems [not maintained](https://github.com/dbazza/oneDrive/issues/4).

**Describe the solution you'd like**
- adding that to the contrib folder
- maybe publish along with OneDrive

**Describe alternatives you've considered**
fork https://github.com/dbazza/oneDrive , but probably nobody will find it.

**Additional context**

**Comment by abraunegg** [comment]
@bufferoverflow , @mlegnew , @flphrrr

> There is a One Drive gnome shell extension for this project here and it seems not maintained.

Unfortunately you will need to either fork that and maintain it yourself, or ask the developer to maintain it.

> * adding that to the contrib folder
> * maybe publish along with OneDrive

I have no desire to add to the contrib folder code that is already not maintained, nor do I have the desire to bring in something that is less than complete and having to then start developing it, maintaining that on top of the client.

Looking at what this shell extension does - I guess you have missed this: https://github.com/abraunegg/onedrive/wiki/External-Enhancements-to-the-OneDrive-Linux-Client

With this is https://github.com/DanielBorgesOliveira/onedrive_tray - which covers off already some of what this shell extension is doing, and is maintained by @DanielBorgesOliveira

The other option is what @SairusCZ is working on - see https://github.com/abraunegg/onedrive/issues/1668 for details.

**Comment by flphrrr** [comment]
Thanks @abraunegg we'll take a look on the Onedrive_tray maintained extension.

Thanks again,
