### ISSUE TITLE
Sync only the top folder.

### ISSUE THREAD

**Issue by hangnoh** [abraunegg/onedrive#183]
### Bug Report Details ###
**Describe the bug**

Hi, thanks for your effort, first of all.  I used to use the skilion version of onedrive, and found this place recently since the skilion onedrive eats up one of my CPUs 100%.  The problem was solved after installing "abraunegg" version, but it only syncs the top folder (i.e. ~/OneDrive); it does not recursively sync the folders below. It does sync very well for the OneDrive folder, but not the folders inside of the folder.

**Application and Operating System Details:**
- OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
- Are you using a headless system (no gui) or with a gui installed?
- Application version: Output of `onedrive --version`
- OneDrive Account Type
- DMD or LDC compiler version `dmd --version` or `ldmd2 --version`

I am using Ubuntu 18.04.1 LTS with the GUI.
Linux 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
onedrive v2.1.2-6-g3a4c71d
dmd-2.082.0
OneDrive account type
Office365 personal

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```
onedrive --synchronize --verbose
Loading config ...
Using Config Dir: /home/hangnoh/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/hangnoh/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: #
Default Root ID: #
Remaining Free Space: 802427466811
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID:#
Uploading differences of .
Processing root
The directory has not changed
Processing Documents
The directory has not changed
Processing scRNA-Seq
The directory has not changed
Processing Networks_to_update
The directory has not changed
Processing Papers to read
The directory has not changed
Processing Prediction
The directory has not changed
Processing bloomington_stock_list.txt
The file has not changed
Processing X_Chromosome_Lamin
The directory has not changed
Uploading new items of .
Applying changes of Path ID:#

```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See https://guides.github.com/features/mastering-markdown/ for more details.

Application Log Output:
```
2018-Sep-24 21:54:36.5916451 Initializing the Synchronization Engine ...
2018-Sep-24 21:54:37.6193261 Initializing monitor ...
2018-Sep-24 21:54:37.6194251 OneDrive monitor interval (seconds): 45
2018-Sep-24 21:55:22.9240707 Syncing changes from OneDrive ...
2018-Sep-24 21:56:10.0984963 Syncing changes from OneDrive ...
2018-Sep-24 21:56:55.6561339 Syncing changes from OneDrive ...
2018-Sep-24 21:57:41.3452402 Syncing changes from OneDrive ...
2018-Sep-24 21:58:26.9307677 Syncing changes from OneDrive ...
2018-Sep-24 21:59:12.4702786 Syncing changes from OneDrive ...
2018-Sep-24 21:59:57.9602257 Syncing changes from OneDrive ...
2018-Sep-24 22:00:43.5347273 Syncing changes from OneDrive ...
2018-Sep-24 22:01:29.2603047 Syncing changes from OneDrive ...
2018-Sep-24 22:02:14.9982404 Syncing changes from OneDrive ...
2018-Sep-24 22:03:00.5293659 Syncing changes from OneDrive ...
2018-Sep-24 22:03:46.1721448 Syncing changes from OneDrive ...
2018-Sep-24 22:04:31.6737138 Syncing changes from OneDrive ...
2018-Sep-24 22:05:17.2421244 Syncing changes from OneDrive ...
2018-Sep-24 22:06:04.0618924 Syncing changes from OneDrive ...
2018-Sep-24 22:06:50.0850753 Syncing changes from OneDrive ...
2018-Sep-24 22:07:36.2885243 Syncing changes from OneDrive ...
2018-Sep-24 22:08:22.9787121 Syncing changes from OneDrive ...
2018-Sep-24 22:09:09.2973671 Syncing changes from OneDrive ...
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
- [v ] Detailed description
- [n/a ] Reproduction steps (if applicable)
- [ v] Verbose Log Output

**Comment by abraunegg** [comment]
Are you running this as a normal user (non root) or as a root user? Your 2nd log file extract shows that the log is coming from monitor mode - hence the question.

Attempting to replicate this issue atm.

**Comment by abraunegg** [comment]
Unable to replicate when running manually:
```
user@user-virtual-machine-x64:~/OneDrive$ onedrive --synchronize --verbose
Loading config ...
Using Config Dir: /home/user/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/user/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: <redacted>
Delta link expired, re-syncing...
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
OneDrive Client requested to create remote path: ./test
The requested directory to create was not found on OneDrive - creating remote directory: ./test
Successfully created the remote directory ./test on OneDrive
Uploading file ./test/file1 ... done.
Remaining free space: 5368709120
OneDrive Client requested to create remote path: ./test/dir2
The requested directory to create was not found on OneDrive - creating remote directory: ./test/dir2
Successfully created the remote directory ./test/dir2 on OneDrive
Uploading file ./test/dir2/file3 ... done.
Remaining free space: 5368709120
OneDrive Client requested to create remote path: ./test/dir1
The requested directory to create was not found on OneDrive - creating remote directory: ./test/dir1
Successfully created the remote directory ./test/dir1 on OneDrive
Uploading file ./test/dir1/file2 ... done.
Remaining free space: 5368709120
OneDrive Client requested to create remote path: ./test2
The requested directory to create was not found on OneDrive - creating remote directory: ./test2
Successfully created the remote directory ./test2 on OneDrive
Uploading file ./test2/file4 ... done.
Remaining free space: 5368709120
Applying changes of Path ID: <redacted>
```

Running manually with a larger set of data & will test via monitor mode

**Comment by abraunegg** [comment]
Unable to replicate as a normal user running using monitor mode - sub folders are uploaded / monitored without issue.

**Comment by abraunegg** [comment]
@hangnoh 
I would suggest here that you remove all the `items.sqlite3` files from your `~/.config/onedrive` folder for your user and attempt to resync as I cannot replicate your issue.

**Comment by hangnoh** [comment]
Deleting sqlite3 works!  thank you!

**Comment by evandroamaro** [comment]
Hi everyone.
I'm having the same issue. Only the 2 top level directories were created, but no content was downloaded.
Deleting sqlite3 didn't work for me.
Should I post here or open a new topic?

**Comment by abraunegg** [comment]
@evandroamaro 
Please create a new case and revalidate with v2.2.4 please. Please also provide verbose logging for the issue.
