### ISSUE TITLE
Unable to sync business shared folder

### ISSUE THREAD

**Issue by iMonZ** [abraunegg/onedrive#1839]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a` Ubuntu 21.10
*   Are you using a headless system (no gui) or with a gui installed? nogui
*   OneDrive Account Type Azure AD
*   Did you build from source or install from a package? Package
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
*   OneDrive Application Version: Output of `onedrive --version` onedrive v2.4.10-1

*   OneDrive Application Configuration: Output of `onedrive --display-config`
onedrive version                       = v2.4.10-1
Config path                            = /home/mvg/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/mvg/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = true
business_shared_folders contents:
14 Third Party Risk Assessments

*   Provide the version of curl you are using: Output of `curl --version`
* curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 libidn2/2.3.1 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09

*   Is your configured 'sync_dir' a local directory or a network mount point?
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f`  ext4
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same 
* 

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
Finished this tutorial: https://github.com/abraunegg/onedrive/blob/master/docs/BusinessSharedFolders.md

**Complete Verbose Log Output**
```
std.json.JSONException@std/json.d(627): Key not found: remaining
----------------
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x7f8b35288db6]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x7f8b352e2636]
??:? [0x5592ad87cc5a]
??:? [0x5592ad87c32c]
??:? [0x5592ad8c41e0]
??:? [0x5592ad8bc47e]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7f8b34ff6b9b]
??:? _d_run_main2 [0x7f8b34ff69b7]
??:? _d_run_main [0x7f8b34ff680d]
??:? [0x7f8b34c28fcf]
??:? __libc_start_main [0x7f8b34c2907c]
??:? [0x5592ad8686ad]
std.net.curl.CurlException@std/net/curl.d(4402): A libcurl function was given a bad argument on handle null
----------------
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x7f8b3528905c]
??:? void std.net.curl.HTTP.clearRequestHeaders() [0x7f8b352f014f]
??:? [0x5592ad8b628f]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7f8b34ff6b9b]
??:? _d_run_main2 [0x7f8b34ff69b7]
??:? _d_run_main [0x7f8b34ff680d]
??:? [0x7f8b34c28fcf]
??:? __libc_start_main [0x7f8b34c2907c]
??:? [0x5592ad8686ad]
```

### Bug Report Checklist ###
*   [] Detailed description
*   [] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

Is it possible that I send the log files with private chat since it contains sensitive information.
Still thanks for this tool

So syncing my regular OneDrive folder works fine but the Business shared folder arent working

**Comment by abraunegg** [comment]
@iMonZ 
> onedrive v2.4.10-1

This is your issue. You have installed the client from the Ubuntu Universe which is not supported. Please install the correct client version by following the correct installation instructions.

**Comment by iMonZ** [comment]
> @iMonZ
> 
> > onedrive v2.4.10-1
> 
> This is your issue. You have installed the client from the Ubuntu Universe which is not supported. Please install the correct client version by following the correct installation instructions.

I tried that.
This broke my whole operating system with dependencies that uninstalled my desktop environment.
Is it possible to create a flatpak or Snapcraft this would resolve all the problem?

**Comment by abraunegg** [comment]
> I tried that.
> This broke my whole operating system with dependencies that uninstalled my desktop environment.

You followed the incorrect installation instructions then.

Please follow the *correct* instructions for installing on Ubuntu.

Please read the top section of https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md *very* carefully and then read https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md *very* carefully. 

> Is it possible to create a flatpak or Snapcraft this would resolve all the problem?

No it wont.
