### ISSUE TITLE
Can I choose difference directory for local vs Onedrive

### ISSUE THREAD

**Issue by Kalay1995** [abraunegg/onedrive#184]
For example, on One drive, I have 2 folder: PC, Laptop
I want to sync Home of my PC to PC folder on Onedrive, and sync Home of my Laptop to Laptop folder on Onedrive.

**Comment by abraunegg** [comment]
The easiest way to do this would be to use symbolic links

EG - Laptop

/OneDrive/Home is a symbolic link to your laptop home

then run:

`onedrive --synchronize --syncdir /OneDrive --single-directory Home`

On your PC

/OneDrive/PC is a symbolic link to your PC Folder

Then run:

`onedrive --synchronize --syncdir /OneDrive --single-directory PC`

This should upload ONLY the contents of the Home & PC directories to OneDrive, but on OneDrive you would see both Home & PC folders.

Please test and report back as this 'should' be a workable solution.

**Comment by Kalay1995** [comment]
> The easiest way to do this would be to use symbolic links
> 
> EG - Laptop
> 
> /OneDrive/Home is a symbolic link to your laptop home
> 
> then run:
> 
> `onedrive --synchronize --syncdir /OneDrive --single-directory Home`
> 
> On your PC
> 
> /OneDrive/PC is a symbolic link to your PC Folder
> 
> Then run:
> 
> `onedrive --synchronize --syncdir /OneDrive --single-directory PC`
> 
> This should upload ONLY the contents of the Home & PC directories to OneDrive, but on OneDrive you would see both Home & PC folders.
> 
> Please test and report back as this 'should' be a workable solution.

Sorry, I may not have made it clear.
For example, I have a local directory **~/.vim**(my local OneDrive folder is **~/OneDrive**), and I want to sync this folder **~/.vim** to OneDrive remote folder **ubuntu/.vim**,what should I do?

**Comment by abraunegg** [comment]
That is not supported - sorry

**Comment by Kalay1995** [comment]
> That is not supported - sorry

I tested, that is also a wonderful way. Thank you.
