### ISSUE TITLE
Bug: Onedrive creating huge syslog file?

### ISSUE THREAD

**Issue by oeah2** [abraunegg/onedrive#1843]
Basically the title. When the authentification is outdated, onedrive leads to an huge sysfile. Or at least I assume it is onedrive. When I restartet the system, onedrive sent me the same error message several times. 

The sysfile is basically filled with this error:
`Feb 16 11:18:30 xxx-Lenovo xdg-desktop-portal[10419]: [10419:0216/111830.033269:ERROR:address_tracker_linux.cc(355)] Failed to recv from netlink socket: Permission denied (13)`

**Comment by abraunegg** [comment]
@oeah2 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

This should have been opened up as a discussion.
