### ISSUE TITLE
Transfer speed in download/upload progress bar

### ISSUE THREAD

**Issue by hypersonicdk** [abraunegg/onedrive#185]
When file is uploading or downloading, I would like some network transfer information displayed by the progress bar

Perhaps with the use of -v it should show a speed by ETA 

Uploading  10%  |oooo                                              |  ETA 00:10:00  | Tx: 10 Mb/s

and maybe take 10 second averages, or what every you use 
It must be used in the ETA calculation any way?

Thanks
Sam

**Comment by abraunegg** [comment]
> It must be used in the ETA calculation any way?

The progress bar is actually not very 'intuitive' in this way. The progress bar is called based on the number of 'iterations' (file parts as defined by fragmentSize) that the file will have. Example:

* 100MB file, will have 10 iterations, based on a 10MB fragmentSize

What this will do then is, when the start of the upload occurs, it records the start time, and the bad is outputted based on the elapsed time between each iteration to calculate ETA. When each file part is uploaded, the bar increments with new elapsed time details.

Happy for you to look at implementing this and submit a PR, but for now I suggest that you look at using something like 'nethogs' to look at processes / upload / download traffic per second
