### ISSUE TITLE
--resync not working

### ISSUE THREAD

**Issue by deklesen** [abraunegg/onedrive#186]
If i type "onedrive --resync" the program says "--synchronize or --monitor missing from your command options or use --help for further assistance"

**Comment by abraunegg** [comment]
@deklesen 
What the `--resync` parameter does is it essentially removes the local database.

In order to use the `--resync` parameter you need to use it with either `--synchronize` or `--monitor` in the command - you cant just use it on it's own.

**Comment by deklesen** [comment]
Thank you for the answer. I should mention that I tried the command because the readme says under the sync_dir section that one should issue "onedrive --resync".

**Comment by abraunegg** [comment]
Thanks for the feedback. Updated the documentation to clarify how to use that switch when changing defaults.
