### ISSUE TITLE
Large download sync kills app

### ISSUE THREAD

**Issue by brendan-pike** [abraunegg/onedrive#1870]
```
$ onedrive --version
onedrive v2.4.15-1~np2
```
Downloading a large folder set of around 8GB with this command, 
`onedrive --force-http-2 --synchronize --download-only --verbose --single-directory 'My files'`

It downloads for awhile, eventually gets the "ERROR: Query of OneDrive for file details failed" and then does:
```
Thread sleeping due to 'HTTP request returned status code 429' - The request has been throttled
Sleeping for 224 seconds
Processing 247 OneDrive items to ensure consistent local state
```
But then always dies with 
```
ERROR: Query of OneDrive for file details failed
Thread sleeping due to 'HTTP request returned status code 429' - The request has been throttled
Sleeping for 30 seconds

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 429 ()
  Error Reason:     The request has been throttled
  Error Timestamp:  2022-03-09T05:39:06
  API Request ID:   ecf64df7-5af7-400b-bcfe-1ead04e139d5
  Calling Function: applyDifferences()
```
Ubuntu 20.04.4 LTS

- OneDrive Account Type: personal but its a shared folder I'm downloading
- used deb package
```
onedrive --display-config
onedrive version                       = v2.4.15-1~np2
Config path                            = /home/bedlore/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/bedlore/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false

```
curl --version
curl 7.68.0 

lsblk -f /dev/sdc1
NAME FSTYPE LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
sdc1 ext4         d8acc212-e181-49f0-8a91-3b069cb95d97  458.7G    46% /

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Let me know what other info may help.

Cheers

**Comment by abraunegg** [comment]
@brendan-pike 
> v2.4.15-1~np2

This is your problem. Upgrade your client as the Ubuntu package is missing the following critical fixes:
* https://github.com/abraunegg/onedrive/pull/1789
* https://github.com/abraunegg/onedrive/pull/1828

> But then always dies with ..

The client is not 'dying' here .. it is thread sleeping.

> `--force-http-2`

Do not use this option - use HTTP 1.1 which is the application default as the OneDrive service itself does not fully support HTTP2 requests.

Please:

1. Uninstall the package
2. Ensure you remove all package references including the defunct systemd reference as per https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md#known-issues-with-installing-from-the-above-packages
3. Build and install the client from source
4. Retest and do not use `--force-http-2`

**Comment by brendan-pike** [comment]
Thank you, I apt-get removed it, (I didn't purge) then removed the systemd reference.   I built from source but the same issue persists, and I did not use --force-http-2

onedrive --version
onedrive v2.4.15-28-gc4a7c1e

**Comment by abraunegg** [comment]
@brendan-pike 
Please can you do the following:

1. Provide a full verbose log (running the application with `--verbose`) showing the error you are experiencing.
2. Provide a full verbose debug log (running the application with `--verbose --verbose`) showing the error you are experiencing.

**Comment by brendan-pike** [comment]
Thanks, the error remains the same, 
```
*snip*...... 210167_006.docx ... ERROR: Query of OneDrive for file details failed
ERROR: Query of OneDrive for file details failed
Thread sleeping due to 'HTTP request returned status code 429' - The request has been throttled
Sleeping for 42 seconds

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 429 ()
  Error Reason:     The request has been throttled
  Error Timestamp:  2022-03-09T08:42:49
  API Request ID:   01376cf9-30e6-430e-a292-371c3f11f978
  Calling Function: applyDifferences()
```
How ever this second run is still going strong after maybe 30 mins which it would never of done before. So maybe is good, if it fails again I'll use --verbose --verbose, either way I'll report back.  Thanks

**Comment by abraunegg** [comment]
@brendan-pike 
> Thanks, the error remains the same,

Is the application 'exiting' or crashing ... or is it simply sleeping for 42 seconds and then continuing ?

What is your actual experience here?

I need the FULL logs as well - not just a small extract like you have been giving.

**Comment by abraunegg** [comment]
@brendan-pike
Any update here in regards to the information requested?

**Comment by brendan-pike** [comment]
Hi, when I used double verbose it managed to complete the sync as it was probably a good way along.  Perhaps I can move local copy and see if I can get it to fail again.

**Comment by brendan-pike** [comment]
Okay, I discovered moving the files themselves doesn't force a full sync/download, how can I do that?

**Comment by abraunegg** [comment]
@brendan-pike 
> Hi, when I used double verbose it managed to complete the sync as it was probably a good way along. Perhaps I can move local copy and see if I can get it to fail again.

Quite possible your application upgrade with the 2 fixes I mentioned was the actual fix.

As v2.4.16 is released, you can revert to using the OpenSuSE Build Service repository as per https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md

> Okay, I discovered moving the files themselves doesn't force a full sync/download, how can I do that?

As this issue is resolved, this ticket will be closed. Please open a discussion.
