### ISSUE TITLE
Feature Request: Docker run with root

### ISSUE THREAD

**Issue by zanjie1999** [abraunegg/onedrive#1899]
### Is your feature request related to a problem? Please describe.

ROOT level privileges prohibited!

### Describe the solution you'd like

run with uid=0 gid=0 (root user)

### Describe alternatives you've considered

```
docker run -d --restart=unless-stopped --name onedrive \
    -v /opt/apps/onedrive:/onedrive/conf \
    -v /data/OneDrive:/onedrive/data \
    -e ONEDRIVE_UID=0 \
    -e ONEDRIVE_GID=0 \
    -e ONEDRIVE_RESYNC=1 \
    driveone/onedrive:latest
docker cp onedrive:/entrypoint.sh ./
```
edit `entrypoint.sh` and delete line `grep -qv root <( groups "${oduser}" ) || { echo 'ROOT level privileges prohibited!'; exit 1; }`
```
docker cp -f entrypoint.sh onedrive:/entrypoint.sh
docker start onedrive
```
now onedrive sync will run fine with root
(test with Openwrt)

**Comment by abraunegg** [comment]
@zanjie1999 
No .. you should not be running Docker container as root .... if this is your solution, you need to rethink your security. Sorry.
