### ISSUE TITLE
Onedrive Bussiness Authorization Problem

### ISSUE THREAD

**Issue by tugyan** [abraunegg/onedrive#19]
Hi. When I try to authorize my account using the link given by client, response link turns out like this:

`https://login.microsoftonline.com/common/oauth2/nativeclient?error=invalid_client&error_description=AADSTS65005%3a+Using+application+%27OneDrive+Free+Client%27+is+currently+not+supported+for+your+organization+ee.bilkent.edu.tr+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+ee.bilkent.edu.tr+before+the+application+OneDrive+Free+Client+can+be+provisioned.+Request+ID%3a+2eb630bd-a2b0-4e8a-9bcd-059209e32ab1%2c+Timestamp%3a+06%2f12%2f2018+21%3a12%3a27%0d%0aTrace+ID%3a+5f2cf98a-1df6-460f-97ce-c50398de2d00%0d%0aCorrelation+ID%3a+a99ac265-08e2-47fe-b171-80a332351c92%0d%0aTimestamp%3a+2018-06-12+21%3a12%3a27Z`

I understand it has to do with the domain I use (which is my universities domain btw.). Yet, is there a workaround to this problem?

**Comment by abraunegg** [comment]
The work around is listed in the error response from OneDrive - have a chat with your Administrator to resolve

**Comment by tugyan** [comment]
Well, I am not sure if there is an administrator in first place, but it seems there is nothing you can do. :)
