### ISSUE TITLE
not uploading any files!!

### ISSUE THREAD

**Issue by kurokirasama** [abraunegg/onedrive#190]
### Bug Report Details ###
**Describe the bug**
I got this on log:
```
Skipping uploading this new file as parent path is not in the database:
```
It seems that subdirectories are created but files are not uploaded.

**Application and Operating System Details:**
- OS: Linux lgomezOpenWorld 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 18.04 with GNOME Shell 3.28.3
- Application version: onedrive 2.1.3-2-gd1d3c8a
- Onedrive Bussiness account
- DMD64 D Compiler v2.080.1
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright

**To Reproduce**
directory with subdirectories with files and run `onedrive --synchronize --monitor`

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```
onedrive --synchronize --verbose <any of your other needed options>
```
[logonedrive.txt](https://github.com/abraunegg/onedrive/files/2457796/logonedrive.txt)

### Bug Report Checklist ###
- [ ] Detailed description
- [ ] Reproduction steps (if applicable)
- [ ] Verbose Log Output

**Comment by kurokirasama** [comment]
where is the answer?

**Comment by abraunegg** [comment]
@kurokirasama 
The best thing to do here is remove any `items.sqlite3` file from your home directory.

The 'skilion' codebase has massive database issues, and unfortunately what 'should' happen is when upgrading to my version, the DB version bump should erase the database & start from scratch again.

**Process:**
1. stop any service / onedrive process from running
2. remove any `items.sqlite3` file from your home directory
3. restart service or application

**Comment by abraunegg** [comment]
@kurokirasama 
Did the above resolve your issue?

**Comment by kurokirasama** [comment]
hi,

i don't have any sqlite3 files in my home:
[ls -ash1X](https://yadi.sk/i/XjkSJDR5xzkDkQ)

**Comment by abraunegg** [comment]
@kurokirasama 
The local database files are in `~/.config/onedrive/`

**Comment by kurokirasama** [comment]
Ok, now it's OK. Thanks.
