### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by MADx00** [abraunegg/onedrive#1913]
### Describe the bug

when following the instructions of deploying the docker version, everything went fine. But when adding "config" file the sync stop, and "onedrive --display-config" (within the docker) show no change in config.

### Operating System Details

```shell
Linux * 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

### Client Installation Method

From 3rd Party Source (PPA, OpenSuSE Build Service etc)

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

onedrive v2.4.13-7-g2b32c3a

### What is your OneDrive Application Configuration

```shell
my new config file is:

# Configuration for OneDrive Linux Client
# This file contains the list of supported configuration fields
# with their default values.
# All values need to be enclosed in quotes
# When changing a config option below, remove the '#' from the start of the line
# For explanations of all config options below see docs/USAGE.md or the man page.
#
# sync_dir = "~/OneDrive/"
# skip_file = "~*|.~*|*.tmp"
# monitor_interval = "300"
# skip_dir = ""
# log_dir = "/var/log/onedrive/"
# drive_id = ""
 upload_only = "true"
# check_nomount = "false"
# check_nosync = "false"
# download_only = "false"
# disable_notifications = "false"
# disable_upload_validation = "false"
# enable_logging = "false"
# force_http_2 = "false"
# local_first = "false"
 no_remote_delete = "true"
# skip_symlinks = "false"
# debug_https = "false"
# skip_dotfiles = "false"
# dry_run = "false"
# min_notify_changes = "5"
# monitor_log_frequency = "5"
# monitor_fullscan_frequency = "10"
# sync_root_files = "false"
# classify_as_big_delete = "1000"
# user_agent = ""
 remove_source_files = "true"
# skip_dir_strict_match = "false"
# application_id = ""
 resync = "true"
# resync_auth = "false"
# bypass_data_preservation = "false"
# azure_ad_endpoint = ""
# azure_tenant_id = "common"
# sync_business_shared_folders = "false"
# sync_dir_permissions = "700"
# sync_file_permissions = "600"
# rate_limit = "131072"
# operation_timeout = "3600"
# webhook_enabled = "false"
# webhook_public_url = ""
# webhook_listening_host = ""
# webhook_listening_port = "8888"
# webhook_expiration_interval = "86400"
# webhook_renewal_interval = "43200"
```

### What is your 'curl' version

```shell
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
I am using docker version (driveone/onedrive:latest)
```

### What are all your local file system partition types

```shell
I am using docker version (driveone/onedrive:latest)
```

### How do you use 'onedrive'

I am using one drive personally 

### Steps to reproduce the behaviour

1- Run docker version using "docker run" this is the command:
`docker run -it --name onedriveTest -v "$(pwd)/config-onedrive:/onedrive/conf" -v "$(pwd)/data-onedrive:/onedrive/data" -e "ONEDRIVE_UID=1000" -e "ONEDRIVE_GID=1000" driveone/onedrive:latest`

2- stop/kill container 
3- remove the contaier (I want to use docker compose later), and this the command:
`docker rm onedriveTest`

4- run docker compose with the same configuration, this is the file:
`version: '3.3'
services:
    onedrive:
        container_name: onedriveTest
        volumes:
            - './config-onedrive:/onedrive/conf'
            - './data-onedrive:/onedrive/data'
        environment:
            - ONEDRIVE_UID=1000
            - ONEDRIVE_GID=1000
        image: 'driveone/onedrive:latest'
`

5- copy my new "config" file to "config-onedrive" folder, and below is my main changes in "config":
`upload_only = "true"
 no_remote_delete = "true"
 remove_source_files = "true"
 resync = "true"`

### Complete Verbose Log Output

```shell
if there is a need for this i can share it later
```

**Comment by abraunegg** [comment]
@MADx00 
There are a number of issues here:
1. I am using docker version (driveone/onedrive:latest) .... this means you are using an obsolete client, that is no longer updated due to the change in Docker policies to integrate to GitHub. You must rebuild your Docker container locally - do not pull it from Docker Hub. Please rebuild your Docker container locally following https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md#build-instructions
2. Do not add `resync = "true"` to your configuration file. Use the Docker environment variable to control a resync as per https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md#environment-variables

**Comment by MADx00** [comment]
Thanks @abraunegg, after following your suggestion and rebuilding my own onedrive image, everything went fine

**Comment by abraunegg** [comment]
@votdev 
https://www.zdnet.com/article/docker-changes-its-subscription-plans-usage-rules-and-product-line/

Essentially an opensource entity now has to buy a business subscription to push/build Docker images to DockerHub

I have tried to get this to work by building locally and just pushing the image to DockerHub - but this is also failing because the DockerHub is an organisation - ergo - not a single account ... 

So ... between a rock and a hard place.
