### ISSUE TITLE
Bug: Local files not deleted in download_only mode

### ISSUE THREAD

**Issue by JessiBaughman** [abraunegg/onedrive#1914]
### Describe the bug

When using download_only="true", local files are not deleted when removed from the remote drive.

### Operating System Details

```shell
uname -a
Linux m300-119 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Tue Mar 8 12:56:54 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/redhat-release
Red Hat Enterprise Linux release 8.5 (Ootpa)
```

### Client Installation Method

From Source

### OneDrive Account Type

SharePoint

### What is your OneDrive Application Version

onedrive v2.4.16-3-gf26f03b

### What is your OneDrive Application Configuration

```shell
Configuration file successfully loaded
config file has been updated, checking if --resync needed
onedrive version                       = v2.4.16-3-gf26f03b
Config path                            = /root/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = true
Config option 'sync_dir'               = /mnt/sharepoint
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = true
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'drive_id'               = b!d<withheld>
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
!mrc/Calendar
!mrc/notebook
!mrc/tutorials
!mrc/mrc_service/archive
!mrc/mrc_service/aArchive
General
mrc
mrc_data
Business Shared Folders configured     = false
```

### What is your 'curl' version

```shell
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.6 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.2.0) libssh/0.9.4/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=3910888k,nr_inodes=977722,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
none on /sys/kernel/tracing type tracefs (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/mapper/rhel-root on / type xfs (rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)
mqueue on /dev/mqueue type mqueue (rw,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=37,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=716)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda2 on /boot type xfs (rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)
/dev/mapper/rhel-home on /home type xfs (rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)
/dev/sda1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro)
/dev/sdb1 on /mnt/sharepoint type ext4 (rw,relatime)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
tmpfs on /run/user/502 type tmpfs (rw,nosuid,nodev,relatime,size=788012k,mode=700,uid=502,gid=30)
gvfsd-fuse on /run/user/502/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=502,group_id=30)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=788012k,mode=700)
gvfsd-fuse on /run/user/0/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
xrdp-chansrv on /root/thinclient_drives type fuse.xrdp-chansrv (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
```

### What are all your local file system partition types

```shell
NAME          FSTYPE      LABEL      UUID                                   MOUNTPOINT
sda
├─sda1        vfat                   F0E5-E1FF                              /boot/efi
├─sda2        xfs                    8fc37d23-6a6c-4b74-a597-3c92b11768da   /boot
└─sda3        LVM2_member            xpkVNO-hZA0-MaQM-gGBM-Wa6a-3J0p-eGPp0c
  ├─rhel-root xfs                    e55db45b-de67-44cc-b2b6-9d09f9ff10c1   /
  ├─rhel-swap swap                   ab39aea3-008a-464d-9cf6-560b3af469e3   [SWAP]
  └─rhel-home xfs                    364e7447-767a-4424-99a0-d58d6f8649bc   /home
sdb
└─sdb1        ext4        sharepoint 34e5a5c9-bf9a-470b-9947-20e413000a8b   /mnt/sharepoint
sr0
```

### How do you use 'onedrive'

Files in SharePoint are managed online and from Windows 10 workstations. The files on the remote SharePoint server are then mirrored one-way (download_only) to the local RHEL 8.5 workstation. 

### Steps to reproduce the behaviour

onedrive --synchronize -v

When ran, it will not mention nor delete any local files no longer present in SharePoint. Resyncing the database with --resync doesn't remove the local files either.

### Complete Verbose Log Output

```shell
Using 'user' Config Dir: /root/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Checking Application Version ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /mnt/sharepoint
Application version: v2.4.16-3-gf26f03b
Account Type: documentLibrary
Default Drive ID: b!d...
Default Root ID: 01...
Remaining Free Space: 27375922952613
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 016URTSBF6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 27375922952613
```

**Comment by abraunegg** [comment]
@JessiBaughman 
> When using download_only="true", local files are not deleted when removed from the remote drive.

Was the system actually 'in-sync' before the file was deleted online - or, was this a clean sync / first time sync? If the system was already 'in-sync' it should have removed the local file. 

> Resyncing the database with --resync doesn't remove the local files either.

Correct - because the application does not know, due 'download only' that the local files if they are not present online need to be removed - because there is no referential integrity of state (it has been deleted due to use of --resync)

Think of it this way - download only, you are basically downloading your data, keeping an ever increasing local archive of data from online.


Please can you also follow the correct support process and provide a verbose debug log.

**Comment by JessiBaughman** [comment]
> Was the system actually 'in-sync' before the file was deleted online - or, was this a clean sync / first time sync? If the system was already 'in-sync' it should have removed the local file.
Yes to both? It was a first time sync, but the folders were deleted after the first sync had completed.

> it has been deleted due to use of --resync
So I might have made it worse doing that. Is my options at this point manually compare and delete or start over?

> download only, you are basically downloading your data, keeping an ever increasing local archive of data from online.
This is counter to how I understand upload-only to work, given it has a don't delete flag as well. Shouldn't download-only work the same as upload-only, just in different directions?

> Please can you also follow the correct support process and provide a verbose debug log.
That is the verbose output at this point. I just truncated the drive and root id's.

**Comment by JessiBaughman** [comment]
I think you can close this. I tested again by 

1. creating a folder and file online
2. syncing to download it
3. deleting the remote version
4. resyncing

After the sync, the new folder and file were deleted. So I think my issue was running resync. But I had to run it since I updated the exclusion list in sync_list. So I'll make a note to sync before making changes to config or sync_list in the future to avoid this issue.

**Comment by abraunegg** [comment]
@JessiBaughman 
> This is counter to how I understand upload-only to work, given it has a don't delete flag as well. Shouldn't download-only work the same as upload-only, just in different directions?

This is because we are able to query the API if a file exists, or does not exist, or, when we delete it from local & we have record of it being in-sync we know that we need to delete it from the remote side.

Local file systems have no API or capability to know what is correct - so the assumption here is that local files are local for a reason, and, when you are downloading data with download-only you are adding to your local files. It is not going to know what to delete locally, what to keep locally .. its just downloading data ... 

> That is the verbose output at this point. I just truncated the drive and root id's.

That is not a verbose debug log ... you get a verbose debug log via `--verbose --verbose`

**Comment by abraunegg** [comment]
> I think you can close this. I tested again by
> 
> 1. creating a folder and file online
> 2. syncing to download it
> 3. deleting the remote version
> 4. resyncing
> 
> After the sync, the new folder and file were deleted on the local machine. So I think my issue was running resync. But I had to run it since I updated the exclusion list in sync_list. So I'll make a note to sync before making changes to config or sync_list in the future to avoid this issue.

OK .. good to know

Just do not use --resync .... this 'blows' away your local sync state ... just do-not-use-it unless the application tells you to because you changed your configuration

**Comment by JessiBaughman** [comment]
> its just downloading data ...

Ok. I thought it was doing an actual file comparison like rsync. So that makes sense.

**Comment by abraunegg** [comment]
Closing issue
