### ISSUE TITLE
Feature Request: When syncing a folder, there should be a way to excude subfolders of that folder from being synced

### ISSUE THREAD

**Issue by CmdrNorthpaw** [abraunegg/onedrive#1919]
### Is your feature request related to a problem? Please describe.

One of the ways I use OneDrive is to synchronize my code across multiple devices without having to think about Git commits all the time. The problem is that a lot of developer tools create folders and files that should really stay locally. NPM's node_modules folder, for instance, is full of lots of tiny little JavaScript files that take ages to download.

### Describe the solution you'd like

I think the `onedrive` tool should have a feature, a bit like sync_list, where you can define a pattern of file or folder names not to be synced. If `onedrive` detects a folder matching that pattern on the disk it will not upload it to OneDrive, and if such a folder is detected on the remote it will not be downloaded. This applies to every folder and subfolder being synced.

### Describe alternatives you've considered

The only alternative I can think of other than "use another tool" is "bite the bullet and wait ages for small files to download"

**Comment by abraunegg** [comment]
@CmdrNorthpaw 
Please read the documentation - this capability already exists: 
* https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#skip_dir
* https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#how-to-skip-directories-from-syncing
