### ISSUE TITLE
Feature Request: parallel downloads

### ISSUE THREAD

**Issue by pfedan** [abraunegg/onedrive#1922]
### Is your feature request related to a problem? Please describe.

When synchronizing a larger number of files, it can take quite a while to perform a full synchronization, downloading all files one by one.

### Describe the solution you'd like

Add a parameter `--parallel <n>` that allows the user to specify a number of parallel downloads during synchronization.

### Describe alternatives you've considered

none

**Comment by pfedan** [comment]
possibly related to #232

**Comment by abraunegg** [comment]
Closing this feature request
