### ISSUE TITLE
Feature Request: Add Ubuntu 22.04 to OBS Build

### ISSUE THREAD

**Issue by theofficialgman** [abraunegg/onedrive#1933]
### Is your feature request related to a problem? Please describe.

Documentation indicates that ubuntu 22.04 has an OBS build, but it does not. https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/

### Describe the solution you'd like

22.04 has been officially released and many people will be upgrading to it in the coming weeks. Please add this as a build target as soon as possible.

### Describe alternatives you've considered

(alternative it to build from source or install the package from an older ubuntu target)

**Comment by abraunegg** [comment]
@norbusan
Please could you look into this given Ubuntu 22.04 was released on the 21st April 2022?

**Comment by norbusan** [comment]
At the moment, OBS has no build support for Ubuntu 22.04. My guess is that it will come rather soon, but as of 5min ago there wasn't.

I'll check back in a few days.

**Comment by Sutyke** [comment]
OneDrive doesn't work at the moment on Ubuntu 22.04

**Comment by abraunegg** [comment]
@Sutyke 

> OneDrive doesn't work at the moment on Ubuntu 22.04 , any advice how to build the package from the source ?

Just follow the same instructions to build from source as per Ubuntu 20.x until the OpenSuSE Build Service supports Ubuntu 22.04

**Comment by Sutyke** [comment]
To install onedrive to ubuntu 22.04 follow this instructions https://linuxhint.com/install-microsoft-onedrive-ubuntu/

This is older build but works without any problem on 22.04.

**Comment by abraunegg** [comment]
> 

Please do *not* use those instructions. The Ubuntu PPA provides an obsolete and unsupported client version.

Your *only* option at the moment, until OBS supports Ubuntu 22.04 is to build from source following these instructions: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-ubuntu-18x---ubuntu-22x--debian-9---debian-11---x86_64

**Comment by norbusan** [comment]
I am checking every day, but still no signs of Ubuntu 22.04 on OBS ...

**Comment by abraunegg** [comment]
@norbusan 
Have you seen this: https://github.com/openSUSE/open-build-service/issues/12496

From this link: https://github.com/openSUSE/open-build-service/issues/12496#issuecomment-1111911908

> That's already done. It will not be displayed in the distribution list until GA, though.
If you want to build for Ubuntu 22.04 you have to get to the Distributions page and "add from project". There you can enter xUbuntu22 and start building.


Can you see if this is actually the case .. and if so, see if this is a workable item ?

**Comment by norbusan** [comment]
Hmmm, just tried that but couldn't find xUbuntu22, strange.

I'm not in mobile only (long weekend and holiday here), but will check back when I'm back.

**Comment by norbusan** [comment]
Added, builds are mostly finished (aarch64 in process).

**Comment by abraunegg** [comment]
@norbusan 
Awesome :)

**Comment by norbusan** [comment]
New version is already in OBS ;-)
