### ISSUE TITLE
Problems with syncing name changes and deletions

### ISSUE THREAD

**Issue by adrianghc** [abraunegg/onedrive#194]
### Bug Report Details ###
**Describe the bug**
When deleting a file or directory on the local copy, this is not synced up to OneDrive. When renaming a file or directory on the local copy, a new copy is synced up to OneDrive and a copy with the old name is kept. All other scenarios work in both directions, as far as I can tell.

**Application and Operating System Details:**
- Linux stuart 4.9.0-7-armmp-lpae #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) armv7l GNU/Linux
- I'm running a headless client
- The client version is onedrive v2.1.4
- I use a personal Microsoft account for OneDrive
- I compiled with ldc2-1.10.0-linux-armhf

**To Reproduce**
To reproduce, create a new file or folder and sync with _./onedrive --synchronize_. The result is that nothing happens. The console output is simply

> Initializing the Synchronization Engine ...
> Syncing changes from OneDrive …

When renaming an existing file that has already been uploaded to OneDrive, e.g. renaming _test.txt_ to _test2.txt_, _test.txt_ is kept on the server and _test2.txt_ is uploaded additionally. The console output in that case is

> Initializing the Synchronization Engine ...
> Syncing changes from OneDrive ...

**Comment by adrianghc** [comment]
This issue was created in error, my apologies. Pleas refer to #195 instead.

**Comment by abraunegg** [comment]
@adrianghc

Can you advise if you did an upgrade from the skilion version?

I know that this issue manifests itself if you are upgrading and you do not delete the items.* files from your ~/.config/ondrive directory
