### ISSUE TITLE
Feature Request: Sync Shared Libraries without having to authenticate again.

### ISSUE THREAD

**Issue by titusjan** [abraunegg/onedrive#1948]
### Is your feature request related to a problem? Please describe.

I am trying to use to your marvelous program to make a mirror/backup of all the SharePoint Shared Libraries in our organization. I have made a small PowerShell script that returns a list of names of all the Shared Libraries I want to sync, so I've got that part automated.

Now I run into the issue that I cannot make a script to sync a new Shared Library because, according to [the documenation](https://github.com/abraunegg/onedrive/blob/master/docs/advanced-usage.md#4-authenticate-the-client), I need to create a new config file per Shared Library and authenticate again. Creating a new config file is not a problem, but the authentication step can't be automated because you need to enter your password in a web browser.

### Describe the solution you'd like

I'd like to be able to sync a new Shared Library without having to authenticate myself again for each shared library. A one time authentication is fine of course. 

### Describe alternatives you've considered

I can't think of any alternatives. Is the authentication step really necessary? Can you please explain why or why not?

**Comment by abraunegg** [comment]
@titusjan 
This should be a discussion, not a Feature Request
