### ISSUE TITLE
Bug: installing man-pages as 0755 instead of 0644

### ISSUE THREAD

**Issue by brobr** [abraunegg/onedrive#1952]
### Describe the bug

Hi compiling onedrive on Slackware creates man-pages with the wrong permission (0755; i.e. executable); should have been 0644. 

Could this happen by not setting any permissions on the invocation of install here: https://github.com/abraunegg/onedrive/blob/v2.4.17/Makefile.in#L110 ?

Maybe this is intended and not a bug; but has not been seen with any other programs built following the same method.

### Operating System Details

```shell
Linux knotsUL 5.17.4 #1 SMP PREEMPT Wed Apr 20 13:05:51 CDT 2022 x86_64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz GenuineIntel GNU/Linux

Slackware64-current (15.0 -> 15.1)
```

### Client Installation Method

From Source

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

2.4.17

### What is your OneDrive Application Configuration

```shell
na
```

### What is your 'curl' version

```shell
na
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
na
```

### What are all your local file system partition types

```shell
ext4
```

### How do you use 'onedrive'

na

### Steps to reproduce the behaviour

see description; these are the relevant build & install steps
>
>./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --enable-notifications \
  --enable-debug \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --build=$ARCH-slackware-linux
>
>make
make install DESTDIR=$PKG

### Complete Verbose Log Output

```shell
na
```

**Comment by abraunegg** [comment]
@brobr 
Thanks for catching this long standing oversight.

Please can you test the following PR to resolve your issue:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1953/head:pr1953
git checkout pr1953
./configure; make clean; make; sudo make install;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.17-9-g3911b7d` or greater.

I have tested the PR myself - the correct permissions are now used:
```
/usr/bin/install -c -D onedrive /usr/local/bin/onedrive
/usr/bin/install -c -D -m 644 onedrive.1 /usr/local/share/man/man1/onedrive.1
/usr/bin/install -c -D -m 644 contrib/logrotate/onedrive.logrotate /usr/local/etc/logrotate.d/onedrive
mkdir -p /usr/local/share/doc/onedrive
/usr/bin/install -c -D -m 644 README.md config LICENSE CHANGELOG.md docs/Docker.md docs/INSTALL.md docs/SharePoint-Shared-Libraries.md docs/USAGE.md docs/BusinessSharedFolders.md docs/advanced-usage.md /usr/local/share/doc/onedrive
/usr/bin/install -c -d -m 0755 /usr/lib/systemd/user /usr/lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive@.service /usr/lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive.service /usr/lib/systemd/system
```

**Comment by brobr** [comment]
Hi, thanks for the quick response and the PR; it works at  my end ;-)

I tested the PR a bit differently by first creating an archive (attached script)  that then could be tested with the common build script (onedrive.SlackBuild), which created a package with the contents as described in the other attachment.

Last lines are the most relevant ones:
>drwxr-xr-x root/root         0 2022-05-05 22:45 usr/man/
drwxr-xr-x root/root         0 2022-05-05 22:45 usr/man/man1/
-rw-r--r-- root/root      3761 2022-05-05 22:45 usr/man/man1/onedrive.1.gz

BTW I just have been the messenger; @aclemons at slackbuilds.org noticed the mistake and suggested where it could originate from.

[onedrive-v2.4.17.r9.g3911b7-x86_64-1_SBo.txt](https://github.com/abraunegg/onedrive/files/8636252/onedrive-v2.4.17.r9.g3911b7-x86_64-1_SBo.txt)
[get-git-onedrive.sh.txt](https://github.com/abraunegg/onedrive/files/8636254/get-git-onedrive.sh.txt)
