### ISSUE TITLE
Bug: onedrive stays locked if process gets interrupted

### ISSUE THREAD

**Issue by elhennig** [abraunegg/onedrive#1954]
### Describe the bug

Running onedrive puts out:
Configuration file successfully loaded
ERROR: onedrive application is already running - check system process list for active application instances

But there is no process in the system. Is there a lock file somewhere?

### Operating System Details

```shell
Linux, onedrive client Latest build from main
```

### Client Installation Method

From Source

### OneDrive Account Type

Business | Office365

### What is your OneDrive Application Version

onedrive v2.4.17-9-g04c65f9

### What is your OneDrive Application Configuration

```shell
> onedrive --display-config
Configuration file successfully loaded
ERROR: onedrive application is already running - check system process list for active application instances
```

### What is your 'curl' version

```shell
curl --version
curl 7.83.0 (x86_64-suse-linux-gnu) libcurl/7.83.0 OpenSSL/1.1.1d-fips zlib/1.2.11 brotli/1.0.9 zstd/1.4.4 libidn2/2.2.0 libpsl/0.20.1 (+libidn2/2.0.4) libssh/0.8.7/openssl/zlib nghttp2/1.40.0 OpenLDAP/2.4.46
Release-Date: 2022-04-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
/dev/nvme0n1p6 on /boot/grub2/i386-pc type btrfs (rw,noatime,compress=lzo,ssd,space_cache,subvolid=267,subvol=/@/boot/grub2/i386-pc)
/dev/nvme0n1p6 on /boot/grub2/x86_64-efi type btrfs (rw,noatime,compress=lzo,ssd,space_cache,subvolid=266,subvol=/@/boot/grub2/x86_64-efi)
/dev/nvme0n1p6 on /data type btrfs (rw,noatime,compress=lzo,ssd,space_cache,subvolid=257,subvol=/@/data)
/dev/nvme0n1p6 on /home type btrfs (rw,noatime,compress=lzo,ssd,space_cache,subvolid=265,subvol=/@/home)
/dev/nvme0n1p6 on /opt type btrfs (rw,noatime,compress=lzo,ssd,space_cache,subvolid=264,subvol=/@/opt)
/dev/nvme0n1p6 on /root type btrfs (rw,noatime,compress=lzo,ssd,space_cache,subvolid=263,subvol=/@/root)
/dev/nvme0n1p6 on /srv type btrfs (rw,noatime,compress=lzo,ssd,space_cache,subvolid=262,subvol=/@/srv)
/dev/nvme0n1p6 on /tmp type btrfs (rw,noatime,compress=lzo,ssd,space_cache,subvolid=261,subvol=/@/tmp)
/dev/nvme0n1p6 on /usr/local type btrfs (rw,noatime,compress=lzo,ssd,space_cache,subvolid=260,subvol=/@/usr/local)
/dev/nvme0n1p6 on /var type btrfs (rw,noatime,compress=lzo,ssd,space_cache,subvolid=259,subvol=/@/var)
/dev/nvme0n1p6 on /vbox type btrfs (rw,noatime,compress=lzo,ssd,space_cache,subvolid=258,subvol=/@/vbox)
/dev/nvme0n1p3 on /win type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096)
/dev/nvme0n1p5 on /boot/efi type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
```

### What are all your local file system partition types

```shell
nvme0n1                                                                                  
├─nvme0n1p1 vfat      FAT32 SYSTEM   AE09-07F4                                           
├─nvme0n1p2                                                                              
├─nvme0n1p3 ntfs                     9C70177E70175E78                       21,1G    79% /win
├─nvme0n1p4 swap      1              7e4ee8b0-248b-4d0b-9621-91b8ee7dc6e7                [SWAP]
├─nvme0n1p5 vfat      FAT16          E25D-570F                             250,7M     2% /boot/efi
└─nvme0n1p6 btrfs                    6b35d1f2-a6b4-4ee8-a3f7-3fe82c4640d4  180,8G    78% /vbox
```

### How do you use 'onedrive'

Config contains a personal onedrive account on O365 and worked well until yesterday. The same user can still access and sync sharepoint on the same service  (O365 cloud)

### Steps to reproduce the behaviour

Run onedrive client

### Complete Verbose Log Output

```shell
> onedrive --synchronize --verbose
Using 'user' Config Dir: /home/e8864/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
ERROR: onedrive application is already running - check system process list for active application instances
 - Use 'sudo ps aufxw | grep onedrive' to potentially determine acive running process
```

### Other Log Information or Details

```shell
sudo ps aufxw | grep onedrive
e8864      704  0.0  0.0  10260   784 pts/4    S+   14:45   0:00      \_ grep --color=auto onedrive
```

**Comment by elhennig** [comment]
Is there any lock file? and if yes, where is this stored?

**Comment by elhennig** [comment]
The behavior seems to be caused by interrupting onedrive. How can I get rid of such a lock?

**Comment by tonovcp** [comment]
Hi, same here. Waiting for a solution.

**Comment by elhennig** [comment]
I found a workaround by removing the items.sqlite* files.. Of course then you have to perform a resync everytime, which is obviously not really good.

**Comment by tonovcp** [comment]
> I found a workaround by removing the items.sqlite* files.. Of course then you have to perform a resync everytime, which is obviously not really good.

Thank, you. Do you have to do it every reboot?

**Comment by elhennig** [comment]
No, it only happens when onedrive terminates either by internal fault of Ctrl-C

**Comment by j188482367** [comment]
我也是阿 刚重启 就弹一样的 ERROR: onedrive application is already running - check system process list for active application instances

**Comment by elhennig** [comment]
Maybe you could write in English, so everyone can understand your post

**Comment by j188482367** [comment]
The same situation to me, just after reboot then running command "onedrive", I get ERROR: onedrive application is already running - check system process list for active application instances
It was compiled and installed on May 6th today. onedrive is not added to the system service, the last normal command is --monitor, and then interrupted with ctrl-c

**Comment by elhennig** [comment]
I do not use --monitor but call onedrive manually. But if I interrupt the process, I get the error as you also described it

**Comment by abraunegg** [comment]
@elhennig , @tonovcp , @j188482367 

Thanks for reporting this. This is a side consequence of PR #1944 and your actions of terminating the application via CTRL-C - which, is not also cleaning up various files as it should be when CTRL-C is being used.

Looking into a more robust resolution at the moment.

**Comment by abraunegg** [comment]
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1955/head:pr1955
git checkout pr1955
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.17-10-g0f8042e` or greater.

**Example - 1st Application Instance:**
```
Configuration file successfully loaded
Notification (dbus) server not available, disabling

Unable to write activity log to /var/log/onedrive/alex.onedrive.log
Please set appropriate permissions to allow write access to the logging directory for your user account
The requested client activity log will instead be located in your users home directory

Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 60
```

**Example - 2nd Application Instance:**
```
[alex@centos7full onedrive-pr1955]$ ./onedrive --confdir '~/.config/onedrive-personal/' --monitor --verbose
Using 'user' Config Dir: /home/alex/.config/onedrive-personal/
Configuration file successfully loaded
Using logfile dir: /var/log/onedrive/
Notification (dbus) server not available, disabling

Unable to write activity log to /var/log/onedrive/alex.onedrive.log
Please set appropriate permissions to allow write access to the logging directory for your user account
The requested client activity log will instead be located in your users home directory

Checking Application Version ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...

ERROR: onedrive application is already running - check system process list for active application instances
 - Use 'sudo ps aufxw | grep onedrive' to potentially determine acive running process
```

**Using CTRL-C on 1st instance:**
```
Configuration file successfully loaded
Notification (dbus) server not available, disabling

Unable to write activity log to /var/log/onedrive/alex.onedrive.log
Please set appropriate permissions to allow write access to the logging directory for your user account
The requested client activity log will instead be located in your users home directory

Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 60
^CGot termination signal, performing clean up
Shutting down the HTTP instance
Shutting down db connection
(dmd-2.099.0)[alex@centos7full onedrive-pr1955]$ ./onedrive --confdir '~/.config/onedrive-personal/' --monitor
Configuration file successfully loaded
Notification (dbus) server not available, disabling

Unable to write activity log to /var/log/onedrive/alex.onedrive.log
Please set appropriate permissions to allow write access to the logging directory for your user account
The requested client activity log will instead be located in your users home directory

Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 60
```
No longer false triggering due to CTRL-C

**Comment by abraunegg** [comment]
@elhennig 
> No, it only happens when onedrive terminates either by internal fault of Ctrl-C


Concerned by this comment. The application should not be terminating by an internal fault. 

Please open a new issue with evidence of this so if this is an actual issue - it can be fixed

**Comment by j188482367** [comment]
![screenshot](https://user-images.githubusercontent.com/8536025/167253394-7d1838e2-5218-48f9-9e28-73764d023123.png)

Just restarted ，i dont know where is hiding-active proces. How can I fix it
I just started using ubunut and am not very familiar with it. Sorry for any mistakes

**Comment by tonovcp** [comment]
> No, it only happens when onedrive terminates either by internal fault of Ctrl-C

Thanks

**Comment by abraunegg** [comment]
@j188482367 
> I just started using ubunut and am not very familiar with it

I suggest that you `sudo make uninstall` and `reboot` .. then follow https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md to use the Ubuntu packages.

If you are using Ubuntu 18.x .. upgrade your Ubuntu version to 22.04

**Comment by elhennig** [comment]
> @elhennig
> 
> > No, it only happens when onedrive terminates either by internal fault of Ctrl-C
> 
> Concerned by this comment. The application should not be terminating by an internal fault.
> 
> Please open a new issue with evidence of this so if this is an actual issue - it can be fixed

I built version onedrive v2.4.17-11-g0c8a242 and for now ot seems to work. Thanks for the quick fix!

Regarding the internal fault: I observed this end of last week, when I treid to find out, why this error happened. Since then I haven't seen it again. If it occurs again, I will open another ticket.
