### ISSUE TITLE
remote deletes are not deleted locally

### ISSUE THREAD

**Issue by sj-science** [abraunegg/onedrive#196]
### Bug Report Details ###
**Describe the bug**
A file deleted remotely, e.g. via drop down menu 'Delete' in the browser is not deleted locally.
The same accounts for a folder (tested with an empty folder).  

However, renaming a file or moving a file to a subfolder remotely is reproduced locally.

**Application and Operating System Details:**
- OS: Ubuntu 18.04.1 LTS
- no gui
- onedrive v2.1.4-2-g9680127
- OneDrive Account Type: Business
- DMD64 D Compiler v2.082.0

**To Reproduce**
1. command line:  onedrive --monitor
2. copy file manuscript_clean.tex to local OneDrive folder
3. onedrive synchronizes change: 
Uploading file ./manuscript_clean.tex ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:                                     
 done.
4. switch to OneDrive tab in browser to see remote changes / manuscript_clean.tex appears
5. Delete file manuscript_clean.tex in browser app via drop down menu
6.  the deleted file remains in the local folder 

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```
user01@linux:~/.config/onedrive$ onedrive -v --monitor
Loading config ...
Using Config Dir: /Users/home/user01/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /Users/home/user01/05_mnt/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!tSP3vTnqREuOegO0Lav9JG4uuKq3SWRBhYEBOWd2lpq81krwi8hLTqbc4pUZpQZG
Default Root ID: 013ZOVV5N6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1078649041583
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing monitor ...
OneDrive monitor interval (seconds): 45
Monitor directory: .
Monitor directory: ./05_DGT_experiment
Monitor directory: ./05_DGT_experiment/drafts
Monitor directory: ./05_DGT_experiment/article
Monitor directory: ./05_DGT_experiment/article/figures
Monitor directory: ./05_DGT_experiment/corrections
Monitor directory: ./05_DGT_experiment/figures
Monitor directory: ./Email attachments
Monitor directory: ./Attachments
Monitor directory: ./Shared with Everyone
[M] File changed: ./manuscript_clean.tex
Uploading differences of ./manuscript_clean.tex
Uploading new items of ./manuscript_clean.tex
Uploading file ./manuscript_clean.tex ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:                                    
 done.
Remaining free space: 1078648913116
Syncing changes from OneDrive ...
Applying changes of Path ID: 013ZOVV5N6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
Uploading new items of .
Applying changes of Path ID: 013ZOVV5N6Y2GOVW7725BZO354PWSELRRZ
Syncing changes from OneDrive ...
Applying changes of Path ID: 013ZOVV5N6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
Uploading new items of .
Applying changes of Path ID: 013ZOVV5N6Y2GOVW7725BZO354PWSELRRZ
^C
```

### Bug Report Checklist ###
- [ x] Detailed description
- [ x] Reproduction steps (if applicable)
- [x ] Verbose Log Output

**Comment by abraunegg** [comment]
@sj-science
Any update?

**Comment by sj-science** [comment]
Thank you for very quick response.
1. yes I upgraded from 'skilion' version
2. No, I did not delete items.sqlite3  ...

Will test it today and let you know. Thank you

**Comment by sj-science** [comment]
No change in behavior unfortunately
Here the slightly expanded test

1. removed items.sqlite3
2. started onedrive monitor
3. copied two files to local OneDrive 
-  manuscript_clean.tex
-  manuscript_clean_2.tex
4. both were uploaded by onedrive
5. on the remote onedrive, i.e. browser app
- deleted manuscript_clean.tex
- moved manuscript_clean_2.tex to folder attachements



user01@linux:~/.config/onedrive$ rm items.sqlite3*
user01@linux:~/.config/onedrive$ onedrive --monitor -v
Loading config ...
Using Config Dir:/Users/home/user01/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /Users/home/user01/05_mnt/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!tSP3vTnqREuOegO0Lav9JG4uuKq3SWRBhYEBOWd2lpq81krwi8hLTqbc4pUZpQZG
Default Root ID: 013ZOVV5N6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1078051628315
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing monitor ...
OneDrive monitor interval (seconds): 45
Monitor directory: .
Monitor directory: ./05_DGT_experiment
Monitor directory: ./05_DGT_experiment/drafts
Monitor directory: ./05_DGT_experiment/article
Monitor directory: ./05_DGT_experiment/article/figures
Monitor directory: ./05_DGT_experiment/corrections
Monitor directory: ./05_DGT_experiment/figures
Monitor directory: ./Email attachments
Monitor directory: ./Attachments
Monitor directory: ./Shared with Everyone
[M] File changed: ./manuscript_clean.tex
Uploading differences of ./manuscript_clean.tex
Uploading new items of ./manuscript_clean.tex
Uploading file ./manuscript_clean.tex ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:                                     
 done.
Remaining free space: 1078051499848
Syncing changes from OneDrive ...
Applying changes of Path ID: 013ZOVV5N6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
Uploading new items of .
Uploading file ./manuscript_clean_2.tex ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:                                     
 done.
Remaining free space: 1078051371381
Applying changes of Path ID: 013ZOVV5N6Y2GOVW7725BZO354PWSELRRZ
Syncing changes from OneDrive ...
Applying changes of Path ID: 013ZOVV5N6Y2GOVW7725BZO354PWSELRRZ
Moving manuscript_clean_2.tex to Email attachments/manuscript_clean_2.tex
Uploading differences of .
Processing root
Uploading new items of .
Applying changes of Path ID: 013ZOVV5N6Y2GOVW7725BZO354PWSELRRZ
Syncing changes from OneDrive ...
Applying changes of Path ID: 013ZOVV5N6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
Uploading new items of .
Applying changes of Path ID: 013ZOVV5N6Y2GOVW7725BZO354PWSELRRZ
^C

i find it strange that the moving of the file does trigger onedrive to act correctly but not the deleting of the file.  Any other tests I could perform?  Would it help if I tested the behavior with a windows client?

**Comment by abraunegg** [comment]
Do you have any other configuration for your 'onedrive' client going on?

I can confirm that for Business accounts delete's do occur - why it's not occurring for your account needs to be analysed.

Can you please run the client manually - without using monitor mode, and see if the delete is processed?

Additionally, if it is not deleted, rerun the client manually (no monitor mode), whilst doing a 'new' remote delete, but add the `--debug-https` flag to your command line and see what is actually being send by OneDrive to the onedrive client.

**Comment by sj-science** [comment]
I would say 'no', there is no other configuration going on.  But being 'just' a user how do I make sure this is true?

However, maybe I'm not running the client correctly to start with.  
I only use the 
onedrive --monitor -v
command.  Isn't that manual running?
Doesn't onedrive require either the --synchronize or --monitor option to do anything?

Let me do a clean restart according to Readme.md and see if it works then.

**Comment by sj-science** [comment]
Here we go
1. run
onedrive --logout
2. delete local OneDrive folder
3. run
user01@linux:~/.config/onedrive$ rm items.sqlite3-*
4. output config
user01@linux:~/.config/onedrive$ cat config 
# Directory where the files will be synced
sync_dir = "~/05_mnt/OneDrive"
# Skip files and directories that match this pattern
skip_file = ".*|~*"
5. run
onedrive --synchronize --debug-https
6. run
onedrive --monitor --debug-https
7. copy manuscript_clean.tex to local OneDrive folder
8. after uploading, delete remote manuscript_clean.tex

Remote delete does not register...

I'm trying to upload the logs of 5. and 6. to pastebin as recommended.

**Comment by abraunegg** [comment]
> run
onedrive --monitor --debug-https

When trying to diagnise this issue - please do not use `--monitor` - only `onedrive --synchronize --verbose --debug-https`

**Comment by abraunegg** [comment]
unable to view - please output email to support@mynas.com.au

**Comment by sj-science** [comment]
done.  Thanks again for looking into this.

**Comment by abraunegg** [comment]
Please try the following PR which will output each change from OneDrive:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/197/head:pr197
git checkout pr197
make
```

Delete the file from OneDrive, then run the above built version:

```
./onedrive --synchronize --verbose 
```

You should get output similar to below:
```
Loading config ...
Using Config Dir: /home/user/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/user/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 1099259766710
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","fileSystemInfo":{"createdDateTime":"2018-04-04T03:32:04Z","lastModifiedDateTime":"2018-10-15T03:37:33Z"},"folder":{"childCount":0},"id":"01D6JQORV6Y2GOVW7725BZO354PWSELRRZ","name":"root","parentReference":{"driveId":"b!xA9hqR7mT0OL6Gku8YbuzTJ8oZmRnQZJu6-yDL49Zc5MccrHbuT0R4QUwIzUvbJY","driveType":"business"},"root":{}}
OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"\"c:{69164C54-0A4E-4BAB-B7FA-FE03B9699C32},4294967295\"","deleted":{"state":"deleted"},"file":{},"fileSystemInfo":{},"id":"01D6JQORSUJQLGSTQKVNF3P6X6AO4WTHBS","parentReference":{"driveId":"b!xA9hqR7mT0OL6Gku8YbuzTJ8oZmRnQZJu6-yDL49Zc5MccrHbuT0R4QUwIzUvbJY","driveType":"business","id":"01D6JQORV6Y2GOVW7725BZO354PWSELRRZ"}}
Deleting item file
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: <redacted>
```

**Comment by sj-science** [comment]
hi Alex,

see output email.  The client appears to receive ` {"state":"deleted"}`  inside the second `OneDrive Change:` line but does not trigger the local
`Deleting item file`
as it does in your example.  Could this be some weird  time stamp issue?

thanks

**Comment by abraunegg** [comment]
no updated email received - nothing in spam either

**Comment by sj-science** [comment]
Sent to github email accidentally.  
Resent to support@mynas.com.au. My apologies

**Comment by abraunegg** [comment]
Can you rebuild your application with the same PR instructions above? I have changed the debug logging given that you are receiving the 'delete change' from OneDrive:

```
Loading config ...
Using Config Dir: /home/user/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/user/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 1099259766016
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: <redacted>
This item is marked for deletion:01D6JQORRR7VIIUIOMSZELQ6TVX4ZXV36R
idsToDelete:[["b!xA9hqR7mT0OL6Gku8YbuzTJ8oZmRnQZJu6-yDL49Zc5MccrHbuT0R4QUwIzUvbJY", "01D6JQORRR7VIIUIOMSZELQ6TVX4ZXV36R"]]
Deleting item file1
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: <redacted>
```

**Comment by sj-science** [comment]
I'm on it.  Thanks for spending so much effort on this.

**Comment by sj-science** [comment]
1. install onedrive pull 197
2.  `onedrive --logout`
3. `./onedrive --synchronize --verbose `
4. copy file to local onedrive folder
5. upload via  `./onedrive --synchronize --verbose `  (see first log)
6. delete remote file
7. `./onedrive --synchronize --verbose `  (see second log)

non of the messages expected :(

user01@linux:~/Desktop/onedrive$ ./onedrive --synchronize --verbose 
Loading config ...
Using Config Dir: /Users/home/user01/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /Users/home/user01/05_mnt/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: xxxxxxxxxxx
Default Root ID: xxxxxxxxxxx
Remaining Free Space: 1078049121613
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: xxxxxxxxxxx
Uploading differences of .
Processing root
Uploading new items of .
Uploading file ./manuscript_clean.tex ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:                                     
 done.
Remaining free space: 1078048993146
Applying changes of Path ID: xxxxxxxxxxx



user01@linux:~/Desktop/onedrive$ ./onedrive --synchronize --verbose 
Loading config ...
Using Config Dir: /Users/home/user01/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /Users/home/user01/05_mnt/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: xxxxxxxxxxx
Default Root ID: xxxxxxxxxxx
Remaining Free Space: 1078048992460
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: xxxxxxxxxxx
Uploading differences of .
Processing root
Uploading new items of .
Applying changes of Path ID: xxxxxxxxxxx
user01@linux:~/Desktop/onedrive$

**Comment by sj-science** [comment]
~/05_mnt is local folder where I keep external sources, like external hard drives, network shares, dropbox etc.  
However, ~/05_mnt/OneDrive is a truly local folder.  Nevertheless, I will double check once back in the office - my home might actually be mounted all together...

I tried the same procedure with pull 197 on my labtop that runs CentOS 7.  Deleting works fine, both ways.

**Comment by abraunegg** [comment]
> I tried the same procedure with pull 197 on my labtop that runs CentOS 7. Deleting works fine, both ways.

Can you retry at home with 'master' as the only difference in #197 is the additional logging.

Why it is not working at work vs working at home - that has to be some sort of local environment issue on the work laptop.

When you raised this case, all the tests I have been performing has been on a Ubuntu 18.04.1 LTS system as well - and I cannot reproduce at all.

I would suggest ensuring that the DMD compiler is correctly installed (not via ubuntu packages etc) with all the dependencies, reboot the laptop and so on.

**Comment by sj-science** [comment]
> I would suggest ensuring that the DMD compiler is correctly installed (not via ubuntu packages etc) with all the dependencies, reboot the laptop and so on.
I suspect that too.  However, I need to motivate my IT admin for playing with the compiler.  Might take a few days, but I keep you posted.  Thanks for the help, really appreciate it!!!

**Comment by abraunegg** [comment]
@sj-science 
If your going to play around with with compiler versions, there is now a `dmd-2.082.1` out. You could also try rebuilding on Ubuntu using LDC as well to see if you get any different outcome. I cannot reproduce this at all.

**Comment by abraunegg** [comment]
@sj-science
Any update from your end?

**Comment by sj-science** [comment]
Unfortunately not.  I won't get to it until next week I'm afraid. 
But indeed the current compiler version is 2.082.0-0.  I'll try with the newer version and will update here.
cheers

**Comment by abraunegg** [comment]
@sj-science 
Any update from your side?

**Comment by sj-science** [comment]
Updating the compiler to version 2.082.1-0 did the trick. 
Just re installed onedrive with the new dmd and the local delete works now.  
I think this can be closed as resolved.
@abraunegg   Thank you for your efforts and guiding to a solution.
cheers
