### ISSUE TITLE
Question: Why does the makefile use cp -raf on systemd service?

### ISSUE THREAD

**Issue by priv** [abraunegg/onedrive#198]
-a switch causes onedrive.service copied into /usr/lib/systemd/user/ with original user and group.

For example on my machine:
-rw-r--r--  1 alvin alvin     270 Oct 15 10:18  onedrive.service

Is that done on purpose?

**Comment by abraunegg** [comment]
> Is that done on purpose?

No - its not done on purpose.

**Comment by abraunegg** [comment]
@priv 
Can you please help validate PR #202:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/202/head:pr202
git checkout pr202
make
sudo make install
```

**Comment by priv** [comment]
It's good, thanks.

**Comment by abraunegg** [comment]
PR #202 merged
