### ISSUE TITLE
Failed to start onedrive.service

### ISSUE THREAD

**Issue by yesongs** [abraunegg/onedrive#203]
### Bug Report Details ###
$ systemctl --user start onedrive
Failed to start onedrive.service: Process org.freedesktop.systemd1 exited with status 1
See user logs and 'systemctl --user status onedrive.service' for details.

**Application and Operating System Details:**
- Linux 4.15.0-1-amd64 #1 SMP Debian 4.15.4-1~mx17+1 (2018-02-23) x86_64 GNU/Linux 
- Desktop: Xfce 4.12.3 Distro: MX-17.1_x64 Horizon March 14  2018
- Application version: onedrive v2.1.4-4-g79d86e0
- OneDrive Account Type: Business
- DMD or LDC compiler version DMD64 D Compiler v2.082.1

**To Reproduce**
Installation is done without errors
Sync is proceeding without problem when using onedrive --synchronize
Only service is not working

**Comment by abraunegg** [comment]
Hi,

You have not provided any detailed logs as to why the service is failing to start. Without that, no assistance can be provided.

**Comment by abraunegg** [comment]
Can you ensure that you are performing the following:
```
user@debian-x86-64:~$ systemctl --user enable onedrive
user@debian-x86-64:~$ systemctl --user start onedrive
```

The service starts without issue as a regular (non root) user.

**Note:** Debian prevents `systemctl --user enable onedrive` from running as 'root' and returns the following error:
```
Failed to connect to bus: No such file or directory
```

This is not a 'onedrive' client issue, rather than a Debian systemd issue if you encounter this problem

**Comment by yesongs** [comment]
After a small research I come to know that:

> systemctl is a systemd command, and mx doesn't use systemd to start/stop services by default. It uses sysvinit.

So I tried the init.d option.

```
$ chkconfig onedrive on
bash: chkconfig: command not found
```
Also some research and:

> The command chkconfig is no longer available in Ubuntu.The equivalent command to chkconfig is update-rc.d.This command nearly supports all the new versions of ubuntu.
> 
> The similar commands are
> 
> update-rc.d <service> defaults
> update-rc.d <service> start 20 3 4 5
> update-rc.d -f <service>  remove

The result:
```
update-rc.d onedrive  start
update-rc.d: error: unable to read /etc/init.d/onedrive
```
What kind of entry is supposed to be in /etc/init.d??

**Comment by abraunegg** [comment]
It sounds like you need to manually create a file called `/etc/init.d/onedrive` with the contents from here: `https://github.com/abraunegg/onedrive/blob/master/init.d/onedrive.init`

You then need to create a file called `onedrive.sh` to the same location where the 'onedrive' binary has been installed. The contents of this file needs to be taken from here: `https://github.com/abraunegg/onedrive/blob/master/init.d/onedrive_service.sh`

Both these files, when correctly installed / configured work without issue on CentOS 6 which is init.d based as well.

**Comment by abraunegg** [comment]
@yesongs
Any update?

**Comment by yesongs** [comment]
Sorry for not posting earlier, just busy with my work....

I followed this advice:

> I believe the script was writting for bsd's init system, or maybe some other init system like OpenRC, and not sysVinit.
> 
> I've hacked together the following. the service does start, but I can't help if the app doesn't actually work.
> 
> 1. take the following file (modified onedrive.init) and place in /etc/init.d (note the original make install does not do this).
> 
> /etc/init.d/onedrive.init
> 
> 
> ```
> #!/bin/sh
> ### BEGIN INIT INFO
> # Provides:          onedrive
> # Required-Start:    $network $remote_fs
> # Required-Stop:     $network $remote_fs
> # Should-Start:	     $syslog
> # Should-Stop:       $syslog
> # Default-Start:     2 3 4 5
> # Default-Stop:      0 1 6
> # Short-Description: Starts and stops OneDrive Free Client
> # 
> ### END INIT INFO
> 
> # Source function library.
> if [ -f /etc/init.d/functions ] ; then
>   . /etc/init.d/functions
> elif [ -f /lib/lsb/init.d/functions ] ; then
>   . /etc/rc.d/init.d/functions
> else
>   . /lib/lsb/init-functions
> fi
> 
> # Source networking configuration.
> #. /etc/sysconfig/network
> 
> # Check that networking is up.
> #[ ${NETWORKING} = "no" ] && exit 1
> 
> APP_NAME="OneDrive Free Client"
> STOP_TIMEOUT=${STOP_TIMEOUT-5}
> RETVAL=0
> 
> start() {
>         echo -n $"Starting $APP_NAME: "
>         #daemon --user root onedrive_service.sh
>         onedrive_service.sh
>         RETVAL=$?
>         echo
>         [ $RETVAL -eq 0 ] && mkdir -p /var/lock/subsys && touch /var/lock/subsys/onedrive || \
>            RETVAL=1
>         return $RETVAL
> }
> 
> stop() {
>         echo -n $"Shutting down $APP_NAME: "
>         killproc onedrive
>         RETVAL=$?
>         echo
>         [ $RETVAL = 0 ] && rm -f /var/lock/subsys/onedrive ${pidfile}
> }
> 
> restart() {
>         stop
>         start
> }
> 
> rhstatus() {
>         status onedrive
>         return $?
> }
> 
> # Allow status as non-root.
> if [ "$1" = status ]; then
>        rhstatus
>        exit $?
> fi
> 
> case "$1" in
>   start)
>         start
>         ;;
>   stop)
>         stop
>         ;;
>   restart)
>         restart
>         ;;
>   reload)
>         reload
>         ;;
>   status)
>         rhstatus
>         ;;
>   *)
>         echo $"Usage: $0 {start|stop|restart|reload|status}"
>         exit 2
> esac
> 
> exit $?
> ```
> 
> 2. make the file executable
> 
> 
> `sudo chmod a+x /etc/init.d/onedrive.init`
> 3. place onedrive_service in /usr/bin (the original make install doesn't do this)
> 
> 4. make onedrive_service executable
> 
> 
> `chmod a+x /usr/bin/onedrive_service`
> 5. you can start the service now with
> 
> 
> `sudo service onedrive.init start`
> and stop with
> 
> 
> `sudo service onedrive.init stop`
> 6. to enable auto start of service on boot,
> 
> 
> `sudo update-rc.d onedrive.init defaults`
> Good luck!

Now I get no error but the service wouldn't start at all, it's just giving the following:

```
$ sudo service onedrive.init start
[sudo] password for george: 
$Starting OneDrive Free Client: 
```

**Comment by abraunegg** [comment]
@yesongs 
Unfortunately I cannot assist any further.

The sample init.d file & service start script works without issue on RHEL6 / CentOS 6 and allows the client to run as the 'root' user. You will have to work with your distribution to make init.d work for you.
