### ISSUE TITLE
Uploaded file size does not match local file when syncing from a shared Sharepoint site

### ISSUE THREAD

**Issue by SL0RD** [abraunegg/onedrive#205]
### Bug Report Details ###
Setting up new Sharepoint site and trying to sync a large amount of local files to the Sharepoint site. The files appear to upload without an issue however I am continually getting this message: Uploaded file size does not match local file - upload failure - retrying
 and it attempts to reupload the file. But this fails and it just loops forever. Ive found if a specify a sub directory it will upload a few files before getting stuck in the loop again.

**Application and Operating System Details:**
- OS: Linux polyserv 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux
- Headless
- Application version: onedrive v2.0.2-23-g95eaa72
- OneDrive Account Type: o365 Business account
- DMD64 D Compiler v2.078.3

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
Installation is done without any errors.
The endless loop happens when running as service or as user.
onedrive --synchronize --resync doesnt change anything.

**Comment by SL0RD** [comment]
just realized I'm using an outdated version of the client. I'm going to update to the latest version and see if that helps.

**Comment by SL0RD** [comment]
Okay i just reinstalled the latest version. However because im using PR104 to connect to o365 sharepoint the version is showing different. Im still getting the upload loop.

**Comment by abraunegg** [comment]
@SL0RD 
You will have to manually create your own branch with master & the PR104 changes and see if that resolves things for you & report back

**Comment by abraunegg** [comment]
Can you help validate PR #206?

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/206/head:pr206
git checkout pr206
make
sudo make install
```

**Comment by abraunegg** [comment]
If the issue still occurs with PR #206, please can you provide verbose log output & potentially look at using the `--debug-https` switch to see what the upload response is to assist in working out why & where this is failing.

**Comment by SL0RD** [comment]
Im getting the same error with PR206. I have a log file but im wondering if there is any sensitive info in it, is there a secure way to post it or send it to you?

**Comment by brandonkirsch** [comment]
I too have the same errors with PR206.

--verbose output does not look any more informative:

> Processing New Business Summary Report - R5542C2 - Source Code.html
> The file last modified time has changed
> Processing New Business Detail Report - R5542C1 - Source Code.html
> The file has not changed
> Processing New Business Summary Report - R5542C2-PC0001.pdf
> The file last modified time has changed
> Processing OT with no ST.xlsx
> The file last modified time has changed
> Uploading new items of .
> Uploading file ./Polychem - CS and Sales/New Business Detail Report - R5542C1 - Source Code-bkirsch-t470s.polychem.com.html ...
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:                                                                                                                
>  done.
> Uploaded file size does not match local file - upload failure - retrying
> Uploading file ./Polychem - CS and Sales/New Business Detail Report - R5542C1 - Source Code-bkirsch-t470s.polychem.com.html ...
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:                                                                                                                
>  done.
> Uploaded file size does not match local file - upload failure - retrying
> Uploading file ./Polychem - CS and Sales/New Business Detail Report - R5542C1 - Source Code-bkirsch-t470s.polychem.com.html ...

After I deleted the file that ends with -bkirsch-t470s.polychem.com.html (which is the name of my machine) and re-ran `onedrive --synchronize` then everything completed just fine.

**Comment by abraunegg** [comment]
@SL0RD, @brandonkirsch 

Can you please archive the local files that are causing the issue for you & email to support@mynas.com.au so that I can try and replicate this

I will also update the PR with some additional debugging - will update here once I have done that.

**Comment by abraunegg** [comment]
@SL0RD, @brandonkirsch
If you can help rebuild your client with the latest PR #206 changes & post the results from:

```
onedrive --synchronize --verbose
```

That would be greatly appreciated.

**Comment by SL0RD** [comment]
I did a bit more testing myself and it seems to only be failing on MS office files and .html files. Ive been able to sync a large number of PDF documents as well as .png and jpg images and some dummy .img files without issue

**Comment by abraunegg** [comment]
@SL0RD 
Can you provide some of the additional debug logs from the updated PR #206? This will show what OneDrive is returning once the file is uploaded which would indicate why it is failing.

**Comment by SL0RD** [comment]
`Uploading new items of Administration/Logos
OneDrive Client requested to create remote path: Administration/Logos/Excel spreadsheet of various Logos from PP
The requested directory to create was not found on OneDrive - creating remote directory: Administration/Logos/Excel spreadsheet of various Logos from PP
Successfully created the remote directory Administration/Logos/Excel spreadsheet of various Logos from PP on OneDrive
Uploading file Administration/Logos/Excel spreadsheet of various Logos from PP/13.04.06.Polycorp.logos.xlsx ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:
 done.
Uploaded file size does not match local file - upload failure - retrying
Uploading file Administration/Logos/Excel spreadsheet of various Logos from PP/13.04.06.Polycorp.logos.xlsx ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:
 done.
Uploaded file size does not match local file - upload failure - retrying
Uploading file Administration/Logos/Excel spreadsheet of various Logos from PP/13.04.06.Polycorp.logos.xlsx ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:
 done.
Uploaded file size does not match local file - upload failure - retrying
Uploading file Administration/Logos/Excel spreadsheet of various Logos from PP/13.04.06.Polycorp.logos.xlsx ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:`

**Comment by abraunegg** [comment]
@SL0RD 
Did you rebuild the client? I added additional debug lines which are not in the above which should be there if you rebuilt the client.

**Comment by SL0RD** [comment]
I just rebuilt it, getting the additional debug info now. See below

`Uploading file Administration/Logos/13.04.06.Polycorp.logos.xlsx ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:
 done.
Upload Response: {"@content.downloadUrl":"https:\/\/polycorpinc.sharepoint.com\/_layouts\/15\/download.aspx?UniqueId=2a72d61f-d0ca-454c-b031-cabce23e6304&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvcG9seWNvcnBpbmMuc2hhcmVwb2ludC5jb21AMjBhYzBjYTktYTI0ZS00ZTJmLTlmZjgtOGUwNDhlOTIwZGZhIiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTU0MDUwMDAwOCIsImV4cCI6IjE1NDA1MDM2MDgiLCJlbmRwb2ludHVybCI6ImF2VUl1aDFYNUlxWk9Hd1ZNbkt4UDhhWTQycjdrK2hGdk54cGFkckRKMUE9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxMjIiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6Ik1UZG1NamxpT1dVdE5qQTJOaTAzTURBd0xUWXlOREV0WkRJMVl6WmxPRFEzTjJNeSIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJNVGd5TWpSaFpXWXRPREJqT1MwMFpUTXlMV0ZrWTJJdE5qY3hNR0kwTXpjNE5URXgiLCJhcHBfZGlzcGxheW5hbWUiOiJPbmVEcml2ZSBGcmVlIENsaWVudCIsImFwcGlkIjoiMjJjNDlhMGQtZDIxYy00NzkyLWFlZDEtOGYxNjNjOTgyNTQ2IiwidGlkIjoiMjBhYzBjYTktYTI0ZS00ZTJmLTlmZjgtOGUwNDhlOTIwZGZhIiwidXBuIjoiYWRtaW5AcG9seWNvcnBpbmMub25taWNyb3NvZnQuY29tIiwicHVpZCI6IjEwMDNCRkZEOTRBNTFDRTUiLCJzY3AiOiJteWZpbGVzLndyaXRlIGFsbGZpbGVzLndyaXRlIiwidHQiOiIyIiwidXNlUGVyc2lzdGVudENvb2tpZSI6bnVsbH0.dnpVdmNBaDZBYWlHRXhQNjhsdjdvYlhIM0JMTHFxMmM4QW8weGxKTFZlND0&ApiVersion=2.0","@odata.context":"https:\/\/polycorpinc.sharepoint.com\/_api\/v2.0\/$metadata#items\/$entity","@odata.editLink":"drives\/b!70oiGMmAMk6ty2cQtDeFEUlFKuWreNdJjTP7UAmMibhf5jBJMCngSouGei04EU3g\/items\/017HNQS6I72ZZCVSWQJRC3AMOKXTRD4YYE","@odata.id":"https:\/\/polycorpinc.sharepoint.com\/_api\/v2.0\/drives\/b!70oiGMmAMk6ty2cQtDeFEUlFKuWreNdJjTP7UAmMibhf5jBJMCngSouGei04EU3g\/items\/017HNQS6I72ZZCVSWQJRC3AMOKXTRD4YYE","@odata.type":"#oneDrive.item","cTag":"\"c:{2A72D61F-D0CA-454C-B031-CABCE23E6304},8\"","createdBy":{"application":{"displayName":"OneDrive Free Client","id":"22c49a0d-d21c-4792-aed1-8f163c982546"},"user":{"displayName":"Polycorp Inc.","id":"98aea979-57b0-486c-93bb-7d2b4cf42c43"}},"createdDateTime":"2018-10-25T20:40:04Z","eTag":"\"{2A72D61F-D0CA-454C-B031-CABCE23E6304},7\"","file":{"hashes":{"quickXorHash":"fJzmk6BKBAnrv\/5eGHQwM\/Fd2TA="},"mimeType":"application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},"fileSystemInfo":{"createdDateTime":"2018-10-25T20:40:04Z","lastModifiedDateTime":"2014-05-20T11:33:00Z"},"id":"017HNQS6I72ZZCVSWQJRC3AMOKXTRD4YYE","lastModifiedBy":{"application":{"displayName":"OneDrive Free Client","id":"22c49a0d-d21c-4792-aed1-8f163c982546"},"user":{"displayName":"Polycorp Inc.","id":"98aea979-57b0-486c-93bb-7d2b4cf42c43"}},"lastModifiedDateTime":"2014-05-20T11:33:00Z","name":"13.04.06.Polycorp.logos.xlsx","parentReference":{"driveId":"b!70oiGMmAMk6ty2cQtDeFEUlFKuWreNdJjTP7UAmMibhf5jBJMCngSouGei04EU3g","driveType":"documentLibrary","id":"017HNQS6IFT7FOVYAULRCI4CJ3BV4XZHTS","path":"\/drives\/b!70oiGMmAMk6ty2cQtDeFEUlFKuWreNdJjTP7UAmMibhf5jBJMCngSouGei04EU3g\/root:\/Administration\/Logos"},"size":983266,"webUrl":"https:\/\/polycorpinc.sharepoint.com\/_layouts\/15\/Doc.aspx?sourcedoc=%7B2A72D61F-D0CA-454C-B031-CABCE23E6304%7D&file=13.04.06.Polycorp.logos.xlsx&action=default&mobileredirect=true"}
Uploaded file size does not match local file - upload failure - retrying
`

**Comment by abraunegg** [comment]
@SL0RD 
OK - thanks. So the size is being reported back from MS Graph Service as the following:
```
"size":983266
```
A couple of questions:

* What does OneDrive say the size is when you view the file size via a web browser?
* What is the actual file size on your local disk where the file resides?

**Comment by SL0RD** [comment]
This is what shows on the server thats hosting the local files. I also confirmed its showing the same size from my windows machine.
`sidney@polyserv:~/OneDrive/Administration/Logos$ ls -la | grep logos.xlsx
-rwxrwxrwx  1 sidney sidney  977069 May 20  2014 13.04.06.Polycorp.logos.xlsx
`
On sharepoint it looks like the file is showing as 960KB, Im not sure how show it in bytes though.

**Comment by abraunegg** [comment]
OK .. so for some reason the size being reported back from OneDrive is incorrect then for the file types - which is weird.

> On sharepoint it looks like the file is showing as 960KB, Im not sure how show it in bytes though.

There should be a file details / file version area (cant recall the exact area atm) that gives you the exact file details.

I suspect that this is a OneDrive API issue. The code is working correctly & as expected, and it ONLY seems to be this way with shared SharePoint systems - as I have tried to upload various files (PDF, MS Office Documents, html files etc) to a OneDrive Business Account and cannot reproduce this at all.

**Comment by SL0RD** [comment]
When i go into previous versions it shows as 960.2KB

**Comment by abraunegg** [comment]
This sounds like an API issue which I have zero control over - sorry.

It works for personal and business accounts, ondrive personal shared folders - but broken for Office 365 / Sharepoint Shared environments

**Comment by abraunegg** [comment]
@SL0RD, @brandonkirsch

Can you please provide some details as to when this was working without issue & potentially a time frame when this broke?

**Comment by SL0RD** [comment]
Im not sure as I only recently discovered this client and have had the issue from the start

**Comment by brandonkirsch** [comment]
Background:  I just started using this client two weeks ago when I got a new machine at work.  I saw this issue the very first day I tried using it on a plain .txt file.  Today the problem came back in an interesting way.

I have a file called **2018-10-12 Burn Down Rate.xlsx** that I initialized locally and then uploaded using this tool.  It was one of 6 Excel sheets that I initialized today, but the only one to throw the `file size does not match` error.

My local copy of this file is 20,143 bytes.  The Sharepoint Documents repository shows 25.6 KB with no obvious way of seeing the exact number of bytes.  However, when I use my web browser to download the file, it comes out to 26,194 bytes!  The visible content within this Excel sheet is identical, but the files themselves must be different.

A cursory look shows that Sharepoint is modifying the files after they are uploaded.  I extracted each of the .XLSX files as ZIP archives and I can see that Sharepoint has injected a new file at the path **docProps/custom.xml** that does not exist in my original upload.  There is an entire extra folder named **customXml** filled with 6 additional files and a subfolder as well.

So Sharepoint is modifying these files after they are uploaded.  That's.... interesting.  My current workaround is to delete the local file after I see the error and allow it to re-sync the updated copy from Sharepoint.  I don't know if that is a sane default but it is the workflow I have adopted.

Here are the two files:  "-orig" is the document I originated on my PC and uploaded via the client.
The "-Sharepoint" version is what is returned to me when I download the file from )365 Sharepoint's web interface.

[2018-10-12 Burn Down Rate-orig.xlsx](https://github.com/abraunegg/onedrive/files/2539670/2018-10-12.Burn.Down.Rate-orig.xlsx)

[2018-10-12 Burn Down Rate-Sharepoint.xlsx](https://github.com/abraunegg/onedrive/files/2539672/2018-10-12.Burn.Down.Rate-Sharepoint.xlsx)

**Comment by demoii** [comment]
Hi, I recently started to see the exact same issue as described above. Is there any way to selectively turn off syncing size validation?

**Comment by abraunegg** [comment]
@demoii 
> Hi, I recently started to see the exact same issue as described above

Can you confirm your using specifically the #206 branch and are syncing from a OneDrive Shared Sharepoint repository?

Do you have some logs to indicate when this may have started at all?

What is the exact same issue your seeing?

1. Just upload size differences?
2. Confirming that files are being modified by OneDrive after upload with customxml data being added?

> Is there any way to selectively turn off syncing size validation?

I can certainly update the code, however the whole 'point' of checking the response from OneDrive on a successful upload - is that we ensure that the file is correctly uploaded - the last thing you want to happen is 'think' that you uploaded the file OK, then delete the good local copy, only to have a corrupt version on OneDrive.

**Comment by demoii** [comment]
@abraunegg 
I confirm that I'm syncing from a Onedrive Shared Sharepoint repository. 

> Do you have some logs to indicate when this may have started at all?
Here are my logs. It is saying the file that is just uploaded does not match the source file. 

`2018-Nov-05 14:29:11.7087623 Uploading file ./GSAX/chen_test/a test file.pptx ... done.
2018-Nov-05 14:29:11.708888 Uploaded file size does not match local file - upload failure - retrying
2018-Nov-05 14:29:17.7264767 Uploading file ./GSAX/chen_test/a test file.pptx ... done.
2018-Nov-05 14:29:17.7266211 Uploaded file size does not match local file - upload failure - retrying
2018-Nov-05 14:29:23.3959142 Uploading file ./GSAX/chen_test/a test file.pptx ... done.
2018-Nov-05 14:29:23.3960317 Uploaded file size does not match local file - upload failure - retrying
2018-Nov-05 14:29:28.9454657 Uploading file ./GSAX/chen_test/a test file.pptx ... done.`

For size validation, I get your point. Having the size difference issue shall be a better way than turning this validation off for sure.  

FYI, the first time i see the issue is from `2018-Oct-08 06:09:45.8543295 JST`. It is a weekly log so i was not sure when exactly the issue happened.

**Comment by abraunegg** [comment]
> FYI, the first time i see the issue is from `2018-Oct-08 06:09:45.8543295 JST`. It is a weekly log so i was not sure when exactly the issue happened.

Do you have any logs from before this date at all showing successful syncing?

The only reason I ask is that I want to provide as much detail to this case: OneDrive/onedrive-api-docs#935

As this is clearly a OneDrive API / MS Graph change which I have zero control over.

**Comment by demoii** [comment]
I have logs before October syncing the files well, but I'm afraid that is running using https://github.com/skilion/onedrive and in beginning of October, switched to current onedrive install.  

`
Mon Sep  3 06:45:29 JST 2018 Downloading GSAX/APAC_CPP_WeeklySlides/Week  2018-08-19 to 2018-08-25/APAC - Weekly - Week  2018-08-19 to 2018-08-25.pptx... done.
Mon Sep  3 06:45:33 JST 2018 Uploading file ./GSAX/APAC_CPP_WeeklySlides/Week  2018-08-19 to 2018-08-25/APAC - Weekly - Week  2018-08-19 to 2018-08-25-cerebro.pptx... done.
Mon Sep  3 06:45:33 JST 2018 Creating folder ./GSAX/APAC_CPP_WeeklySlides/Week  2018-08-26 to 2018-09-01
Mon Sep  3 06:45:37 JST 2018 Uploading file ./GSAX/APAC_CPP_WeeklySlides/Week  2018-08-26 to 2018-09-01/APAC - Weekly - Week  2018-08-26 to 2018-09-01.pptx... done.
`

**Comment by abraunegg** [comment]
OK - thanks ..

**Comment by abraunegg** [comment]
@SL0RD, @brandonkirsch, @demoii 
There is a request from Microsoft in regards to this detailed in https://github.com/OneDrive/onedrive-api-docs/issues/935

Can you please run the application manually, using the `--debug-https` flag so you can capture the following data:

* Date (in UTC, please)
* request-id
* SPRequestGuid (for requests made to OneDrive for Business)

The entire sequence will look something like this - but for your session upload & the response it is giving:

```
The requested directory to create was not found on OneDrive - creating remote directory: ./3A/asdf
* Found bundle for host graph.microsoft.com: 0x55bd52d85600 [can pipeline]
* Re-using existing connection! (#1) with host graph.microsoft.com
* Connected to graph.microsoft.com (20.190.142.178) port 443 (#1)
> POST /v1.0/drives/66d53be8a5056eca/items/66D53BE8A5056ECA!2481/children HTTP/1.1
Host: graph.microsoft.com
User-Agent: Phobos-std.net.curl/2.082 (libcurl/7.61.0)
Accept: */*
Content-Type: application/json
Authorization: bearer <redacted>
Content-Length: 27

* We are completely uploaded and fine
< HTTP/1.1 501 Not Implemented
< Cache-Control: private
< Transfer-Encoding: chunked
< Content-Type: application/json
< request-id: 5467b654-afa7-4b63-870b-74a466dcf43d
< client-request-id: 5467b654-afa7-4b63-870b-74a466dcf43d
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Australia Southeast","Slice":"SliceC","Ring":"5","ScaleUnit":"001","Host":"AGSFE_IN_10","ADSiteName":"ASE"}}
< Duration: 503.7228
< Strict-Transport-Security: max-age=31536000
< Date: Thu, 01 Nov 2018 19:51:06 GMT
< 
* Connection #1 to host graph.microsoft.com left intact
```

If I can get samples from all of you in regards to this that would be greatly appreciated.

**Comment by abraunegg** [comment]
@demoii, @SL0RD 
Many thanks, greatly appreciated.

**Comment by abraunegg** [comment]
@SL0RD, @demoii, @brandonkirsch 
https://github.com/OneDrive/onedrive-api-docs/issues/935#issuecomment-440079639

> After doing a little research this is normal behavior for SharePoint and has been since at least SharePoint 2010. When uploading a file that can contain metadata SharePoint will associate some metadata from the library the file is uploaded to directly in the file. Office files are probably the most typical files where this will happen but it's not unreasonable to assume that this will happen for other rich file types as well.
> 
> Since basic text files don't have in-file metadata they don't see this behavior.
> 
> If you're syncing files to a SharePoint document library using the sync client the initial sync will have the enriched file sync'ed rather than the original.

So it appears that this is a 'feature' of SharePoint to have your files 'modified & enriched' after upload without you asking or requesting.

The workaround here is to create a new flag - something like `--disable-upload-validation` so that when you are uploading a file to SharePoint & SharePoint is 'enriching' the file for you, the client does not generate an error because the 'upload' size does not match the file size.

Unfortunately I cannot see any workaround this without having a new flag to pass in as the modification is beyond my control.

**Comment by demoii** [comment]
hey @abraunegg  
Thanks for investigating. How do we put the flag `--disable-upload-validation` into our upload?

**Comment by abraunegg** [comment]
@demoii 
> How do we put the flag `--disable-upload-validation` into our upload?

I will have to write a patch that adds this as a new feature. Will look at that over the next few days.

Alternatively you could also discuss with Microsoft as to why they are modifying / enriching your files after you upload them - as I suspect you would want your file to be an exact copy of what you uploaded, not something new or different.

**Comment by abraunegg** [comment]
@SL0RD, @brandonkirsch, @demoii 
Can you please help test the latest version of PR 206?

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/206/head:pr206
git checkout pr206
make
sudo make install
```

To bypass the upload validation to SharePoint, you need to add in the following flag:

```
onedrive --synchronize --verbose --disable-upload-validation
```

Please can you test against your SharePoint systems that were modifying files after upload

**Comment by demoii** [comment]
> Please can you test against your SharePoint systems that were modifying files after upload

@abraunegg I've tested the run after fetching pr206, it's working well on our server. Logs are captured below. Is there any way that I can use `--disable-upload-validation` by default on a server? 
 
`
c.wu@cerebro:~$ onedrive --synchronize --verbose --disable-upload-validation
Loading config ...
Using Config Dir: /home/c.wu/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/c.wu/OneDrive
Initializing the Synchronization Engine ...
Account Type: documentLibrary
Default Drive ID: b!n03Ucfe_aUGSivD9rOyobCxhTh9VtTRJkHtmlCgV6FfzOfpNPkgYSLDC7V-4X2nR
Default Root ID: 01JY73QJ56Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1071876971988
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 01JY73QJ56Y2GOVW7725BZO354PWSELRRZ
...
Uploading new items of .
Uploading file ./GSAX/chen_test/APAC - Weekly for testing.pptx ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:
 done.
WARNING: Uploaded file size does not match local file - skipping upload validation
Remaining free space: 1071875914071
Applying changes of Path ID: 01JY73QJ56Y2GOVW7725BZO354PWSELRRZ
`

**Comment by abraunegg** [comment]
@demoii 
Many thanks for the confirmation that the PR is working as intended.

A few notes of interest here:
> Account Type: documentLibrary

It looks like I will need to add this account type to be handled as a 'business' account rather than not being handled correctly for a few things.

> Is there any way that I can use --disable-upload-validation by default on a server?

So .. this is possible, and this ties into the above point. What could be done is that for account types of `documentLibrary` the flag `--disable-upload-validation` could automatically be set to true - thus, 'enabled by default' for accounts of that type.

**Comment by SL0RD** [comment]
I have rebuilt with the new PR and it seems to be working. I will let you know if i have any more issues.

Can we expect any more help on this from Microsoft?
