### ISSUE TITLE
Feature Request: Support of onedrive "personal vault" feature

### ISSUE THREAD

**Issue by SvenAbels** [abraunegg/onedrive#2053]
### Is your feature request related to a problem? Please describe.

OneDrive provides a "personal vault", which is accessible under Windows and MacOS and via the mobile apps and the4 web UI. It would be great to provide a way for accessing it.

### Describe the solution you'd like

A possibility to open the "personal vault" folder of OneDrive

### Describe alternatives you've considered

Accessing it via a webbrowser

### Additional context

see https://www.microsoft.com/en-us/microsoft-365/onedrive/personal-vault

**Comment by abraunegg** [comment]
@SvenAbels 
Unfortunatly the OneDrive API does not support accessing this - so the question on supporting the Personal Vault via the API needs to be asked to Microsoft. 

There is nothing that can be done with this client until the API supports access.

**Comment by SvenAbels** [comment]
OK, thanks for the feedback. LEt'S hope that Microsoft adds support to their API in the future

**Comment by abraunegg** [comment]
Closing this issue as the MS Graph API needs to support this capability first.

Please raise your request to Microsoft.
