### ISSUE TITLE
Files with client name

### ISSUE THREAD

**Issue by NivGelbermann** [abraunegg/onedrive#207]
I have this client running on my Ubuntu Budgie laptop, while my main computer runs the regular Windows 10 Onedrive client.
I can't find the pattern in whice this happens, but sometimes files in my synced folder are duplicated, and the laptop name is added to the end of the file name (e.g. for file 'somefile.txt', another is created, 'somefile-laptop.txt'.
This is a repeating issue - for example, this morning I deleted the duplicate 'somefile-laptop.txt' file from my Windows computer, only to have it duplicated **twice more** when syncing the Linux computer, under the names 'somefile-laptop.txt', 'somefile-laptop-2.txt', 'somefile-laptop-3.txt'.

**Application and Operating System Details:**
- OS: Linux thinkpad 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Application version: onedrive v2.0.2-1-ga491620
- OneDrive Account Type: Business 
- DMD or LDC compiler version: both not installed

**Complete Verbose Log Output**
I just repeated the process (deleted files from Windows pc, synced again from Linux pc) in verbose mode, and the issue has not repeated - but it does happen a lot.

I'd greatly appreciate any help since this is the best OneDrive client available to Linux right now.

**Comment by abraunegg** [comment]
> Application version: onedrive v2.0.2-1-ga491620

Given that the current version is v2.14 - can you please upgrade to that version and see if the issue persists?

There are certainly some fixes between v2.0.2 -> v2.14 that would be applicable in the situation that you describe.

Additionally, if you upgraded from the 'skilion' version of the client, ensure that you remove the 'items.sqlite3' as described in the readme file.

**Comment by NivGelbermann** [comment]
I could be missing something... is there a way to upgrade to the current version without removing then installing again?

Also, I removed 'items.sqlite3' just to be safe.

**Comment by abraunegg** [comment]
> I could be missing something... is there a way to upgrade to the current version without removing then installing again?

How did you install the client in the first place as this is currently not clear. If you installed via a package, it would be best to perform an uninstallation of that package & compile from source using the instructions from the readme.

**Comment by NivGelbermann** [comment]
Is there a way to install via a package? I installed by the instruction in the README file.
Anyway, I installed again, and verified I'm running the current version.
I'll update on the state of the issue here in the following days.

**Comment by abraunegg** [comment]
> Is there a way to install via a package?
No - there is no way to install this version via a package unless package maintainers update their packages to use this fork & keep it up to date.

**Comment by abraunegg** [comment]
@NivGelbermann 
Any update ?

**Comment by abraunegg** [comment]
@NivGelbermann 
Closing issue - lack of response. Assuming here that the upgrade from v2.0.2 -> v2.14 master resolved your issue.

**Comment by NivGelbermann** [comment]
Sorry for not updating sooner - didn't have many chances to sync from my laptop until yesterday and today.
So far only one more file with the client name has been created on it's, in about 10-15 syncing attempts with file changes.
So it seems the upgrade solved the problem.
Thanks!!
