### ISSUE TITLE
Feature Request: Make the software easier for users to install and use

### ISSUE THREAD

**Issue by ipimpat** [abraunegg/onedrive#2072]
### Is your feature request related to a problem? Please describe.

Current way of acquiring and installing the software is complicated

### Describe the solution you'd like

1. Create a Snap package for Ubuntu and Flatpak for the Snap haters
2. Merge external gui enhancements, so everything is shipped at once in working condition

### Describe alternatives you've considered

Not using the software?

**Comment by abraunegg** [comment]
@ipimpat 
> Current way of acquiring and installing the software is complicated

Completely disagree here given that it is packaged and provided for many distributions already - and for Ubuntu, you have the OpenSuSE Build Service to install a package from.


Additionally, Snap and Flatpack are for GUI applications, this is a CLI application.

Furthermore, when this was last investigated, the configuration file paths that the application uses (`~/.config/onedrive/`) was incompatible with their requirements for Snap and Flatpack

I will not be progressing this request.
