### ISSUE TITLE
Local deletion will not be detected with default config file

### ISSUE THREAD

**Issue by priv** [abraunegg/onedrive#208]
### Bug Report Details ###
**Describe the bug**
I want to synchronize a second account, but it failed to detect local deletion.
Could be a glitch in matching rules.  Maybe it is treated as regexp in somewhere of the code and ignored all files?

**Application and Operating System Details:**
- Linux alvin-BM1AF 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Ubuntu 18.04 Desktop
- Application version: onedrive v2.1.4-4-g79d86e0
- OneDrive Account Type: personal
- DMD64 D Compiler v2.082.1

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. create a new confdir in ~/.config
2. copy default config and change sync_dir
3. Add a new file
4. do synchronize, it will upload to the server
5. remove this file
6. do synchronize, nothing happens
7. change skip_file line from `skip_file = ".*|~*"` to `skip_file = "~*"`
8. do synchronize, file deletion is detected and synchronized.

**Complete Verbose Log Output**
```
alvin@alvin-BM1AF:~/priv$ touch 555
alvin@alvin-BM1AF:~/priv$ onedrive -v --synchronize --confdir="~/.config/priv"
Loading config ...
Using Config Dir: /home/alvin/.config/priv
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alvin/priv
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 7bb9296166b8b6e3
Default Root ID: 7BB9296166B8B6E3!153
Remaining Free Space: 5368311037
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 7BB9296166B8B6E3!153
Uploading differences of .
Processing root
Uploading new items of .
Uploading file ./555 ... done.
Remaining free space: 5368311037
Applying changes of Path ID: 7BB9296166B8B6E3!153
alvin@alvin-BM1AF:~/priv$ rm 555
alvin@alvin-BM1AF:~/priv$ onedrive -v --synchronize --confdir="~/.config/priv"
Loading config ...
Using Config Dir: /home/alvin/.config/priv
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alvin/priv
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 7bb9296166b8b6e3
Default Root ID: 7BB9296166B8B6E3!153
Remaining Free Space: 5368311037
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 7BB9296166B8B6E3!153
Uploading differences of .
Processing root
Uploading new items of .
Applying changes of Path ID: 7BB9296166B8B6E3!153
```
change `skip_file` line here
```
alvin@alvin-BM1AF:~/priv$ vim ~/.config/priv/config
alvin@alvin-BM1AF:~/priv$ onedrive -v --synchronize --confdir="~/.config/priv"
Loading config ...
Using Config Dir: /home/alvin/.config/priv
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alvin/priv
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 7bb9296166b8b6e3
Default Root ID: 7BB9296166B8B6E3!153
Remaining Free Space: 5368311037
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 7BB9296166B8B6E3!153
Uploading differences of .
Processing root
The directory has not changed
Processing Getting started with OneDrive.pdf
The file has not changed
Processing Documents
The directory has not changed
Processing Pictures
The directory has not changed
Processing 555
The file has been deleted locally
Deleting item from OneDrive: 555
Uploading new items of .
Applying changes of Path ID: 7BB9296166B8B6E3!153
```
**Other Information**
I see monitor mode is still detecting deletions.

**Comment by abraunegg** [comment]
I dont beleive that that this is a program error, rather than an issue with the default config:

> 2. copy default config and change sync_dir

When I look at the default config file & compare the the defaults used when 'no' config file is present there is a discrepancy:

**code:**
```
setValue("skip_file", "~*");
```

**config file:**
```
skip_file = ".*|~*"
```

What needs to happen is the default config file (which you really don't need to use unless changing the options) needs to be updated to reflect what the code defaults are doing.

**Comment by priv** [comment]
Hi,
I think you're correct.

branch Issue-#208 tested.
It runs without problems.

Thanks

**Comment by abraunegg** [comment]
PR #210 merged
