### ISSUE TITLE
Ignore files by size

### ISSUE THREAD

**Issue by VoidStardust** [abraunegg/onedrive#213]
I hope there would be more Additional Configuration Option, such as

skip_size: any files that has size larger than your setting will be skipped during sync

Example: skip_size = 300                            //with the unit mb
Files has size larger than 300 mb will be skipped during sync

Thanks for your contribution!!!

**Comment by abraunegg** [comment]
Thanks for the feature request, PR / code submissions welcome

**Comment by abraunegg** [comment]
PR #517 merged which implements this feature
