### ISSUE TITLE
Change location of onedrive.log

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [abraunegg/onedrive#216]
There seems to be no command line option or config file option to change where the logfile gets created. Having onedrive.log be created inside the root of your homefolder is very ugly, and shouldn't be the default, nor be hardcoded.

**Comment by AlmightyFloppyFish** [comment]
Closed because issue already exists #212 

oops

**Comment by abraunegg** [comment]
> Having onedrive.log be created inside the root of your homefolder is very ugly, and shouldn't be the default

FYI the default is not the home folder. The default is `/var/log/onedrive` for which you need to set applicable permissions to. If you do not set the permissions, then yes - it writes to your home folder.

**Comment by AlmightyFloppyFish** [comment]
Ah that helps, i was just about to recompile with the path moved in source code so glad i saw this in time.
