### ISSUE TITLE
Upload to official Ubuntu repositories

### ISSUE THREAD

**Issue by Uldiniad** [abraunegg/onedrive#219]
Since skilion seems to have abandoned his repo, I was wondering if you'd consider asking to replace him as the maintainer and upload your latest release as an update?
(I apologize if this was already asked, I searched the issues but did not find a similar request)

**Comment by abraunegg** [comment]
I have already reached out to most distro package maintainers to suggest this. Most are reluctant to do so as there has been 'no official communication' regarding the ongoing development status of the 'skilion' version.

Specifically for Ubuntu - there are these entries:

https://bugs.launchpad.net/ubuntu/+source/onedrive

I suggest reaching out to the package maintainers and have that discussion.
