### ISSUE TITLE
Handle invalidRequest from API (PR #206 related)

### ISSUE THREAD

**Issue by rlanore** [abraunegg/onedrive#221]
**Describe the bug**
If you put a bad driveId into config nothing thrown but assertion failure occur

**Application and Operating System Details:**
- OS: Linux onedrive 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u5 (2018-09-30) x86_64 x86_64 x86_64 GNU/Linux
- Are you using a headless system (no gui) or with a gui installed? No
- Application version: v2.1.4-9-gfdb7082
- OneDrive Account Type: Business
- DMD compiler: dmd-2.082.1

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. git checkout Issue-#205
2. put into config
```
drive_id = "TOTO123456"
```
3. launch monitor
```
onedrive --monitor --verbose
```

Application Log Output:
```
onedrive --monitor --verbose
Loading config ...
Using Config Dir: /root/.config/onedrive
Initializing the OneDrive API ...
Use drive Id: TOTO123456
Opening the item database ...
All operations will be performed in: /root/OneDrive
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 10
Monitor directory: .
Syncing changes from OneDrive ...
RLA: driveId
RLA: rootId
Applying changes of Path ID: 
core.exception.AssertError@src/itemdb.d(346): Assertion failure
----------------
??:? _d_assertp [0x88e39495]
src/itemdb.d:347 immutable(char)[] itemdb.ItemDatabase.getDeltaLink(const(char)[], const(char)[]) [0x88e06398]
src/sync.d:364 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x88e25c17]
src/sync.d:226 void sync.SyncEngine.applyDifferences() [0x88e2558c]
src/main.d:443 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x88e0a68e]
src/main.d:364 _Dmain [0x88e0a129]
```

**Comment by abraunegg** [comment]
@rlanore 
As this is an issue PR #206, I will put this on the back burner for the moment as there is a OneDrive API blocker for that PR being merged. When I merge PR #206 I will look at this before the merge.

**Comment by abraunegg** [comment]
Commit https://github.com/abraunegg/onedrive/pull/206/commits/a48b6b18d89e2f509cf00976a4375401f4b1df6f in PR #206 resolves this issue
