### ISSUE TITLE
Choose what directories you want to sync

### ISSUE THREAD

**Issue by lhorace** [abraunegg/onedrive#230]
**Is your feature request related to a problem? Please describe.**
My feature request isn't a problem related precisely however, when opting to sync only one folder from your OneDrive account. The `skip_files` directive can end up being ridiculously long and not very maintainable friendly. I'm aware of `--single-directory` but requires the folder to exists on the file system first before hand.

**Describe the solution you'd like**
A more broad feature would be to be able to adapt all command line arguments into the `config` file itself. I can't think of similar programs atm that does this. However, I think, code maintainability wise, it would be much better than having different code for parsing the `config` file. You can later add new command arguments at will.

`single_directory` or `single-directory` or `only-these-directories`

**Describe alternatives you've considered**
I don't quite understand the context of this question regarding my feature request.

**Additional context**
None, feel free to ask me any questions.

**Comment by abraunegg** [comment]
@lhorace 
Re-reading this again, and I think this is already in the client today:

* skip_file = skip any file that matches 
* skip_dir = skip any directory that explicitly matches (PR #388)
* sync_list = **ONLY* sync these directories, exclude everything else

Can you clarify your requirement here, as potentially this is a documentation update to ensure this is clearly understood.

**Comment by lhorace** [comment]
I'm bit busy right now, but sync_list seems like what I'm looking far.

**Comment by abraunegg** [comment]
@lhorace 
No problem. When you get time, the relevant readme section is https://github.com/abraunegg/onedrive#selective-sync

**Comment by abraunegg** [comment]
Closing this case as question answered

**Comment by lhorace** [comment]
Sorry it took this long to test, sync_list is working albeit skip_dir isn't working as expected. 

```
onedrive version                    = v2.2.6-4-g99c0267
Config path                         = /home/spawn/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/spawn/Cloud/OneDrive
Config option 'skip_dir'            = *.metadata*
Config option 'skip_file'           = ~*
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = true
sync_list contents:
LHProjects
```
Folders/Directories with `*.metadata*` in their name still get uploaded irregardless though I suspect that's perhaps because that folder exists already in the cloud.

Cheers

**Comment by abraunegg** [comment]
@lhorace 
As you 'updated' your configuration - did you perform a `onedrive --synchronize --resync` as required?

**Comment by lhorace** [comment]
Negative on 'update', fresh install and move 'sync_dir' to new partition and recreated the config by hand. Yes on `onedrive --synchronize --resync`, in fact I ran multiple runs of `onedrive --synchronize --resync --dry-run`, in end, I just fallback to removing local copies of '*.metadata*' folders.

**Comment by abraunegg** [comment]
@lhorace 
OK - going through that change, originally it was expecting an 'explicit' path match to match in order to skip. This has been updated in PR #418
```
[alex@centos7full OneDrivePersonal]$ tree -a .
.
├── asdf
├── blah
├── LHProjects
│   ├── file.txt
│   └── sub_dir1
│       └── .metadata_skip
│           └── file2.txt
└── qwer

6 directories, 2 files
[alex@centos7full OneDrivePersonal]$
```
```
[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-personal' --display-config
onedrive version                    = v2.2.6-5-g58c2805
Config path                         = /home/alex/.config/onedrive-personal
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/alex/OneDrivePersonal
Config option 'skip_dir'            = *.metadata*
Config option 'skip_file'           = ~*
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = true
sync_list contents:
LHProjects
```

Expectation: .metadata_skip will be skipped

```
(dmd-2.083.0)[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose --dry-run
DRY-RUN Configured. Output below shows what 'would' have occurred.
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-personal
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
OneDrive Client requested to create remote path: ./LHProjects
The requested directory to create was not found on OneDrive - creating remote directory: ./LHProjects
Successfully created the remote directory ./LHProjects on OneDrive
OneDrive Client requested to create remote path: ./LHProjects/sub_dir1
OneDrive Client requested to create remote path: ./LHProjects
The requested directory to create was not found on OneDrive - creating remote directory: ./LHProjects
Successfully created the remote directory ./LHProjects on OneDrive
The requested directory to create was not found on OneDrive - creating remote directory: ./LHProjects/sub_dir1
Successfully created the remote directory ./LHProjects/sub_dir1 on OneDrive
Skipping item - excluded by skip_dir config: ./LHProjects/sub_dir1/.metadata_skip
Uploading new file ./LHProjects/file.txt ... done.
Remaining free space: 5368709115
Skipping item - path excluded by sync_list: ./blah
Skipping item - path excluded by sync_list: ./asdf
Skipping item - path excluded by sync_list: ./qwer
Applying changes of Path ID: 66D53BE8A5056ECA!101
(dmd-2.083.0)[alex@centos7full onedrive]$ 
```

**Comment by abraunegg** [comment]
@lhorace 
Can you please help validate the updated master codebase please

**Comment by lhorace** [comment]
I'll see if I could test the fix in a few hours.

Cheers

**Comment by abraunegg** [comment]
@lhorace 
Any update?

**Comment by lhorace** [comment]
Sorry, I completely forgot about it that day, eat dinner, and will work on it after wards!

**Comment by lhorace** [comment]
LGTM
