### ISSUE TITLE
can't upload 100Gb directory with subdirectories

### ISSUE THREAD

**Issue by kurokirasama** [abraunegg/onedrive#236]
### Bug Report Details ###
**Describe the bug**

I'm trying to upload a folder, so i put it in my onedrive directory. The log says it's uploaded but nothing appears on the web, even though it recalculates my available free space. I restarted the onedrive app several times and it seem it tries to upload again, so I end ed up with negative available space.
I created an empty file and was successfully uploaded. 
I created an empty directory and was uploaded.

**Application and Operating System Details:**
- OS: Linux lgomezOpenWorld 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 18.04 with GNOME Shell 3.28.3
- Application version: onedrive 2.1.3-2-gd1d3c8a
- Onedrive Bussiness account
- DMD64 D Compiler v2.080.1
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```
onedrive --synchronize --verbose <any of your other needed options>
```
[log.7z (there is sensitive information here, so please ask for the password to kurokirasama@gmail.com)](https://yadi.sk/d/UsHKx9Id6VLDvQ)

**Comment by abraunegg** [comment]
Please can you retest with:
* building client with latest master & latest dmd release

**Comment by kurokirasama** [comment]
hello, i did what you suggested and now it seems to be uploading just fine. Thanks!
