### ISSUE TITLE
File renames which clobber target are not correctlly synced

### ISSUE THREAD

**Issue by norbusan** [abraunegg/onedrive#249]
### Bug Report Details ###
On Windows the application I used renamed a file from `Japan.gdb` to `Japan.gdb.old_backup`, overwriting the previous `Japan.gdb.old_backup`, and saved the new version as `Japan.gdb`. These changes are synced to the OneDrive cloud. After this I switch to Linux and run the current onedrive.

If I run onedrive on the Linux side, conflicting copies are found: Part of the full `--verbose` log is as follows:
```
Loading config ...
Using Config Dir: /home/norbert/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/norbert/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: XXXXXXXX
Default Root ID: XXXXXXXX!126
Remaining Free Space: 1014154749476
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: XXXXXXX!126
Moving GpsMaps/Kashmir3D-Data/Japan.gdb to GpsMaps/Kashmir3D-Data/Japan.gdb.old_backup
The destination is occupied, renaming the conflicting file...
Downloading file GpsMaps/Kashmir3D-Data/Japan.gdb ...
Downloading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:10
Uploading differences of .
Processing root
.... (many many unchanged files)
Processing Japan.gdb.old_backup
The file has been deleted locally
Deleting item from OneDrive: GpsMaps/Kashmir3D-Data/Japan.gdb.old_backup
Processing Japan.gdb
The file has not changed
...
Uploading new items of .
Uploading file ./GpsMaps/Kashmir3D-Data/Japan.gdb-bulldog.old_backup ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:10
 done.
Remaining free space: 1014125868333
```
The problem seems that the cloud "move" which also clobbered the destination is not correctly reproduced.

**Describe the bug**
The rename/move should be correctly handled and no new file be created.

**Application and Operating System Details:**
- OS: Debian/unstable `Linux bulldog 4.19.5 #82 SMP Wed Nov 28 10:32:16 JST 2018 x86_64 GNU/Linux`
- Application version: 2.2.0 (built from the released source code)
- OneDrive Account Type: normal user account
- `LDC - the LLVM D compiler (1.12.0): based on DMD v2.082.1 and LLVM 6.0.1`

**Comment by norbusan** [comment]
I guess that has to do with the open `TODO` in `sync.d:743`
```
            // handle changed name/path
            if (oldPath != newPath) {
                log.log("Moving ", oldPath, " to ", newPath);
                if (exists(newPath)) {
                    // TODO: force remote sync by deleting local item
                    log.vlog("The destination is occupied, renaming the conflicting file...");
                    safeRename(newPath);
                }
                rename(oldPath, newPath);
            }
```

**Comment by abraunegg** [comment]
@norbusan 
Correct - corner edge case that needs fixing.

**Comment by norbusan** [comment]
The algorithmic solution would be

- check whether the move target has been changed locally
- if yes: `safeRename` and upload as conflicting copy
- if no: simply `rename`

It is interesting that after the above sync, the file `Japan.gdb.old_backup` has disappeared completely and only the local copy seems to remain. This shouldn't happen I guess. What should happen is that the version from the cloud is saved as `Japan.gdb.old_backup` and the local copy renamed to `Japan.gdb-bulldog.old_backup`.

**Comment by abraunegg** [comment]
@norbusan 
Feel free to tackle a fix & submit a PR. I am rather snowed under here work wise at the moment.

**Comment by norbusan** [comment]
Hi @abraunegg 
I have adjusted the code according to the following diff:
```
--- a/src/sync.d
+++ b/src/sync.d
@@ -740,9 +740,22 @@ final class SyncEngine
                        if (oldPath != newPath) {
                                log.log("Moving ", oldPath, " to ", newPath);
                                if (exists(newPath)) {
-                                       // TODO: force remote sync by deleting local item
-                                       log.vlog("The destination is occupied, renaming the conflicting file...");
-                                       safeRename(newPath);
+                                       Item localNewItem;
+                                       if (itemdb.selectByPath(newPath, defaultDriveId, localNewItem)) {
+                                               if (isItemSynced(localNewItem, newPath)) {
+                                                       log.vlog("Destination is in sync and will be overwritten");
+                                               } else {
+                                                       // TODO: force remote sync by deleting local item
+                                                       log.vlog("The destination is occupied, renaming the conflicting file...");
+                                                       safeRename(newPath);
+                                               }
+                                       } else {
+                                               // to be overwritten item is not already in the itemdb, so it should
+                                               // be synced. Do a safe rename here, too.
+                                               // TODO: force remote sync by deleting local item
+                                               log.vlog("The destination is occupied by new file, renaming the conflicting file...");
+                                               safeRename(newPath);
+                                       }
                                }
                                rename(oldPath, newPath);
                        }
```
with that I get nearly the correct result:
```
Syncing changes from OneDrive ...
Applying changes of Path ID: F528DE195E4735F4!126
Moving mydoc.txt to mydoc.txt.backup
Destination is in sync and will be overwritten
```

But then there is hickup ...
```
Deleting item mydoc.txt.backup
```

It seems that the changes obtained contain:

  - the deletion of mydoc.txt.backup
  - the renaming of mydoc.txt to mydoc.txt.backup

but the deletions are executed after the other things have been done, which thus breaks correctness.

I thought about moving the deletions to a different place, but that is not trivial, and I am not sure whether some other parts are influenced by that.

Do you ave any ideas?

**Comment by abraunegg** [comment]
Around line 505 there is the following:
```
// There are valid changes
				foreach (item; changes["value"].array) {
```

You can add below that:

```
writeln("OneDrive Change: ", item);
```

Which will show you each item in the changes array as it is processed.

What you could do is sort the changes array before it is iterated to process local file / folder deletes 'first', but this would potentially mean bubble sorting & creating a new array to pass in - have not looked this this very close.

**Comment by norbusan** [comment]
Thanks, done this. The order of changes sent from the server is:

- init stuff
- rename
- delete

first change:
```
{
   "fileSystemInfo" : {
      "lastModifiedDateTime" : "2009-05-13T11:13:35.46Z",
      "createdDateTime" : "2009-05-13T11:13:34.923Z"
   },
   "name" : "root",
   "eTag" : "aRjUyOERFMTk1RTQ3MzVGNCExMjYuMQ",
   "@odata.type" : "#microsoft.graph.driveItem",
   "cTag" : "adDpGNTI4REUxOTVFNDczNUY0ITEyNi42MzY3OTA1MjA1ODYxMzAwMDA",
   "parentReference" : {
      "id" : "XXXXXX!0",
      "driveType" : "personal",
      "driveId" : "YYYYYYY",
      "path" : "/drive/root:"
   },
   "root" : {},
   "id" : "XXXXXXX!126",
   "folder" : {
      "childCount" : 0,
      "view" : {
         "sortOrder" : "ascending",
         "viewType" : "thumbnails",
         "sortBy" : "name"
      }
   }
}
```

second change
```
{
   "parentReference" : {
      "driveId" : "YYYYYYY",
      "id" : "XXXXXXX!126",
      "driveType" : "personal",
      "name" : "root:",
      "path" : "/drive/root:"
   },
   "id" : "XXXXXXX!31259",
   "name" : "mydoc.txt.backup",
   "fileSystemInfo" : {
      "lastModifiedDateTime" : "2018-11-29T01:32:00Z",
      "createdDateTime" : "1970-01-01T00:00:00Z"
   },
   "file" : {
      "hashes" : {
         "sha1Hash" : "5B615C70DDFF2375C926AC85DB7C480873CF81D2"
      },
      "mimeType" : "application/octet-stream"
   },
   "eTag" : "aRjUyOERFMTk1RTQ3MzVGNCEzMTI1OS4y",
   "@odata.type" : "#microsoft.graph.driveItem",
   "cTag" : "aYzpGNTI4REUxOTVFNDczNUY0ITMxMjU5LjI1Nw"
}
```

third change
```
{
   "name" : "mydoc.txt.backup",
   "deleted" : {
      "state" : "softDeleted"
   },
   "@odata.type" : "#microsoft.graph.driveItem",
   "id" : "XXXXXXX!31260",
   "file" : {},
   "eTag" : "aRjUyOERFMTk1RTQ3MzVGNCEzMTI2MC4x",
   "parentReference" : {
      "driveId" : "YYYYY",
      "id" : "XXXXXXX!126",
      "driveType" : "personal"
   }
}
```

I think I now know what is the problem, but please correct me (never programmed D nor read OneDrive API docs till today)

- the rename action preserves the `id` according to [Adressing items](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/addressing-driveitems) under ID based adressing:

  > Renaming or moving the item will not change the item's ID.

  in our case this is XXXXX!31259

- the delete action deletes XXXXX!31260, despite the fact that the `id` connected to this very path is now XXXXX!31259 instead of 31260.

Do you agree with this assessement? If yes, I look into how this can be fixed.

**Comment by norbusan** [comment]
Ahh, that changed fixed renames but broke deletions ... investigating.

**Comment by abraunegg** [comment]
@norbusan 
Many thanks for your hard work, analysis and fix :) greatly appreciated :)

Looking through the code changes now. Can you confirm that the fixes you propose in your PR resolves your issue?

**Comment by abraunegg** [comment]
PR #252 merged
