### ISSUE TITLE
Feature request: Minimal mode

### ISSUE THREAD

**Issue by Popa21** [abraunegg/onedrive#251]
As seen in https://github.com/skilion/onedrive/pull/435#issuecomment-442345722, some people are still using the skilion client because of its simplicity. I like the new features, but it could be an idea to have an minimal branch of the client, that has still the patches of the main branch, but only contains a onedrive client without additional features (bsp. log rotate), only the features that it nedds for synchronization are included in this version. This could maybe an good option for people, that still want the bugfixes of this repository, but don't want the more features provided.

**Comment by adudek** [comment]
Is there anything that prevents you from using docker image as described in https://github.com/abraunegg/onedrive/pull/241? This docker image provides only sync functionality as stated. Also it gives you benefit of restarting upon error and multiple accounts setup (one per container)

**Comment by Popa21** [comment]
I don't have any problems with the additional features (I like them), but as referenced from above some other people do. But I forgot about the docker image, so this is already a option.

**Comment by abraunegg** [comment]
What I would like to understand however is this - the only "real" difference between the two is:
* Skilion - runs / sync's without any options
* Mine - requires either `--monitor` or `--synchronize` to run to ensure you don't accidently run the program & delete data

All other switches / options are either bug fixes or feature requests that have been implemented. None of those additional switches impact or have any effect if they are not used.

Unsure what else could be called 'minimal' here .. if there is a problem that the client looks / feels like 'bloatware' certainly would like to understand that.
