### ISSUE TITLE
monitor mode: don't fail starting up without network

### ISSUE THREAD

**Issue by norbusan** [abraunegg/onedrive#257]
**Is your feature request related to a problem? Please describe.**

If running via systemd and being offline, onedrive dies with "No network connection to Microsoft OneDrive Service" and the systemd reset counter is increased:
```
Scheduled restart job, restart counter is at 21.
```

This is by itself not a real problem, but I somehow dislike these permanent restarts and thought about whether we can deal with that more gracefully, in the same way we deal now with missing network during monitor mode based sync.

**Describe the solution you'd like**
As long as there is a token available, go as far as possible, and then retry in the usual intervals to connect and sync.

I will look into the code.

**Comment by abraunegg** [comment]
@norbusan 
No problem - thanks

**Comment by abraunegg** [comment]
This should be resolved by PR #266 - can you confirm?

**Comment by norbusan** [comment]
Confirmed, closing.
