### ISSUE TITLE
Support for notifications via libnotify

### ISSUE THREAD

**Issue by norbusan** [abraunegg/onedrive#267]
Add support for notifications via libnotify, which would give nice bubble messages on supported desktop environments.

First (already working!) shot at it at https://github.com/norbusan/onedrive/tree/notifications

**Comment by norbusan** [comment]
Current status:

- notifications are now a compile time option
  use with `make NOTIFICATIONS=1`
- notifications are only shown when running in monitor mode: 
  unfortunately I had to move the monitor setting to a global variable, don't like it but hmm, no better idea
- only one-time logs and errors are shown as notifications, repeating things (like "Syncing ...") as well as messages that the network is not available are *not* show in 45sec interval

Looks already quite nice, we only need to make sure that the licenses of the two files are ok. One is fine, but the `dnotify.d` does not have any license statement.

**Comment by norbusan** [comment]
(going out for a run helps thinking straight!)

The code at the moment is not nice. I will

- move the log/notify functionality into the log modules
- get rid of the global variable, and use a log module initializer

That should make things much clearer ;-)

**Comment by norbusan** [comment]
Concering the license question: I have contacted the author of dnotify.d and he is providing the file under CC0Universal license (see adapted README), so this means license-wise it is all fine now.

**Comment by abraunegg** [comment]
@norbusan 
Certainly looks like an interesting feature set / work that you have done.

> One problem is when starting onedrive service as root via the onedrive@USER mode: here notifications are not shown, out of whatever reason (no idea why).

Potentially this has to do with the the service threads / UID / GID of the application when running via systemd in that fashion - potentially some sort of dbus blocker?

**Comment by norbusan** [comment]
I wait for the offline branch being merged, then rebase/adjust and will open a pull request later. 

The thread/uid/gid is something I will explore at some time ..

**Comment by abraunegg** [comment]
Resolved by PR #270
