### ISSUE TITLE
Option --upload-only does not perform remote delete

### ISSUE THREAD

**Issue by pglez82** [abraunegg/onedrive#272]
### Bug Report Details ###
**Describe the bug**
I have finished uploading my library to one drive using the command:

onedrive --synchronize --upload-only

The only problem is that when I delete a file in local, that file doesn't get deleted on onedrive.

**Application and Operating System Details:**
- OS: 4.4.0-127-generic #153+8.0trisquel2 SMP Tue May 22 10:35:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux. Trisquel 8.
- Are you using a headless system (no gui) or with a gui installed? Console client.
- Application version: onedrive 2.1.3
- OneDrive Account Type: Business. 

DMD64 D Compiler v2.082.0
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright

**To Reproduce**
Synchronize the library with onedrive --synchronize --upload-only
Delete any file in local filesystem.
Synchronize again the library with onedrive --synchronize --upload-only

**Complete Verbose Log Output**
Loading config ...
Using Config Dir: /home/pablo/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /media/DATOS
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: id
Default Root ID: an id
Remaining Free Space: 1038213896353
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from local path only - NOT syncing data changes from OneDrive .$
Uploading differences of .
Processing root
Uploading new items of .

**Comment by abraunegg** [comment]
> Application version: onedrive 2.1.3

Please can ensure you retest using the latest version of the client which is v2.2.1

**Comment by pglez82** [comment]
Sorry, I forgot about updating.

I just compiled again the last version and executed: onedrive --synchronize --upload-only --verbose

I get:

Loading config ...
Using Config Dir: /home/pablo/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /media/DATOS
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: id
Default Root ID: id
Remaining Free Space: 1038213896353
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Processing root
Uploading new items of .

I don't know if the client writes something into the console when it deletes a remote file. Anyway, I have checked in my onedrive account and the deleted file is still there.

**Comment by pglez82** [comment]
> @pglez82
> Also - your initial report is missing what DMD or LDC version you are using to build the client with

I have updated the initial message with the information.

**Comment by abraunegg** [comment]
@pglez82 
I suspect either one of the following is going on:
1. Issues with DMD compiler version
2. Installed copy of the client is still being run vs latest compiled version
3. Local issues with the database


Please can you:
1. Run an uninstall of 'onedrive' & search your local PC for all instances of the client / files etc
2. Remove the local database file 'items.*' from your configuration directory
3. Install / upgrade your DMD to the latest v2.083.0
4. Git clone from the repository master & compile
5. Validate that the version of the client you are running is 'v2.2.1' and that no other 'onedrive' binary can be found in the search path
6. Run the client using the options `--synchronize --upload-only --verbose` as per above
7. Delete a local file
8. Run the client using the options `--synchronize --upload-only --verbose` - the local file should be deleted remotely on OneDrive.

**Comment by pglez82** [comment]
I updated DMD to 2.083.0. I cloned again and compiled the repository. I made sure that I only have v2.2.1 of Onedrive.

I removed the items* files in .config. This goes over all the files again, putting them into my local database. Still, items that I have previously deleted locally are kept in remote.

After synchronizing and regenerating the local database, if now I delete a file and synchronize again, it gets deleted from remote. The problem is that I will have to upload all my library again for it to work and as I have many many files, this is going to take me days again. 

It would be nice that the client would be able to detect changes when rebuilding the database. I will suggest the following steps:
1) synchronize some files to onedrive using --synchronize --upload-only
2) delete a file locally
3) remove the .config/items* files
4) synchronize again to force rebuilding the database using --synchronize --upload-only

The locally deleted file should be deleted from remote.

**Comment by abraunegg** [comment]
> The problem is that I will have to upload all my library again for it to work and as I have many many files, this is going to take me days again.

The client does not work this way.

If the file is 'truely' not on OneDrive, then it will be uploaded to OneDrive. If the file already exists, the metadata is saved to the database.

If you have deleted everything on OneDrive, then restore from your deleted items on OneDrive.

**Comment by pglez82** [comment]
In my case I have some files that exist in Onedrive, but that don't exist any more in local. If I execute:
 
onedrive --synchronize --upload-only

It does not delete the files from remote. If we suppose that I have my local database corrupt and I delete the items* files and execute onedrive --synchronize --upload-only, the files still do not get deleted from remote, so local and remote repositories are different.

What I am saying is that if the database is rebuilt, after executing a synchronize, the local and remote repositories should have the same files.

**Comment by pglez82** [comment]
I don't understand why I have to download the Onedrive state for this. What I expect when I synchronize with upload-only is to see the local and remote folders equal, with the same number of files. This doesn't happen in my case when rebuilding the database (remote files that don't exist in local are not deleted).

Anyway. I can live with this. If I get some free time I will take a look at the code myself. Thanks for the support.

**Comment by abraunegg** [comment]
> I don't understand why I have to download the Onedrive state for this.

Because if you have deleted the local cache the program has no idea what to 'trust' as the source of truth. By default, it treats OneDrive provided data (which you are forcing not to fetch by using --upload-only) as the source of truth.
