### ISSUE TITLE
Feature Request: Permanent Delete on OneDrive

### ISSUE THREAD

**Issue by NovaPixell** [abraunegg/onedrive#2803]
@NovaPixell 
> Is there an option (like on rclone) to enable permanent delete on OneDrive?

Unfortunately no such option exists currently. Please raise a feature request.

Additionally, due to the current development cycle, this will be looked at for some version in v2.5.x and cannot be considered for inclusion in v2.5.0.

**Reference:**
* https://learn.microsoft.com/en-us/graph/api/driveitem-permanentdelete?view=graph-rest-1.0

_Originally posted by @abraunegg in https://github.com/abraunegg/onedrive/discussions/2802#discussioncomment-10645537_

**Comment by abraunegg** [comment]
@NovaPixell

Please can you test PR #2999 that implements your feature request.

First install all the require platform dependencies to build the client on your platforms. Please read https://github.com/abraunegg/onedrive/blob/master/docs/install.md#building-from-source---high-level-requirements and then follow correctly for your platform.

Once this is done, to clone the PR to resolve your issue, you can use a script like the following:
```
#!/bin/bash

PR=2999

rm -rf ./onedrive-pr${PR}
git clone https://github.com/abraunegg/onedrive.git onedrive-pr${PR}
cd onedrive-pr${PR}
git fetch origin pull/${PR}/head:pr${PR}
git checkout pr${PR}

# Configure and Build
./configure --enable-debug --enable-notifications; make clean; make;
./onedrive --version
```

This script will create a local folder called onedrive-pr2999 with the PR version.

To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any other options needed>
```

To install the PR, you will need to perform `sudo make install` to install the PR version to your system.

When running the PR, your version should be: `onedrive v2.5.3-9-ge8a8dfb` or greater.

To activate the new feature, this can ONLY be done from the 'config' file:
```
permanent_delete = "true"
```

The Microsoft OneDrive API for this capability is also very narrow:
| Account Type | API is Supported |
|--------------|------------------|
| Personal     | ❌ |
| Business     | ✔ |
| SharePoint   | ✔ |
| Microsoft Cloud Germany | ✔ |
| Microsoft Cloud for US Government | ❌ |
| Azure and Office365 operated by VNET in China | ❌ |


When running against an unsupported Personal Account the following message will be generated:
```
WARNING: The application is configured to permanently delete files online; however, this action is not supported by Microsoft OneDrive Personal Accounts.
```

When running against a supported account the following message will be generated:
```
WARNING: Application has been configured to permanently remove files online rather than send to the recycle bin. Permanently deleted items can't be restored.
WARNING: Online data loss MAY occur in this scenario.
```

Please can you test and provide your feedback.

**Comment by abraunegg** [comment]
> Im testing rn the feature, seems all okay..
> 
> Anyway, is it correct that each local directory on OneDrive takes twice as much space? For example, a directory on my disk is 2 Gb, on OneDrive 4 Gb

No .. that is something odd which I cant explain for you. 

If this is what you are experiencing, please raise a bug report with Microsoft.

**Comment by NovaPixell** [comment]
> No .. that is something odd which I cant explain for you.

Im using this config

```
enable_logging = "false"
verbose = "0"
sync_dir = "/srv/dev-disk-by-uuid-a3e7c153-0ea5-4785-ba17-615d15177cac/DATI/"
sync_dir_permissions = "750"
sync_file_permissions = "640"
disable_notifications = "true"
local_first = "false"
no_remote_delete = "false"
download_only = "false"
upload_only = "true"
skip_dotfiles = "false"
monitor_interval = "300"
monitor_fullscan_frequency = "12"
rate_limit = "0"
force_http_11 = "true"
ip_protocol_version = "1"
permanent_delete = "true"
```

Anyway the new feature is working well, btw I can’t explain why OneDrive is using double space size. Is a known issue by searching on Google. I’m using OneDrive over Office 365 Business

**Comment by abraunegg** [comment]
RE: online size - one thought is file versions - multiple copies of files based on change - that could account for it potentially.

Thanks for confirmation the PR is working, I will merge this into 'master' in the next day or so.

**Comment by abraunegg** [comment]
Please can you raise a new bug.

Please also help identify if this issue is:
* only with files < 4Mb
* only files > 4Mb
* all files

**Comment by NovaPixell** [comment]
> Please can you raise a new bug.
> 
> Please also help identify if this issue is:
> 
> * only with files < 4Mb
> * only files > 4Mb
> * all files

I think it is relative with all files. Now out of curiosity I am using rclone. In the setup it asks me if I want to disable file versioning (this duplicates the size) only on OneDrive Business

**Comment by abraunegg** [comment]
> I think it is relative with all files. Now out of curiosity I am using rclone. In the setup it asks me if I want to disable file versioning (this duplicates the size) only on OneDrive Business

And that is *not* the right approach ... disabling versioning effectively is giving you data loss.
