### ISSUE TITLE
Provide docker delivery integration

### ISSUE THREAD

**Issue by adudek** [abraunegg/onedrive#281]
Currently supported docker image based on abraunegg branch is pushed manually dogithub repository. Also there is lots of build/run env information required during bug reporting.

Official docker image pull directly from repository CI/CD system can help to reproduce issues and verify used environment. This should help reduce time required for bug triaging (is it code or system/env).

For this to happen alex should provide secrets and env vars for github delivery system in travis. I created github organization (named driveone), that can have multiple users. I will provide dockerhub integration once this is done. Official builds and official docker env should be desired state for this project.

Alternatively trafis.org (or other free build resource provider) could be used and thus builds would be delivered by "unofficial" channel (maintained by me).

**Comment by abraunegg** [comment]
@adudek 
Will provide via email

**Comment by abraunegg** [comment]
@adudek 
Can you send me your email address as it is not in your github profile

**Comment by adudek** [comment]
Verifying from my end: I wrote email to you 2 days ago from gmail address I used with git commit.

**Comment by abraunegg** [comment]
Just responded - it's been a crazy few days here

**Comment by abraunegg** [comment]
@norbusan 
Added github integration to https://cloud.docker.com/u/driveone/repository/docker/driveone/onedrive

It should be building / providing a 'latest' build shortly.

**Comment by abraunegg** [comment]
Closing this as the integration should now be working - will validate with the next few commit's / version release

**Comment by norbusan** [comment]
@abraunegg great thanks a lot. But it would be nice if we only push released versions? Or have one docker `onedrive-dev` for the latest commit, and `onedrive` for the latest release? Is this possible?
