### ISSUE TITLE
More lean / efficient Docker Image

### ISSUE THREAD

**Issue by DerArchivar** [abraunegg/onedrive#282]
Recently, a Dockerfile based on CentOS has been created. First of all, I think that is _really_ awesome, as I personally love to work with Docker containers, too.

Anyway, I highly doubt that basing the image on CentOS is an efficient choice. There is a reason, why the Docker team is preferring and recommending Alpine nowadays. Considering that many people will not necessarily base off of that image and add additional functionality that becomes easier with CentOS, it would be preferable to switch to a more lean base OS, that is also more popular. To state my case, see the size of my recommendations below in comparison to the CentOS base size of 75 MB.

My recommendation would be one of the following (I'll also give a size comparison):
- Ubuntu (32 MB)
- Debian (45 MB) / Debian slim (19 MB)
- Alpine (2 MB)

So, apart from Ubuntu and Debian being much more popular for Docker images, the worst alternative would already save 30 MB == 40%. Switching to Alpine would even save as much as 73 MB, which would be 97.33% smaller.

My personal recommendation would go towards Alpine, as it is being the most prominent one in Docker just for its very efficient design with a very small footprint. If that is not possible or wanted, I would alternatively recommend Ubuntu, as it was the preferred Docker OS before Alpine started to gain a following.

**Comment by adudek** [comment]
I tried using Alpine image but gcc version is missing trace libaries (maybe we could make them optional, but it will require some code updates with precompiler). As of now I deliver build-capable (thus large) containers for contributors to have ability to prepare build system effortlessly without need to mess with their systems.

As for near-future plans I plan on deliver builder-model version based on centos/fedora-atomic, whatever is leaner. I don't plan on supporting ubuntu-based images for now.

**Comment by DerArchivar** [comment]
Thanks for the heads up! Sounds totally plausible and I'm really grateful for your efforts.

Maybe I'll find the time in the next few weeks (when I'm on vacation) to try setting it up in a similar fashion inspired by your current work for Ubuntu / Debian and I'll see if I find a way to make it executable on Alpine as well.

It might not be absolutely necessary, but as I was already thinking about ways to support the project (being it a JavaFX based GUI upon the application or something else), I'd like to tinker on some things that might bring this great effort forward and make it more accessible to the broad public.

**Comment by abraunegg** [comment]
@adudek, @DerArchivar 
Preference here at the moment is to keep using CentOS as this is what I develop & mainly test on.

Does switching the compiler from DMD to LDC for building the client under a container / for a container change the requirement for the trace libraries in any way?

**Comment by adudek** [comment]
@abraunegg changing compiler is worth investigating, do you have any resources on how to change build env?
Problem with Alpine is that musl gcc is used that doesn't provide stacktrace libs and with dynamically linked libraries its impossible to run even already prebuilt image... One option I tried investigating was to statically link binary and place it in Alpine based image, but it took to much effort for something that already works (under CentOS). Maybe this would be good avenue to explore?
1. provide makefile target for statically linked binary
2. use builder model to compile binary inside centos and repackage it into Alpine
WDYT?

**Comment by abraunegg** [comment]
@adudek 
Not for docker builds, but essentially instead of installing DMD to build, use LDC:
```
curl -fsS https://dlang.org/install.sh | bash -s ldc
```
then
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
make DC=/usr/bin/ldmd2
```

Potentially the path to least resistance is most likely build inside CentOS, then repackage for Alpine.

Under CentOS - see if you can build via LDC using 'mock' to rebuild the SRPM from koji as this would also then build automatically under CentOS using LDC & potentially be easier for cross platform repackaging.

**Comment by norbusan** [comment]
@abraunegg 

> Does switching the compiler from DMD to LDC for building the client under a container / for a container change the requirement for the trace libraries in any way?

I am using LDC for the Debian builds and my development, only passing DMD=ldc is enough. The resulting binaries are much smaller compared to ldmd, both before and after stripping. I haven't seen any weird behaviour by now.

**Comment by norbusan** [comment]
I have build a docker image based on Debian buster:slim using ldc2 as compiler. The branch which adds the `Dockerfile.debian` and a line in the `Makefile` how to build it is here: https://github.com/abraunegg/onedrive/tree/norbert/debian-docker
Tested it on my system with a new onedrive account

**Comment by DerArchivar** [comment]
That's awesome, thank you guys for the effort and already elaborating on this! I'm really grateful! The direction this is going is great, but maybe it should really be elaborated to go further towards "packaging". Building it manually for each Docker image each time is definitely possible and not necessarily a big effort, but having prepackaged binaries would in any case lead to a much bigger audience and way easier management of the application on client side. I have the feeling that the project is pretty close to a state where packaging it as RPM and DEB (or SNAP) is not that far away anymore.

Oh, and regarding the remark with the container size, @adudek:
You are totally right in the regard, that it's only the first pull. But you still have the CentOS layer that is being updated (or _should_ be updated) for the future, which - in my case, for example - would mean, that I'm having the entire CentOS image / container only for this sole purpose, as I'm having only Alpine based images for my private server and projects and only Ubuntu based images at work.

Also, which is maybe not a big difference in comparison to Ubuntu and Debian, Alpine is much more lightweight in its execution, too. Meaning that its memory footprint and overall performance is (this is my personal experience and what I've seen in benchmarks so far) better then that of the more "bloated" OS, as Alpine simply has much less background services running per default then any other of the usual Docker OS. Of course you already did target Alpine anyway, so this might not be news to you, but I thought I'd mention it for the sake of making my intentions and reasons for this initial request more clear.

Overall, I can say that this entire request is more of a "nice to have" and "would fit more nicely into _my_ infrastructure". But for the future, I think this would be the way to go to bring this project to the general public more easily, as I believe that there are definitely people who would really appreciate a much more streamlined process of making OneDrive run for their setups.

**Comment by norbusan** [comment]
@DerArchivar a few things, since I guess you have a bit of misconceptions here ...

> state where packaging it as RPM and DEB (or SNAP) is not that far away anymore.

OneDrive is already in Debian in the latest version ... I am also the Debian Maintainer of it ;-)
see https://tracker.debian.org/onedrive

> Also, which is maybe not a big difference in comparison to Ubuntu and Debian, Alpine is much more lightweight in its execution, too. Meaning that its memory footprint and overall performance is (this is my personal experience and what I've seen in benchmarks so far) better then that of the more "bloated" OS, as Alpine simply has much less background services running per default then any other of the usual Docker OS. 

Sorry to correct you, docker images don't run services (normallly). They have one entry point and run one program, that is all. So the memory footprint is the one of the program started. Again, no services since init is not used.

I'm not sure what you are actually trying to achieve? Is it 

- reduce the `docker pull` size?

Or something else? As said, the actual execution is (cum grano salis) the same - Alpine might have a bit smaller footprint due to the musl C library instead of glibc, but this is the only part I see where memory consumption could change.

Please elaborate a bit more ...

**Comment by abraunegg** [comment]
@DerArchivar 
> state where packaging it as RPM and DEB (or SNAP) is not that far away anymore.

Just to aslo add that it is also packaged for RPM - https://koji.fedoraproject.org/koji/buildinfo?buildID=1168814

You can then use that SRPM and via 'mock' rebuild for RHEL, CentOS, Fedora & potentially even other RPM based distro's

**Comment by abraunegg** [comment]
@DerArchivar 
Can you comment on if https://github.com/abraunegg/onedrive/commit/460596dd360d60038455cab5254aab176325bc0d resolves this query for a more lightweight Docker image?

**Comment by abraunegg** [comment]
Closing this case due to the inclusion of https://github.com/abraunegg/onedrive/commit/460596dd360d60038455cab5254aab176325bc0d
