### ISSUE TITLE
Bug: Notification spamming to upgrade client

### ISSUE THREAD

**Issue by fabioraitz** [abraunegg/onedrive#2862]
### Describe the bug

Onedrive is spamming notification to upgrade its client.
I've followd instructions [here](https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md) but didn't resolve, the version for Mint 21.3 (Ubuntu 22.04) still on 2.5.1+1-np1+1.1.

### Operating System Details

```shell
Linux Mint 22.3
```

### Client Installation Method

From 3rd Party Source (PPA, OpenSuSE Build Service etc)

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

2.5.1=1-np1+1.1

### What is your OneDrive Application Configuration

```shell
Cannot report, package currently not installed.
```

### What is your 'curl' version

```shell
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.18
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
~/Onedrive
```

### What are all your local file system partition types

```shell
/
```

### How do you use 'onedrive'

default settings, monitoring with systemd service.

### Steps to reproduce the behaviour

issue occurs constantly whenever systemd service is running.

### Complete Verbose Log Output

```shell
Cannot report, package currently not installed.
```

**Comment by horaciohs** [comment]
IMHO this feature is not a bug, but their notification frequency is (more than 100 notification in last minutes; I have to disable notifications.)

**Comment by abraunegg** [comment]
The application only advises once at startup.

It does not spam anything multiple times.

If you are seeing this - then:

* Your client is restarting over and over - some other issue for you to fix
* You are running 100's of clients

This is *not* a but and will *not* be fixed
