### ISSUE TITLE
Makefile:43: recipe for target 'onedrive' failed

### ISSUE THREAD

**Issue by mbkupfer** [abraunegg/onedrive#288]
I have followed the instructions in the readme and got stuck at the make step. I'm getting a make error at this step.  

This seems slightly similar to recipie for target 'onedrive' failed #81, but I have source the dmd environment. 

**Application and Operating System Details:**
- OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
**Linux ubuntu 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux**

- Are you using a headless system (no gui) or with a gui installed?
**No**

- Application version: Output of `onedrive --version` 
**v2.2.1-7-g91aaf91**
obtained via:
```
(dmd-2.083.1)mkupfer@ubuntu:~/onedrive$ cat version 
v2.2.1-7-g91aaf91
```
- OneDrive Account Type
**Enterprise**

- DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
**dmd --version==v2.083.1**

**Complete Verbose Log Output**
```
(dmd-2.083.1)mkupfer@ubuntu:~/onedrive$ make
dmd -w -g -ofonedrive -O -L-lcurl -L-lsqlite3  -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d
unable to fork: Cannot allocate memory
Makefile:43: recipe for target 'onedrive' failed
make: *** [onedrive] Error 255
```

### Bug Report Checklist ###
- [X] Detailed description
- [X] Reproduction steps (if applicable)
- [X] Verbose Log Output

**Comment by adudek** [comment]
Hello @mbkupfer, this error is typical for building on memory constrained system, make sure you have 1GB free RAM before building onedrive. If its workstation, then close all user applications or extend swap partition for purpose of building this package.

**Comment by mbkupfer** [comment]
Ah I see, thanks for the pointer. I'm on a virtual machine running on vmware. I will look into their documentation on how to do this as I'm really anxious to get business onedrive working in linux.

**Comment by abraunegg** [comment]
Hi @mbkupfer 
As per above & as per readme, you need 1GB of memory & 1GB of swap space in order to compile with DMD. Unsure if this changes if you use LDC as the compiler

**Comment by abraunegg** [comment]
> I'm on a virtual machine running on vmware. I will look into their documentation on how to do this as I'm really anxious to get business onedrive working in linux

The only thing to check VMware wise is to look at the virtual machine configuration to ensure that 1GB of memory has been allocated. Swap space would be 'how' the local OS has been installed in the virtual machine & have nothing to do with the VMware configuration

**Comment by mbkupfer** [comment]
This ended up working after closing all the browser windows. I highly suspect this has to do with github's website as it's always causing my RaspberryPi to crash.  

Thanks again for all your assistance and making this work on Linux. It's truly a lifesaver for my workflow.
