### ISSUE TITLE
Removing One Drive key

### ISSUE THREAD

**Issue by felipebraz** [abraunegg/onedrive#29]
Case I decide to Uninstall it, how can I remove or disable the key that I generated in Microsoft on the first run?

**Comment by abraunegg** [comment]
The easiest was to uninstall is to follow these directions:

```
sudo make uninstall
# delete the application state
rm -rf ~/.config/onedrive
```

This will delete the application state / key that you generated.

If you are using the `--confdir` option, substitute `~/.config/onedrive` above for that directory.

If you want to just delete the key, but keep the database:

```
rm -f ~/.config/onedrive/refresh_token 
```
