### ISSUE TITLE
Cooperating and sharing problems

### ISSUE THREAD

**Issue by ain-soph** [abraunegg/onedrive#294]
I'm coding together with my labmates.
We code on our computers, and sync to the servers to run the codes.

I share the folder with my labmate. She adds it to her own onedrive.

When I use this software, I find it works fine on my server account because the shared folder is on my disk. It will sync all files correctly. But for my labmate, her onedrive only contains an empty folder...

It seems the folder actually exists in the owner's onedrive and won't exist in the others' onedrive like Dropbox does.

Is there any method to achieve that feature? Is it possible to sync sharing folders? Windows Onedrive Client can do this actually.

I can only use rsync right now.

**Comment by abraunegg** [comment]
Hi,

The description of the problem above is not very clear as to what your problem actually is. Can you help clarify what is going on?

* You have 'onedrive' syncing between your PC and OneDrive service
* You have configured one of the OneDrive folders in your OneDrive account to be a shared folder
* You have given that shared folder 'url' to a colleague to use & access
* The colleague has added the shared folder to their OneDrive account
* The shared folder in your colleague's OneDrive account appears 'empty'

Is this correct?

If this is correct, then it would appear to be a OneDrive account / sharing permissions problem and not a problem with this 'onedrive' client.

**Comment by abraunegg** [comment]
Agreed - for code management and sharing - git is the way to go there, tho the questio remains here re permissions on OneDrive and folder access for data that 'should' be present

**Comment by abraunegg** [comment]
@ain-soph
Any update from you in regards to your situation?

If no update from you in the next 24 hours, this case will be closed due to lack of response.

**Comment by ain-soph** [comment]
Sorry for replying so late. I haven't received any email reminder...

I cannot use git for coding, because we need to save our model and input images, and our neural network models are quite large size.

The problem is :

1. I use my onedrive account, send my lab-mate an sharing folder url.
2. She gets that url and adds it to her own onedrive.
3. She opens her Linux server and use your software to sync.
4. The folder exists in the Onedrive folder, but empty.


If I myself use your software, that folder syncs successfully and the content exists.

I think the reason is that the content only exists on my own onedrive disk.
She gets the sharing folder, but the content is on my disk, not on hers. So the software won't sync.

**Comment by abraunegg** [comment]
Can your colleague, when using the OneDrive web interface, 'see' your shared data? 

Can create a new file / folder on the 'shared' folder through the OneDrive web interface?

**Comment by ain-soph** [comment]
Yes, she can.
She can edit the files inside in windows client by Microsoft.

**Comment by abraunegg** [comment]
Please can you provide verbose log output from your colleague's system:
* onedrive --version
* onedrive --display-config
* onedrive --synchronize --verbose

**Comment by abraunegg** [comment]
@ain-soph
Any update from you in regards to your situation?

If no update from you in the next 24 hours, this case will be closed due to lack of response.

**Comment by abraunegg** [comment]
Closing due to lack of response
