### ISSUE TITLE
Add usage text when missing options

### ISSUE THREAD

**Issue by mbkupfer** [abraunegg/onedrive#295]
**Is your feature request related to a problem? Please describe.**
Using onedrive with no options returns a nicely formatted usage text:
```
$ onedrive

--synchronize or --monitor missing from your command options or use --help for further assistance

No OneDrive sync will be performed without either of these two arguments being present
```

But, this isn't the case for some other inputs. For example, using `--single-directory` or `--get-O365-drive-id` without a value will provide a "missing value" error, but this is then followed by a long and unhelpful dump of code. 

**Describe the solution you'd like**
Strip all code from the error message and just leave it at `Missing value for argument <argument-name>.`

**Describe alternatives you've considered**
N/A

**Additional context**

You can reproduce this using the following commands:
`$ onedrive --get-O365-drive-id`
`$ onedrive --synchronize --single-directory`

Output:
```
object.Exception@/home/mkupfer/dlang/dmd-2.083.1/linux/bin64/../../src/phobos/std/getopt.d(883): Missing value for argument --single-directory.
----------------
<very long dump of unreadable code below>
```

**Comment by mbkupfer** [comment]
Works for me.

**Comment by abraunegg** [comment]
PR #299 merged, closing as resolved
