### ISSUE TITLE
Remove line wraps for the help usage

### ISSUE THREAD

**Issue by mbkupfer** [abraunegg/onedrive#298]
**Is your feature request related to a problem? Please describe.**
Help text is very hard to read since the long lines are wrapping the terminal. I always need to expand my terminal to get rid of the linewrap.

**Describe the solution you'd like**
A column like help text. Instead of the lines wrapping to the beginning of the terminal, we can instead have them break in their own column.

**Additional context**
![image](https://user-images.githubusercontent.com/6313008/50241039-4aa99800-037b-11e9-8043-9154040be19b.png)
![image](https://user-images.githubusercontent.com/6313008/50241094-73ca2880-037b-11e9-84c2-1c625523e555.png)

**Comment by abraunegg** [comment]
@mbkupfer 
You can also use the man page:
```
man onedrive
```

How does that get formatted in the 'default' terminal window?

**Comment by abraunegg** [comment]
> Look's great. Why don't you just add this to the usage text instead of `--help`?

The formatting of the `--help` is based on the D language functions used to handle input options & output. Will investigate to see if this can be 'fixed', however in a SSH session via putty or other, it does not line wrap, so this issue is more of a 'default terminal options' item for your Linux install which is causing the lines to line wrap.

**Comment by mbkupfer** [comment]
Oh ok. Got it.

**Comment by norbusan** [comment]
What about the following output?
```
Usage: onedrive [OPTION]...

no option        No sync and exit

Options:
  --check-for-nomount 
    Check for the presence of .nosync in the syncdir root. If found, do not perform sync.
  --confdir 
    Set the directory used to store the configuration files
  --create-directory 
    Create a directory on OneDrive - no sync will be performed.
  --destination-directory 
    Destination directory for renamed or move on OneDrive - no sync will be performed.
  --debug-https 
    Debug OneDrive HTTPS communication.
  --disable-notifications 
    Do not use desktop notifications in monitor mode.
  --display-config 
    Display what options the client will use as currently configured - no sync will be performed.
  --download-only -d
    Only download remote changes
  --disable-upload-validation 
    Disable upload validation when uploading to OneDrive
  --enable-logging 
    Enable client activity to a separate log file
  --get-O365-drive-id 
    Query and return the Office 365 Drive ID for a given Office 365 SharePoint Shared Library
  --local-first 
    Synchronize from the local directory source first, before downloading changes from OneDrive.
  --logout 
    Logout the current user
  --monitor -m
    Keep monitoring for local and remote changes
  --no-remote-delete 
    Do not delete local file 'deletes' from OneDrive when using --upload-only
  --print-token 
    Print the access token, useful for debugging
  --resync 
    Forget the last saved state, perform a full sync
  --remove-directory 
    Remove a directory on OneDrive - no sync will be performed.
  --single-directory 
    Specify a single local directory within the OneDrive root to sync.
  --skip-symlinks 
    Skip syncing of symlinks
  --source-directory 
    Source directory to rename or move on OneDrive - no sync will be performed.
  --syncdir 
    Set the directory used to sync the files that are synced
  --synchronize 
    Perform a synchronization
  --upload-only 
    Only upload to OneDrive, do not sync changes from OneDrive locally
  --verbose -v+
    Print more details, useful for debugging (repeat for extra debugging)
  --version 
    Print the version and exit
  --help -h
    This help information.
```

**Comment by mbkupfer** [comment]
@norbusan , this looks much better. 

Here are some suggestions:

1. Add a brief description of the tool between `Usage: onedrive [OPTION]...` and `Options`. You could even include the `no option        No sync and exit` part in that description. More importantly though, I think this description should explain the synchronize argument and it's mutual exclusivity w/the monito argument.

2. Adding annotations for the options that require values. For example:
` --confdir [dir_name]`

I don't write many cli's so I don't know the main convention, but I hope you understand my example.

**Comment by mbkupfer** [comment]
>Adding the information about arguments and their types is a bit a pain due to the D getopt interface, but I'm looking into it.

Wish I could help there, but I didn't even know about the D language until I got to this project. 

>Concerning the initial description, any suggestion ;-) ?

I'm still learning how onedrive works myself. I don't think I would be a good authorized source ☹️ Happy to copy-edit though.

**Comment by adudek** [comment]
@norbusan Might I recommend using http://docopt.org/ for this purpose. It does exacly what you need but in reverse. First you specify formatted docopt usage message, and then logic does parameter validation and conversion. Aaaaand it implemented in almost every language now

**Comment by norbusan** [comment]
I have implemented the command line parsing via docopt.d The current status is as follows:

No argument given, or wrong argument given, or error:
```
$ ./onedrive 
Usage:
  onedrive [options] [-v | -vv] (--synchronize | --monitor)
  onedrive --display-config
  onedrive -h | --help
  onedrive --version
```

Help given:
```
$ ./onedrive -h
OneDrive - a complete tool to interact with OneDrive on Linux

Usage:
  onedrive [options] [-v | -vv] (--synchronize | --monitor)
  onedrive --display-config
  onedrive -h | --help
  onedrive --version

Options:
  -h --help     Show this screen.
  --version     Show version.
  --check-for-nomount     
       Check for the presence of .nosync in the syncdir root. If found, do not perform sync.
  --confdir ARG
       Set the directory used to store the configuration files
       [default: /home/norbert/.config/onedrive]
  --create-directory ARG
       Create a directory on OneDrive - no sync will be performed.
  --destination-directory ARG
       Destination directory for renamed or move on OneDrive - no sync will be performed.
  --debug-https
       Debug OneDrive HTTPS communication.
  --disable-notifications 
       Do not use desktop notifications in monitor mode.
  --display-config 
       Display what options the client will use as currently configured - no sync will be performed.
  --download-only -d
       Only download remote changes
  --disable-upload-validation 
       Disable upload validation when uploading to OneDrive
  --enable-logging 
       Enable client activity to a separate log file
  --get-O365-drive-id ARG
       Query and return the Office 365 Drive ID for a given Office 365 SharePoint Shared Library
  --local-first 
       Synchronize from the local directory source first, before downloading changes from OneDrive.
  --logout 
       Logout the current user
  --monitor -m
       Keep monitoring for local and remote changes
  --no-remote-delete 
       Do not delete local file 'deletes' from OneDrive when using --upload-only
  --print-token 
       Print the access token, useful for debugging
  --resync 
       Forget the last saved state, perform a full sync
  --remove-directory ARG
       Remove a directory on OneDrive - no sync will be performed.
  --single-directory 
       Specify a single local directory within the OneDrive root to sync.
  --skip-symlinks 
       Skip syncing of symlinks
  --source-directory ARG
       Source directory to rename or move on OneDrive - no sync will be performed.
  --syncdir ARG
       Set the directory used to sync the files that are synced
  --synchronize 
       Perform a synchronization
  --upload-only 
       Only upload to OneDrive, do not sync changes from OneDrive locally
  --verbose -v
       Print more details, useful for debugging (repeat for extra debugging)
```

Let me know what you think?

**Comment by abraunegg** [comment]
LGTM

**Comment by mbkupfer** [comment]
First off, great work! I think this looks much better. 

Below are some comments I have. Please don't take this as me being critical, I'm simply giving the honest opinion of someone that is new to this tool and want's to figure out how it works. I think it is really easy to shoot yourself in the foot by getting into a state where you delete files from the cloud without any backup. 

## Comments:

- Do all arguments have to be wrapped in `' '` 's? If so, then I'd add that just to avoid confusion. 

- In `--confdir ARG`: I'd replace `/home/norbert` with `~/`

- Wording seems vague for  `--destination-directory ARG`. I can't really tell what it does. On first look, it appears that it is setting the `sync_dir` which I don't think it does. 

- Same thing w/wording on `--source-directory ARG`. How does this work? Do I put the name of a directory that I locally changed or moved and it will then update in the cloud?

- Also not sure what  `--syncdir ARG` does from its description. 

- slight tweak to `--synchronize`: Perform a synchronization. Syncs all files in OneDrive when no argument is provided.

**Comment by norbusan** [comment]
>     * Do all arguments have to be wrapped in `' '` 's? If so, then I'd add that just to avoid confusion.

what do you mean? None of them are? Please look at it on github, not in the email. This is markdown for the purpose of formatting.

>     * In `--confdir ARG`: I'd replace `/home/norbert` with `~/`

It is replaced with the correct value for the user invoking the program.

>     * Wording seems vague for  `--destination-directory ARG`. I can't really tell what it does. On first look, it appears that it is setting the `sync_dir` which I don't think it does.

For now I just used the help strings as they have been till now.

>     * slight tweak to `--synchronize`: Perform a synchronization. Syncs all files in OneDrive when no argument is provided.

I leave wording improvements to @abraunegg - I'm not native and might scramble down stupid things ;-)

**Comment by mbkupfer** [comment]
>what do you mean? None of them are? Please look at it on github, not in the email. This is markdown for the purpose of formatting.

What I mean is that arguments have to be surrounded by single-quotes. For example, if I want to do a `--single-directory` with folder `foo`, then I have to enter it as such: 
`onedrive --synchronize --single-directory 'foo'` @abraunegg , am I correct in understanding this?

>It is replaced with the correct value for the user invoking the program.
Sounds good.

**Comment by abraunegg** [comment]
> What I mean is that arguments have to be surrounded by single-quotes. For example, if I want to do a `--single-directory` with folder `foo`, then I have to enter it as such:
> `onedrive --synchronize --single-directory 'foo'` @abraunegg , am I correct in understanding this?

Generally it is better to put single quotes around items as per `onedrive --synchronize --single-directory 'foo'` so that 'spaces in the item' get read in correctly without issue by the application.

**Comment by mbkupfer** [comment]
Ohhh, I see now. Got it.

**Comment by norbusan** [comment]
Ahh, this one. That is basic property of parsing by the used shell, and nothing related to onedrive.

**Comment by mbkupfer** [comment]
@norbusan @abraunegg , is this issue closed?

**Comment by norbusan** [comment]
@mbkupfer No, this is a pull request but it is not decided whether - and if when - we integrate it. We first have to fix some bugs and clean up some stuff before moving forward with this. Very similar to the build system reworks, this is also on lower priority.

Thanks for your understanding

**Comment by norbusan** [comment]
Fixed with recent merge
