### ISSUE TITLE
systemd user units

### ISSUE THREAD

**Issue by liger1978** [abraunegg/onedrive#30]
Why has the latest version got rid  of the systemd user service in `/usr/lib/systemd/user/`  and replaced it with an `onedrive@.service` ? The previous system seemed logical, worked well and is the way user daemons are meant to work with systemd.  You could run the command: `systemctl --user start onedrive` as an unprivileged user.

**Comment by liger1978** [comment]
...also why are you logging to file rather than stdout?  Logging to stdout means the systemd service can control where logs end up (journal/syslog etc).  Logging to a a particular file means that every users needs permissions to write to the log file/directory.

**Comment by abraunegg** [comment]
> Why has the latest version got rid of the systemd user service in /usr/lib/systemd/user/ and replaced it with an onedrive@.service ?

It hasn't. There are 2 service files. See:

https://github.com/skilion/onedrive/pull/348
https://github.com/skilion/onedrive/pull/314/commits/9b361101f6d51b3907c3ac2ecdb58a275b2c2e1d

The original file is as is, with fixes that make it actually work, plus a new systemd file that is a multi user service file to allow them to have their own configuration - this is the @ version.

The issue with the original file is that the user 'running' the daemon was root, not the actual 'user' - thus there are file permission issues coming into play.

> ...also why are you logging to file rather than stdout? 

The logging facility has not changed. The application still logs to stdout. Cleaner output & what should be displayed vs not displayed when using `--verbose` has been done - outside of that, the application still logs to console under stdout and stderr.

The log file addition was added to have a full record of all activities on the system where it may be required from an audit perspective & to provide a log where systemd is not on the system. If a user were to run the daemon in monitor mode manually - they would have zero record of what actually was sync'd or not synced - regardless of systemd being used or not.

**Comment by liger1978** [comment]
Thanks. Apologies, I somehow misread the `Makefile` with regards to where the service files were ending up. Not sure how I managed that!  So under what circumstances does the app log to `/var/log/onedrive` and can this be disabled? Thanks again for adopting this project btw.

**Comment by abraunegg** [comment]
> So under what circumstances does the app log to /var/log/onedrive 

All logging, verbose or not goes to the log file - either in `/var/log/onedrive` as %username%.onedrive.log or in the user home directory root `~/`

> and can this be disabled?

At this stage it is default on, with no off, which is why there is also a logrotate file to compress & manage the log files that get created. It is better to have a log than not. Feel free to submit a PR to add a flag to disable log file logging, however my focus at the moment is getting rid of the bugs & the quickxor issue I found is top priority at the moment.

**Comment by liger1978** [comment]
@abraunegg Thank for the info and help.  FYI I've updated my CentOS 7 OneDrive RPM to use your fork.  More info here: https://gitlab.com/harbottle/centos7-onedrive

Cheers!
