### ISSUE TITLE
Sync_Dir not read from Config file when run in Docker container

### ISSUE THREAD

**Issue by ChessDragon136** [abraunegg/onedrive#306]
Hi Alex - I hope you are well. 

I've noted Issues #301 and #302 which may or may not be the cause, but my sync_dir option is now ignored from the config file. It is not explicitly set in the command line, but I agree with the comments there that any explicitly set sync_dir should take priority. 

Not sure what information to provide on this one, so just ask if you need more.

Thanks,

Version 2.2.3
Running in my custom Docker for UnRaid: [https://github.com/ChessDragon136/OneDrive-Docker](url)
 (Sadly this makes testing older commits a pain in the backside as I was a lazy coder..)
```
--display-config
Config path                         = /OneDriveConf
Config file found in config path    = true
Config option 'sync_dir'            = /home/nobody/OneDrive
Config option 'skip_file'           = .*|~*
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured 
```
Config File
```
sync_dir="/OneDriveData"
skip_file = ".*|~*"
```

**Comment by abraunegg** [comment]
Unable to reproduce:
```
./onedrive --confdir '~/odconfig/' --synchronize --verbose --display-config
Loading config ...
Using Config Dir: /home/alex/odconfig/
Config path                         = /home/alex/odconfig/
Config file found in config path    = true
Config option 'sync_dir'            = /home/alex/OneDriveALT
Config option 'skip_file'           = ~*
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 90
Config option 'log_dir'             = /var/log/onedrive/
Config option 'drive_id'            = b!6H_y8BWP8Uqg2X0QAy4XfxiTMFe_reZKrMZXLeBjL4g70-n16rIGQpOG_l7vVxU5
Selective sync configured           = false
(dmd-2.083.0)[alex@centos7full onedrive]$ cat ~/odconfig/config 
# Directory where the files will be synced
sync_dir = "/OneDriveALT"
# Skip files and directories that match this pattern
skip_file = "~*"
# Wait time (seconds) between sync operations in monitor mode
monitor_interval = "90"
# Drive ID for SharePoint Shared Library
drive_id = "b!6H_y8BWP8Uqg2X0QAy4XfxiTMFe_reZKrMZXLeBjL4g70-n16rIGQpOG_l7vVxU5"
(dmd-2.083.0)[alex@centos7full onedrive]$ ./onedrive --confdir '~/odconfig/' --synchronize --verbose 
Loading config ...
Using Config Dir: /home/alex/odconfig/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /OneDriveALT
Initializing the Synchronization Engine ...
Account Type: documentLibrary
Default Drive ID: b!6H_y8BWP8Uqg2X0QAy4XfxiTMFe_reZKrMZXLeBjL4g70-n16rIGQpOG_l7vVxU5
Default Root ID: 01LWWIJZN6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 27487788814074
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 01LWWIJZN6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing 4
The directory has not changed
Processing Document.docx
The file has not changed
Processing 2
The directory has not changed
Processing Document.docx
The file has not changed
Processing 1
The directory has not changed
Processing 1.txt
The file has not changed
Processing 3
The directory has not changed
Processing Presentation.pptx
The file has not changed
Uploading new items of .
Applying changes of Path ID: 01LWWIJZN6Y2GOVW7725BZO354PWSELRRZ
```

Maybe something unique to your Docker container?

**Comment by lhorace** [comment]
> 301 and 302

#301 #302

Off-topic: Hey there, for future reference, it would have been allot easier for some of else to locate the issues you've mentioned in your post by appending `#`. Thanks.

**Comment by ChessDragon136** [comment]
Ok that's good. I'll investigate further.

> > 301 and 302
> 
> #301 #302
> 
> Off-topic: Hey there, for future reference, it would have been allot easier for some of else to locate the issues you've mentioned in your post by appending `#`. Thanks.

I meant to - It's midnight here, cut me some slack :)

**Comment by abraunegg** [comment]
@ChessDragon136 
Any update here in finding the cause?

Would a new PR version that has extra debugging assist?

**Comment by abraunegg** [comment]
@ChessDragon136 
Will put something together, however I am also looking at the logic right now of where the 'syncdir' is configured, and it does not seem right for all use cases as well.

**Comment by ChessDragon136** [comment]
@abraunegg 
Thanks again. 

Not that my 2p means anything but sync_dir seems too important to be in the config file. Call me old fashioned but I was taught to put program critical operational items in the command line and user preferences in configuration files. And I think this is the only exception where you allow an option to be specified in 2 locations? Anyway happy code hunting.

**Comment by abraunegg** [comment]
@ChessDragon136 
When you get a chance, please can you test this PR on your Docker:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/308/head:pr308
git checkout pr308
make
make install
```
I have made a number of tweaks to the 'sync_dir' handling, and added some extra debugging for output to assist:
```
./onedrive -v -v --syncdir '~/asdf/' --display-config
Loading config ...
Using Config Dir: /home/alex/.config/onedrive
No config file found, using application defaults
[DEBUG] CLI override to set sync_dir to: ~/asdf/
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER is set
[DEBUG] syncDir: /home/alex/asdf/
Config path                         = /home/alex/.config/onedrive
Config file found in config path    = false
Config option 'sync_dir'            = /home/alex/asdf/
Config option 'skip_file'           = ~*
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false
```

If you can test and report back your findings that would be greatly appreciated

**Comment by ChessDragon136** [comment]
Ok that works. 

Sync Dir now reads from the config file correctly. 
If it is also specified in the command line the command line takes priority. Logging from this scenario is below, maybe not crystal clear as debug lines 1 and 3 at first reading looked like it was re-setting the sync_dir to be from config. If there is a CLI override, is it necessary to read the config value?

Loading config ...
Using Config Dir: /OneDriveConf
[DEBUG] CLI override to set sync_dir to: /OneDriveData
[DEBUG] sync_dir: No SHELL or USER detected
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] syncDir: /OneDriveData
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /OneDriveData
Initializing the Synchronization Engine ...
Account Type: personal
......

Config file:
sync_dir = "/OneDriveConf/TEST"
skip_file = ".*|~*|Hardy's Hobbies"
log_dir = "/OneDriveConf/Logs/"

**Comment by abraunegg** [comment]
>  If there is a CLI override, is it necessary to read the config value?

Yes - as the CLI override resets / sets the config value for 'sync_dir', thus now all operations read 'sync_dir' & interpret correctly. 

Previously, in a 'No SHELL or USER detected' state, 'sync_dir' whilst set correctly, was not being 'read' and 'syncDir' was being set to "homeDir + /OneDrive" without any evaluation of if this was even accurate

**Comment by ChessDragon136** [comment]
I just treated myself to a browse through the code changes and can see how it works now.

As always thank you.

**Comment by abraunegg** [comment]
@ChessDragon136 
PR #308 merged into master
