### ISSUE TITLE
Implement a --dry-run option

### ISSUE THREAD

**Issue by abraunegg** [abraunegg/onedrive#317]
Implement a `--dry-run` option to allow users to 'validate' what would occur when using a particular sync command without any data changes occuring.

Switch would be valid for all options except `--monitor` mode as I do not think it would be viable / beneficial.

**Comment by lhorace** [comment]
This is a good idea!

**Comment by norbusan** [comment]
I agree that this would be a good idea, but we need to think about the output format. Should it be the very same one as when running in normal mode?

**Comment by abraunegg** [comment]
> I agree that this would be a good idea, but we need to think about the output format. Should it be the very same one as when running in normal mode?

I was thinking exactly the same, but obviously not executing 'change'. Printing out though at the start a bold message indicating this this is a dry-run and this is what would have occured - similar to `rsync --dry-run` and it's output for such command.

**Comment by norbusan** [comment]
Sounds fine to me.

**Comment by abraunegg** [comment]
@norbusan 
Just wondering if you have any insights as to the eTag / cTag generation?

* eTag for the entire item (metadata + content). Read-only.
* An eTag for the content of the item. This eTag is not changed if only the metadata is changed. Read-only.

Normally, these would be returned by OneDrive as part of response to an upload or an item query request, however in a 'dry-run' scenario, the upload is not being done, thus the response needs t simulated & stored in a tmp database (otherwise other functions fail). Right now I am trying to find function as to how to generate the eTag / cTag items but coming up short. Any ideas?

**Comment by norbusan** [comment]
Good question - but no idea. I searched the API for a bit but didn't get any conclusive answer. Maybe a random string, or the sha256 hash of the content would be fine?

**Comment by abraunegg** [comment]
Hi all,

Looking for folk to assist in testing this PR that implements a `--dry-run` option.

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/337/head:pr337
git checkout pr337
make
```

If you are able to test this PR, and report back that would be greatly appreciated.

Please use this against a **TEST** OneDrive account - as I would currently call this feature **BETA** quality as I have only tested it. 

The feature currently does what it "should" do in my test cases, however this needs some extensive testing & confirmation that there is no undesirable bug which could cause data to be lost.

**Comment by 0x3333** [comment]
I'm going to test this PR.

 In my use case, I'd like to simulate what would be done, so I can check before running the sync if a huge amount of files would be deleted or something. I had a problem with the `skilion` version that I don't want to happen again... :)

I'll get back to you.

**Comment by 0x3333** [comment]
Here we go.
I tried in my production machine, same issue. I'm using the same account(My personal account).

```
$ ./test.sh
Main sync folder: /tmp/test/main
OneDrive config folder: /tmp/test/.config
Refresh token found, using it: /tmp/test/refresh_token

*** Those folders will be deleted and re-created... ***

Press Ctrl+C to cancel or enter to continue...

Removing /tmp/test/main sync folder...
Removing OneDrive config folder...
Recreating folder structure...
/tmp/test/main
/tmp/test/main/a
/tmp/test/main/a/a.txt
/tmp/test/main/a/b
/tmp/test/main/a/b/b.txt
/tmp/test/main/a/b/~b.txt
/tmp/test/main/a/b/c
/tmp/test/main/a/b/c/c.txt
/tmp/test/main/1
/tmp/test/main/1/2
/tmp/test/main/1/2/2.txt
/tmp/test/main/1/2/3
/tmp/test/main/1/2/3/~3.txt
/tmp/test/main/1/2/3/3.txt
/tmp/test/main/1/1.txt
Creating OneDrive config files...
Copying existing Refresh Token...
Running sync...
*** OneDrive output below this line ***

DRY-RUN Configured. Output below shows what 'would' have occurred.
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Processing 5 changes
Creating directory: Public
Creating directory: Documents
Uploading new file ./a/a.txt ... done.

ERROR: Unable to query the following path due to OneDrive API regression: ./a/b
ERROR: Refer to https://github.com/OneDrive/onedrive-api-docs/issues/976 for further details
WORKAROUND: Manually create the path above on OneDrive to workaround API issue

Skipping uploading this new file as parent path is not in the database: ./a/b/b.txt

ERROR: Unable to query the following path due to OneDrive API regression: ./a/b
ERROR: Refer to https://github.com/OneDrive/onedrive-api-docs/issues/976 for further details
WORKAROUND: Manually create the path above on OneDrive to workaround API issue


ERROR: Unable to query the following path due to OneDrive API regression: ./a/b/c
ERROR: Refer to https://github.com/OneDrive/onedrive-api-docs/issues/976 for further details
WORKAROUND: Manually create the path above on OneDrive to workaround API issue

Skipping uploading this new file as parent path is not in the database: ./a/b/c/c.txt

ERROR: Unable to query the following path due to OneDrive API regression: ./1/2
ERROR: Refer to https://github.com/OneDrive/onedrive-api-docs/issues/976 for further details
WORKAROUND: Manually create the path above on OneDrive to workaround API issue

Skipping uploading this new file as parent path is not in the database: ./1/2/2.txt

ERROR: Unable to query the following path due to OneDrive API regression: ./1/2
ERROR: Refer to https://github.com/OneDrive/onedrive-api-docs/issues/976 for further details
WORKAROUND: Manually create the path above on OneDrive to workaround API issue


ERROR: Unable to query the following path due to OneDrive API regression: ./1/2/3
ERROR: Refer to https://github.com/OneDrive/onedrive-api-docs/issues/976 for further details
WORKAROUND: Manually create the path above on OneDrive to workaround API issue

Skipping uploading this new file as parent path is not in the database: ./1/2/3/3.txt
Uploading new file ./1/1.txt ... done.
*** OneDrive exited with '0' ***
Finished!
$ uname -a
Linux smb 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
$ cat /etc/issue
Debian GNU/Linux 9 \n \l
```

**Comment by abraunegg** [comment]
Closing as PR #337 merged
