### ISSUE TITLE
Make command during installation encounters error 127

### ISSUE THREAD

**Issue by nahmias22** [abraunegg/onedrive#32]
Hi, I was directed by you to this github repository from skillion's repository. I am trying to install your software on ubuntu 18.04. I installed all the dependent programs and downloaded the files using git but when i cd into the directory and use make i encounter the bellow response:
```
~/onedrive$ make
echo v1.1.2-15-g54fcb63 >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
make: dmd: Command not found
Makefile:34: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127
```
Do you have any advice to offer for resolving this error?

**Comment by abraunegg** [comment]
How are you installing dmd and the dependancies?

```
sudo apt install libcurl4-openssl-dev sudo apt install libsqlite3-dev curl -fsS https://dlang.org/install.sh | bash -s dmd
```

**Comment by nahmias22** [comment]
I installed all the dependencies using the commands you provide in your instructions. But when i use the command above I get an error as terminal does not understand -s option

**Comment by abraunegg** [comment]
To install DMD - refer to https://dlang.org/download.html

```
curl -fsS https://dlang.org/install.sh | bash -s dmd
```

If this is not working for you refer to the installation instructions for your OS to install via a package. If this is not working, refer your issue to your OS provider for support.

**Comment by nahmias22** [comment]
No it is already installed
dmd-2.080.1 already installed
Using dub 1.9.0 shipped with dmd-2.080.1

Run `source ~/dlang/dmd-2.080.1/activate` in your shell to use dmd-2.080.1.
This will setup PATH, LIBRARY_PATH, LD_LIBRARY_PATH, DMD, DC, and PS1.
Run `deactivate` later on to restore your environment.
but when i try running the make command in the directory of onedrive I receive error 127

**Comment by nahmias22** [comment]
Thanks for your help I managed to get it to work. Apparently I had to activate DMD. Could you please clarify though one more thing for me. When i just use the option synchronize does it first download a file from the cloud or upload. So if i made some edits to a file locally how should i sync it to the drive?

**Comment by abraunegg** [comment]
Thanks for the feedback - will add this to the Readme & wiki.

> When i just use the option synchronize does it first download a file from the cloud or upload. So if i made some edits to a file locally how should i sync it to the drive?

The default mode of operation is below:

`onedrive --synchronize`

This will first download changes / new files from OneDrive first before uploading local changes. To switch this around use the following:

`onedrive --synchronize --local-first`

This will then synchronize from the local directory source first, before downloading changes from OneDrive.

If you want to see what is being performed at a more detail level, use the `--verbose` switch, or check the log file (with or without using verbose mode - the log file is always verbose) either in `/var/log/onedrive` or in `~/`

**Comment by abraunegg** [comment]
Added to https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions
