### ISSUE TITLE
[question] Do I need to maintain two git respositories locally?

### ISSUE THREAD

**Issue by lhorace** [abraunegg/onedrive#321]
Too test PR's, do I need to keep seperate git repositories locally? Or can I just sync changes upstream from my fork?

Regards

**Comment by norbusan** [comment]
??? I don't understand your question. If you want to try out a PR, you can simply use `git checkout`

**Comment by lhorace** [comment]
I've forked this repo here https://github.com/lhorace/onedrive but I haven't sync it, following these instructions here https://help.github.com/articles/syncing-a-fork/, to this repository. I'm still in the process of setting up my development environment atm.

**Comment by abraunegg** [comment]
I use the following script:
```
#!/bin/bash

PR=320

rm -rf ./onedrive-pr${PR}
git clone https://github.com/abraunegg/onedrive.git onedrive-pr${PR}
cd onedrive-pr${PR}
git fetch origin pull/${PR}/head:pr${PR}
git checkout pr${PR}
source ~/dlang/dmd-2.083.0/activate
make clean; make;
deactivate
```

The `source ~/dlang/dmd-2.083.0/activate` would need local modification for your environment however

I then cd to the onedrive-pr${PR} directory, and run 'onedrive' from there

**Comment by lhorace** [comment]
Great, so I don't have to maintain a `onedrive@lhorace` and a `onedrive@abraunegg` seperately.

**Comment by abraunegg** [comment]
Not that I am aware of

**Comment by norbusan** [comment]
> Great, so I don't have to maintain a `onedrive@lhorace` and a `onedrive@abraunegg` seperately.

No you don't have. I have three remotes (this one here, my clone on github, and the Debian packaging on salsa.debian.org) as remotes, and branches are pushed/pulled from here and there.
