### ISSUE TITLE
'JSONValue is not an object' occurs when attempting to resume a session upload

### ISSUE THREAD

**Issue by Zaporozhec7** [abraunegg/onedrive#330]
### Bug Report Details ###

I have error **JSONValue is not an object** with version v2.2.4-5-g1fa7e5f built from master branch.

**Update:** 
Error happen each time on beginning of command run, but uploading percentage sometimes change. 
After I viewed latest uploaded folder through OneDrive web-interface, sync was resumed without errors. 

**Application and Operating System Details:**
Q: OS
A: Ubuntu 18.04.1 | 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Q: Are you using a headless system (no gui) or with a gui installed?
A: I do not understand this question

Q: OneDrive Account Type
A: Office 365 Personal paid subscription

Q: DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
A: DMD64 D Compiler v2.084.0

Q: Application version: Output of `onedrive --version`
A: onedrive v2.2.4-5-g1fa7e5f

Q: Application configuration: Output of `onedrive --display-config`
A:
```
onedrive version                    = v2.2.4-5-g1fa7e5f
Config path                         = /home/stanislav/.config/onedrive
Config file found in config path    = true
Config option 'sync_dir'            = /mnt/sdb/stanislav/CLOUD_SYNC_IMPORTANT_FILES
Config option 'skip_file'           = ~*
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'log_dir'             = /mnt/sdb/var/log/onedrive
Selective sync configured           = false
```

**To Reproduce**

Run with next flags `onedrive --synchronize --upload-only --no-remote-delete`

**Complete Verbose Log Output**

```
$ onedrive --synchronize --upload-only --no-remote-delete --verbose
Loading config ...
Using Config Dir: /home/stanislav/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /mnt/sdb/stanislav/CLOUD_SYNC_IMPORTANT_FILES
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 740cd9a1845fc965
Default Root ID: 740CD9A1845FC965!101
Remaining Free Space: 1032545887353
Fetching details for OneDrive Root
OneDrive Root exists in the database
Trying to restore the upload session ...
Continuing the upload session ...
Uploading   2% |o                                       |   ETA   --:--:--:std.json.JSONException@std/json.d(278): JSONValue is not an object                                                                      
----------------
/root/dlang/dmd-2.084.0/linux/bin64/../../src/phobos/std/exception.d:515 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x7f791e67]
/root/dlang/dmd-2.084.0/linux/bin64/../../src/phobos/std/exception.d:436 pure @safe bool std.exception.enforce!(std.json.JSONException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x7f791de1]
??:? inout pure ref @property inout(std.json.JSONValue[immutable(char)[]]) std.json.JSONValue.object() [0x7f7f368d]
src/sync.d:1703 void sync.SyncEngine.saveItem(std.json.JSONValue) [0x7f7ca68b]
src/sync.d:262 void sync.SyncEngine.init() [0x7f7c4323]
src/main.d:583 bool main.initSyncEngine(sync.SyncEngine) [0x7f7a28ec]
src/main.d:398 _Dmain [0x7f7a1d04]

```

Application Log Output:

There no logs in logs directory.

**Comment by abraunegg** [comment]
@Zaporozhec7 
Unable to reproduce this issue locally by uploading a ~200Mb+ file and using CTRL-C to abort during upload, then restarting. Each time restart is successful & upload completes without failure.

Please generate a full debug log as requested above if you are able to consistently reproduce this issue.

**Comment by Zaporozhec7** [comment]
@abraunegg  thank you for fast response

```
$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

Sorry, Unfortunatelly I can not reproduce this issue for now too, because after multiple retries I have uploaded all files. So I close this issue.
Thank you very much for your work.
