### ISSUE TITLE
Name checking rule not exactly right

### ISSUE THREAD

**Issue by priv** [abraunegg/onedrive#34]
I have an existing file called "HelloCOM2.rar", after moving toward this new branch the program complaining about invalid name problem.

After checking the code, I found it is rejected by COM[0-9] rule.
But I think the original rule is an exact match of COM[0-9].
( https://support.microsoft.com/en-us/help/3125202/restrictions-and-limitations-when-you-sync-files-and-folders )

So HelloCOM2.rar should be valid.

**Comment by abraunegg** [comment]
Thanks - it looks like the pull that provided this (https://github.com/skilion/onedrive/pull/104) whilst works, didn't factor in matching as part of a file name - when it should have been an exact match.

Will look at this once other issues are resolved.

**Comment by abraunegg** [comment]
Can you help validate this PR to resolve your issue:

https://github.com/abraunegg/onedrive/pull/38

**Comment by priv** [comment]
Hi,
I've also validated this patch.
Thanks

**Comment by abraunegg** [comment]
PR #38 merged
