### ISSUE TITLE
Question: Notifications?

### ISSUE THREAD

**Issue by coxackie** [abraunegg/onedrive#342]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
OneDrive client runs with `systemctl --user start onedrive`. Not sure whether this is a bug, more of a question: I do not know what kind of notifications I am supposed to be getting, but I am not getting any. (Note that `libnotify` is installed.) I would expect that when syncing new files, I would get a notification when syncing ends, at the very least.

**Application and Operating System Details:**
*   OS: Output of `uname -a`: `Linux 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux`. Using Arch Linux
*   Are you using a headless system (no gui) or with a gui installed? Using GNOME 3.30
*   OneDrive Account Type: Business (365)
*   DMD64 D Compiler v2.084.0
*   Application configuration: Output of `onedrive --display-config`:
```
onedrive version                    = v2.2.4-22-g1d902a5
Config path                         = /home/coxackie/.config/onedrive
Config file found in config path    = false
Config option 'sync_dir'            = /home/coxackie/OneDrive
Config option 'skip_file'           = ~*
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false
```

*   Curl Version: Output of `curl --version`
```
curl 7.63.0 (x86_64-pc-linux-gnu) libcurl/7.63.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.35.1
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Comment by abraunegg** [comment]
@coxackie 
>  I do not know what kind of notifications I am supposed to be getting, but I am not getting any. 
What should occur is that you currently get notified of application errors and sync errors only at this point in time.

There is a fine balance between 'not enough notification' & 'too much' when the application is running in monitor mode which is why for the moment the application only sends a GUI notification for the following events:
* Aborting a sync if .nosync file is found
* Cannot create remote directory
* Cannot upload file changes
* Cannot delete remote file / folder
* Cannot move remote file / folder

This information is also not in the readme and it should be. Will get that added in so that it is clear what notifications are currently supported.

**Comment by coxackie** [comment]
Many thanks - this is rather clear. My two cents: given that there is at this point no "graphical" way (for example, tray icon) in order to show when syncing is implemented, it could be a good idea to notify when sync starts and when it concludes (for example, a notification of the sort "Syncing 17 files..." and then "Syncing complete") could be useful. Maybe you can consider it for the future.

**Comment by abraunegg** [comment]
@coxackie 
Readme updated via https://github.com/abraunegg/onedrive/pull/345/commits/1028810c434cc10179f360fa226b21cf6b031d07 in preparation for 2.2.5 release

**Comment by abraunegg** [comment]
@coxackie 
FR logged for additional notification support: https://github.com/abraunegg/onedrive/issues/346

**Comment by norbusan** [comment]
@coxackie please see my comments at #346 and let us hear your opinion!
