### ISSUE TITLE
Question: does it keep track of file changes?

### ISSUE THREAD

**Issue by david-tamar** [abraunegg/onedrive#343]
Does it keep track of files that were changed in some way? For example would a modified text file be re-uploaded when scanned the next time?

If yes, then how does it compare to the mirror that resides on the cloud? Via checksum, or merely by recorded dates of modification/creation as recorded by the filesystem?

Another related question: Does it re-upload files that had no changes at all? (I suppose it doesn't, but just want to make sure) Thanks!

**Comment by abraunegg** [comment]
question answered
