### ISSUE TITLE
Current git fixed shared personal folder sync issue

### ISSUE THREAD

**Issue by frispete** [abraunegg/onedrive#344]
Dear @abraunegg,

let me start with a huge thank you for your continuous work on this project.

I just wanted to leave a note about current git fixing my similar issue as well in #323 (most probably with b751632), but since the lock bot closed the thread (prematurely from my POV), I cannot comment there...

So, from my humble POV, this fix deserves just another release soon.

Since a client of mine relies on this package on openSUSE, here'a pointer to my public builds:
https://build.opensuse.org/project/monitor/home:frispete:onedrive
hence, there's no need for compilation for the supported openSUSE releases (if somebody is missing a target, let me know, please).

I will try to push that package to Factory soon.

**Comment by frispete** [comment]
Thanks for the warning, @abraunegg. 

Will carefully watch the operation and expect some more trouble. It's a premiere for me to watch MS in an open collaboration.

**Comment by abraunegg** [comment]
@frispete 
FYI also updated the lockbot from 7 to 30 days. For me, I would rather have a new issue raised than comments added to a closed / resolved issue.

**Comment by abraunegg** [comment]
@frispete 
v2.2.5 released which will simply your release process for SuSE.
