### ISSUE TITLE
I need make a backup of 2 servers in diferent folders

### ISSUE THREAD

**Issue by lanaparadinha** [abraunegg/onedrive#348]
**Is your feature request related to a problem? Please describe.**
I need serverA and serverB
and need create 2 folders diferents for each server in my onedrive.
But i tried:
--destination-directory
--single-dir
and no option worked

**Describe the solution you'd like**
i Think:
--destination-directory sincronize mydir with folder "serverA" in onedrive, but dont work. (I am create this directory in onedrive previously)

**Describe alternatives you've considered**
I believe I should have an option to choose which folder we would like to sync

**Additional context**
None

**Comment by abraunegg** [comment]
@lanaparadinha 
It is best to refer to the readme for the CLI options to use here.
```
--destination-directory ARG
      Destination directory for renamed or move on OneDrive - no sync will be performed.
```
You can only use this option with:
```
--source-directory ARG
      Source directory to rename or move on OneDrive - no sync will be performed.
```
What this allows is moving / renaming a directory on OneDrive from the CLI and no sync is performed.

> I need make a backup of 2 servers in different folders

What you need to do is this:
1. Create 2 different 'config' directories under ~/.config/ for example:
```
~/.config/onedrive-account-1
~/.config/onedrive-account-2
```
2. Create 2 different 'sync' directories under your home drive, for example:
```
~/OneDrive-Account-1
~/OneDrive-Account-2
```
3. In each of the 'config' directories copy the 'default' config file
4. Edit each of the 'config' files so that:
```
sync_dir = "~/OneDrive-Account-1"
```
5. Run the client specifying the configuration directory:
```
onedrive --confdir '~/.config/onedrive-account-1' --synchronize --verbose
onedrive --confdir '~/.config/onedrive-account-2' --synchronize --verbose
```

What should happen is that OneDrive Account 1 data will be saved in ~/OneDrive-Account-1 and OneDrive Account 2 data will be saved in ~/OneDrive-Account-2

**Comment by abraunegg** [comment]
Use of `--single-directory` option:
If say, in any of the OneDrive accounts you have the following folder structure:
```
.
├── Architecture\ Layres
├── Cisco\ VDI\ Whitepaper
├── Copy\ 1
│   ├── Architecture\ Layres
│   ├── Cisco\ VDI\ Whitepaper
│   ├── CP704
│   │   ├── Sample\ Exam
│   │   ├── Week\ 1
│   │   ├── Week\ 10
│   │   ├── Week\ 11
│   │   ├── Week\ 12
│   │   ├── Week\ 2
│   │   ├── Week\ 3
│   │   ├── Week\ 4
│   │   ├── Week\ 5
│   │   ├── Week\ 6
│   │   ├── Week\ 7
│   │   ├── Week\ 8
│   │   └── Week\ 9
│   ├── Desktop\ Crap
│   ├── Desktop\ Crap\ #2
│   ├── Desktop\ Crap\ #3
│   ├── Exchange_Visio_Stencil_and_Template
│   ├── Hans-The\ Silva\ Method
│   ├── MyNAS
│   │   ├── Anaconda\ Code\ Help
│   │   ├── Blank\ NDA's
│   │   ├── EULA\ HTML\ Version
│   │   ├── Install\ Guide\ Graphics
│   │   │   └── PSD
│   │   ├── Install\ Guide\ Graphics\ -\ JPG
│   │   ├── MyNAS\ Install\ Guide
│   │   ├── Tick\ and\ Cross
│   │   └── WebUI\ Errors
│   ├── MYOB\ Hours
│   ├── MYOB\ Work
│   └── SMPP
├── Copy\ 2
│   ├── MYOB\ Hours
│   ├── MYOB\ Work
│   └── SMPP
└── SMPP
```

and that I would like to sync 'only' the 'Copy 2' folder, I would specify as the command line:
```
onedrive --confdir '~/.config/onedrive-account-1' --synchronize --verbose --single-directory 'Copy 2'
```

I would first however have to ensure that 'Copy 2' also exists in the sync directory otherwise the client will complain that the 'Copy 2' folder does not exist, thus cannot make that as the 'root' source for the sync operations.

**Comment by abraunegg** [comment]
> I need serverA and serverB
and need create 2 folders diferents for each server in my onedrive.

The other option here is:

Use whatever script / process to create a 'diff' (changed files, all files, selection of important files) of each server A & server B as a tar file or other & store in ~/OneDrive/ServerA and ~/OneDrive/ServerB respectively.

An alternate to that would be to use a file system on the server that supports snapshots (eg ZFS) and snapshot the filesystem, then perform a zfs send of the snapshot to a tar file for archival purposes.

This way you are only using one OneDrive account to sync, 2 local folders call ServerA & ServerB and the contents of those folders a "backup archive" of ServerA and ServerB

You could then utilise the `--upload-only` & `--no-remote-delete` to ensure that OneDrive only ever has the backups and nothing is deleted.

**Comment by lanaparadinha** [comment]
I think you dont understand my question.

I have 2 servers and need create 2 area in one onedrive account.
ServerA i need upload for folder "ServerA" 
ServerB i need upload for folder "ServerB"

Both server it has same structure of folders.
"/home/backup"
But i need put backup´s in diferent structures inside onedrive.

But i can't put backup in serverA into only folder "ServerA"

my desire structure in onedrive:
.
├── ServerA
│   ├── Backup´s
├── ServerB
│   ├── Backup´s

**Comment by abraunegg** [comment]
> I think you dont understand my question.
> 
> I have 2 servers and need create 2 area in one onedrive account.
> ServerA i need upload for folder "ServerA"
> ServerB i need upload for folder "ServerB"
> 
> Both server it has same structure of folders.
> "/home/backup"
> But i need put backup´s in diferent structures inside onedrive.
> 
> But i can't put backup in serverA into only folder "ServerA"
> 
> my desire structure in onedrive:
> .
> ├── ServerA
> │ ├── Backup´s
> ├── ServerB
> │ ├── Backup´s

1. Symbolic link /home/backup on each server to ~/OneDrive/ServerA or ~/OneDrive/ServerB (or elsewhere if not using ~/OneDrive - but configure the 'config' file first)
2. Configure the 'onedrive' client
3. Run the 'onedrive' client using: 
Server A:
```
onedrive --synchronize --verbose --single-directory 'ServerA' --upload-only
```
Server B:
```
onedrive --synchronize --verbose --single-directory 'ServerB' --upload-only
```

Result:

On OneDrive, you will have /ServerA & /ServerB path's with the correct subdirectories underneath.

**Comment by abraunegg** [comment]
@lanaparadinha 
Does the above answer your question, if so, please can you close this case.

**Comment by abraunegg** [comment]
Closing case as answer provided
