### ISSUE TITLE
Warnings about "bashisms" in init.d script

### ISSUE THREAD

**Issue by mleise** [abraunegg/onedrive#349]
### Bug Report Details ###
On Gentoo Linux, the QA system in the package manager (Portage) warns about non-POSIX features being used in `/etc/init.d/onedrive`:
```
 * QA Notice: shell script appears to use non-POSIX feature(s):
 *    possible bashism in /etc/init.d/onedrive line 27 ($"foo" should be eval_gettext "foo"):
 *            echo -n $"Starting $APP_NAME: "
 *    possible bashism in /etc/init.d/onedrive line 27 (echo -n):
 *            echo -n $"Starting $APP_NAME: "
 *    possible bashism in /etc/init.d/onedrive line 37 ($"foo" should be eval_gettext "foo"):
 *            echo -n $"Shutting down $APP_NAME: "
 *    possible bashism in /etc/init.d/onedrive line 37 (echo -n):
 *            echo -n $"Shutting down $APP_NAME: "
 *    possible bashism in /etc/init.d/onedrive line 77 ($"foo" should be eval_gettext "foo"):
 *            echo $"Usage: $0 {start|stop|restart|reload|status}"
```
I am the maintainer of that package script.

**Application and Operating System Details:**
*   OS: Linux 4.14.83-gentoo #1 SMP PREEMPT Tue Nov 27 23:48:38 CET 2018 x86_64 Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz GenuineIntel GNU/Linux

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Install `checkbashisms` (part of `devscripts` on Debian/Ubuntu)
2.  Run `checkbashisms -n /etc/init.d/onedrive`
3.  See warnings

**Additional context**
Init.d scripts cannot be assumed to be run through bash and should be fixed to be POSIX compliant.
(https://www.google.com/search?q=init.d+bashisms)

**Comment by abraunegg** [comment]
@mleise 
Thanks for this report. Interesting that this was not picked up in the codacy reviews.

**Comment by abraunegg** [comment]
@mleise 
> Init.d scripts cannot be assumed to be run through bash and should be fixed to be POSIX compliant.

This init file was built from standard RHEL scripts, and is executed using `sh` not `bash`:
```
#!/bin/sh
#
# chkconfig: 2345 20 80
# description: Starts and stops OneDrive Free Client
#
``` 

Does `checkbashisms` validate just `bash` operations or `bash` and `sh` ?

**Comment by abraunegg** [comment]
@mleise 
This should be resolved as per https://github.com/abraunegg/onedrive/pull/353/commits/fcc340329453c8c38634ebddd4f89a8a9326274b

```
root@debian-x86-64:~/code/onedrive# checkbashisms init.d/onedrive.init 
root@debian-x86-64:~/code/onedrive# 
```

**Comment by mleise** [comment]
> Does `checkbashisms` validate just `bash` operations or `bash` and `sh` ?

I only know what the man page says:
> Note that the definition of a bashism in this context roughly equates to "a shell feature that is not required to be supported by POSIX"; this means that some issues flagged may be permitted under optional sections of POSIX, such as XSI or User Portability.

Also since it is coming from Debian:
> In cases where POSIX and Debian Policy disagree, checkbashisms by default allows extensions permitted by Policy but may also provide options for stricter checking.

I don't know if it can be used to validate already 100% POSIX scripts. They do offer 3 levels of checks though:
 - Default is what Debian requires for an `sh` implementation on their distribution
 - `--newline` disallows `echo -n` (Gentoo uses this)
 - `--posix` complains about anything required by Debian, but non POSIX

So I'd assume all the warnings you get are from the set "Debian minus POSIX".
