### ISSUE TITLE
SharePoint get Drive ID multiple options

### ISSUE THREAD

**Issue by 0x3333** [abraunegg/onedrive#351]
### Bug Report Details ###
I'm using `onedrive` to sync a SharePoint library to a local linux machine. When I first tried, it run OK, but no files were downloaded from SharePoint.

I started investigating, and I found that there is 2 libraries with the same name, and the command `--get-O365-drive-id` was returning the first one only.

I make a call(Using `curl`) to the same API that `onedrive` uses to retrieve the second libraries ID and then I could sync the "right" library.

I know that is is unusual, but would be nice if `onedrive` could print all IDs it has received that match the Library name.

If you guys think it is ok, I could send a PR, will be something very easy to do and would save some time for others out there with the same rare issue.

The change will be here: [sync.d:1896](https://github.com/abraunegg/onedrive/blob/master/src/sync.d#L1896)

**Application and Operating System Details:**
*   OS: `Debian 9` - `Linux smb 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux`
*   `headless`
*   OneDrive Account Type `SharePoint`
*   `DMD64 D Compiler v2.084.0`
*   Application configuration: 
```
onedrive version                    = v2.2.5
Config path                         = /root/.config/onedrive
Config file found in config path    = true
Config option 'sync_dir'            = /srv/SharePoint
Config option 'skip_file'           = ~*
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'log_dir'             = /var/log/onedrive/
Config option 'drive_id'            = xxxxxxxxxxxxxxxxxxx
Selective sync configured           = false
```
*   `curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3`

**Comment by abraunegg** [comment]
@0x3333 
Can you please provide some JSON evidence that the libraries are indeed the same - potentially using MS Graph Explorer to query all the site names?

**Comment by abraunegg** [comment]
@0x3333 
Please can you help validate PR #354
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/354/head:pr354
git checkout pr354
make
```

**Comment by abraunegg** [comment]
PR #354 merged

**Comment by abraunegg** [comment]
Closing case as PR merged
