### ISSUE TITLE
Make sync mode(default, download-only , upload-only, local-first, no-remote-delete) an option in config

### ISSUE THREAD

**Issue by CaulyKan** [abraunegg/onedrive#356]
When using docker with onedrive, it's quite a difficult work to modify entrypoint.sh and change arguments of onedrive command. So it would be better to make use of config file to take full control of onedrive behavior, especially the sync mode.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a `sync_mode` option to config file, available values:
- default
- upload-only
- download-only 
- local-first
- no-remote-delete
and use them the same way they work in arguments.

**Comment by abraunegg** [comment]
@CaulyKan 
It is certainly an interesting use case, however I need to understand further how any why 'modify entrypoint.sh and change arguments' is so difficult in a docker environment.

@norbusan 
Agree - the proposed method is sub-optimal.

Potentially what would be better is:
```
cli_options = "<your desired options> eg: --single-directory 'blah' --upload-only"
```

This then could accept any number of valid parameters, with then any actual CLI entries taking further priority.

> So if we go in this direction, I suggest that every command line option can have a respective setting in the config file, and the command line takes priority over the config file (as usual).

We could also go in this direction where the command line option makes sense for a 'config' file option. Switches like `--source-directory` & `--destination-directory` for moving folders on OneDrive would not make much sense to have a 'config' file option.

**Comment by norbusan** [comment]
@abraunegg agreed that some switched don't make sense, indeed.

Concerning the `cli_options` versus single options, I am undecided. Parsing the `cli_options` with spaces, embedded " etc might be a bit a pain. Also I think that having single options is a bit clearer.

So *I* would tend to have single options instead of one `cli_options`, but it is really a matter of taste and I don't have strong feelings about it.

If we agree on one method, I can look at the implemetation

**Comment by CaulyKan** [comment]
As far as I can tell, there are several ways to modify entrypoint.sh:
1. clone the repo and edit entrypoint.sh, then docker build. 
2. make a new dockerfile like 'FROM origin CP new_entrypoint.sh ENTRYPOINT new_entrypoint.sh' and build it. 
3. run the image and then `exec -it bash` into it and vi entrypoint.sh. However I'm not sure why this method can't be used becaused every time I try to do this with onedrive container I got an EOF only.

The third way have other problem: when the container starts the sync starts immediately. If I want to change to upload-only I have to disable the config to make the sync fail.

**Comment by norbusan** [comment]
I agree with @CaulyKan that adjustment of the docker entry points is not what we want to be necessary. In an ideal world it should be as described in the `docker/README.md` and configuration option can simply be set in via `-v onedrive_conf:/onedrive/conf` which makes maintenance much easier.

**Comment by norbusan** [comment]
@CaulyKan gui discussion is not really related here, but no, nobody works on it AFAIS. I have looked into writing a applet in D, but GUI toolkits for D are rare and a bit a pain. Furthermore, the current onedrive client is not set up in a way that it could communicate with a frontend (no multi-threading, information handling ...).

So writing a GUI - even a self-contained web ui which needs support from the backend - is future work which we haven't initiated by now.

**Comment by abraunegg** [comment]
> @abraunegg agreed that some switches don't make sense, indeed.
> 
> Concerning the `cli_options` versus single options, I am undecided. Parsing the `cli_options` with spaces, embedded " etc might be a bit a pain. Also I think that having single options is a bit clearer.
> 
> So _I_ would tend to have single options instead of one `cli_options`, but it is really a matter of taste and I don't have strong feelings about it.
> 
> If we agree on one method, I can look at the implemetation

If it is simpler & easier for each option to have it's own 'config' option, then no issue there.

**Comment by abraunegg** [comment]
@CaulyKan 
Can you please help test and evaluate PR #389 against this feature request to have all CLI options as a config file option?
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/389/head:pr389
git checkout pr389
make
make install
```

**Comment by norbusan** [comment]
Merge into master, I think this can be closed.

**Comment by abraunegg** [comment]
PR #389 merged

**Comment by abraunegg** [comment]
Re-opening issue as PR #389 broke client configuration option parsing

**Comment by CaulyKan** [comment]
eh...document not updated? not sure how to start with the new version, where shall I put sync mode in config?

**Comment by abraunegg** [comment]
@CaulyKan 
Can you please help test and evaluate PR #449 against this feature request to have all CLI options as a config file option?
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/449/head:pr449
git checkout pr449
make
make install
```

Any feedback you have is greatly appreciated

**Comment by abraunegg** [comment]
Closing as PR #449 merged
