### ISSUE TITLE
Questions on functions

### ISSUE THREAD

**Issue by takelley1** [abraunegg/onedrive#360]
- What’s the difference between —synchronize and —resync? They both seem to do the same thing. Does resync force overwriting of the database but synchronize picks back up where it left off?

- What’s the difference between —synchronize and —monitor? Does monitor only look for changes in files that have already been synchronized? If so, then do I have to —resync when new files are added?

- Do I only have to synchronize once? If not, how often?

**Comment by abraunegg** [comment]
@takelley1 
Basically you should **only** use `--resync` if:
* You change the 'sync_dir' config
* You change the 'skip_file' config
* You change the 'sync_list' config
* You are having some sort of database issue and the client directs you to do so

The differences between `--resync` & `--synchronize` are:
* `--resync` does nothing on its own
* `--resync` when used with `--synchronize` or `--monitor` will clean up the local database and remove the local 'sync state' that is stored locally - thus essentially performing a 'resync' to OneDrive

The differences between `--monitor` & `--synchronize` are:
* `--synchronize` is best used when you want to sync in an ad-hoc fashion under your control - bash script or manual execution
* `--monitor` is best used when running as a service file as it 'loops' the application constantly based on 'monitor_interval'. Additionally, `--monitor` monitors your local 'sync_dir' for local file changes & uploads them to OneDrive immediately. 


> Do I only have to synchronize once? If not, how often?

Only you know the answer to that. This depends on how often you want your data to be in sync, the volume and rate of local & remote change - this is something I cannot advise on.

**Comment by abraunegg** [comment]
Closing issue as answer provided
