### ISSUE TITLE
Access OneDrive with custom "client_id"

### ISSUE THREAD

**Issue by chiriaev** [abraunegg/onedrive#371]
Guys, Hi. Is it in the plans to allow a "client_id" override with the on disk configuration, so that one could get his own Microsoft "application" used instead of the one you provide by default, "OneDrive Free Client"?

Also, is there a way to upload specific content and shutdown the client? A once-off upload for an artifact generated by Jenkins, for example.

Thanks in advance.

Regards, Andrei

**Comment by abraunegg** [comment]
> Guys, Hi. Is it in the plans to allow a "client_id" override with the on disk configuration, so that one could get his own Microsoft "application" used instead of the one you provide by default, "OneDrive Free Client"?

Not at this stage. Feel free to fork & make changes to use your own client identifier however is the best work around.

> Also, is there a way to upload specific content and shutdown the client? A once-off upload for an artifact generated by Jenkins, for example.

You can do this with the client - just run the client using `--synchronize`  and utilise `--single-directory` to specify the correct folder under your sync directory containing the Jenkins output.

Individual file sync is not supported

**Comment by chiriaev** [comment]
@abraunegg, Hi. Thanks for this. Would it be alright to ask for an enhancement request(s) for the aforementioned? I am quite unfortunately not very fluent with D these days. I hope you understand.

Regards, Andrei

**Comment by abraunegg** [comment]
@chiriaev 
I won't be adding an easy capability to change the client identifier. Changing that is a one line code change & only needs to be done if your getting your own application id, of which then, you most likely will be maintaining your own fork of the client to handle that change.

In terms of 'Also, is there a way to upload specific content and shutdown the client?' - the current client does this today and provides various CLI options to get that job done as previously indicated. You could also utilise the `--upload-only` & `--no-remote-delete` to ensure that it is a one way transfer without removing content on OneDrive.
