### ISSUE TITLE
Not an Issue... But a massive thanks!!

### ISSUE THREAD

**Issue by ADun3306x** [abraunegg/onedrive#377]
Hi @abraunegg ,

Not an issue to report, but a massive thanks for your recent assistance with my issues on an older branch of this OneDrive Git

Your branch also works like a charm, and has stopped me from pulling my hair out re locked dbs

Legend!

**Comment by abraunegg** [comment]
@ADun3306x 
Thanks for the feedback :) greatly appreciated

**Comment by xinchaosong** [comment]
Hi, @abraunegg, I would like to say thank you too. You saved my day!
