### ISSUE TITLE
Shared Folder in OneDrive for Business

### ISSUE THREAD

**Issue by christiancloudibility** [abraunegg/onedrive#382]
First of all - Big thanks for that tool, makes working so much easier :)

Is it possible to integrate shared folder-syncing?
As it is not possible, to add the folders to mine, the way it is provided in your How-To unfortunately is not working in that case.

As I do not know, what you need or if I can help you any how on this, just feel free to ask for informations!

Greetings,
Chris

**Comment by abraunegg** [comment]
@christiancloudibility

I am trying to understand what your after and whats not working for you - as its not clear.

Can you try and elaborate further, use screen shots or diagrams to assist.

Shared folders work totally different between personal and business accounts. Personal accounts you can add a shared folder to your account, business accounts you cant.

**Comment by christiancloudibility** [comment]
Thanks for the fast reply, that is exactly what I meant :)

Is there a way to synchronize shared folders with business accounts?
Sorry If that wasn't that clear

**Comment by abraunegg** [comment]
@christiancloudibility 
The only way to sync a Business Shared Folder is to follow [these](https://github.com/abraunegg/onedrive/blob/master/README.Office365.md) directions

You cant add / sync a Personal Shared Folder to a Business Account

**Comment by christiancloudibility** [comment]
Hey @abraunegg,

thank you for that reply, sad that it's not possible, but I even wanted to ask ;)
The Library instruction is interesting nevertheless, didn't saw that !

Greetings,

Christian

**Comment by abraunegg** [comment]
closing case as question answered

**Comment by abraunegg** [comment]
@christiancloudibility 
Business Shared Folders is currently a feature which is in BETA

Please can you help test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/473/head:pr473
git checkout pr473
make clean; make;
```

**Note:** This PR should be considered BETA quality as I have only tested this against use basic use cases.

Please refer to https://github.com/abraunegg/onedrive/pull/473#issuecomment-485629549 on how to configure & use this feature.

If you can test and provide feedback that is greatly appreciated.

**Comment by abraunegg** [comment]
@christiancloudibility 
Any update in being able to test the PR for this feature request?

**Comment by abraunegg** [comment]
@christiancloudibility
Any update in being able to test the PR for this feature request?

**Comment by abraunegg** [comment]
@christiancloudibility 
forgot to unlock this thread - will close in favour of tracking via #459
