### ISSUE TITLE
Local deleted not deleted from OneDrive using --synchronize

### ISSUE THREAD

**Issue by 0x3333** [abraunegg/onedrive#383]
### Bug Report Details ###
If I delete a folder with files from my local filesystem, the removed files aren't deleted from the OneDrive. In the first sync(database `items.sqlite3` deleted  and using `--resync`) it will upload the files as expected, but after deleting the FileBB.txt and doing a synchronization, the file is not deleted from OneDrive.
I have a pretty much specific configuration, which I believe is causing the issue.

Setup description: I have a Samba File Server with several folders and files in it. I need to sync some folders to OneDrive, but with a different folder structure. To allow this, I created the needed folder structure in another folder(`/srv/samba/OneDrive`) and created some symlinks to the folders in the file server, this way, I have a custom folder structure in OneDrive without affecting my File Server. Here is my filesystem structure:

```
File Server structure(There are files in those folders)
/srv/samba/Share1/FolderA/FolderAA/FolderAAA
/srv/samba/Share2/FolderB/FolderBB/FolderBBB
/srv/samba/Share3/FolderC/FolderCC/FolderCCC

OneDrive sync folder structure:
/srv/samba/OneDrive/.config/
/srv/samba/OneDrive/FileServer/FolderBB (symlink to /srv/samba/Share2/FolderB/FolderBB)
/srv/samba/OneDrive/FileServer/FolderCCC (symlink to /srv/samba/Share3/FolderC/FolderCC/FolderCCC)
```

**Application and Operating System Details:**

* OneDrive Office 365 Account
* Headless
```
$ uname -a
Linux smb 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux

$ curl --version
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

$ onedrive --confdir /srv/samba/OneDrive/.config/ --display-config
onedrive version                    = v2.2.5
Config path                         = /srv/samba/OneDrive/.config/
Config file found in config path    = true
Config option 'sync_dir'            = /srv/samba/OneDrive
Config option 'skip_file'           = .*|~*
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = true
sync_list contents:
FileServer/FolderBB
FileServer/FolderCCC

$ find -L /srv/samba/OneDrive
.
./.config
./.config/refresh_token
./.config/config
./.config/sync_list
./FileServer
./FileServer/FolderBB
./FileServer/FolderBB/FileBB.txt
./FileServer/FolderCCC
./FileServer/FolderCCC/FileCCC.txt
```

**Complete Verbose Log Output**
```
$ onedrive --confdir /srv/samba/OneDrive/.config/ --verbose --synchronize --resync
Loading config ...
Using Config Dir: /srv/samba/OneDrive/.config/
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /srv/samba/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!TIHf06O2FD2UTFZK3HGivR2sRCEmzcmzIB2c6an3iRRRAcJuw7x74HsQlWaZkAnD
Default Root ID: FSFKWSMQKOIZ4RZCJCTZ1F2CYWXSNHOHFW5
Remaining Free Space: 1099484754045
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: FSFKWSMQKOIZ4RZCJCTZ1F2CYWXSNHOHFW5
Uploading differences of .
Processing root
Uploading new items of .
Skipping item - excluded by skip_file config: ./.config
OneDrive Client requested to create remote path: ./FileServer
The requested directory to create was not found on OneDrive - creating remote directory: ./FileServer
Successfully created the remote directory ./FileServer on OneDrive
OneDrive Client requested to create remote path: ./FileServer/FolderBB
The requested directory to create was not found on OneDrive - creating remote directory: ./FileServer/FolderBB
Successfully created the remote directory ./FileServer/FolderBB on OneDrive
Uploading file ./FileServer/FolderBB/FileBB.txt ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:
 done.
Remaining free space: 1099484754034
OneDrive Client requested to create remote path: ./FileServer/FolderCCC
The requested directory to create was not found on OneDrive - creating remote directory: ./FileServer/FolderCCC
Successfully created the remote directory ./FileServer/FolderCCC on OneDrive
Uploading file ./FileServer/FolderCCC/FileCCC.txt ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:
 done.
Remaining free space: 1099484754022
Applying changes of Path ID: FSFKWSMQKOIZ4RZCJCTZ1F2CYWXSNHOHFW5

$ rm FileServer/FolderBB/FileBB.txt

$ find -L .
.
./.config
./.config/items.sqlite3
./.config/refresh_token
./.config/config
./.config/sync_list
./FileServer
./FileServer/FolderBB
./FileServer/FolderCCC
./FileServer/FolderCCC/FileCCC.txt

$ onedrive --confdir /srv/samba/OneDrive/.config/ --verbose --synchronize
Loading config ...
Using Config Dir: /srv/samba/OneDrive/.config/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /srv/samba/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!TIHf06O2FD2UTFZK3HGivR2sRCEmzcmzIB2c6an3iRRRAcJuw7x74HsQlWaZkAnD
Default Root ID: FSFKWSMQKOIZ4RZCJCTZ1F2CYWXSNHOHFW5
Remaining Free Space: 1099484752242
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: FSFKWSMQKOIZ4RZCJCTZ1F2CYWXSNHOHFW5
Uploading differences of .
Processing root
Uploading new items of .
Skipping item - excluded by skip_file config: ./.config
Applying changes of Path ID: FSFKWSMQKOIZ4RZCJCTZ1F2CYWXSNHOHFW5
```

After the last command, `--synchronize` the file is not deleted in the OneDrive folder online, but I believe it should.

**Comment by 0x3333** [comment]
I upgraded to the last master commit, no go.

```
$ onedrive --version
onedrive v2.2.5-30-g4e12496
```

**Comment by abraunegg** [comment]
@0x3333 
The first issue I see is the following:
```
Config option 'skip_file'           = .*|~*
```

This tells me that at some point you were using the 'skilion' client, and upgraded to this branch, however the 'config' file was not updated. Potentially this needs to be made clearer in the readme in the upgrading section.

Can you please do the following:

1. Update your `skip_file = "= .*|~*"` to `skip_file = "~*"` ... this step is very important.
2. Make a backup of your 'items.sqlite3' for safe keeping & then remove it
3. Run `onedrive --confdir /srv/samba/OneDrive/.config/ --verbose --synchronize`

Please advise what is now occurring when syncing after making that config change. Locally deleted files should be deleted without issue on OneDrive.

**Comment by 0x3333** [comment]
Well, I didn't used the skilion client before, but I copied from the README.md file, the `skip_file` section has an example, which I copied.

```
skip_file

Example: skip_file = ".*|~*|Desktop|Documents/OneNote*|Documents/IISExpress|Documents/SQL Server Management Studio|Documents/Visual Studio*|Documents/config.xlaunch|Documents/WindowsPowerShell"

Patterns are case insensitive. * and ? wildcards characters are supported. Use | to separate multiple patterns.
```

The idea is to ignore the `.config` folder from the `sync_dir` folder. Are dot files ignored by default?

I tried removing the `.*` and it worked!

Would you mind explaining why? I can write some doc regarding this situation.

Thanks for your help.

**Comment by abraunegg** [comment]
@0x3333 
OK .. no worries - will have to ensure that the readme get's updated to remove that as well .. it is a left over from the 'skilion' documentation.

**Comment by abraunegg** [comment]
@0x3333 
I have created PR #384 to correct the documentation issue:

https://github.com/abraunegg/onedrive/blob/8c0063b26d69f1dd81ef29c368263a921c805eab/README.md

If you can review & validate that would be greatly appreciated.

**Comment by 0x3333** [comment]
Will be dot files ignored by default?

**Comment by abraunegg** [comment]
> Patterns are case insensitive. * and ? wildcards characters are supported. Use | to separate multiple patterns.
> ```
> The idea is to ignore the `.config` folder from the `sync_dir` folder. Are dot files ignored by default?
> 
> I tried removing the `.*` and it worked!
> 
> Would you mind explaining why? I can write some doc regarding this situation.
> 
> Thanks for your help.

The original 'skilion' code pattern matching was broken, which was caused by the `.*` 

> Will be dot files ignored by default?

No, .files will not be ignored. They will be treated as valid files.

**Comment by abraunegg** [comment]
@0x3333 
A new PR #386 will implement a new CLI flag to skip dot files & folders.

It is currently in development progress. Once complete, if you can assist by testing that would be greatly appreciated.

**Comment by 0x3333** [comment]
Count on me! Thanks.
