### ISSUE TITLE
Access OneDrive service through proxy

### ISSUE THREAD

**Issue by philthynz** [abraunegg/onedrive#398]
We use a proxy in our company.

I have set a proxy in `~/.bashrc` with:
```
http_proxy=http://proxy:8080
https_proxy=https://proxy:8080
export http_proxy
export https_proxy
```

This works when authorising the client and running `onedrive --synchronize`. However the service the ondrive has a `Cannot initialize connection to OneDrive` error.

How can we push the service daemon through a proxy?

**Comment by abraunegg** [comment]
@philthynz 
When you use the bashrc to force the connection that way, does your proxy prompt for additional authentication (username / password)?

**Comment by philthynz** [comment]
@abraunegg Nope, this proxy requires no auth. Same one works for apt, firefox, and the initial auth... but now, even the sync does not work. Running `onedrive --synchronize` gives a `No network connection to Microsoft OneDrive Service`.

Is there another way to run this through a proxy? Other than adding the proxy to ~/.bashrc?

**Comment by abraunegg** [comment]
@philthynz 
If running as a systemd service, you could try modifying the onedrive service file:
```
[Unit]
Description=OneDrive Free Client
Documentation=https://github.com/abraunegg/onedrive
After=network-online.target
Wants=network-online.target

[Service]
Environment="HTTP_PROXY=http://10.112.1.100:8080"
Environment="HTTPS_PROXY=http://10.112.1.100:8080"
Environment="FTP_PROXY=http://10.112.1.100:8080"
ExecStart=/usr/local/bin/onedrive --monitor
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
```

**Comment by abraunegg** [comment]
@philthynz
Any update in testing the above solution?

**Comment by philthynz** [comment]
I updated `/usr/lib/systemd/user/onedrive.service` with

```
Environment="HTTP_PROXY=http://proxy:8080"
Environment="HTTPS_PROXY=http://proxy:8080"
Environment="FTP_PROXY=http://proxy:8080"
```
Restarted the service, and still have a `No network connection to Microsoft OneDrive Service`

I will remove and re-install it. Strange it worked with the first auth and first sync

**Comment by abraunegg** [comment]
@philthynz
Thanks for the feedback. 

It looks like a additional code will be needed to support sending traffic via a proxy

**Comment by philthynz** [comment]
Actually.. it does work. I modified the wrong service, as I'm using it as non root user. I had to change `/usr/lib/systemd/system/onedrive@.service` and add:
```
Environment="HTTP_PROXY=http://proxy:8080"
Environment="HTTPS_PROXY=http://proxy:8080"
``` 

Then run `sudo systemctl daemon-reload`

After that it went through the proxy.

Thanks for the help.

**Comment by abraunegg** [comment]
@philthynz 
Thanks for the feedback - will add this to the documentation

**Comment by abraunegg** [comment]
@philthynz 
Closing case as PR #403 merged
