### ISSUE TITLE
Can I safely remove ~/onedrive and ~/dlang after successful install?

### ISSUE THREAD

**Issue by emubite** [abraunegg/onedrive#400]
After successfully installing, is it safe to remove the ~/onedrive and ~/dlang folders from my home directory?

Thanks for maintaining this project, BTW.

**Comment by abraunegg** [comment]
@emubite
It is certainly safe to remove both folders. 

If you ever need to reinstall or rebuild a newer version however, you will need to reinstall DMD / LDC to compile.

**Comment by emubite** [comment]
Thanks for your prompt response! Keep up the great work.
