### ISSUE TITLE
Cannot Initialize Sync Engine 'HTTP 401 Unauthorized' any run after auth procedure

### ISSUE THREAD

**Issue by etalot** [abraunegg/onedrive#401]
### Bug Report Details ###
2-nd and next runs fail with Cannot Initialize Sync Engine 'HTTP 401 Unauthorized'

**Application and Operating System Details:**
Linux 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
no gui
*   OneDrive Account Type: regular
*   Application configuration:
godot@server:~$ onedrive --display-config
onedrive version                    = v2.2.5-6-g61c40c6
Config path                         = /home/godot/.config/onedrive
Config file found in config path    = false
Config option 'sync_dir'            = /home/godot/OneDrive
Config option 'skip_file'           = ~*
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false

*   Curl Version: curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3

**To Reproduce**
run onedrive second time

**Complete Verbose Log Output**
1-st run:
```onedrive --synchronize --verbose
Loading config ...
Using Config Dir: /home/godot/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49386-d21c-4792-aed1-8f163c9853246&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: Opening the item database ...
All operations will be performed in: /home/godot/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 2caeb47c55074cc7
Default Root ID: 2CAEB47C55074CC7!103
Remaining Free Space: 5348801124
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 2CAEB33C12074CC7!103
Uploading differences of .
Processing root
The directory has not changed
Processing Getting started with OneDrive.pdf
```

Token was created
```
godot@server:~$ ls -l .config/onedrive/refresh_token
-rw-rw-r-- 1 godot godot 389 Mar  7 03:36 .config/onedrive/refresh_token
```

2-nd run:
```$ onedrive --synchronize --verbose
Loading config ...
Using Config Dir: /home/godot/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/godot/OneDrive
Initializing the Synchronization Engine ...

ERROR: OneDrive returned a 'HTTP 401 Unauthorized' - Cannot Initialize Sync Engine
ERROR: Check your configuration as your access token may be empty or invalid```

All tokens and IDs was changed in security reasons.

**Comment by abraunegg** [comment]
@etalot 
Please can you validate the contents of the refresh_token file

As per https://github.com/skilion/onedrive/issues/446 you make the following comment:

> it is excluded. I remove refresh_token, and app creates new with content.

What do you mean by: 'it is excluded' ?

Can you please advise?

Is the 'refresh_token' being updated / re-created every run?

What is the difference in the file between 1st sync and 2nd sync?

Additionally, in https://github.com/skilion/onedrive/issues/446 you make the following comment:

> Look, I run client on my dedicated server in Finland.
> Auth link open on my PC in Vietnam copy back to Finland server.

Potentially this could be the cause as the authentication / validation is coming from 2 different regions. Is there a way for you to test the authentication / application locally in the same region?

**Comment by abraunegg** [comment]
Additionally your application version of `v2.2.5-6-g61c40c6` is rather old.

Please ensure you are running against the latest 'master' please

**Comment by etalot** [comment]
Okey. Updated. After made --logout and Auth procedure again:

`$ onedrive --display-config
onedrive version                    = v2.2.5-38-gba83436
Config path                         = /home/godot/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/godot/OneDrive
Config option 'skip_file'           = ~*
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false
godot@server:~$ onedrive --synchronize
Initializing the Synchronization Engine ...

ERROR: OneDrive returned a 'HTTP 401 Unauthorized' - Cannot Initialize Sync Engine
ERROR: Check your configuration as your access token may be empty or invalid`

**Comment by abraunegg** [comment]
@etalot 
Please can you answer the other questions as well:

1. What do you mean by: 'it is excluded' ?
2. Is the 'refresh_token' being updated / re-created every run?
3. What is the difference in the file between 1st sync and 2nd sync?

The error you are seeing can ONLY occur in the following instance:

1. The file is empty
2. The file has the wrong permissions
3. The file is corrupt
4. The file contents has changed between sync 1 and sync 2 / been modified by another process

**Comment by etalot** [comment]
1. I mean "It can not be", you asked me about something before, and I answered "it is excluded" in meaning "It can not be". File is not empty. opendrive after auth procedure successfully create ".config/onedrive/refresh_token" with content like:
`$ cat .config/onedrive/refresh_token
MCe0KfzqLYEnp0NLYpYzUmDrxD6oJubGvxVLNAgDzFS4QVpp5r*uf6fnbsTjVLE0L0eA6L7iaTYEkQ0QJ12QSclscoHUTClTzYIDeGwmOVyC5Ts2b!sfCOXFDDqjBKJwkGDrOI*u5pvqVQmuoNX!fOKE*eTCdQ!C31YFY7YJeyE1xKJniemkGnskQkuGRDMqbqNWRSTafV03IdTWsE123TazEqWSoVRyz3oGrVZWtbXaG6zfSDMyRxbzhAdD6TFmlOdqB5fKkNaEOXIFRxrcRxGeo8eMFl60mMC6E*F6DbfzERTnOQ!TIPyuyd!P7VnuWu1bgJSfJhMmdnpI*VhicxWzxJGuJf8YvWezZ3yAM6N5StS7AdIJpWbcFAz!fnhfSHA$$`

2. No, Permition is good 664, and owner/group is good user user
3. I don't think so. Server is new and it serve users.

**Comment by abraunegg** [comment]
@etalot 
Can you please do the following:
1. Delete `~/.config/onedrive/refresh_token` 
2. Re-authorise by this explicit command ONLY: `onedrive`. After auth, it WILL complain that no --sync or --monitor was passed in
3. Run `cat ~/.config/onedrive/refresh_token | wc -m` 
4. Run `cp ~/.config/onedrive/refresh_token ~/.config/onedrive/refresh_token.backup`
5. Run a sync using `onedrive --synchronize --verbose`
6. Run `diff ~/.config/onedrive/refresh_token ~/.config/onedrive/refresh_token.backup`
7. Run a sync using `onedrive --synchronize --verbose`
8. Run `cp ~/.config/onedrive/refresh_token ~/.config/onedrive/refresh_token.backup2`


A script similar to the following:
```
rm ~/.config/onedrive/refresh_token
./onedrive
cat ~/.config/onedrive/refresh_token | wc -m
ls -la ~/.config/onedrive/refresh_token
cp ~/.config/onedrive/refresh_token ~/.config/onedrive/refresh_token.original
./onedrive --synchronize --verbose
cat ~/.config/onedrive/refresh_token | wc -m
ls -la ~/.config/onedrive/refresh_token
cp ~/.config/onedrive/refresh_token ~/.config/onedrive/refresh_token.after_sync_1
./onedrive --synchronize --verbose
cat ~/.config/onedrive/refresh_token | wc -m
ls -la ~/.config/onedrive/refresh_token
cp ~/.config/onedrive/refresh_token ~/.config/onedrive/refresh_token.after_sync_2
diff ~/.config/onedrive/refresh_token.original ~/.config/onedrive/refresh_token
diff ~/.config/onedrive/refresh_token.original ~/.config/onedrive/refresh_token.after_sync_1
diff ~/.config/onedrive/refresh_token.original ~/.config/onedrive/refresh_token.after_sync_2
```


Please modify the above for your use and post the entire results as outputted for analysis please

**Comment by etalot** [comment]
It's easy.

```$ onedrive
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=68c49a0d-d21c-4292-aed1-8f163c985812&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=Md47451f8-a2ab-1281-be0d-cbc2726a0642

--synchronize or --monitor missing from your command options or use --help for further assistance

No OneDrive sync will be performed without either of these two arguments being present

$ cat ~/.config/onedrive/refresh_token | wc -m
389

$ ls -la ~/.config/onedrive/refresh_token
-rw-rw-r-- 1 godot godot 389 Mar  7 10:06 /home/godot/.config/onedrive/refresh_token

$ cp ~/.config/onedrive/refresh_token ~/.config/onedrive/refresh_token.original

$ onedrive --synchronize --verbose
Loading config ...
Using Config Dir: /home/godot/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/godot/OneDrive
Initializing the Synchronization Engine ...

ERROR: OneDrive returned a 'HTTP 401 Unauthorized' - Cannot Initialize Sync Engine
ERROR: Check your configuration as your access token may be empty or invalid

$ cat ~/.config/onedrive/refresh_token | wc -m
389

$ ls -la ~/.config/onedrive/refresh_token
-rw-rw-r-- 1 godot godot 389 Mar  7 10:06 /home/godot/.config/onedrive/refresh_token

$ cp ~/.config/onedrive/refresh_token ~/.config/onedrive/refresh_token.after_sync_1
$ onedrive --synchronize --verbose
Loading config ...
Using Config Dir: /home/godot/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/godot/OneDrive
Initializing the Synchronization Engine ...

ERROR: OneDrive returned a 'HTTP 401 Unauthorized' - Cannot Initialize Sync Engine
ERROR: Check your configuration as your access token may be empty or invalid

$ cat ~/.config/onedrive/refresh_token | wc -m
389

$ ls -la ~/.config/onedrive/refresh_token
-rw-rw-r-- 1 godot godot 389 Mar  7 10:06 /home/godot/.config/onedrive/refresh_token

$ cp ~/.config/onedrive/refresh_token ~/.config/onedrive/refresh_token.after_sync_2

$ diff ~/.config/onedrive/refresh_token.original ~/.config/onedrive/refresh_token

$ diff ~/.config/onedrive/refresh_token.original ~/.config/onedrive/refresh_token.after_sync_1

$ diff ~/.config/onedrive/refresh_token.original ~/.config/onedrive/refresh_token.after_sync_2

```

PS: Trick:
$ cp ~/.config/onedrive/refresh_token{,.after_sync_1}
is qual
$ cp ~/.config/onedrive/refresh_token ~/.config/onedrive/refresh_token.after_sync_1

=)

**Comment by abraunegg** [comment]
@etalot 
OK .. so your `refresh_token` is not being updated.

After every sync attempt, this should be updated. What was the 'actual' output of the diff ?

**Comment by etalot** [comment]
diff output is empty. No different's

**Comment by abraunegg** [comment]
@etalot 
OK .. that is **NOT** normal.

Can you do the following:

1. Get a Linux machine 'local' to you and test the sync process - ie - not in Finland but local to you in Vietnam. Validate that it is able to sync OK with your credentials.
2. Get a 'new' remote Linux machine, maybe a test system on Amazon AWS or other - something NOT hosted by the same provider in Finland. Validate that your 'authorise locally' but 'run remote' process works - it should, as I have tested on AWS instances in US, EU without issue.

What we need to do is determine that it is something to do with the Linux server you have remote. Potentially as per my initial suspicions in https://github.com/skilion/onedrive/issues/446 that if the application is writing an invalid token, the token being received by the application is either being modified by some sort of man-in-the-middle attack or you have some sort of SSL / HTTPS inspection going on that is mangling the data.

**Comment by abraunegg** [comment]
@etalot 
Can you please provide an update as to your testing on a 'local' system and an 'alternate' remote system not provided by your current remote provider.

I have tested again this morning with an AWS instance in the EU (Germany) and found no issue - able to sync and perform all operations as per normal

Something either in Finland is caching the HTTPS responses and badly responding with stale data or is modifying the traffic between the client & OneDrive service for this to be failing the way that it is.

**Comment by norbusan** [comment]
Could this be a proxy issue? The copying of URL into the browser would work, because the browser has proxies set up, but onedrive itself hasn't?

**Comment by abraunegg** [comment]
@etalot 
Please can you provide an update

**Comment by etalot** [comment]
> 1. Get a Linux machine 'local' to you and test the sync process - ie - not in Finland but local to you in Vietnam. Validate that it is able to sync OK with your credentials.

I can not. It will take a lot of time. I have second server in Germany. Same provider - HETZNER. But it's old CentOS system. Installing new apps is real hell.

> 2. Get a 'new' remote Linux machine, maybe a test system on Amazon AWS or other - something NOT hosted by the same provider in Finland. Validate that your 'authorise locally' but 'run remote' process works - it should, as I have tested on AWS instances in US, EU without issue.

Don't have time for this.

> What we need to do is determine that it is something to do with the Linux server you have remote. Potentially as per my initial suspicions in [skilion#446](https://github.com/skilion/onedrive/issues/446) that if the application is writing an invalid token, the token being received by the application is either being modified by some sort of man-in-the-middle attack or you have some sort of SSL / HTTPS inspection going on that is mangling the data.

I think just MS is piece of SH*T. Like in old times =)
I tried Official Opendrive SDK (https://github.com/xybu/onedrived-dev), doesn't work. =)
Fail on auth step.
I give up.

> Could this be a proxy issue? The copying of URL into the browser would work, because the browser has proxies set up, but onedrive itself hasn't?

I'm in Vietnam, and make auth procedure on my Win10 PC, linux server in Finland.
In run with auth procedure onedrive sync successfully. 

PS: I use HETZNER for 6 years and never had problem any service(that needed real IP)

**Comment by abraunegg** [comment]
@etalot 
Well given I cannot reproduce your issue, and by the sounds of it not willing to help progress the diagnosis of the issue - not much else I can do to help you out - sorry.

**Comment by etalot** [comment]
OK, Thank you for help!
