### ISSUE TITLE
OAuth2 authorization process force download "nativeclient" at end with chrome

### ISSUE THREAD

**Issue by prodigy7** [abraunegg/onedrive#405]
I compiled the current version and try to setup onedrive. Using the auth url in google chrome force download of a empty file with name "nativeclient". Same process with Internet Explorer returns url which I can use for setup.

**Comment by abraunegg** [comment]
@prodigy7 
This is not a bug with the client.

This is a bug with Microsoft and the OneDrive website. Please submit an issue for this here: https://github.com/OneDrive/onedrive-api-docs/issues

The auth process works with:
* Firefox
* IE

Fails with:
* Chrome (for the last ~1-2 weeks from what I can determine)

This means that there has been an API change on the Microsoft end to incorrectly handle Chrome as a browser to perform the authentication steps.

**Comment by abraunegg** [comment]
Submitted issue here: https://github.com/OneDrive/onedrive-api-docs/issues/1019
