### ISSUE TITLE
Better error reporting when case-insensitive clashes occur

### ISSUE THREAD

**Issue by norbusan** [abraunegg/onedrive#406]
While testing the dry-run option I saw this
```
ERROR: A local directory has the same name as another local directory.
ERROR: To resolve, rename this local directory: /home/norbert/OneDriveTest/./foobar
```
and indeed, there is `Foobar` and `foobar` in my onedrive. We could do a better message here - maybe ...

**Comment by abraunegg** [comment]
@norbusan 
Just wondering what a better message could be ?

**Comment by abraunegg** [comment]
@norbusan 
Can you check PR #412 ?

**Comment by abraunegg** [comment]
Closing issue as PR #412 merged
