### ISSUE TITLE
Sharepoint folder of Office 365 

### ISSUE THREAD

**Issue by Kilok** [abraunegg/onedrive#415]
Can you add an extra option to change the path of sync of Sharepoint folders?
for eample: drive_id_with_sync_dir = ("insert the drive id from above here","dir path")

**Comment by abraunegg** [comment]
@Kilok
This would be better handled by having separate configuration files where you specify `drive_id` & `sync_dir` then utilise `--confdir` to call that configuration.

**Comment by Kilok** [comment]
Then, can you add an option to only sync sharepoint folders. Because I tried to sync my main folder with one process and one of the sharepoint folders with other, skiping the main folders in  the socond process. And with minimal change in my main onedrive, the sharepoint process download it.

**Comment by abraunegg** [comment]
> Then, can you add an option to only sync sharepoint folders. Because I tried to sync my main folder with one process and one of the sharepoint folders with other, skiping the main folders in the socond process. And with minimal change in my main onedrive, the sharepoint process download it.

Post deleted before able to respond.

Unsure what your attempting to do here. You most certainly can do this with the client.

**Comment by abraunegg** [comment]
Closing issue as question answered
