### ISSUE TITLE
Make fails for tar download

### ISSUE THREAD

**Issue by psmit** [abraunegg/onedrive#416]
### Bug Report Details ###
**Make fails for download of release tarball**

**Application and Operating System Details:**
*   OS: Arch Linux

### Bug Report Checklist ###
*   Download release tarball and run `make` in the right directory
*   Make fails with `make: *** No rule to make target '.git/HEAD', needed by 'version'.  Stop.`

There should be some mechanism to build anyway without building from a git checkout.

**Comment by abraunegg** [comment]
@psmit 
Thanks for the bug report. Due to the nature of this one, whilst it will be fixed in master, it wont get fixed in the release archive until the next release.

**Comment by abraunegg** [comment]
@psmit 
PR #417 will resolve this issue once merged, however will not be fully fixed until the next release.

**Comment by psmit** [comment]
Sure, totally understand! Thanks for the quick patch.

**Comment by abraunegg** [comment]
Closing issue - PR #417 merged
