### ISSUE TITLE
Remote change discarded - not in --single-directory scope

### ISSUE THREAD

**Issue by wiryonolau** [abraunegg/onedrive#428]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
Syncing share folder using Add to my onedrive produce a lot of "Remote change discarded - not in --single-directory scope"

All shared folder file is flagging as unwanted, e.g item.driveId (74076a283bf6cedb), item.parentId (74076A283BF6CEDB!104) not in local database

**Application and Operating System Details:**
Build using Dockerfile inside repository
*   OS: CentOS Linux release 7.6.1810 (Core), Linux 4.15.0-46-generic 
*   No Gui
*   Personal account
*   DMD or LDC compiler version : Not installed in docker container
*   Application configuration: 
```
onedrive version                    = v2.2.6
Config path                         = /root/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /root/OneDrive
Config option 'skip_file'           = ~*
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false
```
*   Curl Version: curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.36 zlib/1.2.7 libidn/1.28 libssh2/1.4.3

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  git clone https://github.com/abraunegg/onedrive.git
2.  cd onedrive
3.  git checkout v2.2.6
3.  docker build -t abraunegg/onedrive . ( using default Dockerfile )
4.  docker run -it --restart unless-stopped --name onedrive -v "${onedriveConf}:/onedrive/conf" -v "${onedriveDir}:/onedrive/data" abraunegg/onedrive
5.  Set the key
6.  export ARGS="--monitor --verbose --verbose --confdir /onedrive/conf --syncdir /onedrive/data --synchronize --force-http-1.1"
7.  docker run --name onedrive -v "${onedriveConf}:/onedrive/conf" -v "${onedriveDir}:/onedrive/data" abraunegg/onedrive ${ARGS}

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```text
onedrive
++ stat /onedrive/data -c %u
+ ONEDRIVE_UID=1000
++ stat /onedrive/data -c %g
+ ONEDRIVE_GID=1000
++ getent group 1000
+ odgroup=
+ odgroup=onedrive
+ groupadd onedrive -g 1000
++ getent passwd 1000
+ oduser=
+ oduser=onedrive
+ useradd onedrive -u 1000 -g 1000
+ chown onedrive:onedrive /onedrive/ /onedrive/conf
+ ARGS=(--monitor --verbose --confdir /onedrive/conf --syncdir /onedrive/data)
+ '[' 9 -gt 0 ']'
+ ARGS=("${@}")
+ exec gosu onedrive /usr/local/bin/onedrive --monitor --verbose --verbose --confdir /onedrive/conf --syncdir /onedrive/data --synchronize --force-http-1.1
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/onedrive
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/onedrive/.config
[DEBUG] configDirName: CLI override to set configDirName to: /onedrive/conf
Loading config ...
Using Config Dir: /onedrive/conf
No config file found, using application defaults
[DEBUG] CLI override to set sync_dir to: /onedrive/data 
[DEBUG] sync_dir: No SHELL or USER environment variable configuration detected
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] syncDir: /onedrive/data
Initializing the OneDrive API ...
[DEBUG] Downgrading all HTTP operations to HTTP 1.1
Opening the item database ...
[DEBUG] Using database file: /onedrive/conf/items.sqlite3
All operations will be performed in: /onedrive/data
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: bbb6b5e0f1eeb9b0
Default Root ID: BBB6B5E0F1EEB9B0!166
Remaining Free Space: 1103082380889
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: BBB6B5E0F1EEB9B0!166
[DEBUG] Sync Folder Name: root
[DEBUG] Number of changes from OneDrive to process: 0
Applying changes of Path ID: 74076A283BF6CEDB!11756
[DEBUG] Sync Folder Name: Group - TEST
[DEBUG] Sync Folder Path: /drives/74076a283bf6cedb/items/74076A283BF6CEDB!104:
[DEBUG] Sync Folder Child Path: /drives/74076a283bf6cedb/items/74076A283BF6CEDB!104:/Group - TEST/
Processing 200 changes
[DEBUG] ------------------------------------------------------------------
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDo3NDA3NkEyODNCRjZDRURCITExNzU2LjYzNjg4ODMxMDUxODUwMDAwMA","eTag":"aNzQwNzZBMjgzQkY2Q0VEQiExMTc1Ni4z","fileSystemInfo":{"createdDateTime":"2017-05-02T05:32:41Z","lastModifiedDateTime":"2017-06-14T01:37:05Z"},"folder":{"childCount":0,"view":{"sortBy":"name","sortOrder":"ascending","viewType":"thumbnails"}},"id":"74076A283BF6CEDB!11756","name":"Group - TEST","parentReference":{"driveId":"74076a283bf6cedb","driveType":"personal","id":"74076A283BF6CEDB!104","name":"Documents","path":"\/drives\/74076a283bf6cedb\/items\/74076A283BF6CEDB!104:"},"size":2434051330}
[DEBUG] 'search id'                                       = 74076A283BF6CEDB!11756
[DEBUG] 'parentReference id'                              = 74076A283BF6CEDB!104
[DEBUG] syncFolderPath                                    = /drives/74076a283bf6cedb/items/74076A283BF6CEDB!104:
[DEBUG] syncFolderChildPath                               = /drives/74076a283bf6cedb/items/74076A283BF6CEDB!104:/Group - TEST/
[DEBUG] thisItemId                                        = 74076A283BF6CEDB!11756
[DEBUG] thisItemPath                                      = /drives/74076a283bf6cedb/items/74076A283BF6CEDB!104:
[DEBUG] 'item id' matches search 'id'                     = true
[DEBUG] 'parentReference id' matches search 'id'          = false
[DEBUG] 'item path' contains 'syncFolderChildPath'        = false
[DEBUG] 'item path' contains search 'id'                  = false
[DEBUG] Change matches search criteria to apply
[DEBUG] The item we are syncing is a folder
[DEBUG] Flagging as unwanted: item.driveId (74076a283bf6cedb), item.parentId (74076A283BF6CEDB!104) not in local database
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] ------------------------------------------------------------------
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"aYzo3NDA3NkEyODNCRjZDRURCITE0NTQzLjU2Mg","eTag":"aNzQwNzZBMjgzQkY2Q0VEQiExNDU0My4zNQ","file":{"hashes":{"sha1Hash":"5D7A7277E0DA482A00EB594235AD2E2AF71437F1"},"mimeType":"application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},"fileSystemInfo":{"createdDateTime":"2017-09-01T10:31:13.83Z","lastModifiedDateTime":"2017-09-08T08:40:22.422Z"},"id":"74076A283BF6CEDB!14543","name":"test.xlsx","parentReference":{"driveId":"74076a283bf6cedb","driveType":"personal","id":"74076A283BF6CEDB!11756","name":"Group - TEST","path":"\/drives\/74076a283bf6cedb\/items\/74076A283BF6CEDB!104:\/Group%20-%20TEST"},"size":11971}
[DEBUG] 'search id'                                       = 74076A283BF6CEDB!11756
[DEBUG] 'parentReference id'                              = 74076A283BF6CEDB!11756
[DEBUG] syncFolderPath                                    = /drives/74076a283bf6cedb/items/74076A283BF6CEDB!104:
[DEBUG] syncFolderChildPath                               = /drives/74076a283bf6cedb/items/74076A283BF6CEDB!104:/Group - TEST/
[DEBUG] thisItemId                                        = 74076A283BF6CEDB!14543
[DEBUG] thisItemPath                                      = /drives/74076a283bf6cedb/items/74076A283BF6CEDB!104:/Group%20-%TEST
[DEBUG] 'item id' matches search 'id'                     = false
[DEBUG] 'parentReference id' matches search 'id'          = true
[DEBUG] 'item path' contains 'syncFolderChildPath'        = false
[DEBUG] 'item path' contains search 'id'                  = false
[DEBUG] Change matches search criteria to apply
[DEBUG] Flagging as unwanted: find(item.parentId).length != 0
[DEBUG] Flagging as unwanted: item name is excluded: test.xlsx
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] ------------------------------------------------------------------

# REPEAT for the rest of the shared folder file, top is for Directory, the bottom is File
```

**Screenshots**
None

**Additional context**
None

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output

**Comment by abraunegg** [comment]
@wiryonolau 
Please can you edit your post and follow the directions as per https://github.com/abraunegg/onedrive#reporting-issues for reporting an issue.

Thanks

**Comment by abraunegg** [comment]
@wiryonolau 
Please can you respond

**Comment by wiryonolau** [comment]
Sorry been busy, will try to update it today.

**Comment by abraunegg** [comment]
@wiryonolau 
Thanks for providing the updated information - greatly appreciated.

First issue is this:
```
--monitor --verbose --verbose --confdir /onedrive/conf --syncdir /onedrive/data --synchronize --force-http-1.1
```

You cannot / should not use `--monitor` or `--synchronize` together - its one or the other - not both. Doing so will have undesirable effects, but this is not the cause of your problem.

So just to confirm my understanding of the issue & bug:

* Your attempting to sync a new file / folder from a shared folder and the change is being discarded

**Comment by wiryonolau** [comment]
ok will remove --monitor then, I thought it cause by missing --synchronize option.

So after I started onedrive client, I go to onedrive web and "add shared folder to my onedrive" , then It goes on like that.

**Comment by wiryonolau** [comment]
I never use d language, perhaps different text case in driveId ?

[DEBUG] Flagging as unwanted: item.driveId (74076a283bf6cedb), item.parentId (74076A283BF6CEDB!104) not in local database

**Comment by abraunegg** [comment]
@wiryonolau 
I have attempted to replicate locally with multiple OneDrive shared folders & cannot reproduce.

Can you please email your `items.sqlite3` to support@mynas.com.au for analysis

**Comment by wiryonolau** [comment]
I don't think I cant give you the items.sqlite3 it shared with company file. I'll try rebuilt with empty config

**Comment by abraunegg** [comment]
In that case:

* rebuild your client from 'master'
* delete / rename that file
* perform a sync and advise the outcome

**Comment by wiryonolau** [comment]
Do we need the parent folder to be added add, or we can just add subfolder from shared ?

The company shared a whole "Documents" folder, but I want to add only one of the folder inside this "Documents". This shouldn't be a problem right ?

**Comment by abraunegg** [comment]
Most likely this will cause the issue your seeing - as the parent is not in the database - thus not in scope.

If it is simply you dont want to download - you need to exclude the directories or utilise sync_list to explicitly include all the directories you want to sync

**Comment by wiryonolau** [comment]
I'll test clean sync first. Does changing sync_list require reun using --resync if we use --monitor ?

**Comment by abraunegg** [comment]
> I'll test clean sync first. Does changing sync_list require reun using --resync if we use --monitor ?

Any use / change of configuration requires `--resync` as per readme

**Comment by wiryonolau** [comment]
Ok it's working, for shared we can only add the root foler from shared list in onedrive web and use sync_list to choose. Closing Issue. Thank you
