### ISSUE TITLE
Slow synchornization due to inotify seems not working

### ISSUE THREAD

**Issue by jfvelezserrano** [abraunegg/onedrive#432]
## Bug Report Details ###
From past week, real time detection seems not work in any of my computers. Every time that I make --synchronize **the application iterates over all the files to detect changes**. 

I have been using abraunegg/onedrive several weeks, and before I used skillion. They always worked like a charm. They didn't need to iterate for all the files to detect changes.

But now the --synchronize --verbose display a lot of messages like:
```
Processing EficienciaEnergetica
The directory has not changed
Processing DocumentoPresentacionCertificado.pdf
The file has not changed
Processing ResguardoCM.pdf
The file has not changed
Processing EfienciaEnerge
```

More over, due to the huge amount of messages and the long time in synchronization, the CPU is always at 100% (in one core) when the monitor is active.

## Configuration details ## 
OneDrive bussines.
More that 90k files
Same problem in Kubuntu 18.04 and Neon 18.04
DMD64 D Compiler v2.082.0

My configuration is:
Config path                         = /home/jvelez/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/jvelez/Cloud/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 120
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false

curl 7.63.0

Same problem with --force-http-1.1

## Steps to reproduce the behavior ##

1.  Install
2. synchronize
3. synchronize again (or monitorize)

**Comment by abraunegg** [comment]
@jfvelezserrano 
Please can you test this PR to resolve your high CPU issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/419/head:pr419
git checkout pr419
make
make install
```

**Comment by abraunegg** [comment]
> From past week, real time detection seems not work in any of my computers. Every time that I make --synchronize **the application iterates over all the files to detect changes**.
> 
> I have been using abraunegg/onedrive several weeks, and before I used skillion. They always worked like a charm. They didn't need to iterate for all the files to detect changes.
> 
> But now the --synchronize --verbose display a lot of messages like:
> 
> ```
> Processing EficienciaEnergetica
> The directory has not changed
> Processing DocumentoPresentacionCertificado.pdf
> The file has not changed
> Processing ResguardoCM.pdf
> The file has not changed
> Processing EfienciaEnerge
> ```

This is normal. As you upgraded from the 'skilion' version did you follow the upgrade process by removing your local database cache?

> More over, due to the huge amount of messages and the long time in synchronization, the CPU is always at 100% (in one core) when the monitor is active.

This is not normal, and is a bug as per #404

**Comment by jfvelezserrano** [comment]
> @jfvelezserrano
> Please can you test this PR to resolve your high CPU issue:
> 
> ```
> git clone https://github.com/abraunegg/onedrive.git
> cd onedrive
> git fetch origin pull/419/head:pr419
> git checkout pr419
> make
> make install
> ```

With that version, the CPU keeps low usage values.

However, in my case there are a lot of messages of type "Processing 204 changes","Processing 208 changes"... As I do not modify any file, I don't understand what means these messages. And the synchronize operation is very slow.

By other way, you say that it is normal to scan all the local files looking for changes in each synchronize operation. But I believed that inotify allows to detect changes in the files without to scan all the files.

In any case thank you for this great job. 

Finally, I'm working in a little GUI for this program that perhaps you could consider.
![Screenshot](https://user-images.githubusercontent.com/655188/54873097-c9c1c880-4dcf-11e9-8033-0746a6e9ff37.png)

**Comment by abraunegg** [comment]
> With that version, the CPU keeps low usage values.
> 
> However, in my case there are a lot of messages of type "Processing 204 changes","Processing 208 changes"... As I do not modify any file, I don't understand what means these messages. And the synchronize operation is very slow.

That is normal as the database is being re-created. That will be a one time deal.

> By other way, you say that it is normal to scan all the local files looking for changes in each synchronize operation. But I believed that inotify allows to detect changes in the files without to scan all the files.

To clarify - `inotify` is only used to scan for / trigger new uploads that are created locally.

The scan process you are seeing, is a 'sync' with OneDrive to ensure that all files locally are 'in-sync' - to ensure that if any file is modified on OneDrive, this change is picked up. `inotify` will not do this.

**Comment by jfvelezserrano** [comment]
Ok. Thank you for the clarification respect the operative of inotify.

With the tested version the CPU remain at 100%, but the synchronization time is significantly shorter. The previous version took 15 minutes, and the version that you pointed to me only takes 45 seconds.
![Screenshot](https://user-images.githubusercontent.com/655188/54876224-a9fcc580-4e0c-11e9-8eae-368bafc74cc3.png)

**Comment by abraunegg** [comment]
@jfvelezserrano 
This all looks normal to me with using the PR which has also been merged into master.

Will look into how to reduce 'needless' scanning of the local system for changes down via PR #433

**Comment by abraunegg** [comment]
@jfvelezserrano 
Can you please help test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/433/head:pr433
git checkout pr433
make clean; make;
```

This should also reduce frequent CPU load, however a full scan of your `sync_dir` would now occur every N cycles (default is 10)

If you can test & provide feedback that would be greatly appreciated.

**Comment by jfvelezserrano** [comment]
I think that this great improvement is working very well.

In the test I have been deleting some files and creating other ones. The CPU only seems to take 100% of CPU when changes are performed.

If this works so well, perhaps, a full sync is only necessary at startup.

When using libreoffice, it usually create temporal files. Now, I think that it is important to configure skipping this files to avoid unnecessary uploads (see the screenshot to view an example).

![Screenshot_20190331_090827](https://user-images.githubusercontent.com/655188/55285914-b943bc00-5394-11e9-87d6-5645bd063294.png)

**Comment by abraunegg** [comment]
@jfvelezserrano 
You probably then also need the fixes as per #442, specifically then this: https://github.com/abraunegg/onedrive/pull/442/commits/6172e323be2072cfe108387e5cc277e709c5bf91

Both #433 and #442 will be in the v2.3.2 release

**Comment by jfvelezserrano** [comment]
After watching more slowly the system monitor and the verbose mode, I see that full synchronizations remain every 120 seconds (weeks ago I changed the default value to 120 seconds).

The new system detects changes in the directory immediately, but the synchronization occurs any way in each period.
![Screenshot](https://user-images.githubusercontent.com/655188/55286392-ae405a00-539b-11e9-9ae6-f353039affa4.png)

**Comment by abraunegg** [comment]
Are you sure you are running the right PR?

#433 most certainly changes the full sync to 1st run at startup then 1 every 10 ..

**Comment by jfvelezserrano** [comment]
You are right. I needed to execute 'make install'. Now it works as you described.

**Comment by abraunegg** [comment]
@jfvelezserrano 
Please can you provide some feedback as to how this PR works for you in further reducing load on the system

**Comment by jfvelezserrano** [comment]
This PR has consumed 16 minutes and 42 seconds of CPU in 9 hours. This is 1002 seconds.

My system makes full synchronization every 1200 seconds (10 x 120 s). So, it did 27 full syncs in 9 hours. 

I have 80k files, and each full sync takes 40 seconds aprox. So it is 1080 seconds.

I can conclude that, the time used by this PR corresponds to the expected time.

**Comment by abraunegg** [comment]
@jfvelezserrano 
Thanks for the feedback

**Comment by abraunegg** [comment]
Closing issue as PR #433 merged into master
