### ISSUE TITLE
Problem install after compiling of 2.3.0

### ISSUE THREAD

**Issue by Boia11** [abraunegg/onedrive#436]
I have try to install 2.3.0 release on Debian ARM64 but after compling successfull, I receive this error:
```
~/onedrive# sudo make install
echo v2.3.0 > version
dmd -w -g -ofonedrive -O  -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d
make: dmd: Command not found
Makefile:78: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127

```

**Comment by abraunegg** [comment]
@Boia11 
You did not activate 'dmd' as per the readme: https://github.com/abraunegg/onedrive/blob/master/README.md#compilation--installation and as per https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions#make-command-during-installation-encounters-error-127

**Comment by Boia11** [comment]
> 
> 
> @Boia11
> You did not activate 'dmd' as per the readme: https://github.com/abraunegg/onedrive/blob/master/README.md#compilation--installation and as per https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions#make-command-during-installation-encounters-error-127

This is not the problem, I solve with a simple run of command:
`make install DC=~/ldc2-1.14.0-linux-aarch64/bin/ldmd2 `

**Comment by abraunegg** [comment]
Yep  - that will work too - and as per the readme for ARM64:

https://github.com/abraunegg/onedrive/blob/master/README.md#arm64-architecture

**Comment by Boia11** [comment]
> 
> 
> Yep - that will work too - and as per the readme for ARM64:
> 
> https://github.com/abraunegg/onedrive/blob/master/README.md#arm64-architecture
Yes, I do that like "readme.md":
```
make DC=~/ldc2-1.14.0-linux-aarch64/bin/ldmd2
sudo make install
```
But I need to run `sudo make install DC=~/ldc2-1.14.0-linux-aarch64/bin/ldmd2` because the simple `sudo make install` return error 127. With previously release the simple command work fine

**Comment by abraunegg** [comment]
OK .. 'make install' should not be rebuilding the client. I think this is being triggered by the .PHONY change.

Please can you help validate PR #439:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/439/head:pr439
git checkout pr439
make clean; make;
```

**Comment by Boia11** [comment]
> 
> 
> OK .. 'make install' should not be rebuilding the client. I think this is being triggered by the .PHONY change.
> 
> Please can you help validate PR #439:
> 
> ```
> git clone https://github.com/abraunegg/onedrive.git
> cd onedrive
> git fetch origin pull/439/head:pr439
> git checkout pr439
> make clean; make;
> ```

The 2.3.1 install perfectly working
