### ISSUE TITLE
Some notes

### ISSUE THREAD

**Issue by frispete** [abraunegg/onedrive#438]
Dear @abraunegg,

sorry for opening an issue for this, but I didn't find your email address anywhere.

I just want to inform you, that I build rpms for the current onedrive version for openSUSE here:

https://build.opensuse.org/package/show/home:frispete:onedrive/onedrive

The build still uses a simple patch in order to adhere to the usual packaging constraints, that are:
 * chown commands removed: these are not allowed during build due to security concerns and are handled for rpm builds with %attr() macros in the %files section anyway
 * .PHONY: version removed: now, that version is a real file, .PHONY doesn't make much sense, since it results in compiling onedrive twice (once in %build and once in %install)

While the first issue could be solved to be executed, when running make install as root, the second may be worth generally.

Since I'm quite happy with the state and performance, I'm going to submit this package to openSUSE:Factory soon.

**Comment by abraunegg** [comment]
Thanks

re .PHONY - that is fixed in PR #439, and as a result will be pushing a 2.3.1 release today. That was implemented as a fix due to version never being updated once written - thus became stale. make clean also never cleaned up the version file - now it does with #439

**Comment by abraunegg** [comment]
Also for an email address - can always send an email to support@mynas.com.au

**Comment by abraunegg** [comment]
Closing issue as 2.3.0 is replaced with 2.3.1 where match for .PHONY is now not required.
