### ISSUE TITLE
Handling error 412 (Precondition failed)

### ISSUE THREAD

**Issue by celsosuz** [abraunegg/onedrive#444]
To handle the error 412 properly in upload methods (sync.d source file) I had to throw OneDriveException in both checkHttpCode methods when the code is 412 in onedrive.d file.

**Comment by abraunegg** [comment]
@celsosuz 
Please can you edit your post and follow the directions as per https://github.com/abraunegg/onedrive#reporting-issues for reporting an issue & any details around any crash or problem you fixed

Thanks
