### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by celiapgt** [abraunegg/onedrive#45]
I couldn't find somewhere else to thank you for forking the code.
Your version contains many improvements (as far as I can see).

THANKS!!!

**Comment by abraunegg** [comment]
Thanks for the feedback :)

**Comment by EvoBiomech** [comment]
Just to second that - awesome, thanks!

**Comment by coxackie** [comment]
I third it! really good job - works very well. I know it is a long shot (and by no means essential), but is there any chance of future support of an indicator on the DE to notify for syncing, etc?

**Comment by plembo** [comment]
My thanks as well for stepping up and keeping the dream alive. Well, OK, maybe not _the_ dream -- but a damned fine convenience nonetheless.

**Comment by turekm** [comment]
also another thanks :) good work

**Comment by lorenzosu** [comment]
Really thanks to @abraunegg for the dedication and commends for the patience and responsiveness with issues and user interaction!
This project IMHO is really filling a huge gap in the lack of official support from Microsoft for Linux users and I really look forward to the new features and a growing community :-)

**Comment by happycod3r** [comment]
another thanks  :D great work

**Comment by ricksorensen** [comment]
And another many kudos for keeping this utility going.  Tremendously useful.  I really like some of the new features (e.g. uplink only)

**Comment by GammaPi** [comment]
@abraunegg It's reaaaaaaaaaaaaaaly very helpful program!
Works flawlessly, which seems to be more outstanding when programs in the old repo just screwed up my bakcup files lol.

**Comment by GammaPi** [comment]
Hopefully when I have time I can contribute to this project too!
