### ISSUE TITLE
Support terminal completions

### ISSUE THREAD

**Issue by Modelmat** [abraunegg/onedrive#454]
**Is your feature request related to a problem? Please describe.**
When running onedrive from the terminal, terminal completions are a very useful feature.

**Describe the solution you'd like**
Support zsh (or any other terminal) completions. Some shells like [zsh](https://github.com/zsh-users/zsh-completions) have places to submit the completions to come as default.

**Describe alternatives you've considered**
N/A

![image](https://user-images.githubusercontent.com/25718989/55664003-0fbc6900-5873-11e9-9d58-2b30286d64ec.png)

**Comment by norbusan** [comment]
I like the idea - I will look into it. For bash I can easily write completion. For zsh I'm not sure, their syntax is - well to be polite - very interesting ;-)

**Comment by norbusan** [comment]
Hi @Modelmat 
I have written something up for bash for now, mind trying out this one: https://github.com/abraunegg/onedrive/blob/norbert/completion/completions/complete.bash
For zsh I am a bit at loss, I will look into more examples and try to come up with something.

**Comment by abraunegg** [comment]
@Modelmat 
Please can you help test the following PR for this feature request:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/460/head:pr460
git checkout pr460
make clean; make; 
sudo make install COMPLETIONS=1;
```

**Comment by Modelmat** [comment]
Bash completions work fine without needing to change `.bashrc`. (I have bash-completions installed).
Zsh completions work with the `fpath=(/usr/local/share/zsh/site-functions $fpath)` and then following the rest of the steps by @norbusan.

This is great, thanks!

**Comment by norbusan** [comment]
Hi @Modelmat , can you show me the output of `echo $fpath` *before* adding the above? I thought from what I read on the zsh dev list that the above path is *always* included. Which distribution are you using?

**Comment by Modelmat** [comment]
Oh, sorry. I just realised I didn't do `compinit` in my zshrc (and I followed it manually).
I was just looking at that going, thinking that it was already in the path.

**Comment by norbusan** [comment]
Ok, so it works as expected. Great - thanks for testing.

**Comment by abraunegg** [comment]
PR merged, closing issue
