### ISSUE TITLE
directories named 'root' are not replicated to centos 7

### ISSUE THREAD

**Issue by pzi123** [abraunegg/onedrive#456]
### Bug Report Details ###
I have a few directories named 'root' in my onedrive. None of them and everything below are visible/available on Centos 7 tree.

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
```
pzi@pzi-gw-6:~/onedrive$ uname -a
Linux pzi-gw-6 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
pzi@pzi-gw-6:~/onedrive$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```
*   Are you using a headless system (no gui) or with a gui installed?
no gui

*   OneDrive Account Type
OneDrive+50

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
```
pzi@pzi-gw-6:~$ . ~/dlang/dmd-*/activate
(dmd-2.085.0)pzi@pzi-gw-6:~$ dmd --version
DMD64 D Compiler v2.085.0
Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright
```
*   Application configuration: Output of `onedrive --display-config`
```
(dmd-2.085.0)pzi@pzi-gw-6:~$ onedrive --display-config
onedrive version                    = v2.2.6-5-g58c2805
Config path                         = /home/pzi/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/pzi/OneDrive
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|*.swp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = true
sync_list contents:
.sync
notes
```
*   Curl Version: Output of `curl --version`
```
(dmd-2.085.0)pzi@pzi-gw-6:~$ curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.36 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
```

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Create directory 'root' in widows OneDrive:

PS C:\Users\Peter\OneDrive\notes> mkdir root

2. and then look for it in Linux ~/OneDrive

(dmd-2.085.0)pzi@pzi-gw-6:~/OneDrive/notes$ ls root
ls: cannot access root: No such file or directory

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment]
@pzi123 
```
onedrive version = v2.2.6-5-g58c2805
```
Please can you update your application to the latest release or master version & retest.

Also please can you provide a proper verbose debug log as per: https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

**Comment by abraunegg** [comment]
@pzi123 
Additionally - you have not specified how your running the application on your Linux system

**Comment by pzi123** [comment]
I did a 'git pull' in my ~/onedrive directory and rebuilt (make clean; make; sudo make install).
Now I am running:
pzi@pzi-gw-6:~$ onedrive --version
onedrive v2.3.2-2-gea2e4a9

I am running onedrive from the systemd service and redirecting the logs to syslog.
I run the verbose output generation and it looks like this found the issue right away. The onedrive terminates right after finding 'root' folder. Here is the tail part of the log:

pzi@pzi-gw-6:~$ onedrive --synchronize --verbose --verbose | tee debug_output.log 2>&1

[DEBUG] Checking file: ./notes/ldap/notes-1
[DEBUG] Checking file: ./notes/ldap/notes
[DEBUG] Checking file: ./notes/ldap/config_ref.gif
[DEBUG] Checking file: ./notes/ldap/iplanet
[DEBUG] Checking file: ./notes/ldap/,.l
[DEBUG] Checking path: ./notes/netcat
[DEBUG] Checking file: ./notes/netcat/notes
Applying changes of Path ID: DE985A79DED9042C!150
[DEBUG] Sync Folder Name: root
[DEBUG] Number of changes from OneDrive to process: 0

I use a workaround and rename the 'root' directories to something like 'root2' and these work fine.

**Comment by abraunegg** [comment]
@pzi123 
Please can you help validate this PR to resolve your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/457/head:pr457
git checkout pr457
make clean; make;
```

**Comment by pzi123** [comment]
Moved old ~/onedrive to ~/onedrive- and followed your instructions and build in a clean directory. I also did installation with 'sudo make install'. Now at:

pzi@pzi-gw-6:~$ onedrive --version
onedrive v2.3.2-3-gd2d7890

Rerun the test with the same result:

pzi@pzi-gw-6:~$ onedrive --synchronize --verbose --verbose | tee debug_output.log 2>&1
...
[DEBUG] Checking file: ./notes/ldap/MigrationTools-44/migrate_all_nisplus_offline.sh
[DEBUG] Checking file: ./notes/ldap/MigrationTools-44/migrate_fstab.pl
[DEBUG] Checking file: ./notes/ldap/MigrationTools-44/migrate_profile.pl
[DEBUG] Checking file: ./notes/ldap/MigrationTools-44/migrate_automount.pl-
[DEBUG] Checking file: ./notes/ldap/MigrationTools-44/migrate_common.ph
[DEBUG] Checking file: ./notes/ldap/MigrationTools-44/migrate_networks.pl
[DEBUG] Checking file: ./notes/ldap/notes-1
[DEBUG] Checking file: ./notes/ldap/notes
[DEBUG] Checking file: ./notes/ldap/config_ref.gif
[DEBUG] Checking file: ./notes/ldap/iplanet
[DEBUG] Checking file: ./notes/ldap/,.l
[DEBUG] Checking path: ./notes/netcat
[DEBUG] Checking file: ./notes/netcat/notes
Applying changes of Path ID: DE985A79DED9042C!150
[DEBUG] Sync Folder Name: root
[DEBUG] Number of changes from OneDrive to process: 0

**Comment by abraunegg** [comment]
can you revalidate - as now, with my local testing a local directory called 'root' is created:
```
(dmd-2.085.0)[alex@centos7full fix-issue-456]$ ./onedrive --confdir '~/.config/onedrive-business' --synchronize --verbose --resync          
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-business
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!xA9hqR7mT0OL6Gku8YbuzTJ8oZmRnQZJu6-yDL49Zc5MccrHbuT0R4QUwIzUvbJY
Default Root ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1098672456121
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
Processing 5 changes
Downloading file Document.docx ... done.
Creating directory: blah
Creating directory: blah/root
Creating directory: root
Uploading differences of .
Processing root
The directory has not changed
Processing Document.docx
The file has not changed
Processing blah
The directory has not changed
Processing root
The directory has not changed
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
(dmd-2.085.0)[alex@centos7full fix-issue-456]$ 
```

**Comment by abraunegg** [comment]
without patch:
```
(dmd-2.085.0)[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-business' --synchronize --verbose --resync
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-business
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!xA9hqR7mT0OL6Gku8YbuzTJ8oZmRnQZJu6-yDL49Zc5MccrHbuT0R4QUwIzUvbJY
Default Root ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1098672456121
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
Processing 5 changes
Downloading file Document.docx ... done.
Creating directory: blah
Uploading differences of .
Processing root
The directory has not changed
Processing Document.docx
The file has not changed
Processing blah
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
(dmd-2.085.0)[alex@centos7full onedrive]$ 
```
with patch:
```
(dmd-2.085.0)[alex@centos7full onedrive-pr457]$ ./onedrive --confdir '~/.config/onedrive-business' --synchronize --verbose --resync
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-business
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!xA9hqR7mT0OL6Gku8YbuzTJ8oZmRnQZJu6-yDL49Zc5MccrHbuT0R4QUwIzUvbJY
Default Root ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1098672456121
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
Processing 5 changes
Creating directory: blah/root
Creating directory: root
Uploading differences of .
Processing root
The directory has not changed
Processing Document.docx
The file has not changed
Processing blah
The directory has not changed
Processing root
The directory has not changed
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
(dmd-2.085.0)[alex@centos7full onedrive-pr457]$ 
```

**Comment by pzi123** [comment]
No. My 'root' directories are not created on the linux server.  I create them on windows then run the linux onedrive as ordinary user - here pzi.

**Comment by pzi123** [comment]
will resume tomorrow...

**Comment by abraunegg** [comment]
@pzi123 
Please can you re-try but run a non service / monitor mode sync whilst using `--resync` to force the database to create the correct objects. 

The new 'root' folders should be created without issue as per my testing and examples.

**Comment by abraunegg** [comment]
@pzi123 
confirmed - with this PR and **NOT** adding `--resync` additional 'root' named folders are not created:
```
(dmd-2.085.0)[alex@centos7full onedrive-pr457]$ ./onedrive --confdir '~/.config/onedrive-business' --synchronize --verbose 
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-business
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!xA9hqR7mT0OL6Gku8YbuzTJ8oZmRnQZJu6-yDL49Zc5MccrHbuT0R4QUwIzUvbJY
Default Root ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1098672456121
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing Document.docx
The file has not changed
Processing blah
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
(dmd-2.085.0)[alex@centos7full onedrive-pr457]$ 
```

**Comment by pzi123** [comment]
It worked with --resync - Thanks!

Let's see if adding/removing 'root' directories works under the service 
run mode.

I have the following service definition:


cat <<EOF > /etc/systemd/system/onedrive.service
[Unit]
Description=OneDrive Free Client
Documentation=https://github.com/skilion/onedrive

[Service]
ExecStart=/usr/local/bin/onedrive -m -v --confdir=/home/pzi/.config/onedrive
User=pzi
#StandardOutput=/var/tmp/onedrive.log
#StandardError=/var/tmp/onedrive.log
StandardOutput=syslog
StandardError=syslog
Restart=on-failure
RestartSec=3


[Install]
WantedBy=default.target

EOF



On 4/8/2019 12:48 AM, abraunegg wrote:
> |--synchronize --verbose --resync|

-- 
Peter Ziobrzynski, mailto:pzi@pzi.net

**Comment by pzi123** [comment]
And service mode works fine also. Thanks again!

BTW - what was the bug? It is hard to imagine that we had a hardcoded 
'root' string somewhere.

On 4/8/2019 7:18 AM, Peter Ziobrzynski wrote:
>
> It worked with --resync - Thanks!
>
> Let's see if adding/removing 'root' directories works under the 
> service run mode.
>
> I have the following service definition:
>
>
> cat <<EOF > /etc/systemd/system/onedrive.service
> [Unit]
> Description=OneDrive Free Client
> Documentation=https://github.com/skilion/onedrive
>
> [Service]
> ExecStart=/usr/local/bin/onedrive -m -v 
> --confdir=/home/pzi/.config/onedrive
> User=pzi
> #StandardOutput=/var/tmp/onedrive.log
> #StandardError=/var/tmp/onedrive.log
> StandardOutput=syslog
> StandardError=syslog
> Restart=on-failure
> RestartSec=3
>
>
> [Install]
> WantedBy=default.target
>
> EOF
>
>
>
> On 4/8/2019 12:48 AM, abraunegg wrote:
>> |--synchronize --verbose --resync|
> -- 
> Peter Ziobrzynski,mailto:pzi@pzi.net

-- 
Peter Ziobrzynski, mailto:pzi@pzi.net

**Comment by abraunegg** [comment]
The bug was an additional validation was needed for 'root' items, as your use case was triggering a false positive.

Closing case as PR #457 merged
