### ISSUE TITLE
Warn on big deletes

### ISSUE THREAD

**Issue by norbusan** [abraunegg/onedrive#458]
While testing a PR I just did something stupid - I exchanged `--confdir` with `--syncdir` which removed **a lot** very quickly ;-)

It would be nice if we could somehow detect such large deletes and warn or ask for confirmation.

**Comment by abraunegg** [comment]
@norbusan 
No way to really know if you really meant to do an `rm -rf` or anything else as well ... unsure how this could be trapped for ... maybe an expansion of `--dry-run` where you prompt at the end of running it to run without??

Unsure how else to prevent / not run in the event of 'large change'

**Comment by norbusan** [comment]
I am fine with getting asked to confirm. Other sync programs sometimes have options like "warn on big deletes". SO say a config option 1Gb that if more than this file size (or number of files?) are removed, one needs to confirm (or pass in `--force`). Just an idea... I will look into it myself.

**Comment by abraunegg** [comment]
Potentially work in with what is discussed in #280 - store last run config in DB, if change, warn?

**Comment by abraunegg** [comment]
@norbusan 
I think potentially the changes in #617 negates the need for this warning on big deletes - as changes where a --resync is needed, will now fail fast, rather than proceed & do mass delete which is what you originally experienced. Should this be closed or do you want to look at some other option / alternative as well ?

**Comment by norbusan** [comment]
Hmmm, I am not sure. I am imagining other big changes, like accidentally removing a huge directory, or similar. In this case a warning might be useful? But maybe not, you are right ... there is anyway the history function in OneDrive ;-)

**Comment by abraunegg** [comment]
@norbusan 
**Assumptions:**
* --syncdir change which will delete files on OneDrive will be detected with PR #617
* If running in monitor mode, a local `rm -rf` will delete a local directory and a inotify will issue a delete, delete the files on OneDrive right away - no way to prevent this, can prevent the delete, but then users will have no idea why the delete did not occur, have to restart service / monitor process etc.
* If running in standalone mode, a local `rm -rf` will delete a local directory but will not replicate to OneDrive until next manual sync

In this last assumption, a check can be made from the DB as to how many 'children' are affected by the delete, thus warn or not process unless a --force is issued

What sort of other use case were you thinking in regards to this?

**Comment by abraunegg** [comment]
PR Testing assistance required:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/621/head:pr621
git checkout pr621
make clean; ./configure; make;
```

**Changes:**
* If deleting many objects, if that object count is > 1000, an error message will display & sync will be halted
* If that sync is required, the added use of `--force` is needed
* Mass delete detection has zero impact when using `--monitor`

**Comment by abraunegg** [comment]
Closing issue as PR #621 merged into master
