### ISSUE TITLE
--get-O365-drive-id doesn't show a Sharepoint drive

### ISSUE THREAD

**Issue by obilodeau** [abraunegg/onedrive#461]
### Bug Report Details ###
**Describe the bug**
Trying to sync to a Sharepoint / Office365 shared drive, I can't find it with `--get-O365-drive-id`:

```
$ onedrive --verbose --verbose --get-O365-drive-id Research
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/olivier
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/olivier/.config
[DEBUG] configDirName: Configuring application to use default config path
Loading config ...
Using Config Dir: /home/olivier/.config/onedrive
No config file found, using application defaults
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /home/olivier/OneDrive
Initializing the OneDrive API ...
Opening the item database ...
[DEBUG] Using database file: /home/olivier/.config/onedrive/items.sqlite3
All operations will be performed in: /home/olivier/OneDrive
[DEBUG] Configuring skip_dir ...
[DEBUG] skip_dir: 
[DEBUG] Configuring skip_file ...
[DEBUG] skip_file: ~*|.~*|*.tmp
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!XXX
Default Root ID: XXX
Remaining Free Space: 1098836616688
Fetching details for OneDrive Root
OneDrive Root exists in the database
Office 365 Library Name Query: Research
SiteName: Research
drive_id: b!XXX
URL:      https://<corp>.sharepoint.com/sites/Research988
SiteName: Research
drive_id: b!XXX
URL:      https://<corp>.sharepoint.com/sites/Research988
```

Note that there are two different drive_id listed yet the URL is the same. Loading these they are not the drive I'm looking for, they are two empty Microsoft Teams automatically generated shares.

If I look at the URL pattern on the sharepoint site itself, the name of the group is with a lowercase R, trying to search for `research` instead of `Research` gives:

```
ERROR: This site could not be found. Please check it's name and your permissions to access the site.
```

The Sharepoint group I'm looking for is private. Not sure if it changes anything.

**Application and Operating System Details:**
*   OS: Linux barachois 5.0.4-arch1-1-ARCH #1 SMP PREEMPT Sat Mar 23 21:00:33 UTC 2019 x86_64 GNU/Linux, Arch Linux
*   I have a GUI
*   OneDrive Account Type: Business
*   DMD64 D Compiler v2.085.0
*   Application configuration: 

```
onedrive version                    = 2.3.2
Config path                         = /home/olivier/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/olivier/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false
```

*   Curl Version: curl 7.64.1 (x86_64-pc-linux-gnu) libcurl/7.64.1 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.1.1) libssh2/1.8.1 nghttp2/1.36.0

Provided full debug log above it looks like `--verbose --verbose` isn't adding much to see the requests behind the scenes for `--get-O365-drive-id`. 

**Screenshots**
I do have two teams named `Research` on sharepoint:

![onedrive](https://user-images.githubusercontent.com/546325/55814038-cf036080-5abb-11e9-8408-9538685f7ffa.png)

And one of them holds the file I want to sync:

![onedrive-group](https://user-images.githubusercontent.com/546325/55814199-125dcf00-5abc-11e9-9888-9e5c4806402d.png)

I am willing and available to do additional manuals steps to try to understand this issue.

**Comment by abraunegg** [comment]
@obilodeau 
Please can you rebuild your client with the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/462/head:pr462
git checkout pr462
make clean; make;
```
Then execute this against your OneDrive Business account with the following switches:
```
--verbose --verbose --get-O365-drive-id '*'
```
This will output all of the SharePoint Sites; associated with your account:
```
Office 365 Library Name Query: *
[DEBUG] Found O365 Site: {"createdDateTime":"2018-04-16T03:22:47Z","displayName":..."}
[DEBUG] Found O365 Site: {"createdDateTime":"2018-04-16T03:20:27Z","displayName":..."}
[DEBUG] Found O365 Site: {"createdDateTime":"2018-04-04T03:25:32Z","displayName":..."}
[DEBUG] Found O365 Site: {"createdDateTime":"2018-04-16T03:22:27Z","displayName":..."}
[DEBUG] Found O365 Site: {"createdDateTime":"2018-12-02T05:44:01Z","description":..."}
[DEBUG] Found O365 Site: {"createdDateTime":"2018-12-20T19:33:51Z","description":..."}
[DEBUG] Found O365 Site: {"createdDateTime":"2019-01-18T20:47:07Z","description":..."}
ERROR: This site could not be found. Please check it's name and your permissions to access the site.
```
Please can you validate the following fields for the site(s) you are looking for:
* description
* displayName

**Comment by obilodeau** [comment]
I've updated and found many sites but not the one I was looking for.

I think I'm dealing with a Sharepoint group that has Documents and not an Office 365 group (or Team) that has a OneDrive share. I'm very unfamiliar with all of this but I think moving the files and notifying team members is going to be easier.

The feature in the PR is still useful though :slightly_smiling_face:

**Comment by abraunegg** [comment]
@obilodeau 
Thanks for the feedback

You can also use the `--debug-https` flag and see what the actual responses are from OneDrive when performing the calls.

If you are not seeing the data your looking for, unsure where this may be located.

Can you confirm however that this is not a 'Business Shared Folder'? 

Business Shared Folders is currently not supported in the client. See #459 for further details.

**Comment by abraunegg** [comment]
@obilodeau 
PR #462 is merged into master, pending your information this issue could probably be closed

**Comment by obilodeau** [comment]
Adding `--debug-https` does add a fair amount of information but I couldn't find the drive I was looking for.

> Can you confirm however that this is not a 'Business Shared Folder'?

I don't believe it is a business shared folder since the group has a calendar, a mailing list and other SharePoint features beyond just a shared folder from a business account.

I'm going to try and resolve this with my IT group. Create a new team or group and transfer the files over. You can close this. Thanks for your help!

**Comment by abraunegg** [comment]
Closing issue
