### ISSUE TITLE
Cannot start program due to Error on initSyncEngine

### ISSUE THREAD

**Issue by FabioNevesRezende** [abraunegg/onedrive#468]
### Bug Report Details ###
**Describe the bug**
When I run `onedrive --monitor` the program crashes with the following error message:

```
> Initializing the Synchronization Engine ...
> std.json.JSONException@std/json.d(540): Key not found: expirationDateTime
> ----------------
> /usr/include/dlang/dmd/std/exception.d:515 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0xf16a9dcf]
> ??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0xf1761fa2]
> ??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0xf1719fa1]
> src/upload.d:85 bool upload.UploadSession.restore() [0xf16ed39e]
> src/sync.d:286 void sync.SyncEngine.init() [0xf16e25f1]
> src/main.d:688 bool main.initSyncEngine(sync.SyncEngine) [0xf16bcb18]
> src/main.d:476 _Dmain [0xf16bbdb3]
```

**Application and Operating System Details:**
*   `uname -a`: Linux fabiopc 5.0.6-artix1-1-ARTIX #1 SMP PREEMPT Wed Apr 3 21:22:28 UTC 2019 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?
Yes, no gui
*   OneDrive Account Type
I dont know, an onedrive account...

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`

> DMD64 D Compiler v2.085.0

*   Application configuration: Output of `onedrive --display-config`

onedrive version                    = v2.3.1
Config path                         = /home/fabio/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/fabio/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false

*   Curl Version: Output of `curl --version`

> curl 7.64.1 

**Note:** If curl version is >= 7.62.0 please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

```
> [DEBUG] homePath: HOME environment variable set
> [DEBUG] homePath: /home/fabio
> [DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
> [DEBUG] configDirBase: /home/fabio/.config
> [DEBUG] configDirName: Configuring application to use default config path
> Loading config ...
> Using Config Dir: /home/fabio/.config/onedrive
> No config file found, using application defaults
> [DEBUG] sync_dir: Getting syncDir from config value sync_dir
> [DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
> [DEBUG] syncDir: /home/fabio/OneDrive
> Initializing the OneDrive API ...
> Opening the item database ...
> [DEBUG] Using database file: /home/fabio/.config/onedrive/items.sqlite3
> All operations will be performed in: /home/fabio/OneDrive
> [DEBUG] Configuring skip_dir ...
> [DEBUG] skip_dir: 
> [DEBUG] Configuring skip_file ...
> [DEBUG] skip_file: ~*
> Initializing the Synchronization Engine ...
> Account Type: personal
> Default Drive ID: ...
> Default Root ID: ...
> Remaining Free Space: 996871288943
> Fetching details for OneDrive Root
> OneDrive Root exists in the database
> Trying to restore the upload session ...
> OneDrive returned a 'HTTP 400 - Bad Request' - gracefully handling error
> std.json.JSONException@std/json.d(540): Key not found: expirationDateTime
> ----------------
> /usr/include/dlang/dmd/std/exception.d:515 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x91aafdcf]
> ??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x91b67fa2]
> ??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x91b1ffa1]
> src/upload.d:85 bool upload.UploadSession.restore() [0x91af339e]
> src/sync.d:286 void sync.SyncEngine.init() [0x91ae85f1]
> src/main.d:688 bool main.initSyncEngine(sync.SyncEngine) [0x91ac2b18]
> src/main.d:476 _Dmain [0x91ac1db3]
```

Once the full degug log has been generated & emailed, please retry your sync by adding `--force-http-1.1`. If this is successful, please advise in issue ticket that `--force-http-1.1` was sucessful in resolving your issue.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Just run `onedrive --monitor`

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output

**Comment by norbusan** [comment]
Could you please try the latest version (2.3.2) or directly from git master and see if it is reproducible?

Furthermore, I guess when using `--synchronize` all is fine, right?

**Comment by FabioNevesRezende** [comment]
Just updated with git pull, ran `make clean; make; sudo make install` to version **v2.3.2-9-g521cf33**. The problem persists and I call reproduce it with both `--synchronize` and `--monitor` options.

**Comment by norbusan** [comment]
Very strange, I just did the same, and don't see any problem.

The only difference I can see is that your `dmd` compiler is newer than mine.

Do you have ldc2 also installed? On my linux system Debian this is in package `ldc`.

I will later try to test the newer dmd compiler, too

**Comment by norbusan** [comment]
Ok, now I tried with `DMD64 D Compiler v2.085.1` and still cannot reproduce this problem.

**Comment by norbusan** [comment]
Ah, now I see. Nothing to do with the compiler. We don't check at some point for this error. Interesting.

**Comment by FabioNevesRezende** [comment]
Yes, I have ldc-2:1.14.0-2 installed. Still the error occuring

**Comment by abraunegg** [comment]
@FabioNevesRezende 
Please follow the instructions here to create a HTTPS Debug log and email to support@mynas.com.au

https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support

**Comment by abraunegg** [comment]
@FabioNevesRezende 
Please can you test the following PR for resolution for your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/469/head:pr469
git checkout pr469
make clean; make;
```

**Comment by abraunegg** [comment]
@FabioNevesRezende 
Any update on being able to test the fix for your issue?

**Comment by abraunegg** [comment]
@FabioNevesRezende 
Marking this bug as fixed as 'manually' triggering by code change shows code fixes correctly trapping the error reported. Waiting on your confirmation to close out this bug.

**Comment by FabioNevesRezende** [comment]
Hello, the proposed solution worked. Thanks
