### ISSUE TITLE
Log rotation not working

### ISSUE THREAD

**Issue by mcintyrechris** [abraunegg/onedrive#47]
Currently, this application is logging to `/var/log/onedrive/<filename for log>` and is not rotating the log or truncating it. It would be nice to rotate the log at regular intervals and delete older logs or truncate old log entries. I don't know what is a good interval, but my current log file is ~8.9M after about 7 weeks of 10-minute interval `--synchronize` runs.

**Comment by abraunegg** [comment]
There is this in the source tree:

https://github.com/abraunegg/onedrive/blob/master/logrotate/onedrive.logrotate

Was this installed & operational for you? It should be rotating the log file weekly & keeping 4 files by default.

**Comment by mcintyrechris** [comment]
I am not sure how to tell if logrotate has errors or not. I can do whatever you think could help troubleshoot this, though. The `onedrive.logrotate` is present in the `logrotate.d` folder.

Other info: I run `onedrive --synchronize` using a cron job on my user crontab every 10 minutes. I did notice that the log file in `/var/log/onedrive` is owned by my user, not `root:users` per the logrotate file above; not sure if that would cause issues.

**Comment by mcintyrechris** [comment]
`logrotate -f -v /etc/logrotate.d/onedrive` rotated the log just fine, not sure why it wasn't doing it before. Let me leave it for a week and see how it goes, I'll update this ticket if it doesn't rotate after the week, but it looks like it *should* work but was not for some reason. I did delete the old log that was 8.9M, re-ran a sync, then ran the above command, so who knows what's going on.

**Comment by abraunegg** [comment]
If you can check your cron log files - see if there is an error or something present there which may help why the logrotate process is not working as intended.

**Comment by mcintyrechris** [comment]
I don't see any logged errors in any of the usual places, sorry.

**Comment by abraunegg** [comment]
The 'only' thing I can see that 'may' have an effect on the log rotation is that lines 4 - 7 use a tab vs all others use a space character.

Given it works when run manually, and I have checked my test systems here and it does run as specified (with the tab in place) can you switch the characters from tab to space for lines 4-7 to see if that makes a difference for you?

**Comment by mcintyrechris** [comment]
I will give that a shot and let you know after the next rotation.

**Comment by abraunegg** [comment]
@mcintyrechris 
Any update on this issue?

**Comment by mcintyrechris** [comment]
Nothing yet, I should have a rotation by Wednesday night. I'll be back, don't worry! Thanks for keeping up on this project, too!

**Comment by abraunegg** [comment]
@mcintyrechris 
Any update on this issue?

**Comment by mcintyrechris** [comment]
I checked last night and it did not rotate, so I'm not sure what's up with that. I'm out of ideas, so let me know if I can do anything to help troubleshoot. I'm not super worried about this, personally, though.

**Comment by abraunegg** [comment]
It would be good to work out why it's not working.

According to this: https://serverfault.com/questions/375004/logrotate-not-rotating-the-logs/375404

> the /var/lib/logrotate/status file "stores information about when it last rotated each log file.". The logrotate manpage says that is called a "state file".

Is there any details in there?

**Comment by mcintyrechris** [comment]
`"/var/log/onedrive/full name.onedrive.log" 2018-7-14-22:0:0`

It seems to say it last rotated it at 10pm tonight, but it certainly did not.

**Comment by abraunegg** [comment]
@mcintyrechris
Any update on this issue or should this be closed and put down to some sort of local OS issue?

**Comment by mcintyrechris** [comment]
Sorry, I've tried everything I know, so I'll close it.
