### ISSUE TITLE
systemd not finding executable

### ISSUE THREAD

**Issue by petobens** [abraunegg/onedrive#472]
Hi! I'm getting the following error 
```
$ systemctl --user status onedrive
● onedrive.service - OneDrive Free Client
   Loaded: bad-setting (Reason: Unit onedrive.service has a bad unit file setting.)
   Active: inactive (dead)
     Docs: https://github.com/abraunegg/onedrive

Apr 19 19:45:41 Matebook-X-Pro systemd[1256]: /usr/lib/systemd/user/onedrive.service:7: Neither a valid executable name nor an absolute path: prefix@/bin/onedrive
Apr 19 19:45:41 Matebook-X-Pro systemd[1256]: onedrive.service: Cannot add dependency job, ignoring: Unit onedrive.service has a bad unit file setting.
 ```
I probably have to update some config parameter but I'm quite lost. Any pointers are greatly appreciated. For the record I'm on arch running latest master. Thanks in advance!

**Comment by abraunegg** [comment]
@petobens 
Best steps to resolve:
1. Stop and disable all 'onedrive' services
2. Make sure there is no 'onedrive' process running

Then look at your onedrive service file, have a look at what is being called to start the service. It should be similar to:
```
ExecStart=/usr/bin/onedrive --monitor
```

Attempt to manually start OneDrive using that ExecStart portion:
```
/usr/bin/onedrive --monitor
```

Now your error log details the following:
```
Neither a valid executable name nor an absolute path: prefix@/bin/onedrive
```

So maybe something has screwed up the systemd unit file when performing a build.

Did you build from 'master' or use the Arch package?

**Comment by petobens** [comment]
Indeed the unit file seems corrupted. I've changed the `ExecStart` path to `/usr/bin/onedrive` and it seems to work now. I'm using the aur package https://aur.archlinux.org/packages/onedrive-abraunegg-git/. 
No idea why the path is wrongly set though...

**Comment by abraunegg** [comment]
Most likely then the git package needs to be modified - postban issue with the package on the aur website

**Comment by abraunegg** [comment]
Closing issue - packaging issue with aur git package

**Comment by norbusan** [comment]
Indeed a packaging issue, but I checked the PkGBUILD file and nothing strange jumped at me. I'll check it later on when I'm back home at a computer.

**Comment by norbusan** [comment]
I checked now the PKGBUILD file and the commands in there work as expected. I can only assume that something else was broken at some point. But this is an AUR issue indeed.

**Comment by petobens** [comment]
Thanks!

**Comment by abraunegg** [comment]
@petobens 
OK - so tracked this back as well - this is a side product of not running / using `./configure` as part of the build process. PR #475 resolves this issue.

**Comment by abraunegg** [comment]
PR #475 merged

**Comment by petobens** [comment]
Thanks! I'm now getting the following though:
```
==> Starting build()...
make: Entering directory '/home/pedro/.cache/yay/onedrive-abraunegg-git/src/onedrive'
make: *** No targets specified and no makefile found.  Stop.
make: Leaving directory '/home/pedro/.cache/yay/onedrive-abraunegg-git/src/onedrive'
==> ERROR: A failure occurred in build().
    Aborting...
Error making: onedrive-abraunegg-git
```

**Comment by norbusan** [comment]
Can you please send the full log, including which commands were called. Otherwise we cannot guess what is going on

**Comment by norbusan** [comment]
It seems that you didn't call configure ...

**Comment by petobens** [comment]
Ohh sorry. My bad. Thanks!!
