### ISSUE TITLE
Not sync after closing the lid (laptop)

### ISSUE THREAD

**Issue by turunut** [abraunegg/onedrive#482]
Hello,
I'm using a laptop and I automatically run onedrive at start-up (Ubuntu 16.04 LTS). Everything works perfect but I have small problem:
The syncing does not work again after closing the lid and open it again. (However the process onedrive remains open)
The estrange think is that I have tried suspending Ubuntu clicking on the option Suspend and once I wake-up the OS again everything works fine and the created files sync without problems.

There is any solution?
Thank you very much

**Comment by abraunegg** [comment]
@turunut 
This will not be a problem with the client. This is to do with Ubuntu & the scripts / process it follows for:
* Running suspend & resume
* Running suspend when shutting laptop & resume

What you will need to do is work out the differences between the two to identify where & what is not being performed correctly by Ubuntu.

**Comment by norbusan** [comment]
@turunut which version of OneDrive do you use? I made some changes that should make it reconnect after suspends etc. It works on my system at least

**Comment by turunut** [comment]
> 
> 
> @turunut which version of OneDrive do you use? I made some changes that should make it reconnect after suspends etc. It works on my system at least

Hi @norbusan , I was using the last released version at that moment. I will reinstall it with the updated sources to see if I still have the same issue. The easy solution that I have been using until now is suspending the OS before closing the lid.

**Comment by abraunegg** [comment]
@turunut
The only way to resolve this I suspect is to look at the scripts that Ubuntu is calling when just shutting the laptop lid and resuming vs suspending.

This is not an issue with the client, but Ubuntu.

Closing issue as not onedrive client related.
