### ISSUE TITLE
Survey from current users: any problems

### ISSUE THREAD

**Issue by SRGOM** [abraunegg/onedrive#486]
Hello,

Sorry if this isn't the best place but the last time I used a onedrive client for Linux (not this one) it gave me a lot of issues. Can some current users chime in about how well this works for them?

**Comment by wertydoo** [comment]
Hi! 
So I'm experimenting with this repo right now and have some things I can comment on. Generally it works well. Installation was pretty straight forward and adding it to systemd services was also trivial. I am finding that there is a bottleneck with large amounts of files irrelevant of size. It was taking more than 30 minutes to sync 1000+ files that added up to roughly 14 MB in one folder. If this could be addressed then I think abraunegg's fork would be about perfect!

**Comment by SRGOM** [comment]
Thank you so much for answering! My biggest worry is data duplication (observed in my previous onedrive-client) or loss. From the other open issues and from your comment, I gather that there are no bugs in this code, only certain things that could be better. 

Thank you again!

**Comment by abraunegg** [comment]
@SRGOM 
If you had specific concerns I would have been able to answer them rather than wait for other users to comment.

Data duplication & data loss - where the file names kept of being appended - is one major bug that has been resolved for a long time in this fork - certainly suggest you look at the https://github.com/abraunegg/onedrive/releases link to review what has been changed / fixed / added.

One option which you potentially may be able to utilise until you are 100% comfortable is the `--dry-run` switch - which - will do as it implies - tell you what would have occurred during client operational activities.

**Comment by abraunegg** [comment]
@wertydoo 
> Hi!
> So I'm experimenting with this repo right now and have some things I can comment on. Generally it works well. Installation was pretty straight forward and adding it to systemd services was also trivial. I am finding that there is a bottleneck with large amounts of files irrelevant of size. It was taking more than 30 minutes to sync 1000+ files that added up to roughly 14 MB in one folder. If this could be addressed then I think abraunegg's fork would be about perfect!
> 
> The issue I'm describing is actually referenced in an open issue from august. I believe it has to do with the fact that this program doesn't have a lot of parallel support at the moment.

Thanks providing feedback for this.

In terms of "slow upload sync" - this is on the cards - see #175 and #232 for resolution. Assistance / patches are always also welcome.

**Comment by norbusan** [comment]
@SRGOM (disclaimer: I also write code for this onedrive client)
I used the original client for some time, and it was extremely buggy. With the current one here I am syncing permanently about 100G and more between several computers and the cloud.

**Comment by ga2k** [comment]
I'm having trouble getting files *in* the sync_dir from getting sync'ed in either direction. Files in the folders sync in both directions just fine.

This is probably a configuration issue. Here is my sync_list:
bin
Templates
Subversion
Documents
Public

and here is my config
sync_dir = "/home/geoffrey"
skip_dir = ".cache|.gnupg|.pki|./Desktop|./dlang|./Downloads|./Music|./onedrive|./Pictures|./Videos"
enable_logging = "true"

**Comment by norbusan** [comment]
@ga2k can you please send the full config?

**Comment by abraunegg** [comment]
@ga2k 
> I'm having trouble getting files _in_ the sync_dir from getting sync'ed in either direction. Files in the folders sync in both directions just fine.
> 
> This is probably a configuration issue. Here is my sync_list:
> bin
> Templates
> Subversion
> Documents
> Public
> 
> and here is my config
> sync_dir = "/home/geoffrey"
> skip_dir = ".cache|.gnupg|.pki|./Desktop|./dlang|./Downloads|./Music|./onedrive|./Pictures|./Videos"
> enable_logging = "true"

Please open a new issue as per https://github.com/abraunegg/onedrive/blob/master/README.md#reporting-issues

**Comment by ga2k** [comment]
> @ga2k can you please send the full config?

Sure. I'm running this on Ubuntu 18.04.2 LTS Server...

jeeves:~ geoffrey$ cat .config/onedrive/config
# Configuration for OneDrive Linux Client
# This file contains the list of supported configuration fields
# with their default values.
# All values need to be enclosed in quotes
# For explanations see the README.md or the man page.
#
sync_dir = "/home/geoffrey"
# skip_file = "~*|.~*|*.tmp"
# monitor_interval = "45"
skip_dir = ".cache|.gnupg|.pki|./Desktop|./dlang|./Downloads|./Music|./onedrive|./Pictures|./Videos"
# log_dir = "/var/log/onedrive/"
# drive_id = ""
# upload_only = "false"
# check_nomount = "false"
# check_nosync = "false"
# download_only = "false"
# disable_notifications = "false"
# disable_upload_validation = "false"
enable_logging = "true"
# force_http_11 = "false"
# local_first = "false"
# no_remote_delete = "false"
# skip_symlinks = "false"
# debug_https = "false"
# skip_dotfiles = "false"
# dry_run = "false"
# monitor_interval = "45"
# min_notify_changes = "5"
# monitor_log_frequency = "5"
# monitor_fullscan_frequency = "10"

jeeves:~ geoffrey$ cat .config/onedrive/sync_list
bin
Templates
Subversion
Documents
Public

jeeves:~ geoffrey$ onedrive --display-config
onedrive version                    = v2.3.3-5-gaf43b77
Config path                         = /home/geoffrey/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/geoffrey
Config option 'skip_dir'            = .cache|.gnupg|.pki|./Desktop|./dlang|./Downloads|./Music|./onedrive|./Pictures|./Videos
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = true
sync_list contents:
bin
Templates
Subversion
Documents
Public

**Comment by SRGOM** [comment]
Thank you @wertydoo @norbusan @ga2k for answering my questions! 

Thanks @abraunegg for maintaining this! The problem was not in this client but in another but glad to know that these issues are not in the present code. I look forward to trying this as soon as i can.

Thanks again, all.

Closing this issue.
