### ISSUE TITLE
Dry run reports "Deleting item from one drive" for remotely created file

### ISSUE THREAD

**Issue by MK-42** [abraunegg/onedrive#489]
Dry run is a really nice feature, but is incorrect for one specific case for me

### Bug Report Details ###
**Describe the bug**
Running with dry-run reports downloading and successive deletion of new remote file, but running without dry-run wont delete it.

running with dry-run:
Downloading file NewFile.ext ... done.
Deleting item from OneDrive: NewFile.ext

running without dry-run:
Downloading file NewFile.ext ... done.

**Application and Operating System Details:**
*   OS: Linux redacted-hostmane 5.0.9-200.fc29.x86_64 #1 SMP Mon Apr 22 00:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (Fedora 29)
*   Desktop system
*   OneDrive Business, syncing a shared folder
*   dmd-2.083.0
*   Application configuration: Output of `onedrive --display-config`
onedrive version                    = v2.3.1
Config path                         = /home/mk/.config/onedrive/someFolder/
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/user/someFolder/
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'drive_id'            = b!myDriveId
Selective sync configured           = true
sync_list contents:
SomeSpecificFolder
# with some comments
*   Curl Version: Output of `curl --version`
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1b zlib/1.2.11 brotli/1.0.5 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.7/openssl/zlib nghttp2/1.34.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink 

**To Reproduce**
Upload remote file, sync local storage with --dry-run, then without

**Complete Verbose Log Output**
sorry, no verbose output atm

**Comment by abraunegg** [comment]
@MK-42 
Can you retry / retest with latest master given your client version is rather old?

I know this was tested when the feature was developed ...

**Comment by abraunegg** [comment]
@MK-42 
Please can you test the following PR for fixing this issue. Local testing indicates that this solves the problem:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/490/head:pr490
git checkout pr490
make clean; make;
```

**Comment by abraunegg** [comment]
@MK-42 
PR is merged into master, closing issue

**Comment by MK-42** [comment]
Thanks for the immediate fix. Wasn't able to free time to reproduce again. But codewise it looks like it should fix the issue.

Thanks again for all the effort you and other contributors put into this piece of software - eases life so much and runs much smoother since you forked the project.
