### ISSUE TITLE
Failed to execute operation: No such file or directory - CentOS 7

### ISSUE THREAD

**Issue by sombrakey** [abraunegg/onedrive#495]
the service is not being created, it displays the following error:
```
# systemctl enable onedrive
Failed to execute operation: No such file or directory
```

step by step:
https://pastebin.com/4VFXBjj6

**Comment by abraunegg** [comment]
@sombrakey 
Thanks for the bug report / pastebin output.

Issue has been identified and fixed - please can you test this PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/496/head:pr496
git checkout pr496
make clean; ./configure; make; sudo make install
```

This should now install the unit files to the correct unit directories on RHEL / CentOS platforms:
```
(dmd-2.085.0)[alex@centos7full onedrive]$ sudo make install              
/usr/bin/install -c -d -o root -g users -m 0775 /var/log/onedrive
/usr/bin/install -c -D onedrive /usr/local/bin/onedrive
/usr/bin/install -c -D onedrive.1 /usr/local/share/man/man1/onedrive.1
/usr/bin/install -c -D -m 644 logrotate/onedrive.logrotate /usr/local/etc/logrotate.d/onedrive
for i in README.md README.Office365.md config LICENSE CHANGELOG.md ; do /usr/bin/install -c -D -m 644 $i /usr/local/share/doc/onedrive/$i ; done
/usr/bin/install -c -d -o root -g root -m 0755 /usr/lib/systemd/user /usr/lib/systemd/system
/usr/bin/install -c -m 0644 systemd.units/onedrive.service /usr/lib/systemd/system
/usr/bin/install -c -m 0644 systemd.units/onedrive@.service /usr/lib/systemd/system
(dmd-2.085.0)[alex@centos7full onedrive]$ 

```

**Comment by sombrakey** [comment]
Hi, works fine now.

(dmd-2.086.0)[root@teste onedrive]# systemctl enable onedrive
Created symlink from /etc/systemd/system/default.target.wants/onedrive.service to /usr/lib/systemd/system/onedrive.service.
(dmd-2.086.0)[root@teste onedrive]# systemctl start onedrive

the logs do not appear, you have to enable the --enable-logging?

(dmd-2.086.0)[root@teste onedrive]# journalctl --user-unit onedrive -f
-- Logs begin at Qui 2019-05-09 13:52:02 -03. --

**Comment by abraunegg** [comment]
@sombrakey 
You will need to determine what level of logging you want to run and modify accordingly. Logging output is very minimal when not using --verbose

**Comment by abraunegg** [comment]
@sombrakey 
> the logs do not appear, you have to enable the --enable-logging?
`--enable-logging` is used when you want to send the logs to a log file in addition to the systemd log (or not running systemd, standalone etc

**Comment by abraunegg** [comment]
@sombrakey 
Closing issue as PR #496 merged
