### ISSUE TITLE
onedrive --display-config doesnt read config file, cant change sync dir

### ISSUE THREAD

**Issue by tricecold** [abraunegg/onedrive#500]
I cannot change the sync dir, no matter what I do.
my config file at
~/.config/onedrive$ nano config returns that i edited my path correctly
```
# sync_dir = "/media/tricecold/BACKUP"
```
but 
```
onedrive --display-config
onedrive version                          = v2.3.3-8-g0280625
Config path                                  = /home/tricecold/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'      = false
Config option 'sync_dir'                = /home/tricecold/OneDrive
```
i really cant make it read this folder.

Any ideas

**Comment by abraunegg** [comment]
This could be just a display issue ...

What happens when you use: `--dry-run` ? Does it dry-run sync the correct location?

**Comment by abraunegg** [comment]
Ok scratch that .. after editing your post i see the issue.

You need to remove the `#` from the config line

**Comment by abraunegg** [comment]
closing issue as answer provided
