### ISSUE TITLE
"Peer certificate cannot be authenticated with given CA certificates on handle" when synchronizing files

### ISSUE THREAD

**Issue by jsferguson** [abraunegg/onedrive#502]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
I have installed this application, as described, on my fresh Ubuntu 18.0 Workstation. No errors during the installation. I can perform a dry-run syncrhonization without any errors. However, if I perform the sync "for real", I see the following errors:
```
Downloading file Test/Schoolkrant.pub ... Giving up on sync after three attempts: Peer certificate cannot be authenticated with given CA certificates on handle 55BA52BBF830
std.net.curl.CurlException@std/net/curl.d(4364): Peer certificate cannot be authenticated with given CA certificates on handle 55BA52BBF830
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x55ba5266132a]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x55ba5266129d]
??:? void std.net.curl.Curl._check(int) [0x55ba5263ac13]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x55ba5263b03f]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x55ba52639c5c]
src/onedrive.d:497 void onedrive.OneDriveApi.download(const(char)[], immutable(char)[], long) [0x55ba525e163f]
src/onedrive.d:213 void onedrive.OneDriveApi.downloadById(const(char)[], const(char)[], immutable(char)[], long) [0x55ba525dfe76]
src/sync.d:1068 void sync.SyncEngine.downloadFileItem(itemdb.Item, immutable(char)[]) [0x55ba525f068c]
src/sync.d:983 void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x55ba525eff52]
src/sync.d:943 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x55ba525efc16]
src/sync.d:734 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x55ba525eec02]
src/sync.d:387 void sync.SyncEngine.applyDifferences() [0x55ba525ed295]
src/main.d:618 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x55ba525dded0]
src/main.d:389 _Dmain [0x55ba525dd27d]

```

**Application and Operating System Details:**
*   OS: Linux ws-dev-jsferguson 4.18.0-18-generic #19~18.04.1-Ubuntu SMP Fri Apr 5 10:22:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 18.04
*   Default GUI for Ubuntu 18.04
*   OneDrive Account Type: Personal
*   DMD64 D Compiler v2.086.0
Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright
* LDC - the LLVM D compiler (1.8.0)
*   Application configuration: Output of `onedrive --display-config`
onedrive version                    = v2.3.3-11-g20eda60
Config path                         = /home/jsf/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/jsf/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
Test
*   Curl Version: Output of `curl --version`: 
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

Once the full degug log has been generated & emailed, please retry your sync by adding `--force-http-1.1`. If this is successful, please advise in issue ticket that `--force-http-1.1` was sucessful in resolving your issue.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Open terminal: ~/OneDrive
2.  run: onedrive --synchronize
3.  See error

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
onedrive --synchronize --verbose
Using Config Dir: /home/jari/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/jari/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: d178150101dbfdbf
Default Root ID: D178150101DBFDBF!101
Remaining Free Space: 998213268670
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: D178150101DBFDBF!101
Processing 265 changes
Downloading file Test/Schoolkrant.pub ... Retry sync count: 1: Peer certificate cannot be authenticated with given CA certificates on handle 55A4D12B5830
Syncing changes from OneDrive ...
Applying changes of Path ID: D178150101DBFDBF!101
Processing 265 changes
Downloading file Test/Schoolkrant.pub ... Retry sync count: 2: Peer certificate cannot be authenticated with given CA certificates on handle 55A4D12B5830
Syncing changes from OneDrive ...
Applying changes of Path ID: D178150101DBFDBF!101
Processing 265 changes
Downloading file Test/Schoolkrant.pub ... Giving up on sync after three attempts: Peer certificate cannot be authenticated with given CA certificates on handle 55A4D12B5830
std.net.curl.CurlException@std/net/curl.d(4364): Peer certificate cannot be authenticated with given CA certificates on handle 55A4D12B5830
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x55a4cff2932a]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x55a4cff2929d]
??:? void std.net.curl.Curl._check(int) [0x55a4cff02c13]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x55a4cff0303f]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x55a4cff01c5c]
src/onedrive.d:497 void onedrive.OneDriveApi.download(const(char)[], immutable(char)[], long) [0x55a4cfea963f]
src/onedrive.d:213 void onedrive.OneDriveApi.downloadById(const(char)[], const(char)[], immutable(char)[], long) [0x55a4cfea7e76]
src/sync.d:1068 void sync.SyncEngine.downloadFileItem(itemdb.Item, immutable(char)[]) [0x55a4cfeb868c]
src/sync.d:983 void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x55a4cfeb7f52]
src/sync.d:943 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x55a4cfeb7c16]
src/sync.d:734 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x55a4cfeb6c02]
src/sync.d:387 void sync.SyncEngine.applyDifferences() [0x55a4cfeb5295]
src/main.d:608 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x55a4cfea5ea7]
src/main.d:389 _Dmain [0x55a4cfea527d]

```

**Comment by norbusan** [comment]
Do you use proxies? Is there something blocking connectivity?

**Comment by jsferguson** [comment]
I am on a corporate network, so I guess it is possible. I haven't explicitly set a proxy server. Also, if I use http://amibehindaproxy.com/, it reports it didn't detect a proxy-server.
 I am able to perform a dry-run without any errors. Also, I am able to access OneDrive on my Windows laptop (using the Microsoft software).

**Comment by abraunegg** [comment]
@jsferguson 
Most likely you have a transparent proxy in place that is doing HTTP/HTTPS inspection. Speak to your corporate IT folk to confirm.

To resolve this, your corporate CA certificates need to be installed on your Linux server - otherwise you will get this sort of error.

The reason why it works on Windows, is that your connected to Active Directory, and Windows inherently has all the corporate CA certificates loaded - this is why there is no issue when using Windows.

**Comment by jsferguson** [comment]
Okay, that sounds good. I will look into it. Thanks for your help!
