### ISSUE TITLE
 syncing sharepoint document librarys - I don't get it ... 

### ISSUE THREAD

**Issue by HansAchterbahn** [abraunegg/onedrive#503]
>Hi,
>
>I used the Graph Explorer and the Sharepoint API:
>https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/sharepoint
>
>There you can see, how to build the required URL in order to geht the drive ID:
>GET https://graph.microsoft.com/v1.0/sites/[hostname]:/[PATH]:/drives
>
>So what you need to know is the Hostname and the Path to the sharepoint website collection. Example:
>GET https://graph.microsoft.com/v1.0/sites/contoso.sharepoint.com:/teams/hr:/drives
>
>I created a Sharepoint website collection called "Backup" in the Sharepoint Admin Center. So the URL is:
>GET https://graph.microsoft.com/v1.0/sites/myname.sharepoint.com:/sites/Backup:/drives
>
>Unfortunately this URL cant be direclty used as "driveURL" in the sync client. But in the answer there is an entry called "id". Using this ID you can create the "driveURL":
>https://graph.microsoft.com/v1.0/drives/[id]

>Inserting this into driveUrl, itemByIdUrl and itemByPathUrl in the source code allows the sharepoint drives to be synced using this client.

_Originally posted by @riversource in https://github.com/skilion/onedrive/issues/283#issuecomment-366899361_

Hi guys, I tried realy hard to get this to work, but i didn't get it. Can you may help me on this?
Syncing on my private documents is working, but i don't get the drive_id.

[debug_output.log](https://github.com/abraunegg/onedrive/files/3182914/debug_output.log)

**Comment by abraunegg** [comment]
Please follow the directions here:

https://github.com/abraunegg/onedrive/blob/master/README.Office365.md

**Comment by HansAchterbahn** [comment]
Thanks a lot! But now I have the Problem of 2 displayed IDs for one shared folder. In sharepoint there is only 1 folder.

```{.sh}
➜  ~ onedrive --get-O365-drive-id 'Allgemein'
Initializing the Synchronization Engine ...
Office 365 Library Name Query: Allgemein
SiteName: Allgemein
drive_id: b!oJfcF8mx5U2RA3i_2EZ2cIgTYMuBGnFGssXyaKBEk16rWlVp3zwzS5iNXsbkNcdD
URL:      https://dbdplasma.sharepoint.com/Allgemein
SiteName: Allgemein
drive_id: b!oJfcF8mx5U2RA3i_2EZ2cIgTYMuBGnFGssXyaKBEk17f6Y3BZwZ_TplstQ2qX2wz
URL:      https://dbdplasma.sharepoint.com/Allgemein
➜  ~ 
```

I tried both IDs but unfortunately the folder dose not sync. I stopped and started the service, tried it manually by `onedrive --synchronize` and restarted the system with no effect.

Can you tell me what I missed?

**Comment by HansAchterbahn** [comment]
~/.config/onedrive/config
```
# Configuration for OneDrive Linux Client
# This file contains the list of supported configuration fields
# with their default values.
# All values need to be enclosed in quotes
# For explanations see the README.md or the man page.
#
# sync_dir = "~/OneDrive"
# skip_file = "~*|.~*|*.tmp"
# monitor_interval = "45"
# skip_dir = ""
# log_dir = "/var/log/onedrive/"
# drive_id = "b!oJfcF8mx5U2RA3i_2EZ2cIgTYMuBGnFGssXyaKBEk17f6Y3BZwZ_TplstQ2qX2wz"
# upload_only = "false"
# check_nomount = "false"
# check_nosync = "false"
# download_only = "false"
# disable_notifications = "false"
# disable_upload_validation = "false"
# enable_logging = "false"
# force_http_11 = "false"
# local_first = "false"
# no_remote_delete = "false"
# skip_symlinks = "false"
# debug_https = "false"
# skip_dotfiles = "false"
# dry_run = "false"
# monitor_interval = "45"
# min_notify_changes = "5"
# monitor_log_frequency = "5"
# monitor_fullscan_frequency = "10"
# sync_root_files = "false"
```

**Comment by HansAchterbahn** [comment]
oh shit I see - in the config file are all values comments ^_^'

**Comment by abraunegg** [comment]
> Thanks a lot! But now I have the Problem of 2 displayed IDs for one shared folder. In sharepoint there is only 1 folder.
> 
> ```
> ➜  ~ onedrive --get-O365-drive-id 'Allgemein'
> Initializing the Synchronization Engine ...
> Office 365 Library Name Query: Allgemein
> SiteName: Allgemein
> drive_id: b!oJfcF8mx5U2RA3i_2EZ2cIgTYMuBGnFGssXyaKBEk16rWlVp3zwzS5iNXsbkNcdD
> URL:      https://dbdplasma.sharepoint.com/Allgemein
> SiteName: Allgemein
> drive_id: b!oJfcF8mx5U2RA3i_2EZ2cIgTYMuBGnFGssXyaKBEk17f6Y3BZwZ_TplstQ2qX2wz
> URL:      https://dbdplasma.sharepoint.com/Allgemein
> ➜  ~ 
> ```
> 
> I tried both IDs but unfortunately the folder dose not sync. I stopped and started the service, tried it manually by `onedrive --synchronize` and restarted the system with no effect.
> 
> Can you tell me what I missed?

This will be because you have 2 folders with the same name

When ever changing drive_id - you need to use `--resync`

**Comment by HansAchterbahn** [comment]
Okay, it's getting clearer and clearer!

Do you know what this error message means?

```{.sh}
ERROR: OneDrive quota information is being restricted. Please fix by speaking to your OneDrive / Office 365 Administrator.
ERROR: Flagging to disable upload space checks - this MAY have undesirable results if a file cannot be uploaded due to out of space.
Account Type: documentLibrary
```

**Comment by abraunegg** [comment]
> Okay, it's getting clearer and clearer!
> 
> Do you know what this error message means?
> 
> ```
> ERROR: OneDrive quota information is being restricted. Please fix by speaking to your OneDrive / Office 365 Administrator.
> ERROR: Flagging to disable upload space checks - this MAY have undesirable results if a file cannot be uploaded due to out of space.
> Account Type: documentLibrary
> ```

It means exactly what it says - your OneDrive account is not providing details that are normally present. This is usually due to 'security privileges' being insufficient.

**Comment by abraunegg** [comment]
Closing issue as question answered
