### ISSUE TITLE
Latest timestamp = source of truth

### ISSUE THREAD

**Issue by kilrau** [abraunegg/onedrive#505]
First of all AMAZING work!

**Is your feature request related to a problem? Please describe.**

Client prio's remote over local when local file was edited by another operating system, in the log below one can see that the newer local file gets renamed and discarded and the older remote file downloaded:
```
* The local item has a different modified time 2019-May-20 10:34:30Z remote is 2019-May-16 13:19:14Z 
* The local item has a different hash 
* The local item is unsynced, renaming: a.file -> b.file
* Downloading file a.file ... done. 
```
**Describe the solution you'd like**
Client should have the option, or rather default to always prio latest timestamp as source of truth.

**Describe alternatives you've considered**
Can be an optional feature at first.

**Additional context**
N/A

**Comment by abraunegg** [comment]
@kilrau 
Thanks for the feature request - good news is this is already implemented:
```
--local-first
      Synchronize from the local directory source first, before downloading changes from OneDrive.
```

**Comment by kilrau** [comment]
I am suggesting to take latest timestamp as source of truth, no matter if local or remote.

That's a use case for everyone with 2 or more devices manipulating the same OneDrive files and is more or less the behavior of the MS OneDrive client I believe.

**Comment by abraunegg** [comment]
> I am suggesting to take latest timestamp as source of truth, no matter if local or remote.
> 
> That's a use case for everyone with 2 or more devices manipulating the same OneDrive files and is more or less the behavior of the MS OneDrive client I believe.

Yes - I do understand this. The original 'skilion' codebase always sync's from OneDrive first. To ensure the same process flow was used was retained - this is why `--local-first` was implemented so you can treat your local disk as your source of truth rather than OneDrive.

Can you provide an 'exact' sequence of commands on multiple systems using a single OneDrive account so that I can replicate your environment to perform some further investigations.

**Comment by abraunegg** [comment]
@kilrau 
The only way I have been able to trigger this:
```
* The local item has a different modified time 2019-May-20 10:34:30Z remote is 2019-May-16 13:19:14Z 
* The local item has a different hash 
* The local item is unsynced, renaming: a.file -> b.file
* Downloading file a.file ... done. 
```
is with the following:
1. perform a manual or monitor sync
2. modify a file locally
3. perform a manual or monitor sync with `--resync` added to rebuild the database

Please can you help validate PR #506 against your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/506/head:pr506
git checkout pr506
make clean; ./configure; make;
```

**Comment by abraunegg** [comment]
@kilrau 
With the patch, the following should now occur:
```
...
Applying changes of Path ID: 01WOGXO2N6Y2GOVW7725BZO354PWSELRRZ
The local item has a different modified time 2019-May-21 19:41:25Z remote is 2019-May-21 19:40:54Z
The local item has a different hash
Local item modified time is newer based on UTC time conversion
Uploading differences of .
...
```

**Comment by kilrau** [comment]
Just did that.

Scenario 1:
1. performed monitor sync
2. stop the sync
3. modified the local file
4. restarted monitor sync

Result Scenario 1:
`May 22 12:11:03 X onedrive[4896]: Uploading modified file a.file ... done.`

Scenario 2:
1. performed monitor sync
2. stop the sync
3. modified the local file via second OS
4. reboot into OS, restarted monitor sync

Result Scenario 2:
`May 22 12:27:42 X onedrive[2042]: Uploading modified file a.file ... done.

Scenario 3:
1. performed monitor sync
2. stop the sync
3. modified remote file
4. restarted monitor sync

Result Scenario 3:
`May 22 12:34:19 X onedrive[3447]: Downloading file a.file ... done.`

So all behaves as it should and I think you were right, I must have accidentally added the --resync command somehow. I think your changes are good to merge though to catch this edge case as well.

**Comment by abraunegg** [comment]
@kilrau 
Thanks for the feedback.
