### ISSUE TITLE
Notification fails due to dbus

### ISSUE THREAD

**Issue by gkirtzou** [abraunegg/onedrive#509]
I just install onedrive (commit 239085f1fc0c297a96b35678114ae18861dedd4e) with  DMD version 2.086 on a linux mint system with i3wn. During configuration I enabled the flag `--enable-notification` and I have also installed the libnotify package as requested. When I set the onedrive to run as demon  with `systemctl`, the `journalctl --user-unit onedrive -f` show that 

> Notification (dbus) server not available

Any idea what could go wrong? What may I miss?

**Comment by abraunegg** [comment]
@gkirtzou 
Most likely the "D-BUS Service" is not started on your system.

I do not test or use Linux Mint, so unable to assist any further.

**Comment by gkirtzou** [comment]
@abraunegg thanks for the reply. I think that the system was available, but I will double check.

**Comment by norbusan** [comment]
It could be an issue with systemd starting the user service too fast, before the suer dbus server is running. Not sure whether this can be circumvented by adding some `After` or so statements in the systemd service file?

**Comment by luukvbaal** [comment]
Having the same issue on Arch with `i3` and `dunst`. `dbus-daemon` is running but `onedrive` still reports `Notification (dbus) server not available, disabling`. Same behavior after a `systemctl restart onedrive@` so timing is not an issue. Any other suggestions?

**Comment by norbusan** [comment]
I guess that using the @ service, that is starting as root `onedrive@USER` does not allow the process to connect to the dbus-daemon. If you want notifications, you probably are better of with using the user level targeted service file, that is, start as user `systemctl --user start onedrive` (and maybe enable).

**Comment by luukvbaal** [comment]
Yeah that fixes it, thanks!

**Comment by norbusan** [comment]
@luukvbaal Be sure to `disable` the `onedrive@USER` otherwise you might be running two instances (this happened to me more than once!)

**Comment by marcofaga** [comment]
I'm with the same problem as @luukvbaal. I use Arch Linux with i3 and dunst and when I run onedrive --monitor it gets: "Notification (dbus) server not available, disabling".  Could you explain what can I do to solve this issue?

**Comment by abraunegg** [comment]
@marcofaga 
> I guess that using the @ service, that is starting as root `onedrive@USER` does not allow the process to connect to the dbus-daemon. If you want notifications, you probably are better of with using the user level targeted service file, that is, start as user `systemctl --user start onedrive` (and maybe enable).

Can you provide some further details here? The post from @norbusan details how to resolve.

**Comment by norbusan** [comment]
@marcofaga Is the dbus server started by the i3 session? I am not sure whether this happens on i3 sessions.

**Comment by abraunegg** [comment]
@norbusan 
Doing some research - `dunst` is a 'replacement on Arch Linux for dbus - https://wiki.archlinux.org/index.php/Dunst

@marcofaga 
In order to get notifications, you need to be using dbus. Using dunst as your notification daemon is not supported.

**Comment by luukvbaal** [comment]
`dunst` is not a replacement for dbus and a `dbus` session [should](https://wiki.archlinux.org/index.php/D-Bus) be started on arch systems by systemd. As such notifications work fine when `onedrive` is started inside a user session, e.g. via `onedrive --monitor` or `systemctl --user start/enable` (again `onedrive@` unit doesn't work. So  if it's not working @marcofaga, check if a dbus session is indeed started for your user. Does `dunst` work for other applications? You can try `notify-send test`.

**Comment by abraunegg** [comment]
@luukvbaal 
I got this from the Arch Wiki - 

is a lightweight replacement for the notification-daemons provided by most desktop environments


I guess my interpretation was not correct.

**Comment by luukvbaal** [comment]
Yeah 'notification-daemons' in that case is referring to one of the [notification servers](https://wiki.archlinux.org/index.php/Desktop_notifications#Notification_servers), not `dbus` itself.
