### ISSUE TITLE
add a --no-local-delete option when using --upload-only

### ISSUE THREAD

**Issue by Gustutu** [abraunegg/onedrive#510]
Hi, 
Thanks for this usefull software !

Could you add an option to NOT forward to OneDrive files that have been deleted locally when using --upload-only.

Thanks 👍  ^^

**Comment by abraunegg** [comment]
> Could you add an option to NOT forward to OneDrive files that have been deleted locally when using --upload-only.

This is already available:
```
--no-remote-delete
      Do not delete local file 'deletes' from OneDrive when using --upload-only
```

**Comment by abraunegg** [comment]
Closing issue as question answered
