### ISSUE TITLE
Docker: Unknown key in config file: skip_dir when run in docker container

### ISSUE THREAD

**Issue by christian-scheible** [abraunegg/onedrive#518]
Hi,

I am using your software in a docker container using docker-compose with this file: [docker-compose.txt](https://github.com/abraunegg/onedrive/files/3266290/docker-compose.txt)

When I try to exclude folders like this:
`skip_dir = "/onedrive/data/plex-library/Cache|/onedrive/data/plex-library/Codecs|/onedrive/data/plex-library/Diagnostics|/onedrive/data/plex-library/Logs"` 

The container is not able to start and the following error is logged:
**Unknown key in config file: skip_dir**

Note: I had to rename the docker-compose.yml to docker-compose.txt to be able to add it here.

If you need any more information I will try to provide it.

**Comment by abraunegg** [comment]
@christian-scheible 
```
The container is not able to start and the following error is logged:
Unknown key in config file: skip_dir
```
This sounds like the 'onedrive' binary does not support that config option. What version are you currently running?

As per bug report submissions, please provide the following:
### Bug Report Details ###
**Describe the bug**
A clear and concise description of what the bug is.

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
*   Are you using a headless system (no gui) or with a gui installed?
*   OneDrive Account Type
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
*   Application configuration: Output of `onedrive --display-config`
*   Curl Version: Output of `curl --version`

**Comment by christian-scheible** [comment]
Thank you for your fast response. I am just running the latest docker image from docker hub. I was not aware that it is 6 month behind the current release. 

So the problem really is that the onedrive binary does not support that config option.

- onedrive --version: onedrive v2.2.3-1-g1060d85

**Comment by norbusan** [comment]
Ohh, we will try to upload a new image. Not sure who as push rights, though!

**Comment by christian-scheible** [comment]
Well that would be great.

**Comment by abraunegg** [comment]
@christian-scheible 
Docker tag 'latest' is rebuilding. Will monitor over the next few releases to ensure that the Docker integration is correctly working.

**Comment by abraunegg** [comment]
@christian-scheible 
Docker tag 'latest' is rebuilt based on v2.3.3 codebase. This does not include fixes / patches / updates v2.3.3 -> 'master'

Please can you help validate.

**Comment by christian-scheible** [comment]
Hi @abraunegg, thanks for all your work. I validated that the image is running version v2.3.3-19-ge4ab9e7 and that skip_dir doesn't lead to an error.

However I am not sure if the setting is really used as onedrive --display-config does not match the settings i made in the docker vollume onedrive_conf.

this is the result of --display-config:

```
onedrive version                    = v2.3.3-19-ge4ab9e7
Config path                         = /root/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /root/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
I would have expected this:

`skip_dir = "/onedrive/data/plex-library/Cache|/onedrive/data/plex-library/Codecs|/onedrive/data/plex-library/Diagnostics|/onedrive/data/plex-library/Logs"`

But it is reading the config file. Because when I add an invalid configuration option it won't start and throws an error that the config option is unknown.

Maybe this is just a bug in --display-config.

**Comment by abraunegg** [comment]
@christian-scheible 
If you are simply running:
```
onedrive --display-config
```
This will default to the 'current user home directory' and use `~/.config/onedrive/config` as the file for configuration to output. This can be seen in your output above.

If you want to see the config you are running with, you need to pass in the `--confdir` parameter with the appropriate location of the config file - for example:
```
./onedrive --confdir '~/.config/onedrive-personal' --display-config
```

This then would display the appropriate configuration your looking for and expecting.

**Comment by christian-scheible** [comment]
@abraunegg Running

`onedrive --confdir /onedrive/conf --display-config` 

is working as expected. Thanks for your help.
