### ISSUE TITLE
skip_file configuration doesn't handle spaces or specified directory paths 

### ISSUE THREAD

**Issue by robertjf** [abraunegg/onedrive#52]
I've created a pull request (#51) and as an afterthought thought I'd better create a corresponding issue.

I also thought after I'd done the pull request I should have put it in a new branch rather than master - if you want me to do that let me know.

Details are on the PR description

**Comment by abraunegg** [comment]
Thanks - will test locally & provide some feedback for the PR :)

**Comment by abraunegg** [comment]
Resolved by PR #57
