### ISSUE TITLE
Docker: Failure setting up container - buggy parsing of gid

### ISSUE THREAD

**Issue by rcarmo** [abraunegg/onedrive#520]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**

When starting the container, it halts with an error message due to buggy GID parsing (shown below).

```bash
rcarmo@tao:~$ sudo docker run -it --restart unless-stopped --name onedrive -v /home/piku/.config/onedrive:/onedrive/conf -v /home/piku/OneDrive:/onedrive/data driveone/onedrive
++ stat /onedrive/data -c %u
+ ONEDRIVE_UID=1001
++ stat /onedrive/data -c %g
+ ONEDRIVE_GID=33
++ getent group 33
+ odgroup=tape:x:33:
++ getent passwd 1001
+ oduser=
+ oduser=onedrive
+ useradd onedrive -u 1001 -g 33
+ chown onedrive:tape:x:33: /onedrive/ /onedrive/conf
chown: invalid group: 'onedrive:tape:x:33:'
```

**Comment by abraunegg** [comment]
@rcarmo 
Thanks for the bug report, will have to do some research and reading as the script is correct according to bash scripting guidelines and also passes codacy validation checks.

**Comment by abraunegg** [comment]
@rcarmo 
From my reading all of the above should work without issue. Docker is also not my area of expertise.

**Comment by rcarmo** [comment]
This is not a Docker issue per se, but a shell expansion issue. This appears to not have been tested with GIDs below 1000, which (I’m guessing) is why that shell expansion breaks.

**Comment by abraunegg** [comment]
@rcarmo 
That should not break based on GID < 1000 ... this being said however - can you test this change in "entrypoint.sh":
```
chown "${oduser}:${odgroup}" /onedrive/ /onedrive/conf
```
To:
```
chown $ONEDRIVE_UID:$ONEDRIVE_GID /onedrive/ /onedrive/conf
```

I do not use or test with Docker so I am unable to validate. If you can test something like the above change that would be greatly appreciated.

**Comment by norbusan** [comment]
Well, looking at the code of `entrypoint.sh` this cannot work out.
```
# Create new group using target GID
if ! odgroup="$(getent group $ONEDRIVE_GID)"; then
  odgroup='onedrive'
  groupadd "${odgroup}" -g $ONEDRIVE_GID
fi
```
now, if the group already exists, `odgroup` is set to the return value of `getent`, which contains the group name, group password, group id, and add info.
```
$ getent group 33
www-data:x:33:
```

Later on the code does
```
chown "${oduser}:${odgroup}" /onedrive/ /onedrive/conf
```
which does not work.

My proposal is
```
if ! odgroup="$(getent group $ONEDRIVE_GID)"; then
  odgroup='onedrive'
  groupadd "${odgroup}" -g $ONEDRIVE_GID
else
  odgroup=${odgroup%%:*}
fi
```
fi
```

**Comment by norbusan** [comment]
See https://github.com/abraunegg/onedrive/pull/521

**Comment by abraunegg** [comment]
@norbusan 
Thanks for looking into this one

**Comment by abraunegg** [comment]
@rcarmo 
Can you retest using the latest master as a fix has been pushed.

**Comment by abraunegg** [comment]
@rcarmo 
Any update in testing the latest master?

**Comment by rcarmo** [comment]
I've pulled the new image from Docker hub and it is now working on the machine I detected this issue on.

I am now trying to get it to work on another setup (where I cannot run Docker interactively to supply the URL via a tty). I will submit another issue regarding that scenario.
