### ISSUE TITLE
Poll-based interactive setup for containers

### ISSUE THREAD

**Issue by rcarmo** [abraunegg/onedrive#524]
**Is your feature request related to a problem? Please describe.**
I need to be able to deploy the Docker container in a setup (Kubernetes) where I cannot perform interactive authentication (i.e., where I don't even have a tty allocated so that [this readln() call](https://github.com/abraunegg/onedrive/blob/master/src/onedrive.d#L166) can work).

**Describe the solution you'd like**
I would like to have a "passive" setup mode where the program would use two files: `auth_url` and `response_url`. It would create `auth_url` in the configuration folder and wait until `response_url` was created, read it, and use its contents to authenticate, deleting both files upon success.

This would make it easy to perform the setup process by:

* using `cat auth_url` and `tee response_url` manually outside the container in a shared volume
* Glueing it to a sidecar container in Kubernetes, which would put up a simple web UI for manual provisioning

**Describe alternatives you've considered**
Building a wrapper script that would essentially perform the above.

**Comment by norbusan** [comment]
@rcarmo I think running under Kubernetes is a good idea, but I am not sure whether what you propose is a good idea:

- what would happen if kubernetes decides to migrate the pod to a different node? Should the whole initialization be restarted?
- how would you deal with multiple instances

But I see that running under Kubernetes without interactive tty is indeed a pain, so having some feature like you describe might be indeed a good idea.

**Comment by norbusan** [comment]
Ok, here is draft PR working on that. My local test did work indeed, but for now there is no error checking for the files etc etc.
https://github.com/abraunegg/onedrive/pull/525
@abraunegg WDYT?

**Comment by abraunegg** [comment]
@norbusan 
I think this is a good start - however if the files dont exist, the app will most likely crash out - we should 'fail in a graceful fashion' rather than probably just error dumping out 

(presuming here as I havnt run / tested the code)

**Comment by norbusan** [comment]
@abraunegg no, the write creates the file if necessary. I tested it locally and the authUrl files is created automatically, and when an external source writes the responseUrl file the onedrive process continues successfully.

**Comment by norbusan** [comment]
Here is a run:
Terminal one
```
$ ./onedrive --confdir ~/.config/onedrive-test --logout
Authorize this app visiting:
Ctrl-C
$ ./onedrive --confdir ~/.config/onedrive-test --auth-files aaa:bbb --synchronize
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Processing 18 changes
$
```

Temrinal two:
```
$ cat aaa
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
# ... visit the url and log in
$ echo "...." > bbb
# synchronization starts in Termain One
$ ls aaa bbb
ls: cannot access 'aaa': No such file or directory
ls: cannot access 'bbb': No such file or directory
$
```

**Comment by abraunegg** [comment]
@norbusan 
Great work there :)

**Comment by abraunegg** [comment]
Implemented via PR #525

**Comment by rcarmo** [comment]
Thanks, will be testing this next weekend. Where it regards pods being moved around, k8s supports persistent volume claims, and the setup I have I in mind used as shared mounted volume (I considered using a FIFO for talking to the container, but that wouldn’t work on some remote file systems).

**Comment by abraunegg** [comment]
@rcarmo 
Any update in testing this?

**Comment by rcarmo** [comment]
Couldn’t do it this weekend. Will circle back.

**Comment by abraunegg** [comment]
@rcarmo 
Closing this issue as feature implemented & tested locally, however not in a container where interactive cannot be performed.
