### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by ukreddy-erwin** [abraunegg/onedrive#534]
uday@jenkins-server:~/onedrive$ make clean; make; rm -f onedrive onedrive.o version rm -rf autom4te.cache rm -f config.log config.status if [ -f .git/HEAD ] ; then \         echo v2.3.4-1-g56f6343 > version ; \ else \         echo v2.3.5-dev > version ; \ fi ldmd2  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive make: ldmd2: Command not found Makefile:100: recipe for target 'onedrive' failed make: *** [onedrive] Error 127 uday@jenkins-server:~/onedrive$ OS Details:uday@jenkins-server:~/onedrive$ lsb_release -aNo LSB modules are available.Distributor ID: UbuntuDescription: Ubuntu 18.04.2 LTSRelease: 18.04Codename: bionic
--

Even I ran the dependencies commands you mentioned.

Please find the output below.

sudo apt install build-essential

o/p:
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
The following package was automatically installed and is no longer required:
  bridge-utils
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 135 not upgraded.

sudo apt install libcurl4-openssl-dev

o/p:
Reading package lists... Done
Building dependency tree
Reading state information... Done
libcurl4-openssl-dev is already the newest version (7.58.0-2ubuntu3.7).
The following package was automatically installed and is no longer required:
  bridge-utils
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 135 not upgraded.

sudo apt install libsqlite3-dev

o/p:
Reading package lists... Done
Building dependency tree
Reading state information... Done
libsqlite3-dev is already the newest version (3.22.0-1).
The following package was automatically installed and is no longer required:
  bridge-utils
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 135 not upgraded.

sudo apt install pkg-config

o/p:
Reading package lists... Done
Building dependency tree
Reading state information... Done
pkg-config is already the newest version (0.29.1-0ubuntu2).
The following package was automatically installed and is no longer required:
  bridge-utils
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 135 not upgraded.

curl -fsS https://dlang.org/install.sh | bash -s dmd

o/p:
dmd-2.086.0 already installed
Using dub 1.15.0 shipped with dmd-2.086.0

Run `source ~/dlang/dmd-2.086.0/activate` in your shell to use dmd-2.086.0.
This will setup PATH, LIBRARY_PATH, LD_LIBRARY_PATH, DMD, DC, and PS1.
Run `deactivate` later on to restore your environment.

sudo apt install libnotify-dev
o/p:
Reading package lists... Done
Building dependency tree
Reading state information... Done
libnotify-dev is already the newest version (0.7.7-3).
The following package was automatically installed and is no longer required:
  bridge-utils
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 135 not upgraded.

git clone https://github.com/abraunegg/onedrive.git
cd onedrive
./configure
make clean; make;
sudo make install

./configure
o/p:
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... no
checking for ldmd2... no
checking for ldc2... no
configure: error: Could not find any compatible D compiler

uday@jenkins-server:~/onedrive$ make clean; make;
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        echo v2.3.4-1-g56f6343 > version ; \
else \
        echo v2.3.5-dev > version ; \
fi
ldmd2  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
make: ldmd2: Command not found
Makefile:100: recipe for target 'onedrive' failed
make: *** [onedrive] Error 127

**Comment by abraunegg** [comment]
@ukreddy-erwin 
Why open a new issue for the same problem? Please read your output very carefully and the links provided. Essentially ypu are not activating the compiler before configure and compile process.
