### ISSUE TITLE
Update LDC Compiler

### ISSUE THREAD

**Issue by Boia11** [abraunegg/onedrive#547]
New stable release avaliable of LDC compiler (tested on Debian ARM64 and work fine with onedrive code)

Version: 1.15.0

[https://github.com/ldc-developers/ldc/releases/latest](https://github.com/ldc-developers/ldc/releases/latest)

**Comment by norbusan** [comment]
There is nothing to update in this project. Onedrive can be compiled with ldc 1.15.0.
