### ISSUE TITLE
'JSONValue is not an object' exception in sync.isMalware function

### ISSUE THREAD

**Issue by borouhin** [abraunegg/onedrive#550]
### Bug Report Details ###
Crash with the following output when downloading file:
```
Downloading file XXX ... Giving up on sync after three attempts: JSONValue is not an object
std.json.JSONException@std/json.d(306): JSONValue is not an object
----------------
/usr/include/dmd/phobos/std/exception.d:515 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x55b04381cccf]
/usr/include/dmd/phobos/std/exception.d:436 pure @safe bool std.exception.enforce!(std.json.JSONException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x55b04381cc49]
??:? inout pure @property @trusted inout(std.json.JSONValue[immutable(char)[]]) std.json.JSONValue.objectNoRef() [0x55b04386c91d]
/usr/include/dmd/phobos/std/json.d:645 const pure @safe const(std.json.JSONValue)* std.json.JSONValue.opBinaryRight!("in").opBinaryRight(immutable(char)[]) [0x55b043834cbf]
src/sync.d:69 bool sync.isMalware(ref const(std.json.JSONValue)) [0x55b04383e580]
src/sync.d:1113 void sync.SyncEngine.downloadFileItem(itemdb.Item, immutable(char)[]) [0x55b043843043]
src/sync.d:1031 void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x55b043842946]
src/sync.d:973 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x55b04384254c]
src/sync.d:738 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x55b0438412ce]
src/sync.d:391 void sync.SyncEngine.applyDifferences() [0x55b04383f961]
src/main.d:609 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x55b043830163]
src/main.d:390 _Dmain [0x55b04382f53c]
```

**Application and Operating System Details:**
*   OS: `Linux home 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed? Headless
*   OneDrive Account Type: Personal
*   DMD or LDC compiler version: `DMD64 D Compiler v2.086.0`
*   Application configuration: 
```
onedrive version                    = v2.3.4-10-g097b58a
Config path                         = /home/XXX/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/XXX/OneDrive
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /XXX/log/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
*   Curl Version: `curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3`

**To Reproduce**
I encountered this specific error for the first time, seems to be caused by some specific OneDrive error (see additional context below), so it doesn't seem easily reproducible.

**Complete Verbose Log Output**
See above.

**Screenshots**
Not applicable.

**Additional context**
It looks as if fileDetails argument passed to sync.isMalware from sync.downloadFileItem was not a valid JSON. And it happened for some other reason than HTTP 5XX error code (which is handled just above the call to sync.isMalware).

I would also suggest to change the "retry 3 times and than give up" logic.
In my case, the first 2 exceptions were raised hours before the 3rd one (both were "Timeout was reached on handle...") But the counter in catch block in main.performSync persists throughout the entire sync.
But it's quite normal for a long sync to cause multiple errors, if they are not the same and for the same item (which probably indicates a permanent problem).

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Reproduction steps (if applicable)
*   [X] Verbose Log Output

**Comment by abraunegg** [comment]
@borouhin 
Interesting .. i wonder if that bug has been introduced as a result of fixing the other bugs ... looking into it now

**Comment by borouhin** [comment]
@abraunegg,
As far as I can understand, if OneDriveApi.getFileDetails throws a OneDriveException with httpStatusCode<500 this error is inevitable. If it's the 3rd exception in a sync - it leads to crash as well.

This behavior was introduced by adding this block:
```
		catch (OneDriveException e) {
			if (e.httpStatusCode >= 500) {
				// OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error - error message already logged
				return;
			}
		}
```
as it silently dismisses OneDriveExceptions with httpStatusCode<500, but they still lead to invalid fileDetails.

**Comment by abraunegg** [comment]
@borouhin 
Yes - however also, in your other testing - that catch / try block was not even being triggered for some reason .. 

Currently creating a PR

**Comment by abraunegg** [comment]
@borouhin 
Can you help validate the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/551/head:pr551
git checkout pr551
make clean; ./configure; make;
```

**Comment by borouhin** [comment]
@abraunegg, I've built and launched the new version with this PR. I'm not sure, however, whether I encounter such combination of errors anytime soon to test.
Looking at the changes in source code - such error should not happen anymore for sure.

**Comment by abraunegg** [comment]
PR #551 merged
