### ISSUE TITLE
Makefile.in should call git lazily

### ISSUE THREAD

**Issue by sgraf812** [abraunegg/onedrive#553]
### Bug Report Details ###
**Describe the bug**
When building in a pure environment, like those provided by the Nix package manager, the call to `git describe --tags` in Makefile.in is executed whether or not the outer `if` condition actually evaluates to true. This breaks the build in case we aren't in a git repository but also don't have a `git` executable in `PATH`.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Make sure you don't have `git` in your path
2.  Download a tarball or remove the `.git` folder from the source tree
3.  Initiate a build

** Solution **

Here's a patch with a possible solution to this (I hope):

```patch
diff --git a/Makefile.in b/Makefile.in
index 5c6d3e1..95cc877 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -141,7 +141,7 @@ endif
 
 version:
 	if [ -f .git/HEAD ] ; then \
-		echo $(shell git describe --tags) > version ; \
+		git describe --tags > version ; \
 	else \
 		echo $(version) > version ; \
 	fi
```

**Comment by norbusan** [comment]
Agreed, and thanks for the patch!

**Comment by abraunegg** [comment]
Thanks for the patch :) PR #554 merged.
