### ISSUE TITLE
Corrupt files are downloaded silently on OneDrive errors

### ISSUE THREAD

**Issue by borouhin** [abraunegg/onedrive#558]
### Bug Report Details ###
Maybe this bug report is not "clear and concise" as requested, but IMHO this issue should be investigated.
I downloaded a lot of files from OneDrive Personal. After that, I compared the files in freshly downloaded OneDrive folder with the same folder on another computer synced with the same account (did it from Windows, with Total Commander "Synchronize directories" feature).

I found out that some downloaded files contain error messages inside them instead of the actual content. For example:
```
{
  "error": {
    "code": "generalException",
    "message": "An error occurred in the data store.",
    "innerError": {
      "request-id": "a5c11f14-1bf4-4520-ae02-497088a7670c",
      "date": "2019-06-15T04:28:24"
    }
  }
}
```
```
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='content-type'/>
		<style type='text/css'>
			body {font-family:Arial; margin-left:40px; }
			img  { border:0 none; }
			#content { margin-left: auto; margin-right: auto }
			#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }
			#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}
			#errorref { font-size: 11px; color: #737373; margin-top: 41px }
		</style>
		<title>OneDrive</title>
	</head>
	<body>
		<div id='content'>
			<div id='message'>
				<h2>Our services aren't available right now</h2>
				<p>We're working to restore all services as soon as possible. Please check back soon.</p>
			</div>
			<div id='errorref'>
				<span>Ref A: E845636963774FC5A5A1499DFCA0E581 Ref B: STOEDGE0521 Ref C: 2019-06-13T05:57:02Z</span>
			</div>
		</div>
	</body>
</html>
```
(formatted this one for readability, it was actually one long line of HTML code without paragraph breaks and indentation)
```
Service Unavailable
------------------------------------
HTTP Error 503. The service is unavailable.
```
(that's all the contents in the file instead of the actual one)

Several other file have just 0 bytes size.

OneDrive regularly generates some kind of error, sure, but these erorrs should not get into file contents and reside there indefinitely (as onedrive seems to treat them as correctly downloaded and doesn't retry).

**Application and Operating System Details:**
*   OS: `Linux home 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed? Headless
*   OneDrive Account Type: Personal
*   DMD or LDC compiler version: `DMD64 D Compiler v2.086.1`
*   Application configuration:
```
onedrive version                    = v2.3.5-2-gffc8cd2
Config path                         = /home/XXX/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/XXX/OneDrive
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /YYY/log/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
(note: during the sync I changed different onedrive versions to cope with previuos issues reported)
*   Curl Version: Output of `curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3`

**To Reproduce**
Inapplicable. I cannot force OneDrive errors to happen... And they happen not that often. For a folder with 290 000 files just 40 files contained errors of were empty.

**Complete Verbose Log Output**
Nothing was logged for the corrupt files.

**Screenshots**
Inapplicable.

**Additional context**

### Bug Report Checklist ###
*   [X] Detailed description
*   [ ] Reproduction steps (if applicable)
*   [ ] Verbose Log Output

P.S. This issue seems to be ages old as I've found some files corrupt the same way on my old server. These files were downloaded last year.

**Comment by abraunegg** [comment]
@borouhin 
Many thanks - will look into this ASAP.

What 'should' happen is that the 'error' fails and nothing is written out.

**Comment by borouhin** [comment]
@abraunegg, sure, I meant exactly this.

If OneDrive for some unknown reason sometimes reports success (HTTP 200?) with the error in file contents instead - then we should probably check whether the resulting file size after download matches the one reported by OneDrive? This would also help with 0-byte files.

**Comment by abraunegg** [comment]
@borouhin 
Looking at the code - and depending on 'when' these files were created - I think those files with HTML / error codes could have been created before the handling of such responses was added in - those most certainly should be fixed.

Adding in validation that the local file = what should have been downloaded should be done

**Comment by abraunegg** [comment]
@borouhin 
Please can you test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/560/head:pr560
git checkout pr560
make clean; ./configure; make;
```

This will:
* Validate that the file was downloaded (already did this)
* That the file size = what OneDrive reports (new)
* That the file hash = what OneDrive reports (new) 

If 'size' or 'hash' is wrong, then the file is reported as a download error & what was downloaded is 'safe removed' & flagged as 'Download Failed'

**Comment by borouhin** [comment]
@abraunegg, thanks!
I've rebuilt onedrive with this PR. However, I doubt I can do any meaningful testing. The rate of such errors is rare and I have no more hundreds of thousands files to download left...
Maybe later I'll delete a big folder and re-download it again, but not right now.

**Comment by abraunegg** [comment]
@borouhin 
Totally understand .. better to have some check than none at all.

**Comment by abraunegg** [comment]
PR #560 merged

**Comment by abraunegg** [comment]
Closing issue as PR merged
