### ISSUE TITLE
windows docker host: volume mapping fails 'ROOT level priviledges prohibited!' check

### ISSUE THREAD

**Issue by joaoffs** [abraunegg/onedrive#561]
`docker run -it --restart unless-stopped --name docker_onedrive -v /c/dev/tools/personal-onedrive/:/onedrive/conf -v /c/users/myuser/Documents/test:/onedrive/data driveone/onedrive`

The above fails the root priviledges check, any known workaround?

**Comment by abraunegg** [comment]
@joaoffs 
A couple of questions:
* Which 'docker' image are you running? The official one is: https://hub.docker.com/r/driveone/onedrive
* What version of 'docker' are you running?
* What host OS are you running
* What user are you when you are invoking the command above?

**Comment by norbusan** [comment]
I cannot reproduce this:
```
$ mkdir foobar
$ mkdir foobar/data
$ mkdir foobar/conf
$ docker run -it --restart unless-stopped --name docker_onedrive -v ~/foobar/conf:/onedrive/conf -v ~/foobar/data:/onedrive/data driveone/onedrive
++ stat /onedrive/data -c %u
+ ONEDRIVE_UID=1000
++ stat /onedrive/data -c %g
+ ONEDRIVE_GID=1000
++ getent group 1000
+ odgroup=
+ odgroup=onedrive
+ groupadd onedrive -g 1000
++ getent passwd 1000
+ oduser=
+ oduser=onedrive
+ useradd onedrive -u 1000 -g 1000
+ chown onedrive:onedrive /onedrive/ /onedrive/conf
+ ARGS=(--monitor --verbose --confdir /onedrive/conf --syncdir /onedrive/data)
+ '[' 0 -gt 0 ']'
+ exec gosu onedrive /usr/local/bin/onedrive --monitor --verbose --confdir /onedrive/conf --syncdir /onedrive/data
Using Config Dir: /onedrive/conf
No config file found, using application defaults
Initializing the OneDrive API ...
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=REDACTED&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: REDACTED
Opening the item database ...
All operations will be performed in: /onedrive/data
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: REDACTED
Default Root ID: REDACTED!126
Remaining Free Space: REDACTED
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing monitor ...
OneDrive monitor interval (seconds): 45
Monitor directory: .
Applying changes of Path ID: REDACTED!126
Processing 206 changes
Creating directory: XXXX
Creating directory: XXXXX
Creating directory: XXXXX
Downloading file XXXXX ... done.
...
```

From the name of the drive `/c/dev/tools/personal-onedrive/:/onedrive/conf` I assume you have the Windows drive mounted via ntfs-3g. I am not sure whether this is supported.

**Comment by joaoffs** [comment]
@abraunegg :
- I'm using the official docker image
- my docker version is 18.09.2
- Windows 10
- tried with both my own user and with elevated privileges with the same outcome

@norbusan : Your assumption is correct, this is a windows host.

This use case might not be common and therefore unsupported because in theory, on windows one could just use the OneDrive windows client, in my case I can't so I'm just looking for a workaround.

**Comment by abraunegg** [comment]
@joaoffs 
This may be applicable to your situation:

https://medium.com/@Charles_Stover/fixing-volumes-in-docker-toolbox-4ad5ace0e572

It also may mean your command needs to be modified:
```
docker run -it --restart unless-stopped --name docker_onedrive -v //c/dev/tools/personal-onedrive/:/onedrive/conf -v //c/users/myuser/Documents/test:/onedrive/data driveone/onedrive
```

**Comment by joaoffs** [comment]
Thanks @abraunegg that wouldn't be applicable as i'm using hyper-v, not VirtualBox. I found this is a known limitation on docker for windows reported here https://github.com/docker/docker.github.io/issues/3298

There's apparently no workaround so I'll just accept this is not going to work, thanks guys.
