### ISSUE TITLE
Not all files being downloaded

### ISSUE THREAD

**Issue by CaptainJawZ** [abraunegg/onedrive#563]
### Bug Report Details ###
So I have just installed the application and when I run onedrive --synchronize --resync 
it will start downloading files but it will only download about 60 files from a folder containing 300 files. 
I am of course using test folders. I've tried a different array of settings and configurations but nothing seems to work. 

**Application and Operating System Details:**
*   OS: Linux Workstation 4.19.49-1-MANJARO #1 SMP PREEMPT Sun Jun 9 20:24:20 UTC 2019 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed? Using: KDE plasma
*   OneDrive Account Type: Personal
*   DMD or LDC compiler version: DMD64 D Compiler v2.086.0
*   Application configuration: Output of `onedrive --display-config`:
```
onedrive version                    = v2.3.5-8-g4a4611c
Config path                         = /home/jawz/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/jawz/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
Desktop
2019
```
*   Curl Version: curl 7.65.1

**Comment by abraunegg** [comment]
@CaptainJawZ 
Please can you provide detailed logging and details as per https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md as you provide zero details as to if an error is being generated

**Comment by CaptainJawZ** [comment]
I'm very sorry for not providing it, I've generated it: 
[debug_output.log](https://github.com/abraunegg/onedrive/files/3353388/debug_output.log)

**Comment by abraunegg** [comment]
@CaptainJawZ 
Looking at your log file you have many many many errors stemming from unable to query OneDrive for file details, but also you appear to be deleting your OneDrive directory before starting the application.

**Comment by CaptainJawZ** [comment]
I delete it just so I can re-download the test folder. But even if I delete the database before doing so, it wont won't download all the files. 
What could happen to prevent the query of OneDrive files?

**Comment by abraunegg** [comment]
@CaptainJawZ 
Can you please test the following PR against your test cases:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/564/head:pr564
git checkout pr564
make clean; ./configure; make;
```

That should take care of the erroneous database inserts when the query is failing.

> What could happen to prevent the query of OneDrive files?

So this would indicate the following:
* Some sort of internal OneDrive issue - but the actual internal error is being suppressed somewhere
* Incorrect outbound request being generated - but that query is based on the information received from OneDrive itself .. so .. leads back to the first dot point. 

The only way to truly know what is going on would be to use the `--debug-https` flag and see what is being sent & received when this error `ERROR: onedrive.getFileDetails call returned a OneDriveException error` is being thrown.

**Comment by CaptainJawZ** [comment]
Alrighty I inputed the codes you gave me, and then ran the debug log again with the debug-https flag the debug file is now 300mbps 
Tried to find Error: onedrive lines but found none still here is the log: 
https://1drv.ms/u/s!AsPHe5lOdL1hosQ5DAvnzVPQ4Gbl7Q

So I purged the sql database and ran the command again with less files this time and an the code again, once again the output was a very big file 
https://1drv.ms/u/s!AsPHe5lOdL1hosk04dZDKY1yLcRzGQ?e=5POaTS

**Comment by abraunegg** [comment]
@CaptainJawZ 
Did you run with the PR version provided?

**Comment by CaptainJawZ** [comment]
I think so should I have uninstalled the previous versionfor this new one to have worked? Or use a special code to call it?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by abraunegg** [comment]
@CaptainJawZ 
Looking at the 300Mb log right now - all files appear to have been successfully downloaded without issue or error.

Can you confirm that all the files you are expecting to have downloaded - have been downloaded?

Can you run the PR with just the following to confirm:
```
./onedrive --synchronize --verbose --resync 
```

**Comment by abraunegg** [comment]
@CaptainJawZ 
Any update from your side as to if this is now working as it should?

**Comment by CaptainJawZ** [comment]
Apologies, it was night time in my country. So I've been working for a few hours now trying to make it work, again without positive results, i've tried to put it on a different hard drive (since it seemed to work with the outdated onedrive this one is forked from) 

Also I set up a new folder with new files in case there is a specific problem with the files, but still it doesnt seem to download a whole bunch of them. 
Also I discovered that as it seems, running the command just once, when it finishes downloading files by the end it deleted whichever files it didn't downloaded. 

Here is the newest log as well as a screenshot to see if I'm doing it right 
![Terminal screenshot](https://user-images.githubusercontent.com/43111068/60622981-3a9d5700-9da7-11e9-9a44-98ec6dacc7b6.png)

[debug_output.log](https://github.com/abraunegg/onedrive/files/3356714/debug_output.log)

**Comment by abraunegg** [comment]
@CaptainJawZ 
That error means you still have a 'onedrive' process running 'somewhere'

**Comment by CaptainJawZ** [comment]
I find that unlikely as I don't have any one drive process running on my processes and it seems like the service isn't outputting any logs and is neither started.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by abraunegg** [comment]
@CaptainJawZ 
When you get this error:
```
A database statement execution error occurred: disk I/O error
```
This is indicative of:
* A rouge / still running processes and your trying to re-execute 'onedrive'
* Incorrect permissions for the files / folders in your config directory

**Comment by CaptainJawZ** [comment]
So for the past two hours or so I've been experimenting with this, restarting my computer several times and making sure the service isnt running. 

there was a time where it actually worked and it synched all of my files and I'm sure it was by running the ./onedrive from within the onedrive master directory. 

Unfortunately I have yet to be able to replicate said results. 
I've been running the script several times, each time I follow these steps:
1) stop service and onedrive if its running
2) delete the local files
3) make a copy of my test files from the onedrive page 
4) delete the items* files from the ~/.config/onedrive directory 

Run the commands, here are the output logs:
running:
onedrive --synchronize --verbose --resync >> debug_output.log 2>&1
[debug_output(Normal).log](https://github.com/abraunegg/onedrive/files/3357144/debug_output.Normal.log)

running: 
./onedrive --synchronize --verbose --resync >> ~/"debug_output(debug 2).log" 2>&1   
[debug_output(debug 2).log](https://github.com/abraunegg/onedrive/files/3357145/debug_output.debug.2.log)

and lastly I let the service run. 

Neither of the instances downloaded all of my files and some deleted them. 
It only worked once and unfortunately I have yet to be able to replicate the steps.

**Comment by abraunegg** [comment]
@CaptainJawZ 
So depending on what binary your running - will depend on the results:

What does:
```
onedrive --version
````
and
```
./onedrive --version
```
return?

Possibly you have an older version of the client 'installed' somewhere in a search path and this is the one that is being run when the downloads are failing

**Comment by CaptainJawZ** [comment]
There is a version mismatch I'll purge everything OneDrive related and give you an update later tonight gonna be bussy for a couple hours.

**Comment by abraunegg** [comment]
@CaptainJawZ 
No problem. Please ensure that the version you are running is:
```
./onedrive --version
onedrive v2.3.7
```
and
```
onedrive --version
onedrive v2.3.7
```

**Comment by CaptainJawZ** [comment]
Hello, so I purged my onedrive installations and installed the v2.3.7 
I ran the code:

**Comment by abraunegg** [comment]
@CaptainJawZ 
Can you provide the following:
* A folder listing of what you are expecting to be downloaded (ie a list of everything on OneDrive)
* A listing of what actually gets downloaded

I have attempted to replicate this thus far using dummy data & similar folder names / structures - and everything downloads 100% of the time without issue.

**Comment by CaptainJawZ** [comment]
Would a log from windows with cmd printing a list of the files within the folder and the same on Linux be good enough for that?

**Comment by abraunegg** [comment]
Whatever works / gives a reliable listing

**Comment by CaptainJawZ** [comment]
Here are the result files
Here is a list of the files from Windows, the files I expect to sync fully
[Expected.txt](https://github.com/abraunegg/onedrive/files/3358080/Expected.txt)
And here is a list of the files thad ended up on linux after running the onedrive --synchronize --resync etc command
[result.txt](https://github.com/abraunegg/onedrive/files/3358082/result.txt)

And lastly here is the log 
[files_test.log](https://github.com/abraunegg/onedrive/files/3358090/files_test.log)

**Comment by abraunegg** [comment]
@CaptainJawZ 
Thanks. As this is also just 'test data' can you archive the entire source and provide that? I want to try and fully replicate this as much as possible.

**Comment by abraunegg** [comment]
@CaptainJawZ 
Looking at the logfile as well - there is missing output when there is an error (as seen by the lines where the client indicates it is downloading but .. nothing is happening)

Please can you re-run your tests but use the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/568/head:pr568
git checkout pr568
make clean; ./configure; make;
```

This should introduce some additional logging to make things a little more clear.

When running, this will be `v2.3.7-1-ge6f6660` as evidenced in the logs.

**Comment by CaptainJawZ** [comment]
Hello! I ran your instructions 
![Screenshot_20190704_031050](https://user-images.githubusercontent.com/43111068/60650256-681aec80-9e09-11e9-9eb7-08ff6dcafda7.png)

This is the output log: 
[debug_output.log](https://github.com/abraunegg/onedrive/files/3358389/debug_output.log)

And I really appreciate all your help with this issue which is why I feel bad not being able to share with you my test archive because while its just a copy of dummy images, most of them are rather private in nature. 

this log seems to show different new date I hope it helps for a bit, it's night time here but tomorrow I'll see about making a folder containing 300 or so files that I am comfortable sharing and then repeat tonight test. 

Although in my experience so far these files have been synched (even the ones that dont sync) whenever there are less files on the folder, like if I only copy the first 50 files on the folder they seem to sync properly.

**Comment by abraunegg** [comment]
@CaptainJawZ 
OK .. so the error is this:
```
onedrive.getFileDetails call did not return valid data or returned an invalid JSON Object
```

So this means one of 3 things:
* That the object has no reported file size
* That the object has no hash 
* That the element is not a JSON object

Now - it cant be the last, as otherwise it would have been a different error message - so one of the other 2 is what is tripping this up - but what.

Can you rebuild the PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/568/head:pr568
git checkout pr568
make clean; ./configure; make;
```

This will give you `onedrive v2.3.7-2-ge0d98a6`. If you can re-run your tests and provide the debug log that will be great.

**Comment by abraunegg** [comment]
@CaptainJawZ 
Any update in regards to testing the updated PR ?

**Comment by CaptainJawZ** [comment]
I'm very sorry I had to spend most of my day on Windows because of work, so I followed your instructions and it seems as if this new version worked
I leave here the log and will do some more tests
[debug_output.log](https://github.com/abraunegg/onedrive/files/3361387/debug_output.log)

**Comment by abraunegg** [comment]
@CaptainJawZ 
Many thanks for the feedback. Marking this as fixed.

**Comment by abraunegg** [comment]
Closing issue as resolved

**Comment by CaptainJawZ** [comment]
So it seems that running the command onedrive still doesnt sync all files which is expected since It's running on the old version. 

How can I make sure that the new version that you indicated me to download gets installed? is it just following the normal steps after uninstalling and using git or do I still have to use the: 
git fetch origin pull/568/head:pr568
git checkout pr568
commands?

**Comment by abraunegg** [comment]
@CaptainJawZ 
Inside the directory where you have the 'working' version - perform a `make install` or `sudo make install` (whatever is applicable for your system / environment). This 'should' take the PR version you have been testing with and 'install' it over the top of whatever version you have elsewhere that is broken.

Then you can validate that it installed correctly:
```
onedrive --version
```

**Comment by CaptainJawZ** [comment]
I can confirm onedrive --version and ./onedrive --version both print onedrive v2.3.7-6-gfb9d268
and upon doing a make install onedrive seems to download all desired files.

Thank you so much! sorry if at times I was slow. 
This app is a life saviour as recently I had to start using Linux to work on a project however using also windows and being highly dependant of OneDrive this app saved me a lot of time! 

Thank you so much for your support and for working on this.

**Comment by abraunegg** [comment]
No problem - glad it is all working now as intended
