### ISSUE TITLE
Resource leak where onedrive.service fails silently 

### ISSUE THREAD

**Issue by MatthewFallon** [abraunegg/onedrive#567]
### Bug Report Details ###
**Describe the bug**
I will start off by mentioning that I actually did easily fix this bug myself by simply removing and reinstalling the package, but I wanted to bring up the fact that I hit this bug at some point and didn't know whether to file it as a feature request or a bug, so apologies if I've marked it wrong.

I actually really appreciate the fact that you take the time to maintain this package and am happy to see how far this package and its upstream source has grown, I haven't paid much attention to it other than running updates on it since I installed it and back when I installed it its only command was `onedrive` which acted as `onedrive --synchronize` and there was no daemon functionality. I just ran it as a cron job which I assume started failing silently at some point when the command changed as these things normally do :laughing: 

I just wanted to bring up the fact that I was attempting to be pretty low maintenance with this package and that it ended up causing problems that might be occurring for other users of the package while they don't even know it.

What I am speaking of is the fact that at some point the program installed and also enabled a onedrive service as root user that obviously would fail as I had up until then run the onedrive command authorized as my user, not root.

This in and of itself isn't an issue but the fact that it has a restart policy meant that the service has been enabled and sapping system resources to continually stop and restart while I didn't even notice for however long since it first created this root service.

I actually wouldn't have ever known except I recently started playing with creating systemd services and when I checked the systemd journal to see my service I found the ENTIRE log was filled with endless failure messages from the onedrive service telling me it wasn't authorized :laughing: 

If the onedrive service is not authorized then there is no possible way for it to ever restart gracefully, and I don't know super much about systemd but I was wondering if there was a way to have the service disable itself if it the process exited with the exit code for not being authorized in order to close this resource leak, leaving it to the user to reauthorize the user it needed to and restart the systemd service for themselves.

Perhaps it would also be a good idea to somehow alert the user the service is disabled again, maybe by nesting the parent onedrive folder inside of another new folder saying it was broken or something, but at the very least I see no point in having a service just repeatedly fail when it can't possibly recover on its own. And this could also apply for users if the authorization somehow changes or expires. The service should just stop happening until they go into the terminal and reauthorize.

Thank you for taking the time to read through this I appreciate it. Thanks for the great work and help maintaining the packaging for this project :+1: 

**Application and Operating System Details:**
*   OS: Linux grapefruit-lacroix-local 5.1.12-300.fc30.x86_64 #1 SMP Wed Jun 19 15:19:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
*   Gnome Desktop 3.32
*   OneDrive Account Type: personal
*   Installed through dnf repo 
*   Application configuration: Output of `onedrive --display-config`
```
$ onedrive --display-config
onedrive version                    = 2.3.5
Config path                         = /home/matthewfallon/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/matthewfallon/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
*   Curl Version: Output of `curl --version`: N/A

### Bug Report Checklist ###
*   [x] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment]
@MatthewFallon 
Thanks for the info - also - as your running v2.3.5, silent exit's were an issue if your Curl version is above 7.62, which was fixed in later releases - so your probably better off running the latest release rather than v2.3.5

| What I am speaking of is the fact that at some point the program installed and also enabled a onedrive service as root user that obviously would fail as I had up until then run the onedrive command authorized as my user, not root.

This should 'only' occur if you run 'make install' however as you are installing via 'Installed through dnf repo' - I have no idea here as the package maintainer is probably doing something to install the service files by default and activating - which they should not do.

Where are you installing the package from?

**Comment by norbusan** [comment]
@MatthewFallon you are reporting problems with the RedHat/Fedora (my guess due to `dnf` in your description) packaging of OneDrive. Please direct these complains to the respective bug place.

We here provide Systemd service files, but do **not** activate/start them whatsoever. This means, if a service was activated/started on your computer, it was due to the packaging of RedHat/Fedora or other influences, but nothing we can do here.

Thanks

@abraunegg I think this can/should be closed.

**Comment by abraunegg** [comment]
@norbusan 
Agreed. Looking also however at the spec file for onedrive from Fedora 30:
```
%global project abraunegg
%global repo onedrive

Name:           onedrive
Version:        2.3.5
Release:        1%{?dist}
Summary:        OneDrive Free Client written in D
License:        GPLv3
URL:            https://github.com/%{project}/%{repo}
Source0:        %{url}/archive/v%{version}/%{repo}-v%{version}.tar.gz
BuildRequires:  ldc
BuildRequires:  libcurl-devel
BuildRequires:  libnotify-devel
BuildRequires:  sqlite-devel
BuildRequires:  systemd
Requires(preun): systemd
ExclusiveArch:  %{ldc_arches}

%description
Free CLI client for Microsoft OneDrive written in D.

%prep
%setup -q -n %repo-%{version}
# sed -i 's|version ||g' Makefile
# sed -i '/chown/d' Makefile.in
sed -i 's/-o root -g users//g' Makefile.in
sed -i 's/-o root -g root//g' Makefile.in
# sed -i '/git/d' Makefile
sed -i "s|std\.c\.|core\.stdc\.|" src/sqlite.d
echo %{version} > version

%build
%configure
export DFLAGS="%{_d_optflags}"
export PREFIX="%{_prefix}"
make DC=ldmd2 %{?_smp_mflags}

%install
%make_install \
    PREFIX="%{_prefix}"
chmod a-x %{buildroot}/%{_mandir}/man1/%{name}*

%preun
%systemd_user_preun %{name}.service
%systemd_preun %{name}@.service

%files
%doc README.md LICENSE CHANGELOG.md
%{_bindir}/%{name}
%{_userunitdir}/%{name}.service
%{_unitdir}/%{name}@.service
%{_mandir}/man1/%{name}.1.gz
%{_docdir}/%{name}
%config %{_sysconfdir}/logrotate.d/onedrive
```

Nothing stands out in the spec file for enabling the service files by default by install .. so no idea what has occured here at all

**Comment by MatthewFallon** [comment]
Ok, thanks for the mention about the newer Curl issues I'll probably build from source off of here to keep myself updated to the newest version instead, and apologies about the report having to do with DNF, I just followed up with an issue here because when I grabbed the info for the package it listed this github repo for the URL so I wondered if the fedora dnf package repo maintainers were perhaps working with you on putting out their releases.

Yes it was just coming from the standard fedora 30 repo and that spec file doesn't denote actually enabling the service at any point, it's possible that I inadvertently enabled the service in some other way as a dumb user haha.

My only actual main question is actually then about this logging I noticed which actually I probably should have included at first. Perhaps silent is the wrong term for this as it did throw an error in the logs just not one that a general user would see or be able to respond to, sorry kind of a newbie. my systemd logging output was:

```
systemd[1852]: Started OneDrive Free Client.
onedrive[14568]: Initializing the Synchronization Engine ...
onedrive[14568]: Invalid authentication response from OneDrive. Please check the response uri
onedrive[14568]: Authorize this app visiting:
onedrive[14568]: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21>
onedrive[14568]: Enter the response uri: Invalid uri
onedrive[14568]: ERROR: OneDrive returned a 'HTTP 401 Unauthorized' - Cannot Initialize Sync Engine
onedrive[14568]: ERROR: Check your configuration as your access token may be empty or invalid
systemd[1852]: onedrive.service: Main process exited, code=dumped, status=11/SEGV
systemd[1852]: onedrive.service: Failed with result 'core-dump'.
systemd-coredump[14576]: Process 14568 (onedrive) of user 1000 dumped core.
                                                                  
                                                                  Stack trace of thread 14568:
                                                                  #0  0x0000000000000000 n/a (n/a)
systemd[1852]: onedrive.service: Service RestartSec=3s expired, scheduling restart.
systemd[1852]: onedrive.service: Scheduled restart job, restart counter is at 12157.
systemd[1852]: Stopped OneDrive Free Client.
```

I have literally thousands of these as you can see from the insane restart counter on this service, this is just one from before I went in and fixed the issue for myself. 

I just noticed that, once the systemd service had been started by the wrong user, it would throw up an error stating it couldn't connect without an access token into the logs, but then would not really react to that error message and would rely on the user to eventually find the erroneous service and either run onedrive as that user to create an access token or to disable the service. I was more just wondering if it was feasible or a good idea to have the service somehow stop restarting itself during a session after this error, or possibly to have it disable that enabled version of the service altogether, in order to prevent this service from falling in to an endless start, fail, exit with error, and restart cycle that it has the easy potential to fall into.

It's totally ok if you want to close the issue thread after this, I didn't mean to take up too much of your time, thanks.

**Comment by abraunegg** [comment]
> I was more just wondering if it was feasible or a good idea to have the service somehow stop restarting itself during a session after this error, or possibly to have it disable that enabled version of the service altogether, in order to prevent this service from falling in to an endless start, fail, exit with error, and restart cycle that it has the easy potential to fall into.

This is not really possible - as this would require systemd to know what to do when the application fails or generates certain output.

Essentially - you should only enable the service if:
* You know it is working
* You have enough monitoring / checking in place to determine if something stops working

**Comment by abraunegg** [comment]
Closing issue - question answered

**Comment by norbusan** [comment]
In addition to what @abraunegg , this is a systemd issue. It should not try to restart a service ad infinitum when it fails. But don't get me started on systemd ...

**Comment by MatthewFallon** [comment]
@norbusan  Oh I will bring up what I found really quickly searching around about systemd, it seems the only reason it does this in this case is because you actually set the service to `restart=on-failure` which directly tells systemd to do exactly that with this service. You could force it to never restart after this specific error code, it looks like 11 in this case by including `RestartPreventExitStatus=11` which would tell it to never restart the service when it exited on exit status = 11 or something like that. Sorry if that's the wrong thing. I understand the hate-love relationship with systemd haha.

**Comment by norbusan** [comment]
Well, `restart=on-failure` is something that we probably could remove now, I agree. @abraunegg WDYT?

The reason it was there is that in old versions the client failed when there were connection problems, etc, so it was good that it actually got restarted.

Now we carefully (more or less) handle all errors and dont terminate if not necessary, so the `on-failure` could reasonably be removed.

**Comment by abraunegg** [comment]
@norbusan 
It probably needs to be tested extensively before making the change so that we are clear on how / when it stops / when it fails to get going again

**Comment by norbusan** [comment]
@abraunegg sure, but I am running it since ages now in permanent monitor mode and it often stumbles due to network connection, but never crashed ;-) So **my** tests are fine.
