### ISSUE TITLE
Regular "There was a problem in accessing the Microsoft OneDrive service - Internet connectivity issue?" 

### ISSUE THREAD

**Issue by nodje** [abraunegg/onedrive#569]
### Bug Report Details ###
**Describe the bug**
Recurring error message 
`
Cannot initialize connection to OneDrive
There was a problem in accessing the Microsoft OneDrive service - Internet connectivity issue?` 
from which onedrive sync never seem to recover.

Once it starts it just keeps being in error.

I get the problem every one or two days and can't do anything but restart the problem.

It's kind of annoying, and frustrating, as it otherwise works perfectly.

Anything to do about it? Can I get more debug information?

**Application and Operating System Details:**
*   OS: Linux 5.0.0-19-generic #20-Ubuntu Ubuntu 19.04
*   Used mostly headless but some user session with XRDP
*   OneDrive Account Type: probably standard
*   DMD64 D Compiler v2.086.1
*   Application configuration: 
```
jean@shura:~$ onedrive --display-config
onedrive version                    = v2.3.5
Config path                         = /home/user/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /media/share/OneDrive
Config option 'skip_dir'            = Some Dir
Config option 'skip_file'           = ~*|.~*|*.tmp|.DS_Store|._.DS_Store|._*
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
*   Curl Version: 
```
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.6/openssl/zlib nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Note:** If curl version is >= 7.62.0 please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au
Generated file is 300k lines long, I guess a subset of it should be enough. Besides, as said, things work perfectly, I'm unconvinced this log would help as it describes a working config.

**Comment by abraunegg** [comment]
Please make sure you are using v2.3.7 or later as your version is defaulting to using http/2 calls due to your curl version

**Comment by nodje** [comment]
thanks, will do that asap and wait a few days see if it gets better.

**Comment by abraunegg** [comment]
@nodje 
Any update with running the latest codebase?

**Comment by nodje** [comment]
So far so good is all I can say, taking in account the nature of the problem!
It looks good, I'll close the issue and reopen if needed.
Thanks
