### ISSUE TITLE
Error on resync - dwarfeh(371) fatal error

### ISSUE THREAD

**Issue by sibero80** [abraunegg/onedrive#573]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
Trying to sync for the first time, using RESYNC argument, because I'm using the folder list feature to sync only 2 folders for now.
Folder 1 - 85GB, 3900 files.
Folder 2 - 132GB, 15400 files.

When syncing videos within file size limitations, the process fails.

**Application and Operating System Details:**
*   OS: Linux DietPi 4.14.111+ #1 SMP PREEMPT Thu Apr 18 11:16:51 UTC 2019 armv7l GNU/Linux
*   Headless
*   Personal OneDrive (Paid Home O365)
*   LDC Version: ldc2-1.13.0-linux-armhf (as per ARMHF install instructions)
*   Curl Version: 
```
curl 7.52.1 (arm-unknown-linux-gnueabihf) libcurl/7.52.1 OpenSSL/1.0.2r zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```
*   Application configuration:
```
onedrive version                    = v2.3.6
Config path                         = /home/dietpi/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /mnt/USB2TB/OneDrive
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
Audiobooks
Fotos
```

**Note:** If curl version is >= 7.62.0 please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

Once the full debug log has been generated & emailed, please retry your sync by adding `--force-http-1.1`. If this is successful, please advise in issue ticket that `--force-http-1.1` was successful in resolving your issue.

**Complete Verbose Log Output**
https://pastebin.com/vBTRNVaq

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Verbose Log Output

**Comment by abraunegg** [comment]
@sibero80 
Your running a version which is flagged as DO NOT USE - `v2.3.6` has a regression. Please rebuild / retest with 'master'.

**Comment by abraunegg** [comment]
@sibero80 
Also - there appears to be a v1.16.0 version of LDC for ARMHF now as well - which, prior to this release v1.13.0 was the latest for ARMHF. It would be worth:
* Rebuilding with latest 'master'
* Rebuilding with v1.16.0 version of LDC

I am unable to reproduce this at all, and reading / research thus far points to a compiler issue.

**Comment by abraunegg** [comment]
@sibero80
Any update in testing the updated LDC ?

**Comment by sibero80** [comment]
I rebuilt and compiled used updated LDC and got the same result.
Tried accesing the filer using sha256sum and got Input/output error on the file.
Will mark issue as closed as it is an issue with my HDD.

**Comment by abraunegg** [comment]
@sibero80 
No problem. It would be worth ensuring that your local file system protects against silent corruption & maintains file integrity as well.
