### ISSUE TITLE
Linux changes no more uploaded to OneDrive account

### ISSUE THREAD

**Issue by asnowfix** [abraunegg/onedrive#575]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**

`onedrive` no more upload change on Linux to my OneDrive account. Changes on my Windows machines are correctly propagated to my Linux machine.

**Application and Operating System Details:**
*   OS: Output of uname -a:

```
$ uname -a
Linux ncelrnd2450 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

*   Are you using a headless system (no gui) or with a gui installed? **Laptop, using vanilla GNOME**
*   OneDrive Account Type: **OneDrive for Business with an Office 365 account.**
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`

```
dmd --version
DMD64 D Compiler v2.086.1
Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

*   Application configuration: Output of `onedrive --display-config`

```
onedrive --display-config
onedrive version                    = v2.3.7
Config path                         = /home/fkowalski/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/fkowalski/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = .git|~*|*~|.dropbox*|thumbs.db|Games/*.iso|Desktop.ini
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 60
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

*   Curl Version: Output of `curl --version`

```
curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**

```
$ ./onedrive -m -d
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 60
Syncing changes from OneDrive ...
[...]
```

Many changes on Linux, none of them causing any output in the console....

```
[...]
Syncing changes from OneDrive ...
[...]
```

Changes on Windows: causing console output:

```
[...]
Processing 5 changes
Downloading file Documents/ACS/ACS Pipeline/New Rich Text Document.rtf ... done.
Processing 5 changes
Moving Documents/ACS/ACS Pipeline/New Rich Text Document.rtf to Documents/ACS/ACS Pipeline/foo.rtf
Syncing changes from OneDrive ...
Processing 5 changes
Downloading file Documents/ACS/ACS Pipeline/foo.rtf ... done.
```

~~If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au~~

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

The problem does not happen with `--synchronize` option: only with `--monitor`. Changes from Linux are correctly propagated by a `--synchronize` run.

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Additional context**

This happened in v2.3.6, v2.3.7. I did not check which version it started with. Former non-GNU autotools version was not having the problem & I was activating Inotify manually before (with an environment variable provided at build time).

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Reproduction steps (if applicable)
*   [X] Verbose Log Output (with `--monitor` option)

**Comment by abraunegg** [comment]
@asnowfix 
Please can you validate against the latest 'master' please. This is probably issue #563.

**Comment by abraunegg** [comment]
@asnowfix 
Also - you are invoking 'download only' mode:
```
onedrive -m -d
```
Local Linux changes will be skipped and not 'uploaded' as you are explicitly telling the application 'download only'

**Comment by abraunegg** [comment]
@asnowfix 
Confirmed behaviour on `4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` that is this is due to the `-d` flag being used - which prevents local changes from being uploaded.

**Comment by asnowfix** [comment]
Hehehe, `-d` use to be equivalent to `--debug`: it was sticking in my startup script. I confirm v2.3.7 works as expected.

**Comment by abraunegg** [comment]
> `-d` use to be equivalent to `--debug`

Not for this application however :) It has always been for download only - going all the way back to 'skilion' v1.1.1 where this was introduced: https://github.com/skilion/onedrive/commit/764975e2247eae9a7b4b6ea13de21584bfa3beb1 

Perhaps this should be something that should be changed - as in - drop the use of `-d` ?

**Comment by norbusan** [comment]
@abraunegg See https://github.com/abraunegg/onedrive/pull/577 - WDYT?

**Comment by abraunegg** [comment]
@abraunegg 
All good - approved and merged
