### ISSUE TITLE
Error in centos 6.10

### ISSUE THREAD

**Issue by sombrakey** [abraunegg/onedrive#576]
Hi, the command below gave error in the centos:
```
(dmd-2.087.0)[root@shared ~]# mock --rebuild sqlite-3.7.15.2-2.fc19.src.rpm
..
(...)
..
attach-6.1... Ok
attach-6.2...
**** Tests do not work when run as root ****
make: *** [test] Error 1


Erros na construção do RPM:
erro: Status de saída de /var/tmp/rpm-tmp.bER1IP inválido (%check)
    Status de saída de /var/tmp/rpm-tmp.bER1IP inválido (%check)
ERROR: Exception(sqlite-3.7.15.2-2.fc19.src.rpm) Config(epel-6-x86_64) 3 minutes 40 seconds
INFO: Results and/or logs in: /var/lib/mock/epel-6-x86_64/result
ERROR: Command failed. See logs for output.
 (root) bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/sqlite.spec
(dmd-2.087.0)[root@shared ~]#
```

**Comment by sombrakey** [comment]
I created a new user I ran the command and passed, but now said I did not recognize the package

(dmd-2.087.0)[root@shared onedrive]# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.087.0
checking for curl... yes
checking for sqlite... no
configure: error: Package requirements (sqlite3) were not met:

No package 'sqlite3' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables sqlite_CFLAGS
and sqlite_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by abraunegg** [comment]
@sombrakey 
To get the pre-requesites installed under CentOS 6 you need to follow: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-centos-6x--rhel-6x
```
sudo yum -y update
sudo yum -y install epel-release, wget
sudo yum -y install mock
wget https://kojipkgs.fedoraproject.org//packages/sqlite/3.7.15.2/2.fc19/src/sqlite-3.7.15.2-2.fc19.src.rpm
mock --rebuild sqlite-3.7.15.2-2.fc19.src.rpm
sudo yum -y upgrade /var/lib/mock/epel-6-{arch}/result/sqlite-*
```

You have installed mock, rebuilt sqlite, but you have not installed / upgraded sqlite after rebuilding with mock.

You need to look at the mock build log to determine where the built RPM files are, then install the right sqlite RPM's.

**Comment by sombrakey** [comment]
I'm going to retake the tests.
