### ISSUE TITLE
After rename folder - no sync/upload for additional files in this folder in monitor mode

### ISSUE THREAD

**Issue by naui11** [abraunegg/onedrive#578]
### Bug Report Details ###
**Describe the bug**
After renaming a folder from "test" to ".test" the log file confirms with "Moving ./test to ./.test". When a new file is created in the renamed folder the file is not uploaded to onedrive. The log file output is "Skipping uploading this new file as parent path is not in the database: .test/no3.txt". It seems the local database is not updated correctly in case of a folder rename with this special name. This issue only occurs with the special name, having '.' at the front name.

When creating an additional folder, it seems a full sync occurs and is also sync the missing files and updating the database correctly. If you stop the --monitor and do a --synchronize will also sync the files.

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
Linux xxx 5.1.16-300.fc30.x86_64 #1 SMP Wed Jul 3 15:06:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Fedora 30
*   Are you using a headless system (no gui) or with a gui installed?
dnf install onedrive
*   OneDrive Account Type
OneDrive (no business)
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
*   Application configuration: Output of `onedrive --display-config`
```
onedrive version                    = v2.3.7-3-gf39621c
Config path                         = /home/xxx/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /data/sync_onedrive1
Config option 'skip_dir'            = appl|portable
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
*   Curl Version: Output of `curl --version`
```
curl 7.64.0 (x86_64-redhat-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1c zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.7/openssl/zlib nghttp2/1.38.0
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink
```
**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Rename an existing folder (for example "mv test4b .test4b")
(log file confirms with "Moving ./test4b to ./.test4b")
(rename is confirmed on OneDrive)
2.  Create a file in the folder "./test" like "echo >.test4b/testfile3.txt"
(it skips the upload)
(it is not uploaded to OneDrive)

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --monitor --verbose
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
...
2019-Jul-10 02:06:24.0801149 [DEBUG] event IN_MOVED_FROM: ./test4b
2019-Jul-10 02:06:24.0803317 [DEBUG] event IN_MOVED_TO: ./.test4b
2019-Jul-10 02:06:24.0804913 Monitor directory: ./.test4b
2019-Jul-10 02:06:24.0806568 [M] Item moved: ./test4b -> ./.test4b
2019-Jul-10 02:06:24.0807725 Moving ./test4b to ./.test4b
2019-Jul-10 02:06:24.6352518 [DEBUG] Adding to database: Item("xxxxxxxxxxxxxxxx", "XXXXXXXXXXXXXXXX!125279", ".test4b", dir, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 2019-Jul-10 00:05:59.344Z, "XXXXXXXXXXXXXXXX!999", "", "", "", "", "")
2019-Jul-10 02:06:35.6571391 [DEBUG] event IN_CREATE: .test4b/testfile3.txt
2019-Jul-10 02:06:35.6574017 [DEBUG] event IN_CLOSE_WRITE and ...: .test4b/testfile3.txt
2019-Jul-10 02:06:35.6574876 [M] File changed: .test4b/testfile3.txt
2019-Jul-10 02:06:35.6575585 Uploading differences of .test4b/testfile3.txt
2019-Jul-10 02:06:35.6579129 Uploading new items of .test4b/testfile3.txt
2019-Jul-10 02:06:35.658141 [DEBUG] Checking file: .test4b/testfile3.txt
2019-Jul-10 02:06:35.6586308 Skipping uploading this new file as parent path is not in the database: .test4b/testfile3.txt
2019-Jul-10 02:06:35.6587743 Remaining free space: 96306108899
2019-Jul-10 02:06:51.163103 Applying changes of Path ID: XXXXXXXXXXXXXXXX!999
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment]
@naui11 
Confirmed as bug, currently working on a fix

**Comment by abraunegg** [comment]
@naui11 
Please can you test the following PR for fixing your use case:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/586/head:pr586
git checkout pr586
make clean; ./configure; make;
```

**Comment by abraunegg** [comment]
@naui11 
Please can you re-validate #586 based on feedback from #587

**Comment by abraunegg** [comment]
Closing issue as PR merged & bug confirmed as being fixed
