### ISSUE TITLE
Get this error on Ubuntu 18: Makefile:34: recipe for target 'onedrive' failed

### ISSUE THREAD

**Issue by Keruberne** [abraunegg/onedrive#58]
Hi
I get this error when running the command make in onedrive folder:

```
(dmd-2.081.0)Test@Ubuntu18:~/onedrive$ make
echo v1.1.2-38-gc0d2874 >version
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
cc: No such file or directory
Error: linker exited with status 255
Makefile:34: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1
(dmd-2.081.0)johnny@Ubuntu18:~/onedrive$ 
```

I ran the depencies and activated dmd

```
sudo apt install libcurl4-openssl-dev
sudo apt install libsqlite3-dev
curl -fsS https://dlang.org/install.sh | bash -s dmd
```
What am i doing wrong?
it works directly with Linux Mint 19

**Comment by abraunegg** [comment]
It looks like perhaps there are some other dependencies not being installed which are required:

```
cc: No such file or directory
Error: linker exited with status 255
```

It looks like on your ubuntu install you have not installed `cc` or potentially other development dependencies.

Also - your version seems to be off:

```
v1.1.2-38-gc0d2874 >version
```

You should be v1.4.0 or v2.0.0 (depending on when you cloned) ... v2.0.0 is the latest

**Comment by Keruberne** [comment]
Hey first of all thanks

it was the gcc dependencies i was missing. installing them and it ran through like a charm and the version now also shows as 2.0.0.
So problem solved

thanks for a fast reply.
