### ISSUE TITLE
Docker: add images stretch and alpine in driveone/onedrive

### ISSUE THREAD

**Issue by mnagaku** [abraunegg/onedrive#583]
You can add build targets by adding settings like images.

![Screenshot from 2019-07-11 17-18-32](https://user-images.githubusercontent.com/3443925/61034933-2b4e8700-a401-11e9-96d4-87685403781c.png)

**Comment by norbusan** [comment]
@mnagaku Yes indeed, but do you think it is worth it? @abraunegg I can make these changes, though not sure whether it gives a lot of added value.

**Comment by abraunegg** [comment]
@norbusan 
I am unsure as well ... maybe it makes it easier for folk to download their 'desired' image? I dont know.

**Comment by mnagaku** [comment]
@norbusan 
@abraunegg 
If I want to use alpine (small binary is good), I can build it myself. But, I'm glad if I can use the auto-built images from this repository (always up-to-date maintenance).

**Comment by norbusan** [comment]
Ok, I have added the two tags. Maybe later we add buster? Thanks

**Comment by norbusan** [comment]
@abraunegg looking at the sizes of the images, it might be worth switching away from the current (whatever) to alpine or stretch/buster:

- latest 196M
- stretch 33M
- alpine 9M

!!!

**Comment by abraunegg** [comment]
@norbusan 
The default I think is based off CentOS - happy to have whatever changed around if that makes more sense.

**Comment by norbusan** [comment]
@abraunegg I think we could drop the current centos dockerfile completely, or rename it to Dockerfile-centos, and mv the Alpine version to the main. There are many reasons for that

- the centos version does not do staged builds, so all the ldm stuff needed for build is still in the image (could be fixed separately, I know)
- alpine is extremely small

I am not really eager to work on reducing the centos image by doing the staged builds, and see how small it will get.

WDYT? Should I send a PR?

**Comment by abraunegg** [comment]
@norbusan 
I am happy for a PR that does the following:
* renames the current dockerfile to dockerfile-centos (or as per current naming convention)
* moving alpine to main
