### ISSUE TITLE
Cannot upload file modification. Instead, files are deleted and recreated on OneDrive. 

### ISSUE THREAD

**Issue by theeggdev** [abraunegg/onedrive#585]
**Note:** I am running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. 

### Bug Report Details ###
**Describe the bug**
I am syncing mostly .xlsx, .csv and .txt to OneDrive. 

Previously, I encountered [this issue](https://github.com/OneDrive/onedrive-api-docs/issues/935) and multiple copies of the same .xlsx file were created, as the local version could not merge with the version on OneDrive. _(I am not sure if this piece of information is related to the issue I am submitting, but just mentioning it here in case.)_

Now the previous issue has been resolved with the update. However, now I encounter another issue - 
For any files regardless of their file type, when I modify the file, it will show in OneDrive: 

> Admin deleted file.xlsx from folder
> 4 hours ago
> 
> Admin created file.csv in folder
> 4 hours ago

I can confirm that I have not deleted and re-created the file on my end. I really just modified the files concerned. 

Deleting and re-creating the file is not ideal for my usage, as version history on the files will be lost and I rely greatly on the version history functionality OneDrive provides to me. 

**Application and Operating System Details:**
*   OS: **(Output of `uname -a`)** `Linux Admin 4.15.0-54-generic #/58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` ; **(provide your OS & version)**  `Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-54-generic x86_64)`
*   Are you using a headless system (no gui) or with a gui installed? headless system
*   OneDrive Account Type: Sharepoint group drive in Office 365 business
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`: DMD64 D Compiler v2.087.0
*   Application configuration: 
```
onedrive version                    = v2.3.7-3-gf39621c
Config path                         = /home/work/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/work/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'drive_id'            = (hidden)
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

*   Curl Version: 
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  open a file
2.  modify a file
3.  save the file with the modification
4.  let it sync
5.  see the file been deleted and re-created

**Complete Verbose Log Output**

Application Log Output:
```
will send the log output privately 
```

### Bug Report Checklist ###
*   [done] Detailed description
*   [done] Reproduction steps (if applicable)
*   [done] Verbose Log Output

**Comment by theeggdev** [comment]
I got one more issue. Although not related. 
I have been using 
```
systemctl enable onedrive@work.service
systemctl start onedrive@work.service 
```
to continuously sync my files. 

However, once I did `onedrive --synchronize --verbose --verbose > debug_output.log 2>&1` , the service keep deactivating and re-activating in every  OneDrive monitor interval (seconds): 45 
i.e. 
Have I done anything wrong? The sync seems broken after I generated the debug report. 

Many thanks on this!!

**Comment by abraunegg** [comment]
> I can confirm that I have not deleted and re-created the file on my end. I really just modified the files concerned.
> Deleting and re-creating the file is not ideal for my usage, as version history on the files will be lost and I rely greatly on the version history functionality OneDrive provides to me.

This is the only way to solve the problem of https://github.com/OneDrive/onedrive-api-docs/issues/935 

When you modify a file locally, and upload to a SharePoint site - Microsoft MODIFIES this file without telling you. OneDrive API does not tell you that the file has been modified & the client 'thinks' what it has uploaded is true and accurate - but it is not.

When you again upload the same file after only modifying it locally, without making ANY changes to the Microsoft modified file online, the client (without the fixes introduced a long time ago) will fail to upload / merge the data as the file metadata is different (it is non referenceable due to Microsoft modifying the file - the 'original' that we think should exist - does not)

The ONLY way to resolve this is to remove the Microsoft modified file (you didn't edit it, you didn't make changes - Microsoft did) and upload your copy. Additionally there is NO way to turn off Microsoft modifying your file if you are using a Sharepoint site ...

**Comment by theeggdev** [comment]
@abraunegg Thank you for your prompt reply! 

I have some comments on this: 

1. The issue OneDrive/onedrive-api-docs#935 did not affect .txt or .csv files previously. Is it possible to exempt at least these 2 types of files from _the deletion and re-creation workaround_? 

2. Sorry but I think I might have missed something, I could not get why there would be a 404 error. Last time when I encountered the "enriched" file issue, what I got is only tons of files with the suffix file-admin.xlsx, file-admin-2.xlsx, file-admin-3.xlsx, file-admin-4.xlsx, ... etc. because the files cannot be merged. I didn't encounter the issue raised here [OneDrive/onedrive-api-docs/issues/1068](https://github.com/OneDrive/onedrive-api-docs/issues/1068). 

3. I am using the Official OneDrive syncing client in my Windows computer. I noticed that: whenever my computer upload modification of a .xlsx file, there will be a download process immediately following the upload process. I think my Windows computer was downloading the "enriched" file at that time. 
So - is it actually possible to follow the same routine as how Microsoft is doing for Windows? 

i.e. "**upload modification --then--> download enriched file**" instead of "**remove existing file --then--> upload modification**"
 
I see that you already added the download part in `uploadNewFile` in `\src\sync.d` (as quoted below). I just wonder if the deletion part is still necessary. 
And how about adding the similar code snippet to `uploadFileDifferences` so that the enriched file is downloaded and local would be in sync? 
(I apologise for not being able to test this out myself. I have not got a test environment setup and I cannot risk my current Sharepoint Document Library.)
```
1982: private void uploadNewFile(string path)
[...]
2256: // Download the Microsoft 'modified' file so 'local' is now in sync
2257: log.vlog("Due to Microsoft Sharepoint 'enrichment' of files, downloading 'enriched' file to ensure local file is in-sync");
2258: log.vlog("See: https://github.com/OneDrive/onedrive-api-docs/issues/935 for further details");
2259: auto fileSize = response["size"].integer;
2260: onedrive.downloadById(response["parentReference"]["driveId"].str, response["id"].str, path, fileSize);

```
4. Apart from losing the version history, some users reflected to me that their Windows computer that sync the same Sharepoint Document Library suffer from the constantly incoming deleted files in their recycle bin. 
 
5. I will definitely storm the Sharepoint / O365 repo to voice out my discontent to their "enrichment feature". 

6. Anyhow I want to give you my appreciation to you on this workaround, though it brings me some inconvenience. I would say it is very effective. And I am actually happy that at least I can successfully sync my files to the cloud.

Thank you!

**Comment by abraunegg** [comment]
@theeggdev 
> The issue OneDrive/onedrive-api-docs#935 did not affect .txt or .csv files previously. Is it possible to exempt at least these 2 types of files from the deletion and re-creation workaround?

Patches welcome

>Sorry but I think I might have missed something, I could not get why there would be a 404 error. Last time when I encountered the "enriched" file issue, what I got is only tons of files with the suffix file-admin.xlsx, file-admin-2.xlsx, file-admin-3.xlsx, file-admin-4.xlsx, ... etc. because the files cannot be merged.

This could have been for a variety of issues:
1. The original 'skilion' client was horribly broken - if there was any 'checksum' issue, it would detect as conflict and rename files appending the hostname to the file name. 
2. The original 'skilion' client also had a bug where for Business accounts it would never ever generate the right hash (https://github.com/abraunegg/onedrive/issues/23) for files larger than 64Kb & this was a significant contributor to this 'hostname' problem.

> I am using the Official OneDrive syncing client in my Windows computer. I noticed that: whenever my computer upload modification of a .xlsx file, there will be a download process immediately following the upload process. I think my Windows computer was downloading the "enriched" file at that time.
So - is it actually possible to follow the same routine as how Microsoft is doing for Windows?

This is what the code used to do - however, the 'replace' flag for the upload session for the files would not replace the file and generate an error. The only way to reliably upload that 'new locally modified file' was to tell OneDrive to delete the bad file, and upload the modified file as a new file, then download the enriched file. This mimics the Windows client behaviour, although with the delete as well.

Patches welcome if you want to have a go a uploading the modified file without the delete

**Comment by abraunegg** [comment]
@theeggdev 
Can you help validate the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/590/head:pr590
git checkout pr50
make clean; ./configure; make;
```
This PR 'should' made the following enhancements:
* Update Sharepoint Document Library handling for .txt & .csv files
*  Replace modified Sharepoint Document Library files rather than delete and upload as new

**Comment by abraunegg** [comment]
Closing issue as PR #590 is merged into master
