### ISSUE TITLE
how to ignore some folders of OneDrive account to synchronize to the local.

### ISSUE THREAD

**Issue by yongqianxiao** [abraunegg/onedrive#595]
@abraunegg thanks for the former help. I can synchronize all the files and folders from OneDrive. But there are so many files and folders on OneDrive, can I choose some folders not to synchronize to the local? I tried to modify the config file ~/.config/onedrive/config, and the contents as follows:
```
skip_file = "~*|.~*|*.tmp"
sync_dir = "~/OneDrive"
skip_dir = "~/OneDrive/cart_pole|~/OneDrive/文档"
```
where `~/OneDrive` is the folder to synchronize all files of OneDrive. `cart_pole/` and `文档/` are 2 folders of my OneDrive account.
Could you tell me how to design the config file to ignore some folders and files of my OneDrive account to synchronize to the local? Thanks a lot.

**Comment by abraunegg** [comment]
@yongqianxiao 
`skip_dir` is relative to `sync_dir` so:
```
skip_dir = "~/OneDrive/cart_pole|~/OneDrive/文档"
```

should be:
```
skip_dir = "cart_pole|文档"
```

**Comment by yongqianxiao** [comment]
> @yongqianxiao
> `skip_dir` is relative to `sync_dir` so:
> 
> ```
> skip_dir = "~/OneDrive/cart_pole|~/OneDrive/文档"
> ```
> 
> should be:
> 
> ```
> skip_dir = "cart_pole|文档"
> ```

it works, thank you so much.
