### ISSUE TITLE
Start onedrive service on boot

### ISSUE THREAD

**Issue by mbaldassarri** [abraunegg/onedrive#597]
Thanks for this amazing project. 
Is there a way to start it on boot using `systemctl`?
The current Wiki talks about enabling and starting the service with init.d and systemctl and, if needed, how to start it as non-root user. 
In my case I chose systemctl with this command:

`systemctl --user start onedrive`

Unfortunatelly when I log out my ssh session or restart Ubuntu, onedrive is not up and it doesn't sync, it starts synching only when I log the user in again.

Thank you

**Comment by abraunegg** [comment]
@mbaldassarri 
Can you provide the exact commands you are issuing to 'enable' & 'start' the service before the reboot please?

What is the full service log output after reboot where the service has not started?

**Comment by mbaldassarri** [comment]
Following the guide I used these:

```
systemctl --user enable onedrive
systemctl --user start onedrive
```

When I logout my user session (SSH or boot) the client stops, I noticed it automatically restarts once I log the user again (via SSH).
This is the log after loggin in again after few minutes (from 9.34 to 9.42) :

```
lug 21 09:34:18 desktop systemd[1018] Got termination signal, shutting down db connection
lug 21 09:34:19 desktop systemd[1018]: Stopping OneDrive Free Client...
lug 21 09:34:19 desktop systemd[1018]: Stopped OneDrive Free Client.
lug 21 09:42:41 desktop systemd[1018]: Started OneDrive Free Client.
lug 21 09:42:42 desktop onedrive[1646]: Initializing the Synchronization Engine ...
lug 21 09:42:46 desktop onedrive[1646]: Continuing the upload session ...
```

I just would like the onedrive service run even if I am not logged in, but just thanks to the PC to be turned on, as it happens for the other services.
The only thing I noticed is this --user which I don't like, and the onedrive.service path is in 
`/usr/lib/systemd/user/onedrive.service`
 
and Not in:

`/etc/systemd/system/` where the other systemd services are.


Thank you

**Comment by norbusan** [comment]
@mbaldassarri You can use
```
sudo systemctl enable onedrive@USER
```
to start onedrive for user `USER` without the need for logging in. The only thing you will use are notifications since the process is started independent from the dbus daemon of the user.

Closing this issue.

**Comment by mbaldassarri** [comment]
Thank you, how do I check the status log after enabling and starting this way?

**Comment by norbusan** [comment]
These information are all in the USAGE document.

Checking the status is done as usual with systems by: journalctl -u onedrive@USER

**Comment by abraunegg** [comment]
> The only thing I noticed is this --user which I don't like, and the onedrive.service path is in
> `/usr/lib/systemd/user/onedrive.service`
> 
> and Not in:
> 
> `/etc/systemd/system/` where the other systemd services are.

As per https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-root-user you were using the instructions to run the client as the 'root' user. This is the correct location for this file when running the client as the 'root' user.

As per above, it appears you needed to use 'non-root' user configuration for your setup.
