### ISSUE TITLE
Error when uploading files

### ISSUE THREAD

**Issue by mbaldassarri** [abraunegg/onedrive#598]
### Bug Report Details ###
**Describe the bug**

When uploading files this error occurs randomly:

```
ERROR: OneDrive response missing required 'id' element
ERROR: 
{
   "error":{
      "code":"resourceModified",
      "innerError":{
         "date":"2019-07-21T14:32:59",
         "request-id":"my-request-id"
      },
      "message":"ETag does not match current item's value"
   }
}
```

The process doesn't crash but keeps uploading the next file.

**Application and Operating System Details:**
*   OS: `Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
*   Process is running using `sudo systemctl start onedrive@USER`
*   OneDrive Account Type:Normal
*   DMD or LDC compiler version : DMD64 D Compiler v2.086.1
*   Application configuration:
```
onedrive version                    = v2.3.7-20-g21e5047
Config path                         = ~/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /media/storage/Files
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|.~*|*.tmp|.DS_Store
Config option 'skip_dotfiles'       = true
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
Documents
```
*   Curl Version: curl 7.58.0

Thank you

**Comment by abraunegg** [comment]
@mbaldassarri 
Please can you provide the following:
* OneDrive Account Type - this will be Personal, Business or documentLibrary (Normal as an account type is invalid)
* Verbose debug log as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

The above is needed so that the correct area of code can be looked at and trace back what is causing this.

As your running as a service file, you may need to update the service files with the correct verbosity to provide the details required.

**Comment by abraunegg** [comment]
@mbaldassarri 
Any update as to providing debug logs for this issue?

**Comment by mbaldassarri** [comment]
The type is "Personal".

Sorry can't provide the log you requested at the moment, I restarted the deamon with systemctl and now I get another fatal error:

```
lug 23 09:59:28 desktop onedrive[2979]: ERROR: A local file has the same name as another local file.
lug 23 09:59:28 desktop onedrive[2979]: ERROR: To resolve, rename this local file: /media/storage/...

```
by hitting the systemctl status onedrive@USER again I get:
```
lug 23 10:00:11 desktop onedrive[2979]: <div id="header"><h1>Server Error</h1></div>
lug 23 10:00:11 desktop onedrive[2979]: <div id="content">
lug 23 10:00:11 desktop onedrive[2979]:  <div class="content-container"><fieldset>
lug 23 10:00:11 desktop onedrive[2979]:   <h2>404 - File or directory not found.</h2>
lug 23 10:00:11 desktop onedrive[2979]:   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
lug 23 10:00:11 desktop onedrive[2979]:  </fieldset></div>
lug 23 10:00:11 desktop onedrive[2979]: </div>
lug 23 10:00:11 desktop onedrive[2979]: </body>
lug 23 10:00:11 desktop onedrive[2979]: </html>
lug 23 10:00:12 desktop onedrive[2979]: Processing 46 changes
```

**Comment by abraunegg** [comment]
@mbaldassarri 
Suggest for the moment that you do not use the service files until you are 100% confident that it is working the way it should be. Please use a manual service start until everything is working right:

```
onedrive --monitor --verbose
```

> ERROR: A local file has the same name as another local file.

This is not an error. You have files that, under Linux are named 'differently' however for OneDrive, they are the same name. Refer to [this](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#file-naming) for more details.

**Comment by abraunegg** [comment]
@mbaldassarri 
> Sorry can't provide the log you requested at the moment, 

When you received this error:
```
ERROR: OneDrive response missing required 'id' element
```

Do you happen to know if this was when uploading a new file or a modified file?

**Comment by mbaldassarri** [comment]
`ERROR: OneDrive response missing required 'id' element`

it happened when uploading a new file. Imagine the Onedrive completely empty and you start uploading your files from your local machine; that's the case.

**Comment by abraunegg** [comment]
Thanks .. will see if I can stress test an upload process with random files & replicate

**Comment by mbaldassarri** [comment]
I was uploading a new file

**Comment by abraunegg** [comment]
@mbaldassarri 
Able to replicate this after generating 10K random PNG files, but it only occurs 1 in ~2000 image uploads.

**Comment by mbaldassarri** [comment]
I manually deleted all the files not well formatted with Microsoft rules, this is what I got after running OneDrive without systemctl:


``
marco@marco-desktop:/home$ onedrive --monitor --confdir=/home/marco/.config/onedrive
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 45
Retry sync count: 1: Unexpected character '<'. (Line 1:1)
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

Retry sync count: 2: Unexpected character '<'. (Line 1:1)
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

Giving up on sync after three attempts: Unexpected character '<'. (Line 1:1)
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

std.json.JSONException@std/json.d(1537): Unexpected character '<'. (Line 1:1)
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

----------------
/home/marco/dlang/dmd-2.087.0/linux/bin64/../../src/phobos/std/json.d:807 pure @safe void std.json.parseJSON!(char[]).parseJSON(char[], int, std.json.JSONOptions).error(immutable(char)[]) [0x55d69fdba2c8]
/home/marco/dlang/dmd-2.087.0/linux/bin64/../../src/phobos/std/json.d:1207 pure @safe void std.json.parseJSON!(char[]).parseJSON(char[], int, std.json.JSONOptions).parseValue(ref std.json.JSONValue) [0x55d69fdbb0c6]
/home/marco/dlang/dmd-2.087.0/linux/bin64/../../src/phobos/std/json.d:1213 pure @safe std.json.JSONValue std.json.parseJSON!(char[]).parseJSON(char[], int, std.json.JSONOptions) [0x55d69fdba228]
src/onedrive.d:628 std.json.JSONValue onedrive.OneDriveApi.perform() [0x55d69fdb98b9]
src/onedrive.d:457 std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x55d69fdb8e2b]
src/onedrive.d:300 std.json.JSONValue onedrive.OneDriveApi.getPathDetails(const(immutable(char)[])) [0x55d69fdb8053]
src/sync.d:1959 void sync.SyncEngine.uploadCreateDir(const(immutable(char)[])) [0x55d69fdcc178]
src/sync.d:1864 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcba38]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55d69fdcbafc]
src/sync.d:1362 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x55d69fdc9b8d]
src/main.d:623 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x55d69fdb54e9]
src/main.d:490 _Dmain [0x55d69fdb4c85]
marco@marco-desktop:/home$
``

Still getting this File or directory not found error even after rebooting the system or stopping the service. Don't know how to get it up and running again. Any suggestion?


About this error:

OneDrive response missing required 'id' element

It didn't happen to me again, sounds to be very rare indeed, thanks for investigating.

**Comment by abraunegg** [comment]
@mbaldassarri 
OK .. this is a different issue to debug / fix. 

The problem will be that some directory has a very weird name - one that OneDrive cannot handle, but also the client should handle and not crash.

Can you please run the following command, and email the log output please to support@mynas.com.au
```
onedrive --monitor --confdir=/home/marco/.config/onedrive --synchronize --verbose --verbose
```
This should give enough debug details as to what directory it is failing on, what it is named, the bad character etc.

**Comment by abraunegg** [comment]
@mbaldassarri 
Please can you get me that log file ASAP so I can work on fixing this remaining issue

**Comment by abraunegg** [comment]
Marking as fixed as found solution to the final issue, however user has advised they are no longer interested in fix.
