### ISSUE TITLE
When moving files/folders the client deletes the source and uploads the destination

### ISSUE THREAD

**Issue by CaptainJawZ** [abraunegg/onedrive#599]
So it seems that when I move files around regardless of how small or big they are they sometimes will be deleted from the source and instead re-uploaded once they are on their destination. 
Could this be an error on my file manager? because this didn't happened before. 

I did notice because I religiously check my recycle bin online in case it deletes a random file (so far it hasn't happened). 

It seems to happen wether I move a dozen files manually (drag and drop using Dolphin). 
Or also happens when I move a directory, I just moved a heavy directory, something like 
Original > Directory1
Original > New Directory > Directory1 

I did thought it could happen because I had moved the directory into a directory I had just created, but it does seem to happen to when I just move files across already existing directories. 

It's not a breaking bug as it doesnt "delete" the files locally, just deletes them on the cloud but then re-uploads them. 

Version of client: onedrive v2.3.7-16-g946c9bd

**Comment by CaptainJawZ** [comment]
Here is an example of how the log after I move a couple files: 
`Jul 21 16:52:43 Workstation onedrive[892]: Deleting item from OneDrive: Desktop/Screenshot_20190720_182322.png
Jul 21 16:52:54 Workstation onedrive[892]: Moving Desktop/D_9yTt_UcAAA5u0.jpeg to Pictures/Saved Pictures/To Organize/D_9yTt_UcAAA5u0.jpeg
Jul 21 16:52:54 Workstation onedrive[892]: Deleting item from OneDrive: Pictures/Saved Pictures/To Organize/D_9yTt_UcAAA5u0.jpeg
Jul 21 16:52:55 Workstation onedrive[892]: Moving Desktop/D_Yd7HkUYAAlyvI.jpeg to Pictures/Saved Pictures/To Organize/D_Yd7HkUYAAlyvI.jpeg
Jul 21 16:52:55 Workstation onedrive[892]: Deleting item from OneDrive: Pictures/Saved Pictures/To Organize/D_Yd7HkUYAAlyvI.jpeg
Jul 21 16:52:56 Workstation onedrive[892]: Moving Desktop/D_zhR5mUwAAAPj5.jpeg to Pictures/Saved Pictures/To Organize/D_zhR5mUwAAAPj5.jpeg
Jul 21 16:52:56 Workstation onedrive[892]: Deleting item from OneDrive: Pictures/Saved Pictures/To Organize/D_zhR5mUwAAAPj5.jpeg
`

**Comment by abraunegg** [comment]
@CaptainJawZ 
What was the actual 'actions' you took when this was taking place?
* `mv X Y`
* Moved files via 'cut' & 'paste' in OS GUI

**Comment by abraunegg** [comment]
@CaptainJawZ 
> Could this be an error on my file manager? because this didn't happened before.

When you say this - do you have any data to back this up?

**Comment by CaptainJawZ** [comment]
> @CaptainJawZ
> What was the actual 'actions' you took when this was taking place?
> 
> * `mv X Y`
> * Moved files via 'cut' & 'paste' in OS GUI

Moved files via cut and pasty in OS GUI, I'm using Manjaro/KDE/Dolphin 



> @CaptainJawZ
> 
> > Could this be an error on my file manager? because this didn't happened before.
> 
> When you say this - do you have any data to back this up?

Not really, sorry. Just my experience using the software, I've been using the client for about a month and I first noticed this behaviour about a week ago. For the most part everything has been seamless so I didn't paid much mind until now that I noticed that it's something that happens quite often.

**Comment by abraunegg** [comment]
@CaptainJawZ 
Nothing in the code has changed in terms of how 'moved' files are handled ... 

Also - your version your running - is probably still a PR version (v2.3.7-16-g946c9bd) - suggest that you run the latest 'master' and then retest, and if still occuring, then backtrack through the commits finding the one which breaks this for you.

**Comment by CaptainJawZ** [comment]
I'll upgrade the version and wait for my files to sync (Still uploading) then I'll do a detailed test and let you know my results, I'm starting to wonder if there really is something wrong with my account as I keep having this issues that are hard to replicate. Last time it seemed as if re-login also helped, so I'll give that a shot too.

**Comment by CaptainJawZ** [comment]
Sorry it took me a while to get back to you, restoring my backup took a couple hours. 
So I've been moving files and folders around for the past hour. Since I upgraded to the lastest master it seems like the problem significantly reduced in ocurrences but it still happens. 

I've been keeping an eye on journalctl as wel2 files randomly deleted l as the onedrive website, as I move files. 
At first I got some files randomly deleted, here is an example log of the occurance: 

`Jul 22 01:07:58 Workstation onedrive[9501]: Moving Desktop/EAAPix9WwAEYFYU.jpg to Pictures/Saved Pictures/To Organize/EAAPix9WwAEYFYU.jpg
Jul 22 01:07:58 Workstation onedrive[9501]: Moving Desktop/EAAtVvkUcAEBDVY.jpeg to Pictures/Saved Pictures/To Organize/EAAtVvkUcAEBDVY.jpeg
Jul 22 01:07:59 Workstation onedrive[9501]: Moving Desktop/EACZxFYWkAEOAtb.jpg to Pictures/Saved Pictures/To Organize/EACZxFYWkAEOAtb.jpg
Jul 22 01:07:59 Workstation onedrive[9501]: Moving Desktop/Soccerdasdsa3432.jpg to Pictures/Saved Pictures/To Organize/Soccerdasdsa3432.jpg
Jul 22 01:08:10 Workstation onedrive[9501]: Moving Desktop/01_.jpg to Pictures/Saved Pictures/To Organize/01_.jpg
Jul 22 01:08:10 Workstation onedrive[9501]: Deleting item from OneDrive: Pictures/Saved Pictures/To Organize/01_.jpg
`

These were moved by drag&dropping as I always do. However as I mentioned a random delete isn't a huge deal. 

However I think I've nailed it down to find out when it exactly happens. Anytime the client goes on hold to process XX changes, if I move a folder during that timeframe it wont detect the move and start uploading the files. Here is an example: 

``Jul 22 01:52:21 Workstation onedrive[9501]: Processing 18 changes
Jul 22 01:53:42 Workstation onedrive[9501]: Uploading new file ./Pictures/Saved Pictures/Artists/Raccon/1.jpg ... done.
Jul 22 01:53:44 Workstation onedrive[9501]: Uploading new file ./Pictures/Saved Pictures/Artists/Raccon/CtTMoGwUAAAZKFt.jpg ... done.

Lastly I managed to make it occur again under the same circumstances 
`Jul 22 02:14:38 Workstation onedrive[9501]: Processing 49 changes
Jul 22 02:15:33 Workstation onedrive[9501]: Uploading new file ./Desktop/Beast/1084390571299356672_1.jpg ... done.
Jul 22 02:15:35 Workstation onedrive[9501]: Uploading new file ./Desktop/Beast/tumblr176918017803_03.jpg ... done.
`
And it went on to upload all the files from the folder I moved. 

It seems like a very small timeframe to get this bug happening but if you're doing a normal session of organizing photos, moving folders around and the like seems like the chances of this happening drastically increase as this happens only while it's processing changes. 

Also sorry I keep coming with bugs, I really wish I could be of assistance with fixing them and contributing to the code but I still have a lot to learn.

**Comment by abraunegg** [comment]
@CaptainJawZ 
I think this is a quirk of how the client operates & not a bug or issue.

When the client is 'processing changes', it is checking / validating what is in the 'cache database' as being uploaded and in sync valid with what is on the local disk. As you are making changes when that check is occuring - of course the application will think that the file / folder it thinks is in location X is now not there (you manually moved it) - thus deleted it - as there is no way to post your manual move to update the database.

What I suggest is you have a read on how to configure the [monitor interval value](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#monitor_interval) - set this to something much longer that the default of 45 seconds so that the DB validation occurs much less frequent.

This will reduce the impact of your 'moving files around' and being caught with the scenario you are seeing.

**Comment by CaptainJawZ** [comment]
I'll give that a shot thank you so much!
