### ISSUE TITLE
How to upload local files to remote and do not delete remote files even if the local files already delete?

### ISSUE THREAD

**Issue by 858665536** [abraunegg/onedrive#605]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when ...

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 858665536** [comment]
I want upload my local files to onedirve and then delete local files,but always keep all files in onedrive.
How should i do?

**Comment by abraunegg** [comment]
It would be worth reviewing this: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#all-available-commands

Specifically investigate:
* local first
* no remote delete
