### ISSUE TITLE
Only a certain number of files at a time are downloaded when the application is invoked with `--synchronize --verbose`

### ISSUE THREAD

**Issue by scottdotjs** [abraunegg/onedrive#606]
The following bug report applies to the version currently available to install in Ubuntu through apt. See bottom of report relating to version built from master.

### Bug Report Details ###
Only a certain number files at a time are downloaded when the application is invoked with `--synchronize --verbose` - example verbose logs of 3 runs attached, in which 121 files were downloaded each time However in the attached debug log (`--synchronize --verbose --verbose`) 182 files were downloaded. Additionally, the last item in each of the provided log files does not end with "done" so it appears that only 120 files were downloaded in each case.

**Application and Operating System Details:**
*   OS: `Linux Sprawl 5.0.0-21-generic #22-Ubuntu SMP Tue Jul 2 13:27:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 19.04)`
*   Running from command line
*   OneDrive account type: personal
*   DMD or LDC compiler version: DMD64 D Compiler v2.087.0, but not installed at time of issue
*   Curl version: 7.64.0, but not installed at time of issue
*   Application configuration:
```
onedrive version                    = v2.2.5-1build1
Config path                         = /home/scott/.config/onedrive
Config file found in config path    = true
Config option 'sync_dir'            = /home/scott/OneDrive
Config option 'skip_file'           = ~*|Backups|Music|Photos
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false
```

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Run `onedrive --synchronize --verbose`

**Log files**
* [verbose_1.log](https://github.com/abraunegg/onedrive/files/3447429/verbose_1.log)
* [verbose_2.log](https://github.com/abraunegg/onedrive/files/3447430/verbose_2.log)
* [verbose_3.log](https://github.com/abraunegg/onedrive/files/3447431/verbose_3.log)
* [debug_output.log](https://github.com/abraunegg/onedrive/files/3447428/debug_output.log)

**Built version**
I followed the build instructions but the application crashes.

```scott@Sprawl:~$ /usr/local/bin/onedrive --confdir .config/onedrive --synchronize --verbose
Using Config Dir: .config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/scott/OneDrive
Initializing the Synchronization Engine ...
std.file.FileException@std/file.d(826): .config/onedrive/refresh_token: No such file or directory
----------------
/home/scott/dlang/dmd-2.087.0/linux/bin64/../../src/phobos/std/file.d:272 @trusted bool std.file.cenforce!(bool).cenforce(bool, scope const(char)[], scope const(char)*, immutable(char)[], ulong) [0x55ca8bcde3b4]
??:? @trusted void std.file.writeImpl(scope const(char)[], scope const(char)*, scope const(void)[], bool) [0x55ca8bd4d769]
/home/scott/dlang/dmd-2.087.0/linux/bin64/../../src/phobos/std/file.d:734 @safe void std.file.write!(immutable(char)[]).write(immutable(char)[], const(void[])) [0x55ca8bcea68d]
src/onedrive.d:423 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x55ca8bd1688f]
src/onedrive.d:412 void onedrive.OneDriveApi.newToken() [0x55ca8bd1672b]
src/onedrive.d:437 void onedrive.OneDriveApi.checkAccessTokenExpired() [0x55ca8bd16929]
src/onedrive.d:207 std.json.JSONValue onedrive.OneDriveApi.getDefaultDrive() [0x55ca8bd15270]
src/sync.d:264 void sync.SyncEngine.init() [0x55ca8bd22a0f]
src/main.d:536 bool main.initSyncEngine(sync.SyncEngine) [0x55ca8bd12e44]
src/main.d:313 _Dmain [0x55ca8bd11d27]```

**Comment by scottdotjs** [comment]
Update... the 120 thing may be a red herring. I've just run it twice again and had downloads of 171 and 535 files. Not sure if this is the same as issue #563.

**Comment by abraunegg** [comment]
@scottdotjs 
Due to you using Ubuntu and the Ubuntu packages, your version is very very very old.

Please rebuild from 'master' and don't use the Ubuntu package please.

**Comment by abraunegg** [comment]
@scottdotjs 
> See bottom of report relating to version built from master.

Whilst you indicate you have built from 'master' your verbose debug indicates your still running the Ubuntu version of code. Uninstall the Ubuntu package, build clean from 'master'. Test from the build directory first before installing.

**Comment by abraunegg** [comment]
@scottdotjs 
Looking at the debug log as well, it seems you upgraded to Curl 7.64.0. This means your using HTTP/2 operations by default - which - breaks the client - if your not using v2.3.x .... which because your still using the Ubuntu package, you have v2.2.5 which contains a vast array of bugs and issues.

**Comment by abraunegg** [comment]
@scottdotjs 
Any update from you in terms of updating your application binary?

**Comment by abraunegg** [comment]
@scottdotjs
Any update from you in terms of updating your application binary?

**Comment by abraunegg** [comment]
@scottdotjs 
Closing issue due to the following reasons:
* lack of response
* debug logs are all from v2.2.5
* application crash extract traced back to v2.2.5
