### ISSUE TITLE
Segmentation fault (core dumped) on initial run

### ISSUE THREAD

**Issue by romelanthonysb** [abraunegg/onedrive#61]
I was able to install the dependencies and run the make and make install commands for this, but when I tried running 'onedrive' for the first time, the error was 'Segmentation fault (core dumped)'. What should I check first? Thanks in advance.

**Comment by abraunegg** [comment]
What is your OS and version - `uname -a`

**Comment by evgeniy-pupkov** [comment]
Hello!
I'm experiencing the same error. 
I build the project in docker container in openshift. 
Docker is docker-dmd, based on Ubuntu 16.04 with dmd development environment. 
Build goes fine, but any tries to start onedrive client fail.

**Comment by abraunegg** [comment]
@romelanthonysb, @evgeniy-pupkov 

Can you please provide some details here - there is no verbose log information, no OS & architecture information.

**Comment by romelanthonysb** [comment]
Ah, maybe that might be it. I was trying to run this in 32-bit--I am on an ancient netbook (MSI Wind U123 from 2009).

OS: Lubuntu 18.04
Uname: Linux Zephyr3 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 17:59:24 UTC 2018 i686 i686 i686 GNU/Linux

Thanks for looking into it.
