### ISSUE TITLE
Mirror- instead of syncing: asymmetric mode?

### ISSUE THREAD

**Issue by nwo9** [abraunegg/onedrive#610]
It would be great if asymmetric modes would be allowed. 

Reason: I would like to use the onedrive storage mainly for backups. Thus I would prefer to limit syncing to the upload side, potentially also to deleting files in the cloud storage, but not to downloading or (beware) deleting files on my local storage. I imagine something like:

`onedrive upsync write  `
--> loads files in the cloud, but not down, potentially overwriting old files in the cloud but not deleting any.

`onedrive upsync clean`
--> deletes files in the cloud  which are not present locally anymore.

Obviously the two options could be joined:
`onedrive upsync clean write`
--> Completely mirroring the local folder in the cloud.

And equivalently an option "downsync" or something similar with opposite sign.
Such separate commands could then be scheduled to run at specific times, potentially with previous confirmation request in case of deletion/overwriting. That would be excellent!

Alternatives:
I am currently using an awkward work around by loading files up, than shifting them manually through the webinterface into a folder called "NoSync" which I exclude from syncing in the onedrive .config file, thus keeping a "backup" which is not constantly synced.

I am sorry that I am completely incapable of doing such modifications myself. Thanks a lot though for all your work!

**Comment by abraunegg** [comment]
@nwo9 
> I am currently using an awkward work around by loading files up, than shifting them manually through the webinterface into a folder called "NoSync" which I exclude from syncing in the onedrive .config file, thus keeping a "backup" which is not constantly synced.

It would be worth reviewing this: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#all-available-commands

Specifically investigate:

* local first
* upload only
* no remote delete

This would avoid your awkward work around.

Patches welcome for changing how the client operates as well.

**Comment by nwo9** [comment]
Excellent !
Thank you very much and please excuse me for not having seen this before. I will try out, but suppose this answers pretty much all of my request. 
Thanks again and sorry for the hassle.
