### ISSUE TITLE
add way to reveal hyperlink to file in onedrive online

### ISSUE THREAD

**Issue by meonkeys** [abraunegg/onedrive#611]
What if we added a way to reveal the link so a file on disk could be opened in a web browser? Is this possible? Something like `onedrive --get-link /path/to/local/file`, which would output `https://example.com/path/to/file/in/onedrive`, which could then be sent to `xdg-open` or similar to open the link in a web browser.

**Comment by abraunegg** [comment]
@meonkeys 
Interesting idea & quite doable as well

Patches welcome

**Comment by abraunegg** [comment]
@meonkeys 
Please can you help test the following PR to implement this feature:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/612/head:pr612
git checkout pr612
make clean; ./configure; make;
```

**Example:**
```
(dmd-2.085.0)[alex@centos7full onedrive-issue-611]$ ./onedrive --confdir '~/.config/onedrive-personal/' --get-file-link /home/alex/OneDrivePersonal/file.txt 
Initializing the Synchronization Engine ...
File URL: https://1drv.ms/t/s!AMpuBaXoO9VmhNIg
(dmd-2.085.0)[alex@centos7full onedrive-issue-611]$ ./onedrive --confdir '~/.config/onedrive-personal/' --get-file-link /home/alex/OneDrivePersonal/file2.txt 
Initializing the Synchronization Engine ...
File has not been synced with OneDrive: /home/alex/OneDrivePersonal/file2.txt
(dmd-2.085.0)[alex@centos7full onedrive-issue-611]$ 
```

**Comment by meonkeys** [comment]
Yes, works for me! Nice!

    $ onedrive --get-file-link /redacted/Document.docx 
    Initializing the Synchronization Engine ...
    File URL: https://example.com/redacted?sourcedoc=...

**Comment by abraunegg** [comment]
Suggestions?
Improvements?
Good to go as is?

**Comment by meonkeys** [comment]
The most useful output would be only the URL (or an error if one occurs). For example:

    $ onedrive --get-file-link /redacted/Document.docx 
    https://example.com/redacted?sourcedoc=...

This could easily be fed to `xdg-open` unmodified.

I see that `Initializing the Synchronization Engine ...` goes to stderr, so that's fine since it would be ignored in stdout pipes/redirects. So maybe just remove `File URL: `.

**Comment by abraunegg** [comment]
@meonkeys 
Can you rebuild your client with the updated PR and advise?

**Comment by meonkeys** [comment]
Looks good. I recommend silencing `Initializing the Synchronization Engine ...` or sending it to standard error so `--get-file-link` can be conveniently used in combination with other commands, as in

    $ xdg-open $(onedrive --get-file-link /redacted/Document.docx)

**Comment by abraunegg** [comment]
@meonkeys 
Updated the PR to reduce the logging output - can you revalidate the PR?

**Comment by meonkeys** [comment]
OK, testing d4eea2c0174b80d2df6ee97b6b777e061feccd80 . I follow the logic and it looks like it should work. In general I'm a fan of composeable command-line programs, so I'd say no output to the console should be the rule rather than the exception. Especially since you send notifications to the desktop and also log to a file on disk.

**Comment by meonkeys** [comment]
Nope, that didn't work. Still spits out `Initializing the Synchronization Engine ...` (along with the file URL, as expected).

**Comment by meonkeys** [comment]
I also tested a nonexistant file, and here's what happened:

    $ onedrive --get-file-link /redacted/NonexistantDocument.doc 2>/dev/null
    Initializing the Synchronization Engine ...
    File not found on local system: /redacted/NonexistantDocument.doc
    $ echo $?
    0

I'd say:

1. the exit code should be nonzero
1. `File not found on local system: /redacted/NonexistantDocument.doc` should probably also go to stderr

**Comment by abraunegg** [comment]
@meonkeys 
Can you check the latest PR version - should be: `onedrive v2.3.7-34-g288ce6d`

**Comment by abraunegg** [comment]
Closing issue as PR #612 merged into master

**Comment by meonkeys** [comment]
Looks good! :+1:
