### ISSUE TITLE
Upload incomplete

### ISSUE THREAD

**Issue by edumm84** [abraunegg/onedrive#616]
Hi!

First of all thanks for providing this fantastic problem. I could install it but when onedrive --synchronize, it starts uploading files (the cloud is empty and my local folder is full of folders and files), but it seems to have finished its work but only uploaded some files...

Thanks in advance.

**Comment by abraunegg** [comment]
@edumm84 
Please follow the directions here:
https://github.com/abraunegg/onedrive#reporting-issues

You have also not provided all the details as requested when filling in a bug report (https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md) as your details above are meaningless without this data

Please fix your first post and provide the requested data.

**Comment by abraunegg** [comment]
@edumm84 
Please can you respond by updating your first post please

**Comment by abraunegg** [comment]
@edumm84
Please can you respond by updating your first post please

**Comment by abraunegg** [comment]
@edumm84 
Closing this issue for the following reasons:
* lack response from you
* lack of required details when submitting an issue such as client version, compiler version, linux OS / distro, curl version and client configuration - all of which are required to assist you with your problem
