### ISSUE TITLE
Can't install onedrive: dlang Broken GPG installation

### ISSUE THREAD

**Issue by JueGoWinDo** [abraunegg/onedrive#628]
Hi!

I've been trying to install onedrive on Lubuntu - i386 / i686

After 
```
curl -fsS https://dlang.org/install.sh | bash -s dmd
```
Print:
```
gpg: Fatal: can't open '/home/ale/.gnupg/trustdb.gpg': Permission denied 
Broken GPG installation
```
And I can't continue with the onedrive installation.

Thanks!

**Comment by abraunegg** [comment]
@JueGoWinDo 
This is not a problem with 'onedrive' or this repo

What you somehow have done is screwed up the permissions of the .gnupg directory. Refer to: https://ubuntuforums.org/showthread.php?t=1236084

To fix, run as your 'ale' user:
```
sudo chown -R ale.ale ~/.gnupg
```

Closing issue as not an issue with this client.
