### ISSUE TITLE
Failed to compile on AWS EC2 instance (Ubuntu 16.04, t2.micro)

### ISSUE THREAD

**Issue by openedhardware** [abraunegg/onedrive#63]
![image](https://user-images.githubusercontent.com/16890683/42624144-424de348-85f7-11e8-847b-9851f2e8a409.png)

Any idea?

Of course, I installed all dependencies and activated dmd as you could see above.

**Comment by abraunegg** [comment]
The only thing I can think for a build failure of is memory on the EC2 instance. As per the readme:

**Build Requirements**
* Build environment must have at least 1GB of memory
* libcurl
* SQLite 3
* Digital Mars D Compiler (DMD)

What is the OS Architecture as well - i686 or x86_64 as you have not identified this.

**Comment by openedhardware** [comment]
Thanks for your quick reply, @abraunegg !

Here is my output:
![image](https://user-images.githubusercontent.com/16890683/42625357-209975d4-85fa-11e8-9f6a-059051a2fe43.png)


Let me try after installing gcc.

**Comment by openedhardware** [comment]
Whew, I had to add swap memory space to get it working...
Thanks for your help!

**Comment by openedhardware** [comment]
Yeah

**Comment by abraunegg** [comment]
How much swap did you add as well ? It would be good to capture this.

**Comment by openedhardware** [comment]
1GB like this:
![image](https://user-images.githubusercontent.com/16890683/42626203-466d7060-85fc-11e8-88ce-07191beb8cfa.png)

**Comment by abraunegg** [comment]
Thanks
