### ISSUE TITLE
Support for locally hosted Sharepoint / OneDrive for Business?

### ISSUE THREAD

**Issue by ttbrunner** [abraunegg/onedrive#633]
I'm sorry for asking what seems to be trivial, but I have read the docs up and down and didn't succeed in setting this up.

Does this app support SharePoint / OneDrive for Business when it's locally hosted? 

No matter what I do, the onedrive command always asks me to go to a Microsoft URL - I don't have a Microsoft account. I have an account at my company's local SharePoint server, and they provide what they call Sharepoint for Business, which probably has the old Groove File Sync under the hood.

As an example, the URL to my local share looks like https://sharepoint.mycompany.org/personal/username/Documents

Can I set up onedrive to work with this? I'm confused by the documentation and the many different things that appears to be "OneDrive".

**Comment by abraunegg** [comment]
I am afraid your out of luck for that sort of support. Locally hosted Sharepoint is totally different to Sharepoint / Office365 hosted sharepoint. Your locally hosted Sharepoint environment also will not have all the API endpoints etc that the client is looking for - so even if you modified the auth urls to point at your instance - it would fail. Additionally your local Sharepoint instance would not understand the client identifier or access tokens

If you were able to convince your organisation to migrate to an Office 365 / hosted Sharepoint environment - then it would work ... depending on yout organisation that may be possible .. maybe not

**Comment by ttbrunner** [comment]
I see, thanks for the quick answer. A pity! 

Still, thanks for the great work in this project. I will give it a go privately :)
