### ISSUE TITLE
Exception Code 141

### ISSUE THREAD

**Issue by TheFlyingBadger** [abraunegg/onedrive#636]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
When syncing my account (using volansmelesmeles/onedrive docker image) I'm (seeming randomly) getting error 141 out of the onedrive executable

**Application and Operating System Details:**
*   OS:  4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux - Debian Buster
*   Headless (docker)
*   OneDrive for Business
*   DMD (current)
*   Application configuration:
```
onedrive version                    = v2.3.9
Config path                         = /root/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = true
Config option 'sync_dir'            = /root/OneDrive
Config option 'skip_dir'            = $*
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = true
Config option 'skip_symlinks'       = true
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
*   Curl Version: Output of `curl --version`
```
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
Ermmmm. random!

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:/start.sh exited 141
```
[onedrive.zip](https://github.com/abraunegg/onedrive/files/3568058/onedrive.zip)

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment]
@TheFlyingBadger 

> When syncing my account (using volansmelesmeles/onedrive docker image) I'm (seeming randomly) getting error 141 out of the onedrive executable

Please use the correct docker image as per https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md 

Docker Hub: https://hub.docker.com/r/driveone/onedrive 

No other image is tested or validated

The error indicates some sort of shell exit code - sorry, cannot help more than that. Perhaps ping the publisher of that Docker image for support.

**Comment by TheFlyingBadger** [comment]
Cheers eggo. I hadn't spotted that you'd created a docker image. I've moved onto that one now - if I get any further weirdness i'll let you know!
