### ISSUE TITLE
Unable to login : AADSTS50011 error

### ISSUE THREAD

**Issue by lmorel3** [abraunegg/onedrive#641]
### Bug Report Details ###
**Describe the bug**
I tried to login into the application for the first time but I got the error from the login page "AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application".

**Application and Operating System Details:**
*   OS: Fedora 30
*   Are you using a headless system : no
*   OneDrive Account Type : Business
*   DMD or LDC compiler version : 2.088.0
*   Application configuration:
```
onedrive version                    = v2.3.9-2-ge8c3c23
Config path                         = /home/lmorel/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/lmorel/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
*   Curl Version: 7.65.3

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Do a fresh install
2. Launch `onedrive` and follow the URL

**Comment by abraunegg** [comment]
Please can you post a screen shot of the error.

**Comment by lmorel3** [comment]
It's now working. Thanks Microsoft.. :)
