### ISSUE TITLE
abnormal termination of systemd service when no internet connection

### ISSUE THREAD

**Issue by rugubara** [abraunegg/onedrive#642]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
The systemd service ends abnormally when there is no internet connection. Started to manifest with version 2.3.9. 
```
сен 05 21:51:55 PF16W6Y2 systemd[4530]: Started OneDrive Free Client.
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: Cannot connect to Microsoft OneDrive Service
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: Reason: Couldn't resolve host name on handle 557833AC1B60
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: Initializing the Synchronization Engine ...
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: There was a problem in accessing the Microsoft OneDrive service - Internet connectivity issue?
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: std.json.JSONException@std/json.d(274): JSONValue is not an object
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: ----------------
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: ??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x32fa3c57]
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: ??:? pure @safe bool std.exception.enforce!(std.json.JSONException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x32fa3bd1]
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: ??:? inout pure @property @trusted inout(std.json.JSONValue[immutable(char)[]]) std.json.JSONValue.objectNoRef() [0x7ae0011d]
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: ??:? const pure @safe const(std.json.JSONValue)* std.json.JSONValue.opBinaryRight!("in").opBinaryRight(immutable(char)[]) [0x32fc0537]
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: ??:? void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x32fbeccb]
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: ??:? void onedrive.OneDriveApi.newToken() [0x32fbec6b]
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: ??:? void onedrive.OneDriveApi.checkAccessTokenExpired() [0x32fbee69]
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: ??:? std.json.JSONValue onedrive.OneDriveApi.getDefaultDrive() [0x32fbd830]
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: ??:? void sync.SyncEngine.init() [0x32fcc363]
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: ??:? bool main.initSyncEngine(sync.SyncEngine) [0x32fbb484]
сен 05 21:51:55 PF16W6Y2 onedrive[6140]: ??:? _Dmain [0x32fba243]
сен 05 21:51:55 PF16W6Y2 systemd[4530]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
сен 05 21:51:55 PF16W6Y2 systemd[4530]: onedrive.service: Failed with result 'exit-code'.
сен 05 21:51:58 PF16W6Y2 systemd[4530]: onedrive.service: Service RestartSec=3s expired, scheduling restart.
сен 05 21:51:58 PF16W6Y2 systemd[4530]: onedrive.service: Scheduled restart job, restart counter is at 3.
сен 05 21:51:58 PF16W6Y2 systemd[4530]: Stopped OneDrive Free Client.
сен 05 21:51:58 PF16W6Y2 systemd[4530]: Started OneDrive Free Client.
```
Restarts follow in a rapid succession.

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
` Linux PF16W6Y2 5.2.11-gentoo #2 SMP PREEMPT Thu Sep 5 12:58:13 MSK 2019 x86_64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz GenuineIntel GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed? `Gnome 3.30 GUI`
*   OneDrive Account Type - `personal`
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`   `DMD64 D Compiler v2.082.1`
*   Application configuration: Output of `onedrive --display-config`
```
anton@PF16W6Y2 ~ $ onedrive --display-config
onedrive version                    = v2.3.9
Config path                         = /home/anton/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/anton/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~Exchange
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = true
Config option 'monitor_interval'    = 300
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
*   Curl Version: Output of `curl --version`    `curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1c zlib/1.2.11`

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment]
@rugubara 
Thanks for the bug report, will look into this shortly.

How are you reproducing this? disable network interface / firewall rule ?

**Comment by abraunegg** [comment]
@rugubara 
Please can you test the following PR to resolve this issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/643/head:pr643
git checkout pr643
make clean; make;
```

**Comment by abraunegg** [comment]
Closing issue as PR #643 merged into master

**Comment by rugubara** [comment]
Hello, @abraunegg 

I've patched and tested. Works fine now. Thanks!
