### ISSUE TITLE
Docker confdir and syncdir not honored with latest commit (PR 638, commit e8c3c23)

### ISSUE THREAD

**Issue by fmoledina** [abraunegg/onedrive#648]
### Bug Report Details ###
Using the latest Docker file (commit e8c3c23 capturing PR 638), the ARGS variable loses the `--confdir` and `--syncdir` arguments somehow with the incorporation of the `ONEDRIVE_VERBOSE` environment variable. Docker log output is below:

```
onedrive             | 2019-09-08T21:13:47.152872085Z ++ stat /onedrive/data -c %u
onedrive             | 2019-09-08T21:13:47.156543341Z + : 1000
onedrive             | 2019-09-08T21:13:47.157041584Z ++ stat /onedrive/data -c %g
onedrive             | 2019-09-08T21:13:47.158007125Z + : 1000
onedrive             | 2019-09-08T21:13:47.158381687Z ++ getent group 1000
onedrive             | 2019-09-08T21:13:47.159836901Z + odgroup=onedrive:x:1000:
onedrive             | 2019-09-08T21:13:47.159892710Z + odgroup=onedrive
onedrive             | 2019-09-08T21:13:47.160455748Z ++ getent passwd 1000
onedrive             | 2019-09-08T21:13:47.161640879Z + oduser=onedrive:x:1000:1000::/home/onedrive:/bin/bash
onedrive             | 2019-09-08T21:13:47.161956416Z + oduser=onedrive
onedrive             | 2019-09-08T21:13:47.161988304Z + usermod -g onedrive onedrive
onedrive             | 2019-09-08T21:13:47.166529764Z usermod: no changes
onedrive             | 2019-09-08T21:13:47.167060570Z + grep -qv root /dev/fd/63
onedrive             | 2019-09-08T21:13:47.167123267Z ++ groups onedrive
onedrive             | 2019-09-08T21:13:47.168956895Z + chown onedrive:onedrive /onedrive/ /onedrive/conf
onedrive             | 2019-09-08T21:13:47.170500751Z + ARGS=(--monitor --confdir /onedrive/conf --syncdir /onedrive/data)
onedrive             | 2019-09-08T21:13:47.170757890Z + '[' 1 == 0 ']'
onedrive             | 2019-09-08T21:13:47.170851355Z + echo '# We are being verbose'
onedrive             | 2019-09-08T21:13:47.170884121Z + echo '# set ONEDRIVE_VERBOSE environment to 0 (Zero) to be less chatty'
onedrive             | 2019-09-08T21:13:47.170910198Z + ARGS=(--verbose ${ARGS})
onedrive             | 2019-09-08T21:13:47.170944508Z # We are being verbose
onedrive             | 2019-09-08T21:13:47.170986235Z # set ONEDRIVE_VERBOSE environment to 0 (Zero) to be less chatty
onedrive             | 2019-09-08T21:13:47.170969592Z + '[' 0 -gt 0 ']'
onedrive             | 2019-09-08T21:13:47.171061759Z + exec gosu onedrive /usr/local/bin/onedrive --verbose --monitor
onedrive             | 2019-09-08T21:13:47.196847406Z Using Config Dir: /home/onedrive/.config/onedrive
onedrive             | 2019-09-08T21:13:47.197288923Z No config file found, using application defaults
onedrive             | 2019-09-08T21:13:47.198879981Z Initializing the OneDrive API ...
onedrive             | 2019-09-08T21:13:47.674330865Z Authorize this app visiting:
```

I expect that the entrypoint command should end up looking like

```
exec gosu onedrive /usr/local/bin/onedrive --verbose --monitor --confdir /onedrive/conf --syncdir /onedrive/data
```

I have made no changes to my configuration since before the update and am not explicitly setting the `ONEDRIVE_VERBOSE` environment variable.

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc): `Linux caprica 5.0.0-27-generic #28~18.04.1-Ubuntu SMP Thu Aug 22 03:00:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed? No GUI
*   OneDrive Account Type - Personal (i.e. Microsoft account) and Office 365
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`. Not installed, using Docker.
*   Application configuration: Output of `onedrive --display-config`. Not installed, using Docker.
*   Curl Version: Output of `curl --version`. 

```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au. Not applicable, using Docker.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Run Docker container as per instructions. Mount points are not used. Default directories within the Docker container are used.

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Not applicable, using Docker.

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

Not applicable, using Docker.

**Screenshots**

Console output is above.

**Additional context**

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Reproduction steps (if applicable)
*   [X] Verbose Log Output

**Comment by abraunegg** [comment]
@fmoledina 
Thanks - will roll back that Docker change and ask the user to review the patch

**Comment by abraunegg** [comment]
@fmoledina 
Please can you re-validate with latest master once Docker Hub rebuilds as this commit has been reverted.

**Comment by abraunegg** [comment]
@TheFlyingBadger
Please can you review your #638 patch in light of the information above.

**Comment by TheFlyingBadger** [comment]
Apologies chaps, changes re-submitted (this time correctly!) as #651

**Comment by abraunegg** [comment]
@TheFlyingBadger 
Thanks for looking at this

@fmoledina 
Please can you check https://github.com/abraunegg/onedrive/commit/230be5a23d35e96d8bea6db1c14a23c119784788 once this is built on Docker Hub

**Comment by fmoledina** [comment]
Thanks @TheFlyingBadger and @abraunegg for the prompt response. I've currently rolled back to Docker tag `latest-201908312256` so I can get through the workday. I'll test out the new build later on today. Thanks again!

**Comment by fmoledina** [comment]
@TheFlyingBadger and @abraunegg, looks like the latest commit solves the issue. Thanks again for the prompt fix.
