### ISSUE TITLE
Notification spam when there isn't connection at boot

### ISSUE THREAD

**Issue by jose-sanchezm** [abraunegg/onedrive#653]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
When running the onedrive client at boot as user (systemctl --user enable onedrive) and there's no internet connection at boot, onedrive spams notifications with the message "Starting the Synchronization Engine" continuously until the internet connection is available.

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
```
Linux dell-latitude-arch 5.2.13-arch1-1-ARCH #1 SMP PREEMPT Fri Sep 6 17:52:33 UTC 2019 x86_64 GNU/Linux
```
*   Are you using a headless system (no gui) or with a gui installed?
GNOME 3.32

*   OneDrive Account Type
Onedrive business account

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
DMD64 D Compiler v2.087.1

Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright

*   Application configuration: Output of `onedrive --display-config`
```
onedrive --display-config                            
onedrive version                    = v2.3.9
Config path                         = /home/jose/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/jose/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

*   Curl Version: Output of `curl --version`
```
curl --version                                     
curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.8.2 nghttp2/1.39.2
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Install the onedrive client and have it starting at boot with systemctl enable --user onedrive
2.  Boot the computer into GNOME 3.32 without an interenet connection
3.  Have a continuous stream of notifications from the onedrive client saying "Starting the Synchronization Engine"
4.  Connect to the internet
5. The notifications stop

Usability wise, it should stop sending notifications or just send an error notification and stop but having a notification pop up continuously until an internet connection comes up is extremely annoying.

**Comment by abraunegg** [comment]
@jose-sanchezm 
> "Starting the Synchronization Engine" continuously until the internet connection is available.
> onedrive version = v2.3.9

Some changes were made in https://github.com/abraunegg/onedrive/commit/0424caaaf8f39832ec57f0a0d14b0fe87c5a0b9a 

Given your not using the latest master, but a 'general release' version, does running / building from the latest master yield a slightly different / better result for you?

**Comment by abraunegg** [comment]
@jose-sanchezm 
Please can you also test / evaluate the following PR for your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/656/head:pr656
git checkout pr656
make clean; ./configure; make;
```

**Comment by jose-sanchezm** [comment]
I tested it and I don't get spam notifications anymore:

When my computer boots without internet connection onedrive is loaded but exits silently according to onedrive status --user onedrive and I don't get any notification.

When I connect to a network, the onedrive client goes back to life according to the same command. No notification shown too but that's fine.

**Comment by abraunegg** [comment]
@jose-sanchezm 
OK great ... so .. resolved with the PR then ?

**Comment by jose-sanchezm** [comment]
Yes. Solved

**Comment by abraunegg** [comment]
@jose-sanchezm 
great - will get that merged into master

**Comment by abraunegg** [comment]
Closing issue as PR #656 merged into master
