### ISSUE TITLE
logout downloading all the drive

### ISSUE THREAD

**Issue by x0rld** [abraunegg/onedrive#660]
**Note:** 
I tried to logout with `onedrive --logout` 

### Bug Report Details ###
**Describe the bug**
when i tried to logout i copy paste the uri then all my onedrive start to be download

**Application and Operating System Details:**
*   OS: Linux x0rld-UX410UAK 5.0.0-27-generic #28~18.04.1-Ubuntu SMP 2019 x86_64 x86_64 x86_64 GNU/Linux
*  gui
*   Application configuration: i have Unrecognized option --display-config
*   Curl Version: 7.58

**Comment by abraunegg** [comment]
@x0rld 
> Application configuration: i have Unrecognized option --display-config

This does not seem right.

What does:
```
onedrive --version 
```

indicate?

**Comment by x0rld** [comment]
it's 1.0.1

**Comment by abraunegg** [comment]
This is the skilion version.

However you installed it, uninstall it as it is badly broken. Do not use any version that is not at least v2.3.9 or above

**Comment by x0rld** [comment]
oh ok thanks
