### ISSUE TITLE
Running as root using systemd:  Failed to connect to bus: No such file or directory.

### ISSUE THREAD

**Issue by frohro** [abraunegg/onedrive#662]
In another issue you stated:

> Can you also ensure that you are performing the following:
> 
> `user@debian-x86-64:~$ systemctl --user enable onedrive`
> `user@debian-x86-64:~$ systemctl --user start onedrive`
> The service starts without issue as a regular (non root) user.
> 
> Note: Debian prevents systemctl --user enable onedrive from running as 'root' and returns the following error:
> 
> Failed to connect to bus: No such file or directory
> This is not a 'onedrive' client issue, rather than a Debian systemd issue if you encounter this problem

I have this issue on Ubuntu 18.04.  It works fine with an ordinary user, but not as root.  I tried doing:
```
export XDG_RUNTIME_DIR=/run/user/`id -u`
```
and it didn't seem to help.  (I can't figure out how this markup language makes a single back quote, but they surround the id -u above.)  I suspect it has to do with some safety thing root has going that an ordinary user doesn't.  I know this isn't an onedrive issue, but it is still keeping me from backing up some root owned folders that I need to back up.  Do you have any suggestions that might help me out?
Thanks,
Rob

**Comment by abraunegg** [comment]
@frohro 
Dont run as a service for root user?

Run as a cron job for root files ?

**Comment by abraunegg** [comment]
@frohro 
I have been looking into a workaround for this issue, and the following steps were successful:

1. Ensure that the client is 'authorised' and works 100% when as 'root' & using `onedrive --synchronize --verbose`
2. Enable the service with the following: `systemctl enable onedrive@root.service`
3. Edit `/etc/systemd/system/multi-user.target.wants/onedrive@root.service` and update the confdir parameter:
```
--confdir=/root/.config/onedrive
```
4. Issue a `systemctl daemon-reload`
5. Start the service with: `systemctl start onedrive@root.service`
6. Check the status with: `systemctl status onedrive@root.service`
```
root@alex-virtual-machine:~# uname -a
Linux alex-virtual-machine 5.0.0-27-generic #28~18.04.1-Ubuntu SMP Thu Aug 22 03:00:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@alex-virtual-machine:~# systemctl status onedrive@root.service
â— onedrive@root.service - OneDrive Free Client for root
   Loaded: loaded (/lib/systemd/system/onedrive@.service; indirect; vendor preset: enabled)
   Active: active (running) since Tue 2019-09-17 06:48:54 AEST; 8min ago
     Docs: https://github.com/abraunegg/onedrive
 Main PID: 1906 (onedrive)
    Tasks: 2 (limit: 2302)
   CGroup: /system.slice/system-onedrive.slice/onedrive@root.service
           â””â”€1906 /usr/local/bin/onedrive --monitor --confdir=/root/.config/onedrive

Sep 17 06:56:44 alex-virtual-machine onedrive[1906]: Deleting item from OneDrive: random_files/ILg9AFI0BLiE1TwT3fK4j0atyyKyZNd3/file0.data
Sep 17 06:56:44 alex-virtual-machine onedrive[1906]: Deleting item from OneDrive: random_files/ILg9AFI0BLiE1TwT3fK4j0atyyKyZNd3/file2.data
Sep 17 06:56:44 alex-virtual-machine onedrive[1906]: Deleting item from OneDrive: random_files/ILg9AFI0BLiE1TwT3fK4j0atyyKyZNd3/file8.data
Sep 17 06:56:44 alex-virtual-machine onedrive[1906]: Deleting item from OneDrive: random_files/ILg9AFI0BLiE1TwT3fK4j0atyyKyZNd3/file9.data
Sep 17 06:56:45 alex-virtual-machine onedrive[1906]: Deleting item from OneDrive: random_files/ILg9AFI0BLiE1TwT3fK4j0atyyKyZNd3/file3.data
Sep 17 06:56:45 alex-virtual-machine onedrive[1906]: Deleting item from OneDrive: random_files/ILg9AFI0BLiE1TwT3fK4j0atyyKyZNd3/file5.data
Sep 17 06:56:46 alex-virtual-machine onedrive[1906]: Deleting item from OneDrive: random_files/ILg9AFI0BLiE1TwT3fK4j0atyyKyZNd3/file1.data
Sep 17 06:56:46 alex-virtual-machine onedrive[1906]: Deleting item from OneDrive: random_files/ILg9AFI0BLiE1TwT3fK4j0atyyKyZNd3/file4.data
Sep 17 06:56:47 alex-virtual-machine onedrive[1906]: Deleting item from OneDrive: random_files/ILg9AFI0BLiE1TwT3fK4j0atyyKyZNd3
Sep 17 06:56:47 alex-virtual-machine onedrive[1906]: Deleting item from OneDrive: ./random_files
root@alex-virtual-machine:~# 
```

**Comment by abraunegg** [comment]
Added to wiki entry this work around: https://github.com/abraunegg/onedrive/wiki/systemd:-Failed-to-connect-to-bus:-No-such-file-or-directory

**Comment by abraunegg** [comment]
@frohro 
Were you able to test / try the above workaround?

**Comment by abraunegg** [comment]
Closing issue as answer & workaround provided

**Comment by frohro** [comment]
Thanks!  I verified this works just great!
