### ISSUE TITLE
perform onedrive --synchronize --resync with dockerized onedrive

### ISSUE THREAD

**Issue by xiaguoxin** [abraunegg/onedrive#669]
**Is your feature request related to a problem? Please describe.**
after update sync_list file, i don't know how to pass --resync to onedrive docker container.
`docker exec -ti onedrive bash` and do it mannually didn't work.

**Describe the solution you'd like**
maybe there's some way to control container just like undockerized onedrive.

By the way, after running onedrive several days, the container logs size becomes very big. now i just clean it mannually, and add a `--log-opt max-size=700m` running container( which I don't know if it works). Maybe there are some better solution?

Thank you.

**Comment by abraunegg** [comment]
@xiaguoxin 
> after update sync_list file, i don't know how to pass --resync to onedrive docker container

You will need to either:
* Enter the container and run onedrive manually
* Modify entrypoint.sh manually to include `--resync` :

```
# Default parameters
ARGS=(--monitor --confdir /onedrive/conf --syncdir /onedrive/data --resync)
```

**Comment by abraunegg** [comment]
@xiaguoxin 
> By the way, after running onedrive several days, the container logs size becomes very big. now i just clean it mannually, and add a `--log-opt max-size=700m` running container( which I don't know if it works). Maybe there are some better solution?

This will not work. You will need to configure log rotation for your Docker image / container.

**Comment by josefrvaldes** [comment]
I have the same question. What I did to try to selective sync:
- I went to my onedrive_conf folder shown when I run `docker volume inspect onedrive_conf`
- Then create a default config file [https://raw.githubusercontent.com/abraunegg/onedrive/master/config](url)
- And then, I put a sync_list file in the same directory (I'm not familiarized with docker at all, so probably this is just totally useless..)

But now I don't know how to perform a resync and I don't know if those were the right steps...

Could you please clarify it a little? Thank you very much!

**Comment by josefrvaldes** [comment]
> @xiaguoxin
> 
> > after update sync_list file, i don't know how to pass --resync to onedrive docker container
> 
> You will need to either:
> 
> * Enter the container and run onedrive manually
> * Modify entrypoint.sh manually to include `--resync` :
> 
> ```
> # Default parameters
> ARGS=(--monitor --confdir /onedrive/conf --syncdir /onedrive/data --resync)
> ```

Do I have to keep that --resync option forever? Or do I have to delete it after the full resync?

**Comment by abraunegg** [comment]
@josefrvaldes 
> Do I have to keep that --resync option forever? Or do I have to delete it after the full resync?

No - should just be for the first sync post config change.

> And just for other people if they try to do the same. When I tried to modify the entrypoint.sh and add the sync_list file I found that there were no text editor installed. To install one, I just had to run yum install nano.

This is not ideal. Will update `entrypoint.sh` so that resync can be added as a passed in parameter - this makes more sense.

**Comment by abraunegg** [comment]
@josefrvaldes
> I ran onedrive from the fist time and it tried to download EVERYTHING, including unwanted folders.

This sounds like https://github.com/abraunegg/onedrive/issues/658 - however this also depends on what version of the Docker container your running & what client version the Docker container is using. Can you provide some debug logs for this?

**Comment by xiaguoxin** [comment]
> @xiaguoxin
> 
> > after update sync_list file, i don't know how to pass --resync to onedrive docker container
> 
> You will need to either:
> 
> * Enter the container and run onedrive manually
> * Modify entrypoint.sh manually to include `--resync` :
> 
> ```
> # Default parameters
> ARGS=(--monitor --confdir /onedrive/conf --syncdir /onedrive/data --resync)
> ```

Thank you for your reply, and for this great project.
Last time I try to run command inside the container it did not work, and the container keeps kicking me out(just like run `exit`). But I now running a brand new container and it do not behave like the past one, so I think it might works this time.
Again, thank you very much.

**Comment by abraunegg** [comment]
@xiaguoxin, @josefrvaldes 

Please can you evaluate the following Docker Tag:
```
driveone/onedrive:test
```

This will allow:
* Setting of verbose output
* Setting of debug output
* Performing a resync

**Verbose Output:**
```bash
docker container run -e ONEDRIVE_VERBOSE=1 -v onedrive_conf:/onedrive/conf -v "${onedriveDir}:/onedrive/data" driveone/onedrive:test
```
**Debug Output:**
```bash
docker container run -e ONEDRIVE_DEBUG=1 -v onedrive_conf:/onedrive/conf -v "${onedriveDir}:/onedrive/data" driveone/onedrive:test
```
**Perform a --resync:**
```bash
docker container run -e ONEDRIVE_RESYNC=1 -v onedrive_conf:/onedrive/conf -v "${onedriveDir}:/onedrive/data" driveone/onedrive:test
```
**Perform a --resync and --verbose:**
```bash
docker container run -e ONEDRIVE_RESYNC=1 -e ONEDRIVE_VERBOSE=1 -v onedrive_conf:/onedrive/conf -v "${onedriveDir}:/onedrive/data" driveone/onedrive:test
```

**Comment by josefrvaldes** [comment]
> @josefrvaldes
> 
> > I ran onedrive from the fist time and it tried to download EVERYTHING, including unwanted folders.
> 
> This sounds like #658 - however this also depends on what version of the Docker container your running & what client version the Docker container is using. Can you provide some debug logs for this?

Maybe I expressed myself wrong. When I said that it tried to download everything including unwanted folders, I meant that I didn't want those folders but I hadn't still done anything to avoid that. I hadn't still made changes in the config files or anything. It was just a default first run, so I thing is the expected behavior to download all your files, isn't it?
If that's not the case, let me know and I'll try to provide you some debug logs, despite that I don't know how to do it :(.

Thanks again for your help!

**Comment by xiaguoxin** [comment]
> ```shell
> ONEDRIVE_RESYNC=1 -e ONEDRIVE_VERBOSE=1
> ```

I just tested these command, and it seems works.

With `ONEDRIVE_DEBUG=1` there're `+ echo '\# We are performing debug output'
\# We are performing debug output` and `[DEBUG]` outcoming.

With `ONEDRIVE_RESYNC=1` there are `+ echo '# We are performing a --resync'
\# We are performing a --resync`. And the file did synced.

Thank you for your work.

**Comment by abraunegg** [comment]
@josefrvaldes

> Maybe I expressed myself wrong. When I said that it tried to download everything including unwanted folders, I meant that I didn't want those folders but I hadn't still done anything to avoid that. I hadn't still made changes in the config files or anything. It was just a default first run, so I thing it is the expected behavior to download all your files, isn't it?
> If that's not the case, let me know and I'll try to provide you some debug logs, despite that I don't know how to do it :(.

Without configuration then yes - that is the default behaviour.

**Comment by abraunegg** [comment]
> > ```shell
> > ONEDRIVE_RESYNC=1 -e ONEDRIVE_VERBOSE=1
> > ```
> 
> I just tested these command, and it seems works.
> 
> With `ONEDRIVE_DEBUG=1` there're `+ echo '\# We are performing debug output' \# We are performing debug output` and `[DEBUG]` outcoming.
> 
> With `ONEDRIVE_RESYNC=1` there are `+ echo '# We are performing a --resync' \# We are performing a --resync`. And the file did synced.
> 
> Thank you for your work.

Thanks for testing. merging the PR to 'master'

**Comment by abraunegg** [comment]
Closing as PR #672 merged to 'master'
