### ISSUE TITLE
Add new setting incl_file as an alternative to skip_file

### ISSUE THREAD

**Issue by zell-mbc** [abraunegg/onedrive#674]
Never mind, got this wrong..but don't seemt o be able to delete the entry.

**Comment by abraunegg** [comment]
>My use case is such that I have many folders on Onedrive but really only need to sync 2 or so.
Having a "incl_file" setting which would contain the files/folders to sync and ignore the rest would make my live easier.
This should also help when the "skip_file" setting gets really long and it may be easier to manage the whitelist instead.
Conceptionally this would be adding a whitelist approach to the existing "skip_file" blacklist.
Another benefit would be that in case a new folder gets added to OneDrive. At the moment I have to manually add the new folder to the skip_file setting to avoid potential vast amounts of data beeing synced, with this proposal nothing needs to be done.
The --single-directory switch somehow does this but is limited to one folder only.


This is achieved by using 'sync_list' - https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#selective-sync
