### ISSUE TITLE
Can't compile on raspbian

### ISSUE THREAD

**Issue by JohannesRabauer** [abraunegg/onedrive#683]
`make` on my raspberry pi 3 brings followinig output:
```
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.3.11-dev > version ; \
fi
/home/johannes/onedrive2/ldc2-1.16.0-linux-armhf/bin/ldmd2  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
Error: Error executing /home/johannes/onedrive2/ldc2-1.16.0-linux-armhf/bin/ldc2: Killed
Makefile:100: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1
```

At some time in the past i made some changes to the OS to be able to use docker. Unfortunatly i don't remember what changes i made specifically. Because i still use some docker stuff, i would like to run onedrive without a complete reinstall. 

*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
`Linux raspberrypi 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed?
**gui installed**
*   OneDrive Account Type
Personal
*   DMD or LDC compiler version **`ldmd2 --version`**
```
LDC - the LLVM D compiler (1.1.1):
  based on DMD v2.071.2 and LLVM 3.9.1
  built with LDC - the LLVM D compiler (1.1.0)
  Default target: armv6-unknown-linux-gnueabihf
  Host CPU: (unknown)
  http://dlang.org - http://wiki.dlang.org/LDC
```
*   Curl Version: Output of `curl --version`
```
curl 7.52.1 (arm-unknown-linux-gnueabihf) libcurl/7.52.1 OpenSSL/1.0.2t zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Comment by Rondom** [comment]
> Error: Error executing /home/johannes/onedrive2/ldc2-1.16.0-linux-armhf/bin/ldc2: Killed

Are you running out of RAM? Check dmesg to see if the OOM killer killed ldc2.

**Comment by abraunegg** [comment]
@JohannesRabauer 
One of the key build requirements is this:
* Build environment must have at least 1GB of memory & 1GB swap space

Are you compliant with this?

I don't have a ARM environment to test, however every build is tested via Travis CI on ARMHF and ARM64

**Comment by JohannesRabauer** [comment]
> 
> 
> > Error: Error executing /home/johannes/onedrive2/ldc2-1.16.0-linux-armhf/bin/ldc2: Killed
> 
> Are you running out of RAM? Check dmesg to see if the OOM killer killed ldc2.

Looks like you are right. dmesg:
```
[348888.030122] Out of memory: Kill process 27088 (ldc2) score 661 or sacrifice child
[348888.030141] Killed process 27088 (ldc2) total-vm:733052kB, anon-rss:693876kB, file-rss:0kB, shmem-rss:0kB
[348888.149734] oom_reaper: reaped process 27088 (ldc2), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```


> 
> 
> @JohannesRabauer
> One of the key build requirements is this:
> 
>     * Build environment must have at least 1GB of memory & 1GB swap space
> 
> 
> Are you compliant with this?
> 
> I don't have a ARM environment to test, however every build is tested via Travis CI on ARMHF and ARM64

Alright, it seems like i need to use more swap space:
```
swapon -s
Filename                                Type            Size    Used    Priority
/var/swap                               file            102396  100936  -2

```

Will try again ASAP.

**Comment by JohannesRabauer** [comment]
After adding 1,5GB Swap space it works! Thanks a lot!
