### ISSUE TITLE
Cannot connect to Microsoft OneDrive Service Reason: Unsupported protocol on handle 55B1F2EB0C40

### ISSUE THREAD

**Issue by manojmone** [abraunegg/onedrive#684]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
When I try to run onedrive, I'm encountering following error -
Cannot connect to Microsoft OneDrive Service
Reason: Unsupported protocol on handle 55908E9F2C40

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
Linux  5.0.0-31-generic #33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I'm using Description:	Ubuntu 18.04.3 LTS Release:	18.04

*   Are you using a headless system (no gui) or with a gui installed?
no gui
*   OneDrive Account Type
 Personal Office 365

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
DMD64 D Compiler v2.087.1

*   Application configuration: Output of `onedrive --display-config`
```
onedrive version                    = v2.3.10-2-g8b969de
Config path                         = /home/manoj/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/manoj/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

*   Curl Version: Output of `curl --version`
curl 7.67.0-DEV (x86_64-pc-linux-gnu) libcurl/7.67.0-DEV

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

[debug_output.log](https://github.com/abraunegg/onedrive/files/3694169/debug_output.log)

**Comment by abraunegg** [comment]
@manojmone 
Please can you follow these instructions to generate a HTTPS Debug log for this issue please:

https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support

**Comment by abraunegg** [comment]
@manojmone 
> * Curl Version: Output of `curl --version`
>   curl 7.67.0-DEV (x86_64-pc-linux-gnu) libcurl/7.67.0-DEV

Also your version of curl appears incorrect for Ubuntu 18.04 LTS. It should be:
```
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 5.0.0-31-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Kata Containers are now fully integrated in Charmed Kubernetes 1.16!
   Yes, charms take the Krazy out of K8s Kata Kluster Konstruction.

     https://ubuntu.com/kubernetes/docs/release-notes

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

0 packages can be updated.
0 updates are security updates.

Your Hardware Enablement Stack (HWE) is supported until April 2023.
Last login: Sun Oct  6 21:05:55 2019 from 172.16.16.212
alex@alex-virtual-machine:~$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
alex@alex-virtual-machine:~$ 
```

So this is certainly a local environmental issue that you need to sort out with your curl version.

**Comment by abraunegg** [comment]
@manojmone
Please can you respond and provide an update

**Comment by manojmone** [comment]
Sorry, have been travelling... I will try this today and update.  Thank you!

**Comment by manojmone** [comment]
You were spot on about the curl version. I installed the right version and voila it worked! Thank you!
