### ISSUE TITLE
Sqlite database corrupted prevents synchronization

### ISSUE THREAD

**Issue by helderdaniel** [abraunegg/onedrive#688]
### Bug Report Details ###
When trying to synchronize, some new local files did not upload to server.
Trying to sync only one dir, with new files:

onedrive --verbose  --verbose  --synchronize  --single-directory newdir

give the error: An internal database error occurred: disk I/O error

So, it seems that the SQLite database is corrupted.
How can it be recovered?

Maybe a resync can solve the issue, however I have new files on local system, that must be preserved and uploaded to server.
How can I ensure that?

Doing a resync with --local-first?
or
Doing a resync with --upload-only?

thx,

helder

Full log is:
```
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/hdaniel
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/hdaniel/.config
[DEBUG] configDirName: Configuring application to use default config path
Using Config Dir: /home/hdaniel/.config/onedrive
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] syncDir: /storage/OneDrive - Universidade do Algarve
Initializing the OneDrive API ...
[DEBUG] Downgrading all HTTP operations to HTTP/1.1 by default
Opening the item database ...
[DEBUG] Using database file: /home/hdaniel/.config/onedrive/items.sqlite3

An internal database error occurred: disk I/O error
```

**Application and Operating System Details:**
Linux Lucas 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

No Gui
OneDrive business
DMD64 D Compiler v2.084.0
```
onedrive version                    = v2.3.8-36-g9d0a653
Config path                         = /home/hdaniel/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /storage/OneDrive - Universidade do Algarve
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 500
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Comment by abraunegg** [comment]
Please can you do the following:

1. Ensure that there is no other 'onedrive' process running at the same time.
2. Make sure that the user permissions for the files in your onedrive config directory are readable, writable and owned by the same user executing the binary

**Comment by abraunegg** [comment]
Additionally you are running a version several releases old - please update with either latest release or master codebase to ensure you are not impacted by issues that have already been fixed

**Comment by helderdaniel** [comment]
Hi @abraunegg 

thanks for the suggestions.

Maybe there was some other onedrive process running at the time of the previous error.
Making sure that there is no other onedrive process running, I tried again.
The log reported the error:

SQLite Database Disk Image Is Malformed

I tried a sync of only one folder with --upload-only and --local-first

The new local files were not updated again on the server

I did some combinations of sync with and without those 2 parameters, again with no luck.

Then a tried with a different dir and --local-first. It uploaded the files.

Now I am doing a full sync with  --local-first

onedrive --synchronize --enable-logging --verbose --verbose --local-first

For each file found in the local directories, it founds it also on the server but does not find an entry on the local database, so it updates the database.
So, it seems it is reconstructing the database.
Maybe the database was corrupted and cleaned somehow.
There is an extract of the log at the end.

But I still have a question, since my local folders have the latest changes that I want to preserve when synchronizing:

synchronizing with --local-first, as I am doing now,  ensures the issues below?

1) all the files existing in the local folders are preserved and uploaded to the local server
2) files deletes on local folders are deleted on the server
3) files deleted on the server ARE NOT deleted on the local folders. Instead, the local folder existing files are uploaded to the server

Do I need to add also --upload-only?

And if it is needed to set the server folders and files as they are in the local folders can I use a:

resync with: --local-first

or

resync with: --local-first and --upload-only


> Additionally you are running a version several releases old - please update with either latest release or master codebase to ensure you are not impacted by issues that have already been fixed

I thought the version that I am running is the last one: v2.3.8-36-g9d0a653
9d0a653 is the last one committed in branch master:

https://github.com/abraunegg/onedrive/commits/master


Extract of the log:
```
2019-Oct-16 09:26:37.389877 [DEBUG] Checking file: ./00-FotosVideos/2015/20150803-NevoeiroOlhão1/IMG_20150803_191320.jpg
2019-Oct-16 09:26:37.6100369 Requested file to upload exists on OneDrive - local database is out of sync for this file: ./00-FotosVideos/2015/20150803-NevoeiroOlhão1/IMG_20150803_191320.jpg
2019-Oct-16 09:26:37.6103443 Updating the local database with details for this file: ./00-FotosVideos/2015/20150803-NevoeiroOlhão1/IMG_20150803_191320.jpg
2019-Oct-16 09:26:37.610666 [DEBUG] Adding to database: Item("b!nJQI4UfVkkuT3DscKMYwgTdEq3YfLs5MoqnjdcN889m8trHuJL_7To6pfkM0De48", "01TUY2TI4YBF6C4E3VYZBYOTGWL7FFBVOF", "IMG_20150803_191320.jpg", file, "\"{2E7C0998-7513-43C6-874C-D65FCA50D5C5},2\"", "\"c:{2E7C0998-7513-43C6-874C-D65FCA50D5C5},1\"", 2015-Aug-03 18:13:20Z, "01TUY2TIZMXCATX4UITBBI3KSZXG2DFEJW", "", "", "58Tvnlqbpdx8zgl3JVzcoOKSri0=", "", "")
2019-Oct-16 09:26:37.619229 Remaining free space: 1041377895411
```

**Comment by abraunegg** [comment]
@helderdaniel 
> I thought the version that I am running is the last one: v2.3.8-36-g9d0a653

Build 'g9d0a653' is right, 'v2.3.8-36' is wrong - so most likely not cleaning before building as per instructions which can lead to this issue occurring.





> Then a tried with a different dir and --local-first. It uploaded the files.
> 
> Now I am doing a full sync with --local-first
> 
> onedrive --synchronize --enable-logging --verbose --verbose --local-first
> 
> For each file found in the local directories, it founds it also on the server but does not find an entry on the local database, so it updates the database.
> So, it seems it is reconstructing the database.
> Maybe the database was corrupted and cleaned somehow.

So this to me sounds like your 'original' issue (An internal database error occurred: disk I/O error) is now resolved? correct ?? You also still did not mention or validate if the files in your config directory are owned by the right user correctly.

> But I still have a question, since my local folders have the latest changes that I want to preserve when synchronizing:
> 
> synchronizing with --local-first, as I am doing now, ensures the issues below?
> 
> 1. all the files existing in the local folders are preserved and uploaded to the local server
> 2. files deletes on local folders are deleted on the server
> 3. files deleted on the server ARE NOT deleted on the local folders. Instead, the local folder existing files are uploaded to the server
> 
> Do I need to add also --upload-only?

`--local-first` will check / upload changes from your local system 'first' before checking OneDrive. Normal operation is: OneDrive, Local, OneDrive, so this switch prevents the first sync.

> 3. files deleted on the server ARE NOT deleted on the local folders. Instead, the local folder existing files are uploaded to the server

To achieve this, you want to use `--upload-only` as well - as, this will not 'download' changes made on OneDrive - where a 'change' is a 'delete' or any other operation.

> Extract of the log:

This looks all normal to me.

**Comment by helderdaniel** [comment]
Sorry, I forgot to mention before: The folders have all the same user. Some did upload others do not.

I checked my logs and command history which suggested that it was a SQLite error.
However, I did not find yet why the DB error happened.

So, the first error was an SQLite error:
``
SQLite Database Disk Image Is Malformed
``

Then I got the one that I reported:
``
An internal database error occurred: disk I/O error
``

But this probably happened because I tried to run one onedrive command while another was still running in background, as you mentioned.

Then after several different sync commands, with different options I did a resync, which I interrupted after a while:

onedrive --verbose  --verbose  --synchronize --resync --upload-only  --local-first

This should have cleaned the local database, and that's why now it is being reconstructed with a sync command.


About the version, I build it as instructed with:

git pull origin master

./configure
make clean; make;
sudo make install

but the version reported is the one I told you:

```
(dmd-2.084.0)hdaniel@Lucas:~/onedrive$ ./onedrive --version
onedrive v2.3.8-36-g9d0a653
```

After a "make clean" the repo looks like below. There are still some files from the previous version:

```
-rw-r--r--   1 hdaniel hdaniel  10912 Aug 18 13:30 aclocal.m4
-rw-r--r--   1 hdaniel hdaniel  22695 Oct 16 05:44 CHANGELOG.md
-rw-r--r--   1 hdaniel hdaniel   1054 Oct 16 05:44 config
-rwxr-xr-x   1 hdaniel hdaniel 111213 Oct 16 05:44 configure
-rw-r--r--   1 hdaniel hdaniel   9647 Oct 16 05:44 configure.ac
drwxr-xr-x  10 hdaniel hdaniel   4096 Oct 16 05:44 contrib
drwxr-xr-x   2 hdaniel hdaniel   4096 Oct 16 05:44 docs
drwxr-xr-x   8 hdaniel hdaniel   4096 Oct 16 05:44 .git
drwxr-xr-x   3 hdaniel hdaniel   4096 Aug 18 13:30 .github
-rw-r--r--   1 hdaniel hdaniel    210 Aug 18 13:30 .gitignore
-rwxr-xr-x   1 hdaniel hdaniel  15368 Aug 18 13:30 install-sh
-rw-r--r--   1 hdaniel hdaniel  35147 Aug 18 13:30 LICENSE
-rw-r--r--   1 hdaniel hdaniel   4592 Oct 16 11:38 Makefile
-rw-r--r--   1 hdaniel hdaniel   4712 Oct 16 05:44 Makefile.in
-rw-r--r--   1 hdaniel hdaniel   8939 Oct 16 11:38 onedrive.1
-rw-r--r--   1 hdaniel hdaniel   8947 Oct 16 05:44 onedrive.1.in
-rw-r--r--   1 hdaniel hdaniel   2403 Oct 16 05:44 README.md
drwxr-xr-x   3 hdaniel hdaniel   4096 Oct 16 05:44 src
drwxr-xr-x   2 hdaniel hdaniel   4096 Aug 18 13:30 tests
-rw-r--r--   1 hdaniel hdaniel   6876 Aug 18 13:30 .travis-ci.sh
-rw-r--r--   1 hdaniel hdaniel    264 Aug 18 13:30 .travis.yml
```

**Comment by abraunegg** [comment]
@helderdaniel 
> Then after several different sync commands, with different options I did a resync, which I interrupted after a while:
> 
> onedrive --verbose --verbose --synchronize --resync --upload-only --local-first
> 
> This should have cleaned the local database, and that's why now it is being reconstructed with a sync command.

Yes - this will clean up the database and rebuild it correctly when there is an error. Just be sure to remove the `--resync` otherwise each and every time you sync you are rebuilding the database.

> About the version, I build it as instructed with:
> 
> ```
> git pull origin master
> 
> ./configure
> make clean; make;
> sudo make install
> ```
> 
> but the version reported is the one I told you:
> 
> ```
> (dmd-2.084.0)hdaniel@Lucas:~/onedrive$ ./onedrive --version
> onedrive v2.3.8-36-g9d0a653
> ```
> 
> After a "make clean" the repo looks like below. There are still some files from the previous version:

OK .. this is weird ... I think this has to do with how pulling the code from the repository. The recommended and documented way is detailed [here](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#building-using-dmd-reference-compiler):

**Example:**
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
source ~/dlang/dmd-2.085.0/activate
./configure; make clean; make;
deactivate
```

When this is done, the version is correct:
```
[alex@centos7full onedrive]$ ./onedrive --version
onedrive v2.3.10-7-g9d0a653
[alex@centos7full onedrive]$ 
```
The output of the files locally would be as follows:
```
[alex@centos7full onedrive]$ ls -la
total 16520
drwxrwxr-x.   8 alex alex    4096 Oct 17 07:14 .
drwxrwxr-x. 164 alex alex    8192 Oct 17 07:13 ..
-rw-rw-r--.   1 alex alex   10912 Oct 17 07:13 aclocal.m4
-rw-rw-r--.   1 alex alex   22695 Oct 17 07:13 CHANGELOG.md
-rw-rw-r--.   1 alex alex    1054 Oct 17 07:13 config
-rwxrwxr-x.   1 alex alex  111213 Oct 17 07:13 configure
-rw-rw-r--.   1 alex alex    9647 Oct 17 07:13 configure.ac
drwxrwxr-x.  10 alex alex     125 Oct 17 07:13 contrib
drwxrwxr-x.   2 alex alex      77 Oct 17 07:13 docs
drwxrwxr-x.   8 alex alex     163 Oct 17 07:13 .git
drwxrwxr-x.   3 alex alex      44 Oct 17 07:13 .github
-rw-rw-r--.   1 alex alex     210 Oct 17 07:13 .gitignore
-rwxrwxr-x.   1 alex alex   15368 Oct 17 07:13 install-sh
-rw-rw-r--.   1 alex alex   35147 Oct 17 07:13 LICENSE
-rw-rw-r--.   1 alex alex    4600 Oct 17 07:13 Makefile
-rw-rw-r--.   1 alex alex    4712 Oct 17 07:13 Makefile.in
-rwxrwxr-x.   1 alex alex 8098672 Oct 17 07:14 onedrive
-rw-rw-r--.   1 alex alex    8939 Oct 17 07:13 onedrive.1
-rw-rw-r--.   1 alex alex    8947 Oct 17 07:13 onedrive.1.in
-rw-r--r--.   1 alex alex 8507704 Oct 17 07:14 onedrive.o
-rw-rw-r--.   1 alex alex    2403 Oct 17 07:13 README.md
drwxrwxr-x.   3 alex alex     232 Oct 17 07:13 src
drwxrwxr-x.   2 alex alex      54 Oct 17 07:13 tests
-rw-rw-r--.   1 alex alex    6876 Oct 17 07:13 .travis-ci.sh
-rw-rw-r--.   1 alex alex     264 Oct 17 07:13 .travis.yml
-rw-rw-r--.   1 alex alex      19 Oct 17 07:13 version
```

In your listing you are also missing the 'version' file - which also does not make sense. Also other files like your Makefile are the wrong size. I suspect your 'clone' source is out of sync or something is wrong with where you are cloning from - which also means if those files are out of sync, what else is out of sync and are you running the correct codebase ? I would suspect at this stage no - meaning - you have the potential to have other issues appear which have been already fixed.

Please can you 'fix' your cloning / build process and your source repository so that you are getting the correct code source and build & retest.

**Comment by helderdaniel** [comment]
@abraunegg 

cloned and rebuilt as suggested now gives correct version:
``
hdaniel@Lucas:~/onedrive/onedrive$ onedrive --version
onedrive v2.3.10-7-g9d0a653
``

It is still synchronizing and reconstructing DB, since I have tens of GBytes in onedrive, and many are small files.
Until now looks good.

It seems the issue was due to SQLite DB corruption. The original error:

SQLite Database Disk Image Is Malformed

was corrected when resyncing.
Still have to figure out why DB got corrupted, but there can be many reasons that do not involve the onedrive client.

thanks for your help

**Comment by abraunegg** [comment]
@helderdaniel 
No problem - glad it is all resolved.

Closing issue as resolved
