### ISSUE TITLE
skip_dir is not skipping all dirs

### ISSUE THREAD

**Issue by hugomilan** [abraunegg/onedrive#689]
### Bug Report Details ###
I am migrating from [onedrived](https://github.com/xybu/onedrived-dev) and I have been using OneDrive with Linux for quite a while now. Consequently, I have a very long list of skip dirs. My skip_dir variable has about 905 chars with 34 folders to skip.

I have written the skip_dir as instructed [here](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md). Then, I run a `onedrive --synchronize --resync --verbose`. While running that command, I noticed that some directories I assigned to the skip_dir variable were not being skipped but were being synchronized (downloaded from my OneDrive account). When I noticed that they were being synchronized, I Ctrl + C the execution. When I synchronize with `onedrive --synchronize --verbose --dry-run` I notice that the database was broken.

**Application and Operating System Details:**
*   Linux pop-os 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
*   GNOME 3.32.2
*   OneDrive Account Type: personal
*   dmd-2.088.1
*   Application configuration: 
```
onedrive version                    = v2.3.10-7-g9d0a653
Config path                         = /home/hugomilan/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/hugomilan/OneDrive
Config option 'skip_dir'            = Anexos de email|Computação|Cornell/Fall 2015-2016|Cornell/2016*|Cornell/2017*|Cornell/2018*|Cornell/2019 S*|Cornell/Artigos|Cornell/Fields for minor|Cornell/Others/Alex/22 ICB/website/Freelancer/website_\*|Cornell/Project/TLM/Netbeans/V05/tlmbht/docs/doxygen/html|Cornell/Project/TLM/Netbeans/V05/tlmbht/docs/doxygen/latex|Cornell/Publications/2018/Piglets 2013/code|Documentos|Documents|Doutorado|MaiaFR|Mestrado|Outros/Experimento Julho 2016|Imagens/Imagens da Câmera/HVL|Imagens/Imagens da Câmera/200*|Imagens/Imagens da Câmera/2010|Imagens/Imagens da Câmera/2011|Imagens/Imagens da Câmera/2012|Imagens/Imagens da Câmera/2013|Imagens/Imagens da Câmera/2014|Imagens/Imagens da Câmera/2015|Imagens/Imagens da Câmera/2016|Imagens/Imagens da Câmera/2017|Imagens/Imagens da Câmera/2018|Imagens/Imagens da Câmera/Outros|Imagens/Imagens da Câmera/photogrammetry|Imagens/Capturas de tela|Imagens/Imagens salvas
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
*   Curl Version: 
```
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

**Note:** Please generate a full debug log as per 
The logs for --resync and after that were sent in the e-mail. The two files sent were debug_output_resync.zip and debug_output_dry_run.log

**To Reproduce**
When I run `onedrive --synchronize --verbose --dry-run` I see a problem with the database. If I resynchronize, I see the directories I asked to skip being downloaded.

**Complete Verbose Log Output**
Sent in the e-mail.

### Bug Report Checklist ###
*   [x] Detailed description
*   [X] Reproduction steps (if applicable)
*   [X] Verbose Log Output

**Comment by abraunegg** [comment]
@hugomilan 
The debug email finally came through, will look into the files provided.

**Comment by abraunegg** [comment]
@hugomilan 
> While running that command, I noticed that some directories I assigned to the skip_dir variable were not being skipped but were being synchronized (downloaded from my OneDrive account).

Given the size of the provided logs, can you provide some directory names that match this criteria?

**Comment by hugomilan** [comment]
Thanks for reaching out. I noticed that "Cornell/Spring 2017" was being
synchronized even though I added it to the skip_dir variable.

**Comment by abraunegg** [comment]
@hugomilan 
Thanks - just gives me some reference as to what & where to look at in the logs provided & see if I can replicate what is going on.

**Comment by abraunegg** [comment]
@hugomilan 
> I noticed that "Cornell/Spring 2017" was being synchronized even though I added it to the skip_dir variable.

Unfortunately that string sequence is not in your 'skip_dir' config - nor does it even show up anywhere in the debug log file .. 

Do you have another example / reference to look at?

**Comment by hugomilan** [comment]
I am sorry, I confused it. It should be "Cornell 2017 Spring"

**Comment by hugomilan** [comment]
BTW, I have it as a wildcard in the current skip_dir "Cornell/2017*" but I
also tried writing it in full "Cornell/2017 Spring"

**Comment by abraunegg** [comment]
@hugomilan 
Thanks .. will see if I can replicate what is going on

**Comment by abraunegg** [comment]
@hugomilan 
Replicated what is going on, working on a fix

**Comment by abraunegg** [comment]
@hugomilan 
Please can you test the following PR against your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/692/head:pr692
git checkout pr692
./configure; make clean; make;
```

**Note:** For directories that were supposed to be skipped and were not, you may need to perform some sort of local cleanup manually.

When using your `skip_dir` configuration to test the above patch, the result is below:

```
Using Config Dir: /home/alex/.config/onedrive-personal/
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.10-7-g9d0a653
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5354469671
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 16 changes
Creating directory: Cornell
Creating directory: 10-Files
Creating directory: 10-Files/Cisco VDI Whitepaper
Creating directory: 10-Files/Architecture Layres
Skipping item - excluded by skip_dir config match: Cornell/2017 Spring
Skipping item - excluded by skip_dir config match: Cornell/2016 Spring
Downloading file 10-Files/Cisco VDI Whitepaper/white_paper_c11-494994.pdf ... done.
Skipping item - excluded by skip_file config: campover.pdf
Downloading file 10-Files/Architecture Layres/architecture layers v0.4 - AB.vsd ... done.
Uploading differences of .
Processing root
The directory has not changed
Processing Cornell
The directory has not changed
Processing 10-Files
The directory has not changed
Processing Cisco VDI Whitepaper
The directory has not changed
Processing white_paper_c11-494994.pdf
The file has not changed
Processing Architecture Layres
The directory has not changed
Processing architecture layers v0.4 - AB.vsd
The file has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

**Comment by abraunegg** [comment]
@hugomilan
Any chance in testing this PR yet?

**Comment by hugomilan** [comment]
Working as expected!

**Comment by abraunegg** [comment]
Closing loop as PR #692 merged into master
