### ISSUE TITLE
Fail to start monitor process

### ISSUE THREAD

**Issue by linchangyi** [abraunegg/onedrive#704]
### Bug Report Details ###
**Describe the bug**
Failed to start the monitor process

**Application and Operating System Details:**
*   OS: Linux lincy-desktop 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

*   System: KDE neon
*   OneDrive Account Type: personal
*   DMD version: DMD64 D Compiler v2.087.1
*   Application configuration: 
```
onedrive version                    = v2.3.10-13-ge99872e
Config path                         = /home/lincy/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/lincy/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
工作
技术
文档
配置
```

*   Curl Version: curl 7.65.3 

**To Reproduce**

Failed to run 'onedrive --monitor --verbose'

Output:
> Using Config Dir: /home/lincy/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/lincy/OneDrive
Application version: v2.3.10-13-ge99872e
Account Type: personal
Default Drive ID: 403cf3685820d136
Default Root ID: 403CF3685820D136!407
Remaining Free Space: 2921007726
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 45
monitor.MonitorException@src/monitor.d(59): inotify_init failed (Too many open files)
src/monitor.d:16 void monitor.Monitor.init(config.Config, bool, bool, bool) [0x561c8b9cfda4]
src/main.d:675 _Dmain [0x561c8b9ceef0]

**Complete Verbose Log Output**

 Please refer to the attachment below to see the log of 'onedrive --synchronize --verbose', .

[debug_output.log](https://github.com/abraunegg/onedrive/files/3782942/debug_output.log)

### Bug Report Checklist

*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment]
@linchangyi 
Whilst the crash needs to be fixed, this is a local system issue. please refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#running-onedrive-as-a-system-service - which says:

**Note:** If using the service files, you may need to increase the `fs.inotify.max_user_watches` value on your system to handle the number of files in the directory you are monitoring as the initial system default value may be too low.

**Comment by abraunegg** [comment]
@linchangyi 
Please can you test the following PR to resolve the application crash:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/705/head:pr705
git checkout pr705
./configure; make clean; make;
```

Whilst this should fix the application crash, you also need to modify your system. To do this:

```
sysctl fs.file-max
```

This will give you a value, then you need to increase this value to something more applicable:
```
sudo sysctl fs.file-max=<new_value>
```

What this new value is, I cannot advise. I also cannot advise on your OS & making this change permanent.

**Comment by linchangyi** [comment]
@abraunegg  ,  thanks.  I followed your advice and googled it and fixed it,  that is what I found.
just modify  '/etc/security/limits.conf' to increase user process file-handle(default is 1024),  
```
youruser          soft    nofile 10000
youruser           hard    nofile 30000
```

**Comment by abraunegg** [comment]
@linchangyi 
Thanks for the confirmation.

PR #705 merged into master, closing case
