### ISSUE TITLE
Uni of leeds lists this as the onedrive client for Linux

### ISSUE THREAD

**Issue by Tasty213** [abraunegg/onedrive#713]
This isn't really a feature request or a bug report just thought the developers would like to know that on the Leeds uni office 365 homepage, there's a list of software thats available to students to help them use office 365. So alongside word/excel/powerpoint/outlook, there's 'onedrive for linux'. Which links here, guess this means that this is the official onedrive for linux client for the University of Leeds.

**Comment by abraunegg** [comment]
@Tasty213 
Thanks for letting us know :)

**Comment by abraunegg** [comment]
closing, not an issue :)

**Comment by norbusan** [comment]
Thanks @Tasty213 that is good to hear!!
