### ISSUE TITLE
Constant notify: Processing ### Changes

### ISSUE THREAD

**Issue by lazylionca** [abraunegg/onedrive#716]
### Bug Report Details ###
Two scenarios:

If I enable it to run in the background using systemctl then i get the notifications flashing in the upper right corner saying "OneDrive Processing XXX changes" where XXX is always a different number. 

If I run it from cli using onedrive --synchronize  it will scroll pages of the same message.

Thing is, all the files are already synced. There have not been any changes, or there are only a few changes. 

I can understand if the program is checking for changes, but I don't need to be told that it's checking, that's expected behavior.  I only want to be notified when it starts checking for changes, when it find changes and is syncing them, and when it is done checking. 

Because I sync a fair amount of files I have the monitor_interval = "600" (  ten minutes ). I originally had the default five minutes but it took too long to check everything and a new cycle would start before the old one finished. (doesn't it check for that?) 

I have this installed on three different machines all running Manjaro (ARCH) Cinnamon 18.1 64 bit
and they all do the same thing.

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
```
    Linux mycomputer 5.2.21-1-MANJARO #1 SMP PREEMPT Sat Oct 12 11:09:56 UTC 2019 x86_64 GNU/Linux
```

*   Are you using a headless system (no gui) or with a gui installed?
    Gui: Cinnamon

*   OneDrive Account Type
    Paid Personal

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
    DMD64 D Compiler v2.088.0-dirty

*   Application configuration: Output of `onedrive --display-config`
```
onedrive version                    = v2.3.10
Config path                         = /home/user/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /Data/OneDrive
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = true
Config option 'skip_symlinks'       = true
Config option 'monitor_interval'    = 900
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
Books
Concert-Videos
Documents
Finances
icons
Insurance
Programming
ringtones
StartPage
stuff
```

*   Curl Version: Output of `curl --version`
```
curl 7.66.0 (x86_64-pc-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.8.2 nghttp2/1.39.2
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Install on Manjaro Cinnamon 8.1 and run using config above.

**Complete Verbose Log Output**

The logfile is 1.5 Mbytes.
Can i email it ?

**Comment by abraunegg** [comment]
@lazylionca 
Thanks for the bug report, however this issue you are seeing is as a direct result of the following:
* Your using sync list
* A bug that was identified where when you move folders into a 'sync_list' matched folder online, nothing would sync - see #658 for details

The good news here is, the behaviour your seeing is fixed in 'master' by #679 

As your running (based on your version output) v2.3.10 where as the latest master is v2.3.10-20-g7b4ba2e - please can you upgrade your client and retest.

**Comment by abraunegg** [comment]
@lazylionca 
Please can you respond in regards to this issue.

**Comment by lazylionca** [comment]
I appreciate the prompt response. I look forward to testing the new versoin.

Thanks!

**Comment by lazylionca** [comment]
Ok, It looks like the sync'ing part is working now, but this new notify message that is "Processing XXX items to ensure consistent state due to sync_list being used" won't go away. It keeps flashing repeatedly and getting in the way of controls for other programs. It does this even when there is no changes to sync. 

I want the notifications, but can they be a lot less detailed? Show one when the sync process starts, then again when finished, maybe a periodic one every few minutes. I don't need a new notify every two seconds that last 1.75 seconds!!

**Comment by abraunegg** [comment]
@lazylionca 
Please can you ensure you are using the latest code base and modify your configuration in regards to how frequent notifications occur as per https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#min_notify_changes

If you are still having an issue, please provide a debug log as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support
