### ISSUE TITLE
document Improvement: desktop notification

### ISSUE THREAD

**Issue by priv** [abraunegg/onedrive#718]
Hi,

notification-daemon is not installed by default on 19.10 eoan any more, you need do `sudo apt install notification-daemon` before you can use notification.

Maybe you want to hint user about this in configure and run section.

Thanks

**Comment by abraunegg** [comment]
@priv 
Thanks for the info, can you submit a PR that updates the documentation?

**Comment by priv** [comment]
Sorry I think that I had some misunderstanding here.

This is same issue as #509, actually libnotify should work.  And it works without notification-daemon if invoked from GUI after logged in.

It just cannot use notification server normally when invoked by systemd automatically.

Installing notification-daemon package just worked around the issue since it provides another entry for notification, not a real solution.

**Comment by abraunegg** [comment]
@priv 
Can you provide more details around your *actual* problem you faced?

Was it this issue: https://github.com/abraunegg/onedrive/wiki/systemd:-Failed-to-connect-to-bus:-No-such-file-or-directory ?

**Comment by norbusan** [comment]
I think it was the usual case that OneDrive was started via the systemd unit, and this cannot connect to the notification service.
I agree with the OP that this can be closed.
