### ISSUE TITLE
error when syncing business shared folder

### ISSUE THREAD

**Issue by e-dub** [abraunegg/onedrive#719]
Getting following error when syncing business shared folders:
```
onedrive --synchronize --sync-shared-folders
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 501 (Not Implemented)
  Error Reason:  view.delta can only be called on the root.

Remove your '~/.config/onedrive/items.sqlite3' file and try to sync again

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 501 (Not Implemented)
  Error Reason:  view.delta can only be called on the root.

Remove your '~/.config/onedrive/items.sqlite3' file and try to sync again
```

Removed file as stated, but still getting same error. 
Any ideas for me?

**Comment by abraunegg** [comment]
@e-dub 
Whilst you have provided some details, you have not used the template for submitting issues or followed the directions as per https://github.com/abraunegg/onedrive/blob/master/README.md#reporting-issues 

Please can you update your post above with the following:

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
*   Are you using a headless system (no gui) or with a gui installed?
*   OneDrive Account Type
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
*   Application configuration: Output of `onedrive --display-config`
*   Curl Version: Output of `curl --version`

This **critically important** as it helps configure a system in an attempt to replicate the issue or identify very quickly if this is a version issue.

Please can you also generate a verbose debug log as per: https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

This is needed so the code can be correctly tracked through as to what may be occurring and why.

**Comment by abraunegg** [comment]
@e-dub 
Please can you respond

**Comment by abraunegg** [comment]
@e-dub
Please can you respond

**Comment by abraunegg** [comment]
@e-dub 
I have spent some time looking into this, and fixed the issue. 

As this is a PR, which is on hold, and not merged into master, marking this as a bug, fixed & closing.
