### ISSUE TITLE
Token generation problem

### ISSUE THREAD

**Issue by Boia11** [abraunegg/onedrive#726]
I need to update token and I use `rm -f ~/.config/onedrive/refresh_token` and after `onedrive` command.
I copy the link show after `Authorize this app visiting:` but after selection of my Business account and authorized the app "OneDrive Free Client", the browser show only one blank page.
Why?

**Comment by abraunegg** [comment]
This is 100% normal.

You take the result URL from that white page and paste into the client as the response. Refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#first-run-zap for further details.

**Comment by Boia11** [comment]
> 
> 
> This is 100% normal.
> 
> You take the result URL from that white page and paste into the client as the response. Refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#first-run-zap for further details.

This is the link in address bar `https://login.microsoftonline.com/common/oauth2/nativeclient?code=OAQABAAIAAACQN9QBRU3jT6bcBQLZNUj7FT2FxWBEoe1qQUGCvGm3bJ57yuHjeR9PjFtQxyEt5LO6fSfby6xO9mNdrPOo0mNan9pyo8C7nAEeDHyZsQTlnzXPAG82fqK80A_Ba3EH5om1CTtqgPS-AyXxe8dpEZxykC6vlafBV8croE9e5NyFG0i8waZF2UccJ--gCDy4qmTLKlgahsgGduDjVSA6Ux-pH1VtSRNr0XsE33snZ3ZBoHdRVdeURiszyvmsd31XoRs8RoYufKhPoun3m9Vz-hTx7AsAh9eKzJfMCKcEil1ZWRbYgXInBxCrJXeKE2ZunQjLPAv3N4YGllTkHtQ3YiLJXX_sbF9sy-edZXgoXDEGA3aqZtH1vagRwTObDWqWLPuuyzz2yFqsXnEcXTDFUeGhVpK0rbJUw9O53S4vO5BeYm3Yaybb75L4L2VmJqipw5QOWnKiWC4k9Tr3y3eydlpkZoptcH934dMRdtyNlmQbkKt5hT_mf-a7p_uFEmoWahMMPf3XxKY8Tfntfcm4eahD8dFvkZrUIZySm1AdwlCvAgFnRtnowBiuk4VhN3ugD_V11X-IZtOl6fnjoKGz5YUwQagc2BQo9Vrfz8HDP6NBWlXZhNFNp8Q58DuxKwqOhGQ0jMw5e-_l1LY-S14udTQ23Zm-2wrtt_uUZd9mdEoC3MrEb4OUf2rl9jEXEofU2bTj5noSwJt_MG--suzv_ZxwYyzBN94zDrNTU15sQ2vDZWplKMDNRLjseiW_kCIDfJgqtD-iSmjuZDMYuL11iZ-vf6Lev9ZMckHnsqEmfB2-WiB9YZXg2tFa_cSHLz5F3QkgAA&session_state=d3482b7f-9a31-4135-8bbf-e6e38ca69dd2`
I need to put it that?

**Comment by abraunegg** [comment]
Yes .. you paste that as the response to the application
