### ISSUE TITLE
wildcard for skip_dir and skip_file

### ISSUE THREAD

**Issue by x0rld** [abraunegg/onedrive#735]
#189  Bug Report Details ###
Sorry for the last issue I missclicked and I was searching if I can close it... I didn't see the button below 
**Describe the bug**
I used theses wildcard for skip_file
the .mp4 are still downloading
*Application and Operating System Details:**
*   OS:Linux x0rld-UX410UAK 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
*   I use gnome
*  Office 365 account
*   DMD64 D Compiler v2.087.1
*Application configuration:
```
onedrive version                    = v2.3.11-2-gc876b9c
Config path                         = /home/x0rld/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/x0rld/OneDrive
Config option 'skip_dir'            = Image/*|2017 ESGI 1ere/*|lycée/*|Music/*|Wordlist/*
Config option 'skip_file'           = IMG*|201*|*Instagram*|*.jpeg| *.jpg | *.mp4 | *.png
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
```
*   Curl Version:  libcurl/7.58.0 

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  set *.mp4 in skip_file 
2. execute `onedrive -synchronize --verbose --resync`
and the .mp4 files are still downloading

Application Log Output:
```bash
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/x0rld
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/x0rld/.config
[DEBUG] configDirName: Configuring application to use default config path
Using Config Dir: /home/x0rld/.config/onedrive
```

**Screenshots**
![image](https://user-images.githubusercontent.com/45242856/69467977-a9953f80-0d8a-11ea-9891-7fa1af02aca0.png)

**Comment by x0rld** [comment]
Well I restart it one more time but now the .mp4 are exluded, I readlly don't understand why now it works.
![image](https://user-images.githubusercontent.com/45242856/69468592-0691f500-0d8d-11ea-9741-f31343c90eff.png)

**Comment by norbusan** [comment]
```
Config option 'skip_file'           = IMG*|201*|*Instagram*|*.jpeg| *.jpg | *.mp4 | *.png
```
I think you need to remove the spaces before the `*`, otherwise this is matching only files ` something.mp4`, that is, with an initial space.

**Comment by x0rld** [comment]
oh yeah probably thanks
