### ISSUE TITLE
Unable to query OneDrive to initialize application

### ISSUE THREAD

**Issue by Boia11** [abraunegg/onedrive#736]
I use the last Onedrive Unable to query **OneDrive v2.3.11** but from upgrade sometimes not work with error `Unable to query OneDrive to initialize application`

Debian 9 on ARM64

**Comment by abraunegg** [comment]
@Boia11 
This is not a problem or issue with the application. This is indicative of an local environmental issues - transient network access issue or something else which is preventing the application from communicating with OneDrive to obtain the required information to initialise.

Also - when reporting issues please ensure your follow these steps: https://github.com/abraunegg/onedrive#reporting-issues
