### ISSUE TITLE
Docker container image?

### ISSUE THREAD

**Issue by derekoharrow** [abraunegg/onedrive#74]
Not exactly a feature request for your client, but would you be able to create a docker image for this?

There is [one already](https://bitbucket.org/jkoo/docker-onedrive) for the skilion code, but that is obviously out of date so it would be good to have one based on a current client.

If you don't have the time, then perhaps I can have a crack at it - not tried doing it before, but willing to give it  a go - it looks fairly trivial as I guess most of the dockerfile would be identical except for the source of the master.zip file...

**Comment by abraunegg** [comment]
There are complexities around building a docker image for this application at the moment:

* The application utilises either command line switches or a configuration file, but the configuration file lacks all of the options that could be passed in. This needs to be fixed.
* The monitor mode of the application is not good. You certainly do not want to be running this application in a Docker container in monitor mode at present as it will run away CPU wise and cause a significant performance impact. The only way to 'not use' monitor mode is to configure the application to use 'cron' to run - however there are challenges around that within a Docker container. The way the application performs when in monitor mode needs to be fixed before I would even suggest using this application in a Docker container.

For the moment I will not be working on providing a Docker image.

**Comment by adudek** [comment]
Just yesterday I submitted docker image monitoring service based on this repo: docker pull driveone/onedrive. For usage, please refer to https://github.com/abraunegg/onedrive/blob/5c566a1b87e09901b7db072e8d82917bda66172c/docker/README.md
