### ISSUE TITLE
Dedicated directories for Sharepoint group drives

### ISSUE THREAD

**Issue by benoiton** [abraunegg/onedrive#748]
I successfully sync my OneDrive and a Sharepoint group drive.
But files and directories of the Sharepoint group drive are directly in my local OneDrive directory.

Example:

- In remote OneDrive: dir1
- In remote Sharepoint group drive: dir2
- In my local $HOME/OneDrive directory: dir1 and dir2

With more files or Sharepoint group drives, it will be a mess.

It should be possible to associate each SharePoint group drive with a local directory.

Thanks

**Comment by abraunegg** [comment]
@benoiton 
> It should be possible to associate each SharePoint group drive with a local directory.

Agree, but this is a constraint on how the client works unfortunately. This would be a massive re-write to handle such situation.

**Comment by abraunegg** [comment]
@benoiton 
A possible workaround also would be to have 2 client configurations, where:
* sync_dir is updated for where you want to store your 'OneDrive' folder
* sync_dir is updated for where you want to store your SharePoint Group Drive + specify the Group Drive under drive_id

**Comment by benoiton** [comment]
This workaround seems OK! Thanks.
And I suppose this is also the way to go to sync more than 1 Sharepoint group drive.
https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#using-multiple-onedrive-accounts.
I'm not sure: how should I create and sync if I do not want to sync my OneDrive, but only a Sharepoint groupe drive?

**Comment by abraunegg** [comment]
@benoiton
When specifying a drive_id - only that drive id is synced, so in theory, only that group drive would be synced

**Comment by benoiton** [comment]
I confirm adding a drive_id "hides" previous conf. It may be useful to write it on https://github.com/abraunegg/onedrive/blob/master/docs/Office365.md.
I successfully tested this. Thanks.

**Comment by abraunegg** [comment]
@benoiton 
Feel free to submit a PR that articulates this use case and configuration
