### ISSUE TITLE
Please update installation instruction for CentOS 7.7

### ISSUE THREAD

**Issue by hulalalb** [abraunegg/onedrive#750]
I abandoned the git from skilion for failing running onedrive on CentOS 7.7 because of expiration of grant, and don't know how to re-authorization. I wanna use you version, but no instructions for latest version of CentOS, even your updated MD file. Please.

**Comment by abraunegg** [comment]
@hulalalb 
To install on CentOS 7.x please follow these instructions to install the dependencies: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-fedora--version-18--centos--rhel

Then follow these instructions to build & compile: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#compilation--installation

To configure, use the following directions: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md

**Comment by abraunegg** [comment]
Closing issue as questioned answered

**Comment by hulalalb** [comment]
Bingo~. Thanks  a lot.
