### ISSUE TITLE
Consider providing install instructions for official Fedora package

### ISSUE THREAD

**Issue by thomasfedb** [abraunegg/onedrive#751]
This project is packaged in the official Fedora software repositories. All that end users need to do to install on recent versions of Fedora is `sudo dnf install onedrive`. It would be helpful if this was added to the installation documentation.

**Comment by abraunegg** [comment]
@thomasfedb 
Feel free to submit a PR also with the necesary changes if easier

**Comment by thomasfedb** [comment]
> @thomasfedb
> Feel free to submit a PR also with the necesary changes if easier

Done!

**Comment by abraunegg** [comment]
@thomasfedb 
Thanks for the PR, closing as this is now merged

**Comment by abraunegg** [comment]
@thomasfedb 
Whilst this has been added, it appears that the package on Fedora Koji is 2 versions out .. v2.3.10 ...

Please fix the Fedora CI/CD process so that the latest released packages get updated for Fedora

**Comment by thomasfedb** [comment]
Hi @abraunegg, package updates in Fedora are not automated, they require manual intervention. I will look to update the version on onedrive soon. Generally I update the package when a Fedora user reports an issue that is resolved in a more recent version.

**Comment by abraunegg** [comment]
@thomasfedb 
If you can automate like the Arch AUR does - that would be better that waiting for users to report issues on the RedHat / Fedora tracker - most issues are reported here firat and fixes fairly quickly. Releases are on a ~monthly cadence or if urgent.
