### ISSUE TITLE
Possible to synchronise from 2 different O365 for business domains?

### ISSUE THREAD

**Issue by jazibobs** [abraunegg/onedrive#756]
Good afternoon, 

Is it possible to synchronise data from 2 different Sharepoint domains?

I have O365 accounts with my work and my university and I would like to be able to synchronise a number of Sharepoint sites from both accounts. Is it currently possible to do this?

Thanks for your help,

Jared

**Comment by abraunegg** [comment]
@jazibobs 
This is possible. Refer to  https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#using-multiple-onedrive-accounts that details using multiple configurations. Each configuration can be a different SharePoint library and have a separate `drive_id` configured.

Essentially, for each config:

* sync_dir is updated for where you want to store your 'OneDrive' folder
* sync_dir is updated for where you want to store your SharePoint Group Drive + specify the Group Drive under drive_id

**Comment by abraunegg** [comment]
Closing issue as question answered
