### ISSUE TITLE
Wrong output of --dry-run when using --no-remote-delete

### ISSUE THREAD

**Issue by AutumnSun1996** [abraunegg/onedrive#758]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
The --no-remote-delete is ignored when preview with --dry-run

**Application and Operating System Details:**
* OS: Ubuntu 16.04.1 (no gui)
* Onedrive version: v2.3.12-5-g217d724
* Account Type: business
* DMD: DMD64 D Compiler v2.089.1
* Using default config

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Creat a file at `~/OneDrive`, see `file-to-delete`
2.  call `onedrive --synchronize`
3.  delete the file locally
4.  call `onedrive --synchronize --upload-only --no-remote-delete --dry-run -v`
Output:
```
...
Processing file-to-delete
The file has been deleted locally
Deleting item from OneDrive: file-to-delete
```

5. In the output of `onedrive --synchronize --upload-only --no-remote-delete -v`, there is
```
...
Processing file-to-delete
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
```
So this seems to be only a problem of --dry-run.

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment]
@AutumnSun1996 
Please can you validate the following PR for your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/759/head:pr759
git checkout pr759
./configure; make clean; make;
```

Below is output when testing this PR:
```
(dmd-2.085.0)[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose --upload-only --no-remote-delete --dry-run
Using Config Dir: /home/alex/.config/onedrive-personal/
DRY-RUN Configured. Output below shows what 'would' have occurred.
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.12-5-g217d724
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709103
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Processing root
The directory has not changed
Processing file-to-delete
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Uploading new items of .
(dmd-2.085.0)[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose --upload-only --no-remote-delete
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.12-5-g217d724
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709103
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Processing root
The directory has not changed
Processing file-to-delete
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Uploading new items of .
(dmd-2.085.0)[alex@centos7full onedrive]$ 
```

**Comment by AutumnSun1996** [comment]
It works as expected now. Thanks for your work.

**Comment by abraunegg** [comment]
@AutumnSun1996 
Thanks for the confirmation.

Closing issue as PR #759 is merged into master
