### ISSUE TITLE
Delete local files after sync

### ISSUE THREAD

**Issue by victoriusnet** [abraunegg/onedrive#763]
Hi!

I'm using the client with arguments "onedrive --synchronize --upload-only". 

What is the best way to clean up the local files after successful upload?

This might be a feature request but if any simple solution exists I would appreciate your help!

Thank you!

**Comment by abraunegg** [comment]
@victoriusnet 
> What is the best way to clean up the local files after successful upload?

The best way currently is for you to delete the files manually after you have uploaded them.

> This might be a feature request but if any simple solution exists I would appreciate your help!

Will add this to the backlog for something to look at in the future.

**Comment by abraunegg** [comment]
@victoriusnet 
Please can you test the following PR for your scenario:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/767/head:pr767
git checkout pr767
./configure; make clean; make;
```

To remove source files after upload, use `--remove-source-files` or configure the correct option in the updated 'config' file

**Example:**
```
./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --upload-only --remove-source-files --no-remote-delete --verbose
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.13-6-g38aa7f0
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709100
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Processing root
The directory has not changed
Processing file1.txt
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Uploading new items of .
Uploading new file ./file2.txt ... done.
Removing local file as --upload-only & --remove-source-files configured
Remaining free space on OneDrive: 5368709083
```

**Comment by abraunegg** [comment]
@victoriusnet 
Any update on testing this PR ?

**Comment by abraunegg** [comment]
@victoriusnet
Any update on testing this PR ?

**Comment by abraunegg** [comment]
Closing issue as PR #767 implemented
