### ISSUE TITLE
Exception thrown when local disk is full

### ISSUE THREAD

**Issue by dleslie** [abraunegg/onedrive#77]
### Bug Report Details ###
**Exception thrown when local disk is full**
When the disk fills the following exception is thrown:
```
Jul 21 08:54:32 dleslie-ThinkPad-X140e onedrive[7651]: sqlite.SqliteException@src/sqlite.d(77): unable to open database file
Jul 21 08:54:32 dleslie-ThinkPad-X140e onedrive[7651]: ----------------
Jul 21 08:54:32 dleslie-ThinkPad-X140e onedrive[7651]: ??:? int sqlite.Database.getVersion() [0x14857181]
Jul 21 08:54:32 dleslie-ThinkPad-X140e onedrive[7651]: ??:? itemdb.ItemDatabase itemdb.ItemDatabase.__ctor(const(char)[]) [0x1483b6e0]
Jul 21 08:54:32 dleslie-ThinkPad-X140e onedrive[7651]: ??:? _Dmain [0x14840a6c]
Jul 21 08:54:32 dleslie-ThinkPad-X140e systemd[2236]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
Jul 21 08:54:32 dleslie-ThinkPad-X140e systemd[2236]: onedrive.service: Failed with result 'exit-code'.
Jul 21 08:54:35 dleslie-ThinkPad-X140e systemd[2236]: onedrive.service: Service hold-off time over, scheduling restart.
Jul 21 08:54:35 dleslie-ThinkPad-X140e systemd[2236]: onedrive.service: Scheduled restart job, restart counter is at 2809.
```

**Application and Operating System Details:**
 - OS: Linux dleslie-ThinkPad-X140e 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Application version: v1.1.2-37-g4667eca

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. Launch onedrive service
2. Fill the disk while the service is syncing
3. See exception.

**Comment by abraunegg** [comment]
Thanks for the bug report. Will into this issue and resolve to better handle the case of the local disk being full - it should exit gracefully rather than crash,

Additionally, your not running the latest version of the client which contains a number of fixes since the v1.1.2 release.

**Comment by abraunegg** [comment]
@dleslie 
Can you please help validate PR #80 to resolve your issue please:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/80/head:pr80
git checkout pr80
make
make install
```

**Comment by abraunegg** [comment]
@dleslie 
Can you provide an update here as if your able to test the fix for your issue?

**Comment by abraunegg** [comment]
@dleslie
Can you provide an update here as if your able to test the fix for your issue?

**Comment by abraunegg** [comment]
Closed due to zero response from @dleslie 

Will merge PR as local testing validated fix & code reviewed.

**Comment by dleslie** [comment]
Yep, I believe this works now. Thanks! :+1:
