### ISSUE TITLE
best setup for automated operation

### ISSUE THREAD

**Issue by oscarrdz1977** [abraunegg/onedrive#771]
If I run the program as a service, would it continually sync? I want to just leave it running every time I start up so it will sync up automatically as I work. What would be the best setup for that?

**Comment by abraunegg** [comment]
@oscarrdz1977 
> If I run the program as a service, would it continually sync? I want to just leave it running every time I start up so it will sync up automatically as I work. What would be the best setup for that?

This is what `--monitor` mode is designed for combined with running the application as a service. Refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#running-onedrive-in-monitor-mode for more information.

**Comment by abraunegg** [comment]
Closing issue as question answered
