### ISSUE TITLE
New client website launched

### ISSUE THREAD

**Issue by abraunegg** [abraunegg/onedrive#772]
Finally had some down time to create a new website for promoting this client:

https://abraunegg.github.io/

Most search engines always return the 'skilion' ones, so it is about time this updated version of the client had some web presence. 

Suggestions, feedback welcome & assistance in getting this URL / website out there - blogged about, listed in forums etc would is greatly appreciated.

**Comment by SRGOM** [comment]
Might I suggest having the URL as https://abraunegg.github.io/onedrive so that power users (you can reasonably expect Linux users, specially of this software to be so) can glance at the URL?

I intend to add this link to the documentation for NixOS package.

**Comment by abraunegg** [comment]
> Might I suggest having the URL as https://abraunegg.github.io/onedrive so that power users (you can reasonably expect Linux users, specially of this software to be so) can glance at the URL? Basically having a "onedrive" somewhere in the URL.

This is what I tried to do, however GitHub has changed how these sites are 'created' - for example:

![publish](https://user-images.githubusercontent.com/4956234/72641230-b8c8f000-39bd-11ea-8a65-07b93906d4b5.jpg)

For your suggested URL, this site would have to then be hosted in the /docs directory of this repo, whereas today this contains all of the client documentation - needing then to add a git ignore directive to the /docs folder .. not an ideal solution.

If you can see another way - by all means open to suggestions.

**Comment by SRGOM** [comment]
Probably fine, maybe people would soon associate abraunegg with onedrive :-). I added this link to NixOS distribution documentation. It would render like this- https://github.com/NixOS/nixpkgs/pull/77734#issuecomment-575673456

Would you have any comments on that?

**Comment by Rondom** [comment]
Hmm, maybe you can create a GitHub organisation with a fitting name. This way, you can have [orgname].github.io

**Comment by abraunegg** [comment]
> Probably fine, maybe people would soon associate abraunegg with onedrive :-). I added this link to NixOS distribution documentation. It would render like this- [NixOS/nixpkgs#77734 (comment)](https://github.com/NixOS/nixpkgs/pull/77734#issuecomment-575874225)
> 
> Would you have any comments on that?

@SRGOM 

Thanks for the feedback, commented on the PR as well

**Comment by abraunegg** [comment]
@Rondom 

> Hmm, maybe you can create a GitHub organisation with a fitting name. That way, you can have [orgname].github.io

Something to consider for sure down the track, also ensuring no name / copyright / trademark infringements as well

**Comment by abraunegg** [comment]
@SRGOM 
Can you also suggest / create a PR to update https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#linux-packages with details on NixOS and installing from packages ?

**Comment by SRGOM** [comment]
@abraunegg I will add documentation about the already existing package and the service once the service is approved.

**Comment by SRGOM** [comment]
The PR (on NixOS) is all but rejected so I've gone ahead and added installation instructions here (which still reference the said PR) https://github.com/abraunegg/onedrive/pull/785

**Comment by abraunegg** [comment]
Closing issue as no longer need to have this open
