### ISSUE TITLE
ERROR: inotify_add_watch failed, The user limit on the total number of inotify watches has been reached

### ISSUE THREAD

**Issue by fmoledina** [abraunegg/onedrive#781]
### Bug Report Details ###
**Describe the bug**
Docker setup using `driveone/onedrive` from Dockerhub. I run 4 instances of this Docker container, 3 Office365 Corporate accounts and 1 for a personal Microsoft account. This error is comes up on both account types.

The error: cannot sync with OneDrive, multiple repeated errors for various files and folders exactly as below:

```
onedrive-personal    | 2020-01-21T02:52:11.088760561Z ERROR: inotify_add_watch failed: ./Documents/Computers/MD1000  
onedrive-personal    | 2020-01-21T02:52:11.088865914Z The user limit on the total number of inotify watches has been reached.
onedrive-personal    | 2020-01-21T02:52:11.088917623Z To see the current max number of watches run:
onedrive-personal    | 2020-01-21T02:52:11.088953347Z sysctl fs.inotify.max_user_watches
onedrive-personal    | 2020-01-21T02:52:11.088986435Z To change the current max number of watches to 524288 run:
onedrive-personal    | 2020-01-21T02:52:11.089021336Z sudo sysctl fs.inotify.max_user_watches=524288
```

Running the recommended `sysctl` command inside the container results in the following output:

```
$ docker exec -it onedrive-personal /bin/bash
[root@f9c7933d5149 /]# sysctl fs.inotify.max_user_watches
fs.inotify.max_user_watches = 8192
```

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc): `Linux caprica 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed? No GUI
*   OneDrive Account Type: Personal (i.e. Microsoft account) and Office365
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`: Not installed, using Docker.
*   Application configuration: Output of `onedrive --display-config`: Not installed, using Docker.
*   Curl Version: Output of `curl --version`

```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au: Not applicable, using Docker.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Use `driveone/onedrive` Docker container to connect to OneDrive.
2.  Make a change on the remote OneDrive using a different computer.
3.  After the Docker detects the change and tries to sync the new changes, the above error message comes up referring to the changed files/dirs.

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Not applicable, using Docker.

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

Not applicable, using Docker.

**Screenshots**

Console output is above.

**Additional context**

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output

**Comment by abraunegg** [comment]
@fmoledina 
This is not a bug or issue. You need to update your environment to support a great amount of file system watches. In your details above, you have determined what your current value is, but you are not setting a new value.

To set a new value you need to:
```
sysctl fs.inotify.max_user_watches=524288
```

for each Docker environment you are running.

**Comment by fmoledina** [comment]
Ah, understood, that command should be run on the host. I'll try that right now, thanks.

**Comment by fmoledina** [comment]
@abraunegg, thanks for the prompt response. It's a local issue that's resolved by the (very helpful) command right in the console output. Fixed on my host, and the error appears to have gone. I've been running these 4 containers for a few months and I don't believe I'd set the `fs.inotify.max_user_watches` specifically before, so I don't know what changed on my side. In any case, this is _not_ an issue for this project. Thanks.
