### ISSUE TITLE
curl: (28) on dlang

### ISSUE THREAD

**Issue by Keruberne** [abraunegg/onedrive#784]
Hi
On Centos 8 i get curl: (28) Resolving timed out after 5000 milliseconds when running curl -fsS https://dlang.org/install.sh | bash -s dmd
Same with Fedora 31

Don't know how to get past that.

**Comment by Keruberne** [comment]
Work around i downloaded the rpm file and installed that.

**Comment by abraunegg** [comment]
@Keruberne 
Most likely this would have been due to the firewall rules on the local system or a proxy server being configured for yum / dnf but not system wide so items like curl can utilise. Will investigate further in the next few days.
