### ISSUE TITLE
Log files are created with name "unknown.onedrive.log"

### ISSUE THREAD

**Issue by tyger** [abraunegg/onedrive#786]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Log files are created with name "unknown.onedrive.log"**

**Application and Operating System Details:**
*   OS: `Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux; Raspbian GNU/Linux 10 (buster)`
*   Using headless version of raspberry and application
*   OneDrive Account Type: Personal
*   LDC: 
```
LDC - the LLVM D compiler (1.16.0):
  based on DMD v2.086.1 and LLVM 7.0.0
  built with LDC - the LLVM D compiler (1.16.0)
  Default target: arm-unknown-linux-gnueabihf
  Host CPU: cortex-a72
  http://dlang.org - http://wiki.dlang.org/LDC

  Registered Targets:
    arm     - ARM
    armeb   - ARM (big endian)
    thumb   - Thumb
    thumbeb - Thumb (big endian)
    wasm32  - WebAssembly 32-bit
    wasm64  - WebAssembly 64-bit
```
*   Application configuration: 
```
$ onedrive --display-config
onedrive version                       = v2.3.13-7-gb81b969
Config path                            = /var/lib/onedrive/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /srv/dev-disk-by-label-ExtDrive/personal/dtyger/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = true
Config option 'skip_symlinks'          = true
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```
*   Curl Version: 
```
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  There is not special steps as such...
2.  Configure application to write logs to some folder, I use `/var/log/onedrive`
3.  Start app
4.  Log-file is created with strange name

^ This was reproduced with two different users

**Complete Verbose Log Output**

Application Log Output:
```bash
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /var/lib/onedrive
[DEBUG] configDirName: CLI override to set configDirName to: /var/lib/onedrive/.config/onedrive
Using Config Dir: /var/lib/onedrive/.config/onedrive
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] syncDir: /srv/dev-disk-by-label-ExtDrive/personal/dtyger/OneDrive
Using logfile dir: /var/log/onedrive/onedrive/
[DEBUG] Process ID: B6C98AC4
[DEBUG] User UID:   116
[DEBUG] User GID:   122
[DEBUG] User Name:  onedrive
Initializing the OneDrive API ...
[DEBUG] Downgrading all HTTP operations to HTTP/1.1 by default
Opening the item database ...
[DEBUG] Using database file: /var/lib/onedrive/.config/onedrive/items.sqlite3
All operations will be performed in: /srv/dev-disk-by-label-ExtDrive/personal/dtyger/OneDrive
[DEBUG] Configuring skip_dir ...
[DEBUG] skip_dir: 
[DEBUG] Configuring skip_file ...
[DEBUG] skip_file: ~*|.~*|*.tmp
[DEBUG] OneDrive Account Details:      {}
[DEBUG] OneDrive Account Root Details: {}
Application version: v2.3.13-15-g0ac8866
Account Type: personal
Default Drive ID: 4e64c9b
Default Root ID: 4E64C9B
Remaining Free Space: 983840345260
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 4E64C9B
[DEBUG] OneDrive Path Details: {}
[DEBUG] Item details returned no parent reference path
[DEBUG] Sync Folder Name:        root
[DEBUG] Sync Folder Parent Path: 
[DEBUG] Sync Folder Actual Path: 
[DEBUG] OneDrive Reported no delta changes - Local path and OneDrive in-sync
Uploading differences of .
Processing root
The directory has not changed
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [*] Detailed description
*   [*] Reproduction steps (if applicable)
*   [*] Verbose Log Output

**Comment by abraunegg** [comment]
@tyger 
Whilst this is not an 'execution bug' you have not complied with the requirements to submitting an issue as detailed here: https://github.com/abraunegg/onedrive#reporting-issues

Specifically - issue raised without using the issue template, not providing a debug log of the problem at hand.

Please update your post above with the required details.

Now - specifically to your problem. The reason why the log file is prepended with 'unknown' is that the user mapping is not working or cannot determine the current user based on the user UID.

So ... to assist with that, see the above request for details.

Secondly, I will create a debug PR, so that this will generate further information needed to understand what is going on when looking up the UID on your system, and potentially why this is failing.

**Comment by abraunegg** [comment]
@tyger 
Please can you use this PR when creating the debug log as this will provide additional details as to the UID mapping process:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/787/head:pr787
git checkout pr787
./configure; make clean; make;
```

**Comment by tyger** [comment]
Will provide debug log shortly.

**Comment by abraunegg** [comment]
@tyger 
I have been looking at this issue a little closer this morning, and updated the PR as there could be issues where the current process fails .. 

Can you please rebuild your client with the latest version of the PR detailed above and advise the outcome.

**Comment by abraunegg** [comment]
@tyger 
Any update from you?

**Comment by tyger** [comment]
@abraunegg 
Hi, sorry for delay. 
Surprisingly after building and installing code from the brunch above problem is gone - logs are written into correct file if app from terminal and as a service.
Still adding verbose logging (stripping sensitive data).
It seems that you've fixed it when was adding more logs :)

**Comment by abraunegg** [comment]
@tyger 
Thanks for the feedback - will mark this as fixed and merge the PR

**Comment by abraunegg** [comment]
Closing issue as PR merged into 'master'
