### ISSUE TITLE
Feature request: Detect when sync-folder is missing

### ISSUE THREAD

**Issue by droberg** [abraunegg/onedrive#8]
I would like a feature that detects whether the local sync-root is missing (i.e. not mounted or wrongly configured) before going ahead with synch. 

I have my onedrive root directory on an external drive. Sometimes I forget to mount my external drive and start onedrive by mistake. From what I have seen, onedrive will then detect that all files in the root directory are missing and will remove them from the online storage.

If I had removed everything from my storage, excluding the onedrive root dir I agree that this would be the correct way to act. However, because in my case the folder that act as the root is also missing I think it would be better to assume that something is horribly wrong and warn the user.

**Comment by abraunegg** [comment]
When you run 'onedrive' what is your 'syncdir' ? Is it the standard / normal '~/OneDrive' ?

Can you help to provide some file system details of your mounts / configuration so I can work out the right approach here

**Comment by abraunegg** [comment]
@droberg 
Any chance of providing the information requested?

**Comment by droberg** [comment]
Thanks for the reminder. 
I didn't forget but I wanted to give you a good answer and I have just been busy.

To answer you direct question: 
No, I am not using ~OneDrive, I use ~/Projects/XXX and ~/Project/YYY 

This is my setup: 
I manage 3 drives, and they are on a hardware encrypted disk so I need to unlock them using a special SCSI com-tool (that I forgot the name of right now). I cooked up a bash script that is triggered by login so that it has the login-key from kwallet. It is then running in a Xterm window that works like follows: 

1) Loop and check for drive with correct "footprint" in dmesg (Western Digital something something)
2) Get the drive device number info from dmesg
3) Request sudo pass for future use
4) Get password from kwallet or user 
5) Pass scsi commands to unlock disk 
6) Wait for new devices to show up, mount drives if not automounted
7) Make sure they are mounted and if so
 a) cd into to the drive (to make sure it cannot be unmounted until the sync-window is closed)
 b) start 3 instances of onedrived with different config files and different onedrive-id's

The 7b) part looks like follows: 
 "onedrive --confdir ~/.config/onedrive.xxx -m  2>&1 | tee --append /home/user/.config/onedrive/syncLogXXX.log &"
Exept for the third entry that does not end with an "&"

This way all three sync daemons live in the same xterm-window and will keep living (and blocking umount) until i close the window. The only issue I currently have with this setup is that I have the xterm window open in the background and cannot hide it as a notification icon or similar.

**Comment by abraunegg** [comment]
Thanks for the information. Is this just one physical disk (with 3 partitions) or say 3 different encrypted USB drives?

When you mount them (step 6) what is `mount` showing?

What I am thinking here is an option to check the filesystem mounts for that entry:

```
onedrive --check-mount /dev/sdb1
```

The other alternative is to have a . file as a flag that is not replicated to OneDrive - say having a file called `.mounted` on the unencrypted filesystem root & then:

```
onedrive --check-mount
```

This way - if the . file is not present, or the mount itself is not present - stop & no sync.

I dont see an easier way to handle this for you.

**Comment by droberg** [comment]
It happens to be the same physical disk for this case, two sync dirs on one partition and one syncdir on another.

E.g.: 
/dev/sdb1 -> /home/user/Projects/Disk1
/dev/sdb2 -> /home/user/Projects/Disk2

SyncDirs are
* /home/user/Projects/Disk1/Dir1
* /home/user/Projects/Disk1/Dir2
* /home/user/Projects/Disk2/Dir1

Not to what mount outputs: 
Mount sometimes output an error and sometimes not. I could specify exactly what is says but I don't have it available right now. The reason for my troubles is  automatic mounting of external drives. I guess I could reconfigure my system to disable auto-mounting of external drives but I don't really want to. My issue is that sometimes the auto-mount (either systemd or KDE's responsibility, havent checked this) is quicker than my script and sometimes my script is quicker than the automount. 

Right now, I'm using the fact that if I can cd into the dir, it exists and mount succeded since
/home/user/Projects/Disk1/Dir1 doesn't even exist if the mount failed. 

My suggestion for a solution would be:
1) If the sync-dir does not even exist, don't sync (unless specified "--force" or similar)
2) If "--check mount" is given, check for file as per your suggestion (or  no file as suggested below). 

As for the suggested solution, I agree that using  an empty ".mounted" file as an indicator  would be a good solution. Perhaps as an alternative the mount location could contain an empty  ".nosync" which would be made invisible when the new drive is mounted.

**Comment by abraunegg** [comment]
> If the sync-dir does not even exist, don't sync (unless specified "--force" or similar)

This is why I introduced the --synchronize flag - without it, no sync is performed.

> Perhaps as an alternative the mount location could contain an empty ".nosync" which would be made invisible when the new drive is mounted.

I think this is the right resolution - having a dot file in the mount point as it will be 'hidden' when the mount is actually active.

Will work on this once I have got #2 and #11 closed and resolved (in progress)

**Comment by abraunegg** [comment]
Hi,

Can you help validate https://github.com/abraunegg/onedrive/pull/28 against your request

**Comment by droberg** [comment]
Thanks, 
I will try it as soon as possible

**Comment by abraunegg** [comment]
Any update on testing the changes in #28?

**Comment by droberg** [comment]
No, I haven't had time to test this yet because of my current workload. Due to the nature of the patch I thought that I should make sure to have a decent backup before engaging in this. 

Hopefully I finish of some other critical tasks before the end of the day so that I can try this out.

**Comment by droberg** [comment]
So, I did some tests today...

I only did one test, because it kinda failed and I had to restore files from Recycle bin

The first time I tried it it deleted all the files, and I think this is what I did:
(I had to redo it to document it but now I cant make it happen again)

1) "Forget" to mount drives
2) Cmd line : "onedrive --confdir ~/.config/onedrive -m -v"
( onedrive config file contains "snc_dir = "~/xxxx/Personal" )
Result: 
---------------------------
Loading config ...
Using Config Dir: /xxx/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/xxx/Personal
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: xxx
Default Root ID: yyy
Remaining Free Space: 1099238513147
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing monitor ...
Monitor directory: .
.... (time passes)
.... (time passes)
.... (time passes)
Applying changes of Path ID: xxxx
This item is marked for deletion:
This item is marked for deletion:
This item is marked for deletion:
This item is marked for deletion:
This item is marked for deletion:
This item is marked for deletion:
This item is marked for deletion:
... (repeating)
... (repeating)
... (repeating)
... (repeating) (forever as it seems)
------------------
Nothing is deleted at this point... 
3) Mount drive while onedrive is running, everything seems ok this time

The thing is, now I cant make it stop saying that "This item is marked for deletion"

**Comment by abraunegg** [comment]
It sounds like 2 things:

1. You potentially did not clone the right code and build that, then use the specific new flag to check for the .nosync file

2. To clear the db state, delete or move the items.* file out of the config directory

**Comment by droberg** [comment]
I know I messed up. I wanted to verify some functionality before trying your check-mount...
Removing the databases did the trick.

I'm testing the code right now.

**Comment by droberg** [comment]
I can confirm that the "--check-mount" works as intended. I'm not completely comfortable with the name though, it feels like it can give the user the wrong impression but I cannot come up with anything better.

**Comment by abraunegg** [comment]
How about renaming the option to '--check-for-nomount' as this is exactly what the option does?

**Comment by droberg** [comment]
Yes, that would do it.

Thanks
Per

**Comment by abraunegg** [comment]
OK - feature request is merged into master
