### ISSUE TITLE
How to Enable notify?

### ISSUE THREAD

**Issue by flaviusbuffon** [abraunegg/onedrive#805]
after installing
i don't know 
why don't have notify when download file from my onedrive

**Comment by abraunegg** [comment]
@flaviusbuffon 

Have you followed the instructions to enable:
* Installed the applicable dependencies?
* Configured the correct build options at compile time?

If you have done this, please follow the directions as per https://github.com/abraunegg/onedrive#reporting-issues and update your first post with all the correct details & provide a verbose debug log showing the issue.

**Comment by abraunegg** [comment]
@flaviusbuffon 

Please can you respond

**Comment by flaviusbuffon** [comment]
i will try again thank 
we can caht with email or skype

**Comment by abraunegg** [comment]
@flaviusbuffon 
Please can you provide an update as to your progress in following the build instructions to enable notifications.

**Comment by flaviusbuffon** [comment]
No any problem!
Thanks
live:jczhang-for-country
this is my skepe id
please add me!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by abraunegg** [comment]
@flaviusbuffon 
I am sorry - I am unable to provide or support you in that way.

Please follow the directions as per https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md to install and configure the application for your OS

**Comment by abraunegg** [comment]
Closing issue as a question as details provided on how to enable notifications.
