### ISSUE TITLE
Fast status query option

### ISSUE THREAD

**Issue by macdems** [abraunegg/onedrive#806]
Thank you for the great program.

It would be very useful if it provided a command-line option to quickly query status of the all the files in specified path. For regular files it should report if the file is up to date, should be uploaded or it is ignored. For directories it should report if any uploads or downloads (optionally, as it requires net access) are waiting there.

Such option would allow to easily write file-manager plugins showing the current status of current directory as emblems (like e.g. official client for Dropbox).

**Comment by abraunegg** [comment]
@macdems 
This is already available - refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#all-available-commands

**Comment by abraunegg** [comment]
Closing issue as question answered
