### ISSUE TITLE
Question: Any way to start the service without logging in ?

### ISSUE THREAD

**Issue by Rathna-K** [abraunegg/onedrive#807]
as the question suggests, right now I am running it as systemd --user service as per documentation but it only starts after I login to a headless unit thru putty first. anyway to start the service without logging in? 
I tried enabling global option in systemd and this is what the error i am getting 

```
$ systemctl --global enable onedrive
Failed to enable unit, file /etc/systemd/user/default.target.wants/onedrive.service: No such file or directory.
```

**Comment by abraunegg** [comment]
@Rathna-K 
You potentially need to re-read the documentation. Refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-a-non-root-user-via-systemd-without-notifications-or-gui

**Comment by Rathna-K** [comment]
my bad, thanks for pointing me to that. one last question, is there a way to auto delete after upload in upload-only mode?

**Comment by abraunegg** [comment]
@Rathna-K 
This is possible. Please refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#all-available-commands

**Comment by Rathna-K** [comment]
Wow this is one of the most comprehensively thought out project in github :)

**Comment by abraunegg** [comment]
Closing issue as question answered
