### ISSUE TITLE
Skip depth-independent directory

### ISSUE THREAD

**Issue by linchangyi** [abraunegg/onedrive#810]
Is it possible to add a configuration  like `skip_dir="**/target"`,  in order to skip syncing directories like `a/target` or `a/b/target`? Is this possible currently and could it possibly be implemented?

I kown you can add a ''.nosync'' empty file to any folder to stop sync directories , but my situation is that the `target` folder  would be 
frequently regenerated,  so  I can't  use the `nosync` configuration to meet my needs.

**Comment by abraunegg** [comment]
@linchangyi 

> Is it possible to add a configuration like `skip_dir="**/target"`, in order to skip syncing directories like `a/target` or `a/b/target`? Is this possible currently and could it possibly be implemented?

This is how the client already operates. When `skip_dir` is configured it will skip all relative paths that match 'target'. To implement what you are seeking to do:
```
skip_dir="target"
```

To change this default behavior, use the following:
```
skip_dir_strict_match = "true"
```

This will change the handling of skip_dir to be an explicit match.

Ensure you test your configuration change with `--dry-run` to confirm this is doing what you want.

**Comment by linchangyi** [comment]
Very thanks for your answer ！

**Comment by abraunegg** [comment]
Closing issue as question answered
