### ISSUE TITLE
Colorful log output terminal modification

### ISSUE THREAD

**Issue by zzzdeb** [abraunegg/onedrive#817]
First of all, It is really nice program. Thank you.

**Is your feature request related to a problem? Please describe.**
Looking at colorful logs(lots of) makes life easier for me. Get lots of information from log without really having to read each line. Even though in this specific case it is not that useful, I wanted to offer work around in wiki page or so, for interested people.  

**Describe the solution you'd like**
https://github.com/zzzdeb/dotfiles/blob/master/scripts/tools/onedrive_log
![screenshot-200307-1736-03](https://user-images.githubusercontent.com/22198738/76147304-2da1d780-609b-11ea-89b7-2224da402954.png)

**Comment by abraunegg** [comment]
Thanks for providing this feedback

**Comment by abraunegg** [comment]
Closing this issue tracker as this external enhancement is now referenced in the wiki: https://github.com/abraunegg/onedrive/wiki/External-Enhancements-to-the-OneDrive-Linux-Client
