### ISSUE TITLE
Initial sync runs way too long

### ISSUE THREAD

**Issue by renawi94** [abraunegg/onedrive#818]
### Bug Report Details ###
**Describe the bug**
I synchronize with OneDrive for the first time and in sync_list I have configured only one file as a start.

So I expect onedrive to initially download that file and be quickly done.

But what happens is that onedrive runs for hours (!) outputting (verbose)
"Processing xxx changes"
and
"Skipping item - excluded by sync_list config: xxxxx"
all the time.

It seems for me that on initial sync it is not necessary to process any changes but to just download the current files.
Or, maybe, I have not enough Insights to the OneDrive API?
On the other hand non-MS apps like OneSync for Android are also much faster on initial synch so it has to be possible.

**Application and Operating System Details:**
*   OS: Linux Mint-xfce-VM 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Linux Mint 19.3
*   xfce gui installed
*   OneDrive Account Type: Personal (Office 365)
*   DMD or LDC compiler version: DMD64 D Compiler v2.090.1
*   Application configuration:
``` 
onedrive version                       = v2.3.13-22-g63ce6a7
Config path                            = /home/x/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/x/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = true
sync_list contents:
Documents/other/keepass.kdbx
```
*   Curl Version:
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```
**To Reproduce**
1.  Install onedrive
2. do the activation step
3.  setup a sync_list file with only one file referenced in it
4.  call onedrive --verbose --synchronize
5.  now it runs for hours outputting
"Processing xxx changes"
and
"Skipping item - excluded by sync_list config: xxxxx"
all the time.

**Comment by abraunegg** [comment]
@renawi94 
All of the above sounds 100% normal - mainly because you are using `sync_list`

Please provide a verbose debug log as per directions to this can be analysed to determine if there actually is an issue, or to provide feedback as to your exact situation.

**Comment by renawi94** [comment]
If this sounds normal to you then consider it a feature request instead of a bug report.

**Comment by abraunegg** [comment]
@renawi94 
Please provide a verbose debug log as per directions (https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) to this can be analysed to determine if there actually is an issue, or to provide feedback as to your exact situation.

This is not a feature request.

Because you are using `sync_list` a full scan is needed of all objects in your OneDrive account to determine if any of these 'out of scope' items get moved, via the Web UI 'into your sync_list scope'

This is because the OneDrive API lacks a call to query 'changes' for just a single path or reference item - only the 'whole' OneDrive folder.

If you are 'only' ever syncing a single folder, do not use 'sync_list' - use the `--single-directory` command option.

**Comment by abraunegg** [comment]
@renawi94
Please provide a verbose debug log as per directions (https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) so this can be analysed to determine if there actually is an issue, or to provide feedback as to your exact situation.

**Comment by renawi94** [comment]
Thank you for your quick replies!
May I email the log to support@mynas.com.au that is mentioned in the directions you supplied?
Since it contains some personal data (such as folder names etc.) I would not like to share it as attachment here.

**Comment by abraunegg** [comment]
@renawi94 
That's the correct process as the wiki link

**Comment by renawi94** [comment]
Ok, I sent you the log.
In addition some further questions for better comprehension.

> 
> 
> This is not a feature request.
> 
> Because you are using `sync_list` a full scan is needed of all objects in your OneDrive account to determine if any of these 'out of scope' items get moved, via the Web UI 'into your sync_list scope'
> 
> This is because the OneDrive API lacks a call to query 'changes' for just a single path or reference item - only the 'whole' OneDrive folder.
> 
I still don't get it: why do any changes matter at all if this is the _first sync run_?
I would think that initially you get the current state of the files and then you have to sync changes only from then on.
At the moment it feels like it is initially processing all the changes ever made since I started to use OneDrive years ago.

> 
> If you are 'only' ever syncing a single folder, do not use 'sync_list' - use the `--single-directory` command option.

Thanks for that hint, this may be the pragmatic solution for me.

**Comment by abraunegg** [comment]
@renawi94 
OK .. looking at the logs in more detail, this can be improved to assist with understanding of what is actually occuring.

Please can you test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/819/head:pr819
git checkout pr819
./configure; make clean; make;
```

With this PR, the following should occur for the 1st sync:
```
./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.13-23-ga14fbbf
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 5 OneDrive items to ensure consistent state due to sync_list being used
Skipping item - excluded by sync_list config: random_videos
Skipping item - excluded by sync_list config: random_images
Skipping item - excluded by sync_list config: random_files
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Skipping item - excluded by sync_list config: ./random_files
Skipping item - excluded by sync_list config: ./random_images
Skipping item - excluded by sync_list config: ./random_videos
Applying changes of Path ID: 66D53BE8A5056ECA!101
```
This line will be repeated a number of times:
```
Processing 5 OneDrive items to ensure consistent state due to sync_list being used
```

This line will be different for you - it will be repeated X number of times based on the following:
* Number of items in your OneDrive account divided by ~200 to 250

Once you have done a full sync and let it complete, subsequent sync's will output like this:

```
./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.13-23-ga14fbbf
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Skipping item - excluded by sync_list config: ./random_files
Skipping item - excluded by sync_list config: ./random_images
Skipping item - excluded by sync_list config: ./random_videos
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

Notice the difference here - because all OneDrive objects are now in the database / processed, and that there is now referential data in the local cache database the second sync will not have to 'process' everything as per first time around.

The ONLY change in this PR is the logging output when 'sync_list' is being used:

From
```
Processing 253 changes
```
To
```
Processing 253 OneDrive items to ensure consistent state due to sync_list being used
```

This now clearly articulates what is occurring, clarifying that this is not a 'change' but a OneDrive object that needs to be processed and analysed against your 'rules' based on your configuration (sync_list + any other skip_dir | skip_file etc configuration)

**Comment by abraunegg** [comment]
@renawi94 
Please can you respond in regards to the PR feedback

**Comment by abraunegg** [comment]
Closing issue as PR #819 merged into master
