### ISSUE TITLE
A question of usage.

### ISSUE THREAD

**Issue by Photonico** [abraunegg/onedrive#820]
Hello, 

I'm new in Linux, my OS is Solus with Plasma desktop. 
I downloaded onedrive via eopkg and when run onedrive.
When I input the response uri, the terminal shows that:
```
--synchronize or --monitor missing from your command options or use --help for further assistance
No OneDrive sync will be performed without either of these two arguments being present
```
how to use it correctly?

Sincerely,

**Comment by mussorgsky** [comment]
You need to run it with either `--synchronize` or `--monitor` as an argument. With `--synchronize` it will perform a one time sync and exit and with `--monitor` it will continuously check if there is anything to upload or download and will keep up to date.

**Comment by abraunegg** [comment]
As this question is raised many times, I have created the following PR to help tighten up the messaging in the following scenarios:

* Just authorising the application
* Running the application without the required switches

Please can you help test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/821/head:pr821
git checkout pr821
./configure; make clean; make;
```

**Comment by Photonico** [comment]
> You need to run it with either `--synchronize` or `--monitor` as an argument. With `--synchronize` it will perform a one time sync and exit and with `--monitor` it will continuously check if there is anything to upload or download and will keep up to date.

Thank u for ur help, I can use it now. But i want to know how to change the onedirve file path?

**Comment by abraunegg** [comment]
@Photonico 
Please review the documentation to assist with that.

**Comment by abraunegg** [comment]
Closing issue as PR #821 merged into master
