### ISSUE TITLE
How to update older version to most recent?

### ISSUE THREAD

**Issue by rafinhaa** [abraunegg/onedrive#822]
I had the version:
```
> [root@srv-samba ~]# onedrive --version
> onedrive v2.3.3-11-g20eda60
```
I uninstalled the old version by command
```
> sudo make install
```
I installed the new version through the repo:
```
> Download harbottle-main-release rpm:
> https://harbottle.gitlab.io/harbottle-main/7/x86_64/harbottle-main-release.rpm
> Install harbottle-main-release rpm:
> # rpm -Uvh harbottle-main-release.rpm
> Install onedrive rpm package:
> # yum install onedrive
```
the new version installed
```
> [root@srv-samba ~]# onedrive --version
> onedrive 2.3.13-2
```
But there were some problems
```
> [root@srv-samba ~]# onedrive
>-bash: / usr / local / bin / onedrive: File or directory not found
```

And others like invalid URI...

how do I upgrade without problems?

**Comment by abraunegg** [comment]
@rafinhaa 

There are two options:
1. Open a packaging issue with the package maintainer. Something is 'wrong' with the package. I cannot assist with that.
2. Uninstall the package you have installed via yum (`yum uninstall onedrive`), then ensure that there is no other version still hanging around. Once complete, follow the directions to install and compile the application for your OS.

> And others like invalid URI...

Please follow the correct support procedure as per https://github.com/abraunegg/onedrive#reporting-issues & provide a debug log via email as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

**Comment by liger1978** [comment]
Nowt wrong with the harbottle package afaik. Looks like you have a bad file at `/usr/local/bin/onedrive`. Maybe check it and remove it?

**Comment by rafinhaa** [comment]
I already checked this place, it is empty.

I created a / usr / local / bin / onedrive / onedrive shortcut for it and it worked, but it's not the right one.

I still have connection errors, the next business day I will try to remove the package and compile for my operating system centos7

**Comment by abraunegg** [comment]
@rafinhaa 
Any update on your progress to resolve your installation issue ?

**Comment by rafinhaa** [comment]
Hello, after the manual update, it looks like everything is working.

**Comment by abraunegg** [comment]
@rafinhaa 
Thanks for the confirmation that things are installed and now working as expected

Closing issue as resolved
