### ISSUE TITLE
timeouts from docker

### ISSUE THREAD

**Issue by vigilancetech-com** [abraunegg/onedrive#825]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
When following the instructions in the Docker.md file it times out
**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)

The latest Sabayon Linux: 
Linux belay 5.4.0-sabayon #1 SMP Tue Feb 25 22:46:38 UTC 2020 x86_64 Intel(R) Core(TM)2 Duo CPU T9300 @ 2.50GHz GenuineIntel GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?
no
*   OneDrive Account Type
IDK, personal?

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`

no dmd nor ldmd2 commands onboard (do I need one for docker?)

*   Application configuration: Output of `onedrive --display-config`
n/a (because using docker?)

*   Curl Version: Output of `curl --version`

curl 7.66.0 (x86_64-pc-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.1.1 nghttp2/1.39.2
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL TLS-SRP UnixSockets

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au
n/a (says onedrive command not found)

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Follow the instructions in Docker.md
2.  when you get to the command: 

docker run -it --restart unless-stopped --name onedrive -v onedrive_conf:/onedrive/conf -v "${onedriveDir}:/onedrive/data" driveone/onedrive

Paste the URL given into the browser, go there, log in to onedrive, allow permissions to the app, paste the resultant empty page's URL back into the linux command line, and get the  output/error messages below

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
kevin@belay ~/0work/onedrive $ docker run -it --restart unless-stopped --name onedrive -v onedrive_conf:/onedrive/conf -v "${onedriveDir}:/onedrive/data" driveone/onedrive
++ stat /onedrive/data -c %u
+ : 1000
++ stat /onedrive/data -c %g
+ : 1001
++ getent group 1001
+ odgroup=
+ odgroup=onedrive
+ groupadd onedrive -g 1001
++ getent passwd 1000
+ oduser=
+ oduser=onedrive
+ useradd -m onedrive -u 1000 -g 1001
+ chown onedrive:onedrive /onedrive/ /onedrive/conf
+ ARGS=(--monitor --confdir /onedrive/conf --syncdir /onedrive/data)
+ '[' 0 == 1 ']'
+ '[' 0 == 1 ']'
+ '[' 0 == 1 ']'
+ '[' 0 -gt 0 ']'
+ exec gosu onedrive /usr/local/bin/onedrive --monitor --confdir /onedrive/conf --syncdir /onedrive/data
Cannot connect to Microsoft OneDrive Service
Reason: Couldn't resolve host name on handle 17B85C0
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=M8feafa2d-b928-9060-35cb-1ad13c0dd12f
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17B85C0
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17B85C0
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17B85C0
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17B85C0
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17B85C0
ERROR: Unable to query OneDrive to initialize application
kevin@belay ~/0work/onedrive $ 

```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment]
@vigilancetech-com 
Please validate that you have no firewall blocking HTTPS access from your system or Docker instance.

This is not something I can solve for.

**Comment by abraunegg** [comment]
@vigilancetech-com 
Please can you respond in terms of the question regarding HTTPS being blocked - either a local firewall rule policy or something further up the chain in your local network.

**Comment by abraunegg** [comment]
@vigilancetech-com
Please can you respond

**Comment by abraunegg** [comment]
@vigilancetech-com
Please can you respond

**Comment by abraunegg** [comment]
@vigilancetech-com
Please can you respond

**Comment by abraunegg** [comment]
Closing issue due to lack of response
