### ISSUE TITLE
AADSTS9002313: Invalid request. Request is malformed or invalid.

### ISSUE THREAD

**Issue by zfil** [abraunegg/onedrive#829]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
Cannot authorize anymore the onedrive client.

**Application and Operating System Details:**
*   OS:
`Linux garrus 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
Linux Mint 19.3 (equivalent of Ubuntu 18.04)
*   Are you using a headless system (no gui) or with a gui installed?
gui
*   OneDrive Account Type
Business
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
`dmd --version
DMD64 D Compiler v2.091.0`
*   Application configuration: Output of `onedrive --display-config`
```onedrive --display-config
onedrive version                       = v2.3.13-26-gedd365d
Config path                            = /home/pjandot/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/pjandot/OneDrive
Config option 'skip_dir'               = Attachments|Microsoft Teams Chat Files|Notebooks
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```
*   Curl Version: Output of `curl --version`
```
curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```
**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:

onedrive --synchronize

[debug_output.log](https://github.com/abraunegg/onedrive/files/4358912/debug_output.log)

**Comment by zfil** [comment]
I've actually find the bug in the code:

src/onedrive.d line 228 the regexp is wrong. It should be `(?:[\?&]code=)([\w\d-.]+)`

when I change this onedrive client is working fine again ...

**Comment by abraunegg** [comment]
@zfil 
Many thanks for looking at this and providing a fix. Will validate and update master shortly.

**Comment by abraunegg** [comment]
PR #830 merged into master

**Comment by abraunegg** [comment]
Closing issue as PR merged into master.
