### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by DanielBorgesOliveira** [abraunegg/onedrive#832]
Hi friends,

The program stop working.

This is the output:

> ```
> Initializing monitor ...
> OneDrive monitor interval (seconds): 45
> 
> object.Exception
> @std/file.d(4020): Failed to stat file `./6-SISTEMAS/Openstack-Controller-Conep/etc/iscsi/nodes/iqn.2010-10.org.openstack:volume-e27df71b-998f-42b9-95ed-7b3a6b514e77'
> ----------------
> 
> 
> /opt/dmd2/linux/bin64/../../src/phobos/std/exception.d:515 pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x560c13ececee]
> ??:? pure @safe bool std.exception.enforce!().enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x560c13fa946d]
> ??:? @trusted void std.file.DirEntry._ensureLStatDone() [0x560c13faa57b]
> ??:? @trusted void std.file.DirEntry._ensureStatOrLStatDone() [0x560c13faa479]
> ??:? @property @safe bool std.file.DirEntry.isDir() [0x560c13faa108]
> src/monitor.d:112 void monitor.Monitor.addRecursive(immutable(char)[]) [0x560c13f6b515]
> src/monitor.d:113 void monitor.Monitor.addRecursive(immutable(char)[]) [0x560c13f6b530]
> src/monitor.d:113 void monitor.Monitor.addRecursive(immutable(char)[]) [0x560c13f6b530]
> src/monitor.d:113 void monitor.Monitor.addRecursive(immutable(char)[]) [0x560c13f6b530]
> src/monitor.d:113 void monitor.Monitor.addRecursive(immutable(char)[]) [0x560c13f6b530]
> src/monitor.d:113 void monitor.Monitor.addRecursive(immutable(char)[]) [0x560c13f6b530]
> src/monitor.d:61 void monitor.Monitor.init(config.Config, bool, bool, bool) [0x560c13f6b1f5]
> src/main.d:673 _Dmain [0x560c13f6a37b]
> ```

Can someone help me with this?

Thank you.

**Comment by abraunegg** [comment]
@DanielBorgesOliveira 
Please update your first post above with all the required information when raising an issue as per https://github.com/abraunegg/onedrive#reporting-issues

Critically missing are all the details as required when submitting an issue using the bug issue template.

Please update your post above with the required information. This is why this is asked when submitting a bug report.

**Comment by abraunegg** [comment]
@DanielBorgesOliveira 
Looking at the 'crash details' I am almost 100% certain this is an old code issue - most likely v2.3.9

If this is the case, most likely:
* You are running Ubuntu
* You have installed from a package which is against advice for Ubuntu platforms. You MUST build from source for Ubuntu.

This most likely means that you have not read the following warning listed here: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#linux-packages

**Important:** Distribution packages may be of an older release when compared to the latest release that is [available](https://github.com/abraunegg/onedrive/releases). If a package is out out date, please contact the package maintainer for resolution.

**Comment by abraunegg** [comment]
@DanielBorgesOliveira 
Please can you respond

**Comment by DanielBorgesOliveira** [comment]
Hi @abraunegg,

You are right. The problem was caused because my code was outdated.
I updated the code and compiled again. Now the program is running nice and easy.
Sorry for the delay. I spent the day testing the program and making sure it is running okay.

Sorry for not read the instructions. This will not happen again.

Thank you very much.

**Comment by abraunegg** [comment]
@DanielBorgesOliveira 
No problem - glad this is all resolved. Closing issue as resolved.
