### ISSUE TITLE
Simplify using Onedrive with automaton tools/programmatically 

### ISSUE THREAD

**Issue by rapucha** [abraunegg/onedrive#84]
**User story**
In many DIY, not-so-office applications I just want to save some data to some remote location. I may not want to sync per se, or syncing may be not feasible due to limited local storage. Say I have an RPi with just an SD card, making periodical shots or recording video. Storing that much data locally in order to sync it with the remote may be not what I want in this situation. Simple upload or storing to some mounted location would be preferable. In other words I am talking about a way to use Onedrive storage with some automation. 
This probably could be achieved at some level with sync_dir on the fly manipulation, but it will be really messy.

**Possible solution**
Provide an API of some sort for storing and retrieving data to/from Onedrive. Could be storing/reading a file by its full remote path, or simulating a key-value storage.

**Alternatives**
Mounting OneDrive as a file system will allow saving/reading files using automation tools. This will also allow cases like

**Additionally**
Having streaming capabilities may be beneficial for large files.

**Comment by abraunegg** [comment]
Unless I am reading this incorrectly - your looking for basically a locally mounted WebDAV type solution where anything saved to that local folder is automatically saved / stored on the cloud service - is this correct?

**Comment by rapucha** [comment]
Very interesting tool, thank you. Amount of supported storages is fascinating.

**Comment by abraunegg** [comment]
Given the availability of an alternate tool for your FR - and that really attempting what your looking for would not be technically possible for a quite a while (lots of re-engineering) - can we close this FR?

**Comment by rapucha** [comment]
yes, sure
