### ISSUE TITLE
Remote change discarded - not in --single-directory sync scope

### ISSUE THREAD

**Issue by Blackmorse** [abraunegg/onedrive#840]
Hi.
I'm trying to synchronize only one folder in my OneDrive.
So I have path at local machine: `~/OneDrive/PCfiles/Programming` and trying to synchronize it .
Command
```onedrive --synchronize  --single-directory   'PCfiles/Programming' --verbose ```
results in next output:
```
Using Config Dir: /home/blackmorse/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/blackmorse/OneDrive
Application version: v2.4.0-1-ge1c8186
Account Type: personal
Default Drive ID: 3b6021c8b1c418d3
Default Root ID: 3B6021C8B1C418D3!101
Remaining Free Space: 755988261274
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from this selected path: PCfiles/Programming
Syncing changes from selected OneDrive path ...
Getting path details from OneDrive ...
Applying changes of Path ID: 3B6021C8B1C418D3!230208
Processing 208 changes
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
```
last line repeats endlessly.

What's the problem?

For example `onedrive --synchronize` works perfect (synchronizing all files)

Thanks

**Comment by Blackmorse** [comment]
As I understand from https://github.com/abraunegg/onedrive/issues/428, It related to the fact, that parent directory didn't syncronized. Is there any workarounds?

**Comment by abraunegg** [comment]
@Blackmorse 
This output is 100% normal.

As per your investigations, essentially what is occurring is you have 'changes' or OneDrive objects that have been updated that are outside the sync scope you are forcing with `--single-directory`, thus, when OneDrive sends the change bundle (`Processing 208 changes`) each of those have to be processed for applicability.

The work around for this would be to drop the `--verbose` as this will not output this output when a remote change falls into this category.

**Comment by abraunegg** [comment]
Closing issue as question answered
