### ISSUE TITLE
A database statement execution error occurred: database disk image is malformed

### ISSUE THREAD

**Issue by xueweiya** [abraunegg/onedrive#844]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
*   Are you using a headless system (no gui) or with a gui installed?
*   OneDrive Account Type
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
*   Application configuration: Output of `onedrive --display-config`
*   Curl Version: Output of `curl --version`

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by xueweiya** [comment]
when i did the below 
onedrive --synchronize --verbose --dry-run
i got Using Config Dir: /home/weiya/.config/onedrive
DRY-RUN Configured. Output below shows what 'would' have occurred.
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/weiya/OneDrive
Application version: v2.4.0-1-ge1c8186
Account Type: business
Default Drive ID: b!W3hvAfOAUEiv_ZYb5bCxCgXPqvASj9RBvuxHYvdOkNXm07TeDKflR5xvlVdaeJTV
Default Root ID: 01ZTFIQPV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 5471695891706
Fetching details for OneDrive Root

A database statement execution error occurred: database disk image is malformed

**Comment by abraunegg** [comment]
@xueweiya 
Please fill in all the required information in your first post. This is critically important to assisting you.

> `A database statement execution error occurred: database disk image is malformed`


This error generally means the following:

1. permissions to the database file are wrong
2. you have another 'copy' of the client active at the same time, that uses the same configuration, and the database file cannot be opened

Please can you verify your file permissions & validate how many instances of the client you are running at the same time, using the same configuration.

**Comment by abraunegg** [comment]
Able to replicate by manually editing the database to make it corrupt.

Please can you test the following PR to resolve your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/845/head:pr845
git checkout pr845
./configure; make clean; make;
```

**Comment by xueweiya** [comment]
thanks a lot. it is working now.

**Comment by abraunegg** [comment]
@xueweiya 
Thanks for confirmation - merged #845 into master

**Comment by Spp-** [comment]
I had this issue a couple of minutes ago and found the commit via google. I recompiled and i can also confirm it is solved for me :)

**Comment by abraunegg** [comment]
@Spp- 
You should just need to rebuild 'master', the PR is merged into master.
