### ISSUE TITLE
Skip existing files

### ISSUE THREAD

**Issue by Happyfeet01** [abraunegg/onedrive#847]
Hello,

Is it possible to only upload new files and skipping existing files? I don't want to delete files at a new sync.

**Comment by abraunegg** [comment]
@Happyfeet01 
Please can you explain your use case a little better as it is unclear what you are trying to achieve.

* Existing files locally?
* Existing files on OneDrive?
* What files dont you want to delete - local? OneDrive?

> Is it possible to only upload new files

Yes, the client uploads or downloads new files if found

> and skipping existing files

Existing files in each location will not be downloaded / changed unless they are out of sync

> I don't want to delete files at a new sync.

I do not know what you mean by this. Files are not deleted, unless you specify options to delete, or you remove the file and then sync.

Please review the documentation for further details: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#all-available-commands

**Comment by Happyfeet01** [comment]
Hi,

I found out that there is an option, that no files would delete when a new sync starts. 
This problem is solved.

The last question is how can run this in Background when I lock out of my server? 

STRG+Z and bg & disown works but the sync stops after some time.

**Comment by abraunegg** [comment]
@Happyfeet01 

Please review the documentation for further details:
https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md

Investigate:
* Monitor mode
* init.d or systemd operation

**Comment by abraunegg** [comment]
Closing issue as question answered
