### ISSUE TITLE
How to change the name of OneDrive folder

### ISSUE THREAD

**Issue by mansoorahmedme** [abraunegg/onedrive#857]
Can I change the name of OneDrive folder to something else.

**Comment by mansoorahmedme** [comment]
Is this repo outdated.

**Comment by abraunegg** [comment]
@mansoorahmedme 
This repo is not outdated and is actively maintained.

In regards to your question:

> Can I change the name of OneDrive folder to something else.

Yes you can. Please read the documentation on how to do this: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md

**Comment by mansoorahmedme** [comment]
Thanks

**Comment by abraunegg** [comment]
Closing issue as question answered
