### ISSUE TITLE
Cannot initialize onedrive 2.4.0 on a fresh install

### ISSUE THREAD

**Issue by afettouhi** [abraunegg/onedrive#859]
I am running Arch Linux and I have installed your onedrive client via AUR for the first time (v2.4.0) but it seems to fail for me when I try to run the dry-run. I get this

```
[af@andre ~]$ onedrive --synchronize --verbose --dry-run
Using Config Dir: /home/af/.config/onedrive
No config file found, using application defaults
DRY-RUN Configured. Output below shows what 'would' have occurred.
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/af/OneDrive

ERROR: OneDrive returned a 'HTTP 400 Bad Request' - Cannot Initialize Sync Engine
```

I do not understand why this happens. The initial setup seemed fine.

**Comment by afettouhi** [comment]
[debug_output.log](https://github.com/abraunegg/onedrive/files/4434509/debug_output.log)

**Comment by afettouhi** [comment]
Please ignore this.

**Comment by abraunegg** [comment]
@afettouhi 
Glad you were able to solve this. What was the issue?

**Comment by afettouhi** [comment]
Using a microsoft account that doesn't have onedrive.

**Comment by abraunegg** [comment]
Thanks - if you have more verbose log output, after this line:
```
ERROR: OneDrive returned a 'HTTP 400 Bad Request' - Cannot Initialize Sync Engine
```

It should have also printed the reason for failure .. did you get that ?

**Comment by afettouhi** [comment]
No, that was all of the output I got.

**Comment by abraunegg** [comment]
@afettouhi 
Thanks - the error messaging should be consistent. Will generate a PR for you to test if you are able to.

**Comment by afettouhi** [comment]
Happy to do it. Thanks for making this app avaiable on Linux.

**Comment by abraunegg** [comment]
@afettouhi 
Please can you test the following PR against your account that did not have OneDrive activated:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/860/head:pr860
git checkout pr860
./configure; make clean; make;
```

Whilst I cannot test for that exact scenario myself, I did 'mangle' the URL's to trigger an error when testing this PR. Rather than the generic error message, it should be consistent with the rest of the application - for example:

```
./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 401 (Unauthorized)
  Error Reason:  A HTML response was provided. Use debug logging (--verbose --verbose) to view.

ERROR: Check your configuration as your refresh_token may be empty or invalid. You may need to issue a --logout and re-authorise this client.

```

**Comment by afettouhi** [comment]
OK, I will do that ASAP. Just a question regarding the use of your application. I currently quite a lot of data to sync my OneDrive and a slow internet connection. What happens if I just cancel a sync? Do I have to move it all over again? Is there a clean way to quit a sync?

**Comment by abraunegg** [comment]
@afettouhi 

> OK, I will do that ASAP. Just a question regarding the use of your application. I currently quite a lot of data to sync my OneDrive and a slow internet connection. What happens if I just cancel a sync? Do I have to move it all over again? Is there a clean way to quit a sync?

If you CTRL-C a sync operation, the current in progress will stop. Depending on the sync direction, it will either start downloading / uploading again. Existing files will be unaffected.

**Comment by afettouhi** [comment]
OK, many thanks for the clarification.

**Comment by afettouhi** [comment]
> @afettouhi
> Please can you test the following PR against your account that did not have OneDrive activated:
> 
> ```
> git clone https://github.com/abraunegg/onedrive.git
> cd onedrive
> git fetch origin pull/860/head:pr860
> git checkout pr860
> ./configure; make clean; make;
> ```
> 
> Whilst I cannot test for that exact scenario myself, I did 'mangle' the URL's to trigger an error when testing this PR. Rather than the generic error message, it should be consistent with the rest of the application - for example:
> 
> ```
> ./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose
> Using Config Dir: /home/alex/.config/onedrive-personal/
> Initializing the OneDrive API ...
> Opening the item database ...
> All operations will be performed in: /home/alex/OneDrivePersonal
> 
> ERROR: OneDrive returned an error with the following message:
>   Error Message: HTTP request returned status code 401 (Unauthorized)
>   Error Reason:  A HTML response was provided. Use debug logging (--verbose --verbose) to view.
> 
> ERROR: Check your configuration as your refresh_token may be empty or invalid. You may need to issue a --logout and re-authorise this client.
> ```

I tested the PR as you asked and this is the output I get now
´af@andre-laptop ~/Hentninger/onedrive $ ./onedrive --confdir '~/.config/onedrive/' --synchronize --verbose
Using Config Dir: /home/af/.config/onedrive/
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/af/OneDrive

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  Tenant does not have a SPO license.´

it now correctly mentions that this account doesn't have OneDrive.

**Comment by abraunegg** [comment]
@afettouhi 
Awesome - many thanks for confirming the fix. Will merge this into master

**Comment by abraunegg** [comment]
Closing as PR #860 merged into master
