### ISSUE TITLE
Inotify gives warning for all not readable directories inside of skip dirs or directories starting with dot

### ISSUE THREAD

**Issue by TheOnlyTrueJonathanHeard** [abraunegg/onedrive#864]
### Bug Report Details ###
**Bug Description**
If you run the onedrive client in monitor mode with the option skip-dotfile="true" and having a directory starting with a dot in which a directory exist which is not readable for the client, inotify gives the following warning: 

`WARNING: inotify_add_watch failed - permission denied: ./.hidden/test`

This also occurs with not readable folders inside a skip-dir folder but not for not readable files. This is a problem for me because I am using the onedrive client for monitoring my Home directory and also using the Software "PlayOnLinux". This Software creates a folder .PlayOnLinux in the Home directory in which the software creates a link to the complete linux filesystem. If I run the client as a non-root user there are countless not readable folders for the onedrive client. In this case the client doesn't just give annoying warnings but is also busy for a long period with creating the Warnings and doesn't react on other changes during this time. This can be prevented by starting the client as root but in this case the client doesn't give any notifications (at least in my case. Not sure if this is a system relevant problem). 

**To Reproduce**
1. Activate the option 'skip_dotfiles' in your config file (alternatively specify a skip_dir)
2. Create a directory starting with a dot inside your sync dir (alternatively create a dir specified as skip_dir)
3. Create a directory inside the directory created in the previous step which is not readable for non-root users, e.g.
     ```
     sudo mkdir test
     sudo chmod 600 test
     ```
4. Start the onedrive client as non-root user in monitor mode with the option resync:  `onedrive --monitor --resync`
 
Expected Behavior:
The not readable folder is ignored when starting the onedrive client

Actual Behavior:
Onedrive gives the warning showing above for the non-readable directory created in step 3

**Application configuration**
```
onedrive version                       = v2.4.0-12-g1c555c3
Config path                            = /home/jonathan/.config/onedriveTest
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/jonathan/OneDrive
Config option 'skip_dir'               = skipDir
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = true
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```

**Verbose Log Output**

```
Using Config Dir: /home/jonathan/.config/onedriveTest
Using logfile dir: /var/log/onedrive/
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/jonathan/OneDrive
Application version: v2.4.0-12-g1c555c3
Account Type: personal
Default Drive ID: dc457103bff8ccb6
Default Root ID: DC457103BFF8CCB6!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: DC457103BFF8CCB6!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Skipping item - .file or .folder: ./.hidden
Applying changes of Path ID: DC457103BFF8CCB6!101
Initializing monitor ...
OneDrive monitor interval (seconds): 45
Monitor directory: .
WARNING: inotify_add_watch failed - permission denied: ./.hidden/test
```

**Comment by abraunegg** [comment]
@TheOnlyTrueJonathanHeard 
Strictly this is not a bug. The application is performing normally. An enhancement is needed to not log that the application cannot monitor a directory due to permissions, if that path is in a path that should not me watched.

**Comment by abraunegg** [comment]
@TheOnlyTrueJonathanHeard 
Please can you test this PR against this issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/866/head:pr866
git checkout pr866
./configure; make clean; make;
```

**Comment by TheOnlyTrueJonathanHeard** [comment]
Ok I am happy with that. Thank you
