### ISSUE TITLE
Library libphobos2 not found

### ISSUE THREAD

**Issue by Jogai** [abraunegg/onedrive#869]
**Describe the bug**
`onedrive: error while loading shared libraries: libphobos2-ldc-shared.so.89: cannot open shared object file: No such file or directory`

**Application and Operating System Details:**
*   5.6.2-1-MANJARO #1 SMP PREEMPT Thu Apr 2 11:32:09 UTC 2020 x86_64 GNU/Linux
*   GUI
*   OneDrive Account Type: personal
*   LDC - the LLVM D compiler (1.20.1) + DMD64 D Compiler v2.091.0
*   Cant show Output of `onedrive --display-config`
*   Curl Version: url 7.69.1 (x86_64-pc-linux-gnu)

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  run `onedrive --display-config`
2. See `onedrive: error while loading shared libraries: libphobos2-ldc-shared.so.89: cannot open shared object file: No such file or directory`

Sorry, cant provide more details since this is the only output.

**Comment by abraunegg** [comment]
@Jogai 
Please can you explicitly detail how you installed the application

**Comment by Jogai** [comment]
yay -S

**Comment by abraunegg** [comment]
@Jogai 
OK - you will need to take this up with the packaging maintainer. The package is potentially not pulling in the appropriate dependencies for Manjaro. This is not something I can fix.

If you wish to install and use the application on Manjaro, you may be able follow the applicable directions for Arch Linux to get you going:
* https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-arch-linux
* https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#compilation--installation

**Comment by Jogai** [comment]
Ok, thanks for answering this, and pointing out the dependencies. I'll take it up on aur.

**Comment by Jogai** [comment]
Reinstalling the aur package fixed my problem
