### ISSUE TITLE
Ability to skip symbolic links?

### ISSUE THREAD

**Issue by leifdenby** [abraunegg/onedrive#87]
**Is your feature request related to a problem? Please describe.**
I have quite a lot of large files that I don't want to add to my OneDrive that are stored in a separate disk on my machine. To access the files in my terminal I simple symlink them into directories which contains analysis scripts that I want to sync to OneDrive.

**Describe the solution you'd like**
Ability to simply skip symlinks. Either these would appear as symlinks once synced to OneDrive (although I'm not sure if OneDrive supports "shortcuts" like this?) or otherwise just skipped altogether.

**Describe alternatives you've considered**
The current alternative I use is to skip files with file extension that matches the large files I want to skip, but that doesn't avoid all the other files in the symlinked directories being synced. I could also add every symlinked directory that I don't want to sync to the config file, but this will be quite laborious. Another option would be to support a sort of `.onedriveignore` file with the same syntax as `git`.

**Additional context**
n/a

**Comment by leifdenby** [comment]
I would be happy to contribute development to this myself, but I am unfamiliar with D. If you could point me to the source code which determines which files to sync I could try and add this myself. I had a quick search for "filter" and "skip" in the source code but couldn't find anything.

Also, thank you for keeping this project alive!

**Comment by abraunegg** [comment]
Thanks for the feature request.

The simplest way to achieve this would be, in main.d add a new flag that can be used by sync.d, that if set, the symbolic link is skipped in `private void uploadNewItems`

Line 936 in sync.d currently checks to make sure a symbolic link is valid. What you could do before this iss check if your new flag is set to skip path if it is a symbolic link before the checks validating the path are done.

Line 938 should also read `Skipping item - invalid symbolic link` not `Skipping item - symbolic link` - will have to fix that.

**Comment by abraunegg** [comment]
PR #92 merged which implements this feature

**Comment by leifdenby** [comment]
@abraunegg I just realised that I should really skip symlinked files when using the "monitor" command too. I was thinking of adding adding in similar checks on https://github.com/abraunegg/onedrive/blob/master/src/monitor.d#L65 and https://github.com/abraunegg/onedrive/blob/master/src/monitor.d#L166.

What do you think?

**Comment by abraunegg** [comment]
monitor.d essentially sets up all the inotify flags, however the main code where the changes were made is still run regardless of monitor mode or manual sync. By adding in changes to monitor.d, all that would happen would be no inotify watch be created on a symbolic link. In doing that there could be an 'incremental' performance boost by not adding an inotify watch to a symlink if it is manually going to be excluded during the sync process - so potentially worth doing.
