### ISSUE TITLE
Add openSUSE Package

### ISSUE THREAD

**Issue by SchoolGuy** [abraunegg/onedrive#871]
**Is your feature request related to a problem? Please describe.**
Currently there is no openSUSE Package Repo/Build officially available.

**Describe the solution you'd like**
I'd like a review on: https://build.opensuse.org/package/show/home:SchoolGuy/onedrive

**Describe alternatives you've considered**
Ask the project but then again I can do it myself. See above.

**Additional context**
If the project is fine with my home project build, I would submit against Factory/Tumbleweed and against Leap 15.2. Ignore the unresolved errors, they are unrelated to the build of the package. Important are: openSUSE_Tumbleweed and Leap 15.1 If the project decides to go for it, I would maintain the package for openSUSE

**Comment by abraunegg** [comment]
@SchoolGuy 
No issues in you submitting a package for openSUSE and maintaining it.

However I see issues with your spec file that you are using, and probably this is related to #872 that you have opened. In the spec file you are directing your files to:
```
%attr(0755,root,root) /usr/bin/onedrive
```

Suggest you look at the Fedora spec file as this has the following:
```
%build
%configure
export DFLAGS="%{_d_optflags}"
export PREFIX="%{_prefix}"
make DC=ldmd2 %{?_smp_mflags}

%install
%make_install \
    PREFIX="%{_prefix}"
chmod a-x %{buildroot}/%{_mandir}/man1/%{name}*

%preun
%systemd_user_preun %{name}.service
%systemd_preun %{name}@.service

%files
%doc README.md LICENSE CHANGELOG.md
%{_bindir}/%{name}
%{_userunitdir}/%{name}.service
%{_unitdir}/%{name}@.service
%{_mandir}/man1/%{name}.1.gz
%{_docdir}/%{name}
%config %{_sysconfdir}/logrotate.d/onedrive
```

Most likely your using the spec file included with this repo as a base. That was added way back when I was building this for CentOS 6 locally and probably needs to be updated.

**Comment by abraunegg** [comment]
@SchoolGuy 
Perhaps also have a chat with this openSUSE user who has developed the packages thus far:

https://software.opensuse.org/download.html?project=home%3Abmanojlovic%3Aonedrive&package=onedrive

**Comment by SchoolGuy** [comment]
Thanks for pointing me to this. I will have a chat with him and see if we can push this. It would be sad to not have support for this on openSUSE.

**Comment by SchoolGuy** [comment]
So he is fine with also being a maintainer in Factory and Leap. Which means we have (including me) two maintainers for the openSUSE package. Submission will be done in an hour or so. Hopefully the reviews won't have anything against it.

**Comment by SchoolGuy** [comment]
Request is out in the wild: https://build.opensuse.org/request/show/794526

**Comment by SchoolGuy** [comment]
Sigh. Forgot that we need a devel project first.

**Comment by SchoolGuy** [comment]
Now we have a request against `network`: https://build.opensuse.org/request/show/794528

**Comment by abraunegg** [comment]
@SchoolGuy 
Once the package is updated / accepted within openSUSE, can you please submit a PR to update this section with the relevant details: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#linux-packages

**Comment by SchoolGuy** [comment]
@abraunegg Yes, I will do!

**Comment by SchoolGuy** [comment]
Devel Project got accepted 17 hours ago, we have a package under `network`. Now the request against `openSUSE:Factory` is open.

https://build.opensuse.org/request/show/795665

**Comment by SchoolGuy** [comment]
@abraunegg Can we somehow get around needing to unpack the `bad-file-name.tar.gz`. It seems that the legal check is not working when having this `tar.gz`-file.

Reference: https://build.opensuse.org/request/show/796645#comment-1210700

**Comment by abraunegg** [comment]
@SchoolGuy 
That file is only used by the Travis CI process I use, as part of testing the client based on prior issue cases.

If you have a way in your build process to:
* Ignore /tests
* Delete /tests

Before doing any sort of legal check then do so.

That archive contains 1 single file - a publicly available PDF, where the name contains a '\n'

```
State-of-the-art, challenges, and open issues in the integration of Internet of\nThings and Cloud Computing.pdf
```

**Comment by SchoolGuy** [comment]
@abraunegg Waiting for an answer now from the legal guys.

**Comment by SchoolGuy** [comment]
Things are moving forward.
- They explained on how to exclude that file.
- Also we did not include in the specfile the logrotate config.
I will try to address both things today.

**Comment by SchoolGuy** [comment]
Next request is in the wild: https://build.opensuse.org/request/show/800279

**Comment by abraunegg** [comment]
@SchoolGuy 
Thanks for the update

**Comment by abraunegg** [comment]
@SchoolGuy 
Any update in the package development?

**Comment by SchoolGuy** [comment]
@abraunegg I yesterday pinged a person internally what hinders this from going onwards, I guess because of the SUSE IT transision things which are not critical are moving more slowly. I am very interested in moving things forward but so far there is nothing that I can do to my knowledge to speed up the submission procress...

**Comment by SchoolGuy** [comment]
The person was apparently on leave and now got back in touch with me. Apparently it is stuck in legal and some manual process was not done. I am now in touch with the person responsible for that process. Things are finally moving again it seems.

**Comment by SchoolGuy** [comment]
Sidenote: As long as the license does not change, updates for the package should be done a lot quicker!

**Comment by abraunegg** [comment]
@SchoolGuy 
Thanks for the update. Re licence, no change planned there

**Comment by abraunegg** [comment]
@SchoolGuy
Any update in the package review by SuSE Legal ?

**Comment by SchoolGuy** [comment]
@abraunegg Yes my fix for excluding the bad file went sideways and I wasn't aware of this because no tool checks for it. After checking with people I have a new request: https://build.opensuse.org/request/show/814697

**Comment by SchoolGuy** [comment]
Finally its through legal!

**Comment by abraunegg** [comment]
@SchoolGuy 
Thats great :) Thanks for the update

**Comment by SchoolGuy** [comment]
It is accepted! So I will now prepare the PR which adds the links to the package to the README.

**Comment by msrn** [comment]
It would be great if the official build was to be build with all the  build switches on (notifications and shell completions ). Otherwise thanks for this!

**Comment by abraunegg** [comment]
@SchoolGuy
> It would be great if the official build was to be build with all the build switches on (notifications and shell completions ). Otherwise thanks for this!

Can you look into this + update the client to v2.4.3

**Comment by SchoolGuy** [comment]
@abraunegg Will do on Monday.

**Comment by SchoolGuy** [comment]
I submitted the package also to Leap 15.2: https://build.opensuse.org/request/show/819159
There is a request also in the pipeline for 2.4.3 for TW: https://build.opensuse.org/request/show/819159
