### ISSUE TITLE
Systemd service not working because of wrong ExecStart path

### ISSUE THREAD

**Issue by SchoolGuy** [abraunegg/onedrive#872]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
Onedrive Systemd Service not working on openSUSE because the executable is in `/usr/bin/onedrive `and not `/usr/local/bin/onedrive`.

**Application and Operating System Details:**
*   OS: `5.6.2-1-default` & openSUSE Tumbleweed
*   Are you using a headless system (no gui) or with a gui installed? - openSUSE Tumbleweed with KDE
*   OneDrive Account Type: business
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version` - None as I have built it with the OBS. In the OBS dmd `dmd-2.087.1-1.2` was used.
*   Application configuration: Output of `onedrive --display-config`

````
onedrive version                       = v2.4.0
Config path                            = /home/egotthold/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/egotthold/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
````

*   Curl Version: Output of `curl --version`

````
curl 7.69.1 (x86_64-suse-linux-gnu) libcurl/7.69.1 OpenSSL/1.1.1f-fips zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0
Release-Date: 2020-03-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
````

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Install application on Tumbleweed
2.  Configure the application
3.  `systemctl --user start onedrive`
4.  See error

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
Apr 15 14:33:49 gaming-dg-opensuse-br0.fritz.box systemd[3013]: Started OneDrive Free Client.
Apr 15 14:33:49 gaming-dg-opensuse-br0.fritz.box systemd[12068]: onedrive.service: Failed to execute command: No such file or directory
Apr 15 14:33:49 gaming-dg-opensuse-br0.fritz.box systemd[12068]: onedrive.service: Failed at step EXEC spawning /usr/local/bin/onedrive: No such file or directory
Apr 15 14:33:49 gaming-dg-opensuse-br0.fritz.box systemd[3013]: onedrive.service: Main process exited, code=exited, status=203/EXEC
Apr 15 14:33:49 gaming-dg-opensuse-br0.fritz.box systemd[3013]: onedrive.service: Failed with result 'exit-code'.

```

**Additional context**

A fix would be to change the line `ExecStart=/usr/local/bin/onedrive --monitor` in the service files to `ExecStart=/usr/bin/onedrive --monitor`.

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by norbusan** [comment]
This is a packaging issue and not a problem of here. Please report this to the maintainer of onedrive in openSUSE.

The installation routines here do install into `/usr/local` and thus the systemd service files are correct.

**Comment by abraunegg** [comment]
@SchoolGuy 
The other option here is when you are running `./configure` use the correct directive when configuring the application:
```
./configure --bindir=/usr/local/bin/onedrive
```

This results in:
```
(dmd-2.085.0)[alex@centos7full onedrive]$ ./configure --bindir=/usr/local/bin/onedrive
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.085.0
checking for curl... yes
checking for sqlite... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
(dmd-2.085.0)[alex@centos7full onedrive]$ make clean; make;
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.4.1-dev > version ; \
fi
dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
(dmd-2.085.0)[alex@centos7full onedrive]$ cat contrib/systemd/onedrive.service
[Unit]
Description=OneDrive Free Client
Documentation=https://github.com/abraunegg/onedrive
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/local/bin/onedrive --monitor
Restart=on-failure
RestartSec=3
RestartPreventExitStatus=3

[Install]
WantedBy=default.target
(dmd-2.085.0)[alex@centos7full onedrive]$ cat contrib/systemd/onedrive@.service
[Unit]
Description=OneDrive Free Client for %i
Documentation=https://github.com/abraunegg/onedrive
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/local/bin/onedrive --monitor --confdir=/home/%i/.config/onedrive
User=%i
Group=users
Restart=on-failure
RestartSec=3
RestartPreventExitStatus=3

[Install]
WantedBy=multi-user.target
(dmd-2.085.0)[alex@centos7full onedrive]$ 

```

What options are you passing in at `./configure` time?

**Comment by abraunegg** [comment]
Most likely related to #871 where the spec file being used, specified the installation directory of `/usr/bin/onedrive`

**Comment by SchoolGuy** [comment]
@abraunegg Yes you are right, I tried to use your specfile and the issue you mentioned is indeed linked. I will try to adjust accordingly and then look if we can close this one.

**Comment by SchoolGuy** [comment]
Let's close this as I just packaged it wrong and we have a working package now I think.

**Comment by abraunegg** [comment]
@SchoolGuy 
> @abraunegg Yes you are right, I tried to use your specfile and the issue you mentioned is indeed linked. I will try to adjust accordingly and then look if we can close this one.

FYI PR #873 updated the example spec file and added examples for building on CentOS. It should fix the root cause of this issue.
