### ISSUE TITLE
resync in config

### ISSUE THREAD

**Issue by sezanzeb** [abraunegg/onedrive#874]
**Is your feature request related to a problem? Please describe.**
Adding --resync solved my problem. But I could not add it to the config

```
Unknown key in config file: resync
Configuration file has errors - please check your configuration
```

https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md does not describe resync as being available for the config. Or maybe it is, but the link to https://github.com/abraunegg/onedrive/blob/master/docs/config is dead.

Since I cannot add resync to the config, using the `systemctl --user enable onedrive` service doesn't help me and I need to write my own service which uses `--resync`

**Describe the solution you'd like**
adding `resync = "true"` to `~/.config/onedrive/config` makes `onedrive` do `--resync`

**Describe alternatives you've considered**
writing my own service

thanks. Using onedrive v2.4.0-15-g2a7e48b

**Comment by abraunegg** [comment]
@sezanzeb 
Thanks for the enhancement suggestion and it also seems rather logical that is should be there, but it is not.

Will also update the documentation, as the link should be pointing to the right file

**Comment by sezanzeb** [comment]
cool, thanks a lot!

**Comment by abraunegg** [comment]
@sezanzeb 
Documentation link is fixed

**Comment by abraunegg** [comment]
@sezanzeb 
Please can you test the following PR for resoling your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/875/head:pr875
git checkout pr875
./configure; make clean; make;
```
