### ISSUE TITLE
Limit upload/download speed

### ISSUE THREAD

**Issue by abdellahaski** [abraunegg/onedrive#885]
This might be a feature request but anyway, I need a way to limit the upload speed of the Onedrive sync, is there a way I can achieve this.

**Comment by abraunegg** [comment]
@abdellahaski 
Whilst I appreciate the desire to do this "in application" there are many other alternatives to do this:
* trickle
* iptables
* implement QoS in system, switch, router etc

Please look into some of the above alternatives to provide this capability.

**Comment by abdellahaski** [comment]
Thank you for the fast response.

**Comment by abraunegg** [comment]
PR #1210 implements this feature request

**Comment by abraunegg** [comment]
PR #1210 implements this feature request
