### ISSUE TITLE
MFA re-auth

### ISSUE THREAD

**Issue by fredericsanty** [abraunegg/onedrive#887]
### Bug Report Details ###
If MFA re-auth is necessary, no warning is given when using the onedrive client as a user service (with notification enabled).

**Describe the bug**
When office365 requests a Re-auth, no gui warning is given when using onedrive client as a user service.
Which means that the user doesn't know there is an issue.
After performing a manual logout & login & url-authorize, sync works again.

**Application and Operating System Details:**
*   OS: 
    Linux whatever 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
    Ubuntu 18.04
*   Are you using a headless system (no gui) or with a gui installed? 
Gui
*   OneDrive Account Type: 
Office 365 Business Premium
*   DMD or LDC compiler version: 
DMD64 D Compiler v2.091.0
*   Application configuration:
``` 
onedrive version                       = v2.4.0-5-g50fb2d8
Config path                            = /home/whatever/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/whatever/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```
*   Curl Version: 
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

**To Reproduce**
- Enable mfa with a X-days reauth necessary.
- configure the onedrive client to work as a user service
- When re-auth is necessary, no popup/Warning is mentioned.

**Comment by abraunegg** [comment]
@fredericsanty 
Please can you provide a verbose debug log regarding this issue. I do not have an O365 account to test this with.

**Comment by abraunegg** [comment]
@fredericsanty 
Please can you respond

**Comment by abraunegg** [comment]
@fredericsanty
Please can you respond

**Comment by abraunegg** [comment]
@fredericsanty
Please can you respond

**Comment by abraunegg** [comment]
Closing due to lack of response
