### ISSUE TITLE
Syncing problem: "Requested file to upload is newer than existing file on OneDrive" but it is not true.

### ISSUE THREAD

**Issue by pdelbeato** [abraunegg/onedrive#89]
### Bug Report Details ###
Syncing problem after upgrading OS (from Ubuntu 16.04 LTS to Ubuntu 18.04LTS). After the upgrade, it recognizes local and remote files as not synced: as a result, it uploads again the file ("Requested file to upload is newer than existing file on OneDrive").
I made a little bit of troubleshooting. Problem is to be located in sync.d and linked with 
localFileModifiedTime and remoteFileModifiedTime. The values of these variables are similar but not equal. I inserted a command in sync.d so as to print out the values of those variables. This is a result:

```
localFileModifiedTime: 2008-Dec-08 16:31:45.23825Z
remoteFileModifiedTime: 2008-Dec-08 16:31:45Z
```

So the problem is that now files have seconds with decimals, so they are recognized as newer than the remote files, starting a complete and whole sync from the beginning.
In my opinion, it could be possible to "round" seconds to integer, without causing any kind of problem.

**Application and Operating System Details:**
 - OS: Linux HTPC 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Application version: onedrive v1.1.1-118-g2336118

**To Reproduce**
Not known

**Comment by pdelbeato** [comment]
What about adding the same hack which is in the function `isItemSynced`? I'm talking about this:
`// HACK: reduce time resolution to seconds before comparing`
`...`
`localModifiedTime.fracSecs = Duration.zero;`

**Comment by abraunegg** [comment]
Thanks for reporting this issue.

The values "should" be same. Can you provide the line numbers where you inserted your output from above so I can quickly zero in on where the change needs to be made?

**Comment by pdelbeato** [comment]
Sure!

I'm referring to line 1193 in sync.d. In my fork, I implemented this modification, but I had no time to test at the moment. If you believe, I can give you some feedback in a day or less.

**Comment by abraunegg** [comment]
Thanks - PR #91 created which has the fix for this issue. 

Can you help to validate PR #91 by doing the following:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/80/head:pr91
git checkout pr91
make
make install
```

**Comment by pdelbeato** [comment]
Sure!

In a day or less I will give you my validation.

Thanks.

**Comment by pdelbeato** [comment]
Tested. Everything was good.
