### ISSUE TITLE
AssertError when using --dry-run against Shared Folders and utilising skip_dir

### ISSUE THREAD

**Issue by sisasam** [abraunegg/onedrive#890]
when I run `onedrive --synchronize --resync --verbose --dry-run`
I get an Error saying:
```
> Syncing OneDrive Shared Folder: _some_dir_
> Applying changes of Path ID: EC120421C7A2918A!4301
> Processing 200 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
> core.exception.AssertError@src/itemdb.d(380): Assertion failure
> \----------------
> ??:? _d_assertp [0x55646af8a4ed]
> src/itemdb.d:380 immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0x55646af52ffb]
> src/sync.d:1311 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x55646af769ed]
> src/sync.d:1118 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[], bool) [0x55646af75c42]
> src/sync.d:490 void sync.SyncEngine.applyDifferences(bool) [0x55646af73aeb]
> src/main.d:945 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool, bool) [0x55646af5f47a]
> src/main.d:680 _Dmain [0x55646af5e5a6]
```

it occours always at the same place when it runs, so always running the sync up to a specific file and then crashing, I don't know if it has to do with specific files though.

to my configurations.
I put an _config_ file into _~/.config/onedrive/_ left everything apart from the _skip_dir_ line as a comment though.

> skip_dir = "_some_dir_|...|_some_dir_/_some_inner_dir_"

`onedrive --version`

> onedrive v2.4.0-26-g628c58a

I ran an `git status` as well which returned an 

> everything is up to date

running `onedrive --synchronize --display-config`

shows:
```
> onedrive version                       = v2.4.0-26-g628c58a
> Config path                            = /home/_user_name_/.config/onedrive
> Config file found in config path       = true
> Config option 'check_nosync'           = false
> Config option 'sync_dir'               = /home/_user_name_/OneDrive
> Config option 'skip_dir'               = _some_dir_|...|_some_dir_/_some_inner_dir_
> Config option 'skip_file'              = \~*|.\~*|*.tmp
> Config option 'skip_dotfiles'          = false
> Config option 'skip_symlinks'          = false
> Config option 'monitor_interval'       = 45
> Config option 'min_notify_changes'     = 5
> Config option 'log_dir'                = /var/log/onedrive/
> Config option 'classify_as_big_delete' = 1000
> Config option 'sync_root_files'        = false
> Selective sync configured              = false
> 
```
Im running **Ubuntu 18.04.4 LTS**

**Comment by abraunegg** [comment]
@sisasam 
Please can you provide a verbose debug log via email. Will need to see unredacted output to correlate what is going on here.

Also, in future, please follow the directions as per https://github.com/abraunegg/onedrive#reporting-issues and use the bug report issue template - this is why it exists.

**Comment by sisasam** [comment]
Hey,

since I am not sure, if you recieved this message I am replying in a
different way.

Thanks very much for the help and kind Regards



-------- Forwarded Message --------
Subject: 	GitHub onedrive Issue AssertError #890
Date: 	Fri, 24 Apr 2020 12:32:13 +0200
From: 	Tore <t.arndt94@gmx.de>
To: 	support@mynas.com.au



Hey,

sorry for not following the Bug Report template.

As you asked I am sending you the full verbose log. You may find it in
the attachment.

I have not run a full sync but this is the output for the dry-run.

I'm happy to answer any followup questions and thanks very much for your
quick support.

Kind regards Tore



$ onedrive --synchronize --resync --verbose --dry-run


Using Config Dir: /home/tore/.config/onedrive
DRY-RUN Configured. Output below shows what 'would' have occurred.
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/tore/OneDrive
Application version: v2.4.0-26-g628c58a
Account Type: personal
Default Drive ID: 34344d4df6317fab
Default Root ID: 34344D4DF6317FAB!143
Remaining Free Space: 78477660603
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 34344D4DF6317FAB!143
Processing 211 changes
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder-tore-TravelMate-X349
Processing 203 changes
Skipping item - excluded by skip_dir config match: root:/Bilder-tore-TravelMate-X349
Processing 203 changes
Skipping item - excluded by skip_dir config match: root:/Bilder-tore-TravelMate-X349
Processing 203 changes
Skipping item - excluded by skip_dir config match: root:/Bilder-tore-TravelMate-X349
Processing 216 changes
Skipping item - excluded by skip_dir config match: root:/Share
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
Skipping item - excluded by skip_dir config match: root:/Bilder-tore-TravelMate-X349
Creating directory: Documents/Reflect
Creating directory: 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew
Creating directory: 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/Audios-und-Videos
Downloading file 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/ArbeitenMitOracle.pdf ... done.
Downloading file 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/beleg-richtlinien.pdf ... done.
Creating directory: 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/MySQL
Skipping item - excluded by skip_dir config match: 04SeminarNew/Bilder
Creating directory: 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/Volltext
Downloading file Documents/Bewerbung/Werkstudent/Bewerbung_zum_Werkstudenten_Softwareentwicklung.pdf ... done.
Downloading file Documents/Bewerbung/Praktikum/Bewerbung_zum_Praktikum_im_Bereich_IT_SENEC.pdf ... done.
Downloading file Documents/Bewerbung/Praktikum/Bewerbung_zum_Praktikum_im_Bereich_IT_Procilon.pdf ... done.
Downloading file 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/Audios-und-Videos/audios.zip ... done.
Downloading file 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/Audios-und-Videos/videos.zip ... done.
Downloading file 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/MySQL/film-table.sql ... done.
Downloading file 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/Audios-und-Videos/melodie-konturen.xlsx ... done.
Downloading file 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/Audios-und-Videos/OrdAudioVideo.pdf ... done.
Downloading file 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/Audios-und-Videos/melodie-konturen.pdf ... done.
Downloading file 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/MySQL/mysql-volltext-uebung.fm.pdf ... done.
Downloading file 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/Volltext/Signature-Files-Uebungen.pdf ... done.
Downloading file 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/Volltext/OracleTextThesaurusUebung.pdf ... done.
Downloading file 05Semester_priv/01Multimedia-Datenbanken/04SeminarNew/Volltext/OracleText.pdf ... done.
Processing 244 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
The Microsoft OneNote Notebook './Notizbuch von Tore' is not supported by this client
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: 05Semester_priv/07VR-AR
Creating directory: Books/Uni
Downloading file Books/Uni/Schnellstart-Python.pdf ... done.
Downloading file Books/Uni/Einführung-in-die-Optimierung.pdf ... done.
Downloading file Books/Uni/Netzwerk-und-Datensicherheit.pdf ... done.
Downloading file Books/Uni/Computernetze-Kompakt.pdf ... done.
Downloading file Books/Uni/Python3-Lern-Arbeitsbuch.pdf ... done.
Downloading file Books/Uni/Eine-praktische-Einführung.pdf ... done.
Downloading file Books/Uni/C-als-erste-Programmiersprache.pdf ... done.
Downloading file Books/Uni/ComputerNetworks-Computernetze.pdf ... done.
Downloading file Books/Uni/Signalverarbeitung.pdf ... done.
The local item has a different modified time 2020-Jan-15 08:27:28Z remote is 2020-Jan-15 08:40:58Z
The local item has a different modified time 2020-Jan-15 08:27:28Z remote is 2020-Jan-15 08:41:40Z
Downloading file 03Semester_priv/Rechnernetze/theorie.pdf ... done.
Downloading file 05Semester_priv/04BWL/Skript_WS_2019_17INB_MIB_Stand20190925.pdf ... done.
Downloading file 05Semester_priv/04BWL/loesung_uebung_existenzgruendung_20190925.xls ... done.
Downloading file 05Semester_priv/04BWL/BWL-Prufung-2008.pdf ... done.
Downloading file 05Semester_priv/09Praxisprojekt/Beschluss_Prüfungsausschuss_Anerkennung-von-Tätigkeiten-als-Praxisprojekt.pdf ... done.
Downloading file 05Semester_priv/09Praxisprojekt/Ausbildungsvertrag.pdf ... done.
Downloading file 05Semester_priv/09Praxisprojekt/Antrag_Praxisprojekt.pdf ... done.
Downloading file 05Semester_priv/09Praxisprojekt/Taetigkeitsnachweis.pdf ... done.
The local item has a different modified time 2019-Dec-04 20:27:36Z remote is 2019-Dec-04 20:28:55Z
Downloading file 05Semester_priv/05IT-Sicherheit/01Skripte/itsicher_09_securedesignpatterns.pdf ... done.
The local item has a different modified time 2020-Feb-13 13:54:12Z remote is 2019-Dec-16 13:27:12Z
Skipping item - excluded by skip_dir config match: 03Seminar/Bilder
The local item has a different modified time 2020-Feb-13 13:54:12Z remote is 2019-Dec-16 16:53:52Z
Downloading file Documents/Bewerbung/Praktikum/Bewerbung_zum_Praktikum_MPI.pdf ... done.
The local item has a different modified time 2020-Jan-29 13:00:22Z remote is 2019-Dec-19 05:39:02Z
The local item has a different modified time 2020-Jan-29 13:00:22Z remote is 2019-Dec-19 05:39:52Z
Downloading file 05Semester_priv/06Betriebssysteme/Uebungen/info.html ... done.
The local item has a different modified time 2020-Jan-09 06:37:48Z remote is 2020-Jan-08 20:00:16Z
Downloading file 05Semester_priv/01Multimedia-Datenbanken/01Skripte/7-video-db.ppt ... done.
Downloading file 05Semester_priv/05IT-Sicherheit/01Skripte/itsicher_10_grundschutz.pdf ... done.
Downloading file 05Semester_priv/06Betriebssysteme/Uebungen/uebung_raid.db.pdf ... done.
Downloading file 05Semester_priv/05IT-Sicherheit/01Skripte/itsicher_gesamt.pdf ... done.
Creating directory: 05Semester_priv/04BWL/02Mitschriften/lina
Downloading file Documents/Bewerbung/Praktikum/Bewerbung_zum_Praktikum_Data_Science___Data_Analytics__KPMG_AG_.pdf ... done.
Downloading file 05Semester_priv/01Multimedia-Datenbanken/03Seminar/Audios-und-Videos/melodie-konturen.pdf ... done.
Downloading file 05Semester_priv/04BWL/02Mitschriften/lina/02Woche.pdf ... done.
Downloading file 05Semester_priv/04BWL/02Mitschriften/lina/11Woche.pdf ... done.
Downloading file 05Semester_priv/04BWL/02Mitschriften/lina/05Woche.pdf ... done.
Downloading file 05Semester_priv/04BWL/02Mitschriften/lina/07Woche.pdf ... done.
Downloading file 05Semester_priv/04BWL/02Mitschriften/lina/09Woche.pdf ... done.
Downloading file 05Semester_priv/04BWL/02Mitschriften/lina/04Woche.pdf ... done.
Downloading file 05Semester_priv/04BWL/02Mitschriften/lina/06Woche.pdf ... done.
Downloading file 05Semester_priv/04BWL/02Mitschriften/lina/03Woche.pdf ... done.
Downloading file 05Semester_priv/04BWL/02Mitschriften/lina/10Woche.pdf ... done.
Downloading file 05Semester_priv/04BWL/02Mitschriften/lina/99Woche.pdf ... done.
Downloading file 05Semester_priv/04BWL/02Mitschriften/lina/08Woche.pdf ... done.
Downloading file Documents/Wohnung/Neue Wohnung/Altenburger Str/Untermiete/Samson/07.02.20Anteilskalkulation.ods ... done.
Processing 210 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: 05Semester_priv/07VR-AR
Processing 244 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: 05Semester_priv/07VR-AR
The local item has a different modified time 2019-Nov-26 22:00:26Z remote is 2019-Dec-04 20:33:03Z
Skipping item - excluded by skip_dir config match: 03Seminar/Bilder
The local item has a different modified time 2019-Dec-05 18:17:26Z remote is 2019-Dec-19 16:45:18Z
The local item has a different hash
Remote item modified time is newer based on UTC time conversion
The local item is out-of-sync with OneDrive, renaming to preserve existing file: 05Semester_priv/04BWL/01Skripte/Skript_WS_2019_17INB_MIB_Stand20190925.pdf -> 05Semester_priv/04BWL/01Skripte/Skript_WS_2019_17INB_MIB_Stand20190925-tore-TravelMate-X349.pdf
Downloading file 05Semester_priv/04BWL/01Skripte/Skript_WS_2019_17INB_MIB_Stand20190925.pdf ... done.
The local item has a different modified time 2019-Nov-18 10:56:39Z remote is 2019-Dec-25 21:25:17Z
The local item has a different hash
Remote item modified time is newer based on UTC time conversion
The local item is out-of-sync with OneDrive, renaming to preserve existing file: 05Semester_priv/05IT-Sicherheit/03VortragTore/ATFuzzer.pdf -> 05Semester_priv/05IT-Sicherheit/03VortragTore/ATFuzzer-tore-TravelMate-X349.pdf
Downloading file 05Semester_priv/05IT-Sicherheit/03VortragTore/ATFuzzer.pdf ... done.
Processing 210 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Uni-Acer-TravelMate
Skipping item - excluded by skip_dir config match: root:/Uni-DESKTOP-GHGPVHG
Skipping item - excluded by skip_dir config match: root:/Birthday Pictures
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: 05Semester_priv/07VR-AR
The local item has a different modified time 2020-Feb-13 13:54:12Z remote is 2019-Oct-24 04:08:16Z
The local item has a different modified time 2020-Feb-13 13:54:12Z remote is 2019-Oct-11 13:33:51Z
The local item has a different modified time 2020-Feb-13 13:54:12Z remote is 2019-Oct-11 13:33:51Z
The local item has a different modified time 2020-Feb-13 13:54:12Z remote is 2019-Oct-24 04:07:34Z
Skipping item - excluded by skip_dir config match: 03Seminar/Bilder
Processing 220 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Birthday Pictures
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
Skipping item - excluded by skip_dir config match: Assembler/Share
Processing 214 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 222 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Programme
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: Assembler/Share
Processing 224 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Programme
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
The local item has a different modified time 2019-Feb-24 16:50:33Z remote is 2020-Apr-24 09:00:26Z
The local item has a different modified time 2019-Feb-24 16:49:40Z remote is 2020-Apr-24 09:00:48Z
Processing 215 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Pictures
Processing 213 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Musik
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 216 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
The Microsoft OneNote Notebook './Notizbuch von Tore' is not supported by this client
Skipping item - excluded by skip_dir config match: root:/Programme
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 217 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
The Microsoft OneNote Notebook './Notizbuch von Tore' is not supported by this client
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
The Microsoft OneNote Notebook 'Documents/Wohnungen' is not supported by this client
The Microsoft OneNote Notebook 'Documents/Langzeitarchivierung' is not supported by this client
The Microsoft OneNote Notebook 'Documents/Wohnung/Neue Wohnung/Wohnungen' is not supported by this client
Processing 205 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 203 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 220 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 203 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 206 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 214 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 205 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 206 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 203 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Pictures
Processing 203 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Pictures
Processing 206 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 206 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 206 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 255 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 204 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 205 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 206 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 204 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 204 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 204 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 217 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 215 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 203 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 205 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 209 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 207 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 208 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 211 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 207 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 203 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 219 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 222 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 204 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 203 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 203 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 203 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 205 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 204 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 203 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 203 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 206 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Processing 225 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Bilder
Skipping item - excluded by skip_dir config match: AOP-1/Programme
Processing 227 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Schottland
Skipping item - excluded by skip_dir config match: AOP-1/Programme
Processing 225 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: AOP-1/Programme
Skipping item - excluded by skip_dir config match: Uebung_4/bilder
Skipping item - excluded by skip_dir config match: modul2/bilder
Processing 214 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
The Microsoft OneNote Notebook './Notizbuch von Tore' is not supported by this client
Skipping item - excluded by skip_dir config match: AOP-1/Programme
Processing 209 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
The Microsoft OneNote Notebook './Notizbuch von Tore' is not supported by this client
Skipping item - excluded by skip_dir config match: root:/Pictures
The local item has a different modified time 2017-Jul-09 13:03:10Z remote is 2017-Jul-09 14:36:50Z
The local item has a different modified time 2018-Apr-26 15:06:22Z remote is 2017-Jul-09 14:54:00Z
Processing 204 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Processing 204 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Processing 115 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
Skipping item - excluded by skip_dir config match: root:/Pictures
Skipping item - excluded by skip_dir config match: root:/Bilder
Syncing OneDrive Shared Folder: 05Semester
Applying changes of Path ID: EC120421C7A2918A!4301
Processing 200 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive

core.exception.AssertError@src/itemdb.d(380): Assertion failure
----------------
??:? _d_assertp [0x559e1139f4ed]
src/itemdb.d:380 immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0x559e11367ffb]
src/sync.d:1311 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x559e1138b9ed]
src/sync.d:1118 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[], bool) [0x559e1138ac42]
src/sync.d:490 void sync.SyncEngine.applyDifferences(bool) [0x559e11388aeb]
src/main.d:945 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool, bool) [0x559e1137447a]
src/main.d:680 _Dmain [0x559e113735a6]

######################################################################

$ onedrive --synchronize --display-config


onedrive version                       = v2.4.0-26-g628c58a
Config path                            = /home/tore/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/tore/OneDrive
Config option 'skip_dir'               = Programme|Bilder|Pictures|Musik|Bilder-tore-TravelMate-X349|Birthday Pictures|Schottland|Share|Uni-Acer-TravelMate|Uni-DESKTOP-GHGPVHG|05Semester_priv/07VR-AR
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false

**Comment by abraunegg** [comment]
@sisasam 
Your email and log file received - I only got to it this morning due to my location & timezeone, however the data you have provided is not what was requested

As per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support please generate a Verbose Debug Log

When submitting the verbose debug log, please also include the full command used when the issue occurred.

**Comment by abraunegg** [comment]
@sisasam 
Thanks for the verbose debug log.

I have not been able to replicate the issue with Shared Folders - either as a root shared or a sub level shared item - so no crash at all for me, so I am unable to test the below fix.

Please can you test the following PR against your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/891/head:pr891
git checkout pr891
./configure; make clean; make;
```

**Comment by sisasam** [comment]
PR Provided resolved the issue.
