### ISSUE TITLE
Uploading arbitrary directory

### ISSUE THREAD

**Issue by trochdewei** [abraunegg/onedrive#894]
Is it possible to simply upload arbitrary directories or files not from ~/OneDrive?

**Comment by abraunegg** [comment]
@trochdewei 
No this is not possible - files / folders need to be in the configured `sync_dir` location or at least be a symbolic link within the configured `sync_dir` so that they can be found when the client runs

**Comment by abraunegg** [comment]
Closing issue as question answered
