### ISSUE TITLE
"unknown key"  error with using config file..

### ISSUE THREAD

**Issue by Dutchglory** [abraunegg/onedrive#895]
**SYSTEM INFORMATION:**
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-26-generic
OS Type: 64-bit
Processors: 2 × Intel® Core™2 CPU 6700 @ 2.66GHz
Memory: 5,7 GiB
- - - 

**"unknown key"  error with using config file:**
( explained here:  https://www.maketecheasier.com/sync-onedrive-linux/ )  

when using the config file, the following options give "unknown key" error :  
classify_as_big_delete = "1000"
user_agent = ""
remove_source_files = "false"
application_id = ""
skip_dir_strict_match = "false"
resync = "false"

please let me know on what these should be or add information to the manual on how to set options... 

André

**Comment by abraunegg** [comment]
@Dutchglory 
Please refer to this information: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#configuration

This provides the full config file with examples on how to configure the 'config' file.

Secondly - do not use Ubuntu packages to compile the application as suggested on that website, but also more importantly not do use the Ubuntu 'onedrive' package. It is way out of date. If you want to use a Ubuntu package, suggest testing the user provided PPA as detailed here: https://github.com/abraunegg/onedrive/issues/853

Regarding your issue - most likely, you have installed / have installed an older version of the binary somewhere on your system. You need to find it, then remove it, then ensure you build and install the correct version.

As you have not followed the directions as per https://github.com/abraunegg/onedrive#reporting-issues or used the "bug report template" critical information is missing from your first post that would assist helping you further.

**Comment by abraunegg** [comment]
Closing issue as question answered
