### ISSUE TITLE
When using sync_list onedrive --synchronize takes forever to finish

### ISSUE THREAD

**Issue by reinketelaars** [abraunegg/onedrive#896]
This bug was introduced approximately around the time the client had to be re-authorized with OneDrive.
When using a sync_list file to selectively sync certain folders, the client takes forever (after > 24 hours still not finished) to finish. I ran with --verbose and logging. The client doesn't freeze, but keeps producing output like this: 
"Processing 251 OneDrive items to ensure consistent local state due to sync_list being used"
There is about 150 GB in my OneDrive.

onedrive version 2.4.0-26
Debian Buster 10.3
dmd 2.091.0 

**configuration:**
```
onedrive version                       = v2.4.0-26-g628c58a
Config path                            = /home/rein/.config/onedrive_Archief/
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /mnt/raid/
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp|Thumbs.db|Documents/My Webs/varwww
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /home/rein/OneDrive/log/Archief/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = true
sync_list contents:
Archief
```

curl version:  7.64.0

**Comment by dab414** [comment]
Similar situation here! I reinstalled my clients on two different machines both running the latest dev version of Ubuntu. I'm just doing basic `onedrive --synchronize` commands, and the client takes *much* longer than it used to to finish (~15 mins or so). I can post more details if needed, but just wanted to +1 this issue, assuming they're originating from the same source.

**Comment by abraunegg** [comment]
@reinketelaars, @dab414 
In BOTH of your scenarios, can you ensure you edit your post to add the following please:
- [ ] Full command being run or using service files (@dab414 , you are saying normal standalone not needed)
- [ ] Application configuration `--display-config` (@dab414 , you are missing this)
- [ ] Confirmation that you are making zero changes locally or zero changes via OneDrive online

What this sounds like is the code changes for #867 potentially fritzed this up.

What I will need to do is get a PR version, and will need debug logs from you both from that PR version to ensure I am getting the right data from each of your scenarios. 

Are you OK in assisting here to do this?

**Comment by abraunegg** [comment]
@reinketelaars , @dab414 
Please can you use the following PR for your respective use cases:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/898/head:pr898
git checkout pr898
./configure; make clean; make;
```

No need at this stage to do debug logging, either of the following will suffice:
```
onedrive --synchronize --verbose
```
or
```
onedrive --synchronize --verbose
```

The application version (currently) that should be in use is: `onedrive v2.4.0-29-g590bd32`

Example output:
```
Applying changes of Path ID: 66D53BE8A5056ECA!101
syncListConfigured = false
oneDriveFullScanTrigger = false
performFullItemScan = false
performFullItemScan is false, using the deltaLink as per database entry
deltaLink contains valid data - resulting API query will be treated as a delta scan of OneDrive
Uploading differences of .
Processing root
The directory has not changed
Processing random_videos
The directory has not changed
Processing random_files
The directory has not changed
Processing random_images
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
syncListConfigured = false
oneDriveFullScanTrigger = false
performFullItemScan = true
performFullItemScan is true, not using deltaLink to force query of all OneDrive items
Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
syncListConfigured = false
oneDriveFullScanTrigger = false
performFullItemScan = false
performFullItemScan is false, using the deltaLink as per database entry
deltaLink contains valid data - resulting API query will be treated as a delta scan of OneDrive
Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
syncListConfigured = false
oneDriveFullScanTrigger = false
performFullItemScan = false
performFullItemScan is false, using the deltaLink as per database entry
deltaLink contains valid data - resulting API query will be treated as a delta scan of OneDrive
Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
syncListConfigured = false
oneDriveFullScanTrigger = false
performFullItemScan = false
performFullItemScan is false, using the deltaLink as per database entry
deltaLink contains valid data - resulting API query will be treated as a delta scan of OneDrive
Sync with OneDrive is complete
Starting a sync with OneDrive
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
syncListConfigured = false
oneDriveFullScanTrigger = false
performFullItemScan = false
performFullItemScan is false, using the deltaLink as per database entry
deltaLink contains valid data - resulting API query will be treated as a delta scan of OneDrive
Sync with OneDrive is complete
```

**Comment by dab414** [comment]
First, I'm in the `onedrive` directory, and confirming I'm on the correct branch:  
Input:  
`git branch`  
Output:  
```bash
  master
* pr898
```
But, my version seems to be different from what you're suggesting it should be above:  
Input:  
`./onedrive --display-config`  
Output:  
```bash
onedrive version                       = v2.4.0-30-g45635bd
Config path                            = /home/dave/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/dave/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```
*Note, I'm calling the app directly from the directory via dot slash and not the environment variable. simply using `onedrive --display-config` gives me app version `v2.4.0-22-g77b1e4b`, which is still inconsistent with the version you describe above.  

Next, running a verbose sync:  
Input:  
`./onedrive --synchronize --verbose`  
Output:  
```bash
The file has not changed
Processing review.txt
The file has not changed
Processing script.py
The file has not changed
Processing wednesday
The directory has not changed
Processing review.txt
The file has not changed
Processing sampleScript.py
The file has not changed
Processing file.txt
The file has not changed
Processing thursday
The directory has not changed
...
OneDrive Reported no delta changes - Local path and OneDrive in-sync
deltaLink query reports that there are 0 changes that need processing on OneDrive
OneDrive Reported no delta changes - Local path and OneDrive in-sync
deltaLink query reports that there are 0 changes that need processing on OneDrive
```
I'm copying the truncated output here. The app is checking over lots of different files (top), then spamming the bottom string pattern many times. The output is so much that I'm not able to retrace all the way back to the first line of output. The total run time for the sync was 3 min 34 sec (still much longer than the app used to run)---most of this time was spent with the app just sitting on that last `The directory has not changed` line of output before closing and returning me to the terminal. 

I'm a bit inexperienced troubleshooting software via GitHub, so let me know if I can do anything else to make things clear.

**Comment by abraunegg** [comment]
@dab414 

yes you need to run the client with `./` in the front to ensure your running the PR version.

On the version itself - I have been making 'tweaks' to the logging output - so even if you rebuild the client, you will get `onedrive v2.4.0-32-g3100e8c`

So far your doing all the right things above

**Comment by abraunegg** [comment]
@dab414 
Can you provide some insight here for this question:
* When you say the total run time 'before' - how long on average was this taking to sync?
* When running this PR version - ignoring all the debug output - how long is this taking to sync?

Ignoring the PR output - can you:

* run: `time ./onedrive --synchronize --verbose > debug_output.log 2>&1` - that will give an accurate time for the current situation but also send all application output to a log file which can be looked at later.

Secondly, given your configuration, potentially be able to triage this by walking though older PR's - for example, running / testing without any changes that were made:

**Release 2.4.0 / PR 833**
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/833/head:pr833
git checkout pr833
./configure; make clean; make;
```

**my run times**
Master: `real    0m11.905s`
PR 898: `real    0m12.661s` (with extra logging / output)
PR 898: `real    0m12.079s` (without extra logging / output)
PR 833: `real    0m5.397s`

Tracking back all the changes, the only change that was occurred was in the handling of the 'fullScanRequired' flag, to when to perform the full walk of all item objects to ensure a consistent local state. 

In v2.4.0 and prior, this true-up action was always 'false' unless you were using 'sync' list .. which, really .. is not right. This meant that you never did the true-up and potentially missed changes on OneDrive and missed ensuring the system is in correct & true sync. So this is potentially *why* you are seeing things taking longer - because the 'true-up' is now actually occurring.

Now .. important question for you - in v2.4.0 when this was in this 'what I consider to be broken state' - was everything actually in-sync? Did you ever experience any 'issues' data not being in-sync?

**Comment by dab414** [comment]
I was going to suggest going back to a prior commit to time the app and contrast it--awesome that you laid that out for me. I'm about to sign off for the night, but I'll give this all a shot tomorrow and report back. 

Before calling it a night- I can answer your important question, which is: no. As far as I was aware, I had absolutely no issues with data not being in-sync. I would sometimes get conflicts more often than I liked, where the app would create a `myfile-dave-desktop.txt` (for example) in cases where I didn't think a conflict was actually present... but this was relatively infrequent and easily resolved by just deleting the older and unnecessary version of the file.

**Comment by abraunegg** [comment]
@dab414 
When you come to test, please test this 'very specific PR' for your scenario:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/899/head:pr899
git checkout pr899
./configure; make clean; make;
```

**Comment by reinketelaars** [comment]
I am on PR 898. onedrive v2.4.0-33-g371ba49
Problem looks the same. It looks like an initial sync and after about 30 minutes it appears to be finished (11:43:44). But 15 minutes later it starts all over again in an apparent endless loop.

```
....
2020-Apr-27 11:43:44.8303564 Applying changes of Path ID: A72A63EEB9B27A33!123
2020-Apr-27 11:59:15.2617783 OneDrive returned a 'HTTP 504 - Gateway Timeout' - retrying request
2020-Apr-27 11:59:15.2619531 Applying changes of Path ID: A72A63EEB9B27A33!123
2020-Apr-27 11:59:17.2295012 Processing 230 OneDrive items to ensure consistent local state due to sync_list being used
2020-Apr-27 11:59:17.2433552 Skipping item - excluded by sync_list config: Pictures
2020-Apr-27 11:59:17.2441769 Skipping item - excluded by sync_list config: Desktop
2020-Apr-27 11:59:17.2448457 Skipping item - excluded by sync_list config: Documents
2020-Apr-27 11:59:17.2462106 Skipping item - excluded by sync_list config: Afbeeldingen
2020-Apr-27 11:59:17.2468669 Skipping item - excluded by sync_list config: Shared
2020-Apr-27 11:59:19.0264939 Processing 225 OneDrive items to ensure consistent local state due to sync_list being used
....

```

@abraunegg 
Tried PR 833 and it still keeps on going. I have sent you the debug log.

**Comment by abraunegg** [comment]
@dab414 , @reinketelaars 
Please can you both test the updated #899 PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/899/head:pr899
git checkout pr899
./configure; make clean; make;
```

The version should be `v2.4.0-33-g9b979c6` 

When testing, no need for any debug output, but what I am interested in, the following - what are you getting in regards to `Final True-Up:` messages.

In `--monitor` mode this should be if sync_list is in use:
* 1st monitor loop sync, you should get this message:
  * Final True-Up: Perform a full walk of OneDrive objects because a full scan was required and sync_list is in use and trigger was set in --monitor loop
* 2nd – 10th monitor loop sync, you should get this message
  * Final True-Up: Do not perform a full walk of the OneDrive objects - not required

In `--synchronize` mode this should be if sync_list is in use:
* Final True-Up: Perform a full walk of OneDrive objects because sync_list is in use / or trigger was set in --monitor loop

When sync_list is not in use, the messaging should be:
* Final True-Up: Do not perform a full walk of the OneDrive objects - not required


If that is what you are seeing, next need to understand if your 'processing time' issue has been sorted.

**Comment by dab414** [comment]
I've never messed around with sync_list... I'm assuming it's not in use because I never explicitly configured it. Below is my current configuration setting on PR899:
```bash
nedrive version                       = v2.4.0-33-g9b979c6
Config path                            = /home/dave/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/dave/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```
So, I ran `./onedrive --synchronize --verbose` and I indeed saw the following in the long output:

```bash
...
Processing IMG_20200423_150349.jpg
The file has not changed
Uploading new items of .
Final True-Up: Do not perform a full walk of the OneDrive objects - not required
Applying changes of Path ID: 01R57CWN56Y2GOVW7725BZO354PWSELRRZ
Processing 202 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
...
```

I compared run times across PRs 899 and 833:

```
PR833, real: 3m34.674s
PR899, real: 5m11.228s
```
And I could not find any trace of `Final True-up` in the debug logs of PR833 after running `./onedrive --synchronize --verbose`.

**Comment by abraunegg** [comment]
@dab414 
Thanks for this. OK .. some analysis:

> I've never messed around with sync_list... I'm assuming it's not in use because I never explicitly

That is why you see this message:
```
Final True-Up: Do not perform a full walk of the OneDrive objects - not required
```
That's the positive sign that things are doing 'what it should'

This message however - is not:
```
Processing 202 OneDrive items to ensure consistent local state due to a full scan being triggered by actions on OneDrive
```

This means that a full scan trigger was tripped. That particular trigger should only be tripped when using sync_list / skip_dir configurations. That is the fix that is #898 .

What I will do is add #898 to #899 - then if you can re-test that would be greatly appreciated. Will advise when the update is done and what the new version will be in ~5 mins.

**Comment by dab414** [comment]
Man, I'm impressed by how on top of this you are. I heavily rely on this app, so it's much appreciated!

**Comment by abraunegg** [comment]
@dab414 
If you can rebuild PR #899 and retest that would be greatly appreciated.

The client version should be `onedrive v2.4.0-34-g594e9b4`

**Comment by dab414** [comment]
Hey, this one's looking good!

After running `./onedrive --synchronize --verbose` on a rebuild PR899, from the debug logs:

```bash
...
Processing 01_reformat.jpg
The file has not changed
Processing IMG_20200423_150349.jpg
The file has not changed
Uploading new items of .
Final True-Up: Do not perform a full walk of the OneDrive objects - not required
Applying changes of Path ID: 01R57CWN56Y2GOVW7725BZO354PWSELRRZ
```
The final line in the snippet above was the final line in the log. Also run time greatly improved:

`real: 0m22.641s`

**Comment by abraunegg** [comment]
@dab414 
OK - great. Can you do the following with that version:

* make a few file changes locally .. tell me how that impacts the performance
* make a few file changes online on OneDrive .. tell me how that impacts the performance

Is it now operating in alignment with what you were previously expecting / experiencing?

**Comment by dab414** [comment]
Runtime after adding files locally:
`real: 40.448s`
Runtime after adding same files from online and downloading to local:
`real: 25.446s`

This performance is *much* more like what I remember. The app is doing the file changes and then promptly exiting me back to the terminal.

**Comment by abraunegg** [comment]
@dab414 
OK - thanks for the confirmation on this - greatly appreciated. Please can you test this thoroughly over the next day or two, ensure that everything is correctly in-sync in alignment with your expectation. I suspect it will be, but as the main change here is around how and when a full scan is performed, and in your case - using stand alone, there is no full walk being done as a true-up as it should not be required given you are not using 'sync_list' - but really need to be sure on this and I can only test limited permutations.

I will clean up the PR logging output, will wait for @reinketelaars to complete similar testing before I merge this into 'master'

**Comment by abraunegg** [comment]
@dab414 

> Runtime after adding files locally:
> `real: 40.448s`
> Runtime after adding same files from online and downloading to local:
> `real: 25.446s`
> 
> This performance is _much_ more like what I remember. The app is doing the file changes and then promptly exiting me back to the terminal.

Can you also do 1 more test ? I have updated the PR so that the true-up sync is 'true' - which was the setting, even way back in earlier 2.3.x versions.

I would like to compare this to your tests above where this was false - if you can do that, that would be greatly appreciated.

**Comment by dab414** [comment]
> @dab414
> OK - thanks for the confirmation on this - greatly appreciated. Please can you test this thoroughly over the next day or two, ensure that everything is correctly in-sync in alignment with your expectation. I suspect it will be, but as the main change here is around how and when a full scan is performed, and in your case - using stand alone, there is no full walk being done as a true-up as it should not be required given you are not using 'sync_list' - but really need to be sure on this and I can only test limited permutations.
> 
> I will clean up the PR logging output, will wait for @reinketelaars to complete similar testing before I merge this into 'master'

Yup, I'll keep an eye on it. I'm planning to upgrade to Ubuntu 20.04 at some point this week and I'll do a full resync, so I imagine that'll be a good test.

So I rebuilt PR899 and tried to do the first clocking by uploading files, and it's been running for probably close to 10 minutes. I can see from the online client that the files were uploaded about 10 mins ago, and the app hasn't kicked me back to the terminal yet... do you need an exact clock or can I pull the plug?

**Comment by abraunegg** [comment]
@dab414 
OK - Thanks, so that is walking through making sure that everything is 'in-sync' based on the 'true' setting.

In terms of 'processing time' - how long is that now taking?

**Comment by reinketelaars** [comment]
I have built and tested PR 899
```
onedrive v2.4.0-39-g8f681f1
```
After the "Applying changes of Path ID: A72A63EEB9B27A33!123" message, it seems to restart after a 15 minute HTTP 504 timeout error. As shown below. This is repeated multiple times.
It still keeps running, now for over one hour again.
```
...
Skipping item - excluded by sync_list config: ./mp3_albums
Skipping item - excluded by sync_list config: ./incoming
Applying changes of Path ID: A72A63EEB9B27A33!123
OneDrive returned a 'HTTP 504 - Gateway Timeout' - retrying request
Applying changes of Path ID: A72A63EEB9B27A33!123
Processing 229 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Pictures
Skipping item - excluded by sync_list config: Desktop
Skipping item - excluded by sync_list config: Documents
...
```

Also, there are no "Final True-Up:" messages in my --verbose logs...
I have sent some logs by email.

**Comment by dab414** [comment]
Okay, coming back today to time uploads and downloads.

On PR899 `onedrive v2.4.0-38-g29db857`

Upload: `real: 5m57.472s`  
Download: `real: 5m28.405s`

So I'm seeing slower times again. And it's doing a full scan (from the logs):
```bash
Deleting item from OneDrive: debug_output.log
Processing debug_output3.log
The file has been deleted locally
Deleting item from OneDrive: debug_output3.log
Uploading new items of .
Final True-Up: Perform a full walk of OneDrive objects because a full scan was required
Applying changes of Path ID: 01R57CWN56Y2GOVW7725BZO354PWSELRRZ
Processing 202 changes
Processing 269 changes
```

**Comment by abraunegg** [comment]
@reinketelaars 
OK .. so you still seem to have a problem somewhere.

The issue here is, because you are using 'sync_list' - you have to do a full walk of your tree at some point to ensure you have a consistent state. Regardless of mode operation, this will be done and needs to be done.

> Applying changes of Path ID: A72A63EEB9B27A33!123" message, it seems to restart after a 15 minute HTTP 504 timeout error

This is correct - you had a Internet connection issue between you and OneDrive, and so this was handled gracefully by retrying the last operation.

> Also, there are no "Final True-Up:" messages in my --verbose logs...

This is because you are running `onedrive v2.4.0-39-g8f681f1` vs `onedrive v2.4.0-38-g29db857` where I had already dropped those log output back to debug based on testing by @dab414 

What I need you to do is to test the following PR's:

* PR 833 - this is plain version v2.4.0
* PR 760 - this is plain version v2.3.13

Please provide verbose debug logs (`--verbose --verbose`) for both of these, performing the exact same sync operation and advise which version is working better for you sync / time wise. Then I would like you, when using each of those versions, to confirm that when adding / moving data in / out of an 'in-scope' sync_list folder is working & your data is being pulled in correctly.

@dab414 
OK - thats, so setting 'true' really is not workable which I was testing to ensure that a consistent state is being achieved. If you rebuild PR899 you will be on `onedrive v2.4.0-39-g8f681f1` which is where this is back to the previous test you did. Once you are on that version, I think your issue is solved. If you can confirm that would be greatly appreciated.

**Comment by dab414** [comment]
Testing on PR899 `onedrive v2.4.0-39-g8f681f1`

Upload: `real: 40.533s`  
Download: `real: 20.719s`

Looking good again. Thanks again for all the work you do to maintain this! I've relied on this app for much of my graduate work!

**Comment by abraunegg** [comment]
@reinketelaars 
The other option here, is to *not use sync_list*

When I look at your configuration (and I do not know if this is just because your testing things) - your sync_list configuration is just the following:
```
sync_list contents:
Archief
```
You would be **WAY** better off performance wise by using the following: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#performing-a-selective-directory-sync and removing 'sync_list'

**Example:**
```
onedrive --synchronize --single-directory 'Archief'
```

This would have the effect of:
* Would not have to walk your *entire* OneDrive to ensure a consistent state
* Would utilise the delta changes correctly in an appropriate manner

Is that even an option here for you ?

**Comment by abraunegg** [comment]
> Testing on PR899 `onedrive v2.4.0-39-g8f681f1`
> 
> Upload: `real: 40.533s`
> Download: `real: 20.719s`
> 
> Looking good again. Thanks again for all the work you do to maintain this! I've relied on this app for much of my graduate work!

No problem. Please keep track of ensuring that this is working correctly for at least a week - as I can only really reliably test basic usage and not day-to-day end user use of the application.

**Comment by reinketelaars** [comment]
@abraunegg 
Thank you for the --single-directory suggestion, I will give it a try!
I have tried pr760 and pr833 with an identical sync operation. I have emailed you the logs.

**Comment by abraunegg** [comment]
@reinketelaars 
Thanks - download the logs now to see if there is any decernable difference here. From your first post, you mentioned that from the point of having to re-auth the client the sync times were longer. If this is true, the PR 760 logs should show a different process in operation.

**Comment by dab414** [comment]
When you do pull this PR into master, can you confirm that my commands below are the best way to update the app build on my local machine (a little rusty on my git commands..):
```bash
git pull origin master
```
and then to rebuild and reinstall.. something like this?
```bash
./configure; make clean; make; sudo make install
```

**Comment by abraunegg** [comment]
@dab414 
> When you do pull this PR into master, can you confirm that my commands below are the best way to update the app build on my local machine (a little rusty on my git commands..):
> 
> ```shell
> git pull origin master
> ```
> 
> and then to rebuild and reinstall.. something like this?
> 
> ```shell
> ./configure; make clean; make; sudo make install
> ```

That looks about right & should work.

**Comment by abraunegg** [comment]
@dab414 
Any update on your side for the last 24hrs?

For those following this thread:
* Main cause of issue was the Western Europe OneDrive service throwing HTTP 504 errors, and when these were being handled by the client, the queries for changes were looping due to the re-try for the 504. This looping & re-try has now been fixed.

**Comment by reinketelaars** [comment]
@abraunegg 
The latest PR 899 = `onedrive v2.4.0-46-ga9ddebf` has indeed resolved my issue!
The client does not anymore start from the beginning after a HTTP 504 error received from the "West Europe" data center. It now pauses and continues the process. 
Before, I experienced this issue on multiple machines connecting through different internet connections.

Thank you very, very much for responding so fast and investing so much of your time by analyzing the problem and examining the numerous logs I sent you. Especially because it appears to be a problem specific to the West Europe data center, so you couldn't reproduce the error in Australia.

**Comment by dab414** [comment]
> 
> 
> @dab414
> Any update on your side for the last 24hrs?

I did a full hard drive wipe, dist upgrade, and re-download of the whole onedrive (via master branch, though). Everything seems to have worked great. I've been doing small uploads / downloads since then (on PR 899), and everything works as expected.

**Comment by abraunegg** [comment]
@dab414 , @reinketelaars 
Thanks for confirmation. Closing issue and marking as fixed as PR899 merged into 'master'
