### ISSUE TITLE
Upload piping and uploading without saving on disk

### ISSUE THREAD

**Issue by Joyggy** [abraunegg/onedrive#897]
**Is your feature request related to a problem? Please describe.**
I want to be able to pipe wget requests to be uploaded straight to onedrive without being downloaded first and taking up disk space.

**Describe the solution you'd like**
Straight piping and it not being saved on disk

**Describe alternatives you've considered**
buying bigger harddrives. No solution. Expensive

**Comment by abraunegg** [comment]
@Joyggy 
It is not very clear what you are wanting here. I suspect you are meaning 'on-demand' files - see https://github.com/abraunegg/onedrive/issues/757

If you are meaning something else, as in not downloading data from OneDrive, please read the usage document in regards to `--upload-only` -https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#performing-a-one-way-upload-sync

**Comment by abraunegg** [comment]
Closing issue as question answered
