### ISSUE TITLE
Slow download in syncing - may relate to user-agent setting

### ISSUE THREAD

**Issue by aphan-sevendreamers** [abraunegg/onedrive#9]
I don't know for sure if this is a real thing or not but the download speed (in Linux) is significantly slower than when I use the Microsoft default app on Window (maybe 1/5 ~ 1/10). 
And then I came across this article: https://www.theregister.co.uk/2017/03/23/microsoft_onedrive_linux_slow/

It suggested that microsoft is lazy in doing user agent checking and serve the worst code version to us. 

Could you please check this issue (by trying to supply something like 'firefox mozilla 58/ windows 7' in user-agent string in the HTTP request and see if there is any difference?

This is purely my suggestion in case you guys are not aware of this. Sorry if this is not the case.
Best regards,

**Comment by abraunegg** [comment]
I looked at this before ~6 months ago, and in the testing I was doing I could not see any difference at that point in time between using the default user agent and manually setting to an IE11 agent string.

I will re-run some tests using a large file for upload / download comparison - with & without an IE11 user-agent string

**Comment by aphan-sevendreamers** [comment]
Wow thanks for the quick answer. In my case it is not a big file that make the download speed slow. But instead I have ~1M small files (1MB each). 
In any case, great work!

**Comment by abraunegg** [comment]
1MB file is not that back but 1M of these will certainly take a long time to process. There was a DB tweak in my branch (https://github.com/abraunegg/onedrive/commit/4e0c3a4cf0c22f6215264c2798c4b459bb5b2145) that speeds up database read/writes - have you deleted your local items database file and allowed it to re-create to take advantage of that change?

I would look into things on your network such as:
- network access speeds
- upstream bandwitdh throttling (QoS)
- upstream content control (DLP, AV Scanning)
- MTU issues / mismatch
- Network Interface Card Duplex issues / Switch Port Duplex issues

Can you provide some statistics around how the client is currently operating for you?

**Comment by aphan-sevendreamers** [comment]
Thanks abraunegg, it is as you said, I didn't delete the local items database file. My bad big time! It is much better now.

**Comment by abraunegg** [comment]
No problem. If all is OK - can you close this case out please.

**Comment by abraunegg** [comment]
Added information to FAQ: https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions
