### ISSUE TITLE
Caught in endless loop due to unhandled exception from inotify

### ISSUE THREAD

**Issue by LordPato** [abraunegg/onedrive#903]
### Bug Report Details ###
Already was able to sync almost 800gb from Onedrive. But after that, no changes in my local disk were syncronized even after several hours.
When enabled verbose, it's hanged looping at
**"Processing 293 OneDrive items to ensure consistent local state"**
It's been more than one day in that state (the number differs a bit)
What can I do to make sync faster?

**Application and Operating System Details:**
*   OS: Linux 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 19.10)
*   Docker
*   OneDrive Personal
*   Application configuration: 

/usr/local/bin/onedrive --verbose --monitor --confdir /onedrive/conf --syncdir /onedrive/data
```
onedrive version                       = v2.4.1
Config path                            = /root/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /root/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```
*   Curl Version: 
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets

**Comment by abraunegg** [comment]
@LordPato 
Please can you update your post following the directions as per: https://github.com/abraunegg/onedrive#reporting-issues

1. You have not used the new issue template. There are specific reasons why a bug report template exists so that I can assist you in a timely fashion.
2. You have not provided all the required information as per the new issue template

Please can you fix up your post and follow the bug submission guidelines please.

**Comment by LordPato** [comment]
Just added the information that I was able to gather.

**Comment by abraunegg** [comment]
@LordPato 
Please can you provide a verbose debug log as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support which is Step 3 when reporting an issue. This is used to determine what the application is doing & why.

**Comment by abraunegg** [comment]
> ### Bug Report Details
> Already was able to sync almost 800gb from Onedrive. But after that, no changes in my local disk were syncronized even after several hours.
> When enabled verbose, it's hanged looping at
> **"Processing 293 OneDrive items to ensure consistent local state"**
> It's been more than one day in that state (the number differs a bit)
> What can I do to make sync faster?
> 

Also, just to add, I highly doubt that the issue you are experiencing is against v2.4.1 given it was only released this morning (~2hrs ago) and your note says 'It's been more than one day in that state (the number differs a bit)' ... so most likely this is an issue against a much older version - but unsure without seeing the debug logs.

Please ensure that you:
* If running Docker for this, make sure you are running a v2.4.1 Docker image as per https://hub.docker.com/repository/docker/driveone/onedrive/tags?page=1&name=v2.4.1 and ensure that you re-test
* If running the client outside of Docker, as you are using Ubuntu - make sure that you have not installed the 'onedrive' package - as those are very old.
* Provide a verbose debug log as per above which will assist in providing the answers - or fixing a bug if it exists.

**Comment by LordPato** [comment]
Sorry for the confusion. After  I created the first ticket, I updated it to 2.4.1 to see if it improves. But the issue remains. I would like to attach that debug log but it's still not done.

By looking at it it seems that is reviewing file by file all over again

[DEBUG] ------------------------------------------------------------------

[DEBUG] Processing change 148 of 223

[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"aYzo2MkIxQUI0ODNENTBDQzY3ITIwODA2MS4yNTc","eTag":"aNjJCMUFCNDgzRDUwQ0M2NyEyMDgwNjEuNA","file":{"hashes":{"crc32Hash":"00FD6BEC","sha1Hash":"40C53DDC39F255C0EB36A4EFE4DBB89DD88EA3B0"},"mimeType":"image\/jpeg"},"fileSystemInfo":{"createdDateTime":"2015-07-04T22:08:07Z","lastModifiedDateTime":"2005-08-25T13:16:04Z"},"id":"62B1AB483D50CC67!208061","name":"P8250013.JPG","parentReference":{"driveId":"62b1ab483d50cc67","driveType":"personal","id":"62B1AB483D50CC67!117404","name":"TP2","path":"\/drive\/root:\/(hidden folder name)"},"size":1310935}

[DEBUG] Not a OneDrive deleted item change

[DEBUG] defaultRootId                                        = 62B1AB483D50CC67!103

[DEBUG] 'search id'                                          = 62B1AB483D50CC67!103

[DEBUG] id == defaultRootId                                  = true

[DEBUG] isItemRoot(item)                                     = false

[DEBUG] item['name'].str == 'root'                           = false

[DEBUG] singleDirectoryScope                                 = false

[DEBUG] 'parentReference id'                                 = 62B1AB483D50CC67!117404

[DEBUG] syncFolderName                                       = root

[DEBUG] syncFolderPath                                       = 

[DEBUG] syncFolderChildPath                                  = 

[DEBUG] thisItemId                                           = 62B1AB483D50CC67!208061

[DEBUG] thisItemPath                                         = /drive/root:/-- (hidden folder name)

[DEBUG] 'item id' matches search 'id'                        = false

[DEBUG] 'parentReference id' matches search 'id'             = false

[DEBUG] 'thisItemPath' contains 'syncFolderChildPath'        = true

[DEBUG] 'thisItemPath' contains search 'id'                  = false

[DEBUG] Change matches search criteria to apply

[DEBUG] skip_file item to check: P8250013.JPG

[DEBUG] Result: false

[DEBUG] The item we are syncing is a file

[DEBUG] OneDrive change is an update to an existing local item

[DEBUG] Updating local database with item details

**Comment by abraunegg** [comment]
@LordPato 
Please can you provide the verbose debug log via email for analysis

**Comment by LordPato** [comment]
I'll try but it's still generating logs with that data, it will take weeks to finish that file.

One thing that I noticed. All files have the correct creation date, but all folders were created using current date. Could that be an issue?

**Comment by abraunegg** [comment]
@LordPato 
Without seeing the log - I cannot comment on that. Even if the process is not complete, cancel it, and provide the current log.

I am currently testing here with a 10Gb dataset and do not see this issue you are seeing or reporting.

**Comment by LordPato** [comment]
Sure, I just removed all repetitive stuff and just sent it.

Thanks

**Comment by abraunegg** [comment]
@LordPato 
By removing all the data like you have - you are removing the potential reason why you are maybe seeing an issue.

Right now, based on the log file, everything is 100% normal - no issue.

**Comment by LordPato** [comment]
Sent again. Thanks

**Comment by abraunegg** [comment]
@LordPato 
As per my email - there is nothing in the debug log that is showing any error or issue:

* You are getting consistent ‘Processing 207 OneDrive items to ensure consistent local state’ 
  * Each ‘change set bundle’ of 207 items is unique however, despite the same message being printed. Perhaps in this case, an enhancement is needed to show that this really is a 'new bundle' to avoid undue concern.
* I am not seeing any re-try / HTTP error messages (at least in this log as provided) - which was an issue pre v2.4.1 (see https://github.com/abraunegg/onedrive/issues/896) and this could cause such behavior.

Please also review the other details provided in email

**Comment by abraunegg** [comment]
@LordPato 
Example potential enhancement:
```
Monitor directory: ./50k_files/random_files/random_files_dir_set_2/pbNSrAlrqXmmqtx8BqfSHXkitZG88URP
Monitor directory: ./50k_files/random_files/random_files_dir_set_2/zr9Tc5lITpXDPr2wQzdSFyjBKdVk3eh0
Monitor directory: ./50k_files/random_files/random_files_dir_set_2/nTFTrWo52Fmcju1FN0lnfAO2RazFjn7y
Monitor directory: ./50k_files/random_files/random_files_dir_set_2/lJnqvA0gFFv8vMvoIMg7u8UCXFZm0SkY
Monitor directory: ./50k_files/random_files/random_files_dir_set_2/IFAg4KY28ILj6SVElNKrj68i6oELpXIz
Monitor directory: ./50k_files/random_files/random_files_dir_set_2/XyCSX0TgELCWdizP3TiqvIiZlz3HWbDe
Monitor directory: ./50k_files/random_files/random_files_dir_set_2/ypfXtzNWPfiAhFE1WC8uOdY440ASN9Ud
Starting a sync with OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #1)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #2)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #3)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #4)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #5)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #6)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #7)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #8)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #9)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #10)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #11)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #12)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #13)
Processing 205 OneDrive items to ensure consistent local state (Data Bundle #14)
```

Unfortunately there is no way to know 'how many bundles' OneDrive will be sending, but at least in this scenario, you know that the messaging is different, whilst technically looking the same - but ensuring that the idea of the client being stuck in a 'loop' would be removed.

**Comment by abraunegg** [comment]
With further discussions via email, a potential cause of 'endless looping' is the following:
* Time to scan all objects (full scan 16hrs)
* Unhandled monitor exception `Inotify overflow, events missing (Resource temporarily unavailable)` that causes the monitor / sync process to restart

**Comment by abraunegg** [comment]
@LordPato 
Please can you test the following PR to assist with resolving the unhandled monitor exception you were seeing:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/903/head:pr903
git checkout pr903
./configure; make clean; make;
```

You may need to also manually build a Docker container from this PR and run that as well.

**Comment by LordPato** [comment]
Left it running overnight. Was able to clean up some amount of files so the sync didn't take that much.

Just got the following error, which caused the initial sync to start over again


```
ERROR: OneDrive returned an error with the following message:
Error Message: Failure when receiving data from the peer on handle B5A840
Fragment upload failed - received an exception response from OneDrive
ERROR: OneDrive returned an error with the following message:
Error Message: HTTP request returned status code 100 (Continue)
Retry sync count: 2: JSONValue is not an object
Applying changes of Path ID: 62B1AB483D50CC67!103
Processing 200 OneDrive items to ensure consistent local state
...
```

**Comment by LordPato** [comment]
Ok, happened again with a little more detail :

```
OneDrive returned an error with the following message:
  Error Message: Failure when receiving data from the peer on handle B5A840
Fragment upload failed - received an exception response from OneDrive
ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 100 (Continue)
Giving up on sync after three attempts: JSONValue is not an object
std.json.JSONException@std/json.d(308): JSONValue is not an object
----------------
/usr/include/dmd/phobos/std/exception.d:516 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x62036f]
/usr/include/dmd/phobos/std/exception.d:437 pure @safe bool std.exception.enforce!(std.json.JSONException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x6202e7]
??:? inout pure @property @trusted inout(std.json.JSONValue[immutable(char)[]]) std.json.JSONValue.objectNoRef() [0x6861e9]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x6863dc]
src/upload.d:271 void upload.UploadSession.displayOneDriveErrorMessage(immutable(char)[]) [0x661027]
src/upload.d:207 std.json.JSONValue upload.UploadSession.upload() [0x660c12]
src/upload.d:48 std.json.JSONValue upload.UploadSession.upload(immutable(char)[], const(char)[], const(char)[], const(char)[], const(char)[]) [0x6602c9]
src/sync.d:3251 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x65a1fc]
src/sync.d:2870 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x658ca0]
src/sync.d:2851 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x658b03]
src/sync.d:2851 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x658b03]
src/sync.d:2851 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x658b03]
src/sync.d:2168 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x656541]
src/main.d:969 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool, bool) [0x63b2f8]
src/main.d:813 _Dmain [0x63a846]
```

**Comment by abraunegg** [comment]
@LordPato 
Thanks .. I have updated the PR. If you can rebuild the PR you should get `onedrive v2.4.1-3-g8c6c4a8` as the version.

**Comment by abraunegg** [comment]
@LordPato 
Any update here in testing the updated PR ?

**Comment by abraunegg** [comment]
Closing issue as PR merged into 'master' resolving:
* Unhandled exception from inotify
* Crash when uploading data and OneDrive returning a status code 100
