### ISSUE TITLE
Distinguish between zero space remaining and quota information restriction

### ISSUE THREAD

**Issue by Simon-Tang** [abraunegg/onedrive#906]
**Describe the solution you'd like**

The client currently does not distinguish between 0 remaining space and the error case described by this message:

```
ERROR: OneDrive quota information is being restricted. Please fix by speaking to your OneDrive / Office 365 Administrator.
```

The client would ideally be able to distinguish between these scenarios.

**Describe alternatives you've considered**

The client could either distinguish between these scenarios, or modify the error message to include the possibilty that the user is out of space.

**Additional context**

I encountered this message on my first run, since my OneDrive was full at the time. Once I cleared some space in my OneDrive, the message disappeared as expected. My OneDrive account is a personal account.

**Comment by abraunegg** [comment]
@Simon-Tang 
Thanks for the suggestion. Please can you evaluate the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/907/head:pr907
git checkout pr907
./configure; make clean; make;
```

Example updated message when out of space when using a OneDrive Personal account:
```
./onedrive --confdir '~/.config/onedrive-personal/' --monitor --verbose
Using Config Dir: /home/alex/.config/onedrive-personal/
Notification (dbus) server not available, disabling
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
ERROR: OneDrive account currently has zero space available. Please free up some space online.
ERROR: Flagging to disable upload space checks - this MAY have undesirable results if a file cannot be uploaded due to out of space.
Application version: v2.4.1-1-g4a4d446
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: -12342272
Fetching details for OneDrive Root
OneDrive Root exists in the database
Trying to restore the upload session ...

```

**Comment by Simon-Tang** [comment]
Thanks for the speedy response @abraunegg. I'm in the process of cleaning up my personal OneDrive so I might not be setting my remaining space to 0 again soon. However I'm curious if the handling of quotaAvailable should be updated as well (https://github.com/abraunegg/onedrive/blob/master/src/sync.d#L2863). Possibly with just a different log message, if we still want to attempt to upload regardless.

**Comment by abraunegg** [comment]
@Simon-Tang 
> Thanks for the speedy response @abraunegg. I'm in the process of cleaning up my personal OneDrive so I might not be setting my remaining space to 0 again soon. However I'm curious if the handling of quotaAvailable should be updated as well (https://github.com/abraunegg/onedrive/blob/master/src/sync.d#L2863). Possibly with just a different log message, if we still want to attempt to upload regardless.

No that message is fine as the file will be attempted to be uploaded regardless. OneDrive will then respond with a 507 if unable to upload.

**Comment by Simon-Tang** [comment]
The PR looks great to me, @abraunegg! :)

**Comment by abraunegg** [comment]
Closing issue as PR merged into master
