### ISSUE TITLE
unable to fork: Cannot allocate memory (Ubuntu 18.04.4 LTS)

### ISSUE THREAD

**Issue by DaveMellor** [abraunegg/onedrive#908]
I cloned/installed as per your instructions. The build failed:
```
djm@djm-HP11-aa0XX:~/onedrive$ make clean;make;
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
	git describe --tags > version ; \
else \
	echo v2.4.2-dev > version ; \
fi
dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
unable to fork: Cannot allocate memory
Makefile:99: recipe for target 'onedrive' failed
make: *** [onedrive] Error 255
```
OS: 
```
Linux djm-HP11-aa0XX 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
DMD: 
```
DMD64 D Compiler v2.090.1
Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

CURL:

```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
djm@djm-HP11-aa0XX:~/onedrive$
```
Please let me know if there is any other information you require. Thanks, Dave M

**Comment by abraunegg** [comment]
@DaveMellor 
This 100% sounds like the dependencies are not being met.

Please read this link very carefully especially the first bullet point: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#build-requirements

Please check your system and advise.

**Comment by DaveMellor** [comment]
Getting onto it. Thank you. Will let you know. Dave M.

**Comment by DaveMellor** [comment]
Hi, I am working on it. I'm afraid I'm coming out of retirement so as I am
decrepit I'm a bit slow.

Take care and stay safe 😎

All the best,

Dave Mellor

**Comment by yum-feng** [comment]
I had the same issue with 2GB RAM on a `Ubuntu 18.04.2 LTS` VPS.

It turns out that I didn't have a swap file. The procedure found in https://linuxize.com/post/create-a-linux-swap-file/ showed me how to create a swap file and the build worked afterwards.
