### ISSUE TITLE
Fails to create a new sub-folder in OneDrive inside a shared folder

### ISSUE THREAD

**Issue by gm-mogni** [abraunegg/onedrive#912]
onedrive application fails to create a new sub-folder in OneDrive inside a shared folder where I've been given editing rights.
The sub-folder can be created manually if accessing via web. After it has been created, synchronization of files to that sub-folder works fine.
Creation of regular folders works fine. Synchronization works fine.

$ onedrive --version
onedrive v2.4.1

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
5.4.36-1-MANJARO
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.0
DISTRIB_CODENAME=Lysia
DISTRIB_DESCRIPTION="Manjaro Linux"
*   Are you using a headless system (no gui) or with a gui installed?
gui installed
*   OneDrive Account Type
OneDrive 5GB - personal free account
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
DMD64 D Compiler v2.091.1
*   Application configuration: Output of `onedrive --display-config`
```
[gm@gm-linux ~]$ onedrive --display-config
onedrive version                       = v2.4.1
Config path                            = /home/gm/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/gm/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```
*   Curl Version: Output of `curl --version`
curl 7.69.1 (x86_64-pc-linux-gnu) libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.40.0
Release-Date: 2020-03-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Create a sub-folder in local onedrive. Sub-folder must be inside a shared folder with editing rights (The shared folder was created by a coworker and then shared in OneDrive)
2.  Execute command: onedrive --synchronize --verbose 
3.  See error (Folder DEM mentioned below is the shared folder. 'test2' is a created sub-folder.

```
OneDrive Client requested to create remote path: ./DEM/test2
The requested directory to create was not found on OneDrive - creating remote directory: ./DEM/test2
Giving up on sync after three attempts: The parent item id is not in the database
object.Exception@src/sync.d(2983): The parent item id is not in the database
----------------
??:? pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x55e0061457ee]
??:? pure @safe bool std.exception.enforce!().enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x55e006252d2f]
??:? void sync.SyncEngine.uploadCreateDir(const(immutable(char)[])) [0x55e00621aefc]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55e00621a57e]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55e00621a643]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x55e00621a643]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x55e006218081]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool, bool) [0x55e0061fce38]
??:? _Dmain [0x55e0061fbe8f]
```

**Comment by abraunegg** [comment]
@gm-mogni 
Please can you provide a verbose debug log via email as per the support directions.

Whilst the crash details above assist, the verbose debug log helps with replicating and fixing the issue.

**Comment by gm-mogni** [comment]
Sent, thanks.

**Comment by abraunegg** [comment]
@gm-mogni 
Thanks fort he debug log, it helps confirm what is going on.

Please can you validate the following PR to fix your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/913/head:pr913
git checkout pr913
./configure; make clean; make;
```
You will need to then either 'install' or run the updated application binary from the PR folder to validate the fix.

**Comment by gm-mogni** [comment]
This fixes the issue. Thanks!

**Comment by abraunegg** [comment]
Thanks for the confirmation
