### ISSUE TITLE
Build error - WrapperDigest is not defined

### ISSUE THREAD

**Issue by burnsba** [abraunegg/onedrive#915]
I'm getting a build error that "WrapperDigest is not defined." The output line before gave a warning about a digest library being deprecated.

I *fixed* the problem and was able to build from source by modifying the file /master/src/qxor.d and replacing the second line

    import std.digest.digest;

with 

    import std.digest;

-----

I was having http 429 errors on Debian stable (onedrive apt package isn't available, but 2.3.7-3 .deb can be installed), so I wanted to build from source because I think the issue was fixed in 2.4.1. This is the first time I've ever built onedrive or installed DMD.

system info: debian 10.4 on kernel 4.19 x64

	# cat /etc/debian_version
	10.4
	
	# uname -a
	Linux gigadeb 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux

dependencies

	# apt-get install build-essential libcurl4-openssl-dev libsqlite3-dev pkg-config git curl
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	build-essential is already the newest version (12.6).
	curl is already the newest version (7.64.0-4+deb10u1).
	git is already the newest version (1:2.20.1-2+deb10u3).
	pkg-config is already the newest version (0.29-6).
	The following packages were automatically installed and are no longer required:
	  irqbalance runit-helper
	Use 'apt autoremove' to remove them.
	Suggested packages:
	  libcurl4-doc libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev libssl-dev zlib1g-dev sqlite3-doc
	The following NEW packages will be installed:
	  libcurl4-openssl-dev libsqlite3-dev
	0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
	Need to get 1,206 kB of archives.
	After this operation, 3,808 kB of additional disk space will be used.
	Do you want to continue? [Y/n] y
	Get:1 http://httpredir.debian.org/debian buster/main amd64 libcurl4-openssl-dev amd64 7.64.0-4+deb10u1 [419 kB]
	Get:2 http://httpredir.debian.org/debian buster/main amd64 libsqlite3-dev amd64 3.27.2-3 [787 kB]
	Fetched 1,206 kB in 0s (7,416 kB/s)
	Selecting previously unselected package libcurl4-openssl-dev:amd64.
	(Reading database ... 215093 files and directories currently installed.)
	Preparing to unpack .../libcurl4-openssl-dev_7.64.0-4+deb10u1_amd64.deb ...
	Unpacking libcurl4-openssl-dev:amd64 (7.64.0-4+deb10u1) ...
	Selecting previously unselected package libsqlite3-dev:amd64.
	Preparing to unpack .../libsqlite3-dev_3.27.2-3_amd64.deb ...
	Unpacking libsqlite3-dev:amd64 (3.27.2-3) ...
	Setting up libsqlite3-dev:amd64 (3.27.2-3) ...
	Setting up libcurl4-openssl-dev:amd64 (7.64.0-4+deb10u1) ...
	Processing triggers for man-db (2.8.5-2) ...
	
dmd install

	$ curl -fsS https://dlang.org/install.sh | bash -s dmd
	Downloading https://dlang.org/d-keyring.gpg
	######################################################################## 100.0%
	Downloading https://dlang.org/install.sh
	######################################################################## 100.0%
	The latest version of this script was installed as ~/dlang/install.sh.
	It can be used it to install further D compilers.
	Run `~/dlang/install.sh --help` for usage information.

	Downloading and unpacking http://downloads.dlang.org/releases/2.x/2.092.0/dmd.2.092.0.linux.tar.xz
	######################################################################## 100.0%
	Using dub 1.21.0 shipped with dmd-2.092.0

	Run `source ~/dlang/dmd-2.092.0/activate` in your shell to use dmd-2.092.0.
	This will setup PATH, LIBRARY_PATH, LD_LIBRARY_PATH, DMD, DC, and PS1.
	Run `deactivate` later on to restore your environment.

activate, ./configure, make clean, make

	tolos@gigadeb:~/source/onedrive$ source ~/dlang/dmd-2.092.0/activate
	(dmd-2.092.0)tolos@gigadeb:~/source/onedrive$
	(dmd-2.092.0)tolos@gigadeb:~/source/onedrive$ ./configure
	checking for a BSD-compatible install... /usr/bin/install -c
	checking for pkg-config... /usr/bin/pkg-config
	checking pkg-config is at least version 0.9.0... yes
	checking for dmd... dmd
	checking version of D compiler... 2.092.0
	checking for curl... yes
	checking for sqlite... yes
	configure: creating ./config.status
	config.status: creating Makefile
	config.status: creating contrib/pacman/PKGBUILD
	config.status: creating contrib/spec/onedrive.spec
	config.status: creating onedrive.1
	config.status: creating contrib/systemd/onedrive.service
	config.status: creating contrib/systemd/onedrive@.service
	(dmd-2.092.0)tolos@gigadeb:~/source/onedrive$ make clean
	rm -f onedrive onedrive.o version
	rm -rf autom4te.cache
	rm -f config.log config.status
	(dmd-2.092.0)tolos@gigadeb:~/source/onedrive$ make
	if [ -f .git/HEAD ] ; then \
			git describe --tags > version ; \
	else \
			echo v2.4.2-dev > version ; \
	fi
	dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
	src/qxor.d(2): Deprecation: module std.digest.digest is deprecated - import std.digest instead of std.digest.digest. std.digest.digest will be removed in 2.101
	src/qxor.d(88): Error: template instance WrapperDigest!QuickXor template WrapperDigest is not defined
	make: *** [Makefile:100: onedrive] Error 1
	(dmd-2.092.0)tolos@gigadeb:~/source/onedrive$
	
version stuff

	$ git log
	commit 2529b99265c962ec87ddd9648545be689fb03336 (HEAD -> master, origin/master, origin/HEAD)
	Author: abraunegg <alex.braunegg@gmail.com>
	Date:   Sun May 10 05:42:46 2020 +1000

		Update enforce statement for parent id database query (Issue #912) (#913)

		* Update database enforce check with conditional check on parent drive ID. If the parent is a shared folder, the parent ID will never be in the database as we are never provided that parent ID.

	
	(dmd-2.092.0)tolos@gigadeb:~/source/onedrive$ git describe --tags
	v2.4.1-5-g2529b99

**Comment by Javier1995** [comment]
Same here!

**Comment by abraunegg** [comment]
@burnsba, @Javier1995 
Thanks - looks like this is a change due to the compiler being updated. Will look at this shortly based on your details above and see if this change breaks when using 2.091 version of DMD .. as there is no issue when using the 2.091 compiler. 2.092 must have *just* been released as even the DMD Download site says it is in RC1 still.

> I was having http 429 errors on Debian stable (onedrive apt package isn't available, but 2.3.7-3 .deb can be installed)

Dont use packages that are old ... esp say 2.3.7 ... that is from July last year! There is a reason why I always recommend to build from source.

**Comment by abraunegg** [comment]
@burnsba, @Javier1995
Looks like the update does not break on 2.091, will submit a PR shortly to fix 'master'

**Comment by Javier1995** [comment]
thanks!

**Comment by abraunegg** [comment]
@burnsba, @Javier1995
Fixed and merged into 'master' after CI testing

**Comment by Javier1995** [comment]
It worked!! thanks!

**Comment by hselley** [comment]
Had the same issue in ArchLinux, it worked like a charm!! :D

**Comment by abraunegg** [comment]
@hselley 
On ArchLinux you are better off using the AUR package - https://aur.archlinux.org/packages/onedrive-abraunegg/ - this was updated on 2020-05-27 which includes this fix.
