### ISSUE TITLE
Cannot Authorize

### ISSUE THREAD

**Issue by DrPeeper** [abraunegg/onedrive#919]
### Bug Report Details ###
**Describe the bug**
Just installed and cannot authorize client.
Program crashes after entering the response uri with a HTTP 400 error.
**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
```
Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
```
*   Are you using a headless system (no gui) or with a gui installed?
gui
*   OneDrive Account Type
Business
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
none
*   Application configuration: Output of `onedrive --display-config`
```
	onedrive version                    = v2.2.5-1
	Config path                         = /home/pi/.config/onedrive
	Config file found in config path    = false
	Config option 'sync_dir'            = /home/pi/OneDrive
	Config option 'skip_file'           = ~*
	Config option 'skip_symlinks'       = false
	Config option 'monitor_interval'    = 45
	Config option 'log_dir'             = /var/log/onedrive/
	Selective sync configured           = false
```
*   Curl Version: Output of `curl --version`
```
	Release-Date: 2019-02-06
	Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
	Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```
* Debug log (the standard method was not working so i'm just copy pasting)
```
$ onedrive
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=[REDACTED]&session_state=[REDACTED]
onedrive.OneDriveException@src/onedrive.d(713): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "af0cfb87-6aa6-4fb5-be90-6b1111ea80dd",
    "error": "invalid_grant",
    "error_codes": [
        9002313
    ],
    "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: ec38f294-b006-4430-84ee-f474eddd2100\r\nCorrelation ID: af0cfb87-6aa6-4fb5-be90-6b1111ea80dd\r\nTimestamp: 2020-05-16 18:46:55Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=9002313",
    "timestamp": "2020-05-16 18:46:55Z",
    "trace_id": "ec38f294-b006-4430-84ee-f474eddd2100"
}
----------------
??:? [0x92f03]
??:? [0x921cb]
??:? [0x92a1b]
??:? [0x9155b]
??:? [0x9afb3]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xb68b4b17]
??:? _d_run_main [0xb68b48af]
??:? __libc_start_main [0xb65f2717]

```
**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**
Installed using ap-get on debian
```
onedrive/stable,now 2.2.5-1 armhf
``` 
### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment]
@DrPeeper 
You are running a very old version and you have installed via packages which is not advisable.

Refer to: 
* https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#important-information-for-ubuntu-users
* https://github.com/abraunegg/onedrive/blob/master/README.md#reporting-issues
* https://github.com/abraunegg/onedrive/releases

To resolve this you need to:
* Uninstall the package
* Build from source following 'Raspbian (ARMHF)' directions in https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md

**Comment by DrPeeper** [comment]
Thank you very much.
