### ISSUE TITLE
A database execution error occurred: disk I/O error

### ISSUE THREAD

**Issue by lustasag** [abraunegg/onedrive#926]
Hi, I'm using onedrive 2.4.1 built with DMD 2.0.91.1 (2.0.92.0 fails) on a computing grid that seems to be based on Debian 9.5.

### Bug Report Details ###

The program cannot start synchornising. I tells me to do a "--resync," however, the resync fails with an error while trying to write to the sqlite database. Write permissions should be fine: the 'items.sqlite3' is deleted and then recreated with a size 0. 

I wonder if any additional debugging is possible. The issue might be the sqlite library: how to check which version was used for building?

One more thing: all files reside on an nfs volume, including syncDir and configDir.

**Complete Verbose Log Output**
`\~/bin/onedrive --resync --synchronize --verbose --verbose
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /storage/brno2/home/gabrisa
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /storage/brno2/home/gabrisa/.config
[DEBUG] configDirName: Configuring application to use default config path
Using Config Dir: /storage/brno2/home/gabrisa/.config/onedrive
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /storage/brno2/home/gabrisa/OneDrive
[DEBUG] --resync requested
Deleting the saved status ...
[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive Service
Initializing the OneDrive API ...
[DEBUG] Downgrading all HTTP operations to HTTP/1.1 by default
[DEBUG] clientId    = xxxxxx
[DEBUG] companyName = abraunegg
[DEBUG] appTitle    = OneDrive Client for Linux
Opening the item database ...
[DEBUG] Using database file: /storage/brno2/home/gabrisa/.config/onedrive/items.sqlite3

A database execution error occurred: disk I/O error

Please retry your command with --resync to fix any local database corruption issues.`

**Comment by abraunegg** [comment]
@lustasag 
> I'm using onedrive 2.4.1 built with DMD 2.0.91.1 (2.0.92.0 fails) on a computing grid

This is the most likely cause - you have 'multiple' onedrive processes running at the same time, trying to access the exact same configuration path / database.

Each process, on each node, needs to be configured to use a 'unique' configuration path / database.

**Comment by lustasag** [comment]
> @lustasag
> 
> > I'm using onedrive 2.4.1 built with DMD 2.0.91.1 (2.0.92.0 fails) on a computing grid
> 
> This is the most likely cause - you have 'multiple' onedrive processes running at the same time, trying to access the exact same configuration path / database.
> 
> Each process, on each node, needs to be configured to use a 'unique' configuration path / database.

I'm attempting to run it only on a single head node of a cluster. The home folders are on NFS because they are accessible over all the grid. 

However, your comment might actually be a clue: what I noticed while building is that there might be clock synchronisation issues between the node and the NFS server. Is the sqlite library sensitive to time-stamp issues?

**Comment by abraunegg** [comment]
@lustasag 
The client performs all db operations via exclusive lock. If the lock cannot be obtained because another process is trying to access, this is when you get this sort of error.

**Comment by lustasag** [comment]
Alright, I moved the config files as well as the whole syncDir (to make sure) to a different NFS share and now I'm happily synchronizing to my cloud drive :) 

I can imagine that locking is sensitive to temporal synchronization.

Thanks a lot for putting so much effort in maintaining this program! I am only sad that it's so hard to find: just searching for "onedrive linux" doesn't give me any useful hit, and with some effort finally the "skilion" comes up, but from there there's still no way to find your branch :(

**Comment by abraunegg** [comment]
Yep .. no way to really fix all the google searching other than others blogging / linking / talking about this repo / fork .. feel free to spread the word the best you can.
