### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [abraunegg/onedrive#927]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing OneDrive on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by abraunegg** [comment]
@LeandroStanger 
Feel free to become the packager and maintainer for that functionality as I have no desire to do that myself.

**Comment by abraunegg** [comment]
@LeandroStanger 
Additionally, flatpak is generally used for GUI applications. This client is predominantly a CLI application. The client is packaged for several distributions as per: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#linux-packages

If your chosen OS / Distro is not listed, please become the packager and maintainer for your chosen OS / Distro,

**Comment by abraunegg** [comment]
Closing this issue as 'flatpak' is mainly for packaging GUI applications
