### ISSUE TITLE
Giving up on sync after three attempts: Missing config value: bypass_data_preservation

### ISSUE THREAD

**Issue by psrodh** [abraunegg/onedrive#930]
The application fails (segmentation fault) after 3 attempts, with the message:
"Giving up on sync after three attempts: Missing config value: bypass_data_preservation"
```
mymachine(~)>onedrive --version
onedrive v2.4.1-14-gf9c3ccc
```

With bypass_data_preservation set to "false", the output is:

```
mymachine(~)>onedrive --resync --synchronize
Configuration file successfully loaded
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Retry sync count: 1: Missing config value: bypass_data_preservation
Syncing changes from OneDrive ...
Retry sync count: 2: Missing config value: bypass_data_preservation
Syncing changes from OneDrive ...
Giving up on sync after three attempts: Missing config value: bypass_data_preservation
Segmentation fault (core dumped)
```
With bypass_data_preservation set to "true", the output is:
```
mymachine(~)>onedrive --resync --synchronize
Configuration file successfully loaded
config file has been updated, checking if --resync needed
Initializing the Synchronization Engine ...
WARNING: Application has been configured to bypass local data preservation in the event of file conflict.
WARNING: Local data loss MAY occur in this scenario.
Syncing changes from OneDrive ...
Retry sync count: 1: Missing config value: bypass_data_preservation
Syncing changes from OneDrive ...
Retry sync count: 2: Missing config value: bypass_data_preservation
Syncing changes from OneDrive ...
Giving up on sync after three attempts: Missing config value: bypass_data_preservation
Segmentation fault (core dumped)
```
Weird enough, the application first says that: "... has been configured to bypass local data preservation...", and, afterwards: "... Missing config value: bypass_data_preservation".

With verbose option, the output is:
```
mymachine(~)>onedrive --resync --synchronize --verbose
Using Config Dir: /home/pedro/.config/onedrive
Configuration file successfully loaded
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /mnt/OneDrive
Application version: v2.4.1-14-gf9c3ccc
Account Type: business
Default Drive ID:  ...  (stripped for publishing this message)
Default Root ID:  ...  (stripped for publishing this message)
Remaining Free Space: 1090541209419
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
WARNING: Application has been configured to bypass local data preservation in the event of file conflict.
WARNING: Local data loss MAY occur in this scenario.
Syncing changes from OneDrive ...
Applying changes of Path ID: 01BM63MNF6Y2GOVW7725BZO354PWSELRRZ
Processing 201 OneDrive items to ensure consistent local state
Processing 230 OneDrive items to ensure consistent local state
Processing 279 OneDrive items to ensure consistent local state
Processing 250 OneDrive items to ensure consistent local state
Processing 226 OneDrive items to ensure consistent local state
Processing 250 OneDrive items to ensure consistent local state
Processing 260 OneDrive items to ensure consistent local state
The local item has a different modified time 2020-May-21 06:36:59Z remote is 2020-May-25 08:01:53Z
The local item has a different hash
Remote item modified time is newer based on UTC time conversion
Retry sync count: 1: Missing config value: bypass_data_preservation
Syncing changes from OneDrive ...
Applying changes of Path ID: 01BM63MNF6Y2GOVW7725BZO354PWSELRRZ
Processing 250 OneDrive items to ensure consistent local state
Processing 260 OneDrive items to ensure consistent local state
The local item has a different modified time 2020-May-21 06:36:59Z remote is 2020-May-25 08:01:53Z
The local item has a different hash
Remote item modified time is newer based on UTC time conversion
Retry sync count: 2: Missing config value: bypass_data_preservation
Syncing changes from OneDrive ...
Applying changes of Path ID: 01BM63MNF6Y2GOVW7725BZO354PWSELRRZ
Processing 250 OneDrive items to ensure consistent local state
Processing 260 OneDrive items to ensure consistent local state
The local item has a different modified time 2020-May-21 06:36:59Z remote is 2020-May-25 08:01:53Z
The local item has a different hash
Remote item modified time is newer based on UTC time conversion
Giving up on sync after three attempts: Missing config value: bypass_data_preservation
Segmentation fault (core dumped)
```
**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)

Linux mymachine 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Ubunt 18.04

*   Are you using a headless system (no gui) or with a gui installed?

I'm using gnome, but running the application from a terminal

*   OneDrive Account Type

It is a business type account

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`

DMD64 D Compiler v2.092.0
Copyright (C) 1999-2020 by The D Language Foundation, All Rights Reserved written by Walter Bright

*   Application configuration: Output of `onedrive --display-config`
```
onedrive version                       = v2.4.1-14-gf9c3ccc
Config path                            = /home/pedro/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /mnt/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp|*.bak|*~|*.o|._*|.DS_Store
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```
*   Curl Version: Output of `curl --version`

curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

Done

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:

run:

onedrive --synchronize

**Comment by abraunegg** [comment]
@psrodh 
I am unable to reproduce this issue as per below:
**config:**
```
# Configuration for OneDrive Linux Client
# This file contains the list of supported configuration fields
# with their default values.
# All values need to be enclosed in quotes
# When changing a config option below, remove the '#' from the start of the line
# For explanations of all config options below see docs/USAGE.md or the man page.
#
sync_dir = "~/OneDrivePersonal"
skip_file = "~*|.~*|*.tmp|*.swp"
monitor_interval = "60"
# skip_dir = ""
# log_dir = "/var/log/onedrive/"
# drive_id = ""
# upload_only = "false"
# check_nomount = "false"
# check_nosync = "false"
# download_only = "false"
# disable_notifications = "false"
# disable_upload_validation = "false"
# enable_logging = "false"
# force_http_11 = "false"
# force_http_2 = "false"
# local_first = "false"
# no_remote_delete = "false"
# skip_symlinks = "false"
# debug_https = "false"
# skip_dotfiles = "false"
# dry_run = "false"
# min_notify_changes = "5"
# monitor_log_frequency = "5"
# monitor_fullscan_frequency = "10"
# sync_root_files = "false"
# classify_as_big_delete = "1000"
# user_agent = ""
# remove_source_files = "false"
# skip_dir_strict_match = "false"
# application_id = "22c49a0d-d21c-4792-aed1-8f163c982546"
# resync = "false"
# display_memory = "false"
# monitor_max_loop = "2"
# on_demand = "true"
# display_sync_options = "true"
bypass_data_preservation = "true"
```

**log output - with true:**
```
./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose --resync
Using Config Dir: /home/alex/.config/onedrive-personal/
Configuration file successfully loaded
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.4.1-14-gf9c3ccc
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368706450
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
WARNING: Application has been configured to bypass local data preservation in the event of file conflict.
WARNING: Local data loss MAY occur in this scenario.
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 6 OneDrive items to ensure consistent local state
Downloading file corona_information ... done.
Number of items from OneDrive to process: 1
Uploading differences of .
Processing root
The directory has not changed
Processing random_videos
The directory has not changed
Processing random_images
The directory has not changed
Processing random_files
The directory has not changed
Processing corona_information
The file has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

I am not seeing any error.

**Comment by abraunegg** [comment]
@psrodh 
Please provide a **FULL** unredacted verbose debug log as per this process: https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

**Comment by abraunegg** [comment]
@psrodh 
Even with 'true' set, and modify local file to trigger this 'use-case':
```
onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose --resync
Using Config Dir: /home/alex/.config/onedrive-personal/
Configuration file successfully loaded
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.4.1-14-gf9c3ccc
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368706450
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
WARNING: Application has been configured to bypass local data preservation in the event of file conflict.
WARNING: Local data loss MAY occur in this scenario.
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 6 OneDrive items to ensure consistent local state
The local item has a different modified time 2020-May-25 10:22:06Z remote is 2020-Mar-14 21:39:20Z
The local item has a different hash
Local item does not exist in local database - replacing with file from OneDrive - failed download?
Downloading file corona_information ... done.
Number of items from OneDrive to process: 1
Uploading differences of .
Processing root
The directory has not changed
Processing random_videos
The directory has not changed
Processing random_images
The directory has not changed
Processing random_files
The directory has not changed
Processing corona_information
The file has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

Option is detected correctly, and used correctly ...

So .. please can you **URGENTLY** provide the full verbose debug log as per the above request for analysis.

**Comment by psrodh** [comment]
@abraunegg ,I have sent you the required log.

Just to center the problem: the application worked perfectly well until Friday. Apparently, the problems today are with files that have changed in the remote root, but not in the local one.

And, of course, I have been able to provide a temporary workaround to the problem by emptying the local root (moving it to somewhere else for backup), so the application has correctly downloaded the whole remote files, and now they are in sync. But I'm afraid the problem can reproduce in the future, and this is not a very convenient solution.

**Comment by abraunegg** [comment]
@psrodh 
Thanks for the debug logs. Nothing 'stands out' as obvious being incorrect. Please can you help test the following PR which modifies how this variable from the config file is 'checked'

Unless you 'absolutely need to' - I would 10000000% recommend setting that variable to 'false' or at least hashing it out in your config file. It should ONLY be used if you are seeing some sort of weird local file modifications outside of the running of the client.

The PR for you to test is as follows:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/931/head:pr931
git checkout pr931
./configure; make clean; make;
```
The version when you are running the PR should be:
```
onedrive v2.4.1-15-g95d9873
```

**Comment by psrodh** [comment]
OK, I'll try and tell you in some minutes.

And, of course, I want that variable set to "false", but, as the program started complaining about it not being set, that's why I tried what happened when I set it to "true".

**Comment by abraunegg** [comment]
@psrodh 
Any update in testing the PR ?

**Comment by abraunegg** [comment]
@psrodh 
I have attempted to also reproduce this on Ubuntu using the current 'master' .. no issue arises. 

Please can you report back regarding the use of the PR version.

**Comment by psrodh** [comment]
Hi @abraunegg.

I'm sorry: it has been quite "some minutes".

I have tried the PR, but now I can't reproduce the failure. Both the "normal" version and the PR version have no problems when I force a change in the remote file that was causing yesterday's issues. Apparently, after my "temporary workaround", the problem just disappeared.

I'm sending you the full log of the PR version with bypass_data_preservation commented out.

The only thing I'm observing now is that, for some reason, although skip_symlinks is set to "false", both versions are rejecting symbolic links, with the message: "Skipping item - invalid symbolic link: XXXX".

**Comment by abraunegg** [comment]
@psrodh 
> I have tried the PR, but now I can't reproduce the failure. Both the "normal" version and the PR version have no problems when I force a change in the remote file that was causing yesterday's issues.

Good to know, will mark this as fixed and merge the PR.

> he only thing I'm observing now is that, for some reason, although skip_symlinks is set to "false", both versions are rejecting symbolic links, with the message: "Skipping item - invalid symbolic link: XXXX".

skip_symlinks has zero bearing on that message. That message is generated when a symbolic link is present, and that link is pointing to an invalid location - ie - the target file it is supposed to be linking to fails to exist. That is 100% normal.

**Comment by mp1994** [comment]
Hello folks, I just got a similar error that is preventing me from syncing my OneDrive Business folder.
I am using a particular set-up here: I have a single-drive dual boot with Windows 10 and Ubuntu. To optimize disk usage, I have set up OneDrive in Windows first and then **configured onedrive to use the same folder _on the Windows partition_** (`/media/mattia/8C1E710B1E70EF96` below). Yes, I know it may be risky or whatever, but it works. Well, it did. 
I guess this issue may be due to the fact that some files have been modified in Windows, but I have OneDrive syncing also there so I don't know exactly what may be wrong... 
I can confirm that the option `bypass_data_preservation' is set to `false` in the config file and setting it to `true` gives the warning and then also the error that is not set, as reported above.

Here is the output of `onedrive --synchronize --verbose --dry-run` (I will omit some details for privacy):

> Using Config Dir: /home/mattia/.config/onedrive
Configuration file successfully loaded
config file has been updated, checking if --resync needed
DRY-RUN Configured. Output below shows what 'would' have occurred.
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /media/mattia/8C1E710B1E70EF96/Users/Mattia/OneDrive - XXXXXXXXXX/
Application version: v2.4.1-12-gb9dd8c7
Account Type: business
Default Drive ID: b!s2GrE9mzJ0WEn8nlXBoz8Nu4kdo3AoFAgq5zvqnfq9SUW0j......
Default Root ID: 01QOJ2AAN6Y2GOVW7725BZO3.......
Remaining Free Space: 1075190289760
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 01QOJ2AAN6Y2GOVW7725BZO354P.....
Processing 20 OneDrive items to ensure consistent local state
The local item has a different modified time 2020-May-31 08:11:02Z remote is 2020-May-24 21:24:10Z
The local item has a different hash
Remote item modified time is newer based on UTC time conversion
Retry sync count: 1: Missing config value: bypass_data_preservation
Syncing changes from OneDrive ...
Applying changes of Path ID: 01QOJ2AAN6Y2GOVW7725BZO3......
Processing 20 OneDrive items to ensure consistent local state
The local item has a different modified time 2020-May-31 08:11:02Z remote is 2020-May-24 21:24:10Z
The local item has a different hash
Remote item modified time is newer based on UTC time conversion
Retry sync count: 2: Missing config value: bypass_data_preservation
Syncing changes from OneDrive ...
Applying changes of Path ID: 01QOJ2AAN6Y2GOVW7725BZO3......
Processing 20 OneDrive items to ensure consistent local state
The local item has a different modified time 2020-May-31 08:11:02Z remote is 2020-May-24 21:24:10Z
The local item has a different hash
Remote item modified time is newer based on UTC time conversion
Giving up on sync after three attempts: Missing config value: bypass_data_preservation
Segmentation fault (core dumped)

I'd rather not empty my local folder and then sync from scratch because that's also the OneDrive folder on my Windows partition... Any hints?

**Comment by abraunegg** [comment]
@mp1994 
> Application version: v2.4.1-12-gb9dd8c7

Please upgrade to v2.4.2 or greater to resolve this issue, as per above comments the PR resolves the problem, and the fix was merged into release v2.4.2.

**Comment by mp1994** [comment]
> @mp1994
> 
> > Application version: v2.4.1-12-gb9dd8c7
> 
> Please upgrade to v2.4.2 or greater to resolve this issue, as per above comments the PR resolves the problem, and the fix was merged into release v2.4.2.

Thank you for your reply, I will let you know if it fixes the issue also for me.
Any recommended procedures to update?

**Comment by abraunegg** [comment]
@mp1994 
> Any recommended procedures to update?
Please follow https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md for your respective OS

**Comment by mp1994** [comment]
`onedrive v2.4.2-3-ged1d13b` solved the issue, thank you very much :)

PS: If I may, in the INSTALL.md you should put an Update section (or a separated UPDATE.md file). I know it may be redundant for experts, but I guess some people may find it useful
Cheers!
