### ISSUE TITLE
No notifications with daemons not using DBus activation (e.g. Ubuntu MATE)

### ISSUE THREAD

**Issue by barthiolutheran1** [abraunegg/onedrive#934]
Configured with --enable-notifications, but getting no notifications through my desktop environment, ... possibly because the notifications daemon no longer uses the DBus activation?

I'd like to get desktop notifications when, for example, sync fails on a local file that has a colon in it, so I can fix the filename. (Which has happened half a dozen times now with my work files.) And at the moment I only find that out by watching the output of journalctl.

On Ubuntu MATE 20.04, onedrive compiled from git on 2020-05-26, following install doc; enabled in systemd by user as a user service per the usage doc.

Running "journalctl --user-unit onedrive -f" gets a startup like this:

-----%<-----
onedrive: Configuration file successfully loaded
onedrive: Notification (dbus) server not available, disabling
onedrive: Initializing the Synchronization Engine ...
onedrive: Initializing monitor ...
onedrive: OneDrive monitor interval (seconds): 300
----->%-----

I'm using MATE, but none of the other notification daemons I have installed via apt (notification-daemon, dunst, notify-osd) have changed this situation.

Best I can figure, looking particularly at the development history of the MATE notification daemon (since 2013, and true for other projects as well: https://github.com/mate-desktop/mate-notification-daemon/pull/10), is that multiple notification daemons will run concurrently and can cause race conditions with DBus, so they deprecated using the DBus activation.

(Of course, I could be wrong and it could be some other thing.)

Happy to try things. Thanks! -Matt

**Comment by abraunegg** [comment]
@barthiolutheran1 
Unfortunately your choice of Operating System is what is the problem. Since they stripped out the capability to provide a way to send notifications from applications to the desktop, this is not something I can solve for.

Your choices are:
* Complain to your OS developers
* Install a different (and maybe better suited) OS than Ubuntu

This is something I cannot fix.

**Comment by coxackie** [comment]
Arch Linux user here, and exactly the same happens. It used to work perfectly fine, until I do not know exactly when. The daemon starts upon user login, and I get `onedrive: Notification (dbus) server not available, disabling`. If I `systemctl --user restart` it then notifications appears as usual - no problem with dbus anymore.

**Comment by abraunegg** [comment]
@coxackie 
That sounds more like a systemd ordering requirement - that the service is starting before another service is started.

**Comment by abraunegg** [comment]
@barthiolutheran1
Closing this issue as, the original issue, is that the OS has removed DBus support .. not much I can do regarding that.

@coxackie 
If you can investigate if a change is needed re the systemd unit files in regards to Arch and submit a PR if anything is needed to be changed that would be greatly appreciated.

**Comment by coxackie** [comment]
@abraunegg I included `dbus.service` in the `After` section of the service file, and still having the same issue.I am not too technically inclined with `systemd`, but I cannot anyway think of anything else at this point... if it is a `systemd` issue, should it not happen independently of the distro?

**Comment by abraunegg** [comment]
@coxackie 
I suspect your issue is more related to:
* Startup sequence ordering
* Permission of 'onedrive' process to send notification to 'dbus'

Which systemd unit file are you using - referring to: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-a-non-root-user-via-systemd-with-notifications-enabled-arch-ubuntu-debian-opensuse-fedora

**Comment by coxackie** [comment]
It is the user one, I have `systemctl --user enable onedrive`. Using GNOME, if this is of any help.
