### ISSUE TITLE
A switch to check updates

### ISSUE THREAD

**Issue by jsahil730** [abraunegg/onedrive#935]
**Is your feature request related to a problem? Please describe.**
It is a pain to first check if newer version has been released, and then to install it.

**Describe the solution you'd like**
I am requesting for a switch like `--update` so that one may say `onedrive --update` and onedrive is updated to the latest released version, or if it is the newest version, so is reported.

**Describe alternatives you've considered**
One needs to build it from the source and that sucks, honestly.

**Comment by abraunegg** [comment]
@jsahil730 
> It is a pain to first check if newer version has been released, and then to install it.

Rather simple fix for this - watch the repo for 'releases only'. GitHub will email you when a new release is published .. rather painless. Write a bash script that does the git clone, download & install - painless really .... and very simple.

> I am requesting for a switch like `--update` so that one may say `onedrive --update` and onedrive is updated to the latest released version, or if it is the newest version, so is reported.

Feel free to tackle a PR that attempts this or maybe performs a check against the current running version & compares this to https://github.com/abraunegg/onedrive/releases

> One needs to build it from the source and that sucks, honestly.

Sorry that you feel this way. The alternative is to develop and maintain the official package for your chosen operating system - see: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#linux-packages 

or if you are using Ubuntu ... refer to https://github.com/abraunegg/onedrive/issues/853

As per above, to simplify the compile and build, write a bash script that does the git clone, download & install - painless really .... and very simple.

**Comment by abraunegg** [comment]
Closing issue as question answered
