### ISSUE TITLE
Moving files Locally always requiere upload

### ISSUE THREAD

**Issue by ianmartinezhn** [abraunegg/onedrive#936]
**Is your feature request related to a problem? Please describe.**
Ubuntu 18.04.4 LTS
When moving a file locally thats already in the cloud and synced, would need to re upload (some files are 1gb).

**Describe the solution you'd like**
Any change(move or even rename) on the local file structure to reflect on the Cloud without the need to re Upload already existing files.

**Describe alternatives you've considered**
Looking for a GUI like the navite Onedrive app for mac and windows that has onDemand feature that skips the re upload.

**Additional context**
Thanks for a great tool, its a life saver for linux users. Keep up the good work.

**Comment by abraunegg** [comment]
@ianmartinezhn 
This is not a bug or feature as most likely you are running in standalone mode (--synchronize) the the client cannot track such moves.

If you are using monitor mode (--monitor) this is taken care of and files are moved correctly.

See: https://github.com/abraunegg/onedrive/blob/master/docs/known-issues.md#moving-files-into-different-folders-should-not-cause-data-to-delete-and-be-re-uploaded

**Comment by ianmartinezhn** [comment]
Thanks for the quick response. 
Started using the --monitor and it looks like it works most of the cases it didn't re upload the files.

Couple of use cases:
Move file Locally (WORKED) No Re-upload
Existing 
FolderA
----FolderB
----FolderC
----FileA

New
FolderA
----FolderB
---------FileA
----FolderC

Moved in the cloud (WORKED) No Re-upload
FolderA
----FolderB
----FolderC
----FolderD
----FileB

New
FolderA
----FolderB
---------FileB
----FolderC
----FolderD

Move Locally (DIDNT WORK) re-uploading
FolderA
----FolderB
----FolderC
----FolderD

New
FolderA
FolderD
----FolderB
----FolderC

Let me know if this is related just to folders.

Thanks in advance

**Comment by abraunegg** [comment]
@ianmartinezhn 
Please submit a new bug report for the folder issue, following all directions as per submitting a bug report
