### ISSUE TITLE
Uploading when moving file within onedrive in monitor

### ISSUE THREAD

**Issue by ianmartinezhn** [abraunegg/onedrive#939]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**

Started using the --monitor and it looks like it works most of the cases it didn't re upload the files.
When moving a Folder within One drive it will re upload the folder and its content while using --monitor.

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
Linux ian-desktop 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

*   Are you using a headless system (no gui) or with a gui installed?
Headless

*   OneDrive Account Type
Personal premium
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
LDC - the LLVM D compiler (1.8.0):
  based on DMD v2.078.3 and LLVM 5.0.1
  built with LDC - the LLVM D compiler (0.17.5)
  Default target: x86_64-pc-linux-gnu
  Host CPU: penryn
  http://dlang.org - http://wiki.dlang.org/LDC

  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_be - AArch64 (big endian)
    amdgcn     - AMD GCN GPUs
    arm        - ARM
    arm64      - ARM64 (little endian)
    armeb      - ARM (big endian)
    bpf        - BPF (host endian)
    bpfeb      - BPF (big endian)
    bpfel      - BPF (little endian)
    hexagon    - Hexagon
    lanai      - Lanai
    mips       - Mips
    mips64     - Mips64 [experimental]
    mips64el   - Mips64el [experimental]
    mipsel     - Mipsel
    msp430     - MSP430 [experimental]
    nvptx      - NVIDIA PTX 32-bit
    nvptx64    - NVIDIA PTX 64-bit
    ppc32      - PowerPC 32
    ppc64      - PowerPC 64
    ppc64le    - PowerPC 64 LE
    r600       - AMD GPUs HD2XXX-HD6XXX
    sparc      - Sparc
    sparcel    - Sparc LE
    sparcv9    - Sparc V9
    systemz    - SystemZ
    thumb      - Thumb
    thumbeb    - Thumb (big endian)
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64
    xcore      - XCore

*   Application configuration: Output of `onedrive --display-config`
onedrive version                       = v2.4.1-3-gcb06395
Config path                            = /home/ian/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /mnt/data3/1Drive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 30
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false

*   Curl Version: Output of `curl --version`
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
Move file Locally (WORKED) No Re-upload
Existing
FolderA
----FolderB
----FolderC
----FileA

New
FolderA
----FolderB
---------FileA
----FolderC

Moved in the cloud (WORKED) No Re-upload
FolderA
----FolderB
----FolderC
----FolderD
----FileB

New
FolderA
----FolderB
---------FileB
----FolderC
----FolderD

Move Locally (DIDNT WORK) re-uploading
FolderA
----FolderB
----FolderC
----FolderD

New
FolderA
FolderD
----FolderB
----FolderC

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by ianmartinezhn** [comment]
Adding some information of some use cases:

Original file structure locally already sync:
Documents/Bariloche 2006.pdf
Documents/Bariloche 2006 (4th copy).pdf
Documents/Bariloche 2006 (another copy).pdf
Documents/Bariloche 2006 (3rd copy).pdf
Documents/Bariloche 2006 (copy).pdf

Sync with OneDrive is complete
[M] Item moved: Documents/Bariloche 2006.pdf -> Documents/test/Bariloche 2006.pdf
Moving Documents/Bariloche 2006.pdf to Documents/test/Bariloche 2006.pdf

Uploading new items of .
Uploading new file ./Documents/test/Bariloche 2006 (4th copy).pdf ... done.
Remaining free space on OneDrive: 884968780833
Uploading new file ./Documents/test/Bariloche 2006 (another copy).pdf ... done.
Remaining free space on OneDrive: 884966242148
Applying changes of Path ID: BB4B1B33561ED680!105
Processing 10 OneDrive items to ensure consistent local state
Sync with OneDrive is complete

Uploading new items of .
Applying changes of Path ID: BB4B1B33561ED680!105
Sync with OneDrive is complete
[M] Item moved: Documents/Bariloche 2006 (3rd copy).pdf -> Documents/test/Bariloche 2006 (3rd copy).pdf
Moving Documents/Bariloche 2006 (3rd copy).pdf to Documents/test/Bariloche 2006 (3rd copy).pdf
[M] Item moved: Documents/Bariloche 2006 (copy).pdf -> Documents/test/Bariloche 2006 (copy).pdf
Moving Documents/Bariloche 2006 (copy).pdf to Documents/test/Bariloche 2006 (copy).pdf


What comes into mind is that when moving files at the moment that --monitor is "processing files"/"Processing xx OneDrive items to ensure consistent local state due to a full scan being requested" it will upload but if moved during the small window that the "Sync with OneDrive is complete" it will move the files without upload.

Let me know if im missing any type of configuration. 

Thanks for the patience

**Comment by abraunegg** [comment]
@ianmartinezhn 
I am not seeing this issue you are claiming - see below:
**application output:**
```
./onedrive --confdir '~/.config/onedrive-personal/' --monitor --verbose
Using Config Dir: /home/alex/.config/onedrive-personal/
Configuration file successfully loaded
Notification (dbus) server not available, disabling
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.4.2
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5312701696
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 600
Monitor directory: .
Monitor directory: ./random_files
Monitor directory: ./random_files/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
Monitor directory: ./random_images
Monitor directory: ./random_videos
Monitor directory: ./target
Monitor directory: ./target/5epTJHm7BdsGdFUUPPqUQh3q7051hvEE
inotify path event for: random_files/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
inotify event wd: 2
inotify event mask: 1073741888
inotify event cookie: 102103
inotify event len: 48
inotify event name: 
inotify event flag: IN_MOVED_FROM
inotify event flag: IN_MOVE
inotify event flag: IN_ISDIR
inotify event flag: IN_ALL_EVENTS
event IN_MOVED_FROM: random_files/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
inotify path event for: target/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
inotify event wd: 6
inotify event mask: 1073741952
inotify event cookie: 102103
inotify event len: 48
inotify event name: 
inotify event flag: IN_MOVED_TO
inotify event flag: IN_MOVE
inotify event flag: IN_ISDIR
inotify event flag: IN_ALL_EVENTS
event IN_MOVED_TO: target/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
Monitor directory: target/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
[M] Item moved: random_files/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh -> target/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
Moving random_files/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh to target/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
inotify path event for: target/5epTJHm7BdsGdFUUPPqUQh3q7051hvEE
inotify event wd: 6
inotify event mask: 1073741888
inotify event cookie: 102104
inotify event len: 48
inotify event name: 
inotify event flag: IN_MOVED_FROM
inotify event flag: IN_MOVE
inotify event flag: IN_ISDIR
inotify event flag: IN_ALL_EVENTS
event IN_MOVED_FROM: target/5epTJHm7BdsGdFUUPPqUQh3q7051hvEE
inotify path event for: random_files/5epTJHm7BdsGdFUUPPqUQh3q7051hvEE
inotify event wd: 2
inotify event mask: 1073741952
inotify event cookie: 102104
inotify event len: 48
inotify event name: 
inotify event flag: IN_MOVED_TO
inotify event flag: IN_MOVE
inotify event flag: IN_ISDIR
inotify event flag: IN_ALL_EVENTS
event IN_MOVED_TO: random_files/5epTJHm7BdsGdFUUPPqUQh3q7051hvEE
Monitor directory: random_files/5epTJHm7BdsGdFUUPPqUQh3q7051hvEE
[M] Item moved: target/5epTJHm7BdsGdFUUPPqUQh3q7051hvEE -> random_files/5epTJHm7BdsGdFUUPPqUQh3q7051hvEE
Moving target/5epTJHm7BdsGdFUUPPqUQh3q7051hvEE to random_files/5epTJHm7BdsGdFUUPPqUQh3q7051hvEE
inotify path event for: target/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
inotify event wd: 6
inotify event mask: 1073741888
inotify event cookie: 102105
inotify event len: 48
inotify event name: 
inotify event flag: IN_MOVED_FROM
inotify event flag: IN_MOVE
inotify event flag: IN_ISDIR
inotify event flag: IN_ALL_EVENTS
event IN_MOVED_FROM: target/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
inotify path event for: random_files/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
inotify event wd: 2
inotify event mask: 1073741952
inotify event cookie: 102105
inotify event len: 48
inotify event name: 
inotify event flag: IN_MOVED_TO
inotify event flag: IN_MOVE
inotify event flag: IN_ISDIR
inotify event flag: IN_ALL_EVENTS
event IN_MOVED_TO: random_files/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
Monitor directory: random_files/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
[M] Item moved: target/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh -> random_files/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
Moving target/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh to random_files/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
^CGot termination signal, shutting down db connection
```

This shows that the folder & the associated files were moved from A -> B without issue when using `--monitor`

The moves that were done for the above were:
```
[alex@centos7full OneDrivePersonal]$ mv random_files/5epTJHm7BdsGdFUUPPqUQh3q7051hvEE ./target/
[alex@centos7full OneDrivePersonal]$ mv random_files/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh/ ./target/
[alex@centos7full OneDrivePersonal]$ mv target/5epTJHm7BdsGdFUUPPqUQh3q7051hvEE/ ./random_files/
[alex@centos7full OneDrivePersonal]$ mv target/8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh/ ./random_files/
```

The folder structure is:
```
[alex@centos7full OneDrivePersonal]$ tree -dl
.
├── random_files -> /home/alex/OneDrive/random_files/
│   ├── 5epTJHm7BdsGdFUUPPqUQh3q7051hvEE
│   └── 8HRVUKG7rbqgAh7kDFAg3PaTbC7rWSUh
├── random_images -> /home/alex/OneDrive/random_images/
├── random_videos -> /home/alex/OneDrive/random_videos/
└── target

6 directories
[alex@centos7full OneDrivePersonal]$ 
```

In *all* tests - the folder is moved from the old location to the new location, and the folders moved correctly online from old location to new location without being re-uploaded.

**Comment by abraunegg** [comment]
@ianmartinezhn 
I also suggest you update your client version from v2.4.1-X to v2.4.2 to ensure you are not impacted by any of the issues resolved (of which, this is not something that was a bug between v2.4.1 and v2.4.2)

**Comment by abraunegg** [comment]
@ianmartinezhn 
In order to look at this further I need the following:
* Verbose debug logs that capture the issue
* Reproduction steps that reliably 100% of the time reproduce this issue

**Comment by ianmartinezhn** [comment]
Hey abraunegg, thank again for the quick response. 

i got a lot of files in the drive, is there a way i can just monitor a specific folder without processing all the drive to send you the log files?

Is there a way to upgrade to 2.4.2 or do i need to reinstall?

**Comment by abraunegg** [comment]
@ianmartinezhn 
> i got a lot of files in the drive, is there a way i can just monitor a specific folder without processing all the drive to send you the log files?

No there is not. I test with a file base of ~65k files with ~5k folders .. I do not see this issue at all.
 
> Is there a way to upgrade to 2.4.2 or do i need to reinstall?

Best to refer to https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md

**Comment by abraunegg** [comment]
@ianmartinezhn 
Any update from you in regards to this issue?

**Comment by ianmartinezhn** [comment]
hey @abraunegg, sorry for the delay. 

**heres the use case: 
Original** 
> ian@ian-desktop:/mnt/data3/1Drive/Media/Movies/2020$ tree
> ├── 06 Happiness_3.mp4
> ├── 1568429120alarmdownloadcache.MP4
> ├── 49c29839-28db-48a2-8799-234c6e38468a.MP4
> ├── Call of Duty®_ Modern Warfare®_20200411161902.mp4
> ├── IMG_0598.MOV
> ├── IMG_7523.MOV
> ├── IMG_7524.MOV
> ├── IMG_7525.MOV
> ├── IMG_7527.MOV
> ├── IMG_7528.MOV
> ├── IMG_7529.MOV
> ├── IMG_7540.MOV
> └── test

**then used to mv IMG_7523.MOV to "test" folder**

> ian@ian-desktop:/mnt/data3/1Drive/Media/Movies/2020$ mv IMG_7523.MOV ./test/

> Uploading new items of .
> Uploading new file ./Media/Movies/2020/test/IMG_7523.MOV ... 
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:01:13      

after 

> ian@ian-desktop:/mnt/data3/1Drive/Media/Movies/2020$ tree
> .
> ├── 06 Happiness_3.mp4
> ├── 1568429120alarmdownloadcache.MP4
> ├── 49c29839-28db-48a2-8799-234c6e38468a.MP4
> ├── Call of Duty®_ Modern Warfare®_20200411161902.mp4
> ├── IMG_0598.MOV
> ├── IMG_7524.MOV
> ├── IMG_7525.MOV
> ├── IMG_7527.MOV
> ├── IMG_7528.MOV
> ├── IMG_7529.MOV
> ├── IMG_7540.MOV
> └── test
>     └── IMG_7523.MOV

Log send to support@mynas.com.au

**Comment by abraunegg** [comment]
@ianmartinezhn 
No log file has been received via email

As per previous advice - if you are using standalone sync mode (`--synchronize`) then this is 100% expected behavior as the client has no way to tracking file or folder move operations when the client is not running. 

With your output above:
* It is unclear what mode of operation you are running
* It is unclear if the file `IMG_7523.MOV` was previously in sync - as your information does not provide any evidence to support that it does, so uploading as per your output - is 100% normal

Also, as per the evidence I have provided when attempting to replicate your issue - file / folder moves when using monitor mode (`--monitor`) correctly moves the file / folder online without delete / re-upload of data.

As per my previous original request:
* Please can you provide the following:
  * Crystal clear reproduction steps
    * step 1 - start application with the following configuration
    * step 2 - file / folder upload & ensure that it is in sync
    * step 3 - file / folder move locally
    * step ...
  *  Verbose debug log following these directions that show your reproduction steps: https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

Right now - without any real evidence of the issue - except some log extracts above which, when taken in their individual context without any of the other supporting actions show that you are seeing a file upload - but nothing indicating as to why this is occurring.

Please can you provide the requested information so that:
* I can work out what is it that you are doing that is causing this
* Is this a bug & can this be fixed

I do not have the data from you to perform this analysis yet.

**Comment by ianmartinezhn** [comment]
Sorry, email got stuck trying to send the log...big file. 

Im using --monitor and i even wait a while before moving the files to make sure its synced.

step 1 - onedrive --monitor --verbose > debug_output.log 2>&1
step 2 - make sure everything its synced by renaming a folder in the cloud
step 3 - mv IMG_7523.MOV ./test/ locally

onedrive locally begins to upload file instead of moving.

Let me know if you got the log and need more information. 

thank in advance.

**Comment by abraunegg** [comment]
@ianmartinezhn 
email received now, however the log file provided is not a debug log, and does not show events of moving the file under '--monitor' mode - all the 'inotify' events are missing.

**Comment by abraunegg** [comment]
@ianmartinezhn 
After spending quite some time on this, this situation is a 'bug'. What is occurring is that a race condition happens when 'scanning the database' & 'scanning the local file system' and a move or delete operation occurs. 

Please can you evaluate the following PR which (in my testing) solves this issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/948/head:pr948
git checkout pr948
./configure; make clean; make;
```

When testing this version, your client version should be `onedrive v2.4.2-9-g8282bf6`

Please can you test and provide feedback.

**Comment by abraunegg** [comment]
@ianmartinezhn 
Any update in testing the PR?

**Comment by abraunegg** [comment]
@ianmartinezhn
Any update in testing the PR?
