### ISSUE TITLE
can't connect to my oneDrive account

### ISSUE THREAD

**Issue by bealinux** [abraunegg/onedrive#943]
When I try to authorize my oneDrive account I get this message when I copy the link from the browser back into terminal.
```
bea@boliver:~
$ onedrive
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=0.ASoAh2QPqA3yUEyxVMv8_O-6Kw2axCIc0pJHrtGPFjyYJUYqABw.AQABAAIAAAAm-06blBE1TpVMil8KPQ41YCJd6EaqY0AbhR5fHBEs9cJz865_iLnNZWEoi4UYzWqtVTSvr9goNPtfq57zqRqPTk8FOLvaLWNTqyAQNP2wfA1ivWpckfnawlaASjur1LK013C6opvp9nR0OjYtW7vR1UBm7HTmCKUyJOgImEx9p-Nd3cSpebn6yUVPG6GL0JD0Ldp911Wz-DmxdA3ucggn8nNodAs9ETL3tcvxOyijRYRw-qiJs4AAs7CmPpNLHHIqVHTInR8Uzypu6TFhy5D6Ozc0LCvIxwVzc-ZcHBtHi9xTLt6zpJc1v2RMSZP03fBs1yNpe18IoOHm4yHYmXTJ9MRtjmauxP7sF1gzq0sttL8jgnLK7xRW8BLDcq6fglWVikD5Mrf91Ahoz5Q8Lod-ij1kta1BYJhxPcn0GNKE4e73q_AwAm0XxnYH8RIsS6vmQJNBjn8PKbbpKzWafakDVtGLtreFHG3JE_3bp9SyfoBqVFWACQuEgZpculDTqk1qE05qNz6ClwNjytHJXJbdYVQhnWQxDU9dU2q3BR6jRzTddlV_w2fAvdjt_Dclz8PLTt_vrxYjiiAPoFD_L5t-8rq9B6HjyeIRmg5HORLNVemnje4f7nGJicLO8AI1dnwgAA&session_state=8b76834a-68f6-419f-8774-47bed691801a
onedrive.OneDriveException@src/onedrive.d(408): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "19fb435c-e7dc-4012-b358-273f05e3d91a",
    "error": "invalid_grant",
    "error_codes": [
        9002313
    ],
    "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: 6c93d404-e1e7-47bb-b290-5080fa193a00\r\nCorrelation ID: 19fb435c-e7dc-4012-b358-273f05e3d91a\r\nTimestamp: 2020-05-30 22:58:24Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=9002313",
    "timestamp": "2020-05-30 22:58:24Z",
    "trace_id": "6c93d404-e1e7-47bb-b290-5080fa193a00"
}
----------------Segmentation fault
```
The computer is a new install of Linix MX 19. I have done all the update and upgrades. I followed the installation steps on the FOSS Linux site.

Any suggestions on what I might be doing wrong?  I can log into my oneDrive account via FireFox and on my Windows computer.

**Comment by abraunegg** [comment]
@bealinux 

Please can you follow the correct process to report issues - https://github.com/abraunegg/onedrive#reporting-issues

Whilst you are seeing a crash, you are following directions from online sources which are **known** to be incorrect. I have tried many times to get these website(s) updated / corrected.

The above issue 100% sounds like you have installed older code. As you have not provided any details on *how* you installed the application, I can only assume here that you have installed either via an old package for MX Linux or somehow followed some direction to install the 'skilion' code in error. On checking the [FOSS Linux site](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md) - it is directing you to install the 'skilion' code base.

Please can you uninstall 'whatever' you have installed and follow the directions as per https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md amending them as required for MX Linux.

**Comment by bealinux** [comment]
my apology for posting this in the wrong area. I did not see an area to post a problem such as mine. Thanks for helping any way.

**Comment by abraunegg** [comment]
@bealinux 
You posted in the 'right' area :) your just following the 'wrong' process to install the client by a website that holds incorrect information.

Please follow the directions to install the client the right way, from the right source - and let me know if you run into any issues.

**Comment by abraunegg** [comment]
Closing issue as question answered, old code (skilion) version
