### ISSUE TITLE
Couldn't resolve host name on handle

### ISSUE THREAD

**Issue by bencgreen** [abraunegg/onedrive#949]
### Bug Report Details ###
**Describe the bug**
I'm not sure if it is a bug, it's a strange behaviour / message though - I have installed on a new machine (as it's working so well on the other!) and I've noticed this in the logs:
```
Cannot connect to Microsoft OneDrive Service
Reason: Couldn't resolve host name on handle 557D3C1FB440
```
Followed immediately by this:
```
Account Type: business
Default Drive ID: xx
Default Root ID: xx
Remaining Free Space: 2243560844519
```
Which suggests it **has** resolved the host name - and then it proceeds to work, monitoring the onedrive folder, uploading files, etc.  I have ufw enabled, but it is not blocking outgoing https requests - which is clear as it **is** able to connect to the onedrive service.

**Application and Operating System Details:**
*   OS: Linux server05 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 20.04)
*   Headless
*   Business
*   Docker container (alpine-v2.4.2) - Docker version 19.06.11
*   Application configuration: see below
*   Curl Version: (not found inside docker container)

```
Configuration file successfully loaded
onedrive version                       = v2.4.2
Config path                            = /onedrive/conf
Config file found in config path       = true
Config option 'check_nosync'           = true
Config option 'sync_dir'               = /root/OneDrive
Config option 'skip_dir'               = Old
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
I simply start the container, having already authorised it (successfully).

**Application Log Output (from `docker logs onedrive -f`)**
```bash
++ stat /onedrive/data -c %u
+ : 1000
++ stat /onedrive/data -c %g
+ : 1000
++ getent group 1000
+ odgroup=onedrive:x:1000
+ odgroup=onedrive
++ getent passwd 1000
+ oduser=onedrive:x:1000:1000::/home/onedrive:/bin/ash
+ oduser=onedrive
+ usermod -g onedrive onedrive
usermod: no changes
+ grep -qv root /dev/fd/63
++ groups onedrive
+ chown onedrive:onedrive /onedrive/ /onedrive/conf
# We are being verbose
# We are performing a --resync
+ ARGS=(--monitor --confdir /onedrive/conf --syncdir /onedrive/data)
+ '[' 1 == 1 ']'
+ echo '# We are being verbose'
+ ARGS=(--verbose ${ARGS[@]})
+ '[' 0 == 1 ']'
+ '[' 1 == 1 ']'
+ echo '# We are performing a --resync'
+ ARGS=(--resync ${ARGS[@]})
+ '[' 0 -gt 0 ']'
+ exec gosu onedrive /usr/local/bin/onedrive --resync --verbose --monitor --confdir /onedrive/conf --syncdir /onedrive/data
Using Config Dir: /onedrive/conf
Configuration file successfully loaded
Deleting the saved status ...
Cannot connect to Microsoft OneDrive Service
Reason: Couldn't resolve host name on handle 557D3C1FB440
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /onedrive/data
Application version: v2.4.2
Account Type: business
Default Drive ID: xxx
Default Root ID: xxx
Remaining Free Space: 2243560844519
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 300
Monitor directory: .
(cue rest of log listing directories to monitor, and then actually doing the resync)
```

**Additional context**
Like I said I'm not sure this is really a problem - things seem to be working as far as I can tell (I can see files being uploaded to onedrive), so I'm just checking that there isn't something I need to be aware of.

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output

**Comment by abraunegg** [comment]
@bencgreen 
Essentially this error is thrown when the 'test network' function is unable to access / query / resolve https://login.microsoftonline.com and perform a HTTP check.

Most likely in this instance the Docker container took longer than 5 seconds to resolve the URL .. network issue, DNS lookup issue. Once it was able to cache the DNS, the next queries were successful.

I suspect that this potentially has to do with Alpine Linux and the differences it has to other Linux platforms.

How 'reproducible' is this? 100% reproducible or this occurred just once and not again?

Technically this is also not a bug, as, the application handled the issue, did not crash and is also working as expected.

**Comment by bencgreen** [comment]
Yes it seems to happen when the host is restarted, or the container is rebuilt.  As long as that's all it is, I'm happy to leave it at that.
