### ISSUE TITLE
Build dependencies for Ubuntu 20.04

### ISSUE THREAD

**Issue by MithicSpirit** [abraunegg/onedrive#952]
**Is your feature request related to a problem? Please describe.**
There are no build dependencies for Ubuntu 20.04/20.x. The closest I found was [Ubuntu 19.x](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-ubuntu-18x-ubuntu-19x--debian-9-debian-10---x86_64).

**Describe the solution you'd like**
The build dependencies for Ubuntu 20.x should be present in [INSTALL.md](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md)

**Describe alternatives you've considered**
The Ubuntu 18.x, 19.x might also work in 20.x, but I don't want to try out of fear of breaking my system.

**Comment by abraunegg** [comment]
@MithicSpirit 
The dependencies are the same .. they would not change between 19.x and 20.x

**Comment by abraunegg** [comment]
Updated header reference for clarity (https://github.com/abraunegg/onedrive/commit/7275b2febb76d301bbd6b29c068f152171cc4a52)
