### ISSUE TITLE
Could not find any compatible D compiler

### ISSUE THREAD

**Issue by nttungqn** [abraunegg/onedrive#953]
I'm using Ubuntu 19.10 and when I run ./configure, I got an error. Please help me

> configure error: Could not find any compatible D compiler

**Comment by abraunegg** [comment]
@nttungqn 
Please follow the directions carefully as your dependencies are missing:
* [Build Requirements](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#build-requirements)
* [Ubuntu Dependencies](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-ubuntu-18x-ubuntu-19x-ubuntu-20x--debian-9-debian-10---x86_64)
* [Compile and Install](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#compilation--installation)

If this is too difficult, please refer to https://github.com/abraunegg/onedrive/issues/853 and https://launchpad.net/~yann1ck/+archive/ubuntu/onedrive

**Comment by abraunegg** [comment]
Closing issue as question answered

**Comment by yuusakuri** [comment]
I have the installation script for Ubuntu 2004 as below, but I get a similar error.
I will read and understand those documents. What am I missing?

```
    # Install dependencies
    sudo apt install -y build-essential
    sudo apt install -y libcurl4-openssl-dev
    sudo apt install -y libsqlite3-dev
    sudo apt install -y pkg-config
    sudo apt install -y git
    sudo apt install -y curl
    curl -fsS https://dlang.org/install.sh | bash -s dmd
    source "$(find ~/dlang -maxdepth 2 -mindepth 2 -name 'activate')"
    deactivate
    # Install OneDrive
    mkdir -p ~/apps
    cd ~/apps
    git clone https://github.com/abraunegg/onedrive.git
    cd onedrive
    ./configure
    make clean
    make
    sudo make install
```
