### ISSUE TITLE
inotify error - max number of watches

### ISSUE THREAD

**Issue by rednag** [abraunegg/onedrive#962]
Hi,

I did a resync on a new SSD and now I'm getting the following failure when I'm running the service.

The user limit on the total number of inotify watches has been reached.

```
Jun 23 09:17:26 flipper onedrive[8560]: sysctl fs.inotify.max_user_watches
Jun 23 09:17:26 flipper onedrive[8560]: To change the current max number of watches to 524288 run:
Jun 23 09:17:26 flipper onedrive[8560]: sudo sysctl fs.inotify.max_user_watches=524288
Jun 23 09:17:26 flipper onedrive[8560]: ERROR: inotify_add_watch failed: ./Docs/d/EC/RY4M3OKEWSMTKH3O3ZSRQLE55YUTNJ/_GnpY3Psh3tig6YqJmo3XCA6Tu8=.c9r
Jun 23 09:17:26 flipper onedrive[8560]: The user limit on the total number of inotify watches has been reached.
Jun 23 09:17:26 flipper onedrive[8560]: To see the current max number of watches run:
Jun 23 09:17:26 flipper onedrive[8560]: sysctl fs.inotify.max_user_watches
Jun 23 09:17:26 flipper onedrive[8560]: To change the current max number of watches to 524288 run:
Jun 23 09:17:26 flipper onedrive[8560]: sudo sysctl fs.inotify.max_user_watches=524288
Jun 23 09:17:26 flipper onedrive[8560]: ERROR: inotify_add_watch failed: ./Docs/d/EC/RY4M3OKEWSMTKH3O3ZSRQLE55YUTNJ/60ZHZgHCja8oFSFsy4BGb3JvWOAPxYyB.c9r
```

What's the matter? Thank you for your support :)

**Comment by abraunegg** [comment]
@rednag 
This means the number of files being watched has reached your 'default configured' limit. This limit is set by your OS provider. This is not an issue with this application.

As per the error message, you need to change your OS settings to a higher value. The value of `524288` is just an example.

To resolve this find out what it is set to:
```
sysctl fs.inotify.max_user_watches
```
Then count all files and folders in your configured 'sync_dir':
```
ls -laR | wc -l
```
Take that second value, double it or x4 or whatever, then:
```
sudo sysctl fs.inotify.max_user_watches=XXXXXXXX   <- this new value
```

**Comment by abraunegg** [comment]
Closing issue as question answered
