### ISSUE TITLE
can`t install - make problem

### ISSUE THREAD

**Issue by musarra** [abraunegg/onedrive#963]
### Bug Report Details ###
Following the steps in installation guide, error happens to make and could not perform installation.
below all commands and output.
I have done everything as required for:

System:  Kernel: 5.3.0-59-generic x86_64 bits: 64 
           compiler: gcc v: 7.5.0 Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM 
           Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
```
source ~/dlang/dmd-2.092.1/activate
(dmd-2.092.1)musarra@musarra-HP-EliteBook-820-G1: cd onedrive
(dmd-2.092.1)musarra@musarra-HP-EliteBook-820-G1: /onedrive ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.092.1
checking for curl... yes
checking for sqlite... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
(dmd-2.092.1)musarra@musarra-HP-EliteBook-820-G1:/onedrive make clean; make;
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
	git describe --tags > version ; \
else \
	echo v2.4.3-dev > version ; \
fi
dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
(dmd-2.092.1)musarra@musarra-HP-EliteBook-820-G1:~/onedrive sudo make install
password
/usr/bin/install -c -D onedrive /usr/local/bin/onedrive
/usr/bin/install -c -D onedrive.1 /usr/local/share/man/man1/onedrive.1
/usr/bin/install -c -D -m 644 contrib/logrotate/onedrive.logrotate /usr/local/etc/logrotate.d/onedrive
mkdir -p /usr/local/share/doc/onedrive
/usr/bin/install -c -D -m 644 README.md config LICENSE CHANGELOG.md docs/Docker.md docs/INSTALL.md docs/Office365.md docs/USAGE.md /usr/local/share/doc/onedrive
/usr/bin/install -c -d -m 0755 /usr/lib/systemd/user /lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive@.service /lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive.service /usr/lib/systemd/user
```

**Comment by abraunegg** [comment]
@musarra 
I do not see any error in your output.

Please can you clarify what your error / issue is - as everything above shows:
* You compiled successfully
* You installed successfully

**Comment by musarra** [comment]
You are right, I was able to sync later on with no problems.

Everything is working great.

Sorry for the precipitated post, I was getting some errors but sorted them
out.

Cheers.

**Comment by abraunegg** [comment]
@musarra 
No problem, will close this issue

**Comment by musarra** [comment]
but indeed, if I may, i found a small issue.

when I skip directories in config file, if I have a folder in my 'root'
with the same name of a folder inside other different folder within the
root, it does not sync.

for example:

OneDrive/numbers
OneDrive/example/numbers


if I skip directory  'numbers' the 'example/numbers' does not sync.

Which means, duplicated folder names with root folders are not possible...

**Comment by abraunegg** [comment]
@musarra 
This is a configuration issue: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#skip_dir

If your entry is:
```
skip_dir = "numbers"
```
This will skip all directories called 'numbers'

If you want to only skip '/example/numbers' , use:
```
skip_dir = "/example/numbers"
```
This will sync /numbers and skip /example/numbers


If you want to only skip '/numbers' , use:
```
skip_dir = "/numbers"
```
This will skip /numbers and sync /example/numbers

**Comment by musarra** [comment]
ahhh great and so simple...just a small '/'.

Thank you so much for the help ;)

Excellent job by the way with the onedrive sync client !

**Comment by musarra** [comment]
Hi there....one more question, is there a way to set up the 'on demand'
feature ?

thanks in advance,
cheers

**Comment by abraunegg** [comment]
@musarra 
> Hi there....one more question, is there a way to set up the 'on demand' feature ?

This is not supported. See: https://github.com/abraunegg/onedrive/issues/757
