### ISSUE TITLE
Error Message: Timeout was reached on handle

### ISSUE THREAD

**Issue by chhatch** [abraunegg/onedrive#964]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
After a fresh install of this appllication following the directions provided in the documents

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
    Linux Falchion 5.3.0-59-generic #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020 x86_64 
    x86_64 x86_64 GNU/Linux

*   Are you using a headless system (no gui) or with a gui installed?
    Gui installed

*   OneDrive Account Type
    Personal

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
    dmd-2.092.1

*   Application configuration: Output of `onedrive --display-config`
```
    onedrive version                       = v2.4.2-19-g650cb97
    Config path                            = /home/cj/.config/onedrive
    Config file found in config path       = false
    Config option 'check_nosync'           = false
    Config option 'sync_dir'               = /home/cj/OneDrive
    Config option 'skip_dir'               = 
    Config option 'skip_file'              = ~*|.~*|*.tmp
    Config option 'skip_dotfiles'          = false
    Config option 'skip_symlinks'          = false
    Config option 'monitor_interval'       = 300
    Config option 'min_notify_changes'     = 5
    Config option 'log_dir'                = /var/log/onedrive/
    Config option 'classify_as_big_delete' = 1000
    Config option 'sync_root_files'        = false
    Selective sync configured              = false
```
*   Curl Version: Output of `curl --version`
    7.58.0

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Install onedrive following the directions in this repo
2. Run command `onedrive`
3. Authorize app

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Application Log Output:
```bash
~/bin/onedrive$ onedrive --synchronize --verbose
Using 'user' Config Dir: /home/cj/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d50ca740-c83f-4d1b-b616-12c519384f0c&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.Read.All%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=M13b9a72f-b874-c102-e606-511c7e6da82b
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 561CFF7CF800
Opening the item database ...
All operations will be performed in: /home/cj/OneDrive
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 561CFF7CF800
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 561CFF7CF800
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 561CFF7CF800
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 561CFF7CF800
ERROR: Unable to query OneDrive to initialize application
```

**Additional context**
The application was working correctly until I started getting the following error: 
```ERROR: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?```
This error lasted for weeks. I kept thinking it was a problem with Microsoft that would resolve itself eventually I decided to completely remove the program and perform a fresh install. This is a newer version of the app than I had before, so this really might be the same error I was getting before just with a different message.
Also, the error message, 
```
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle xxxxxxxxxxxx
```
,seems to show a different handle id each time.

### Bug Report Checklist ###
*   [X] Detailed description
*   [x] Reproduction steps (if applicable)
*   [X] Verbose Log Output

**Comment by abraunegg** [comment]
@chhatch 
This error is indicative of Internet access / HTTPS being blocked.

You need to:
* Check your firewall rules on your system
* Check your firewall rules (if any) on your router / firewall / Internet access device
* Speak to your ISP or workplace if they might be blocking access

**Comment by chhatch** [comment]
Thank you for the response. I checked the firewall on my machine with ```$ sudo ufw status```. It is not active. I verified that there isn't anything being blocked by the router. Instead of getting in touch with my ISP because that could take a long time, I signed into OneDrive in Windows running in a virtual machine; it started syncing right away. So, it seems like I can contact their servers.

I ran ```$ onedrive --synchronize``` again before coming back and asking for more guidance, and it's syncing now. It seems pretty odd that it worked just after I signed into OneDrive in Windows, but it could just be a coincidence. If this problem pops up again and signing into OneDrive in Windows resolves it I'll be sure to come back and let you know.

Thanks again for your help and the app!

**Comment by abraunegg** [comment]
@chhatch 
> I signed into OneDrive in Windows running in a virtual machine; it started syncing right away.

So here is your clue. Something on your system is preventing resolution somehow, and by using a virtual machine to login, allowed that resolution to occur, thus, the client was now able to resolve.

As you are running Ubuntu, I suggest that you diagnose this further with Ubuntu support.

**Comment by abraunegg** [comment]
Closing issue as not an issue with this client
