### ISSUE TITLE
run as systemd service fails

### ISSUE THREAD

**Issue by gilsedawk** [abraunegg/onedrive#967]
nevermind, i used the wrong unit file

**Comment by abraunegg** [comment]
@gilsedawk 
Unsure what documentation you were following, as the is the following in the usage.md:
* https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-a-non-root-user-via-systemd-without-notifications-or-gui
* https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-a-non-root-user-via-systemd-with-notifications-enabled-arch-ubuntu-debian-opensuse-fedora

If the above is not clear, please submit a PR to update the documentation.
