### ISSUE TITLE
Unable to sync shared folders? `onedrive --list-shared-folders` produces an unknown option error. 

### ISSUE THREAD

**Issue by joanimato** [abraunegg/onedrive#976]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**

I'm following the instructions here:https://github.com/abraunegg/onedrive/blob/master/docs/BusinessSharedFolders.md to sync a shared folder in my account, but the commands given there don't seem to be valid. 

For example, when I type `onedrive --list-shared-folders`,  I get an "unrecognizable option" error. 

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
     
`Linux pop-os 5.4.0-7634-generic #38~1592497129~20.04~9a1ea2e-Ubuntu SMP Fri Jun 19 22:43:37 UTC  x86_64 x86_64 x86_64 GNU/Linux`

*   Are you using a headless system (no gui) or with a gui installed?

I didn't even know there was a gui

*   OneDrive Account Type

Business/University

*   Did you build from source or install from a package?

From source

*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`

`DMD64 D Compiler v2.092.0`

*   Application configuration: Output of `onedrive --display-config`

`
onedrive version                       = v2.4.2-8-g46c91ba

Config path                            = /home/jmhimara/.config/onedrive

Config file found in config path       = false

Config option 'check_nosync'           = false

Config option 'sync_dir'               = /home/jmhimara/OneDrive

Config option 'skip_dir'               = 

Config option 'skip_file'              = ~*|.~*|*.tmp

Config option 'skip_dotfiles'          = false

Config option 'skip_symlinks'          = false

Config option 'monitor_interval'       = 300

Config option 'min_notify_changes'     = 5

Config option 'log_dir'                = /var/log/onedrive/

Config option 'classify_as_big_delete' = 1000

Config option 'sync_root_files'        = false

Selective sync configured              = true
`

*   Curl Version: Output of `curl --version`

curl 7.68.0

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by joanimato** [comment]
Never mind -- I think I'm one version behind the latest release

**Comment by joanimato** [comment]
Fixed after updating to knew version

**Comment by abraunegg** [comment]
@joanimato 
Correct - any version < v2.4.3 does not include support for syncing business shared folders
