### ISSUE TITLE
The parent item is not in the local database

### ISSUE THREAD

**Issue by cyberblitz** [abraunegg/onedrive#98]
I have been trying to rectify this issue for days now but can't overcome the issue I am having. I have followed all suggestions on this forum to no avail:

this is the error:

```
 Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
The parent item is not in the local database
Syncing changes from OneDrive ...
The parent item is not in the local database
Syncing changes from OneDrive ...
object.Exception@src/sync.d(1091): The parent item is not in the local database
----------------
/usr/include/dmd/phobos/std/exception.d:515 pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, scope const(char)[]) [0xeadcabda]
??:? pure @safe bool std.exception.enforce!().enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0xeae5e031]
src/sync.d:1091 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0xeae39845]
src/sync.d:993 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xeae38fd2]
src/sync.d:984 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xeae38ec9]
src/sync.d:984 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xeae38ec9]
src/sync.d:984 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xeae38ec9]
src/sync.d:984 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xeae38ec9]
src/sync.d:984 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xeae38ec9]
src/sync.d:984 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xeae38ec9]
src/sync.d:984 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xeae38ec9]
src/sync.d:723 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0xeae37c31]
src/main.d:392 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0xeae1bf33]
```

**Comment by abraunegg** [comment]
Please can you provide the application version your using

**Comment by cyberblitz** [comment]
You respond quickly :)

Ok. What would be the best command/s to remove onedrive, just so I'm not doing something wrong here or missing something?

**Comment by abraunegg** [comment]
Either using sudo or as a root user:

`find / | grep 'onedrive'`

That should tell you where every onedrive file / folder is so you can check against where you think things should be

**Comment by cyberblitz** [comment]
I suspected you were going to suggest this route ;) Just wanted to be thorough. I'll let you know how I get on.

**Comment by cyberblitz** [comment]
That did it. I had to reboot the server to remove some system files related to onedrive and start with a clean onedrive account (for some reason when installing fresh it doesn't have a record on whats on the onedrive account and doesn't download anything). Anyway it seems to be working for now

**Comment by abraunegg** [comment]
Old 'skilion' versions and database hanging around is indicative of your original issue. Glad it is resolved now for you. 

If fully resolved can you close this case?
