### ISSUE TITLE
Maximum file size limitations

### ISSUE THREAD

**Issue by m4teh** [abraunegg/onedrive#988]
### Bug Report Details ###
Onedrive should accept files up to 100GB as of July 1 2020 - https://www.microsoft.com/en-us/microsoft-365/blog/2020/07/01/introducing-new-onedrive-features-to-share-and-collaborate-across-work-and-life/

Are file size limitations enforced at a local client level? 20GB file is failing.

**Application and Operating System Details:**
*   OS: Fedora 30
*   OneDrive Account Type - Personal
*   Built from source
*   dmd-2.092.1
*   Application configuration: Output of `onedrive --display-config`
*   Curl Version: Output of `curl --version`

```bash
onedrive version                       = v2.4.3-6-ge23e063
Config path                            = /home/user/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/user/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

**Comment by abraunegg** [comment]
@m4teh 
Thanks for reporting this.

Please can you help validate the following PR to resolve this issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/989/head:pr989
git checkout pr989
./configure; make clean; make;
```

**Comment by m4teh** [comment]
Upload hasn't yet finished, but definitely seems to be working as 
expected! Brilliant

**Comment by abraunegg** [comment]
PR merged into 'master'
