### ISSUE TITLE
Fish Shell completition

### ISSUE THREAD

**Issue by SchoolGuy** [abraunegg/onedrive#990]
**Is your feature request related to a problem? Please describe.**
Currently we have only completitions for bash and zsh. Fish is also a popular shell which is actively developed and used.

**Describe the solution you'd like**
Fish completion for onedrive.

**Describe alternatives you've considered**
Well it is binary. To have it or not.

**Additional context**
None to add.

**Comment by abraunegg** [comment]
@SchoolGuy 
Given that I have no experience with that shell, will have to let someone who is more familiar with it develop a PR for that.

**Comment by OkeyDokeyGnocchi** [comment]
#991 
I took a crack at this and added a pull request.  Let me know if there are any changes, edits, additions, etc. that you'd like.

**Comment by abraunegg** [comment]
@OkeyDokeyGnocchi 
Many thanks :)

@SchoolGuy
Can you help validate this PR ?

**Comment by abraunegg** [comment]
@OkeyDokeyGnocchi 
Many thanks - validated and merged into 'master'

**Comment by OkeyDokeyGnocchi** [comment]
@abraunegg 
Happy to help :)
