### ISSUE TITLE
Feature Request: Create a Snap package

### ISSUE THREAD

**Issue by felipecrs** [abraunegg/onedrive#993]
Originally started on https://github.com/abraunegg/onedrive/issues/853#issuecomment-633023826.

With the Snap packages, users would be able to use this client without having to manually compile it. And it would work in any Linux distribution.

**Comment by abraunegg** [comment]
@felipecassiors 
Feel free to develop the snap package and become maintainer for that functionality as I have no desire to do that myself.

PR's are welcome.

**Comment by yann1cks** [comment]
@felipecassiors Its great that you are building a Snap! Just a little addition from my side. You could also do snap packing on Launchpad. I am not sure if you looked into this option and if it's really easier.

**Comment by abraunegg** [comment]
Closing this feature request for the following reason:
* Blocked by Snap Team for folder / permissions issue
