### ISSUE TITLE
Multiple accounts (one business, one personal)

### ISSUE THREAD

**Issue by danwdart** [abraunegg/onedrive#996]
**Is your feature request related to a problem? Please describe.**
I can only synchronize/login to one account at a time.

**Describe the solution you'd like**
Could we get a --config option to switch profile or similar - or even add two accounts at the same time to the same profile and get them both synchronised?

**Describe alternatives you've considered**
Maybe updating $HOME, or another var or using another account it uses might do it for now but it's dirty.

**Additional context**
One business account, one personal account.

**Comment by norbusan** [comment]
Please use `--confdir DIR` for this. Closing this issue.

**Comment by danwdart** [comment]
ahh, that's what it is, thanks!

**Comment by danwdart** [comment]
Oh, by the way, will the daemons pick that up? And if not, how do I tell them? Ta!

**Comment by norbusan** [comment]
What do you mean with daemons? If you start onedrive in daemon mode with the argument, it will use it
```
onedrive --confdir .... --monitor
```

If you are talking about systemd services, then you need to create **new** services by copying the current service file (either the `onedrive@.service` or the `onedrive.service` in the user dir) and update it to contain the different command line options. There is no simple way to start **multiple** daemons from one service file in systemd.

**Comment by abraunegg** [comment]
Additionally please read: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#using-multiple-onedrive-accounts

**Comment by danwdart** [comment]
Ahh, cool. I meant systemctl btw.

**Comment by danwdart** [comment]
Alright thanks!

**Comment by abraunegg** [comment]
> Ahh, cool. I meant systemctl btw.

Please read the above provided link for those details.
